### ISSUE TITLE
unicode parameters on pyodbc -> unixodbc -> freetds

### ISSUE THREAD

**Issue by ghost** [mkleehammer/pyodbc#1]
I am using Ubuntu 9.04

I have installed the following package versions:

    unixodbc and unixodbc-dev: 2.2.11-16build3
    tdsodbc: 0.82-4
    libsybdb5: 0.82-4
    freetds-common and freetds-dev: 0.82-4

I have configured /etc/unixodbc.ini like this:

    [FreeTDS]
    Description             = TDS driver (Sybase/MS SQL)
    Driver          = /usr/lib/odbc/libtdsodbc.so
    Setup           = /usr/lib/odbc/libtdsS.so
    CPTimeout               = 
    CPReuse         = 
    UsageCount              = 2

I have configured /etc/freetds/freetds.conf like this:

    [global]
        tds version = 8.0
        client charset = UTF-8
  
I have grabbed pyodbc revision 31e2fae4adbf1b2af1726e5668a3414cf46b454f from http://github.com/mkleehammer/pyodbc and installed it using "python setup.py install"

I have a windows machine with Microsoft SQL Server 2000 installed on my local network, up and listening on the local ip address 10.32.42.69. I have an empty database created with name "Common". I have the user "sa" with password "secret" with full priviledges.

I am using the following python code to setup the connection:

    import pyodbc
    odbcstring = "SERVER=10.32.42.69;UID=sa;PWD=secret;DATABASE=Common;DRIVER=FreeTDS"
    con = pyodbc.connect(s)
    cur = con.cursor()
    cur.execute('''
    CREATE TABLE testing (
        id INTEGER NOT NULL IDENTITY(1,1), 
        name NVARCHAR(200) NULL, 
        PRIMARY KEY (id)
    )
        ''')
    con.commit()

Everything WORKS up to this point. I have used SQLServer's Enterprise Manager on the server and the new table is there. Now I want to insert some data on the table.

    cur = con.cursor()
    cur.execute('INSERT INTO testing (name) VALUES (?)', (u'áéí',))

That fails!! Seems like pyodbc won't accept a unicode object. Here's the error I get:

    pyodbc.Error: ('HY004', '[HY004] [FreeTDS][SQL Server]Invalid data type (0) (SQLBindParameter)'

Since my freetds client is configured to use UTF-8 as above, I thought I could solve by encoding data to UTF-8. That gives no error, but then I get back strange data when I query. pyodbc returns unicode strings, and decoded with the wrong encoding so the chars are wrong.

If I can't insert an unicode string, why do I get those back? And wrong?

**Comment by mkleehammer** [comment]
If you use the default unixODBC build (2-byte UCS2) this should now work on 3.0.10 (not built yet).  Can you try the master branch and confirm?
