### ISSUE TITLE
Select statement that returns a single column is returning a list of lists with one element of the nested list being blank

### ISSUE THREAD

**Issue by TimothyBramlett** [mkleehammer/pyodbc#100]
I have some Python code that queries an MS SQL server for data.  When I select multiple columns in the sql query the dataset comes back as expected.  A list of rows (lists) with each element populated correctly:

(3.625, 'foo')
(3.7, 'foo')
(3.75, 'foo')
(3.8, 'foo')
(3.875, 'foo')
(3.95, 'foo')
(3.99, 'foo')
(4.0, 'foo')
(4.05, 'foo')
(4.125, 'foo')
(4.2, 'foo')

The problem comes when I try to just select one column, I get:

(3.625, )
(3.7, )
(3.75, )
(3.8, )
(3.875, )
(3.95, )
(3.99, )
(4.0, )
(4.05, )
(4.125, )
(4.2, )

A list of rows (lists) with an extra blank element.  I am using the cursor.fetchall() method to get the results from my cursor.

What causes this behavior and is there a better way to get the column I need other than looping through the list and just getting the first first element?

**Comment by keitherskine** [comment]
I suspect those are just single element tuples.  Rows returned by pyodbc are tuple-like (see http://mkleehammer.github.io/pyodbc/api.html#row) and what you're seeing I believe is simply the textual representation of those tuples.  Check the length of each row with len() and I think you'll find there is only one element in each row.

**Comment by TimothyBramlett** [comment]
Nice!  You are totally right.  They are like single element tuples which is why it is printing like that.  Thanks for the help!
