### ISSUE TITLE
Unable to pass limit as parameter for oracledb

### ISSUE THREAD

**Issue by Ashwani001** [mkleehammer/pyodbc#1007]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8 (64bit)
- pyodbc: 4.0.32
- OS: Windows
- DB: Oracle
- driver: NatezzaSQL

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

I'm unable to pass limit as a parameter.
`cursor.execute('select * from students where name=? limit 10','ash')` works.
But both
`cursor.execute('select * from students where name=? limit ?,'ash',10) ` and
`cursor.execute('select * from students where name=? limit ?',('ash',10))`
do not work, what gets executed is `'select * from students where name=NULL limit NULL'`.
I've tried passing 10 as a string and float to no avail.

**Comment by v-chojas** [comment]
Could you post an ODBC trace?

This seems like it might be an ODBC driver limitation. It's not unusual for a driver to not support parameterising arbitrary parts of queries.
