### ISSUE TITLE
Cannot use four byte unicode

### ISSUE THREAD

**Issue by burnsba** [mkleehammer/pyodbc#102]
When I try to use a four byte unicode string I get this exception:

    import pyodbc
    cs = 'DRIVER=MSSQL;SERVER=%s;PORT=1433;UID=%s;PWD=%s;DATABASE=%s;TDS_Version=7.2' \
                    % ('server', 'user', 'password', 'database')
    conn = pyodbc.connect(cs)
    cursor = conn.cursor()
    r = cursor.execute('INSERT INTO Table (Column) VALUES (?)', (u'a\U0001f185c'))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: Cannot convert from Unicode 127365 to SQLWCHAR.  Value is too large.

Followed [this guide](http://codesynthesis.com/~boris/blog/2011/12/02/microsoft-sql-server-odbc-driver-linux/) to install msodbcsql driver v11, using unixODBC-2.3.2 built from source with:  

    ./configure --enable-gui=no --enable-stats=no \
     --enable-drivers=no --enable-iconv --with-iconv-char-enc=UTF8 \
    --with-iconv-ucode-enc=UTF16LE --libdir=/usr/lib/x86_64-linux-gnu \
    --prefix=/usr --sysconfdir=/etc

    $ cat /etc/odbcinst.ini
    [MSSQL]
    Description=Microsoft ODBC Driver 11 for SQL Server
    Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-11.0.so.2270.0
    Threading=1
    UsageCount=1

**Comment by mkleehammer** [comment]
Since this is Unicode related, I'm going to link to #112 which will allow different encodings over the wire.

**Comment by mkleehammer** [comment]
Actually, I'm going to close this since I believe that #112 will fix it.  Please subscribe to that issue for updates.  Thanks.

**Comment by adrinjalali** [comment]
Does #112 actually fix this?

Since [here](https://github.com/mkleehammer/pyodbc/blob/3a2fe35e6b486f100418c5cccb98921737f4a4a4/src/sqlwchar.h#L12) the char size is defined as max 2, unicode characters requiring more than 2 bites will be doomed, resulting in errors like [this](https://github.com/michiya/django-pyodbc-azure/issues/62) one. I think they might be different issues.
