### ISSUE TITLE
[ODBC Driver 17 for SQL Server] Unsupported cast of parameter data to text/ntext with collation 'Latin1_General_100_BIN2_UTF8'.

### ISSUE THREAD

**Issue by jdhowroyd** [mkleehammer/pyodbc#1021]
**Environment**

Ubuntu: 20.04.2 LTS amd64
Python: 3.8.2-0ubuntu2 amd64
pyodbc: 4.0.32
driver: ODBC Driver 17 for SQL Server (msodbcsql17) 17.8.1.1-1 amd64
database: Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64) Enterprise Edition
running on: Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) / ESXi VMWare

**Issue**

Parameterised queries raise pyodbc.ProgrammingError: 

> ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot convert to text/ntext or collate to 'Latin1_General_100_BIN2_UTF8' because these legacy LOB types do not support UTF-8 or UTF-16 encodings. Use types varchar(max), nvarchar(max) or a collation which does not have the _SC or _UTF8 flags. (4189) (SQLParamData)") 

when string data exceeds 2000 characters and the database collation is utf8 encoded.

Looks like an underlying issue with the driver.

**Example code**

Attached.
[mssql_test.py.gz](https://github.com/mkleehammer/pyodbc/files/7972467/mssql_test.py.gz)

Further details in the doc string!

**Comment by v-chojas** [comment]
https://github.com/mkleehammer/pyodbc/issues/835
Use setinputsizes() to send as varchar(max).

**Comment by jdhowroyd** [comment]
Thanks for pointing me to the earlier post (and apologies for raising what is essentially the same issue).  I confirm that the use of cursor.setinputsize([(pyodbc.SQL_VARCHAR, 0, 0), ]) fixes the issue in the example code (or SQL_WVARCHAR or both).  Clearly, a more complex issue deeper down.

**Comment by gordthompson** [comment]
Alternative to using `setinputsizes()`

https://github.com/mkleehammer/pyodbc/issues/835#issuecomment-1047228743

**Comment by alexey-formalmethods** [comment]
> Thanks for pointing me to the earlier post (and apologies for raising what is essentially the same issue). I confirm that the use of cursor.setinputsize([(pyodbc.SQL_VARCHAR, 0, 0), ]) fixes the issue in the example code (or SQL_WVARCHAR or both). Clearly, a more complex issue deeper down.
> cursor.setinputsizes([(po.SQL_VARCHAR, 0, 0), (po.SQL_WVARCHAR, 0, 0), (po.SQL_CHAR, 0, 0), (po.SQL_WCHAR, 0, 0)])
works for me on Mac M2, thx

**Comment by alexey-formalmethods** [comment]
works for me on Mac M2, thx

> Thanks for pointing me to the earlier post (and apologies for raising what is essentially the same issue). I confirm that the use of cursor.setinputsize([(pyodbc.SQL_VARCHAR, 0, 0), ]) fixes the issue in the example code (or SQL_WVARCHAR or both). Clearly, a more complex issue deeper down.
