### ISSUE TITLE
Cursors don't work when passed as parameters to another module inside a wrapper object

### ISSUE THREAD

**Issue by rgargente** [mkleehammer/pyodbc#103]
Consider the class:

    class CHolder:
        def __init__(self, cursor):
            self.cursor = cursor

        def __del__(self):
            print("die")

If we create an instance of this class with a cursor, and pass the holder to a function in another module, the cursor won't work:

    c = pyodbc.connect(connection_string, timeout=3)
    ch = CHolder(c.cursor())
    ch.cursor.execute("""INSERT .... # Insert some rows
    someothermodule.bad_function(ch) # We won't be able to read those rows
    someothermodule.good_function(ch.cursor) # We will be able to read those rows

The cursor used inside some_function won't work. It will apparently execute queries succesfully but will not get any result that is uncommitted. In the example above, the rows inserted won't be visible by selects executed inside bad_function, but they are visible by selects executed inside good_function.

I guess it might have something to do with the cursor going out of scope at some moment and being incorrectly closed.

The workaround is obviously using functions like good_function but I don't think the behaviour in bad_function is correct.

**Comment by woodlandhunter** [comment]
Can you post a runnable example?

**Comment by rgargente** [comment]
How would you suggest me to do that without having a database? It's not just as easy as posting the python code... 
Thank you

**Comment by woodlandhunter** [comment]
Use a temporary table for the query and a placeholder for a connection string. Anyone triaging can substitute their own connection string or otherwise handle making sure `connect()` succeeds for testing.

**Comment by rgargente** [comment]
Sorry for not replying earlier. I will do it hopefully soon

**Comment by mkleehammer** [comment]
I do this a lot so I am quite sure it works generally.  I'm going to close it for now but feel free to supply your example and we'll make sure.
