### ISSUE TITLE
Can't use the latest mysql drivers

### ISSUE THREAD

**Issue by bucknerns** [mkleehammer/pyodbc#1034]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.9.7
- pyodbc: 4.0.32
- OS:  Ubuntu 20.04
- DB: Mysql
- driver: 8.0.21 - 8.0.28

### Issue
Drivers 8.0.21 - 8.0.28 cause the error in this ticket 

https://github.com/mkleehammer/pyodbc/issues/1011

**Comment by bucknerns** [comment]
isql works fine

**Comment by bucknerns** [comment]
Same problem with fedora.

**Comment by v-chojas** [comment]
This seems like something you should ask the driver vendor about.

**Comment by gordthompson** [comment]
I am unable to reproduce your issue. After setting up the MySQL APT repository using the .deb file from …

https://dev.mysql.com/downloads/repo/apt/

… I installed MySQL Connector/ODBC via

```
sudo apt install mysql-connector-odbc
```

and this code works fine for me:

```python
import pyodbc

cnxn = pyodbc.connect(
    "DRIVER=MySQL ODBC 8.0 ANSI Driver;"
    "SERVER=192.168.0.199;"
    "UID=scott;PWD=tiger;"
    "DATABASE=test;"
)
print(f"Connected with driver version {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}")
# Connected with driver version 08.00.0028
```

**Comment by bucknerns** [comment]
If the connection is made once before importing protobuf, then the rest of the connections work fine.

**Comment by gordthompson** [comment]
Okay, so I am able to reproduce the issue with MySQL Connector/ODBC and protobuf

```python
from google.protobuf.pyext import _message

import pyodbc

conn_str = (
    "DRIVER=MySQL ODBC 8.0 ANSI Driver;"
    "SERVER=192.168.0.199;"
    "UID=scott;PWD=tiger;"
    "DATABASE=test;"
    "charset=utf8mb4;"
)
cnxn = pyodbc.connect(conn_str)
print(f"Connected with driver version {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}")
```

> pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/lib/x86_64-linux-gnu/odbc/libmyodbc8a.so' : file not found (0) (SQLDriverConnect)")

and commenting out the first (protobuf) import avoids the error. However, the same test with ODBC Driver 17 for SQL Server does not throw the error

```python
from google.protobuf.pyext import _message

import pyodbc

conn_str = (
    "DRIVER=ODBC Driver 17 for SQL Server;"
    "SERVER=192.168.0.199;"
    "UID=scott;PWD=tiger^5HHH;"
    "DATABASE=test;"
)
cnxn = pyodbc.connect(conn_str)
print(f"Connected with driver version {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}")
```

so it is an issue the the MySQL driver, not pyodbc.

**Comment by gordthompson** [comment]
> works fine with the mysql python connector and it uses the same odbc driver

That is not quite true. MySQL Connector/Python and MySQL Connector/ODBC may ultimately use the same MySQL C API, but MySQL Connector/Python does not use an ODBC driver *per se*.
