### ISSUE TITLE
Segmentation fault when I tried to connect with MySQL driver

### ISSUE THREAD

**Issue by Hema-Mathiyazhagan** [mkleehammer/pyodbc#1036]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: Python 3.6.8
- pyodbc: 4.0.32
- OS: RedHat 8.5
- DB: MySQL
- driver:MySQL ODBC driver

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
I tried to connect with MySQL db in my system.
```
con = pyodbc.connect("DRIVER={MySQL ODBC 8.0 ANSI Driver};SERVER=127.0.0.1;DATABASE=SYSTEM;UID=ADMIN;PASSWORD=password");
```
But I got ```Segmentation fault (core dumped)```

can anyone please help? Thanks in advance.

**Comment by gordthompson** [comment]
I am unable to reproduce your issue using Oracle Linux 8.5, which is the closest thing I have to RedHat. I installed MySQL Connector/ODBC using

mysql-connector-odbc-8.0.28-1.el8.x86_64.rpm

from the MySQL Connector/ODBC downloads page.

**Comment by Hema-Mathiyazhagan** [comment]
I could reproduce the issue only with the latest version of pyodbc(4.0.32). Downgrading to 4.0.30 helped solving the issue.

**Comment by gordthompson** [comment]
Okay, thanks for the follow-up.
