### ISSUE TITLE
"Converting decimal loses precision" error with fast_executemany = True

### ISSUE THREAD

**Issue by nenkie** [mkleehammer/pyodbc#1038]
### Environment

- Python:  3.8.10
- pyodbc:  pyodbc 4.0.32
- OS:  Win7 x66
- DB: MSSQL Server + Aurora DB (MySQL)
- driver: {ODBC Driver 17 for SQL Server} and {MySQL ODBC 8.0 Unicode Driver}

### Issue

Decimal columns cannot be transferred reading data from MS SQL Server and writing to MySQL (Aurora in my case) when `fast_executemany = True` for MySQL cursor. Making columns precision same or even wider on destination side doesn't give desired effect.
Setting `fast_executemany = False` resolved the issue.

`ProgrammingError('Converting decimal loses precision', 'HY000')`

If someone else can confirm, we can put another note on [Wiki](https://github.com/mkleehammer/pyodbc/wiki/Driver-support-for-fast_executemany)

**Comment by gordthompson** [comment]
As noted on the [wiki page](https://github.com/mkleehammer/pyodbc/wiki/Driver-support-for-fast_executemany), MySQL Connector/ODBC does not really support `fast_executemany = True`. The Unicode version of the driver is currently listed as "no effect", at least on Windows. However, the situation may be similar to the PostgreSQL ODBC case where we originally thought that `fast_executemany = True` had "no effect" but we recently learned that it actually caused the ODBC driver to drop fractional seconds for date/time values.

**Comment by gordthompson** [comment]
@nenkie 

> If someone else can confirm, we can put another note on [Wiki](https://github.com/mkleehammer/pyodbc/wiki/Driver-support-for-fast_executemany)

Confirmed:

```python
from decimal import Decimal

import pyodbc

cnxn = pyodbc.connect(
    "Driver=MySQL ODBC 8.0 Unicode Driver;"
    "Server=localhost;Port=3307;"
    "UID=scott;PWD=tiger;"
    "Database=test;"
)
print(cnxn.getinfo(pyodbc.SQL_DRIVER_VER))
# 08.00.0028

crsr = cnxn.cursor()
crsr.execute("drop table if exists decimal_table")
crsr.execute("create table decimal_table ( d decimal(18, 4) null )")

d = Decimal("3.14")
crsr.fast_executemany = True
crsr.executemany("INSERT INTO decimal_table VALUES (?)", [(d,), (d,)])
"""
pyodbc.ProgrammingError: ('Converting decimal loses precision', 'HY000')
"""
```

@v-chojas 

> Could you post an ODBC trace?

[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/8208633/SQL.LOG)

**Comment by v-chojas** [comment]
Looks like another driver bug. SQLDescribeParam on a decimal column claims that it's a varchar(255).
```
issue_1038      17c8-1e10	EXIT  SQLDescribeParam  with return code 0 (SQL_SUCCESS)
		HSTMT               0x000000EA49F5B2D0
		UWORD                        1 
		SWORD *             0x000000EA49D2B502 (12) <--- varchar?
		SQLULEN *           0x000000EA49D2B508 (255)
		SWORD *             0x000000EA49D2B510 (0)
		SWORD *             0x000000EA49A9F358 (2)
```

**Comment by gordthompson** [comment]
Wiki updated.

**Comment by dvanbolt** [comment]
Also having the issue

**Comment by SjoerdTimovanVliet** [comment]
Is ithe error resolved?

**Comment by gordthompson** [comment]
> Is ithe error resolved?

The issue has not been fixed in the latest version of MySQL Connector/ODBC (currently version 8.2).

The error can be avoided by using `.setinputsizes()`, e.g., 

```python
d = Decimal("3.14")
crsr.fast_executemany = True
crsr.setinputsizes([(pyodbc.SQL_DECIMAL, 18, 4)])
crsr.executemany("INSERT INTO decimal_table VALUES (?)", [(d,), (d,)])
cnxn.commit()
```

but you will likely find that the performance with `fast_executemany = True` is no better than with `fast_executemany = False` as noted in [the wiki](https://github.com/mkleehammer/pyodbc/wiki/fast_executemany-support-for-various-ODBC-drivers).

You will likely get much better insert performance with

```
pip install mysql-connector-python
```

Docs [here](https://dev.mysql.com/doc/connector-python/en/).

**Comment by aleewen** [comment]
I'm also having this problem in Nov 2024 with MSSQL and `fast_executemany=True`

**Comment by gordthompson** [comment]
@aleewen - Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by aleewen** [comment]
> @aleewen - Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

Temp table or regular table, same result. I'm on `pyodbc` v5.2.0 and my driver is `ODBC Driver 17 for SQL Server`
I can set the decimal value to be the exact precision and scale as the table column, but still no luck.

```python
conn = pyodbc.connect(connection_string)

cursor = conn.cursor()
cursor.fast_executemany = True

cursor.execute("CREATE TABLE #example_temp_table ( my_decimal DECIMAL(18, 10) NULL)")

d = Decimal("3.14")

cursor.executemany("INSERT INTO #example_temp_table VALUES (?)", [(d,), (d,)])

>>> ProgrammingError: ('Converting decimal loses precision', 'HY000')
```

**Comment by gordthompson** [comment]
Try adding `UseFMTONLY=yes` to your connection string.

**Comment by aleewen** [comment]
Looks like that worked. Thank you sir! 🫡

**Comment by aleewen** [comment]
Hi @gordthompson , I'm running into this issue again even when `UseFMTONLY=yes` in my connection string.
