### ISSUE TITLE
Inserting Decimal() type causes HY105 in 3.0.10

### ISSUE THREAD

**Issue by zyzhu2000** [mkleehammer/pyodbc#104]
Environment - Anaconda with python 2.7 and pyodbc 3.0.10 under Windows 10
inserting any value of Decimal type causes an ProgrammingError exception of HY105.

**Comment by mkleehammer** [comment]
What database are you using.  The SQL Server unit tests are working (tests2/sqlservertests.py).

**Comment by zyzhu2000** [comment]
I am using Microsoft SQL server 2012 personal edition.

**Comment by mkleehammer** [comment]
Can you run the sqlservertests.py file?

**Comment by zyzhu2000** [comment]
Will do tonight and report back

**Comment by mkleehammer** [comment]
Closing due to no more info.  Please reopen if you find anything.
