### ISSUE TITLE
How to use pyodbc via proxy eg Socks5.如何使用代理连接pyodbc比如socks代理

### ISSUE THREAD

**Issue by rootGH** [mkleehammer/pyodbc#1041]
- Python: 3.8
- pyodbc: latest
- OS: Windows10 64bit
- DB:mssql 2016
- driver:

**Comment by v-chojas** [comment]
Please be more specific and detailed in your question.

**Comment by rootGH** [comment]
> Please be more specific and detailed in your question.



> Please be more specific and detailed in your question.

I updated my question thanks

> Please be more specific and detailed in your question.

**Comment by rootGH** [comment]
> Please be more specific and detailed in your question.

I mean how to use proxy such as Socks5 in pyodbc

**Comment by v-chojas** [comment]
https://github.com/mkleehammer/pyodbc/discussions/1030
