### ISSUE TITLE
pyodbc.drivers() get empty array inside jupyter container

### ISSUE THREAD

**Issue by b-y-f** [mkleehammer/pyodbc#1048]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.9
- pyodbc: latest
- OS: ubuntu 20.04
- DB:mssql
- driver:

### Issue

Im using [this](https://hub.docker.com/r/jupyter/pyspark-notebook) notebook and tried to connect with remote MSSQL server, and ok with pip install pyodbc. But cannot connect to database and pyodbc.drivers() shows me empty [ ]

**Comment by gordthompson** [comment]
Have you installed the ODBC driver for SQL Server as described [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)?

**Comment by b-y-f** [comment]
Not sure, but in for other project in js with the help of [mssql](https://www.npmjs.com/package/mssql), we can connect to db without any issue.

**Comment by v-chojas** [comment]
Python is not JavaScript, and pyODBC is a generic ODBC interface. Please read [the documentation](https://github.com/mkleehammer/pyodbc/wiki).

**Comment by b-y-f** [comment]
I see. Thank you guys! 👍
