### ISSUE TITLE
 [Errno 13] Permission denied even I tried used  windows terminals with administrator privileges

### ISSUE THREAD

**Issue by Ken123456abcdefghijk** [mkleehammer/pyodbc#1051]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

Win10 21H2 Professional + VS 2015 CE
Python 3.10.4

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 
- pyodbc: 
- OS: 
- DB:
- driver:

### Issue

I tried to install pyodbc manually which I tried to install it with command 'python setup.py install'after I downloaded the codes, and tried to excuse it on  windows terminals with administrator privileges, it doesn't work, it always say "Permission denied", I totally have no clues

D:\opensourcelibrary\python\pyodbc-master>python setup.py install
fatal: Not a git repository (or any of the parent directories): .git
WARNING: git describe failed with: 128
WARNING: Unable to determine version.  Using 4.0.0.0
running install
C:\Users\redmond\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\redmond\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-7464.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

**Comment by Ken123456abcdefghijk** [comment]
any idea? any helps would be appreciated

**Comment by v-chojas** [comment]
That is an unusual place to install Python, check that you have write access to it? You can try installing somewhere else too.

**Comment by Ken123456abcdefghijk** [comment]
> That is an unusual place to install Python, check that you have write access to it? You can try installing somewhere else too.

thank you so much sir, really appeciated
