### ISSUE TITLE
/usr/local/lib/libtdsodbc.so Not Exists!

### ISSUE THREAD

**Issue by TianruiZhang** [mkleehammer/pyodbc#1052]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: python3.10.4
- pyodbc: 4.0.32
- OS: MacOS M1
- DB: Azure SQL Database
- driver: In the docker, I don't know

### Issue

I followed your instruction all along until odbcinst.ini and odbc.ini. `tsql -S MYMSSQL -U myuser -P mypassword` runs successfully .  I guess the problem lies here: 

```
[FreeTDS]
Description=FreeTDS Driver for Linux & MSSQL
Driver=/usr/local/lib/libtdsodbc.so
Setup=/usr/local/lib/libtdsodbc.so
UsageCount=1
```
In fact, I couldn't `/usr/local/lib/libtdsodbc.so` anywhere. By the way, I am using docker on my m1 MacBook Pro.

**Comment by v-chojas** [comment]
Make sure you install an ODBC driver first?

**Comment by TianruiZhang** [comment]
Yes, I installed both of them with `brew install unixodbc freetds `

**Comment by v-chojas** [comment]
You say you are using Docker. Did you install that on the host, or inside the container?

**Comment by TianruiZhang** [comment]
I installed that on my local machine and I think you have pointed out the problem. I'll try to connect to a remote db server from my m1 to see if there's any problem.
