### ISSUE TITLE
Python abnormal termination when connecting to AzureSQL and empty drivers list

### ISSUE THREAD

**Issue by marcozanella** [mkleehammer/pyodbc#1055]
Hi,

pyodbc.drivers() returns an empty list; and when trying to connect regardless, python simply terminates with no apparent error.

I can connect to the Azure SQL Database using both tsql and isql - so, it looks like I have correct odbcinst.ini and odic.ini
Although, before resetting to factory defaults this Mac, I could succeed to connect using mssql17 driver

- Python: 3.10 - installed via homebrew
- pyodbc: 4.0.32
- OS: OS X 12.3.1 monterey on M1
- DB: AzureSQL
- driver: mssql18

Expectation would be to connect using a sample script as follows:
`import pyodbc`
`pyodbc.connet('DRIVER={SQL18};SERVER= example.com; DATABASE= sample_db; UID=admin; PWD=password; Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;')`

**Comment by v-chojas** [comment]
Run `odbcinst -j` and check whether odbcinst.ini it refers to is empty?

> on M1

Make sure you are running consistently arm64 or x86 throughout, since those machines can run either x86 (with emulation) or arm64 binaries, but they don't mix in one process. If you have arm64 Python you cannot use x86 driver/DM and vice-versa.

**Comment by marcozanella** [comment]
@v-chojas , thanks for quick reply
odbcinst.ini is populated, and contains the correct data - I can use that via tsql

I can connect with tsql; so I think all is good between unixodbc, mssql18 driver, config files (ini) and the database.
Any insight how I could check if one component is ran or compiled for x86?

**Comment by v-chojas** [comment]
`python --version`

**Comment by marcozanella** [comment]
> python --version

Python 3.10.3

**Comment by v-chojas** [comment]
```
from platform import processor
processor()```

Run that in the python interactive prompt. What does it say?

**Comment by marcozanella** [comment]
@v-chojas, I have made one step forward ... without understanding why, though.
Trying to follow your suggestion, I have uninstalled almost everything (all python modules, python itself, unixodbc) - I have ran a Rosetta terminal and eventually reinstalled all these components using again arm64 terminal (it was a mistake) - but now I can list ODBC drivers using pyodbc.drivers()
I have not removed, nor edited ini files; they were working before using tsql, they are now - I honestly don't know what could be different now from then.

**Comment by marcozanella** [comment]
> from platform import processor
> processor()

The result is "arm"

**Comment by v-chojas** [comment]
It is likely you had x86 driver + DM and were attempting to use with arm64 Python.
