### ISSUE TITLE
Question marks not detected as parameter markers for CREATE TABLE in Vertica

### ISSUE THREAD

**Issue by maciek16180** [mkleehammer/pyodbc#1059]
### Environment

- Python: 3.7.13
- pyodbc: 4.0.32
- OS: Debian GNU/Linux 11 (bullseye)
- DB: Vertica v11.1.0-0
- driver: https://www.vertica.com/client_drivers/9.2.x/9.2.1-0/vertica-client-9.2.1-0.x86_64.tar.gz (I also tried https://www.vertica.com/client_drivers/11.1.x/11.1.1-0/vertica-client-11.1.1-0.x86_64.tar.gz)

### Issue

**Expected behavior**: question marks will work in all queries as parameter markers.

**Observed behavior**: in some queries question marks are not detected.

I use Python to connect to Vertica database, create a cursor, and try to run parameterized query.

This works:
```
In [17]: cursor.execute("SELECT 1 WHERE 1=?", 1)
Out[17]: <pyodbc.Cursor at 0x7f2c897f2230>
```

But if I wrap it into `CREATE TABLE`, is stops working:
```
In [18]: cursor.execute("CREATE TABLE a AS (SELECT 1 WHERE 1=?)", 1)
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
<ipython-input-18-1e79b89b9f86> in <module>
----> 1 cursor.execute("CREATE TABLE a AS (SELECT 1 WHERE 1=?)", 1)

ProgrammingError: ('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')
```

**Comment by gordthompson** [comment]
Your sample code works fine for me with the "PostgreSQL Unicode" ODBC driver, so this looks like an issue with the Vertica driver.

**Comment by maciek16180** [comment]
I updated the initial post with Vertica version.

**Comment by v-chojas** [comment]
```
[ODBC][7765][1652428595.009863][SQLNumParams.c][144]
                Entry:
                        Statement = 0x56035e6f5ad0
                        Param Count = 0x7ffec3ad8106
[ODBC][7765][1652428595.009872][SQLNumParams.c][231]
                Exit:[SQL_SUCCESS]
                        Count = 0x7ffec3ad8106 -> 0   *** HERE ***
```
That proves it's the ODBC driver which is claiming the query has no parameters. pyODBC isn't the problem here. Ask Vertica about that.
