### ISSUE TITLE
Interrupt a log running query

### ISSUE THREAD

**Issue by smitavk** [mkleehammer/pyodbc#1067]
### Environment

- Python: 
- pyodbc: 
- OS: 
- DB:
- driver:

### Issue
I am using Pyodbc to connect to a SQL server and I want to interrupt the current running query.
from sql server documentation sql server provide functionality of SQLCancel:  
SQLCancel:
Any call to the function that returns SQL_STILL_EXECUTING, an application can call SQLCancel to cancel the function. If the cancel request is successful, the driver returns SQL_SUCCESS. This message does not indicate that the function was actually canceled; it indicates that the cancel request was processed.

So In pyodbc do we have such functionality If yes then kindly provide some  document so that we can add this functionality in our application

Thanks in advance

**Comment by v-chojas** [comment]
pyODBC doesn't use ODBC in async mode, hence the answer is no.
