### ISSUE TITLE
Same queries, two different results

### ISSUE THREAD

**Issue by DandikUnited** [mkleehammer/pyodbc#107]
I have two scripts, I created one of them to test pyodbc connection, the other for production. Once I load my sql result to a pandas dataframe, I do some preprocessing for my sklearn model. The SQL queries are EXACTLY same. One of the data frame has 500k records (that's what I want) other returns 79 records.

When I remove preprocessing 

In my connection test I use these:

```
import pyodbc
import time
import pandas
import pandas.io.sql as psql
```

In  my production script I use these:

```
import pyodbc, pickle, snowballstemmer
import pandas as pd
import numpy as np
from sklearn import cross_validation
from sklearn.ensemble import AdaBoostClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords as sw 
```

When I comment out nltk.corpus it gets what I need. These two modules probably interfere somehow. This seems like a bug to me.

**Comment by mkleehammer** [comment]
It's difficult to tell where the bug would be.  First, are you selecting directly with pyodbc or are you using another library on top?  If directly using pyodbc I'd be interested in seeing an ODBC trace or something.

**Comment by mkleehammer** [comment]
Closing due to no more info, but please reopen if you have some.  Thanks.
