### ISSUE TITLE
I'm having troubles with Pyodbc on my macbook m1

### ISSUE THREAD

**Issue by SallyCodeP** [mkleehammer/pyodbc#1070]
File "/Users/paulogentil/django-maker/BackendCreator/MapFramework/MapDb.py", line 3, in <module>
    import pyodbc as dtb
ImportError: dlopen(/Users/paulogentil/patovenv/lib/python3.7/site-packages/pyodbc.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/unixodbc/lib/libodbc.2.dylib
  Referenced from: /Users/paulogentil/patovenv/lib/python3.7/site-packages/pyodbc.cpython-37m-darwin.so
  Reason: image not found

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
I tried to install unixodbc and configure the odbc.ini file but nothing happens
Someone can help me

**Comment by v-chojas** [comment]
Make sure you are consistently using ARM or x86 binaries throughout. Your Python, pyODBC, unixODBC, and ODBC driver all have to be of the same architecture. Mixing them has been the cause of a few other issues here. https://github.com/mkleehammer/pyodbc/issues?q=M1

**Comment by SallyCodeP** [comment]
I follow that steps:
1-I install the pyodbc package manually (https://pypi.org/project/pyodbc/#files)
2-I install unixodbc 
3-I run these commands:

pip uninstall pyodbc
export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.11/include"
export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.11/lib -liodbc -liodbcinst"
cd /Users/paulogentil/
pip install pyodbc-4.0.32.tar.gz

After all those steps i'm having a new error:
zsh: abort      python main.py
