### ISSUE TITLE
On PyCharm pyodbc, select large column item of delta table to databricks spark shows [Unexpected response from server during a HTTP connection: Bad Status: Unrecognized response with no error message header. Status code: 502. (14) (SQLDriverConnect)]]

### ISSUE THREAD

**Issue by this-is-YJ-Lin** [mkleehammer/pyodbc#1072]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.10
- pyodbc: 4.0.32
- OS: Linux 1123-033650-3lbg0ncl-10-248-20-132 5.4.0-1077-azure #80~18.04.1-Ubuntu SMP Wed Apr 13 02:07:09 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Datrbricks DBR : 10.1
- driver: NA

### Issue
This is Azure Databricks support engineer, we have a Customer who faced below issue:

The user are using pyodbc with **Pycharm** to connect to Azure databricks service to select a delta table,  got this issue :
```
%sql
SELECT tool_id, chamber, itime, **param_value** FROM prod_apc.mf_l8a_b_all_apc_at_continuousdata  
WHERE iday ='2022-06-19'    
AND (itime > '2022-06-19 20:58:57' and itime <= '2022-06-19 21:58:00')   
AND tool_id in ('CFACL101','CFACL201','CFACL301','CFACL401','CFACL501','CFACL601','CFCGL101','CFODF201','CFODF202','CFODF203','CFODF2041','CFODF2042','CFODF2043','CFODF2044','CFODF2045','CFODF2046','CFODF206','CFODF207','CFODF208','CFODF210','CFODF2103','CFODF212','CFODF2122','CFODF2123','CFODF2124','CFODF213','CFODF214','CFODF215','CFODF216','CFODF217','CFODF218','CFODF301','CFODF302','CFODF303','CFODF3041','CFODF3042','CFODF3043','CFODF3044','CFODF3045','CFODF3046','CFODF306','CFODF307','CFODF308','CFODF310','CFODF3103','CFODF312','CFODF3121','CFODF3122','CFODF3123','CFODF3124','CFODF313','CFODF314','CFODF315','CFODF316','CFODF317','CFODF318','CFPFL101','CFPIC101','CFPIC102','CFPIC103','CFPIC104','CFPIC105','CFPIC106','CFPIC107','CFPIC108','CFPIC109','CFPIC110','CFPIC201','CFPIC202','CFPIC203','CFPIC204','CFPIC205','CFPIC206','CFPIC207','CFPIC208','CFPIC209','CFPIC210','')    
AND chamber in ('SOURCE_CURRENT','J_5F','ELECTRICITY','J_3F','')    
AND (param_value like '%CURRENT%' or param_value like '%AVG%')
```
we got this error messages
Error: ('HY000', '[HY000] [Simba][ThriftExtension] (14) Unexpected response from server during a HTTP connection: Bad Status: Unrecognized response with no error message header. Status code: 502. (14) (SQLDriverConnect); [HY000] [Simba][ThriftExtension] (14) Unexpected response from server during a HTTP connection: Bad Status: Unrecognized response with no error message header. Status code: 502. (14)')

1) Only got the error when run this query on Pycharm , but not happen if we run query  on Databricks spark notebook.
2) If we delete **param_value** from select list, query on Pycharm is no problem.
This item is a string column on delta table and saves large json file data

I suspect if there is any limitation when running the query on Pycharm?
Could you please help check it.?

**Comment by v-chojas** [comment]
That error is coming from the ODBC driver. As Gord says, an ODBC trace will show exactly what's happening, but I suspect the root cause is a bug/limitation in the ODBC driver, not pyODBC.

**Comment by this-is-YJ-Lin** [comment]
Thanks for your information and quick comment! Our customer is trying now, and I am waiting for the response, I would let you guys know the result as soon as possible. Thanks again!

**Comment by this-is-YJ-Lin** [comment]
Hi all, 
Good day!
The error messages were presented above, could you please check it?
Thanks again for your help, I am looking forward to your reply!

**Comment by Baiys1234** [comment]
@gordthompson @v-chojas 
I have shared odbc log, could you please confirm it as soon as possible.

Thanks very much

**Comment by this-is-YJ-Lin** [comment]
Hi all @Baiys1234 @v-chojas @gordthompson , 
For helping us to clarify the full scenario, I would like to provide the full log of this issue.
There are two logs respectively. 
1. We got the log of this query from our customer, it found out there are some 502 error responses when If other programs are also using databricks cluster to fetch data at the time of execution: file name - [**select_top1_502_odbc**](https://microsoftapc-my.sharepoint.com/:u:/g/personal/ellenlin_microsoft_com/EYLmkX6e_ItEoy160SpmcvwBm_RPQDwM2_CDsOgnOty-bw?e=Oachcr)
2. Conversely, if no other program is using the databricks cluster to fetch data at the moment,
There will be no 502 error when executing this SQL, but the data cannot be displayed because the returned string is too big: file name - [**select_top1_too_big_odbc**](https://microsoftapc-my.sharepoint.com/:u:/g/personal/ellenlin_microsoft_com/Ee3ef5v0YNlAmcykJhjr5bsBO7v7je2ZHU9Dak6awPpGLg?e=NGVeqp)
Noted that the log files I have updated to the one drive then set it as private file and assigned you guys only can read it, sorry for [Baiys1234](https://github.com/Baiys1234), I couldn't find your mail, but it seems like you have log too.

Thanks a lot!
