### ISSUE TITLE
Missing win-32bit packages on pip (pypi) for python 3.9/3.10

### ISSUE THREAD

**Issue by crash5** [mkleehammer/pyodbc#1073]
Hi,

are the 32bit packages intentionally missing from the PyPI database? (https://pypi.org/project/pyodbc/#files)

As I see the appveyor config in the repository includes the 32bit version pipelines. But the latest 32bit version for windows is for python 3.8.

**Comment by mkleehammer** [comment]
I didn't realize the later versions even supported 32-bit Windows.  I also didn't know that Windows 10 used to have a 32-bit version.  (Apparently they recently stopped sending it to manufacturers, so I think it is near the end.)

I'll do some research into adding these to the CI builds.  I'll also see if Github suports everything we need now and if we can drop AppVeyor completely. 

We'll want to update the setup.py for 3.8:

https://cibuildwheel.readthedocs.io/en/stable/faq/#windows-importerror-dll-load-failed-the-specific-module-could-not-be-found

**Comment by gordthompson** [comment]
> are the 32bit packages intentionally missing from the PyPI database?

It appears so:

https://github.com/mkleehammer/pyodbc/blob/b7e944acdeaa3233dcac045d059d93fe46a71989/.github/workflows/ubuntu_build.yml#L210-L211

As a workaround, at least for now, a limited assortment of 32-bit Windows wheels are available from

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc

**Comment by gordthompson** [comment]
Covered by #1084
