### ISSUE TITLE
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY000', '[HY000] [Dremio][Connector] (1040) Dremio failed to execute the query:

### ISSUE THREAD

**Issue by AlbertUlysses** [mkleehammer/pyodbc#1083]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

Python: 3.10 (64 bit)
pyodbc: 4.0.34
OS: linux/amd64 (Running in Docker)
DB: Dremio
driver: Dremio odbc 1.4.2

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
#### expected behavior
pass the SQL Query to the database
#### observed behavior
```
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('HY000', '[HY000] [Dremio][Connector] (1040) Dremio failed to execute the query: ����������������������������������������\n[30038]Query execution error. Details:[ \nPARSE ERROR: Failure parsing the query.\n\nSQL Query ����������������������������������������\nstartLine 1\nstartColumn 1\nendLine 1\nen...[see log]\x00]㜷㌷っ\u2061湯ㄠ⸰〱㈮㈮㔳㌺〱〱\u0a5d\u200a⠠牯\u2e67灡捡敨挮污楣整献汱瀮牡敳\u2e72煓偬牡敳硅散瑰潩⥮䰠硥捩污攠牲牯愠⁴楬敮ㄠ\u202c潣畬湭ㄠ\u202e䔠据畯瑮牥摥›尢晵晦≤⠠㔶㌵⤳\u202c晡整\u2072›∢\u200a†挠浯搮敲業\u2e6f硥捥瀮慬湮牥献汱瀮牡敳\u2e72浩汰倮牡敳䥲灭\u2e6c潣癮牥䕴捸灥楴湯⤨㌺㤴\u200a†挠浯搮敲業\u2e6f硥捥瀮慬湮牥献汱瀮牡敳\u2e72浩汰倮牡敳䥲灭\u2e6c潮浲污穩䕥捸灥楴湯⤨ㄺ (1040) (SQLExecDirectW)')
[SQL: Select * FROM table]
(Background on this error at: https://sqlalche.me/e/14/dbapi)
```
### Current solution:
Error goes away when I downgrade to pyodbc==4.0.32
And all other libraries stay the same.

**Comment by v-chojas** [comment]
https://github.com/mkleehammer/pyodbc/issues/1082 is almost certainly the cause.
