### ISSUE TITLE
Unable to use ¶ in like statement 

### ISSUE THREAD

**Issue by pljspahn** [mkleehammer/pyodbc#1086]
### Environment

- Python: 3.10.4
- pyodbc: 4.0.32
- OS: PopOS 22.04
- DB: Eloquence (pretty obscure)
- driver: SQL/R (part of Eloquence, also obscure, see https://www.marxmeier.com/sqlr/ )

### Issue

I want to query a field that contains a ¶ character. A basic example of this would be such as:

    sql = """
        select
            prod_code,
            prod_loc
        from product
        where prod_loc like '%¶%'
    """

This returns no results while a value in `prod_loc` is stored like:

    &102D&n365 ¶

I set my connection up as:

```
import pyodbc
from os import environ

class EloquenceConnect:
    cursor = None
    
    def __init__(self):
        connection = pyodbc.connect('DSN='+environ['ODBC_DSN'])
        connection.setencoding(encoding='utf-8')
        self.cursor = connection.cursor()
```

I suspect there's some mishap with how I have set up the connection's encoding, or maybe I need to set the decoding as well? Any suggestions on how to handle this?

**Comment by v-chojas** [comment]
You're right that this likely has something to do with encoding. I suggest retrieving the field from the database through the driver, inspecting the byte sequence to determine the encoding it returned the data in, and using that in sending data to the driver.

**Comment by gordthompson** [comment]
Further to comment from @v-chojas - You could do something like this:

```python
import pyodbc

cnxn = pyodbc.connect(…)

def string_bytes(byte_data):
    return byte_data

cnxn.add_output_converter(pyodbc.SQL_WVARCHAR, string_bytes)

crsr = cnxn.cursor()
print(crsr.execute("SELECT ? AS foo", "¶").fetchval())
# b'\xb6\x00'
```

This was executed against SQL Server. The Pilcrow Sign ('¶') is U+00B6 and we see that the server returned the character as those two bytes in reverse order, so the encoding is UTF16-LE (UTF-16 is the default for pyodbc). If the server had returned `b'\xc2\xb6'` then the encoding would be UTF-8 and you would need to use `setdecoding()`/`setencoding()` as described in the [wiki](https://github.com/mkleehammer/pyodbc/wiki/Unicode).
