### ISSUE TITLE
mod_wsgi and pyodbc

### ISSUE THREAD

**Issue by esemate** [mkleehammer/pyodbc#109]
I've deployed a Django application using sqlalchemy and pyodbc in a virtual env. In development environments everything is ok, but when I use Apache + mod_wsgi, I allways get the same error, when sqlalchemy tries to "load" pyodbc connector, the error is: ImportError: No module named 'pyodbc'

The full text is here:

[Wed Mar 16 16:13:09.682686 2016] [mpm_event:notice] [pid 1755:tid 140690280609664] AH00489: Apache/2.4.12 (Ubuntu) mod_wsgi/4.3.0 Python/3.4.3+ configured -- resuming normal operations
[Wed Mar 16 16:13:09.682799 2016] [core:notice] [pid 1755:tid 140690280609664] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 16 16:13:13.816692 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122] mod_wsgi (pid=1758): Target WSGI script '/home/skull/historydata/historydata/historydata/wsgi.py' cannot be loaded as Python module.
[Wed Mar 16 16:13:13.816814 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122] mod_wsgi (pid=1758): Exception occurred processing WSGI script '/home/skull/historydata/historydata/historydata/wsgi.py'.
[Wed Mar 16 16:13:13.816873 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122] Traceback (most recent call last):
[Wed Mar 16 16:13:13.817122 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydata/wsgi.py", line 15, in <module>
[Wed Mar 16 16:13:13.817138 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     application = get_wsgi_application()
[Wed Mar 16 16:13:13.817313 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Wed Mar 16 16:13:13.817328 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     django.setup()
[Wed Mar 16 16:13:13.817521 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
[Wed Mar 16 16:13:13.817537 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     apps.populate(settings.INSTALLED_APPS)
[Wed Mar 16 16:13:13.817875 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
[Wed Mar 16 16:13:13.817892 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     app_config.import_models(all_models)
[Wed Mar 16 16:13:13.818127 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
[Wed Mar 16 16:13:13.818144 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     self.models_module = import_module(models_module_name)
[Wed Mar 16 16:13:13.818371 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
[Wed Mar 16 16:13:13.818387 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     return _bootstrap._gcd_import(name[level:], package, level)
[Wed Mar 16 16:13:13.818421 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
[Wed Mar 16 16:13:13.818454 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
[Wed Mar 16 16:13:13.818486 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
[Wed Mar 16 16:13:13.818517 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
[Wed Mar 16 16:13:13.818548 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "<frozen importlib._bootstrap>", line 1129, in _exec
[Wed Mar 16 16:13:13.818579 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "<frozen importlib._bootstrap>", line 1471, in exec_module
[Wed Mar 16 16:13:13.818610 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
[Wed Mar 16 16:13:13.818841 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/dataprovider/models.py", line 8, in <module>
[Wed Mar 16 16:13:13.818856 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     engine = create_engine(CNSTR_HD)
[Wed Mar 16 16:13:13.819151 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
[Wed Mar 16 16:13:13.819167 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     return strategy.create(*args, **kwargs)
[Wed Mar 16 16:13:13.819412 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
[Wed Mar 16 16:13:13.819427 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     dbapi = dialect_cls.dbapi(**dbapi_args)
[Wed Mar 16 16:13:13.819656 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/sqlalchemy/connectors/pyodbc.py", line 51, in dbapi
[Wed Mar 16 16:13:13.819671 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122]     return __import__('pyodbc')
[Wed Mar 16 16:13:13.819714 2016] [wsgi:error] [pid 1758:tid 140690175645440] [remote 100.100.100.118:5122] ImportError: No module named 'pyodbc'
[Wed Mar 16 16:13:13.928017 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404] mod_wsgi (pid=1758): Target WSGI script '/home/skull/historydata/historydata/historydata/wsgi.py' cannot be loaded as Python module.
[Wed Mar 16 16:13:13.928093 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404] mod_wsgi (pid=1758): Exception occurred processing WSGI script '/home/skull/historydata/historydata/historydata/wsgi.py'.
[Wed Mar 16 16:13:13.928148 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404] Traceback (most recent call last):
[Wed Mar 16 16:13:13.928241 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]   File "/home/skull/historydata/historydata/historydata/wsgi.py", line 15, in <module>
[Wed Mar 16 16:13:13.928263 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]     application = get_wsgi_application()
[Wed Mar 16 16:13:13.928316 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Wed Mar 16 16:13:13.928329 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]     django.setup()
[Wed Mar 16 16:13:13.928377 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
[Wed Mar 16 16:13:13.928388 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]     apps.populate(settings.INSTALLED_APPS)
[Wed Mar 16 16:13:13.928436 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]   File "/home/skull/historydata/historydata/historydataenv/lib/python3.5/site-packages/django/apps/registry.py", line 78, in populate
[Wed Mar 16 16:13:13.928448 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404]     raise RuntimeError("populate() isn't reentrant")
[Wed Mar 16 16:13:13.928486 2016] [wsgi:error] [pid 1758:tid 140690058032896] [remote 100.100.100.118:28404] RuntimeError: populate() isn't reentrant

**Comment by FlipperPA** [comment]
Which versions of each stack component are you using? For example, it looks like "historydataenv" is set for Python 3.5, yet mod_wsgi is compiled against 3.4.3; these should match. Are you running pyodbc==3.0.10? What's your Django DATABASES settings? What versions of FreeTDS and unixODBC are you using? Thanks.

**Comment by esemate** [comment]
Hi Timothy,

   - historydataenv is a virtual env with Python 3.5.1 and pyodbc 3.0.10
   (installed with pip inside the virtual env)
   - apache2 --> 2.4.12
   - mod_wsgi --> 4.3.0 (it seems it's running under Python 3.4.3+, how can
   I compile it to run under Python 3.5.1??)
   - Django DATABASES = {

    'default': {
'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR,'db.sqlite3'),
    }
}


   - FreeTDS: 0.91-6.1
   - unixODBC: 2.3.1-3


Thank you!

**Comment by FlipperPA** [comment]
Here's an example for mod_wsgi 4.4.21 with Python 3.5 (the key line is "./configure..."):

	wget -q "https://github.com/GrahamDumpleton/mod_wsgi/archive/4.4.21.tar.gz"
	tar -xzf '4.4.21.tar.gz'
	cd ./mod_wsgi-4.4.21
	./configure --with-python=/usr/local/bin/python3.5
	make
	make install

One more thing, can you include your Apache config for the web site, and the wsgi.py file? I'm wondering if you're pointing Apache to the correct virtualenv. Thanks!

**Comment by esemate** [comment]
Hi again, find attached what you've asked.

Thank you Timothy!

**Comment by esemate** [comment]
Up & running!!

Thanks Timothy!!

👏👏👏

**Comment by FlipperPA** [comment]
Fantastic! I'm glad it worked out for you.
