### ISSUE TITLE
Jupyter Kernel Dies when trying to connect to PSQL 12.10 database. It works fine when executing python script via Anaconda terminal

### ISSUE THREAD

**Issue by agopichand88** [mkleehammer/pyodbc#1092]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.6 - 64 bit
- pyodbc: 4.0.31
- OS: Windows Server 2019 - 64 Bit
- DB: pervasive SQL 12.10
- driver: Pervasive ODBC Interface

### Issue
Jupyter Kernel dies on running pyodbc.connect statement,, but when executing the script via Anaconda terminal returns output without any issues. This only happens with this Driver.

Pervasive ODBC Interface, tested fine and able to connect to it using Excel without any issues.

**Comment by v-makouz** [comment]
Does it print any errors?

**Comment by agopichand88** [comment]
Nope, it just does after a couple of secs.

**Comment by gordthompson** [comment]
An [ODBC trace](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) might provide some insight.

**Comment by agopichand88** [comment]
It doesn't generate any odbc trace file while running through Jupyter Notebook.
