### ISSUE TITLE
Failed to connect using 4.0.34 version

### ISSUE THREAD

**Issue by achettyiitr** [mkleehammer/pyodbc#1095]
### Issue

Getting this particular error for DSN-less connection string for the recent version 4.0.34. It's working with the 4.0.32 version. 

> ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')

- [Simba Spark ODBC Driver](https://databricks-bi-artifacts.s3.us-east-2.amazonaws.com/simbaspark-drivers/odbc/2.6.19/SimbaSparkODBC-2.6.19.1033-Debian-64bit.zip)
- unixODBC Driver => ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.9.tar.gz

**Comment by v-chojas** [comment]
Check where your odbcinst.ini is. 4.0.34 came with its own version of unixODBC which might not be looking for the odbcinst.ini in the same place as the one you installed.

**Comment by achettyiitr** [comment]
Sorry, @v-chojas. I added the description incorrectly. It's working with 4.0.32. Not working with the current released version 4.0.34

**Comment by achettyiitr** [comment]
> Check where your odbcinst.ini is. 4.0.34 came with its own version of unixODBC which might not be looking for the odbcinst.ini in the same place as the one you installed.
I have both the files obdc.ini and odbcinst.ini empty since I am opting for a DSN-less connection string and specifying the Driver as well in the connection string itself. But with the current released version, it was kind of looking for these files instead of being specified in the connection string.

**Comment by Atheuz** [comment]
4.0.34 is broken because it includes old libraries. I recommend not using it until it is fixed, and instead use 4.0.32.

**Comment by v-chojas** [comment]
Indeed, avoid '34. It has already caused these problems reported here:
https://github.com/mkleehammer/pyodbc/issues/1082
https://github.com/mkleehammer/pyodbc/issues/1083
https://github.com/mkleehammer/pyodbc/issues/1081
https://github.com/mkleehammer/pyodbc/issues/1079

**Comment by TroyWitthoeft** [comment]
Reporting in with similar issues.

**Comment by v-chojas** [comment]
We know. 4.0.34 is broken.

**Comment by TroyWitthoeft** [comment]
@v-chojas Good luck on the fix!   Appreciate the feedback.
