### ISSUE TITLE
Time for 4.0.35?

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#1096]
According to https://pypistats.org/packages/pyodbc , 4.0.34 has been downloaded more than 20 million times in the last 30 days, and 98%+ of those downloads are for Linux.

IMO, we really should release 4.0.35 to fix the manylinux wheels issue.

**Comment by RajJani** [comment]
Had to pin my stuff to 4.0.32, which causes a whole lot of issues depending on the version of Linux you use.

**Comment by gordthompson** [comment]
As mentioned [here](https://github.com/mkleehammer/pyodbc/issues/1082#issuecomment-1285645409), it appears that Christophe's library of Windows wheels is no longer being updated.

**Comment by leonkosak** [comment]
Any news when 4.0.35 will be released?

**Comment by mkleehammer** [comment]
I cannot apologize enough, especially when @keitherskine has made it so easy to release now.  There is now a 4.0.35 release with 3.11 wheels.
