### ISSUE TITLE
proper way to detect unixODBC

### ISSUE THREAD

**Issue by dcsaba89** [mkleehammer/pyodbc#1097]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 
- pyodbc: 
- OS: 
- DB:
- driver:

### Issue

https://github.com/mkleehammer/pyodbc/blob/master/setup.py#L240

in setup.py line 240 after the comment 
What is the proper way to detect iODBC, MyODBC, unixODBC, etc.?
it should be 
settings['libraries'].append(':libodbc.so.2')

**Comment by v-makouz** [comment]
The standard way is to run `odbcinst -j` although if you have several unixODBC installations it may be inaccurate. In that case the ultimate way is to do an strace and see which lib is actually loaded.
