### ISSUE TITLE
Binding Parameters to Sybase SP fails

### ISSUE THREAD

**Issue by FinQuest** [mkleehammer/pyodbc#110]
Code:

`sql = 'exec p_STOREDPROC @arg_1=:one, @arg_2=:two, @arg_3=:three;'`
`res = engine.execute(sql, arg_1='STRING', arg_2=123.456, arg_3='STRING')`

Error:

> cursor.execute(statement, parameters)
(pyodbc.ProgrammingError) ('The SQL contains 3 parameter markers, but 1 parameters were supplied', 'HY000') [SQL: 'exec p_STOREDPROC @arg_1=:one, @arg_2=:two, @arg_3=:three;'] [parameters: {'arg_1': 'test', 'arg_2': 123.456, 'arg_3': 'test'}]

pyodbc 3.0.10 py34_0
platform : win-64
conda version : 4.0.4
conda-build version : 1.19.2
python version : 3.4.4.fi
requests version : 2.9.1

**Comment by mkleehammer** [comment]
ODBC always uses a question mark for parameter markers and you cannot name them, so you need to use:

    cursor.execute('exec p_STOREDPROC @arg_1=?, @arg_2=?, @arg_3=?',
        'STRING1', 123.456, 'STRING')

I'm not sure what ``engine`` is, but just make sure it passes the values in order.  You can also pass a single sequence (tuple, list, etc.) with the parameters.
