### ISSUE TITLE
Stack smashing error when connecting to an AzureSQL instance

### ISSUE THREAD

**Issue by joeri-vlekken** [mkleehammer/pyodbc#1114]
Hello, our environment with pyodbc has broken recently: every time we try to connect with pyodbc to an Azure SQL instance we get a "stack smashing" error after a few seconds.

I have tested and confirmed the error on 2 separate machines with 2 different Linux OS'es.

### Environment

- python: 3.9.7
- pyodbc: 4.0.34
- SQL Server: default AzureSQL online instance
- OS 1: AlmaLinux 8.6 kernel: 4.18.0-372.32.1.el8_6.x86_64
- OS 2: openSuSe Leap 15.4 kernel: 5.14.21-150400.24.21-default
- Microsoft ODBC driver 18 is installed on both machines

### Issue

I try the following simple example to simply connect to an online database (with ActiveDirectoryServicePrincipal as authentication method)

```
import pyodbc

conn_string = 'DRIVER={ODBC Driver 18 for SQL Server};' \
                'SERVER=' + '####.database.windows.net' + \
                ';DATABASE=' + '####' + \
                ';UID=' + '####' + \
                ';PWD=' + '####' + \
                ';Authentication=ActiveDirectoryServicePrincipal'
print(conn_string)
sql_conn = pyodbc.connect(conn_string)

sql_conn.cursor().execute('test')
sql_conn.close()
```

#### Occured behaviour
The following error get's returned after a few seconds (no other logging appears to return):

```
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

#### Expected behaviour
The program should confirm the connection to AzureSQL after a few moments. (as it did before a few days ago)

**Any other details that can be helpful**
- I have also tried changing the Microsoft ODBC Drivers to version 17, 18, 18.1, all of them occurring with the same problem.
- I use "ActiveDirectoryServicePrincipal" as authentication method, unfortunately I have no other resources at the moment to test alternative authentication methods on Azure.

Any help or advice how to proceed further is much appreciated!

**Comment by v-chojas** [comment]
https://github.com/mkleehammer/pyodbc/issues/1095
If you are using prebuilt binaries for 4.0.34 they include a very old unixODBC, use previous version for now or build from source yourself.

**Comment by gordthompson** [comment]
Agreed. Please try 

```
pip install --upgrade --force-reinstall pyodbc --no-binary pyodbc
```

and let us know if it solves your issue.

**Comment by gordthompson** [comment]
re: trace file - Try putting the Trace directives in an [ODBC] section at the top of the odbcinst.ini file.

```
[ODBC]
Trace=Yes
TraceFile=/home/joeri/odbctrace.log
```

I honestly don't know if unixODBC supports per-driver trace configurations. (Never tried.)

**Comment by joeri-vlekken** [comment]
hey @gordthompson that worked indeed! I've got a lot of output in that trace file and I quickly stumbled upon this message:
```
DIAG [FA004] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Failed to authenticate the user '########-####-####-####-############' in Active Directory (Authentication option is 'ActiveDirectoryServicePrincipal').
Error code 0xA190; state 41360
AADSTS7000222: The provided client secret keys for app '########-####-####-####-############' are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.\r\nTrace ID: ########-####-####-####-############\r\nCorrelation ID: ########-####-####-####-############\r\nTimestamp: 2022-11-02 08:37:39Z
```
So it's clear that my principal key expired (facepalm to myself...). I have refreshed the client secret in Azure and everything is working perfect again now.
Should this type of error be visible at a higher level or is Microsoft's ODBC driver to blame?
In any case: a great thank you for helping out!

**Comment by Augustine-Rivera** [comment]
@joeri-vlekken I was experiencing the same issues with the same environment, but with an Ubuntu 20.0.4 OS. 
How did you go about installing the pyodbc from the source?

**Comment by joeri-vlekken** [comment]
hello @Augustine-Rivera : simply by reinstalling the package through pip as following:
`pip install --upgrade --force-reinstall pyodbc --no-binary pyodbc` as suggested by @gordthompson and @v-chojas above.
