### ISSUE TITLE
ImportError: libodbc.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dxk5271** [mkleehammer/pyodbc#1133]
Pyodbc successfully installs in my Kubernetes container through a requirments.txt file. But I receive errors when importing pyodbc in my python script. 

Downgrading to the previous version fixed this issue.

**Comment by v-chojas** [comment]
What errors, specifically?

**Comment by dxk5271** [comment]
"ImportError: libodbc.so.2: cannot open shared object file: No such file or directory"

I did confirm that pyodbc did exists. Downgrading to 4.0.34 resolved this issue.

**Comment by v-chojas** [comment]
Install unixODBC.

4.0.34 came with unixODBC but it is a very old and buggy version which has caused other issues here.

**Comment by gordthompson** [comment]
https://github.com/mkleehammer/pyodbc/wiki/Install#installing-on-linux

**Comment by johnidm** [comment]
For me, the solution to solve this problem was:

```
sudo apt remove libodbc2
sudo apt install libodbc2
```

I am using a distro based on Ubuntu 22.04 LTS (Jammy)

**Comment by Carmelly212** [comment]
this made the trick !
`sudo apt-get install unixodbc-dev`

**Comment by majkyyx** [comment]
> this made the trick ! `sudo apt-get install unixodbc-dev`

 It's works for python:3.9-bullseye well ! THX

**Comment by SamPrinceFranklin** [comment]
### PyODBC ImportError: libodbc.so.2: cannot open shared object file: No such file or directory

If you encounter the `ImportError: libodbc.so.2: cannot open shared object file: No such file or directory` error when trying to import pyodbc after installing it via pip, follow these steps:

 **Install unixODBC**: Run the following command to install unixODBC, which is required for pyodbc to work properly.
   ```bash
   $ sudo apt install unixodbc
This should resolve the shared object file error and allow you to use pyodbc without any issues.

**Comment by v-chojas** [comment]
Do you really need to repeat what was said multiple times in previous comments already?

**Comment by tarikwaleed** [comment]
## The way it worked for me (on Ubuntu 22.04)
*i was trying to connect to SQL Server database from a django application, but I was facing this error, so the way I solved it was*
#### 1. Install `unixodbc`

First, ensure you have `unixodbc` installed. You can install it using the following command:

```shell
sudo apt install unixodbc
```

#### 2. Install Microsoft ODBC 17 Driver

Run the following bash script to install the Microsoft ODBC 17 Driver:

```shell
if ! [[ "16.04 18.04 20.04 22.04" == *"$(lsb_release -rs)"* ]];
then
    echo "Ubuntu $(lsb_release -rs) is not currently supported.";
    exit;
fi

curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list

sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
# optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
# optional: for unixODBC development headers
sudo apt-get install -y unixodbc-dev
```

**Comment by mikaeilokt** [comment]
> Do you really need to repeat what was said multiple times in previous comments already?

It's a gpt bot.

**Comment by ChanukaVijayantha** [comment]
> This was worked.
> 
> ```
> sudo apt remove libodbc2
> sudo apt install libodbc2
> ```
