### ISSUE TITLE
pyodbc + Azure Function Apps, and 2 "Can't open lib 'ODBC Driver 18 for SQL Server" error

### ISSUE THREAD

**Issue by SebastianDeChiara** [mkleehammer/pyodbc#1136]
- Python: 3.9.13 64 bit
- pyodbc: 4.0.34
- OS: Windows 10 Pro
- DB: SQL Server on Azure
- driver: ODBC Driver 18 for SQL Server

I'm stuck in an error which I've been researching for a while now. I have looked at all the related issues and have found no solution within them.

I have Python code that I want to use in a Function App with a time trigger that runs every day at 06:00. The code:

1. Calls an API, downloads data.

2. Cleans the data.

3. Connects to a database using pyodbc module.

4. Inserts data into the database.

I then create the function app, configure it, and, locally, it's running perfectly, executing the code everyday at 06:00.

Then I create a resource and deploy the function app on Azure. The function executes properly at the configured time. However, when it runs, I get the error.

https://pastebin.com/FWBECeWq

This is the overview of the function app:

https://imgur.com/a/XDetHzk

Could it be related to the fact that the application is hosted on Linux and I'm using pyodbc driver for Windows?

**Comment by keitherskine** [comment]
It's possible the Function App doesn't have ODBC Driver 18 installed.  Perhaps it only has ODBC Driver 17, in which case you could try using that instead, i.e. in your code, do something like this:
`pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server}` ...

To see what drivers are available to pyodbc, try using [pyodbc.dataSources()](https://github.com/mkleehammer/pyodbc/wiki/The-pyodbc-Module#datasources) and [pyodbc.drivers()](https://github.com/mkleehammer/pyodbc/wiki/The-pyodbc-Module#drivers), i.e.:
```
import pyodbc
print(pyodbc.dataSources())
print(pyodbc.drivers())
```

**Comment by SebastianDeChiara** [comment]
> 

Thank you, this was useful to know what drivers the virtual machine has. This helped me solve the issue.
