### ISSUE TITLE
Migrate columns from Oracle to MsSql

### ISSUE THREAD

**Issue by rmartinsdesouza** [mkleehammer/pyodbc#1138]
### Environment

- Python: 3.9.13
- pyodbc: 
- OS: Windows
- DB: Oracle, MsSql
- driver:

### Issue

I need migrate columns from Oracle to MsSql, but i do know make compare data type.
I think transform and change 
`ALTER TABLE TAB_ORIGIM_ORACLE ADD TYPE_ORACLE DEFAULT NULL`
to
`ALTER TABLE TAB_DESTINATION_MSSQL ADD TYPE_MSSQL DEFAULT NULL`

**Comment by gordthompson** [comment]
This is not really a question specific to pyodbc.
