### ISSUE TITLE
pyodbc and pylint static analysis

### ISSUE THREAD

**Issue by keitherskine** [mkleehammer/pyodbc#115]
When I run my code through the static analysis tool [pylint,](https://www.pylint.org/) I get the following error for all calls to pyodbc.connect():

`Module 'pyodbc' has no 'connect' member`

I get similar errors for pyodbc exception objects.  It appears pylint is not able to ascertain the functions and attributes within the pyodbc module. I don't know how this can fixed (because pyodbc is almost entirely C++), but if it can, it would be kinda handy.

FYI, the workaround I have at the moment is to tell pylint to ignore the pyodbc module entirely, by adding the following line to my pylint config file:

```
[TYPECHECK]
ignored-modules=pyodbc
```

**Comment by mkleehammer** [comment]
I don't have the answer, but if you find it, please post it to the Wiki.

**Comment by steveoh** [comment]
Is there not a better solution to this issue?

**Comment by giuliohome** [comment]
> 
> 
> Is there not a better solution to this issue?

Yes [the solution is whitelisting](https://stackoverflow.com/a/56844616/11323942) pyodbc, so that pylint builds the  AST.

I've put

`extension-pkg-whitelist=pyodbc`

in my `.pylintrc`

For exa
