### ISSUE TITLE
Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by J04N4** [mkleehammer/pyodbc#1150]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.9
- pyodbc: 4.0.35
- OS: Windows and Linux
- DB: Azure SQL database
- driver: {ODBC Driver 13 for SQL Server}

### Issue
I'm using pyodbc to establish connection to sql db in my python code. Everything works fine locally, but when I deploy the Function App and I run it on the Azure Portal, I get the "Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")".
error
<img width="552" alt="error" src="https://user-images.githubusercontent.com/44548285/212308775-e98e616d-4cc6-4d5e-b3cc-3592339e813d.png">

I installed the driver locally on my Windows machine and I installed and imported pyodbc on my python environment. The OS used in the function app environment is Linux
Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by gordthompson** [comment]
Check the list returned by `pyodbc.drivers()` to see what ODBC drivers are available to your Python app on the Azure Portal.

**Comment by J04N4** [comment]
@gordthompson On my local machine i have the following ODBC drives: 
- Microsoft ODBC for Oracle
- ODBC Driver 13 for SQL Server

**Comment by gordthompson** [comment]
Fine, but that does not tell you anything about the drivers that are — or are not —  installed on the other machine (to which you deploy your application).

**Comment by J04N4** [comment]
@gordthompson The Function App is associated to an App Service Plan that is Consumption (serverless) and runs on Linux. I don't think I can manage or install things on those, not to my knowledge

**Comment by gordthompson** [comment]
Well, that environment seems to have pyodbc installed so they may have already provided some version of msodbcsql ("ODBC Driver xx for SQL Server"). `pyodbc.drivers()` on the remote system would tell you that.

**Comment by J04N4** [comment]
@gordthompson It seems like they had the odbc driver 17 for sql server installed by default on the container. I change it in my code to match it and it fixed. 
![image](https://user-images.githubusercontent.com/44548285/212654224-0ade99fa-42d5-4c8e-996e-cb1cd77e3b8a.png)

Thank you for the explanation
