### ISSUE TITLE
Support for sub-interpreters

### ISSUE THREAD

**Issue by mgampi** [mkleehammer/pyodbc#117]
With v3.0.10 I'm unable to use pyodbc in different sub-interpreters.
My app crashes when calling connect in second interpreter (inline function 'lowercase').
Ho wcan I use it in such configurations?

**Comment by mkleehammer** [comment]
PyMongo's excellent description of the issue: https://emptysqua.re/blog/python-c-extensions-and-mod-wsgi

**Comment by mkleehammer** [comment]
I have pushed an implementation to the subinterpreters thread but I haven't written my own C program to test it yet.  I've done some minimal testing under mod_wsgi but not enough.  (I couldn't reproduce crashes with earlier versions.  I should do some kind of `isinstance` check that would fail if subinterpreters weren't supported properly.)

**Comment by mkleehammer** [comment]
This has been complete for a while but I forgot to close this.
