### ISSUE TITLE
Unable to connect to SQL managed instance from Linux, works with Windows

### ISSUE THREAD

**Issue by luisaranda** [mkleehammer/pyodbc#1174]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.8.10
- pyodbc: 4.0.35
- OS: Ubuntu 20.04.5
- DB: Azure SQL Managed Instance
- driver: (ODBC):  ODBC Driver 18 for SQL Server, /usr/lib/ libmsodbcsql-18.so

### Issue

The Authentication is set to ActiveDirectoryIntegrated and trying to connect to an Azure SQL Managed Instance. Our Azure Active Directory credentials are federated with OKTA. [Authentication fundamentals: Federation | Azure Active Directory
](https://www.youtube.com/watch?v=CjarTgjKcX8)

The problem is if the application runs on Linux (Ubuntu) the connection fails. When using Windows, the connection works.
The application is on premises.

We collected an ODBC trace log when the connection fails. 
[odbctrace.log](https://github.com/mkleehammer/pyodbc/files/10877302/odbctrace.log)

Is this expected? Is ActiveDirectoryIntegrated supported with Linux? 

Searched on the wiki but couldn't find anything conclusive. 

Would appreciate your expertise. Thanks in advance!

**Comment by v-chojas** [comment]
This has nothing to do with pyODBC. ActiveDirectoryIntegrated will need a valid Kerberos set up. See documentation for more information: https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-ver16

**Comment by artgoldberg** [comment]
@luisaranda Since a Linux user doesn't local Windows AAD credentials, they need to be made available. Use the Kerberos `kinit` command to initialize a Kerberos token that the odbc driver can use to authenticate the user to SQL Server.

**Comment by mkleehammer** [comment]
Thanks artgoldberg.  I'm going to close this since it is unrelated to pyodbc.
