### ISSUE TITLE
pex execution inside docker container got ModuleNotFoundError: No module named 'pyodbc'.

### ISSUE THREAD

**Issue by icymoonicy** [mkleehammer/pyodbc#1194]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.10.4
- pyodbc: 4.0.35
- OS: ubuntu 20.04LTS
- DB: N/A
- driver: N/A

### Issue
I have a .pex file with pyodbc 4.0.35 installed and I've tried execute it on my local and it works fine, however if I run it inside a docker container it will throw: ModuleNotFoundError: No module named 'pyodbc'. 
**If I repack another .pex file with pyodbc 4.0.32 installed, then everything will be fine**.
I followed the installation instructions but with no luck, even I place a RUN pip install pyodbc in my docker file won't help.
PS: I tried both msodbcsql17 and msodbcsql18, both are not working.

Here's my docker file
FROM python:3.10.4
COPY myapplication.pex /myapplication.pex

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/msprod.list \
    && exit

RUN apt-get update \
    && ACCEPT_EULA=Y apt-get -y install mssql-tools unixodbc

EXPOSE 8080 80
ENTRYPOINT ["/bin/bash"]

**Comment by v-chojas** [comment]
Check the python module search path and ensure the pyodbc module is present in it.

**Comment by icymoonicy** [comment]
![image](https://user-images.githubusercontent.com/17135739/230235121-49c3961d-df86-49ae-9497-4ecc541c1e1f.png)
I unpacked the .pex file and indeed pyodbc module is present.

**Comment by v-chojas** [comment]
On Windows I believe it should be a .dll, on Linuxes it's a .so . I see neither of that there.

(As you mentioned your OS is Ubuntu, it doesn't make sense that you seem to be showing a set of files from  _Windows_ , so make sure you're giving us the right information.)
