### ISSUE TITLE
Commit points to none existing GitHub security advisory

### ISSUE THREAD

**Issue by abergmann** [mkleehammer/pyodbc#1201]
The description of commit [6b107a2](https://github.com/mkleehammer/pyodbc/commit/6b107a2bcaf7379e5ba182007b6ecae1bc2fc931) points to GitHub security advisory **GHSA-pm6v-h62r-rwx8** that does not exist anywhere.

Was this a typo inside the commit description or is the GHSA not public (yet)?

Was there a CVE assigned to the issue?

**Comment by mkleehammer** [comment]
A CVE was not assigned.
