### ISSUE TITLE
UnicodeDecodeError on table value functions with non ASCII column names

### ISSUE THREAD

**Issue by roskakori** [mkleehammer/pyodbc#121]
This might be related to the general issue #112, but as it's a very specific case with exampel code and infrastrcuture details, I decided to open a separate issue:

When running an SQL query that accesses a table value function (TVF) with non ASCII characters in the column name (e.g. `ä`), pyodbc fails with:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1: invalid continuation byte

To reproduce this, first create a trivial table value function TVF_temp that returns a single value with the heading "Waehrung" (ASCIIfied German for "currency"):

``` sql
use SomeDatabase;

if object_id('SomeDatabase.dbo.TVF_temp') is not null
    drop function dbo.TVF_temp;
go

create function dbo.TVF_temp(@Waehrung char(1)) returns table as return
select @Waehrung as [Waehrung];
go
```

Using SQL Server Management Studio, it is possible to query this function:

``` sql
select * from dbo.TVF_temp('€');
```

As expected, the result is:

```
Waehrung
--------
€

(1 row(s) affected)
```

Now run the same query using Python and pyodbc (replace `SomeServer` and `SomeDatabase` by approriate values and possibly add additonal connection parameters):

``` python
# -*- coding: utf-8 -*-
import logging
import pyodbc
from contextlib import closing

# Specify connection.
server = 'SomeServer'
database = 'SomeDatabase'
connection_string = 'DRIVER={{SQL Server}};SERVER={server};DATABASE={database}'.format(server=server, database=database)
query_statement = "select * from dbo.TVF_temp('€')"

# Setup logging.
_log = logging.getLogger('temp')
logging.basicConfig(level=logging.INFO)

_log.info('connecting to %s', connection_string)
with pyodbc.connect(connection_string) as connection:
    with closing(connection.cursor()) as cursor:
        _log.info
        try:
            for row in cursor.execute(query_statement):
                _log.info('row=%s', row)
        except UnicodeDecodeError as error:
            _log.error('error.args=%s', error.args)
            raise
_log.info('done')
```

With Python 3.5, the output is as expected:

```
INFO:temp:connecting to DRIVER={SQL Server};SERVER=...;DATABASE=...
INFO:temp:row = ('€', )
INFO:temp:done
```

This is exactly what was desired, so passing data and retrieving results with Unicode characters works fine.

Now change the column name `[Waehrung]` to `[Währung]`:

``` sql
create function dbo.TVF_temp(@Waehrung char(1)) returns table as return
select @Waehrung as [Währung];
go
```

In SQL Server Management Studio this still yields the expected result, with a nice "ä" in the Heading:

```
Währung
-------
€

(1 row(s) affected)
```

Running the Python code again though fails with:

```
INFO:temp:connecting to DRIVER={SQL Server};SERVER=...;DATABASE=...
ERROR:temp:error.args=('utf-8', b'W\xe4hrung', 1, 2, 'invalid continuation byte')
Traceback (most recent call last):
  File "C:\Temp\pyodbc_unicode_error.py", line 23, in <module>
    for row in cursor.execute(query_statement):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 1: invalid continuation byte
```

In error.args you can see that "Währung" is encoded using CP1252 (b'W\xe4hrung'), nevertheless pyodbc attempts to decode it as UTF-8.

Adding CHARSET=UTF-8 to the connection string does not change this.

When researching the topic, I found the following ODBC Unicode tutorial: ​https://www.progress.com/odbc/resources/tutorials/unicode/non-unicode. According to this it seems that on Unix ODBC indeeed uses UTF-8 while under Windows it's either CP1252 or UTF16/UCS2.

Interestingly, running the above code with Python 2.6 yields the following result:

```
INFO:temp:connecting to DRIVER={SQL Server};SERVER=...;DATABASE=...
INFO:temp:row = ('\x80', )
INFO:temp:done
```

So it works, but Python just uses a byte string to represent the result, effectively leaving the CP1252 Euro Sign at 0x80 instead of translating it to the Unicode code point 0x20ac. I only added this example for comparison, I don't expect any fixes or changes for the dated pyodbc version we were using with Python 2.

So seemingly proper Unicode translation happens for queries sent, parameters specified and results transmitted over ODBC. For indirectly quering columns names used by table value functions, no translation takes placed and things are left to the mercy of Python default encoding. Which in case of Python 3's default result in a UnicodeDecodeError when attempting to decode CP1252 using UTF-8.

Here are the details on the infrastructure used:

Python
- Python 3.5.1 (via Anaconda 3), pyodbc 3.0.10 
- Python 2.6.6, pyodbc 2.1.11 

MS SQL Server properties: 
- Version: 11.0.56133.0 
- Language: English 
- Server collation: Latin_1_General_CI_AS 
- Operating System: Windows NT 6.1 (7601) 
- Platform: NT x64 

ODBC Driver 1: 
- Name: SQL Server 
- Version: 6.01.7601.17514 
- File: SQLSRV32.DDL 

ODBC Driver 2 (same result): 
- SQL Server Native Client 11.0 
- Version: 2011.110.3000.00 
- SQLNCLI11.DDL

**Comment by mkleehammer** [comment]
I believe Unicode issues are fixed in the newly released 4.0.0 version.
