### ISSUE TITLE
What could cause a problem with pyodbc and SQL Server tempdb?

### ISSUE THREAD

**Issue by preneram** [mkleehammer/pyodbc#1220]
What could cause a problem with pyodbc and SQL Server tempdb?

When executing a user stored procedure on some database on SQL Server, tempdb properties are not accessible and templog shrinking (for processes running parallel) is somehow blocked. The usp makes use of tempdb during execution.

Therefore, templog is growing infinitely if there is no “close” while debugging (and temporarily during regular execution). 

Running the same usp with Excel Power query has no influence on accessing tempdb properties.

**Comment by gordthompson** [comment]
Have you tried connecting with `autocommit=True` to see if that makes any difference?

**Comment by preneram** [comment]
Thank you for your replies!
With "autocommit=True" the problem is solved in our use case.
Does it mean pyodbc is always using transactions for any executed SQL if auto commit is not set True?
Do I understand this right? It does something like:

 begin transaction

 exec dbo.LongRunningUspUsingTempdb @takesometime = 3600

 commit transaction

**Comment by v-chojas** [comment]
Autocommit is by default off, hence you would need to commit transaction manually.
