### ISSUE TITLE
windows11, connection closed by sqlserver: ('01000', '[01000] [Microsoft][ODBC SQL Server Driver][DBNETLIB]ConnectionWrite (send()). (10054) (SQLExecDirectW); [01000] [Microsoft][ODBC SQL Server Driver][DBNETLIB]General network error. Check your network documentation. (11)')

### ISSUE THREAD

**Issue by witss** [mkleehammer/pyodbc#1224]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.10.9
- pyodbc: 4.0.34
- OS: windows11
- DB: sqlserver 2019
- driver: SQL Server

### Issue
Connection used to keepalive in windows10 and windows server 2019, but when I use windows11, it always be closed by sqlserver in a random period, sometimes  8 minutes, sometimes 2 hours after established.
`conn = pyodbc.connect('DRIVER={SQL Server};SERVER=Stock1;DATABASE=TestDB;UID=r_front;PWD=12345611')`
I have already tried using ODBC Driver 17 for SQL Server but the problem still occured.
Thanks a lot for your help.

**Comment by v-chojas** [comment]
> sometimes 8 minutes, sometimes 2 hours after established.

Is that the amount of time the connection spends idle, and are you connecting to the same server you were before? If so, it is unlikely to be a problem in the driver nor pyODBC, and more likely one in the network stack of the OS.

If you use ODBC Driver 17.4 for SQL Server or newer, you can try to set the KeepAlive/KeepAliveInterval options: https://learn.microsoft.com/en-us/sql/connect/odbc/windows/features-of-the-microsoft-odbc-driver-for-sql-server-on-windows?view=sql-server-ver16#microsoft-odbc-driver-174-for-sql-server-on-windows

This does not appear to be a pyODBC issue.

**Comment by witss** [comment]
> > sometimes 8 minutes, sometimes 2 hours after established.
> 
> Is that the amount of time the connection spends idle, and are you connecting to the same server you were before? If so, it is unlikely to be a problem in the driver nor pyODBC, and more likely one in the network stack of the OS.
> 
> If you use ODBC Driver 17.4 for SQL Server or newer, you can try to set the KeepAlive/KeepAliveInterval options: https://learn.microsoft.com/en-us/sql/connect/odbc/windows/features-of-the-microsoft-odbc-driver-for-sql-server-on-windows?view=sql-server-ver16#microsoft-odbc-driver-174-for-sql-server-on-windows
> 
> This does not appear to be a pyODBC issue.

It's not the connection spends idle, I just made a loop to call the connection every minute,  and just connected to the same server. I will try ODBC Driver 18 for SQL Server, thank you.

**Comment by v-chojas** [comment]
That seems more like a network/OS issue than a driver issue.

**Comment by witss** [comment]
> That seems more like a network/OS issue than a driver issue.

I think so, the mstsc sometimes loss connection, too. I'll close this issue, thank's again.
