### ISSUE TITLE
Pip install fails for 4.0.39 on Windows 10, Python 2.7

### ISSUE THREAD

**Issue by nivlac96** [mkleehammer/pyodbc#1230]
### Environment

- Python: 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
- pyodbc: 4.0.39
- OS: Windows 10 Enterprise
- DB:
- driver:

### Issue

Pip install fails repeatedly with red text shown below. Was able to install version 4.0.35 instead without issue

![image](https://github.com/mkleehammer/pyodbc/assets/11020507/2c1eb0d3-fbf7-4e07-8c2a-e1e61089ae7d)

**Comment by v-chojas** [comment]
Can you copy and paste that text? Dark red on black is absolutely unreadable.

**Comment by gordthompson** [comment]
pyodbc 4.0.35 has Windows wheels for Python 2.7

```
pyodbc-4.0.35-cp27-cp27m-win_amd64.whl  
pyodbc-4.0.35-cp27-cp27m-win32.whl
```

but pyodbc 4.0.39 only has wheels for Python 3. So if you want to install 4.0.39 for Python 2.7 you need to have the C++ compiler as indicated by the message

> error: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

(in the red-on-blue part).
