### ISSUE TITLE
'Query' object has no attribute 'explain_query' error while executing any query.

### ISSUE THREAD

**Issue by rolexsanches** [mkleehammer/pyodbc#1246]
To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.10
- pyodbc: 4.0.39
- OS: Any
- DB: MSSQL
- driver: django-mssql-backend 2.8.1

### Issue
'Query' object has no attribute 'explain_query' error while executing any query.

**Comment by v-chojas** [comment]
pyodbc has no 'query' object nor does any of its objects have 'explain_query' either.
What are you doing? It's not clear this has anything to do with pyodbc.

**Comment by absci** [comment]
You could try our [Django driver](https://github.com/microsoft/mssql-django).
