### ISSUE TITLE
pyODBC doesn't look for unixODBC, instead looks for iODBC

### ISSUE THREAD

**Issue by rholohan** [mkleehammer/pyodbc#125]
Each time I try to create a connection with pyodbc, it gives me the following error:

```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-12-607f0d66e615> in <module>()
      1 pyodbc.connect(
----> 2     'DRIVER=FreeTDS;'
      3     'SERVER= MyServerIP;'
      4     'PORT=1433;'
      5     'DATABASE= DatabaseName;'

Error: ('00000', '[00000] [iODBC][Driver Manager]dlopen(FreeTDS, 6): image not found (0) (SQLDriverConnect)')
```

What concerns me is the reference to the iODBC driver, because I installed unixODBC and I thought it was supposed to default to that (as of 3.0.10). 

This python code that I used: 

```
import pyodbc

pyodbc.connect(
    'DRIVER=FreeTDS;'
    'SERVER=MyServerIP;'
    'PORT=1433;'
    'DATABASE= DatabaseName;'
    'UID=MyUsername;'
    'PWD=MyPassword')
```

I installed pyodbc through conda install pyodbc, and have confirmed it's version 3.0.10.  

I should add: 
1) I've reproduced identical results on three separate Macs
2) I've confirmed good installs of unixODBC and FreeTDS by establishing good connections through isql and tsql commands from the Terminal

**Comment by mkleehammer** [comment]
The choice between iODBC and unixODBC is made at compile time by the setup.py file.  I wish this was not the case, but the two projects both provide a core library and they are compiled very differently.

There is a commit on 2015-04-24 which removes iODBC since Apple no longer supports it, so someone must have gone out of their way to build it like that.

I'm not sure what version you are on, but have you tried installing it via pip instead?  I was providing binary wheels for OS X for Yosemite that are backwards compatible with 10.6.  Please try that and let me know if that works.

**Comment by rholohan** [comment]
I was actually able to solve my issue by rolling back to pyODBC version
3.0.9.  The only thing I can think is that whoever uploaded it to the
anaconda.org repository must have edited the setup.py file to specify
iODBC.  While that’s obviously not your issue, it’s the version anaconda
uses by default, so anyone using a mac and the anaconda python distribution
is going to run into the problem.

Thanks for getting back to me, I have my specific issue solved.  Hope you
don’t keep hearing about this, it was a pain to figure out.

Rich



-- 
Richard Holohan

On June 29, 2016 at 6:00:41 PM, Michael Kleehammer (notifications@github.com)
wrote:

The choice between iODBC and unixODBC is made at compile time by the
setup.py file. I wish this was not the case, but the two projects both
provide a core library and they are compiled very differently.

There is a commit on 2015-04-24 which removes iODBC since Apple no longer
supports it, so someone must have gone out of their way to build it like
that.

I'm not sure what version you are on, but have you tried installing it via
pip instead? I was providing binary wheels for OS X for Yosemite that are
backwards compatible with 10.6. Please try that and let me know if that
works.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mkleehammer/pyodbc/issues/125#issuecomment-229502393>,
or mute the thread
<https://github.com/notifications/unsubscribe/ALyMEnnaYYl00DOPR5R3_T8Bw-NRpuQ5ks5qQusGgaJpZM4I7WrD>
.

**Comment by sculpturearts** [comment]
I was receiving this message with Anaconda pyodbc 3.0.10 on Python 3.5.2 Anaconda:
`pyodbc.DataError: ('22021', '[22021] ERROR: invalid byte sequence for encoding "UTF8": 0xe0 0x81 0xb3;\nError while executing the query (7) (SQLExecDirectW)')`
I built an Anaconda Python 3.4.5 environment with Anaconda pyodbc 3.0.9. The error was not encountered.

**Comment by sculpturearts** [comment]
I tried a pip install of pyodbc of 3.0.10 into my Anaconda package space. This pip version of pyodbc is working as expected. I left a posting on the Anaconda Google Group about the problem.
