### ISSUE TITLE
Error with SQL_Autocommit_Off not implemented?

### ISSUE THREAD

**Issue by pineliu** [mkleehammer/pyodbc#127]
Hello,

I am trying to connect to a ODBC data source but got this error. Could you please help me with it? Thank you very much!

  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HYC00', "[HYC00] The 'SQL_AUTOCOMMIT_OFF' for the 'SQL_ATTR_AUTO
COMMIT' is not implemented. (0) (SQLSetConnnectAttr(SQL_ATTR_AUTOCOMMIT))")

**Comment by skillian** [comment]
Hi, @pineliu,

What type of ODBC datasource are you connecting to and what driver are you using?

**Comment by mkleehammer** [comment]
Your driver apparently does not support autocommit=False, which is the default.  (Perhaps it doesn't support transactions?). The only workaround is to set it to True:

    cnxn = pyodbc.connect(..., autocommit=True)
