### ISSUE TITLE
Error is raised only if the first dataset is the one containing an error

### ISSUE THREAD

**Issue by tjader** [mkleehammer/pyodbc#128]
When I execute multiple statements, and there is an error in another dataset than the first, no exception is raised.
To reproduce this on MS SQL, 
1. create a table containing a column of type int. (e.g my_table)
2. Connect and execute this this

``` python
statement ='''INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (1);
INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (2);
INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (100000000000);'''
result = cursor.execute(statement)
```

The last statement is invalid and should raise the following error

``` python
DataError: ('22003', '[22003] [DataDirect][ODBC SQL Server Wire Protocol driver][Microsoft SQL Server]Arithmetic overflow error converting expression to data type int. (8115) (SQLExecDirectW)')
```

But no error is raised.
Now, if the statements would have occured in a different order, with the last statement first, the error above is raised

``` python
statement ='''INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (100000000000);
INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (2);
INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (1);'''
result = cursor.execute(statement)
```

The error is reproduced in pyodbc 3.0.10 on a linux machine (using an anaconda environment)

**Comment by gordthompson** [comment]
I suspect that 

```
statement ='''SET NOCOUNT ON;
INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (1);
INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (2);
INSERT INTO eu_modeldb_l.ship_tracking.overflow_test VALUES (100000000000);'''
```
would avoid the issue.

**Comment by mkleehammer** [comment]
gordthompson is correct.  It is supposed to work like that so you can retrieve the number of updates (rowcount) for each statement, etc.
