### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by kevCurnow** [mkleehammer/pyodbc#1286]
Was trying to run pip install pyodbc, but got an error that says Microsoft Visual C++ 14.0 or greater is required. I already have visual studio, but went ahead and downloaded the build tools just in case. Currently working with the latest version of python (3.12.0). Is it not supported yet?

**Comment by v-chojas** [comment]
What's the exact message?

**Comment by gordthompson** [comment]
try

```
pip install --pre pyodbc
```

pyodbc version 5.0 hasn't been officially released yet.

**Comment by kevCurnow** [comment]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

ERROR: Failed building wheel for pyodbc

ERROR: Could not build wheels for pyodbc, which is required to install pyproject.toml-based projects

**Comment by MavericSB** [comment]
I ran into similar issues when building a docker container yesterday as well (from python:3-bullseye).  I saw there's an open PR for for 3.12 support but it hasn't been merged yet  #1275.  I'm thinking the wheels for 3.12 are not being built and published to PyPI?  I personally rolled back to 3.11.6 and had no issues, but I would suspect there's desire to expand support to 3.12.0.

**Comment by kevCurnow** [comment]
Yes, just needed to rollback
