### ISSUE TITLE
No Python 3.12 binary wheels in PyPI

### ISSUE THREAD

**Issue by Kapparina** [mkleehammer/pyodbc#1287]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.12.0
- pyodbc: 5.0.0b3
- OS: Windows 10 64 bit

### Issue

Installing pyodbc via pip does not work using Python 3.12 using the provided .whl file uploaded to PyPi. The compatible tags from my pip are below. Note that the latest prerelease version of pyodbc (https://pypi.org/project/pyodbc/5.0.0b3/#files) is named "
pyodbc-5.0.0b3-cp311-cp311-win_amd64.whl" - the tags "cp311-cp311" are not valid. Renaming the downloaded wheel file before attempting installation worked fine.

Compatible tags: 42
  cp312-cp312-win_amd64
  cp312-abi3-win_amd64
  cp312-none-win_amd64
  cp311-abi3-win_amd64
  cp310-abi3-win_amd64
  cp39-abi3-win_amd64
  cp38-abi3-win_amd64
  cp37-abi3-win_amd64
  cp36-abi3-win_amd64
  cp35-abi3-win_amd64
  cp34-abi3-win_amd64
  cp33-abi3-win_amd64
  cp32-abi3-win_amd64
  py312-none-win_amd64
  py3-none-win_amd64
  py311-none-win_amd64
  py310-none-win_amd64
  py39-none-win_amd64
  py38-none-win_amd64
  py37-none-win_amd64
  py36-none-win_amd64
  py35-none-win_amd64
  py34-none-win_amd64
  py33-none-win_amd64
  py32-none-win_amd64
  py31-none-win_amd64
  py30-none-win_amd64
  cp312-none-any
  py312-none-any
  py3-none-any
  py311-none-any
  py310-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

**Comment by mkleehammer** [comment]
Version 5.0.0 has been prepared for Python 3.12, but we won't have binary builds for Windows until AppVeyor adds support for it.  If they take too long we'll manually build some an upload.

https://github.com/appveyor/ci/issues/3879

**Comment by mkleehammer** [comment]
Version 5.0.0, which I hope to release today, will have Python 3.12 support.

**Comment by mkleehammer** [comment]
Uploaded!
