### ISSUE TITLE
pyodbc 5.0.0 core dump on connecting with token to mssql

### ISSUE THREAD

**Issue by karoldob** [mkleehammer/pyodbc#1289]
### Environment

- Python: 3.10.12
- pyodbc: 5.0.0
- sqlalchemy: 2.0.21
- OS: Ubuntu 22.04 64bit
- DB: MSSQL (AzureSQL)
- driver:  Microsoft ODBC Driver 18 for SQL Server (/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.2.1)
- login method: token

### Issue
Trying to connect with token as described in:
https://docs.sqlalchemy.org/en/20/dialects/mssql.html#connecting-to-databases-with-access-tokens

How to reproduce:
- login with `az login` on your machine (in MS way)
- copy-paste sample code from the link and fill server/database
- add `engine.connect()` at the end
- observe segmentation fault (core dumped)

Observations:
pyodbc 4.0.38 is not affected - above samples works well
Just `pip install --upgrade pyodbc==4.0.38` solves the issue, in the same environment
Login with user-password works well

Trace in attachment
[odbctrace.log](https://github.com/mkleehammer/pyodbc/files/12862265/odbctrace.log)

**Comment by karoldob** [comment]
Yes, already tested with this samples:
https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Linux#connecting-to-servers-with-access-tokens

Behavior is the same: segfault on pyodbc 5.0.0, normal working on 4.0.38

**Comment by keitherskine** [comment]
Hi @karoldob , as an experiment, could I ask you to try using a bytearray rather than bytes for the access token in your call to pyodbc.connect.  That is, instead of:
```
cnxn = pyodbc.connect(connection_string, attrs_before={SQL_COPT_SS_ACCESS_TOKEN: token_struct})
```
try:
```
cnxn = pyodbc.connect(connection_string, attrs_before={SQL_COPT_SS_ACCESS_TOKEN: bytearray(token_struct)})
```
It might work.  (But of course bytes should work too.)  Many thanks.

**Comment by jacovg91** [comment]
Just reporting in here, not sure if there is any relationship, but we have noticed, using Pyodbc 5.0.0, this morning we are no longer able to connect to Azure SQL database. This stopped working over night. We are also using token authentication (to Azure) using the msal library. Getting `InterfaceError: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user ''. (18456) (SQLDriverConnect)")`

100% certain right user and password (clientId & secret) are used and neither are expired.

**Comment by karoldob** [comment]
@keitherskine 
Thanks, `bytearray(token_struct)` instead `token_struct` solved issue. But now I'm not sure to close or not: it will be changed internally or just updated documenattion (with bytearray) :)

**Comment by jacovg91** [comment]
Changing to `bytearray(token_struct)` didn't work for us.

Python: 3.9.5
pyodbc: 5.0.0
sqlalchemy:  1.4.0
OS: Linux (Databricks)
DB: MSSQL (AzureSQL)
driver: Microsoft ODBC Driver 18 for SQL Server (/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.2.1)
login method: token using msal

**Comment by keitherskine** [comment]
Hi @karoldob , please do keep this issue open.  This looks like a genuine bug.

**Comment by jabbera** [comment]
4.0.39 has the same issue, but get's lucky to not hit the bug I think.

**Comment by v-chojas** [comment]
Is the token being freed before it gets used in the connect?

**Comment by v-chojas** [comment]
What parameters are you seeing in your SQLSetConnectAttrW call for the access token? Looks like it's somehow going through the string conversion path, which shouldn't be reached by this code path. Also, is that with or without the proposed fix at https://github.com/mkleehammer/pyodbc/pull/1290 ?

**Comment by jabbera** [comment]
@v-chojas ugh, I had a bug i my test harness causing it to go down the string path. The PR does indeed fix the issue!

**Comment by mkleehammer** [comment]
The pull request keitherskine, 1290, fixes this it sounds like.  I'm releasing 5.0.1 with this fix now.  Please reopen if I missed something.

Thanks everyone for troubleshooting this.
