### ISSUE TITLE
DriverConnect Error with pyodbc 5.0.1 using Tibero ODBC driver 

### ISSUE THREAD

**Issue by kjungw1025** [mkleehammer/pyodbc#1303]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.10
- pyodbc: 5.0.1
- OS: Ubuntu 20.04 LTS
- DB: Tibero6
- driver: libtbodbc.so provided by Tibero6 and unixodbc-dev 2.3.6-0.1build1

### Issue
On the pypi.org site, I checked that Python 3.8 or higher was required to use version pyodbc 5.0.1 and tried installing and running version pyodbc 5.0.1, but the following error occurred.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('I000', '[I000]   (-2048) (SQLDriverConnect)')
```
However, lowering the pyodbc version to 4.0.39 fixed the issue.
I'm writing to be a little helpful to those who have similar problems with me!

**Comment by gordthompson** [comment]
Thanks for reporting!

**Comment by ide127** [comment]
You save my hours
