### ISSUE TITLE
Python ODBC sql error on WSL2 environment

### ISSUE THREAD

**Issue by jagathprasanga** [mkleehammer/pyodbc#1304]
To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.10.12 64bit
- pyodbc: 5.0.1
- OS: Ubuntu 22.04.2 LTS on Windows 11 WSL2
- DB: MS SQL Server 2019
- driver:libmsodbcsql-18.3.so.2.1

Cant select more than 53 raws (the number changes with number of columns selected)

The below code hangs at indicated line with this error;
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 18 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)')

<img width="581" alt="image" src="https://github.com/mkleehammer/pyodbc/assets/10453671/786ae52c-6ee9-4142-a7de-cdce02f08bf4">

But below code runs with out any issue;
<img width="567" alt="image" src="https://github.com/mkleehammer/pyodbc/assets/10453671/a9a19bf7-d56d-40c1-9d4a-6dae2031a3ab">

But I can retrieve all rows without any issue using other SQL Server tools.

**Comment by v-chojas** [comment]
Why do you have both "ENCRYPT" and "Encrypt" in your connection string?
Could you post an ODBC trace of this error?

Also, please post actual code instead of images --- it's hard to read images.

**Comment by jagathprasanga** [comment]
def  sql_test3(self):
        server = 'tcp:hqwin21s.ceb.local\SQLSERVER,1433'
        database = 'BreakdownAssist'
        username = 'cebcaresystem'
        password = '2UGP#tpybjfoe69nftRof8'
        driver = 'DRIVER={/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.2.1};'
        connection = pyodbc.connect(driver+ 'SERVER=' + 
                                    server + ';DATABASE=' + database + ';ENCRYPT=yes;UID=' + username + ';PWD=' + 
                                    password + ';TrustServerCertificate=yes;Encrypt=no;')

        cursor = connection.cursor()
        cursor.execute("SELECT top 50 areaid, CenterLon, CenterLat  FROM AreaList order by areaid")
        row = cursor.fetchone()
        while row:
            print(row)
            row = cursor.fetchone()
        cursor.close()
        connection.close()

**Comment by jagathprasanga** [comment]
def  sql_test3(self):
        server = 'tcp:hqwin21s.ceb.local\SQLSERVER,1433'
        database = 'BreakdownAssist'
        username = 'cebcaresystem'
        password = '2UGP#tpybjfoe69nftRof8'
        driver = 'DRIVER={/opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.3.so.2.1};'
        connection = pyodbc.connect(driver+ 'SERVER=' + 
                                    server + ';DATABASE=' + database + ';UID=' + username + ';PWD=' + 
                                    password + ';TrustServerCertificate=yes;Encrypt=no;')

        cursor = connection.cursor()
        cursor.execute("SELECT top 500 areaid, CenterLon, CenterLat  FROM AreaList order by areaid")
        row = cursor.fetchone()
        while row:
            print(row)
            row = cursor.fetchone()
        cursor.close()
        connection.close()

**Comment by jagathprasanga** [comment]
ENCRYPT/Encrypt issue corrected, but not solved. Anyway, thanks for the reply.

**Comment by v-chojas** [comment]
I shall ask again. Can you post an ODBC trace?

**Comment by jagathprasanga** [comment]
Sorry, I dont know how to get it, i tried to add  below lines to odbcinst.ini file but it is write protected 
Trace=Yes
TraceFile=/home/user/odbclog/odbctrace18.log

**Comment by v-chojas** [comment]
https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log

**Comment by gordthompson** [comment]
Possibly related:

https://stackoverflow.com/a/72806836/2144390
