### ISSUE TITLE
Inconsistent license information

### ISSUE THREAD

**Issue by stefan6419846** [mkleehammer/pyodbc#1314]
When looking at the package source code, I observed that the package advertises two different variants of the MIT license: The "plain" MIT and the MIT-0 one.

While the license file and the source files use the MIT-0 license, both the `pyproject.toml` and the `setup.py` file refer to the "plain" MIT license: https://github.com/mkleehammer/pyodbc/blob/bc5b7c6f50f71aa776f881fafce95328338ed35e/setup.py#L58 https://github.com/mkleehammer/pyodbc/blob/bc5b7c6f50f71aa776f881fafce95328338ed35e/setup.py#L63 https://github.com/mkleehammer/pyodbc/blob/bc5b7c6f50f71aa776f881fafce95328338ed35e/pyproject.toml#L13 https://github.com/mkleehammer/pyodbc/blob/bc5b7c6f50f71aa776f881fafce95328338ed35e/pyproject.toml#L25 The correct SPDX identifier seems to be `MIT-0`, the correct trove classifier `License :: OSI Approved :: MIT No Attribution License (MIT-0)`.

**Comment by mkleehammer** [comment]
Thanks for catching this.  We'll update to MIT-0.
