### ISSUE TITLE
Support for SQL_BLOB ODBC SQL type -98

### ISSUE THREAD

**Issue by rupurt** [mkleehammer/pyodbc#1318]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.11.6
- pyodbc: 5.0.1
- OS: Linux
- DB: Db2
- driver: IBM Db2 ODBC

### Issue

Howdy :wave:,

Do you have any plans to support the `ODBC` type `SQL_BLOB`? I'm currently getting the error message from Db2 results.

```shell
'ODBC SQL type -98 is not yet supported.  column-index=5  type=-98', 'HY106'
```

An example query to replicate the issue is:

```sql
SELECT * FROM SYSIBM.SYSTABLES
```

If not, I can try and poke around the IBM Db2 python driver to see if I can adapt that code to `pyodbc`.

Cheers

**Comment by v-chojas** [comment]
You can add an output converter function to handle DB-specific types: https://github.com/mkleehammer/pyodbc/wiki/Using-an-Output-Converter-function

**Comment by rupurt** [comment]
Beautiful. Thank you for pointer @v-chojas
