### ISSUE TITLE
Build failure with Python 3.5.1, Windows, Visual Studio 2015

### ISSUE THREAD

**Issue by danizen** [mkleehammer/pyodbc#132]
I get this error: 

```
   File "c:\tools\python\3.5.1\lib\distutils\util.py", line 125, in convert_path
     raise ValueError("path '%s' cannot be absolute" % pathname)
 ValueError: path '/Users/mkleehammer/dev/pyodbc/src/buffer.cpp' cannot be absolute
```

I may try to fix it, and if so, will issue pull request.

**Comment by danizen** [comment]
`./setup.py build` works, but `./setup.py bdist_wheel` does not.

Christophe Gohlke has a build - http://www.lfd.uci.edu/~gohlke/pythonlibs/
I will ask him how he did it and see whether I can make it automatic by tweaking setup.py

**Comment by danizen** [comment]
On the face of it, this is a duplicate of issue #77, but getting a build that worked for Christophe Gohlke without integrating what he did to fix it doesn't seem like a real solution, but rather a work-around.

Let's leave this open for a bit while I look for a fix.

**Comment by danizen** [comment]
This is a duplicate of issue #82, and pip install from master works.

**Comment by KamodaP** [comment]
+1 here (issue as well)
and it does work with downloaded source

**Comment by mkleehammer** [comment]
I just merged a pull request that fixes this.  Thanks.

**Comment by danizen** [comment]
Thanks.

**Comment by atocyo** [comment]
Issue still present.
