### ISSUE TITLE
Can't build release artifacts due to cibuildwheel issue

### ISSUE THREAD

**Issue by mkleehammer** [mkleehammer/pyodbc#1324]
Cannot build wheels on Windows due to this error:

https://github.com/pypa/cibuildwheel/issues/1748

https://github.com/pypa/cibuildwheel/issues/1740

Unfortunately, it says it is fixed in v2.16.5, but that is the version we are using.

**Comment by mkleehammer** [comment]
@keitherskine Have you run into this?  Any ideas?

**Comment by mkleehammer** [comment]
The #1740 comment indicates it is sporadic for them.  Maybe GH is running different runner versions?

**Comment by mkleehammer** [comment]
Now I'm getting something else: Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3. For more information see: 

It appears GH is not being consistent.

**Comment by keitherskine** [comment]
I haven't seen this.  To test, I have manually kicked off the artifacts build for tag 5.0.1 (on mkleehammer/pyodbc).  Let's see if it completes successfully.  On my pyodbc fork, I didn't see an error after I updated the versions of the Github Action utilities.

**Comment by keitherskine** [comment]
Build run: https://github.com/mkleehammer/pyodbc/actions/runs/7787826214
Takes about 10-15 minutes.

**Comment by mkleehammer** [comment]
Your build is already past the error I'm seeing: https://github.com/mkleehammer/pyodbc/actions/runs/7769781696/job/21236111461

**Comment by keitherskine** [comment]
That build has completed and the zip files of wheels can be downloaded.

The [previous build](https://github.com/mkleehammer/pyodbc/actions/runs/7769781696) failed but that was based on commit bc5b7c6 which is not tag 5.0.1 (commit f075e33).  Is that the issue?

**Comment by keitherskine** [comment]
Meanwhile, the Appveyor build tests for tag 5.1.0 has completed:
https://ci.appveyor.com/project/mkleehammer/pyodbc/builds/49115239

**Comment by mkleehammer** [comment]
I've uploaded the binaries from your build.  I'm going to close this.  If the new GH workflow is having issues, I'm sure they'll be worked out before we need them again.

/close

**Comment by keitherskine** [comment]
Great stuff!  pyodbc appears to work on my M1 now "clean":
```
(pyodbc) /Users/keith/git/pyodbc $ python -m pip install pyodbc
Collecting pyodbc
  Downloading pyodbc-5.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.7 kB)
Downloading pyodbc-5.1.0-cp311-cp311-macosx_11_0_arm64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 3.3 MB/s eta 0:00:00
Installing collected packages: pyodbc
Successfully installed pyodbc-5.1.0
(pyodbc) Users/keith/git/pyodbc $ python -c "import pyodbc; print(pyodbc.version)"
5.1.0
(pyodbc) /Users/keith/git/pyodbc $ 
```
