### ISSUE TITLE
pyodbc and "Always Encrypted" feature of MS SQL Server 2016 Enterprise

### ISSUE THREAD

**Issue by azachert** [mkleehammer/pyodbc#133]
MS SQL Server 2016 Enterprise introduced "Always Encrypted" feature
https://msdn.microsoft.com/en-us/library/mt163865.aspx. 

Is there a plan to support it in pyodbc?

**Comment by mkleehammer** [comment]
Here's the ODBC specific background I looked at: https://msdn.microsoft.com/en-us/library/mt637351(v=sql.110).aspx

I was under the impression that it is possible to use it today as long as ColumnEncryption was enabled in the connection string and parameters are used for passing values, which is what pyodbc already does.  In other words, I was under the impression that the driver and server do most of the work.

I looked through the new constants and didn't see anything that would be useful to implement, but I haven't actually used AE yet.

Can you first try the existing pyodbc with the appropriate driver (>= 13.1) and see how it goes.  I believe it will work.

**Comment by nannanav** [comment]
It does not work with driver 17. The values I get are encrypted and not sure how to decrypt or how to insert! Help is appreciated!!

**Comment by v-chojas** [comment]
You need to add `ColumnEncryption=Enabled` to the connection string. This will be sufficient for decrypting data upon retrieval, but for insertion you need to use parameters instead of literals and keep in mind the constraints. See the documentation for more information -> https://docs.microsoft.com/en-us/sql/connect/odbc/using-always-encrypted-with-the-odbc-driver

**Comment by nannanav** [comment]
Okay, I got it. The permissions I mentioned above are enabled by default.  We need to pass the following additional parameters in the connection string:
KeyStoreAuthentication=KeyVaultClientSecret
KeyStorePrincipalId={client_id}
KeyStoreSecret={client_secret}

**Comment by v-chojas** [comment]
Yes, if you are using AKV for your keys then you need to supply the credentials for it too.

To insert, you need to use parameters. That linked document has a list of limitations you should keep in mind when using AE.
