### ISSUE TITLE
Transaction is not getting rolled back

### ISSUE THREAD

**Issue by SumitDangat** [mkleehammer/pyodbc#1335]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.9.18(64 bit)
- pyodbc: 5.1.0
- OS: Windows
- DB: MSSQL 
- driver: ODBC Driver 17 for SQL Server

### Issue: observed behavior

```python
import pyodbc
import pandas as pd

from pyodbc import apilevel


class DBConnection:
    def __init__(self):
        self.conn = None
        self.error_occurred = False

    def __enter__(self):
        try:
            # Initialize the connection
            self.conn = pyodbc.connect()
            # Begin transaction
            self.conn.autocommit = False
            self.error_occurred = False
            return self
        except Exception as e:
            print(f"Error occurred while establishing connection: {e}")
            raise

    def __exit__(self, exc_type, exc_value, traceback):
        try:
            if self.conn:
                if exc_type is not None or self.error_occurred:
                    # Rollback transaction if exception occurred
                    print(f"exception received here--->{exc_type}")
                    self.conn.rollback()
                    self.error_occurred = False
                else:
                    print("Coming for commit--->")
                    # Commit transaction if no exception occurred
                    self.conn.commit()
                # Reset autocommit to default value
                self.conn.close()
        except Exception as e:
            print(f"Error occurred while closing connection: {e}")

    def select_data(self, query):
        try:
            with self.conn.cursor() as cursor:
                cursor.execute(query)
                rows = cursor.fetchall()
                if rows:
                    columns = [str(column[0]) for column in cursor.description]
                    df = pd.DataFrame.from_records(rows, columns=columns)
                    return df
                else:
                    return pd.DataFrame()
        except Exception as e:
            print(f"Error occurred while executing select query: {e}")
            raise

    def bulk_update(self, table, updates):
        try:
            with self.conn.cursor() as cursor:
                for update in updates:
                    update_query = f"UPDATE {table} SET {', '.join([f'{col} = ?' for col in update['columns']])} WHERE {update['condition']}"
                    cursor.execute(update_query, update['values'])
        except Exception as e:
            print(f"Error occurred while bulk updating data: {e}")
            self.error_occurred = True
            raise

    def single_insert(self, table, data):
        """
        Perform a single insert operation for a row of data into the specified table.

        Args:
            table (str): The name of the table where the data will be inserted.
            data (dict): A dictionary representing the data to be inserted.
                         The keys should correspond to column names and values
                         should correspond to the values to be inserted.

        Raises:
            Exception: If an error occurs during the insert operation.
        """
        try:
            with self.conn.cursor() as cursor:
                columns = ', '.join(data.keys())
                placeholders = ', '.join(['?' for _ in data.values()])
                insert_query = f"INSERT INTO {table} ({columns}) VALUES ({placeholders})"
                cursor.execute(insert_query, list(data.values()))
        except Exception as e:
            print(f"Error occurred while performing single insert: {e}")
            self.error_occurred = True
            raise

    def bulk_insert(self, table, df):
        try:
            with self.conn.cursor() as cursor:
                # Extract column names and values from the DataFrame
                columns = list(df.columns)
                values = df.values.tolist()
                # Generate the INSERT INTO query
                insert_query = f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({', '.join(['?'] * len(columns))})"
                # Execute the query
                cursor.executemany(insert_query, values)
        except Exception as e:
            print(f"Error occurred while bulk inserting data: {e}")
            self.error_occurred = True
            raise


df = pd.DataFrame({
    'mlc_component': ['1_bj'],
    'mlc_section': ['1_bj'],
    'mlc_key': ['1_bj'],
    'mlc_value': ['1_bj']
})

data_to_insert = {
    'mlc_component': '3_bj',
    'mlc_section': '3_bj',
    'mlc_key': '3_bj',
    'mlc_value': '3_bj'
}
data1_to_insert = {
    'mlc_component': '2_bj',
    'mlc_section': '2_bj',
    'mlc_key': '2_bj',
    'mlc_value': '2_bj'
}
with DBConnection() as db_conn:
    try:
        # db_conn.bulk_insert("guess.data_configuration", df)
        print("apilevel here--->", apilevel)
        cursor = db_conn.conn.cursor()
        cursor.execute("BEGIN TRANSACTION")  # Start transaction
        db_conn.bulk_insert('guess.data_configuration', df)
        db_conn.single_insert('guess.data_configuration', data_to_insert)
        db_conn.single_insert('guess.data_configuration', data_to_insert)
        cursor.execute("COMMIT TRANSACTION")  # Commit if both inserts succeed
        # db_conn.bulk_insert("data_configuration", df)
    except Exception as e:
        db_conn.error_occurred = True
        cursor.execute("ROLLBACK TRANSACTION")  # Rollback on any exception
        raise e

```
Here table in which data is getting inserted has primary key and in consecutive single insert I am inserting the same data which raises unique constraint violation error. So here expected behavior is to rollback the previous transactions but that is not observed. Table has 2 entries with the data mentioned in df and data_to_insert. 

To resolve this I have passed same cursor to all the methods defined the class and output is as per my expectations i.e. data is getting rollback for above use case. 

**which raises following questions:**

1. For same connections if the cursor is different then the transaction management will also be different?
2. How the connection management and transaction management takes place is it connection object is taking care of connection management and cursor is taking care of transaction management?
3. What is the ideal way to handle above situation?

**Comment by v-chojas** [comment]
1.Are you connecting with autocommit on or off?
2.Post an ODBC trace.

**Comment by SumitDangat** [comment]
> 1.Are you connecting with autocommit on or off? - Auto commit is off
2.Post an ODBC trace.
[ODBC_Trace.LOG](https://github.com/mkleehammer/pyodbc/files/14669128/ODBC_Trace.LOG)

**Comment by keitherskine** [comment]
@SumitDangat , there's a pyodbc wiki article that might be helpful here:
https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management

In short, you probably shouldn't be executing "COMMIT TRANSACTION" SQL commands (use `conn.commit()` instead), and if you want two concurrent database transactions, you'll have to open up two connections to the database.  Hope that helps.

**Comment by SumitDangat** [comment]
@keitherskine : Thanks for the prompt response.
**In above use case what I am trying is:**
BEGIN TRANSACTION
  INSERT INTO TABLE VALUES ...
  UPDATE TABLE SET ...
COMMIT TRANSACTION
In above code only one connection is created and within that multiple cursors are opened which you can see in bulk_insert() and single insert. as per the above reference link it should be rolled back when within one connection if any of the execute statement fails as per the code which is not happening. 
Help me with possible code changes in above code which can get me the expected results if possible :)

**Comment by keitherskine** [comment]
I think I see where the issue is, @SumitDangat .  It's the use of pyodbc context managers (`with self.conn...`).  It's not obvious, but pyodbc cursor context managers include an implicit commit.  This is described in the wiki here:
https://github.com/mkleehammer/pyodbc/wiki/Cursor#context-manager

So, instead of using `with self.conn.cursor() as cursor:`, I would either use just `cursor = self.conn.cursor()` or the [context.closing](https://docs.python.org/3/library/contextlib.html#contextlib.closing) utility, as described in the wiki:
```python
from contextlib import closing

with closing(self.conn.cursor()) as cursor:
    ...
```

**Comment by SumitDangat** [comment]
Thanks @keitherskine for providing valuable inputs. Given solution is working as per the expectations.
