### ISSUE TITLE
setting transaction isloation level for ms sql server

### ISSUE THREAD

**Issue by StudentForever** [mkleehammer/pyodbc#135]
Hi

I am connecting to ms sql server database using "autocommit = false" option to run queries in transaction.

Is there a way to set transaction isolation level for ms sql server ?

thanks

**Comment by skillian** [comment]
Hi, @StudentForever, it seems to work fine if I just execute `SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED` on the connection object:

```
>>> import pyodbc
>>> conn = pyodbc.connect("driver={sql server native client 11.0};server=sql.server;database=database;uid=username;pwd=password")
>>> conn.execute("set transaction isolation level read uncommitted;")
<pyodbc.Cursor object at 0x000002CA8AB849F0>
>>> cur = conn.cursor()
>>> r = cur.execute("select transaction_isolation_level from sys.dm_exec_sessions where session_id = @@SPID;").fetchone()
>>> r
(1, )
>>> 
```

Microsoft's article [here](https://msdn.microsoft.com/en-us/library/ms176013.aspx) says that 1 = ReadUncommitted.

**Comment by StudentForever** [comment]
thanks

**Comment by gecjmanish** [comment]
thank you
