### ISSUE TITLE
Do we need to close cursor in this case?

### ISSUE THREAD

**Issue by nishantvarma** [mkleehammer/pyodbc#1366]
I have a code that uses cursor directly like this:

```
def execute(session, query):
    connection = session.connection().connection
    cursor = connection.cursor()
    cursor.execute(query)
    description = cursor.description
    if description is not None:
        rows = cursor.fetchall()
    return rows

result = execute(session, "select 1")
```

I get "Connection is busy" errors when there is heavy load in the server. However, I don't see a possibility of this as:

1) I use single session per thread.
2) I always consume the results.
3) Cursor gets closed after it goes out of scope due to GC?

Is it better to use the [`closing` context-manager](https://github.com/mkleehammer/pyodbc/wiki/Connection#context-manager) in this case? There are some edge cases where `fetchall` might not get called (code not shown, presume that is not causing this).

```
def execute(session, query):
    connection = session.connection().connection
    with closing(connection.cursor()) as cursor:
        cursor.execute(query)
        description = cursor.description
        if description is not None:
            rows = cursor.fetchall()
    return rows

result = execute(session, "select 1")
```

Kindly let me know your thoughts.

**Comment by v-chojas** [comment]
Are you also making one connection to the database per thread?

**Comment by gordthompson** [comment]
Just to be clear: `session` is a SQLAlchemy `Session` object, correct?

**Comment by nishantvarma** [comment]
Thanks for checking, @v-chojas, @gordthompson . I forgot to add a small detail. Usually, the flow is like this:

def api():
    result = session.query(...)
    result = session.execute(...)
    result = execute(session, query) # legacy api
    ...

So, we use SQLAlchemy's [(scoped) `session`](https://docs.sqlalchemy.org/en/20/orm/contextual.html) to execute queries. I think it uses the same connection because it uses the `session.connection()` connection pool under the hood? This has been my observation so far. Are there problems mixing queries like this?

**Comment by v-chojas** [comment]
I don't know what driver or DB you're using, but some don't support having more than one simultaneous active resultset on the same connection.

**Comment by v-chojas** [comment]
You mention multiple threads and "heavy load".

**Comment by nishantvarma** [comment]
Yeah, but I am thinking that it is not possible for the same connection to use multiple cursors because: 1) scoped session returns the same connection always 2) executing multiple queries sequentially can't overlap over time.

**Comment by v-chojas** [comment]
I recommend you think more about what it means to have multiple threads and why it only happens under "heavy load".

**Comment by nishantvarma** [comment]
I will read more on that. Appreciate your help!
