### ISSUE TITLE
question about transaction with pyodbc

### ISSUE THREAD

**Issue by StudentForever** [mkleehammer/pyodbc#137]
Hi

I do not know what happens when autocommit is set to False , so I am using the following approach to explicitly call begin and commit transaction as I also need to set transaction isolation level (which based on my understanding needs to be set before starting the transaction). Is there any issue with this approach ?

```
with pyodbc.connect(connection_string, autocommit=True) as db_connection,\
            db_connection.cursor() as db_cursor:
        db_cursor.execute("SET TRANSACTION ISOLATION LEVEL SNAPSHOT;")
        db_cursor.execute("BEGIN TRANSACTION")
        t1 = time.time()
        for query in queries:
            db_cursor.execute(query)
        db_cursor.execute("COMMIT TRANSACTION")
```

thanks for your time

**Comment by mkleehammer** [comment]
When autocommit is False, which is the default and what is usually recommended if you are making updates, the database begins a transaction when the first statement is executed.  You can look up ODBC's autocommit handling to for details - pyodbc does not do anything special.  That is, it does not call begin transaction for you - the DB/driver handles it.

**Comment by mkleehammer** [comment]
What you are doing look like it would work.  I think it would work the same with autocommit set to False too.
