### ISSUE TITLE
Memory allocation error when inserting string of size 128

### ISSUE THREAD

**Issue by lazydev2** [mkleehammer/pyodbc#1375]
### Environment

- Python:  3.12.3
- pyodbc: 5.1.0
- OS: Ubuntu 24.04 LTS
- DB: MariaDB 1:10.11.8
- driver: odbc-mariadb, Version: 3.1.15-3

All environment components are defaults from the distro.
I took their version from `aptitude show package-name`

### Issue

Hello.
I found a bug on inserting data to mariadb via pyodbc, but I am not sure which component (pyodbc, mariadb driver or mariadb itself) is guilty.
Could you help me to find it, and also give some ideas of how to workaround the bug?

Buggy script:
```
#!/bin/python3

import pyodbc

conn = pyodbc.connect(f'DRIVER={{MariaDB Unicode}};User=db_user;Password=db_password;Database=db_name;Server=localhost;Port=3306')
cursor = conn.cursor()

cursor.execute('DROP TABLE IF EXISTS test_table')
cursor.execute('CREATE TABLE test_table(data varchar(255))')

data = "A" * 128

cursor.execute("INSERT INTO test_table (data) VALUES (?)", (data))
```

result:
```
$ ./testing_bug.py 
Traceback (most recent call last):
  File "/opt/doorphony/./testing_bug.py", line 13, in <module>
    cursor.execute("INSERT INTO test_table (data) VALUES (?)", (data))
pyodbc.OperationalError: ('HY001', '[HY001] [ma-3.1.15][10.11.8-MariaDB-0ubuntu0.24.04.1]Memory allocation error (0) (SQLPutData)')
```

**Comment by gordthompson** [comment]
I can reproduce the error. No error with `isql`.

[odbctrace.log](https://github.com/user-attachments/files/16521397/odbctrace.log)

**Comment by v-chojas** [comment]
This is very unusual, does it happen with pyODBC 4.x?

Looks like it's DAE'ing 255 bytes followed by 1 byte.

```
[ODBC][4334][1723022770.189265][SQLPutData.c][148]
		Entry:
			Statement = 0x28ff860
			Data = 0x782f9419efd0
			StrLen = 255
[ODBC][4334][1723022770.189671][SQLPutData.c][315]
		Exit:[SQL_SUCCESS]
[ODBC][4334][1723022770.189738][SQLPutData.c][148]
		Entry:
			Statement = 0x28ff860
			Data = 0x782f9419f0cf
			StrLen = 1
[ODBC][4334][1723022770.190018][SQLPutData.c][315]
		Exit:[SQL_ERROR]
```

**Comment by gordthompson** [comment]
> does it happen with pyODBC 4.x?

Unknown. pyodbc 4.0.39 won't build under Ubuntu 24.04 (Python 3.12.).

**Comment by lazydev2** [comment]
> Also, no error with
> 
> ```python
> data = "A" * 129
> ```

If the string is longer than 128, then yes, there is no error, however, data written to DB are completely broken after 128th symbol.

**Comment by gordthompson** [comment]
> does it happen with pyODBC 4.x?

Yes. It also occurs on Ubuntu 22.04 (Python 3.10, same version of odbc-mariadb) with both pyodbc 5.1.0 and 4.0.39. Same anomaly in the ODBC trace log,

**Comment by gordthompson** [comment]
@lazydev2 - Immediately after the `pyodbc.connect()` call, try adding

```python
conn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
conn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
conn.setencoding(encoding='utf-8')
```

as suggested in the [wiki](https://github.com/mkleehammer/pyodbc/wiki/Unicode#mysql).

**Comment by lazydev2** [comment]
> ```python
> conn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
> conn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
> conn.setencoding(encoding='utf-8')
> ```

It works, no erros, data are written correctly.
If those changes are mandatory, would be good to spread them among all pyodbc guides in the internet :)
