### ISSUE TITLE
SSMS shows "Restoring..." message after this restore command executed from pyodb/python3

### ISSUE THREAD

**Issue by ggmartins** [mkleehammer/pyodbc#1376]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.12.5
- pyodbc: 5.1.0
- OS: Windows 10
- DB: MSSQL2019
- driver:  {SQL Server Native Client 11.0}

### Issue

Restoring the db from this python/SQL above doesn't work. SSMS shows the Restoring.... message.

```sql
RESTORE DATABASE [Mydatabase] FROM  DISK = N'C:\Mydatabase_Latest.bak' WITH REPLACE, RECOVERY, STATS = 5,
MOVE 'Mydatabase' TO 'C:\Databases\tmp\Mydatabase.ndf',
MOVE 'Mydatabase_log' TO 'C:\Databases\tmp\Mydatabase_log.ldf';
```
(This same query runs on SSMS ok.)

```python
#/usr/bin/env python3

import pyodbc
import sys
import time
print("RUNNING QUERY:")
cnxn = pyodbc.connect("Driver={SQL Server Native Client 11.0};"
                      "Server=.\\SQL2019;"
                      "Trusted_Connection=yes;", autocommit=True)
print("DATABASE CONNECTED.")
cursor = cnxn.cursor()

print("CURSOR READY.")
print(f"INFO: Opening {sys.argv[1]}")
with open(sys.argv[1]) as sqlcmd:
  sqldata = sqlcmd.read().split(";")
  for i in sqldata:
      print(f"RUNNING: {i}")
      r=cursor.execute(i)
      try:
         for row in r:
           print(row)
      except pyodbc.ProgrammingError as e:
        print(f"WARN: {e}")
      print(f"DONE")

while cursor.nextset():
    for rec in cursor:
        print(rec)
cursor.close()
```

Question on Stackoverflow has been closed for unknown reasons, but I have everything in there:
https://stackoverflow.com/questions/78850398/unable-to-restore-sql-server-database-restoring

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by gordthompson** [comment]
Probably related issue

https://github.com/mkleehammer/pyodbc/issues/795

Comment with other possibly related issues

https://github.com/mkleehammer/pyodbc/issues/795#issuecomment-655580499

**Comment by ggmartins** [comment]
Thanks, I simplified the logic and everything works now.
