### ISSUE TITLE
CI failing SQL Server: no sqlcmd

### ISSUE THREAD

**Issue by mkleehammer** [mkleehammer/pyodbc#1380]
The CI jobs are failing with this message:

> OCI runtime exec failed: exec failed: unable to start container process: exec: "/opt/mssql-tools/bin/sqlcmd": stat /opt/mssql-tools/bin/sqlcmd: no such file or directory: unknown

Possibly related to this?

https://github.com/microsoft/mssql-docker/issues/892

**Comment by mkleehammer** [comment]
https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver16&tabs=redhat-install#install-tools-on-linux

According to the bug report in the description and this documentation it points to, it should be as easy as adding "18" to the directory name (and maybe add -C).  It says the docker image should already contain it.  I tried on a fix-ss-tests branch and it isn't working.

> OCI runtime exec failed: exec failed: unable to start container process: exec: "/opt/mssql-tools18/bin/sqlcmd": stat /opt/mssql-tools18/bin/sqlcmd: no such file or directory: unknown

**Comment by mkleehammer** [comment]
https://github.com/microsoft/mssql-docker/issues/894

**Comment by keitherskine** [comment]
Adding "18" and "-C" to the mssql2019 and mssql2022 commands (but leaving mssql2017 as was) seems to work:
```
        echo "*** SQL Server 2017"
        docker exec -i "${{ job.services.mssql2017.id }}" /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'StrongPassword2017' -Q "SELECT @@VERSION" || sleep 5
        docker exec -i "${{ job.services.mssql2017.id }}" /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'StrongPassword2017' -Q "CREATE DATABASE test"
        echo "*** SQL Server 2019"
        docker exec -i "${{ job.services.mssql2019.id }}" /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'StrongPassword2019' -C -Q "SELECT @@VERSION" || sleep 5
        docker exec -i "${{ job.services.mssql2019.id }}" /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'StrongPassword2019' -C -Q "CREATE DATABASE test"
        echo "*** SQL Server 2022"
        docker exec -i "${{ job.services.mssql2022.id }}" /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'StrongPassword2022' -C -Q "SELECT @@VERSION" || sleep 5
        docker exec -i "${{ job.services.mssql2022.id }}" /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'StrongPassword2022' -C -Q "CREATE DATABASE test"
```

**Comment by mkleehammer** [comment]
I thought the 2017 was also failing.  Sheesh.  Thanks.  Do you want to commit your copy on master?

**Comment by keitherskine** [comment]
OK, will do.  One sec...

**Comment by mkleehammer** [comment]
Thanks @keitherskine  That was it.  I thought 2017 was also failing.

**Comment by keitherskine** [comment]
No probs @mkleehammer , the Ubuntu CI tests are passing now.
