### ISSUE TITLE
Access ODBC, data source name too long

### ISSUE THREAD

**Issue by madduck** [mkleehammer/pyodbc#1396]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
- pyodbc: 5.2.0
- OS: Windows 10 Pro, 22H2
- DB: Microsoft Access Jet (see below)
- driver: Microsoft Access database engine 16.0.5044.1000 (64 bit)

```
lotus:…sync/2025-01-06-Memorial% head -c24 Memorial2025.TP
Standard Jet DB%
lotus:…sync/2025-01-06-Memorial% file Memorial2025.TP
Memorial2025.TP: Microsoft Access Database
```

### Issue

I am trying to connect to an Access "database" with the following DSN:

```
DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=..\Documents\2025-01-06-Memorial\Memorial2025.TP;Pwd=d4R2GY76w2qzZ
```

This yields a `pyodbc.Error`:

```
('IM010', '[IM010] [Microsoft][ODBC Driver Manager] Data source name too long (0) (SQLDriverConnect)')
```

I feel there are three important pieces of information to share:

1. I get the same error if I put the file into `.\x.mpd`, so really, "name too long" cannot be;
2. If I use `aioodbc`, which builds on top of `pyodbc`, I can open the database just fine, using the same, long connection string as above;
3. If I create a "User DSN" using the Windows ODBC Manager, I can connect just fine.

This all makes me think it may well be something to do with the way `pyodbc` passes DSNs to the driver? But why would it work with `aioodbc`?

**Comment by gordthompson** [comment]
> with the following DSN
>
> `DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=..\Documents\2025-01-06-Memorial\Memorial2025.TP;Pwd=d4R2GY76w2qzZ`

That is not a DSN (name), it is a connection string.

By chance, are you trying to do something like this?

```python
x = r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=..\Documents\2025-01-06-Memorial\Memorial2025.TP;Pwd=d4R2GY76w2qzZ"
cnxn = pyodbc.connect(dsn=x)
```

**Comment by madduck** [comment]
@gordthompson you got it, spot on. It works now. I was confused, because `aioodbc` just uses `dsn`, and not `connstr`. I thought they were the same. Thanks for enlightening me.
