### ISSUE TITLE
Unicode with a large (over two bites) character code fails.

### ISSUE THREAD

**Issue by adrinjalali** [mkleehammer/pyodbc#140]
I've created the test case in [this](https://github.com/adrinjalali/pyodbc/commit/15db5548559fdb848f67d78354ab26739558be37) commit. How can I fix the error?

Corresponding connection string:
`connection-string=DRIVER=FreeTDS;SERVER=sqlserver2008;UID=uid;PWD=pwd;DATABASE=tempdb;TDS_Version=7.2;PORT=1433`

Here's the output:

```
$ python3 tests3/sqlservertests.py -t unicode_largecode
python:  3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1]
pyodbc:  3.0.11b17 /path/to/pyodbc/build/lib.linux-x86_64-3.4/pyodbc.cpython-34m.so
odbc:    03.52
driver:  libtdsodbc.so 0.91
         supports ODBC version 03.50
os:      Linux
unicode: Py_Unicode=4 SQLWCHAR=4
======================================================================
ERROR: test_unicode_largecode (__main__.SqlServerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlservertests.py", line 289, in test_unicode_largecode
    self._test_strtype('nvarchar', "Coloring book FingerPen 🎨 (Google Play", colsize=100)
  File "tests3/sqlservertests.py", line 205, in _test_strtype
    self.cursor.execute("insert into t1 values(?)", value)
ValueError: Cannot convert from Unicode 127912 to SQLWCHAR.  Value is too large.

----------------------------------------------------------------------
Ran 1 test in 0.029s

FAILED (errors=1)
```

**Comment by mkleehammer** [comment]
Can you test with the v4 branch?  I believe it works out-of-the-box with SQL Server but, if not, the encoding for reads and writes can be customized using:

    cnxn.setencoding('utf-16le')
    cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
    cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-16le')

(Those are the defaults so you don't need those.)

I'll be writing up docs and some test cases for FreeTDS (I've already tested on Windows with the MS driver) soon, but could really use some beta testing.

**Comment by adrinjalali** [comment]
Thanks for the update. But unfortunately I don't have access to a MSSQLServer anymore, so can't really test it.

**Comment by mkleehammer** [comment]
No problem.  I'm going to close this as it is going to get a lot of testing anyway.  Thanks.
