### ISSUE TITLE
Data source name not found if there is space in DNS name

### ISSUE THREAD

**Issue by zdenop** [mkleehammer/pyodbc#145]
I am not able to connect to database if there is space in DNS e.g. "Server A". 
E.g. I tried to connect with:
`pyodbc.connect(r'DSN="Server A";UID=user;PWD=pwd')`

And I got error:
`Error: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')`

But it is listed in pyodbc.dataSources():

```
{'Excel Files': 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'MS Access Database': 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Server A': 'IBM INFORMIX ODBC DRIVER',
 'test': 'IBM INFORMIX ODBC DRIVER',
 'dBASE Files': 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)'}
```

I tried also:

```
pyodbc.connect(r'DSN={Server A};UID=user;PWD=pwd')
pyodbc.connect(r'DSN=\"Server A\";UID=user;PWD=pwd')
pyodbc.connect(r'DSN=Server A;UID=user;PWD=pwd')
```

but without success... 
`pyodbc.connect(r'DSN=test;UID=user;PWD=pwd')` works so issues should be related to space in DNS.

**Comment by mkleehammer** [comment]
I'm going to close this only because pyodbc does not touch the connection string, so it must be an ODBC Driver Manager issue.  I wish I could do more.
