### ISSUE TITLE
Teradata query issue using Pyodbc

### ISSUE THREAD

**Issue by sudipto84goswami** [mkleehammer/pyodbc#148]
Hi Team,

I am getting Error : Error: ('HY000', 'The driver did not supply an error!'). I am using the below query.

import teradata
import time
import pyodbc
pyodbc.pooling = False
start_time = time.time()
conn=pyodbc.connect("DSN=prodsn;DBCNAME=XXX;AUTHENTICATION=LDAP;UID=XXX;PWD=XXXX")
cursorstmt = conn.cursor()
cursorstmt.execute("select database;");

Error Message:
ErrorTraceback (most recent call last)
<ipython-input-1-a085084c7ea7> in <module>()
      7 conn=pyodbc.connect('DSN=prodsn;DBCNAME=XXX;AUTHENTICATION=LDAP;UID=SSS;PWD="XX"')
      8 cursorstmt = conn.cursor()
----> 9 cursorstmt.execute("select database;");

Error: ('HY000', 'The driver did not supply an error!')

Pyodbc  Version: 3.0.10 installed. 

Please let us know on this.

**Comment by alexisrolland** [comment]
I am having the exact same issue.

I am able to connect to Teradata database using pyodbc, but any query would trigger the error message:
Error: ('HY000', 'The driver did not supply an error!')

Any help would be greatly appreciated.
Thanks

**Comment by elisabetao** [comment]
@sudipto84goswami you might this working by  using pyodbc v4 branch, pyodbc 3.1.2b7 and setting the encoding based on your needs, in our case utf-8.

Thanks @mkleehammer for the tips and help.

Happy holidays!

**Comment by mkleehammer** [comment]
I've now released 4.0.0 with this feature.  Thanks for your testing help!

**Comment by alexisrolland** [comment]
Hello Michael,

Just a quick comment to let you know that I upgraded my pyodbc library to version 4.0 on my Windows workstation and it seems the code snippet shared above by Elisabeta above does not work anymore.

I am doing this:

```
>>> import pyodbc
>>> pyodbc.version
'4.0.0'
>>> print("Connecting")
Connecting
>>> oConnexion = pyodbc.connect("Driver={Teradata};DBCNAME=myserver;UID=myuser;PWD=mypassword", autocommit=True)
```

The last command above never comes back and I have to manually close the terminal window.
Best

Alexis

**Comment by mkleehammer** [comment]
This doesn’t seem to be showing up on Github.  Did you delete this comment?  Are you still having the issue?

I suspect you need to add ", encoding=‘utf-8’)” to the connect call.  I’ll look at the last changes I made.

**Comment by sushmit86** [comment]
@mkleehammer  I am getting this error. Any help on this ?
