### ISSUE TITLE
isn't it time for a new release ?

### ISSUE THREAD

**Issue by stonebig** [mkleehammer/pyodbc#150]
to get "SQL Server 2012" in UTF-16. cp35 wheel, ... cp36 wheel...

**Comment by mkleehammer** [comment]
Can you elaborate.  It is time for a new release, but is there a particular issue you want closed?  Or are we missing binaries?

**Comment by stonebig** [comment]
missing binaries for python 3.5 and 3.6

**Comment by mkleehammer** [comment]
I've released 3.1.1 binaries for 2.7 and 3.5.  Python 3.6 is, of course, only in beta so I didn't build it yet.  I'm not sure if I should really upload beta binaries to PyPI.
