### ISSUE TITLE
Solaris 5.10 - compilation error

### ISSUE THREAD

**Issue by hrnourzadeh** [mkleehammer/pyodbc#152]
Hi,
I was wondering if somebody have solved the following problem on Solaris 5.10. 

/opt/csw/bin/gcc -DNDEBUG -O2 -DHAVE_NCURSES_H -m64 -O2 -I/usr/sfw/include -I/opt/sfw/include -I/opt/sfw/include/ncurses -fPIC -DPYODBC_VERSION=3.0.11b16 -DPYODBC_UNICODE_WIDTH=2 -I/usr/local/python/epd-7.3-2-SunOS_5.10-x86_64/include/python2.7 -c /gitLocalRepos/pyodbc/src/connection.cpp -o build/temp.solaris-2.10-i86pc.64bit-2.7/gitLocalRepos/pyodbc/src/connection.o -Wno-write-strings
.../gitLocalRepos/pyodbc/src/connection.cpp: In function 'PyObject* Connection_New(PyObject*, bool, bool, bool, long int, bool, PyObject*)':
.../gitLocalRepos/pyodbc/src/connection.cpp:181:39: error: 'PyInt_AsInt' was not declared in this scope
                 ikey = PyInt_AsInt(key);
                                       ^

**Comment by mkleehammer** [comment]
That was embarrassing.  Somehow I added this feature and it didn't get tested in 2.7.  I thought I had tox setup to test that also.  Thanks.
