### ISSUE TITLE
Unknown string encoding in PyODBC data

### ISSUE THREAD

**Issue by moin18** [mkleehammer/pyodbc#153]
On making query with PyODBC, I am getting my table data as:

     > u'\u3836\u3431\u3132\u3230\u3030'

The actual content in my database column is as:

     > 6814210200

When I explicitly encode `pyodbc`'s returned value to `utf-16`, I get the content as (closest I went):

    > >>> print d['data'][0]['upc'].encode('utf-16')
    >  ��6814210200
    > #^^ two junks

**My question is: How can I get the encoded value directly from the PyODBC query?**

I already have `CHARSET=UTF16` set in my database connection string as:

    pyodbc.connect("DRIVER=<driver_name>;" + \
                                     "SERVER=<server_ip>;" +\
                                     "DATABASE=<database>;" +\
                                     "UID=<user>;" +\
                                     "PWD=<password>;" + \
                                     "CHARSET=UTF16",    # setting charset
                                     ansi=True)

Also in all my `odbc.ini` and `odbcinst.ini` file, I have set:

     UnicodeTranslationOption = utf16 
     CharacterTranslationOption = all

under my driver's setting.

**Comment by mkleehammer** [comment]
I've rewritten Unicode handling on the v4 branch and will soon write up some docs and make some beta releases.  This gives you a lot of flexibility to configure encodings, but to tell you how to use it I

The first thing to know is the first two bytes are the byte-order mark.  You need to decode with "utf-16be" to get rid of those.  (Your data is in big endian format.)

On the v4 branch I think you need set this after connection:

Python 2

    cnxn.setencoding(str, 'utf-16be')
    cnxn.setencoding(unicode, 'utf-16be')

Python 3

    cnxn.setencoding('utf-16be')

Can you try these and let me know?  (Also, which Python are you using?)

**Comment by mkleehammer** [comment]
I've rebased the v4 branch so I could make a smaller pull request #160.

**Comment by mkleehammer** [comment]
I believe Unicode issues are fixed in the newly released 4.0.0 version.
