### ISSUE TITLE
Parameterized queries not working for me

### ISSUE THREAD

**Issue by Pentusha** [mkleehammer/pyodbc#154]
Hello, I've got an issue with Oracle database and parameterized queries.
```sql
SELECT * FROM V$VERSION
Oracle Database 11g Release 11.2.0.1.0 - 64bit Production
PL/SQL Release 11.2.0.1.0 - Production
CORE	11.2.0.1.0	Production
TNS for 64-bit Windows: Version 11.2.0.1.0 - Production
NLSRTL Version 11.2.0.1.0 - Production
```

```bash
python --version
Python 3.5.1

pip freeze | grep odbc
pyodbc==3.0.10
```

```python
connection = pyodbc.connect(connection_string)
cursor = connection.cursor()
format_query = '''
    SELECT *
    FROM USER_ARGUMENTS
    LEFT OUTER JOIN USER_TYPES ON USER_ARGUMENTS.TYPE_NAME = USER_TYPES.TYPE_NAME
    LEFT OUTER JOIN USER_TYPE_ATTRS ON USER_ARGUMENTS.TYPE_NAME = USER_TYPE_ATTRS.TYPE_NAME
    WHERE
      PACKAGE_NAME = upper('{package_name}') AND
      OBJECT_NAME = upper('{routine_name}')
    ORDER BY SEQUENCE, POSITION, ATTR_NO;
'''.format(
    package_name=package_name,
    routine_name=routine_name,
)
parameterized_query = '''
    SELECT *
    FROM USER_ARGUMENTS
    LEFT OUTER JOIN USER_TYPES ON USER_ARGUMENTS.TYPE_NAME = USER_TYPES.TYPE_NAME
    LEFT OUTER JOIN USER_TYPE_ATTRS ON USER_ARGUMENTS.TYPE_NAME = USER_TYPE_ATTRS.TYPE_NAME
    WHERE
      PACKAGE_NAME = upper(?) AND
      OBJECT_NAME = upper(?)
    ORDER BY SEQUENCE, POSITION, ATTR_NO;
'''
cursor.execute(format_query, [])
assert cursor.fetchall()  # ok and some results
cursor.execute(parameterized_query, [package_name, routine_name])
assert cursor.fetchall()  # failed, no results
cursor.execute(parameterized_query, package_name, routine_name)
assert cursor.fetchall()  # failed, no results
```

**Comment by skillian** [comment]
Hi, @Pentusha,

What types are `package_name` and `routine_name`?

**Comment by Pentusha** [comment]
@skillian, python 3 strings.
This query allows you to get the structure of parameters and result of oracle's routine.

**Comment by mkleehammer** [comment]
@Pentusha I'm not sure what the issue is here, but it isn't just parameterized queries because I use them, literally, all day long.  (They run in 24x7 servers.)

Can you provide an ODBC trace for this?

**Comment by Pentusha** [comment]
@mkleehammer 
It is server for testing purposes, but anyway I replaced username and password in text to strings with same length. All other information is relevant.
https://gist.github.com/Pentusha/cfacb9f4c24842fcf8fd0726a2291eb0#file-odbc_trace_format-log
https://gist.github.com/Pentusha/cfacb9f4c24842fcf8fd0726a2291eb0#file-odbc_trace_parameterized-log

**Comment by skillian** [comment]
I cannot find the issue, but I thought I recalled seeing an issue where no results were coming back if a value in one of the columns of the result set was too large.  That might be happening here based on the ODBC log:
```
[ODBC][10149][1480409328.608524][SQLDescribeCol.c][497]
		Exit:[SQL_SUCCESS]                
			Column Name = [DEFAULT_VALUE]                
			Data Type = 0x7ffea7875a1a -> -1                
			Column Size = 0x7ffea7875a20 -> 2147483647                
			Decimal Digits = 0x7ffea7875a1c -> 0                
			Nullable = 0x7ffea7875a1e -> 1
```
This is in a call to SQLDescribeCol after the query in the issue description is executed.

**Comment by mkleehammer** [comment]
I'm still looking, but I find this most interesting:

```text
[ODBC][10487][1480409611.119633][SQLFetch.c][348]
		Exit:[SQL_NO_DATA]
```

If [SQLFetch](https://msdn.microsoft.com/en-us/library/ms712424(v=vs.85).aspx) returns SQL_NO_DATA then there are no rows returned by the DB.  I think that would make it more likely that the parameters are not being passed correctly.

The ODBC specification specifies that Unicode is to be UCS-2 encoded (extended to UTF-16 later apparently).  Now, many drivers do not pay attention to this and I am in the process of figuring out how to make the encodings configurable.  In the meantime, perhaps pyodbc is passing UTF-16 data and Oracle is expecting UTF-8.  Can you check that?  Is that something you can configure on the client easily, at least to test?

And kudos on the traces!  Usually when I need one I don't get a response.

**Comment by mkleehammer** [comment]
Now that I read the Oracle docs again, they appear to use SQL_WCHAR normally.  That is, they don't mention any encoding so I'm guessing they are using UCS2.   Are the values you are sending using extended characters or simple English?  I know it sounds like I'm grasping at straws right now, but that's because I am :). I don't have an Oracle install available to me ATM.

**Comment by mkleehammer** [comment]
One last thing, to eliminate the large column theory, can you replace the asterisk with a single column?

**Comment by Pentusha** [comment]
In case of "large column theory" - same result when I replace asterisk with "OBJECT_NAME".

In case of it's a encoding issue:
client:
```python
os.environ['NLS_LANG'] = 'AMERICAN_AMERICA.AL32UTF8'
# I tried a lot of other options with the same result
```
```bash
$ locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
ru_RU.utf8
ru_UA.utf8
```

server:
```sql
SELECT * FROM NLS_DATABASE_PARAMETERS 
WHERE PARAMETER IN ('NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET');

PARAMETER                      VALUE                                   
------------------------------ ----------------------------------------
NLS_CHARACTERSET               CL8MSWIN1251                            
NLS_NCHAR_CHARACTERSET         AL16UTF16                            
                          
```

**Comment by mkleehammer** [comment]
Can you try with v4.x?  I've completely rewritten character handling.

**Comment by mkleehammer** [comment]
I'm going to close this due to lack of response - I really think 4.x will do what you want since you can configure whatever encoding you need.
