### ISSUE TITLE
Not able to install pyodbc in Windows 10

### ISSUE THREAD

**Issue by MaximoTrinidad** [mkleehammer/pyodbc#155]
I'm using Python 3.5.2 but haven't been able to install pyodbc in a fresh Windows 10 VM.  I have installed the required Microsoft Visual C++ Build Tools, missing modules and downloaded both of the wheel files:
pyodbc-3.0.10-cp36-cp36m-win_amd64.whl and 
pyodbc-3.0.10-cp36-cp36m-win_amd64.wpyodbc-3.0.10-cp36-cp36m-win32.whl

During the installation I'm getting the following error message:

PS C:\Users\max_t\Downloads> pip3 install pyodbc-3.0.10-cp36-cp36m-win_amd64.whl
**pyodbc-3.0.10-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform**.

PS C:\Users\max_t\Downloads> pip3 install pyodbc-3.0.10-cp36-cp36m-win32.whl
**pyodbc-3.0.10-cp36-cp36m-win32.whl is not a supported wheel on this platform.**

It works well in Ubuntu 16.04.1 with Python 3.5.2 after adding all the missing module and upgrade.

Any ideas!  

Greatly Appreciated,
Maximo Trinidad

**Comment by MaximoTrinidad** [comment]
So, here's the actual error when I'm using the following command in Windows 10:
pip3 install pyodbc

It shows 2 errors during the setup process:
1.  see below:
**475, in append
      path = convert_path(item)
    File "c:\users\max_t\appdata\local\programs\python\python35\lib\distutils\util.py", line 125, in convert_path
      raise ValueError("path '%s' cannot be absolute" % pathname)
  ValueError: path '/Users/mkleehammer/dev/pyodbc/src/buffer.cpp' cannot be absolute

  ----------------------------------------
  Failed building wheel for pyodbc
  Running setup.py clean for pyodbc**

2. See below:
   **path = convert_path(item)
 File "c:\users\max_t\appdata\local\programs\python\python35\lib\distutils\util.py", line 125, in convert_path
   raise ValueError("path '%s' cannot be absolute" % pathname)
alueError: path '/Users/mkleehammer/dev/pyodbc/src/buffer.cpp' cannot be absolute

---------------------------------------
nd "c:\users\max_t\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C
ers\\max_t\\AppData\\Local\\Temp\\pip-build-al7xqra_\\pyodbc\\setup.py';f=getattr(tokenize, 'open', open)(__file__)
=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\max_t\Ap
\Local\Temp\pip-okm9kzvx-record\install-record.txt --single-version-externally-managed --compile" failed with error
 1 in C:\Users\max_t\AppData\Local\Temp\pip-build-al7xqra_\pyodbc\
**

(See Attached full text file)
[Win10_Python352_pyodbc_errors.txt](https://github.com/mkleehammer/pyodbc/files/607707/Win10_Python352_pyodbc_errors.txt)

**Comment by MaximoTrinidad** [comment]
OK! So, I just found out, with all the errors I was experiencing during the installation, I'm able to import pyodbc module.  

The errors are misleading. I'm able to use pyodbc and connect to any SQL Server in both Windows and Linux.

I'm good for now!

Thanks,
Maximo Trinidad

**Comment by skillian** [comment]
Hi, @MaximoTrinidad, glad to hear that it's working for you, but just so you know the "cp36" in the filename means "C Python 3.6" but you said that you have Python 3.5.2 which means you'd need an installer named something like `pyodbc-3.0.10-cp35-cp35m-win_amd64.whl` or `pyodbc-3.0.10-cp35-none-win_amd64.whl`.

Also, the "path '%s' cannot be absolute" error message is addressed in Pull Request #119.

**Comment by mkleehammer** [comment]
Merged #119
