### ISSUE TITLE
pyodbc and pylint

### ISSUE THREAD

**Issue by gbritton1** [mkleehammer/pyodbc#164]
I talked to the pylint team about why it has trouble with pyodbc.  Here is the response to the question, "What can pyodbc do to help?"

Not familiar with pyodbc's code base, but from a quick glance, it seems to be a C extension. This puts pylint into a tough situation, since it needs to be able to parse the code into ASTs and use those trees for generating objects that can be internally interpreted. In this case, without having access to a source code, pylint can import the respective module and build some kind of ASTs objects on top of that. This is of course a security risk and we shouldn't do this blindly, an extension might be malformed, might take a lot of resources at import time or any other weird scenario you can imagine, hence the use of --extension-pkg-whitelist to specify to pylint that it can include your module for a deep analysis without worrying too much about security.
Now you might now like using this. As an alternative, we do support providing some hints to pylint, through https://github.com/PyCQA/astroid/tree/master/astroid/brain, in which we can say how a particular module or class can look like. It's basically like a stub, but on steroids, since you have access to the entire tree and inference API when building the stub. This might be another way of improving the situation for pyodbc for instance, by providing such a stub, through which pylint can know how the API of pyodbc looks like.
In the future, we will also support PEP 484 stubs, so that will be definitely easier and more straight forward to do.

ref: [https://github.com/PyCQA/pylint/issues/1209](url)

**Comment by gbritton1** [comment]
Also, adding --extension-pkg-whitelist=pyodbc to the command line will stop the errors from pylint.

**Comment by mkleehammer** [comment]
Thanks.  I'm going to close this now as there isn't anything I can do that I know of.
