### ISSUE TITLE
Unsupported type from Postgres `SQLGetData`

### ISSUE THREAD

**Issue by bluesmoon** [mkleehammer/pyodbc#169]
I'm trying to run a very simple query against an Amazon RedShift database:

```sql
SELECT TRIM(datname) FROM pg_database
```

I get the following error:
```
pyodbc.Error: ('07006', '[07006] Received an unsupported type from Postgres. (14) (SQLGetData)')
```

I'm using python 3.4.3 with pyodbc 3.1.1

My code is as follows:

```
>>> import pyodbc
>>> cnxn = pyodbc.connect('DSN=redshift-db')
>>> cursor = cnxn.cursor()
>>> cursor.execute("SELECT TRIM(datname) FROM pg_database")
<pyodbc.Cursor object at 0x7f0f57d95ab0>
>>> rows = cursor.fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('07006', '[07006] Received an unsupported type from Postgres. (14) (SQLGetData)')
```

This code works when using other languages.

**Comment by mkleehammer** [comment]
I am not able to reproduce this with my local PostgreSQL database using the psqlodbc 9.5.0400 ODBC driver on macOS.  What driver are you using?

The unknown type is "14" and I actually don't know what that is.  The OID of pg_database.datname is NAMEOID which the version of psqlodbc I am using converts to varchar or wvarchar, neither of which is 14.

I'm pretty sure this will be a simple case of adding support for type 14, but I do need to find out what it is.

Also, if you need a super-quick workaround you can add a converter for 14 which will receive the value as a bytes object.  You can then simply return `val.decode("utf-8")` or whatever your encoding is.

Finally, I highly recommend trying the v4 branch if possible.  I've completely rewritten text handling and I think you'll have much better success in the long run.  It's still a few weeks away from releasing officially because I want to get input from more people but it is very solid.

**Comment by bluesmoon** [comment]
Thanks, will try the v4 branch.

As far as I can tell, this field is in fact just a VARCHAR. I can get it to work with the `psycopg2` library.

It fails when running through `pyodbc` against a Redshift database, and only if I use the `TRIM` function. If I use an actual PostgreSQL database, or if I remove the `TRIM` function, I have no problem, and I get a VARCHAR back.  Could just be Redshift silliness, but like I said, `psycopg2` has no problem with it.

**Comment by mkleehammer** [comment]
I'm having trouble finding the proper name for type 14.  Can you run this:

    import pyodbc
    cnxn = pyodbc.connect('DSN=pgtests')
    cursor = cnxn.cursor()
    cursor.getTypeInfo(0)
    cols = [t[0] for t in cursor.description]
    for row in cursor:
        print('%s: data_type=%s sql_type=%s' % (row.type_name, row.data_type, row.sql_data_type))

It will print out the name and type numbers for each data type the driver supports:

    int8: data_type=-5 sql_type=-5
    char: data_type=-7 sql_type=-8

Thanks.

**Comment by bluesmoon** [comment]
I don't have the `pgtests` DSN, but I tried it against my Redshift DSN, and this is what I got:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('07006', '[07006] Received an unsupported type from Postgres. (14) (SQLGetData)')
```

which I suppose is no help, so I'll get the values from intermediate steps:

```
>>> cursor.description
(
('type_name', <class 'str'>, None, 128, 128, 0, True),
('data_type', <class 'int'>, None, 5, 5, 0, True),
('precision', <class 'int'>, None, 10, 10, 0, True),
('literal_prefix', <class 'str'>, None, 128, 128, 0, True),
('literal_suffix', <class 'str'>, None, 128, 128, 0, True),
('create_params', <class 'str'>, None, 128, 128, 0, True),
('nullable', <class 'int'>, None, 5, 5, 0, True),
('case_sensitive', <class 'int'>, None, 5, 5, 0, True),
('searchable', <class 'int'>, None, 5, 5, 0, True),
('unsigned_attribute', <class 'int'>, None, 5, 5, 0, True),
('money', <class 'int'>, None, 5, 5, 0, True),
('auto_increment', <class 'int'>, None, 5, 5, 0, True),
('local_type_name', <class 'str'>, None, 128, 128, 0, True),
('minimum_scale', <class 'int'>, None, 5, 5, 0, True),
('maximum_scale', <class 'int'>, None, 5, 5, 0, True),
('sql_data_type', <class 'int'>, None, 5, 5, 0, True),
('sql_datetime_sub', <class 'int'>, None, 5, 5, 0, True),
('num_prec_radix', <class 'int'>, None, 10, 10, 0, True),
('interval_precision', <class 'int'>, None, 5, 5, 0, True)
)

>>> cursor.rowcount
-1

>>> row = cursor.fetchone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('07006', '[07006] Received an unsupported type from Postgres. (14) (SQLGetData)')
```

**Comment by mkleehammer** [comment]
Sorry, I forgot something.  I meant for your test to use your DSN:`DSN=redshift-db`.  Can you try again with yours?

**Comment by bluesmoon** [comment]
yup, that's what I used to get the above.

**Comment by mkleehammer** [comment]
I wasn't expecting that.  Can we try again:

    import pyodbc
    cnxn = pyodbc.connect('DSN=redshift-db')

    def _raw(value):
        return value

    cnxn.add_output_converter(14, _raw)

    cursor = cnxn.cursor()
    cursor.getTypeInfo(0)
    cols = [t[0] for t in cursor.description]
    for row in cursor:
        print('%s: data_type=%s sql_type=%s' % (row.type_name, row.data_type, row.sql_data_type))

**Comment by mkleehammer** [comment]
The only change is we'll pass type 14 through a function that simply returns the raw bytes.

**Comment by bluesmoon** [comment]
Still the same unfortunately.  I should mention that at this time I've also managed to get `pygresql` working, but unfortunately its `cursor` does not have a `getTypeInfo` method that I can use instead.  Is there anything else I can use on a different library to get you the information you need?

**Comment by mkleehammer** [comment]
I can't think of any.  Let me dig around some more or stand up a RedShift instance on my AWS account.

**Comment by mkleehammer** [comment]
OK, I'm a bit baffled.  I've setup a RedShift instance and connected with this driver: Amazon Redshift ODBC Driver 1.3.1.1000

I had trouble, but not the errors you are seeing.  I switched the v4 branch and configured it using these lines:

    cnxn = pyodbc.connect(DSN)
    cnxn.setencoding(encoding='utf-8')
    cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
    cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')

In all of my projects I use a global function that retrieve connections, giving me an easy place to set configuration, wrap with debugging connections if necessary, etrc.

What these do is configure *everything* to use UTF-8.  Now, I'm on a Mac so it could need tweaking for other OSs.  What are you using?

**Comment by bluesmoon** [comment]
i've been testing on Ubuntu, but will give this a try with the v4 branch.

**Comment by nadirsidi** [comment]
Is there any progress on this issue? I am seeing the same thing when trying to read from a AWS RDS PostgreSQL instance using the PostgreSQL driver 10.02.

**Comment by nadirsidi** [comment]
Hello, just following up that my error was being caused by pointing the odbc.ini driver path at the psqlodbca.so file versus the psqlodbcw.so file. Sorry about that!

**Comment by pokoli** [comment]
as @nadirsidi pointed using psqlodbcw.so file instead of psqlodbc.so fixed the issue. 

Maybe we should add some entry on the postgresql wiki page to document this behaviour?

**Comment by v-chojas** [comment]
It's a wiki, go ahead and edit it to add what you think will be helpful.

**Comment by Salompas** [comment]
> OK, I'm a bit baffled. I've setup a RedShift instance and connected with this driver: Amazon Redshift ODBC Driver 1.3.1.1000
> 
> I had trouble, but not the errors you are seeing. I switched the v4 branch and configured it using these lines:
> 
> ```
> cnxn = pyodbc.connect(DSN)
> cnxn.setencoding(encoding='utf-8')
> cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
> cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
> ```
> 
> In all of my projects I use a global function that retrieve connections, giving me an easy place to set configuration, wrap with debugging connections if necessary, etrc.
> 
> What these do is configure _everything_ to use UTF-8. Now, I'm on a Mac so it could need tweaking for other OSs. What are you using?

I was having the same issue and this worked for me. Do you have any idea how or why?
What is SQL_CHAR and SQL_WCHAR?

Thanks!!!!

**Comment by nadirsidi** [comment]
Looking at the connection wiki docs here, it looks like those set the C data types for passing data:

https://github.com/mkleehammer/pyodbc/wiki/Connection

As you can see, the default for Python 3 is utf-16le if that isn't set.

**Comment by joshwarren** [comment]
I've just had the same issue but for Postgres database. I switched to using the Unicode driver instead of the ANSI one which fixed the issue.

**Comment by keitherskine** [comment]
Closed due to inactivity.
