### ISSUE TITLE
param-type=Decimal', 'HY105, fail to insert sqlserver when using DecimalField

### ISSUE THREAD

**Issue by makodo** [mkleehammer/pyodbc#173]
Hi,

I'm using DJANGO and pyodbc. Recently have created a model and I set up a code to trigger an auto record insert. Unfortunately, everytime when I include the an amount which is a DecimalField(18,2)
the code bugged and told me the parameter type type is not correct. I'm using a sqlserver 2008 R2 as my database, the destination field in DB is a numeric(18, 2)

@receiver(post_save, sender=DossierCtrl)
def create_cashFlowDetail(sender, instance, **kwargs):
    
    print "DossierCtrl post_save triggered"         
    
    ct = ContentType.objects.get_for_model(instance)
    
    if instance.chk_go:
        CashFlowDetail.objects.get_or_create(
            object_id = instance.pk,
            content_type = ct,
            nature = instance.nature,
            date_val = instance.date_recu, 
            corresp = instance.corresp,
            account = instance.account,
            montant = instance.montant
            )
e: ProgrammingError('Invalid parameter type. param-index=1 param-type=Decimal', 'HY105')
params: (1, Decimal('100000.00'), 1, u'2017-01-02', 1, 3423, 26)

If we look at the error message the param[1] is wired as it's marked as Decimal('100000.00') as the DB cannot read it. Can you look at this and tell me if its a bug?

**Comment by mkleehammer** [comment]
What version of pyodbc are you using?  It has supported Decimal for quite some time (years).

I've just checked the SQL Server tests and there are a number of decimal tests.  I also checked the parameter handling source and it looks ok.

The error message is certainly from pyodbc itself and the name "Decimal" comes from the class name of the parameter.  Are you sure there isn't *another* Decimal class and this is not "decimal.Decimal"?

**Comment by mkleehammer** [comment]
Actually I'm pretty sure there is another Decimal class.  If I comment out decimal support in pyodbc and run a test on Python 3.6, notice that the class name includes the module:

    param-type=decimal.Decimal

The Python 2.7 docs state that the `tp_name` field being printed in the error message should have the format "<module>.<name>". 

I'm going to close this because I'm pretty sure something that is not a decimal.Decimal is being passed, but please reopen if that is not the case.

Good luck!

**Comment by piyushdeshkar** [comment]
pyodbc.ProgrammingError: ('Invalid parameter type.  param-index=0 param-type=builtin_function_or_method', 'HY105')

print("Enter a Unique Id")    
Id=int(input())    
print("Enter Name")    
Name=str(input()) 
print("Enter Age")    
Age=int(input()) 
print("Enter Address")    
Address=str(input())   
cursor = conn.cursor()    
SQLCommand = ("INSERT INTO Students(id,Name, Age, Address) VALUES (?,?,?,?)")    
Values = [id,Name, Age, Address]   
#Processing Query    
cursor.execute(SQLCommand,Values)     
#Commiting any pending transaction to the database.    
cursor.executemany(SQLCommand, Values[:5])
conn.commit()    
#closing connection    
print("Data Successfully Inserted")   
conn.close()
