### ISSUE TITLE
Python internal heap corruption

### ISSUE THREAD

**Issue by Lexcon** [mkleehammer/pyodbc#174]
**Config**: windows 10, Py35 or Py36, PyODBC 4.0.0

**Symptoms**: Python crashes

**Reproduce**: Running the following program crashes Python occasionally. I used a batchfile to run the program multiple times in an endless loop

**Extra info**: the line conn.add_output_converter(pyodbc.SQL_LONGVARCHAR, tobyte) seems to be the offender, taking that out stabilizes the program. However this line is only problematic when also the other output_converters are set. 

**File content runit.bat:**
:start
python crash.py
goto start

**File content crash.py** : 
import pyodbc
conn = pyodbc.connect('connection_string-here')

def tobyte(val):
	if val is None:
		return None
	return val

conn.add_output_converter(pyodbc.SQL_CHAR, tobyte)
conn.add_output_converter(pyodbc.SQL_VARCHAR, tobyte)
conn.add_output_converter(pyodbc.SQL_LONGVARCHAR, tobyte)

value = b'testing'
cursor = conn.cursor()
cursor.execute("create table t1(s varchar(20))")
cursor.execute("insert into t1 values (?)", value)
v = cursor.execute("select * from t1").fetchone()[0]
print('done')

**Comment by mkleehammer** [comment]
Wow - thanks.  That was pretty bad.

**Comment by mkleehammer** [comment]
I'll release this in 4.0.2.  I want to see if there are other bugs I can quickly close before releasing.

**Comment by Lexcon** [comment]
Great. pyodbc rocks!
