### ISSUE TITLE
Manylinux wheels

### ISSUE THREAD

**Issue by kevin-brown** [mkleehammer/pyodbc#175]
http://pythonwheels.com/

Right now, only Windows and Mac wheels are being distributed for [pyodbc on PyPI](https://pypi.python.org/pypi/pyodbc). For Linux, you need to compile billiard from source, which can add some time to getting everything up and running.

Support for Linux wheels was added in [PEP-513](https://www.python.org/dev/peps/pep-0513/) through [manylinux](https://github.com/pypa/manylinux). It attempts to make it easier to release wheels for the many Linux distributions out there, and the wheels can be generated automatically and in isolation through Docker containers.

I'm not sure what the current packaging process looks like, or if wheels can even pull in the required odbc libraries, so I can't speak for how feasible building manylinux wheels would be.

**Comment by graingert** [comment]
@mkleehammer any update on this? would manylinux2010 help?
