### ISSUE TITLE
Add native support for Python UUID data type

### ISSUE THREAD

**Issue by kevin-brown** [mkleehammer/pyodbc#177]
Looking through the Wiki documentation on [Data Types](https://github.com/mkleehammer/pyodbc/wiki/Data-Types/de8c706abd83214d69e6be0b5c2bb58b2c916212), I noticed that the SQL_GUID type is being converted to/from a string, instead of using [the native `UUID` type](https://docs.python.org/2/library/uuid.html) provided by Python. The SQL_GUID type applies to the `uniqueidentifer` column type, which [pyodbc appears to be testing](https://github.com/mkleehammer/pyodbc/blob/f94251a5b62252fff0e7057b6f70260cb4bf4fb0/tests2/accesstests.py#L426-L435) against.

These tests don't appear to have changed since 2008 (added in https://github.com/mkleehammer/pyodbc/commit/c3f6b46d8a4f73722439b4755ef5df42adff81d9), and there is a comment for the test that alludes to Python not having a UUID type. This was probably true back in 2008, but Python has come a long way since then and now it does have a UUID type.

**Comment by mkleehammer** [comment]
You are correct - uuid was added in Python 2.5 and pyodbc hasn't supported that in a while.

I probably would have wanted to make this change a few weeks back, but I've already released 4.0 and hate to break backwards compatibility so soon.

What about a flag to use native UUIDs along with a deprecation warning (docs only) and switch in v 5.0?  I don't have a time frame in mind for that yet, but it would let you write your code with native now.

**Comment by kevin-brown** [comment]
> What about a flag to use native UUIDs along with a deprecation warning (docs only) and switch in v 5.0?

That would probably be the best option to handle backwards compatibility.

**Comment by andreacassioli** [comment]
Hi,
this is very much needed I think! Good you put it on the table...

**Comment by mkleehammer** [comment]
FYI: There is a branch that handles this, but I don't have the flag to configure UUIDs to be returned natively all the time yet.  Had to put on hold for a bit.

**Comment by mkleehammer** [comment]
I've added to 4.0.9.

Now UUID objects are always accepted as parameters.  If you set pyodbc.native_uuid to True, GUID columns are also returned as UUID objets.  If False, the default for backwards compatibility, they are returned as text.

**Comment by jakubov** [comment]
hi @mkleehammer 
I have a stored proc that takes a @itemID of uniqueidentifier type and in python I'm passing it as a param of itemID = UUID(_a_uuid_str).  
However, I get the following exception on the `execute` call:

Error !!!!! ('22018', '[22018] [Microsoft][ODBC SQL Server Driver][SQL Server]Operand type clash: uniqueidentifier is incompatible with int (206) (SQLExecDirectW)')

Any ideas what might be the issue ?

thanks!
Rob

**Comment by kevin-brown** [comment]
> Any ideas what might be the issue ?

You stored procedure appears to be expecting an `int` but it's passing in a `uniqueidentifier` instead. You should be able to get around this by passing in the integer version of the UUID instead.

```python
itemID = UUID(_a_uuid_str).int
```

**Comment by jakubov** [comment]
@kevin-brown 

that give a `int too big to convert` error !
