### ISSUE TITLE
Windows install issue on Windows python 3.4

### ISSUE THREAD

**Issue by woakesd** [mkleehammer/pyodbc#178]
As there is no wheel for 3.4 it downloads and attempts to compile and I get the error "ValueError: path '/Users/mkleehammer/dev/pyodbc/src/buffer.cpp' cannot be absolute"

**Comment by mkleehammer** [comment]
Sorry about that.  It was actually fixed in #119 but apparently I needed to delete some old files before building.  I apparently can't repackage 4.0.0 and overwrite the existing one so I've released 4.0.1.

i've also provided 3.4 32-bit and 64-bit wheels.

Thanks for reporting it.
