### ISSUE TITLE
Pyodbc without C++

### ISSUE THREAD

**Issue by daym** [mkleehammer/pyodbc#179]
Hi,

not sure whether that's the correct venue but I forked pyodbc and made it C-only: https://gitlab.com/daym/pyodbc-c/ - I will maintain the fork for a long time (years) since I need it for a client of mine.

I'm bringing it up because I see that this original upstream project is very active lately and I wondered: what do you think about removing the C++ parts from upstream in the first place?

I'm using the aforementioned library pyodbc-c in production for about a year now - it works. If you want you are more than welcome to copy whatever you want.

(The reason I created pyodbc-c is that the servers we use don't have a working C++ compiler (no, really) and believe me, I tried to get gcc running on it. Doesn't work.)

**Comment by mkleehammer** [comment]
I have no plans for this at the moment.  What platform are you using that doesn't have a good C++ compiler but does have a good C compiler?

C has come a long way recently (actually C compilers caught up with the standard) so most of the convenience of C++ in pyodbc is already in C.  However, I use destructors for holding temporary objects and really like it.

**Comment by daym** [comment]
SunOS 5.10 on SPARC.

**Comment by mkleehammer** [comment]
I agree.  It's not something I'm ready to look at now, but I my interest is now piqued.  Let me get some of the features implemented and I'll look at it again.
