### ISSUE TITLE
building on mac os x 10.8, unknown command g++-4.2

### ISSUE THREAD

**Issue by mgrandi** [mkleehammer/pyodbc#18]
I was trying to build on mac os x 10.8, and it was working fine until it was trying to link the binary and it was complaining that it couldn't find "g++-4.2", i had to create a symlink named g++-4.2 -> g++

>Corvidae:pyodbc markgrandi$ python3 setup.py install --user
running install
running bdist_egg
running egg_info
creating pyodbc.egg-info
writing dependency_links to pyodbc.egg-info/dependency_links.txt
writing pyodbc.egg-info/PKG-INFO
writing top-level names to pyodbc.egg-info/top_level.txt
writing manifest file 'pyodbc.egg-info/SOURCES.txt'
reading manifest file 'pyodbc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'tests/*'
writing manifest file 'pyodbc.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_ext
building 'pyodbc' extension
creating build
creating build/temp.macosx-10.6-intel-3.3
creating build/temp.macosx-10.6-intel-3.3/Users
creating build/temp.macosx-10.6-intel-3.3/Users/markgrandi
creating build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code
creating build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git
creating build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc
creating build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/buffer.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/cnxninfo.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/cnxninfo.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/connection.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/connection.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/cursor.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/cursor.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/errors.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/errors.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/getdata.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/getdata.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/params.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/params.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/pyodbccompat.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/pyodbccompat.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/pyodbcdbg.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/pyodbcdbg.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/pyodbcmodule.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/pyodbcmodule.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/row.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/row.o -Wno-write-strings -Wno-deprecated-declarations
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -O3 -arch i386 -arch x86_64 -DPYODBC_VERSION=3.0.7 -UMAC_OS_X_VERSION_10_7 -I/Library/Frameworks/Python.framework/Versions/3.3/include/python3.3m -c /Users/markgrandi/Code/git/pyodbc/src/sqlwchar.cpp -o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/sqlwchar.o -Wno-write-strings -Wno-deprecated-declarations
creating build/lib.macosx-10.6-intel-3.3
g++-4.2 -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/buffer.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/cnxninfo.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/connection.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/cursor.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/errors.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/getdata.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/params.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/pyodbccompat.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/pyodbcdbg.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/pyodbcmodule.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/row.o build/temp.macosx-10.6-intel-3.3/Users/markgrandi/Code/git/pyodbc/src/sqlwchar.o -liodbc -o build/lib.macosx-10.6-intel-3.3/pyodbc.so
unable to execute g++-4.2: No such file or directory
error: command 'g++-4.2' failed with exit status 1

**Comment by mkleehammer** [comment]
You will need xcode installed to actually build on OS X.  I'll try making 10.10 binary distributions with wheel when I release 3.0.10.  Note that it will still require unixODBC, of course.

**Comment by mkleehammer** [comment]
OK - 3.0.10 is released with binary packages for 2.7 and 3.4 on OS X.  Please try `pip install pyodbc`.

**Comment by mgrandi** [comment]
That wasn't the problem, the problem was that it was calling a binary that didn't exist, probably because it had the version number in it. Of course I had xcode and the command line tools installed. Thanks for putting the wheels on pypi anyway
