### ISSUE TITLE
No results when VARCHAR(MAX) exceeds 8k characters on MS SQL

### ISSUE THREAD

**Issue by vtraag** [mkleehammer/pyodbc#183]
If a ``VARCHAR(MAX)`` exceeds the 8k characters, ``pyodbc`` does not return any result if ``unicode_results=True`` on MS SQL (``driver='{SQL Server Native Client 11.0}'``).

That is,
```python
>>> sql = "SELECT CAST(REPLICATE('x', 8000) AS VARCHAR(MAX)) + CAST(REPLICATE('x', 8000) AS VARCHAR(MAX)) AS txt";
>>> cursor = conn.execute(sql);
>>> results = cursor.fetchall()
[]
```
Using ``NVARCHAR(MAX)`` does return the correct result.
```python
>>> sql = "SELECT CAST(REPLICATE('x', 8000) AS NVARCHAR(MAX)) + CAST(REPLICATE('x', 8000) AS NVARCHAR(MAX)) AS txt";
```
If ``unicode_results=False``, it also returns the correct result for ``VARCHAR(MAX)``.

**Comment by mkleehammer** [comment]
I'm not reproducing this with v4.0.1.  Can you try it?  Note that it doesn't accept unicode_results=True - it is more configurable now.  You shouldn't need any special settings though - the default is for Unicode results in both Python 2.7 and 3.x.

**IMPORTANT:** It has a bug in decimal handling and I will be releasing 4.0.2 in the next hour or two, so test with it but don't keep it.

**Comment by vtraag** [comment]
I just tested with v4.0.3 PyPi, and can confirm there's no longer any issue. Thanks!

**Comment by mkleehammer** [comment]
Thanks for the update.  Good luck!
