### ISSUE TITLE
Consolidate documentation

### ISSUE THREAD

**Issue by mkleehammer** [mkleehammer/pyodbc#185]
Right now there are two sets of documentation - those in /docs which create the pyodbc website and the Wiki.  I've been trying to keep them the same but it seems like a bit much work.

I think I'd like to use the Wiki.  Since people may have bookmarked the original site I'll need to keep it but put a blurb pointing to the Wiki.

**Comment by gordthompson** [comment]
Sounds good to me. You can keep the website for a brief project overview and other "marketing materials" that won't change often, along with a link to the Wiki for the actual documentation.

**Comment by janscas** [comment]
Keeping just 1 place seems the correct way to go.
