### ISSUE TITLE
pyodbc.drivers() only available on Windows

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#186]
I just installed pyodbc 4.0.3 on Xubuntu 16.04 LTS x64 using

```none
sudo apt install python3-pip unixodbc-dev
sudo -H pip3 install pyodbc
```

The install was successful, but when I launch python3 and do

```python
import pyodbc
pyodbc.drivers()
```

I get

```none
>>> import pyodbc
>>> pyodbc.drivers()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyodbc' has no attribute 'drivers'
```

By contrast, `pyodbc.dataSources()` does not fail, it just returns an empty dictionary.

So it appears that `pyodbc.drivers()` is only available on Windows. Is that "by design"?

**Comment by gordthompson** [comment]
> So it appears that pyodbc.drivers() is only available on Windows. Is that "by design"?

It seems so. I checked the [source code](https://github.com/mkleehammer/pyodbc/blob/master/src/pyodbcmodule.cpp) and the definition for `mod_drivers` is within an `#ifdef WINVER` block.

It also retrieves the information directly from the Windows registry, despite the fact that there is an ODBC [SQLDrivers Function](https://msdn.microsoft.com/en-us/library/ms712400(v=vs.85).aspx) that has apparently been around since ODBC 2.0. I didn't see any comments in the source code explaining why it was implemented that way.

In theory it would be nice if pyodbc used the ODBC function to retrieve the list of drivers so `pyodbc.drivers()` could be available on non-Windows platforms. The one caveat would be that currently `pyodbc.drivers()` on Windows shows only the *available* drivers that match the bitness of the Python environment (i.e., 32-bit or 64-bit). That is very valuable when helping users troubleshoot connection issues with Access ODBC where there are separate 32-bit and 64-bit versions of the Access Database Engine, and I'd hate for `pyodbc.drivers()` to lose that feature on Windows.

**Comment by gordthompson** [comment]
On inspection of the source code for pypyodbc, it uses the ODBC `SQLDriversW` function to implement its `pypyodbc.drivers()` function. Testing it under 64-bit Python on Windows confirms that it only shows the relevant 64-bit ODBC drivers.

However, pypyodbc also includes a specific check to only support `.drivers` under Windows

```python
def drivers():
    if sys.platform not in ('win32','cli'):
        raise Exception('This function is available for use in Windows only.')
```

so presumably there's a reason for the restriction.

**Comment by gordthompson** [comment]
The Windows-only restriction on `pyodbc.drivers()` was removed in version 4.0.11.

**Comment by codeman101** [comment]
> The Windows-only restriction on `pyodbc.drivers()` was removed in version 4.0.11.

No it wasn't. when I run that function on mac or linux it returns an empty list.

**Comment by gordthompson** [comment]
@codeman101 - I can't vouch for Mac, but it certainly does work on Linux:

```python
print(platform.version())
# #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019

print("Python version: " + sys.version.replace("\n", ""))
# Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]

print("pyodbc version: " + pyodbc.version)
# pyodbc version: 4.0.27

print(pyodbc.drivers())
# ['MySQL_ANSI', 'MySQL_Unicode', 'ODBC Driver 17 for SQL Server']
```

**Comment by v-makouz** [comment]
@codeman101 I just tried it on the Mac and also seems to work (that's with pyodbc 4.0.18)

**Comment by v-chojas** [comment]
What version of unixODBC are you using? You can check with `odbcinst -j` command. Earlier versions of unixODBC were quite buggy; you can check www.unixodbc.org for the list of bugs that were fixed in each version.

**Comment by codeman101** [comment]
I probably didn't actually have a driver installed because of the struggle with doing so I've decided not to use pyodbc and continue using pymssql. Since you don't have to do extra steps after you do pip install with that. It makes it way easier to use for things like AWS lambda. It's a shame that pyodbc does not include the actual driver when you pick up install it and you have to go through extra steps on the Microsoft site to get it installed.

**Comment by gordthompson** [comment]
@codeman101 - pymssql is (was) only for connecting to SQL Server. pyodbc is for connecting to any number of ODBC drivers, not just SQL Server. Even if pyodbc could (legally and technically) distribute Microsoft's ODBC driver for SQL Server I don't think it would be appreciated by people who want to use pyodbc to connect to Teradata, or DB2, or some other non-Microsoft database.

**Comment by codeman101** [comment]
@gordthompson 

In case it really should be made possible to do commands `pip install pyoodbc.sqlserver` 'pip install pyodbc.mysql' because the current method for installing a driver for pyodbc is harder than it should be IMO not to mentioned it makes it impossible to use with AWS Lambda.

**Comment by v-chojas** [comment]
The ODBC Driver for SQL Server is not open-source and cannot be distributed in that manner.

**Comment by codeman101** [comment]
@v-chojas is being open source a requirement to be a pip package?
