### ISSUE TITLE
PyCodec_Encode error handler in params.cpp

### ISSUE THREAD

**Issue by keitherskine** [mkleehammer/pyodbc#187]
This is very minor, but within params.cpp, I suspect that the references to `"errors"` in calls to `PyCodec_Encode()` should probably refer to `"strict"` instead.  `"errors"` is not one of the [standard error handlers](https://docs.python.org/3/library/codecs.html#error-handlers). There are two examples of this:
https://github.com/mkleehammer/pyodbc/blob/master/src/params.cpp#L119
https://github.com/mkleehammer/pyodbc/blob/master/src/params.cpp#L167

In those cases, `PyCodec_Encode(param, enc.name, "errors")` should probably be `PyCodec_Encode(param, enc.name, "strict")`

This would match what is in sqlwchar.h, e.g.:
https://github.com/mkleehammer/pyodbc/blob/master/src/sqlwchar.h#L54

There would be no change in behavior, because, as I understand it, if the bytes cannot be encoded then PyCodec_Encode() will return null whether the error handler can be found or not, but it would be preferable if the code did not refer to a non-existent error handler.

**Comment by mkleehammer** [comment]
Very good catch - thanks.  I'll fix now but since I don't *think* it is causing anything to fail I'm not going to make a new release just yet - due to the massive Unicode rewrite I've already released a few patches.  If this is causing issues, please let me know and I'll tag it.

**Comment by keitherskine** [comment]
It's not causing an issue for me, Michael. Feel free to release at your leisure.
