### ISSUE TITLE
[Question] Progress DataDirect ODBC

### ISSUE THREAD

**Issue by iagomez** [mkleehammer/pyodbc#188]
Hello,

I have licensed the Progress DataDirect SQL Server ODBC Driver and I'm trying to use `pyodbc` to connect to my database, but I'm running into some complications while trying to build the module. Here is all the relevant information:

**Versions**
**OS:** RHEL 7
**pyodbc:** 4.0.3

**ODBC Information**
**Install location:** `/gpfs/grid/progress`

## Issues Resolved so far:
**setup.py changes:**
I edited `setup.py` and after line  180 I added the following:
```python
settings['extra_compile_args'].append('-I/gpfs/grid/progress/include/')
settings['extra_compile_args'].append('-L/gpfs/grid/progress/lib/')
```

After making the changes above, I got the following error: `COMPILER ERROR: 'SQL_CP_ONE_PER_HENV' WAS NOT DECLARED IN THIS SCOPE`. I resolved it by editing the `sqlext.h` header file as recommended [here](http://knowledgebase.progress.com/articles/Article/000007256)

## Current Issue:
```
g++ -pthread -shared -L/gpfs/grid/spyder-test/lib -Wl,-rpath=/gpfs/grid/spyder-test/lib,--no-as-needed build/temp.linux-x86_64-2.7/src/row.o build/temp.linux-x86_64-2.7/src/params.o build/temp.linux-x86_64-2.7/src/connection.o build/temp.linux-x86_64-2.7/src/pyodbcdbg.o build/temp.linux-x86_64-2.7/src/errors.o build/temp.linux-x86_64-2.7/src/buffer.o build/temp.linux-x86_64-2.7/src/cursor.o build/temp.linux-x86_64-2.7/src/getdata.o build/temp.linux-x86_64-2.7/src/pyodbccompat.o build/temp.linux-x86_64-2.7/src/cnxninfo.o build/temp.linux-x86_64-2.7/src/pyodbcmodule.o -L/gpfs/grid/spyder-test/lib -lodbc -lpython2.7 -o build/lib.linux-x86_64-2.7/pyodbc.so
/opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.2.1/ld: cannot find -lodbc
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```

The DataDirect drivers require the DataDirect driver manager located in `/gpfs/grid/progress/lib` so installing `unixODBC` is not an option.

Could you please help me get past this issue? I assume I'm missing a small change to `setup.py` or one more compile argument.

Thank you,
Ivan G.

**Comment by iagomez** [comment]
# Update

I was able to get through `setup.py build` by edits after line 180 to:
```
settings['include_dirs'].append('/gpfs/grid/progress/include/')
settings['extra_link_args'].append('-L/gpfs/grid/progress/lib/')
```

# New Problem
If I start python and try to `print pyodbc.dataSources` I get the following error:
`Fatal Python error: Unable to set SQL_ATTR_CONNECTION_POOLING attribute.`

I was able to work around it with `pyodbc.pooling = False`

Now `print pyodbc.dataSources()` runs, but I'm not seeing any of my data sources defined in my odbc.ini file and the connection fails if I try to use one of my DSN's:
```
>>>pyodbc.pooling = False
>>>pyodbc.dataSources()
{'SQL Server Legacy Wire Protocol': 'DataDirect 7.1 SQL Server Legacy Wire Protocol', '': '', 'SQL Server Wire Protocol': 'DataDirect 7.1 SQL Server Wire Protocol'}
```

Any advise?

Thank you,
Ivan G.

**Comment by keitherskine** [comment]
What `dataSources()` returns depends on the driver, and where the driver looks for odbc.ini files.  Those odbc.ini files could be in a number of places, here's a few suggestions:

- /etc/odbc.ini
- ~/.odbc.ini
- /opt/Progress/DataDirect/Connect_for_ODBC_71/odbc.ini
- ~/Progress/DataDirect/ODBC71/odbc.ini

`$ODBCINI` should point to one of those files, but won't necessarily be the one the driver is looking at.  I would suggest you compare what's in those odbc.ini files with the output from `dataSources()` and see which odbc.ini file pyodbc is looking at (probably).  Then place your DSN info in that file.

**Comment by iagomez** [comment]
Thank you for your help @keitherskine.

The only odbc.ini file I have is in the the Data Direct installation directory, which for me is `/gpfs/grid/progress`. This file is symlinked to /etc/odbc.ini

```
-bash-4.2$ ll /gpfs/grid/progress/odbc.ini
-rw-r--r--. 1 root 10003 5424 Jan 30 12:38 /gpfs/grid/progress/odbc.ini
```
```
-bash-4.2$ ll /etc/odbc.ini
lrwxrwxrwx. 1 root root 28 Feb  7 16:07 /etc/odbc.ini -> /gpfs/grid/progress/odbc.ini
```
```
-bash-4.2$ ll ~/.odbc.ini
ls: cannot access /ace/home/igomez/.odbc.ini: No such file or directory
```
```
-bash-4.2$ ll /opt/Progress
ls: cannot access /opt/Progress: No such file or directory
```
```
-bash-4.2$ ll ~/Progress
ls: cannot access /ace/home/igomez/Progress: No such file or directory
```
```
-bash-4.2$ echo $ODBCINI
/gpfs/grid/progress/odbc.ini
```

**Comment by keitherskine** [comment]
That looks OK to me, so what's the connection string you use in the `connect()` function, what's the error message you're getting when you try to connect, and what's the contents of `/gpfs/grid/progress/odbc.ini`?

**Comment by iagomez** [comment]
@keitherskine So even though the DSN's are not listed in the output, I can still connect to them, but the code fails as shown below

### The following snippet:
```
import pyodbc
pyodbc.pooling = False

cnxn = pyodbc.connect('DSN=My_ODBC_DSN; UID=<user>; PWD=REDACTED')
cursor = cnxn.cursor()

for row in cursor.tables():
    print row.table_name
```

### Generates this error:
```
Traceback (most recent call last):

 File "<ipython-input-7-c5d7cce056ee>", line 1, in <module>
   for row in cursor.tables():

UnicodeDecodeError: 'utf16' codec can't decode byte 0x6f in position 2: truncated data
```


I'm using Progress Data Direct, but I found this information on the easysoft site about UCS2 vs UCS4 python builds:
http://www.easysoft.com/developer/languages/python/pyodbc.html#ucs4

```
-bash-4.2$ python -c "import sys;print(sys.maxunicode<66000 and'UCS2'or'UCS4')"
UCS4
```

Could this be related to the the error I'm seeing? My Python install is an Anaconda 64 bit install.

Thank you for your help!

**Comment by keitherskine** [comment]
Your connection is working, so your DSN and odbc.ini file are fine.  The issue appears to be a unicode one.  See the wiki page https://github.com/mkleehammer/pyodbc/wiki/Unicode and the docs http://mkleehammer.github.io/pyodbc/unicode.html.  You probably need to call the connection functions `setencoding()` and `setdecoding()`.  What you set there depends on the Progress driver.  Try a few values, starting with utf-8.

**Comment by iagomez** [comment]
Thank you @keitherskine. I was able to the previous snippet to work with these addition:
```
cnxn.setencoding(str, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
```

The `pyodbc.SQL_CHAR` was key. suggesting my current configuration doesn't support wide calls, which is consistent with what the easysoft guys said [here](http://www.easysoft.com/developer/languages/python/pyodbc.html#ucs4)

## Last Question

If I don't set pooling to `False`, I get the following error:
```
Fatal Python error: Unable to set SQL_ATTR_CONNECTION_POOLING attribute.
```

Even though, according to the [Progress Documentation](http://media.datadirect.com/download/docs/odbc/allodbc/index.html#page/odbc/using-datadirect-connection-pooling.html) pooling is supported for my SQL Server ODBC driver

Thanks again for all the help!

**Comment by keitherskine** [comment]
I doubt very much whether that encoding issue was something to do with the UCS2/UCS4 setting of your Python installation.  It's more likely to be about how the Progress driver implements the "wide" ODBC functions like SQLDriverConnectW, SQLPrepareW, and SQLExecDirectW.  Just continue to call `setencoding` and `setdecoding` and you should be fine.

I'm afraid I can't help you with the SQL_ATTR_CONNECTION_POOLING error you're getting.  That's something to do with the internals of the driver.  The Progress documentation may say it's possible, but the reality seems to be somewhat different.  Looks like you'll have to continue setting `pooling` to False for the time being.

**Comment by keitherskine** [comment]
It's a bit odd that your kernel dies when connection pooling cannot be set, though.  This seems to be because [`Py_FatalError`](https://docs.python.org/3/c-api/sys.html#c.Py_FatalError) is being called in [`AllocateEnv()`](https://github.com/mkleehammer/pyodbc/blob/09072a08b68a2a2b06cb8bb638341c7cc62f1511/src/pyodbcmodule.cpp#L216). @mkleehammer , that seems quite a "hard" exit.  The [documentation](https://docs.python.org/3/c-api/sys.html#c.Py_FatalError) says that causes a core dump.  Should those calls to `Py_FatalError` perhaps be replaced with [`Py_Exit`](https://docs.python.org/3/c-api/sys.html#c.Py_Exit) instead? (And the error message simply written to the terminal).

**Comment by mkleehammer** [comment]
That's a very good point.  Actually, probably just a runtime error - since this happens during the import it would simply cause the import mechanism to raise an exception.  I think most scripts would probably exit when this happens, but it really shouldn't be pyodbc making that decision.  I'll keep this open and make an update.  I probably won't make a new patch just for this update but that way it'll be fixed in the next.

**Comment by iagomez** [comment]
@keitherskine @mkleehammer 
Thank you guys for your help and your time. I really appreciate it. If there's anything I can do to help, let me know.
