### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by janscas** [mkleehammer/pyodbc#190]
I have just upgraded from python 2.7.11 to python 3.6 and i'm porting a project that used pyodbc version 3.0.10.

back in the 2.7 version everything works just fine. My Connection was:

```
con = pyodbc.connect(driver='{SQL Server Native Client 11.0}', server=db_path,
                                 database=DBNAME, trusted_connection='yes', unicode_results=True)
```

Now, with the same code, but with pyodbc 4.0.3 and python 3.6 It's not working anymore.
My database collation is (and was) Modern_Spanish_CI_AI

I have just tried every posible combination of:
```
con.setdecoding()
con.setencoding()
```
with pyodbc.SQL_CHAR and pyodbc.SQL_WCHAR, and encodings: 'utf-8', 'latin-1', 'latin1', 'windows-1250', 'windows-1252'... And it doesn't work.

The error is every time the same:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 13: invalid continuation byte

This error is not happening when selecting rows, but when executing a a storedprocedure. The code line that fails is:

`cursor.nextset()`

Any help?

**Comment by janscas** [comment]
I have found what's causing the problem.

On the final select of the stored procedure there are some columns renamed with spanish accents.

For example:

"SELECT tAGT_TipoDesc AS 'Tipolog**í**a"

The AS clause rename the column with a string that has an accent **í**.
Renaming to an ASCII string  (just 'Tipologia') stops the error.

It's really strange because the result set (the rows) contains lots of accents and spanish characters such as 'ñ'. And that is not causing any problem.

How can I fix this without modifying the stored procedure (I normaly only have read permission so I can not change the stored procedure)?

**Comment by mkleehammer** [comment]
Dang - that'll require a fix on my side.  I very carefully rewrote Unicode handling for *data*, but it looks like I missed the meta data.  I'll try to work on it today.

**Comment by janscas** [comment]
Great, thanks a lot

**Comment by mkleehammer** [comment]
OK, I think v4.0.5 fixes this for you.

Now, I'm pretty sure that the collation you are using sets the code page to latin1, so I think you'll also want to put these in your connection function [1]:

    self.cnxn.setencoding('latin1')
    self.cnxn.setdecoding(pyodbc.SQL_CHAR, 'latin1')

[1] I always make a central function in each product / project that allocates all connections so I have a central place configure them or even wrap connections in other classes.

**Comment by janscas** [comment]
Great! thanks

**Comment by jbajor** [comment]
Hello @mkleehammer . I think the solution to this problem causes problems in another use case. I have no problems using 4.0.3, but things break for me on 4.0.5 and newer versions. I have been looking for changes and believe changes made in 57288699df86c216308c88b197812a03c2f2bf42 are the culprit. The problem is with decoding column names.

Here's the code:

    db_conn_str = ('DRIVER={{NetezzaSQL}};SERVER=thenetezzaserver.org;'
                   'PORT=5480;DATABASE={};UID={};'
                   'PWD={};').format(db_name, db_user, db_pass)

    db_connection = pyodbc.connect(db_conn_str)

    db_connection.setencoding('utf-8')
    db_connection.setdecoding(pyodbc.SQL_CHAR, 'utf-8')
    db_connection.setdecoding(pyodbc.SQL_WCHAR, 'utf-8')

    c = db_connection.cursor()
    r = c.execute("SELECT * FROM medex LIMIT 2")
    a = r.fetchall()
    b = r.description

The result for r.description on 4.0.3 is:

    (('ID', int, None, 19, 19, 0, False),
     ('IND_SEQ', int, None, 19, 19, 0, True),
     ('ENTRY_DATE', datetime.datetime, None, 26, 26, 6, True),
     ...)

But on 4.0.5 and later:

    (('䑉Ȁ', int, None, 19, 19, 0, False),
     ('义彄䕓Q\x00\x00\x00', int, None, 19, 19, 0, True),
     ('久剔彙䅄䕔\x00\x00\x00輀ɲ', datetime.datetime, None, 26, 26, 6, True),
     ('剄䝕也䵁E\x00\x00\x00輀', str, None, 255, 255, 0, True),
     ...)

I am using Netezza, Python 3.6.2, unixODBC 2.3.1, CentOS 7.3. I would greatly appreciate your help. I might be useless at finding the problem in the code, but I will be very happy to test the changes.

**Comment by keitherskine** [comment]
@jbajor , I don't know if this will help, but there is a third sql type called `pyodbc.SQL_WMETADATA` that can be configured with `setdecoding()`, and is specifically for column descriptions.  See https://github.com/mkleehammer/pyodbc/wiki/Connection#sqltype .  Maybe give that a try.

**Comment by jbajor** [comment]
@keitherskine It worked! Thank you. I should have dug deeper into the documentation.

**Comment by keitherskine** [comment]
Glad it worked, @jbajor .  Could you describe what settings you used so that we can add Netezza to the Wiki.  Was it the following? :
```
db_connection.setencoding('utf-8')
db_connection.setdecoding(pyodbc.SQL_CHAR, 'utf-8')
db_connection.setdecoding(pyodbc.SQL_WCHAR, 'utf-8')
db_connection.setdecoding(pyodbc.SQL_WMETADATA , 'utf-8')
```

**Comment by jbajor** [comment]
@keitherskine Yes, the settings above are all that I need to connect to and use Netezza with pyodbc.

**Comment by keitherskine** [comment]
Thank you @jbajor , good to know.

**Comment by glima20** [comment]
@keitherskine Thanks a lot, finally I've found a great solution to my issues with pyodbc.
Justo to Know...

without your solution:

䅔䱂彅䑉 | 䅓偍䥌䝎䑟呁Eᐰ落缤䕮 | 䅖啌E䝎䑟
-- | -- | --
义啓䅒䍎彅䅐䡔 | 2009-09-21 23:00:02 | 13839367816
义啓䅒䍎彅䅐䡔 | 2009-09-22 23:00:01 | 13843998644
义啓䅒䍎彅䅐䡔 | 2009-09-23 23:00:03 | 13848632458

with your solution using only (I've set the encoding in the odbc.ini on linux RHEL, that is, UnicodeTranslationOption = utf8) :

cnxn.setdecoding(pyodbc.SQL_CHAR, 'utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, 'utf-8')
cnxn.setdecoding(pyodbc.SQL_WMETADATA , 'utf-8')

TABLE_ID	SAMPLING_DATE	VALUE
0	INSURANCE_PATH	2009-09-21 23:00:02	13839367816
1	INSURANCE_PATH	2009-09-22 23:00:01	13843998644
2	INSURANCE_PATH	2009-09-23 23:00:03	13848632458

ps: Thank to your solution I've avoided to test my Chinese language :)

**Comment by keitherskine** [comment]
No problem, @glima20 .  I'm glad it worked.
