### ISSUE TITLE
Connection.setencoding() doesn't affect unicode parameter encoding

### ISSUE THREAD

**Issue by smsearcy** [mkleehammer/pyodbc#195]
Reading about [unicode](http://mkleehammer.github.io/pyodbc/unicode.html) my understanding is if I do the following in Python 3 it should encode the parameters as SQL_VARCHAR:

    import pyodbc
    cnxn = pyodbc.connect('DSN=')
    cnxn.setencoding(encoding='utf-8', ctype=pyodbc.SQL_CHAR)
    cursor = cnxn.cursor()
    cursor.execute("SELECT id, name FROM user_table WHERE name = ?", ['scott'])
    print(cursor.fetchone())

However, when I attempt that it is still binding the parameter as `SQL_WVARCHAR` (Python 3.5.2 and pyodbc 4.0.6 on Windows):

		HSTMT               0x000000A0DC7215B0
		UWORD                        1 
		SWORD                        1 <SQL_PARAM_INPUT>
		SWORD                        1 <SQL_C_CHAR>
		SWORD                       -9 <SQL_WVARCHAR>
		SQLULEN                   12
		SWORD                        0 
		PTR                0x000000A0D9BEB0E0
		SQLLEN                    12
		SQLLEN *            0x000000A0DA403E28

		DIAG [HY004] [Microsoft][ODBC Driver Manager] SQL data type out of range (0)

(I have an ODBC driver that doesn't support UTF-16)

Am I misunderstanding how `setencoding()` is supposed to work?

I did a test by copying the 

    info.ParameterType = (enc.ctype == SQL_C_CHAR) ? SQL_VARCHAR : SQL_WVARCHAR;

and similar lines in `param.cpp` from `GetStrInfo()` into `GetUnicodeInfo()` and it seemed to work (see https://github.com/smsearcy/pyodbc/tree/py3-unicode).  However the test was on Fedora and I'm getting a MemoryError with pyodbc 4.0.6 (pyodbc 3.1.1 does not have an issue).  My normal environment is Windows, in which 4.0.6 worked, but I'm not setup to compile packages on Windows so I used Fedora for the test.  I realize this isn't an ideal test scenario but I wanted to get the issue out there while I do a little more digging on the MemoryError.

Here's the trace from the successful test (the MemoryError occurs while loading results):

                Entry:
                        Statement = 0x55dcfc93c1d0
                        Param Number = 1
                        Param Type = 1
                        C Type = 1 SQL_C_CHAR
                        SQL Type = 12 SQL_VARCHAR
                        Col Def = 12
                        Scale = 0
                        Rgb Value = 0x7f6797f8c260
                        Value Max = 12
                        StrLen Or Ind = 0x55dcfc93ddf8

**Comment by mkleehammer** [comment]
I believe you are correct.  What driver are you using?  I'd like to reproduce it before making the change so I can fix the memory error.  (Are you saying this change causes the memory error or the error already exists so you can't really test?)

Note, however, that since very few drivers are following the specification the configuration you have *is* writing UTF-8 (single byte data in your case) but is marking at as SQL_WVARCHAR -- it isn't passing UTF-16.  (That's what it is supposed to do for databases like PostgreSQL and MySQL that pass UTF-8 in both types of buffers.).  It would not surprise me if there is some encoding that works with SQL_WVARCHAR in the meantime.  However, I do want to make the fix you suggest I just need to find a database with that behavior to test against.

**Comment by smsearcy** [comment]
Thank you for the quick response.  The driver is [SQL/R ODBC](http://www.marxmeier.com/products/sqlr-odbc.html), probably kind of a niche driver.

Regarding the memory error, it was not caused by the change I made but seems to be an issue I'm encountering with pyodbc 4.x (including 4.0.7, I saw that was just released) on Fedora 24 with this ODBC driver (on both Python 2.7.12 and 3.5.2), specifically when querying for text (I didn't realize that distinction previously).

I did just test decoding options from the documentation for Postgres/MySQL but that did not fix the memory error.  I've attached a full [ODBC trace](https://github.com/mkleehammer/pyodbc/files/781818/sqlr-odbc-trace.txt) for the test I ran with pyodbc 4.0.7 that fails with the memory error (using the numeric id field for the criteria - it's passed as a double because this is the same driver I mentioned in #84 that chokes on SQL_BIGINT).

I'm intermingling the memory issue and the parameter encoding issue.  If you prefer I can create separate issues for them.

**Comment by smsearcy** [comment]
@mkleehammer, I solved the memory issue.  That ODBC driver ships with two 64-bit versions depending on the length of the [SQLLEN/SQLULEN types](http://www.easysoft.com/developer/interfaces/odbc/64-bit.html#odbc).  When I previously tested this driver on Linux I had to use the "legacy" version, now I was able to use the proper 64-bit version.

That also means I was able to test my changes and they worked correctly.  Would you like a pull request?

**Comment by mkleehammer** [comment]
Great - that's good to hear.  I'm already in the code to fix #84 so I'll fix this also.  Thanks though.

**Comment by smsearcy** [comment]
Thank you, works great!

**Comment by pdimopoulos** [comment]
ODBC Driver 18 for SQL Server utf8
