### ISSUE TITLE
pyodbc and DBISAM ODBC driver

### ISSUE THREAD

**Issue by lanec** [mkleehammer/pyodbc#196]
This is not a bug report.  I think it's more of a feature request/troubleshooting request.  

I am working to get a Django project to talk with a DBISAM 4.21 database using the pyodbc and django-pyodbc software and can find little to nothing about how to make this work.  It seems to me that DBISAM is a relatively obscure proprietary database server software based on SQL-92 standards.  It is not listed as supported by pyodbc at this time.  I'd like to see if it's not supported by pyodbc because of it's obscurity or if there is a technical hurdle. 

The company that makes the software (Elevate Software) claims on their website that they support connections from non Delphi based projects using their provided ODBC driver (http://www.elevatesoft.com/products?action=order&category=dbisam&type=other).  I've been provided with Visual Basic code that apparently works with this ODBC driver provided by the vendor.

I'm trying to use the DBISAM 4.21 database because I am working on interfacing an existing software written in Delphi that stores it's data in the DBISAM database with a new Python 3 + Django 1.10 based software that is yet to be written.

We have a test environment with Windows 2012 R2 running the DBISAM server software.  It has the ODBC driver from the vendor installed along with the vendors Delphi based application.  We have also loaded Python 3.6 along with Django 1.10.5 so we can try and get a connection working. 

I am completely new to the world of DBISAM database technology AND completely new to the Python ODBC world so let me know if I can offer more details on anything to help the process.  

I am wondering if anyone has successfully initiated a connection using pyodbc to a DBISAM database using pyodbc and the ODBC driver from Elevate Software?  If so could you provide some help?

If not, it appears that this software will accept DSN connections.  Is there a good resource for learning more about how to formulate the proper syntax for one of these?  The software vendor we are trying to integrate with has zero experience in Python.  They can't help much.

**Comment by mkleehammer** [comment]
pyodbc passes the connection string as-is to the ODBC driver, so if the other project is using ODBC you can use the exact same string.  The documentation for your driver seems to be here:

http://www.elevatesoft.com/manual?action=viewtopic&id=dbisam4odbc&topic=connection_strings

Give it a try and report back what happens.  If there are any errors, copy the whole error message.  

The manual has very little information about [Unicode](https://github.com/mkleehammer/pyodbc/wiki/Unicode) and encodings, but my guess is the settings will work out of the box.

**Comment by lanec** [comment]
Thanks for the link!  

Using that and the page: https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Windows

I used the DSN name setup in Windows and got the error "the specified dsn contains an architecture mismatch between the driver and application", if you want to see the full error output: http://clicky.strapr.com/2v1X3E3Y3A3D

**Comment by lanec** [comment]
Looks like this means I have to use a 32 bit version of Python and not a 64 bit version: http://stackoverflow.com/questions/36965600/pyodbc-the-specified-dsn-contains-an-architecture-mismatch-between-the-driver

I'll try and switch to that now.

**Comment by lanec** [comment]
After switching to trying to connect using DSN and to Python 3 x86 I'm able to now use the following without an error in the Python shell: 

`pyodbc.connect(r'DSN=databasename;UID=User;PWD=Password’)`

I'll move to the Django-pyodbc Github project now to troubleshoot the issues I'm having with getting a connection going in that framework.  Thank you for the help!

**Comment by mkleehammer** [comment]
Good luck!  I'm going to close this now.

**Comment by lanec** [comment]
UPDATE:

The connection has been made using pyodbc within Windows 2012 R2 using Python 3.6 32bit.  

Would it be helpful to provide a write up for others?

**Comment by mkleehammer** [comment]
Absolutely!  Can you add it to the Wiki?  Thanks.
