### ISSUE TITLE
If it possible to suport DB2 XML column type

### ISSUE THREAD

**Issue by asierra01** [mkleehammer/pyodbc#197]
I was playing with pyodbc and DB2 11 on windows

"DRIVER={IBM DB2 ODBC DRIVER};SEVER=localhost;PORT=50000;DATABASE=sample;UID=user1;PWD=password1"

..and if I do SELECT * from customer
it was giving me the error 
pinfo->sql_type = -370, that's for ibm_db.SQL_XML DB2 XML column type value

RaiseErrorV("HY106", ProgrammingError, "ODBC SQL type %d is not yet supported. column-index=%zd  type=%d",
                       (int)pinfo->sql_type, iCol, (int)pinfo->sql_type)

so I went to the src\getdata.cpp in pyodbc source code and changed, line 780 

 case -370: //DB2.SQL_XML
        return GetText(cur, iCol);

and 699
case -370://ibm_db.SQL_XML 

 and now my select works, but I am not sure if ODBC API has an XML data type and if that matches DB2 XML data type.

**Comment by asierra01** [comment]
...that was quick....

**Comment by asierra01** [comment]
Testing with python3 under mac I get 

Python(59177,0x7ffff12d43c0) malloc: *** mach_vm_map(size=140733193392128) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Exception   <class 'MemoryError'>

will keep investigating....

**Comment by mkleehammer** [comment]
Hmmm...  That's 0x7FFF,0000,1000 which looks very suspicious.  If you know what the decimal value is, we can put it into the unit tests for some other DBs and see if we get the same thing.

**Comment by asierra01** [comment]
I did a test with DB2 10.1 on mac, client pyodbc on mac...crashes
...did a test docker DB2 11.1 on mac , client pyodbc on mac ...crashes

the test is very simple...connect to SAMPLE database ( is like a demo DB2 database) and I do select * from customer, customer table has 2 DB2 XML fields...

will keep investigating...

**Comment by mkleehammer** [comment]
I did not know you could be DB/2 for the Mac.  I'll have to download Express and test...

**Comment by asierra01** [comment]
on windows works OK...let me keep investigating...with Db2 on a docker container, one can run DB2 almost everywhere you can run docker....

**Comment by asierra01** [comment]
Last test works ok...will keep experimenting ....
pyodbc==4.0.17b4 works ok on mac using XML fields from SAMPLE database, table customer.
SELECT * from customer, loop through the cursor...print the fields.
Will do more complex tests, in the future.

**Comment by mkleehammer** [comment]
So, I am assuming we can close this now that whatever is in 4.0.17b4 has been released in 4.0.19.  Please reopen if I misunderstood.

**Comment by asierra01** [comment]
Yes, close it. The last test I did all was ok.
