### ISSUE TITLE
pyodbc - Unable to install on Solaris Box

### ISSUE THREAD

**Issue by wsharad** [mkleehammer/pyodbc#200]
Hi,

Your site is great, and I am trying to get pyodbc installed on my Solaris machine. However it's not working and going through. Any help is much appreciated. Thanks.

SunOS XXX 5.10 Generic_150400-32 sun4v sparc SUNW,Sun-Fire-T200
Python 3.5.3 (default, Feb 23 2017, 11:44:49) [C] on sunos5

Tried same with different versions : pyodbc-master & pyodbc-3.1.2.tar

bash-2.03$ /Python/bin/python3.5 setup.py build 
running build
running build_ext
building 'pyodbc' extension
cc: illegal option -Wno-write-strings
error: command 'cc' failed with exit status 1

**Comment by mkleehammer** [comment]
Hmmm.  Your compiler doesn't support '-Wno-write-strings' which is set in setup.py.  I'm not sure how I would detect that automatically.

If you can build from source, either by downloading or checking out the code, you would look for:

    # Other posix-like: Linux, Solaris, etc.

    # Python functions take a lot of 'char *' that really should be const.  gcc complains about this *a lot*
    settings['extra_compile_args'].append('-Wno-write-strings')

And comment out the `settings` line.

**Comment by Costonied** [comment]
Hello,

I also have the problem with build on my Solaris machine.
My Solaris is: _SunOS z29-ld6 5.11 11.2 sun4v sparc sun4v_

`$ python setup.py build`
`...`
`creating build/temp.solaris-2.11-sun4v-2.6/src
/usr/lib/python2.6/pycc -DNDEBUG -KPIC -DPYODBC_VERSION=4.0.0-unsupported -I/usr/include/python2.6 -c src/cnxninfo.cpp -o build/temp.solaris-2.11-sun4v-2.6/src/cnxninfo.o -Wno-write-strings -DHAVE_UNISTD_H -DHAVE_PWD_H -DHAVE_SYS_TYPES_H -DHAVE_LONG_LONG -DSIZEOF_LONG_INT=4 -I/usr/include/odbc`
`**gcc: error: unrecognized command line option '-KPIC'**`
`error: command '/usr/lib/python2.6/pycc' failed with exit status 1`

On the one web-site ([here](https://www.prelude-siem.org/issues/288)) I found:

> In this case "-KPIC" is a valid option for the Sun C compiler,
> but not for gcc. The equivalent option for gcc is "-fPIC"

Do you know how to set up "-fPIC" instead "-KPIC"?

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
