### ISSUE TITLE
Parameterized query causes python to hang

### ISSUE THREAD

**Issue by ad-65** [mkleehammer/pyodbc#201]
When using the [FileMaker ODBC](http://www.filemaker.com/support/technologies/odbc.html) driver on windows query parameters cause the python process to hang.

```python
#No problem
cur.execute("SELECT * FROM \"Access|Products\" WHERE product = '{}'".format("tst_val"))

#Hangs the python process with no error
cur.execute("SELECT * FROM \"Access|Products\" WHERE product = ?", ("tst_val",))
```

The ODBC trace (attached) just shows 'SQLPutData' repeating over and over until the python process is killed. I am not sure if this a a pyodbc issue, the FileMaker driver behaving badly, or a bit of both.

Thanks.

[sql_log.zip](https://github.com/mkleehammer/pyodbc/files/800615/sql_log.zip)

**Comment by mkleehammer** [comment]
pyodbc asks the driver what the maximum varchar & wvarchar lengths are and uses SQLPut if the length is higher.  There is apparently a bug in that it seems to report -1 and I didn't catch that.  Please try the following override and see if it fixes it.  If it does, I'll update the code to look for values that are too small and keep the default:

    cnxn.maxwrite = 1024 * 1024

**Comment by ad-65** [comment]
Thanks for the explanation and the fix. The override you gave works great.

So the FileMaker driver is reporting -1 when asked about its field length instead of a valid length? FileMaker has limited data types and that particular field is a "Text" field which according to their documentation can store 2gb or 10^9 character. There may be some peculiarities in their ODBC implementation.

Anyway, thanks again for the help.
