### ISSUE TITLE
Installing using setup.py not working on windows

### ISSUE THREAD

**Issue by hammer-of-thor** [mkleehammer/pyodbc#204]
Traceback (most recent call last):
  File "D:\Python\packs\pydbc\setup.py", line 292, in <module>
    main()
  File "D:\Python\packs\pydbc\setup.py", line 70, in main
    files = [ relpath(join('src', f)) for f in os.listdir('src') if f.endswith('
.cpp') ]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'src'

The src folder is definitely there...

(Btw, this is the first issue I've ever posted, so by all means ask for all the info you need)

**Comment by mkleehammer** [comment]
Are you in the "pydbc" directory when you run it.  It is using a relative path so it would be looking for a "src" directory under the *current* directory.  If you are in the "packs" directory when. you run it, it would be looking for "packs\src".

**Comment by hammer-of-thor** [comment]
I'm running everything from the pydbc folder. I'm just unpacking the entire zip as is into 'packs'. So everything is in a folder called pydbc in packs. In the pydbc folder is both the setup.py and the src folder.

![image](https://cloud.githubusercontent.com/assets/24958927/23366289/7dbb883e-fd06-11e6-97f3-5cafb0b09bd9.png)

**Comment by mkleehammer** [comment]
I'm not sure what to say.  I run it on Windows all the time - in fact I just did so to build 4.0.14 for uploading.

Are you using a batch file or anything?  I use `python setup.py build` from the pyodbc directory.

**Comment by hammer-of-thor** [comment]
Tried this again... Including the build command. I'll try another update...

**Comment by hammer-of-thor** [comment]
Nope, same thing. I feel like ' src' is a hardcoded string that doesn't relate to the real (dynamic) network path.. But I don't know enough about this to say this for sure.
![image](https://cloud.githubusercontent.com/assets/24958927/23742839/bedb0ff6-04ae-11e7-9ee5-b0b8b930d606.png)

**Comment by skillian** [comment]
@hammer-of-thor Have you tried: `cd /d D:\Python\packs\pyodbc-master` and *then* `setup.py build`?
I think `relpath` is checking for a relative path, but you're current working directory is `H:`.

**Comment by hammer-of-thor** [comment]
That appears to have solved it! :) Tyvm
