### ISSUE TITLE
Decode error in column name of cursor_description

### ISSUE THREAD

**Issue by zhangjiajie023** [mkleehammer/pyodbc#205]
python 3.5
pyodbc 4.0.11

When i use pyodbc to select a table with chinese column name and chinese data, it can fetch right chinese data, but messy code for column name. connection is set as blowed:
```
conn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
 conn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-16le')
 conn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-16le')
 conn.setencoding(encoding='utf-8')
```

the chinese column name `åºå·` in metadata of results is decoding by `latin1`, because `åºå·.encode('latin1').decode('utf-8')` is the result i exceped, and
`conn.setdecoding(pyodbc.SQL_WMETADATA, encoding='latin1')` is absolutely wrong. I have checked other related issues, don't work for me.
I can't understand, and what should i do? Appreciated!

**Comment by mkleehammer** [comment]
What database are you connecting to?  If Teradata, set the SQL_WMETADATA encoding to "utf-32le".  I'm using SQLDescribeColW and some drivers do weird things when the 'W' version is called.

I might need to add another parameter to the setdecoding for metadata to specify whether the ANSII or wide version should be called.

**Comment by zhangjiajie023** [comment]
@mkleehammer it's our own database, and all the data is encoding by 'utf-8'. The odbc-driver-manager-log show that: `SQLDescribeCol` and `SQLDescribeColW` are all been called, and the column names got by `SQLDescribeColW` just have one byte, exists bug, right?
```
[ODBC][4069][1488249639.096031][SQLDescribeCol.c][247]
                Entry:
                        Statement = 0x19fd380
                        Column Number = 1
                        Column Name = 0x7fffb610b470
                        Buffer Length = 200
                        Name Length = 0x7fffb610b458
                        Data Type = 0x7fffb610b45a
                        Column Size = 0x7fffb610b460
                        Decimal Digits = 0x7fffb610b45c
                        Nullable = 0x7fffb610b45e
[ODBC][4069][1488249639.096170][SQLDescribeCol.c][497]
                Exit:[SQL_SUCCESS]
                        Column Name = [keyword]
                        Data Type = 0x7fffb610b45a -> 12
                        Column Size = 0x7fffb610b460 -> 334
                        Decimal Digits = 0x7fffb610b45c -> 0
                        Nullable = 0x7fffb610b45e -> 1
[ODBC][4069][1488249639.096203][SQLDescribeCol.c][247]
                Entry:
                        Statement = 0x19fd380
                        Column Number = 2
                        Column Name = 0x7fffb610b470
                        Buffer Length = 200
                        Name Length = 0x7fffb610b458
                        Data Type = 0x7fffb610b45a
                        Column Size = 0x7fffb610b460
                        Decimal Digits = 0x7fffb610b45c
                        Nullable = 0x7fffb610b45e
[ODBC][4069][1488249639.096330][SQLDescribeCol.c][497]
                Exit:[SQL_SUCCESS]
                        Column Name = [åº<8f>å<8f>·]
                        Data Type = 0x7fffb610b45a -> 4
                        Column Size = 0x7fffb610b460 -> 4
                        Decimal Digits = 0x7fffb610b45c -> 0
                        Nullable = 0x7fffb610b45e -> 1
....
[ODBC][4069][1488249639.096972][SQLDescribeColW.c][209]
                Entry:
                        Statement = 0x19fd380
                        Column Number = 1
                        Column Name = 0x7fffb610b310
                        Buffer Length = 300
                        Name Length = 0x7fffb610b300
                        Data Type = 0x7fffb610b302
                        Column Size = 0x7fffb610b308
                        Decimal Digits = 0x7fffb610b304
                        Nullable = 0x7fffb610b306
[ODBC][4069][1488249639.097111][SQLDescribeColW.c][460]
                Exit:[SQL_SUCCESS]
                        Column Name = [k]
                        Data Type = 0x7fffb610b302 -> 12
                        Column Size = 0x7fffb610b308 -> 334
                        Decimal Digits = 0x7fffb610b304 -> 0
                        Nullable = 0x7fffb610b306 -> 1
[ODBC][4069][1488249639.097142][SQLDescribeColW.c][209]
                Entry:
                        Statement = 0x19fd380
                        Column Number = 2
                        Column Name = 0x7fffb610b310
                        Buffer Length = 300
                        Name Length = 0x7fffb610b300
                        Data Type = 0x7fffb610b302
                        Column Size = 0x7fffb610b308
                        Decimal Digits = 0x7fffb610b304
                        Nullable = 0x7fffb610b306
[ODBC][4069][1488249639.097268][SQLDescribeColW.c][460]
                Exit:[SQL_SUCCESS]
                        Column Name = [å]
                        Data Type = 0x7fffb610b302 -> 4
                        Column Size = 0x7fffb610b308 -> 4
                        Decimal Digits = 0x7fffb610b304 -> 0
                        Nullable = 0x7fffb610b306 -> 1
[ODBC][4069][1488249639.097305][SQLFetch.c][162]
```

**Comment by mkleehammer** [comment]
I'm still not quite clear on the issue.  Even if the data is UTF-8 encoded, are you sure the driver's SQLDescribeColW's implementation is using UTF-8?  For example, PostgreSQL and MySQL both can have UTF-8 data but still use UTF-16LE for the column names (IIRC).

Can you run the same test with the branch fix205?  I've added some print statements around the code calling SQLDescribeColW to help troubleshoot.

**Comment by zhangjiajie023** [comment]
@mkleehammer hi, this is the ouput from branch fix205:
```
Col 1: type=SQL_VARCHAR (12) colsize=334
enc: 5 (utf-16le) ctype=-8 cbName=14
6b 00 65 00 79 00 77 00 6f 00 72 00 64 00 
Col 2: type=SQL_INTEGER (4) colsize=4
enc: 5 (utf-16le) ctype=-8 cbName=12
e5 00 ba 00 8f 00 e5 00 8f 00 b7 00
```

**Comment by gordthompson** [comment]
@zhangjiajie023 re: "it's our own database" - Michael was really asking what _type_ of database you were connecting to, e.g., Teradata, PostgreSQL, MySQL, etc..

**Comment by mkleehammer** [comment]
If you are saying that the *correct* utf-8 is `b'\xe5\xba\x8f\xe5\x8f\xb7'` then `e5 00 ba 00 8f 00 e5 00 8f 00 b7 00` is utf-16le.

Just to be clear, can you post the lines of code that are actually raising the exception?  The metadata encoding is only used for decoding column names for Cursor.description.  Is that what is failing?  If Cursor.fetchall() is failing, it might have been fixed in 4.0.14.

Also, is your sys.encoding set to latin1 which could cause the same error when printing or merging with an 'str'.  (I know it probably isn't, but I'm not sure what's going on yet.)

**Comment by zhangjiajie023** [comment]
@gordthompson yes, it's the database developed by ourself.
@mkleehammer  The error just exists in Cursor.description, and Cursor.fetchall() works well. Maybe is our odbc's bug. 
tks for help

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
