### ISSUE TITLE
Money type in SQL Server 2000 loses sign when marshaled to Python Decimal

### ISSUE THREAD

**Issue by jlavelle** [mkleehammer/pyodbc#207]
When querying a table that contains both positive and negative values in a money type column in SQL Server 2000, the returned Decimal value has no sign.

Any workarounds are appreciated; currently I'm just querying negative values separately,  applying the sign, and merging the results.

**Comment by gordthompson** [comment]
Have you tried an explicit conversion like `SELECT ... CONVERT(DECIMAL(20,4), moneyvalue) AS decimalvalue` to see if that helps?

**Comment by jlavelle** [comment]
Thanks, the explicit conversion works perfectly.  I should have thought of that :)

**Comment by mkleehammer** [comment]
I am not able to reproduce this.  Can you look at the tests3/sqlservertests.py file I just pushed to master?  It tests -1234.56  -1  0  1  1234.56  123456789.21 in a money field and all of them seem to work.

Can you create a tiny SQL script to reproduce this - a create table with a single column and the value that fails?

**Comment by gordthompson** [comment]
@jlavelle Is it possible for you to test whether this issue is specific to SQL Server 2000? I cannot reproduce it either, but I'm hitting a SQL Server 2014 database and I don't have a SQL Server 2000 instance to test against.

**Comment by jlavelle** [comment]
The configuration of my ODBC driver was causing this issue.  It had an option "Use regional settings when outputting currency, numbers, dates, and times" checked, when I turned that setting off everything started working correctly.

Sorry for the false alarm and thanks a lot for looking into this.
