### ISSUE TITLE
Controlling CursorLocation

### ISSUE THREAD

**Issue by hosford42** [mkleehammer/pyodbc#216]
I am trying to move from COM to pyodbc in order to support both Windows and Linux. The codebase I am working with has code that utilizes the CursorLocation property of the COM connection object to set the cursor location to adUseClient. I didn't see anything in the documentation about this. Is there a way to do this with pyodbc? If not, can it be added?

**Comment by mkleehammer** [comment]
If I understand your question, ODBC cursors are always client-side cursors.  If you want to use a server side cursor, you would need to use the SQL for your database to declare and manage them.  These are two very different things that I'm not sure COM should have mixed.
