### ISSUE TITLE
Sequentially inserting multiple rows in accessdb

### ISSUE THREAD

**Issue by dhanababum** [mkleehammer/pyodbc#218]
Hi, I'm using pyodbc to insert multiple rows with sequential order, But pyodbc inserting rows in random order. Is this normal ?

For understanding I'm giving example,

```
params = [ ('A', 1), ('B', 2), ('C', 3), ('D', 4) ]
executemany("insert into t(name, id) values (?, ?)", params)
```

But in table, I can see order like this,

![image](https://cloud.githubusercontent.com/assets/5729855/24096791/19b8cc64-0d89-11e7-81f1-b68737befa39.png)

**Comment by keitherskine** [comment]
Order is not guaranteed without an ORDER BY clause on your SELECT.  Every time you call SELECT without an ORDER BY clause, the records could be returned in a different order.  This is normal SQL.  By the way, in SQL, there's no such thing as inserting in order, records are just inserted.

To get those records in a specific order, use the following SQL:
```sql
SELECT * FROM t ORDER BY name
```

**Comment by mkleehammer** [comment]
Thanks @keitherskine - well described.

**Comment by skillian** [comment]
Hi, @dhanababum, I know that this ticket is closed, but I noticed that in addition to the rows being in the wrong order, in the table you posted, the pairing of the values are also out of order (It looks like you inserted name: "B", id: 2 but in the result table you have name: "B", id: 3.  Is that really how it was inserted or was that a typo when you created the issue?

**Comment by dhanababum** [comment]
@skillian it's typo
