### ISSUE TITLE
I met a database named Chinese name

### ISSUE THREAD

**Issue by driftluo** [mkleehammer/pyodbc#225]
When I use the function:
```
import pyodbc
cnxn = pyodbc.connect(driver='{SQL Server}', server='localhost', database='测试PV', uid='test', pwd='test')
```
it will return with text: "'ascii' codec can't encode character '\xd07' in position..."

I can't rename the database name.
It doesn't support unicode. Is there any solution?

**Comment by gordthompson** [comment]
I am unable to reproduce your issue on Windows 7 using

- Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32,
- pyodbc 4.0.16, and
- the old "SQL Server" ODBC driver.

You may need to supply a few more details about your environment (OS, Python version, pyodbc version).

**Comment by mkleehammer** [comment]
What versions of Python and pyodbc are you using?

From the error I'm guessing it is Python 2, so the values are byte strings.

If you want to pass the bytes as-is in Python 2, try:

    pyodbc.connect(<your settings>, encoding='raw')

I think that will do what you want.

**Comment by gordthompson** [comment]
The issue appears to be related to using keyword arguments for the `.connect` method with Python 2.7. Under pyodbc 4.0.16, this code fails ...

```python
# coding=utf-8
import pyodbc
db = u'测试PV'
cnxn = pyodbc.connect(
    driver=r"SQL Server",
    server=r".\SQLEXPRESS",
    database=db
    )
print("Connected.")
cnxn.close()
```

... with ...

```none
Traceback (most recent call last):
  File "C:/Users/gord/PycharmProjects/pyodbc_issue_225/main.py", line 11, in <module>
    database=db
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

... but this works:

```python
# coding=utf-8
import pyodbc
db = u'测试PV'
conn_str = u"DRIVER=SQL Server;SERVER=.\\SQLEXPRESS;DATABASE=" + db + u";"
cnxn = pyodbc.connect(conn_str)
print("Connected.")
cnxn.close()
```

**Comment by driftluo** [comment]
I'm very sorry to less marked the environment, it work in winxp and python2.7 environment.

Last night, I use the DSN to connect the db, and it can specifies the default database, don't care about the encoding of the database name.

```
```

But when I try to use, it fails
```
db = u'测试PV'
conn_str = u'DREVER=SQL Server;SERVER=localhost;DATABASE='+ db
cnxn = pyodbc.connect(conn_str)
```
with
```
Traceback (most recent call last):
  File "C:/Documents and Settings/Administrator/桌面/2.py", line 7, in <module>
    cnxn = pyodbc.connect(conn_str)
Error: ('IM002', '[IM002] [Microsoft][ODBC \xc7\xfd\xb6\xaf\xb3\xcc\xd0\xf2\xb9\xdc\xc0\xed\xc6\xf7] \xce\xb4\xb7\xa2\xcf\xd6\xca\xfd\xbe\xdd\xd4\xb4\xc3\xfb\xb3\xc6\xb2\xa2\xc7\xd2\xce\xb4\xd6\xb8\xb6\xa8\xc4\xac\xc8\xcf\xc7\xfd\xb6\xaf\xb3\xcc\xd0\xf2 (0) (SQLDriverConnect)')
```

**Comment by gordthompson** [comment]
From your error message,

> \xce\xb4\xb7\xa2\xcf\xd6\xca\xfd\xbe\xdd\xd4\xb4\xc3\xfb\xb3\xc6\xb2\xa2\xc7\xd2\xce\xb4\xd6\xb8\xb6\xa8\xc4\xac\xc8\xcf\xc7\xfd\xb6\xaf\xb3\xcc\xd0\xf2

in cp936 is

> 未发现数据源名称并且未指定默认驱动程序

which Google Translate tells me means

> The data source name was not found and the default driver was not specified

`DREVER=` is not a valid connection string keyword. The correct spelling is `DRIVER=`.

**Comment by driftluo** [comment]
Sorry, this is my serious mistake
