### ISSUE TITLE
Named SQL Parameters

### ISSUE THREAD

**Issue by dclong** [mkleehammer/pyodbc#227]
Does pyodbc support named parameters? If not, is there any plan on this?

**Comment by mkleehammer** [comment]
No it does not.  pyodbc does not modify the SQL at all - your ODBC driver or database is looking for the '?' markers.

**Comment by AlexHankins** [comment]
@mkleehammer  Would you be interested in a pull request against cursor.execute to support named parameters?  I've written a relatively short function that accomplishes this; it converts a query and a dictionary of parameters into a query that uses placeholders (question marks) and a list.

**Comment by tyz928** [comment]
@AlexHankins Could you plz share the conversion function here to support named parameter list. Thanks a lot.

**Comment by AlexHankins** [comment]
Actually, I found something better.  It's called sqlparams.  You can install it with pip.  It even works with lists (mainly for SQL's `IN` operator).  https://python-sql-parameters.readthedocs.io/en/latest/sqlparams.html

**Comment by pickfire** [comment]
Why doesn't the API mention that it does not support named parameters and lastrowid (these should be mandatory features from what I read based on the spec) when it said it implements DB API 2.0 and instead lets the users search through the pull request to know that it does not support these features?

>  It implements the DB API 2.0 specification but is packed with even more Pythonic convenience.

Maybe that statement needs to be rephrased to something like `It implements a small part of the DB API 2.0 specification based on opinion`?

**Comment by Cnoor0171** [comment]
[PEP 0249](https://www.python.org/dev/peps/pep-0249/) lists qmark style parameters as a valid choice in [this](https://www.python.org/dev/peps/pep-0249/#paramstyle) and mentions [lastrowid](https://www.python.org/dev/peps/pep-0249/#lastrowid) in the "Optional DB API Extensions" section.

I agree both of these feature would be nice to have, but their absence doesn't make pyodbc any less compliant with DB API 2.0 specs.

**Comment by pickfire** [comment]
qmark style wasn't listed in the "Optional DB API Extensions" section.

> Module implementors should prefer numeric, named or pyformat over the other formats because these offer more clarity and flexibility.

It did not mention that qmark style is the preferable choice, it is valid but not preferable.
