### ISSUE TITLE
String value generated by charcodes doesn't return

### ISSUE THREAD

**Issue by ahennar** [mkleehammer/pyodbc#229]
Hi
Let's say I have VARCHAR(14) column in table and I inserted some data like X'010000000203040000'
Then I execute select with where clause and this value as a search filter:
SELECT column FROM table WHERE column = X'010000000203040000'
and I see there is no resultset returned. I checked it in C++ and it returns result set with valid data.
Note: X'0001' and X'0100' returns resultset. Also this select works fine, too:
SELECT column FROM table WHERE column in (X'0001' , X'0100',  x'010000000203040000')

I am getting result set with fetchall() function in all cases.
If it would help I can attach the C++ code to reproduce.

Using python 3.6.1 x64 and pyodbc 4.0.16 on win10 x64

**Comment by gordthompson** [comment]
Which ODBC driver are you using?

**Comment by ahennar** [comment]
Our own

**Comment by gordthompson** [comment]
Do you have any better luck if you try something like this?

```python
bytes = b'\x01\x00\x00\x00\x02\x03\x04\x00\x00'
crxr.execute("SELECT column FROM table WHERE column = ?", bytes).fetchall()
```

**Comment by gordthompson** [comment]
As far as I know, for a query like

```sql
SELECT column FROM table WHERE column = X'010000000203040000'
```

by default pyodbc will send the query string verbatim via SQLExecDirectW, e.g.,

```none
pythonw.exe -c  1530-e50    ENTER SQLExecDirectW 
        HSTMT               0x0031A7D8
        WCHAR *             0x0260CEB8 [      52] "SELECT column FROM table WHERE column = X'010000000203040000'"
        SDWORD                    52
```

with the string encoded as UTF-16LE. How does that compare with what your C++ test code does?

**Comment by ahennar** [comment]
Hi, sorry for delay

That's how my C++ test works, I know the basics but it returns valid data.
```
SQLRETURN rc = SQLPrepare(hdv.hstmt, (SQLCHAR*)query, strlen(query));

    rc = SQLExecute(hdv.hstmt);

    rc = SQLFetch(hdv.hstmt);

    wchar_t data[40] = {0};
    short slen = 4096;
    SQLLEN len = 0;

    rc = SQLGetData(hdv.hstmt, 1, SQL_C_WCHAR, (SQLPOINTER) data, slen, &len);
```

My try with bytes didn't end well, I got driver error.

**Comment by ahennar** [comment]
It returns no rows.

**Comment by mkleehammer** [comment]
gordthompson is correct - pyodbc is not modifying the query.  Can we get an ODBC trace for it?

Just out of curiousity, with that kind of data is there a reason you are not using a varbinary column?

**Comment by ahennar** [comment]
Tested again with different servers and it seems it belongs to our problem. 
Well, actually it was simple words but as a part of test regression we do this kind of verification, too.

Really glad to use your library, guys. Good job.
