### ISSUE TITLE
Is use of executemany() driver depended?

### ISSUE THREAD

**Issue by smile-on** [mkleehammer/pyodbc#231]
I have run very simple test using **executemany()** in pyodbc on top of netezza odbc driver.

    tx = self.conn.cursor()
    insertSql = '''insert into test(vi) values (?)'''
    data = [ (1), (2) ]
    tx.executemany(insertSql,data)

which fails on executemany line with "TypeError: ('Params must be in a list, tuple, or Row', 'HY000')"
Is use of executemany() driver depended? 

Same error with

    data = [ 1, 2 ]

What do I do wrong in the test?

**Comment by gordthompson** [comment]
```python
data = [ (1), (2) ]
```

is not a list of tuples, it is a list of individual numeric values. That statement is actually the same as

```python
data = [ 1, 2 ]
```

If you want a list of tuples you need to use

```python
data = [ (1,), (2,) ]
```

**Comment by smile-on** [comment]
Thank you, @gordthompson . Now I see _'Params must be in a list'_ means each **individual parameter** must be a list or tuple.
The speed of **executemany()**  execution, with autocommit off,  suggests that in my case on top of Netezza ODBC the call is simply converting data into series of individual inserts.
The hope was that  [executemany()](https://www.python.org/dev/peps/pep-0249/#executemany) implements batch insert interface for ODBC driver. Is this up to the driver or pyodbc to implement / enable  batch insert ? Is there something I miss to enable batch insert?

**Comment by keitherskine** [comment]
Pyodbc doesn't do batch inserts with executemany().  This has been requested in #62 and #120 .

**Comment by smile-on** [comment]
Thank you @keitherskine for the clarity.
