### ISSUE TITLE
Cannot connect using a password ending with a semicolon

### ISSUE THREAD

**Issue by geographika** [mkleehammer/pyodbc#232]
The following connection string, where the password ends with a semicolon e.g.:

`cs = "DRIVER={SQL Server};server=SQLEXPRESS;database=dbname;uid=user;pwd=pwd;"`

In .NET the web.config handles this by allowing the password to be wrapped in quotes e.g.

`cs = "DRIVER={SQL Server};server=SQLEXPRESS;database=dbname;uid=user;pwd='pwd;';"`

This doesn't seem supported by pyodbc however and returns:

`[Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'user'. (18456) (SQLDriverConnect); [01S00] [Microsoft][ODBC Driver Manager] Invalid connection string attribute (0); [28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user`

**Comment by gordthompson** [comment]
In an ODBC connection string we don't use single quotes to protect special characters, we use curly brackets. For example, this fails

```python
import pyodbc
cs = (
    "DRIVER={SQL Server};"
    "SERVER=(local)\SQLEXPRESS;"
    "UID=user;"
    "PWD='pwd;'"
    )
print(cs)
cnxn = pyodbc.connect(cs)
print("Connected.")
cnxn.close()
```

with the console output

```none
DRIVER={SQL Server};SERVER=(local)\SQLEXPRESS;UID=user;PWD='pwd;'
Traceback (most recent call last):
  File "C:/Users/gord/Desktop/pyodbc_issue_232.py", line 21, in <module>
    cnxn = pyodbc.connect(cs)
pyodbc.Error: ('28000', "[28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user 'user'. (18456) (SQLDriverConnect)")
```

However, this works:

```python
import pyodbc
cs = (
    "DRIVER={SQL Server};"
    "SERVER=(local)\SQLEXPRESS;"
    "UID=user;"
    "PWD={pwd;}"
    )
print(cs)
cnxn = pyodbc.connect(cs)
print("Connected.")
cnxn.close()
```
producing

```none
DRIVER={SQL Server};SERVER=(local)\SQLEXPRESS;UID=user;PWD={pwd;}
Connected.
```

**Comment by geographika** [comment]
@gordthompson - many thanks for that. I was searching for SQL Server which was recommending quotes, rather than ODBC which uses curly braces. With those the connection was fine. 

I found a couple of links referring to escaping of ODBC strings: 

- https://msdn.microsoft.com/en-us/library/system.data.odbc.odbcconnection.connectionstring(v=vs.110).aspx
- http://www-01.ibm.com/support/docview.wss?uid=swg21649868

**Comment by qing917** [comment]
@gordthompson , many many thanks.  Your answer ended my hours of troubleshooting for my first pyodbc connect.  Everything worked, except pyodbc connection authentication, I should have suspected about the semicolon earlier in the process.

**Comment by chusri** [comment]
@geographika Thanks, you resolved my weeks.

**Comment by chusri** [comment]
@gordthompson Thanks, you saved my day.

**Comment by nocibambi** [comment]
My password contains **both** semicolons and closing curly brackets. Is there a way to escape the brackets too?

**Comment by dpsahoo** [comment]
Curly brackets FTW!
Some examples here for quick ref:
Input:     **;fln3?2ksd**            
Output:   **{;fln3?2ksd}**           
i.e. {Input}


Input:  **;fln?3}2ksd**            
Output:  **{;fln?3}}2ksd}**           
i.e. {Input.replace('}','}}')}

**Comment by dimon222** [comment]
Is this escaping specifically driver based? Do I need to escape different way for each SQL driver?
I'm having trouble with MariaDB. It doesn't seem to work for curly bracket escaping (double curly bracket doesn't make any difference - still crashing on parsing incoming connect string). Wrapping brackets only work for semicolon.

**Comment by v-chojas** [comment]
Yes, because the driver parses the connection string.

The standard ODBC escaping mechanism may not have been implemented correctly --- talk to your driver vendor for further assistance.  pyODBC does not parse the connection string.
