### ISSUE TITLE
pyodbc4 drops millisecond precision from datetime values on MSSQL

### ISSUE THREAD

**Issue by michiya** [mkleehammer/pyodbc#235]
### Environment

- Python: 2.7, 3.5, 3.6
- pyodbc: 4.0.16
- OS:  Windows Server 2012 R2, Ubuntu 16.04, macOS 10.12
- DB: MSSQL 2014/2016 (Windows), MSSQL vNext (Ubuntu)
- driver: ODBC Driver 13 for SQL Server (WIndows/Ubuntu), FreeTDS 1.00.37 (macOS)

### Issue

I have the following table on my MSSQL database,
```
CREATE TABLE pyodbc_datetime_test (pyodbc_version varchar(8) not null, inserted_at datetime2 not null)
```

and the following test script.
```py
from datetime import datetime
import pyodbc

print('pyodbc version: %s' % pyodbc.version)
connstr = "DRIVER={ODBC Driver 13 for SQL Server};SERVER=.\\;UID=sa;PWD=xxxxxxxx;DATABASE=testdb;MARS_Connection=yes"
conn = pyodbc.connect(connstr, autocommit=True)
cursor = conn.cursor()
now = datetime.now()
print(now)
cursor.execute("INSERT INTO pyodbc_datetime_test VALUES (?, ?)", [pyodbc.version, now])
cursor.execute("SELECT TOP 1 inserted_at FROM pyodbc_datetime_test ORDER BY inserted_at DESC")
inserted_at = cursor.fetchone()[0]
print(inserted_at)
conn.close()
assert inserted_at == now, "%s is not equal to %s" % (inserted_at, now)
```

The test script finishes successfully with the folloing output when I run it with pyodbc 3. 
```
pyodbc version: 3.1.1
2017-05-05 01:02:00.986414
2017-05-05 01:02:00.986414
```

But I receive the following error when I run the same script with pyodbc 4.
```
pyodbc version: 4.0.16
2017-05-05 01:04:34.251514
2017-05-05 01:04:34
Traceback (most recent call last):
  File "pyodbc_datetime_test.py", line 15, in <module>
    assert inserted_at == now, "%s is not equal to %s" % (inserted_at, now)
AssertionError: 2017-05-05 01:04:34 is not equal to 2017-05-05 01:04:34.251514
```

From sqlcmd I can see the following records in the table after executing the test script.
```
1> select * from pyodbc_datetime_test
2> go
pyodbc_version inserted_at                           
-------------- --------------------------------------
3.1.1                     2017-05-05 01:02:00.9864140
4.0.16                    2017-05-05 01:04:34.0000000
```

**Comment by gordthompson** [comment]
I have reproduced the issue with pyodbc 4.0.16 under Python 2.7.13 on Windows. The Python statement ...

```python
cursor.execute("INSERT INTO #pyodbc_datetime_test VALUES (?, ?)", [pyodbc.version, now])
```

results in the following call (without fractional seconds) being logged in SQL Profiler:

```
exec sp_prepexec @p1 output,N'@P1 varchar(6),@P2 datetime2',N'INSERT INTO #pyodbc_datetime_test VALUES (@P1, @P2)','4.0.16','2017-05-06 04:10:25'
```

A workaround would be to cast the `now` variable from datetime to string ...

```python
cursor.execute("INSERT INTO #pyodbc_datetime_test VALUES (?, ?)", [pyodbc.version, str(now)])
```

... which results in a call like this (note that `@P2` is now varchar instead of datetime2) ...

```
exec sp_prepexec @p1 output,N'@P1 varchar(6),@P2 varchar(26)',N'INSERT INTO #pyodbc_datetime_test VALUES (@P1, @P2)','4.0.16','2017-05-06 04:15:28.499000'
```

... but that cast really should not be necessary.

**Comment by gordthompson** [comment]
Further investigation suggests that the pyodbc4 behaviour might be a workaround for (or simply a consequence of) a deficiency in Microsoft's ODBC Driver for SQL Server ("mssql-odbc").

My guess is that pyodbc3 bound datetime parameters as string values, similar to the `str()` workaround in my previous comment. pyodbc4 appears to be trying to "do the right thing" by binding the datetime parameter as an actual ODBC timestamp value ...

```
main            1c58-a14    EXIT  SQLBindParameter  with return code 0 (SQL_SUCCESS)
        HSTMT               0x005EAFE8
        UWORD                        2 
        SWORD                        1 <SQL_PARAM_INPUT>
        SWORD                       11 <SQL_C_TIMESTAMP>
        SWORD                       11 <SQL_TIMESTAMP>
        SQLULEN                   19
        SWORD                        0 
        PTR                0x01368F80
        SQLLEN                     0
        SQLLEN *            0x01368F6C (16)
```

... but mssql-odbc seems to have problems handling fractional seconds when the parameter values are passed that way. 

To illustrate, if I do this in C# using System.Data.Odbc

```c#
now = new DateTime(2017, 05, 06, 13, 14, 15, 0);  // i.e., 13:14:15.0
cmd.Parameters.Add("?", OdbcType.DateTime).Value = now;
cmd.ExecuteNonQuery();
```

it works fine. However, if I do

```c#
now = new DateTime(2017, 05, 06, 13, 14, 15, 678);  // i.e., 13:14:15.678
cmd.Parameters.Add("?", OdbcType.DateTime).Value = now;
cmd.ExecuteNonQuery();
```

I get

> ERROR [22008] [Microsoft][ODBC Driver 11 for SQL Server]Datetime field overflow. Fractional second precision exceeds the scale specified in the parameter binding.

The ODBC parameter binding is not exactly identical to that of pyodbc4, with .NET using `SQL_C_TYPE_TIMESTAMP` and `SQL_TYPE_TIMESTAMP` instead of `SQL_C_TIMESTAMP` and `SQL_TIMESTAMP`

```
OdbcConsoleApp. 12b4-108    EXIT  SQLBindParameter  with return code 0 (SQL_SUCCESS)
        HSTMT               0x04B65590
        UWORD                        2 
        SWORD                        1 <SQL_PARAM_INPUT>
        SWORD                       93 <SQL_C_TYPE_TIMESTAMP>
        SWORD                       93 <SQL_TYPE_TIMESTAMP>
        SQLULEN                   23
        SWORD                        0 
        PTR                0x040B2234
        SQLLEN                    16
        SQLLEN *            0x040B2230 (0)
```

but I have a strong suspicion that the results would be the same if pyodbc4 tried to pass fractional seconds to mssql-odbc as actual ODBC timestamp values.

**Comment by gordthompson** [comment]
I originally suspected that pyodbc3 was binding datetime parameters as string values and pyodbc4 was binding them as timestamp values. However, that appears not to be the case; they are both using timestamp values. 

pyodbc3 binds such parameters as

```
main            fa4-1d60    EXIT  SQLBindParameter  with return code 0 (SQL_SUCCESS)
        HSTMT               0x0054B310
        UWORD                        2 
        SWORD                        1 <SQL_PARAM_INPUT>
        SWORD                       11 <SQL_C_TIMESTAMP>
        SWORD                       11 <SQL_TIMESTAMP>
        SQLULEN                   27
        SWORD                        7 
        PTR                0x0143CB70
        SQLLEN                     0
        SQLLEN *            0x0143CB64 (16)
```

while pyodbc4 binds them as

```
main            1d30-1254   EXIT  SQLBindParameter  with return code 0 (SQL_SUCCESS)
        HSTMT               0x004BAFE8
        UWORD                        2 
        SWORD                        1 <SQL_PARAM_INPUT>
        SWORD                       11 <SQL_C_TIMESTAMP>
        SWORD                       11 <SQL_TIMESTAMP>
        SQLULEN                   19
        SWORD                        0 
        PTR                0x01388F80
        SQLLEN                     0
        SQLLEN *            0x01388F6C (16)
```

I'm not very fluent in C++, but `GetDateTimeInfo` at params.cpp:216 seems a likely place to start looking for a reason why pyodbc4 seems to only be passing 19 bytes while pyodbc3 appears to be passing 27 bytes.

**Comment by keitherskine** [comment]
For what it's worth, I can confirm this is happening in pyodbc 4.0.16, but not 3.0.10, with MS SQL Server 2008 R2 and Python 3.4.4.  The fraction of a second is being lost when the Python `datetime.datetime` value is passed as a parameter, for both `datetime` and `datetime2` column types.  The following code:
```python
import datetime as dt
import decimal

import pyodbc

conn_str = 'DSN=xxx;UID=xxx;PWD=xxx;Database=xxx'
conn = pyodbc.connect(conn_str, autocommit=True)
crsr = conn.cursor()
sql = """
    IF OBJECT_ID('dbo.pyodbc_datetimefraction') IS NULL
    CREATE TABLE dbo.pyodbc_datetimefraction(
        cDateTime datetime NULL,
        cDateTime2 datetime2 NULL
    )
"""
crsr.execute(sql)

crsr.execute("TRUNCATE TABLE dbo.pyodbc_datetimefraction")

sql = """
    INSERT INTO dbo.pyodbc_datetimefraction
    (cDateTime, cDateTime2)
    VALUES
    ('1970-07-04 23:43:56.123', '1970-07-04 22:45:58.654321')
"""
crsr.execute(sql)

sql = """
    INSERT INTO dbo.pyodbc_datetimefraction
    (cDateTime, cDateTime2)
    VALUES
    (?,?)
"""
crsr.execute(sql, (dt.datetime(1970, 7, 4, 23, 43, 56, 123000),
                   dt.datetime(1970, 7, 4, 22, 45, 58, 654321)))

rows = crsr.execute("select * from dbo.pyodbc_datetimefraction").fetchall()
for row in rows:
    print(row)

conn.close()
```
returns the following with 4.0.16 (but not with 3.0.10):
```
(datetime.datetime(1970, 7, 4, 23, 43, 56, 123000), datetime.datetime(1970, 7, 4, 22, 45, 58, 654321))
(datetime.datetime(1970, 7, 4, 23, 43, 56), datetime.datetime(1970, 7, 4, 22, 45, 58))
```

**Comment by mkleehammer** [comment]
Thanks for reporting this.  I've been sick for a few days and haven't been keeping up.

Even the SQL Server unit tests showed this bug - I try to run them all before releasing so I don't know how I missed it (though it takes a lot of VMs to run them all).

**Comment by keitherskine** [comment]
Hi @mkleehammer , if this issue results in a loss of data, does the fix for it not warrant a new release?

**Comment by mkleehammer** [comment]
You are correct - I need to make a release.  The issue is that some drivers fail if you write more than they can store, so I have to use getInfo on the first connection to determine the size of a datetime.  That call was failing so the default was being used.

I'll make a release later today.

**Comment by keitherskine** [comment]
Great!  Thanks @mkleehammer .

**Comment by pwaivers** [comment]
Hi @mkleehammer, have you released the fix to this issue?  It has actually come up in my code just today.  When using a datetime as one of the parameters, it truncated off the milliseconds and the query predicate did not work correctly.  Thanks.

**Comment by mkleehammer** [comment]
Doing so right now.

**Comment by mkleehammer** [comment]
Windows versions of 4.0.17 are uploaded.  Having trouble linking with the latest clang on mac.

**Comment by kotarf** [comment]
I reproduced the issue in both 2.7.12 and 3.5.2 and can confirm the fix is very effective. Thank you very much for this.

**Comment by joaoe** [comment]
Hi. I just noticed this bug running pyodbc in python 2. Is the fix python 3 specific ? 
Thank you.

**Comment by zzzeek** [comment]
hi there -

my understanding is that this still drops an extra digit of precision from datetime2 because Python's datetime type only stores microsecond precision, whereas datetime2 seems to store a 7-digit precision.  is this accurate and if so what is the fix for users who want that extra precision?  CAST to string ?

**Comment by gordthompson** [comment]
@zzzeek - Hi Mike

Yes, the default behaviour of returning a Python `datetime` will truncate the seventh decimal point of a `datetime(7)` value.

CAST to string would work, but if someone wanted to get the extra precision without changing their query then they could define an [output converter function](https://github.com/mkleehammer/pyodbc/wiki/Using-an-Output-Converter-function) like this ...

```python
def decode_datetime2(raw_bytes):
    return(struct.unpack("<6HI", raw_bytes))
```
... which would return the individual date/time components with the fractional seconds expressed as nanoseconds:

```python
cnxn.add_output_converter(pyodbc.SQL_TYPE_TIMESTAMP, decode_datetime2)
foo = crsr.execute("SELECT CAST('9999-12-31 23:59:59.9999999' AS datetime2(7)) AS foo").fetchval()
print(foo)  # (9999, 12, 31, 23, 59, 59, 999999900)
```

**Comment by zzzeek** [comment]
hi @gordthompson -

thanks for the quick reply.  just verifying there's no option on the datetime side with this, tuple is another good idea, thanks!
