### ISSUE TITLE
Oracle mapping.

### ISSUE THREAD

**Issue by zevgriner** [mkleehammer/pyodbc#236]
I'm a noob at this, so I apologize if this has been brought up. I read the Wiki and many of the posts, but I didn't see my issue.

I'm using 32-bit Python V3.4.3 with the latest pyodbc version on Windows 7 and Oracle 12.
My issue is more general.

Because Oracle's NUMERIC datatype doesn't have the granularity that other DBs have, like MySQL, I find that that my numbers usually come back incorrectly as floats and decimals, and I have to manually cast them to an int. Also, my column names come back in the same case they are found in the table, not how my SELECT statement asks for them.
I read the documentation about the SQL ODBC datatype mapping. I tried writing a handler, but I couldn't find documentation on how to unpack the struct for numeric values. I found the documentation for the Cursor.description attribute, so that helped me find any issues quickly.

My request is that there should be a way to explicitly define the mapping of a table's returned column names and data types.

Thank you.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
