### ISSUE TITLE
microsoft have release ODBC 13.1 for linux is pyodbc able to use it?

### ISSUE THREAD

**Issue by mbrambley** [mkleehammer/pyodbc#238]
it seems a much cleaner install for linux and solves some bugs
i tried to get the latest version of pyodbc to use it but no joy

any plans? ideas?

Thanks

**Comment by gordthompson** [comment]
The latest version of pyodbc (currently 4.0.16) definitely works with the latest version of Microsoft's Linux port of their ODBC Driver for SQL Server (currently 13.1.7.0). Note that the driver is apparently only available for 64-bit versions of Linux.

For instructions on installing the ODBC driver, see

https://docs.microsoft.com/en-us/sql/connect/odbc/linux/installing-the-microsoft-odbc-driver-for-sql-server-on-linux

**Comment by mbrambley** [comment]
(env) [pyramid@svelte ~]$ pip install --force-reinstall --upgrade pyodbc
Collecting pyodbc
  Using cached pyodbc-4.0.16.tar.gz
Installing collected packages: pyodbc
  Found existing installation: pyodbc 4.0.16
    Uninstalling pyodbc-4.0.16:
      Successfully uninstalled pyodbc-4.0.16
  Running setup.py install for pyodbc ... error
    Complete output from command /home/pyramid/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ui76sutd/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x7ylo63c-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pyramid/env/include/site/python3.5/pyodbc:
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    gcc -pthread -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPYODBC_VERSION=4.0.16 -DSQL_WCHART_CONVERT=1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include -I/home/pyramid/env/include -I/usr/include/python3.5m -c src/pyodbcmodule.cpp -o build/temp.linux-x86_64-3.5/src/pyodbcmodule.o -Wno-write-strings
    In file included from src/pyodbcmodule.cpp:11:
    src/pyodbc.h:56:17: error: sql.h: No such file or directory
    src/pyodbc.h:57:20: error: sqlext.h: No such file or directory
    In file included from src/pyodbcmodule.cpp:11:
    src/pyodbc.h:73: error: ‘IsSet’ declared as an ‘inline’ variable
    src/pyodbc.h:73: error: ‘DWORD’ was not declared in this scope
    src/pyodbc.h:73: error: ‘DWORD’ was not declared in this scope

**Comment by mbrambley** [comment]
its fine!!!

i needed
yum install unixODBC-devel

isnt pip meant to determine that?

**Comment by gordthompson** [comment]
> i needed
> yum install unixODBC-devel
> 
> isnt pip meant to determine that?

No. When `pip` is installing a package it can resolve dependencies that are *other packages distributed by pip*, but it is not designed to resolve dependencies outside of the PyPI universe (such as those installed by `yum` or `apt`).

**Comment by gordthompson** [comment]
> latest version [of SQL Server ODBC for Linux] is 13.1.4 not 7

No, it's currently 13.1.7. You installed 13.1.4 because you told `yum` to do it:

```none
yum install msodbcsql-13.1.4.0-1 mssql-tools-14.0.3.0-1
```

That's probably because the installation instructions at

[Installing the Microsoft ODBC Driver for SQL Server on Linux](https://docs.microsoft.com/en-us/sql/connect/odbc/linux/installing-the-microsoft-odbc-driver-for-sql-server-on-linux)

have version 13.1.4 hard-coded into the examples and that document has not been updated since the newer versions were released.

@meet-bhagdev - You might want to remove the version information from the installation steps so users who copy-and-paste get the latest version.

**Comment by meet-bhagdev** [comment]
@gordthompson definitely! iil get this done today 👍

**Comment by gordthompson** [comment]
@meet-bhagdev 

Still no change at

https://docs.microsoft.com/en-us/sql/connect/odbc/linux/installing-the-microsoft-odbc-driver-for-sql-server-on-linux

Please don't forget about this.

**Comment by meet-bhagdev** [comment]
@gordthompson I have the changes in staging. We actually have another new package with bug fixes. Waiting for the package to go on our repo. Iil update it once the new packages go live
