### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by dhanababum** [mkleehammer/pyodbc#239]
Hi,
 I work with 5-10GB data, will apply computations and then insert in MS Access using pyodbc.

Observed some performance variations following code,

```
cur.execute("Insert")
con.commit()
```
Inserting row by row using above code and it is very slow. Then I came up with

```
cur.executemany("Bulk insert")
con.commit()
```
But it is little fast compared with row by row insertion, But I need extra performance :). Could you give me any suggestions for me

**Comment by gordthompson** [comment]
See #120 for a discussion of `executemany` performance. TL;DR: It is often not much faster than performing individual inserts in a loop. Note that this is true not only for pyodbc but for other Python ODBC layers as well.

A commonly-suggested workaround is to use a bulk copy utility such as the `bcp` utility for Microsoft SQL Server, but Microsoft Access does not have such a stand-alone utility. The MS Access equivalent is to use VBA code to import data from text files via VBA's `DoCmd.TransferText` method. 

If you really need to accomplish your task via ODBC from within Python, then one alternative that *might* offer a modest performance gain would be to 

- create a temporary table with no indexes, possibly in a [separate database file](https://github.com/gordthompson/msaccessdb),
- insert the data into the temporary table while autocommit=False, and then
- `INSERT INTO real_table (...) SELECT ... FROM temp_table`

**Comment by dhanababum** [comment]
Thanks for neat explanation, I go with `DoCmd.TransferText`
