### ISSUE TITLE
Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql and PySlice_Unpack

### ISSUE THREAD

**Issue by bankyha** [mkleehammer/pyodbc#240]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.16
- OS: Ubuntu 16.04
- DB:SQL Server
- driver: Microsoft ODBC Driver 13.1 for SQL Server

### Issue
I've got two issue when I try to use pyodbc in anaconda. 

1st issue: Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.7.0'

When I connect using command below, 
pyodbc.connect('DRIVER={ODBC Driver 13 for SQL Server};SERVER=myserver;DATABASE=mydb'),I've got [01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.7.0' error. 

I followed the instruction 'https://docs.microsoft.com/en-us/sql/connect/odbc/linux/installing-the-microsoft-odbc-driver-for-sql-server-on-linux'.

sudo su 
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
exit
sudo apt-get update

but when I try following command, 
'sudo ACCEPT_EULA=Y apt-get install msodbcsql=13.1.4.0-1 mssql-tools-14.0.3.0-1 unixodbc-dev', it generated error below. 
E: Unable to locate package mssql-tools-14.0.3.0-1
E: Couldn’t find any package by glob ‘mssql-tools-14.0.3.0-1
E: Couldn’t find any package by regex ‘mssql-tools-14.0.3.0-1

So, I've run 'sudo ACCEPT_EULA=Y apt-get install msodbcsql mssql-tools unixodbc-dev' instead and it didn't generate error and following version was installed..
unixodbc-dev : 2.3.1-4.1
msodbcsql 13.1.7.0-1
mssql-tools 14.0.5.0-1

And did rest of command. 
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashr

And I used anaconda to install pyodbc.

conda install -c anaconda pyodbc=4.0.16

Could you help me on this please since I spend quite long time to search and fix, but couldn't find proper solution. 

2nd issue: PySlice_Unpack
when I import pyodbc, it produce 'ImportError: /home/myuser/anaconda3/lib/python3.6/site-packages/pyodbc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PySlice_Unpack' error. 

This issue happened after I install 'conda install -c anaconda pyodbc=4.0.16'.
When it was pyodbc=3.x.x (I can't remember the exact version), it didn't have PySlice_Unpack Issue. 

Thanks in advance!!

**Comment by pasapepe** [comment]
Hello,

I faced the same issue yesterday.
I think there's a bug in pyodbc current version. Last 3. series version was 3.0.10.
I was working with two anaconda environments. The first one (where pyodbc connection works properly) was created 3 weeks ago (version 3.0.10). The second one (where pyodbc connection gives me the same error as you) was created on Monday 15th.

While this bug is solved (I think is related to a pyodbc version 4 bug) I rollback the version of pyodbc to 3.0.10 (conda install --name <myEnv> pyodbc==3.0.10)

This issue happens, at least, for MSSQL Server connection (MySQL works)

Regards

Alex

**Comment by bankyha** [comment]
Thanks Alex!!
Version 3.0.10 solved my second issue 'PySlice_Unpack' issue, so thanks for this!

But, I still have first issue regarding 'Can't open lib '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.7.0'' even though the file exists.. 
Regards,
Bryan

**Comment by pasapepe** [comment]
Hello,

when I saw for the fist time that problem, I copied libmsodbcsql-13.1.so.7.0 to /tmp and I created a new "driver definition" in /etc/odbcinst.ini. Something like:
[...]
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.1.0
UsageCount=1

[SQL_Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/tmp/libmsodbcsql-13.0.so.1.0
UsageCount=1
[...]

Doing that you will evaluate if you have any access right issue from your code (I dont know if you are invoking Python code from cron, remote procedure, command line directly...)

Please note Im using MSSQL Server driver version 13.0 (not version 13.1 as you)

Maybe you can try to install both versions of the driver (in fact if you copy .so file for the old version is enough)

Also can be helpful if you share your environment info.
Mine is this
name: XXX_Production
channels:
- defaults
dependencies:
- anaconda=custom=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.10=0
- decorator=4.0.11=py36_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- ipython=6.0.0=py36_1
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_2
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.2=np112py36_0
- mkl=2017.0.1=0
- nltk=3.2.2=py36_0
- numpy=1.12.1=py36_0
- openssl=1.0.2k=2
- pandas=0.20.1=np112py36_0
- path.py=10.3.1=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.2.0=py36_0
- pyodbc=3.0.10=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=3
- readline=6.2=2
- scikit-learn=0.18.1=np112py36_1
- scipy=0.19.0=np112py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlalchemy=1.1.9=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.2=py36_0
- unixodbc=2.3.4=0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
prefix: /opt/anaconda/envs/XXX_Production

If you change the last line (prefix) to your anaconda installation folder you can import and check it.
(tip_01: https://conda.io/docs/using/envs.html)
(tip_02: https://conda.io/docs/using/envs.html#share-an-environment)

Good luck!!!

Regards

Alex

**Comment by bankyha** [comment]
Thanks Alex, 
Really appreciate!!

I copied 'libmsodbcsql-13.1.so.7.0' file (and libmsodbcsql-13.0.so.1.0 later) to /tmp and changed odbcinst.ini file as below
[SQL_Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/tmp/libmsodbcsql-13.0.so.1.0
UsageCount=1

and run code below in jupyter notebook. 
cnqa = pyodbc.connect('DRIVER={SQL_Server};SERVER=myserver;DATABASE=mydb'')

and have same error '[01000] [unixODBC][Driver Manager]Can't open lib '/tmp/libmsodbcsql-13.0.so.1.0' : file not found (0) (SQLDriverConnect)'

I was trying to import your environment, but had error, so I'll try again later. :-)

And below is my root environment.
(And thanks for introducing environment. I didn't know what environment is.. now I understand a little bit.. :-) )

name: root
channels:
- anaconda
- r
- defaults
dependencies:
- conda=4.3.18=py36_0
- conda-env=2.6.0=0
- pyodbc=3.0.10=py36_1
- unixodbc=2.3.4=0
- _license=1.1=py36_1
- alabaster=0.7.9=py36_0
- anaconda=4.3.1=np111py36_0
- anaconda-client=1.6.0=py36_0
- anaconda-navigator=1.5.0=py36_0
- anaconda-project=0.4.1=py36_0
- astroid=1.4.9=py36_0
- astropy=1.3=np111py36_0
- babel=2.3.4=py36_0
- backports=1.0=py36_0
- beautifulsoup4=4.5.3=py36_0
- bitarray=0.8.1=py36_0
- blaze=0.10.1=py36_0
- bokeh=0.12.4=py36_0
- boto=2.45.0=py36_0
- bottleneck=1.2.0=np111py36_0
- bzip2=1.0.6=3
- cairo=1.14.8=0
- cffi=1.9.1=py36_0
- chardet=2.3.0=py36_0
- chest=0.2.3=py36_0
- click=6.7=py36_0
- cloudpickle=0.2.2=py36_0
- clyent=1.2.2=py36_0
- colorama=0.3.7=py36_0
- configobj=5.0.6=py36_0
- contextlib2=0.5.4=py36_0
- cryptography=1.7.1=py36_0
- curl=7.52.1=0
- cycler=0.10.0=py36_0
- cython=0.25.2=py36_0
- cytoolz=0.8.2=py36_0
- dask=0.13.0=py36_0
- datashape=0.5.4=py36_0
- dbus=1.10.10=0
- decorator=4.0.11=py36_0
- dill=0.2.5=py36_0
- docutils=0.13.1=py36_0
- entrypoints=0.2.2=py36_0
- et_xmlfile=1.0.1=py36_0
- expat=2.1.0=0
- fastcache=1.0.2=py36_1
- flask=0.12=py36_0
- flask-cors=3.0.2=py36_0
- fontconfig=2.12.1=2
- freetype=2.5.5=2
- get_terminal_size=1.0.0=py36_0
- gevent=1.2.1=py36_0
- glib=2.50.2=1
- gmp=6.1.0=0
- greenlet=0.4.11=py36_0
- gsl=2.2.1=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np111py36_2
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- heapdict=1.0.0=py36_1
- icu=54.1=0
- idna=2.2=py36_0
- imagesize=0.7.1=py36_0
- ipykernel=4.5.2=py36_0
- ipython=5.1.0=py36_0
- ipython_genutils=0.1.0=py36_0
- ipywidgets=5.2.2=py36_1
- isort=4.2.5=py36_0
- itsdangerous=0.24=py36_0
- jbig=2.1=0
- jdcal=1.3=py36_0
- jedi=0.9.0=py36_1
- jinja2=2.9.4=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=4.4.0=py36_0
- jupyter_console=5.0.0=py36_0
- jupyter_core=4.2.1=py36_0
- keras=2.0.2=py36_0
- lazy-object-proxy=1.2.2=py36_0
- libffi=3.2.1=1
- libgcc=4.8.5=2
- libgfortran=3.0.0=1
- libgpuarray=0.6.4=0
- libiconv=1.14=0
- libpng=1.6.27=0
- libprotobuf=3.2.0=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- llvmlite=0.15.0=py36_0
- locket=0.2.0=py36_1
- lxml=3.7.2=py36_0
- mako=1.0.6=py36_0
- markupsafe=0.23=py36_2
- matplotlib=2.0.0=np111py36_0
- mistune=0.7.3=py36_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py36_3
- mpmath=0.19=py36_1
- multipledispatch=0.4.9=py36_0
- nbconvert=4.2.0=py36_0
- nbformat=4.2.0=py36_0
- ncurses=5.9=10
- networkx=1.11=py36_0
- nltk=3.2.2=py36_0
- nose=1.3.7=py36_1
- notebook=4.3.1=py36_0
- numba=0.30.1=np111py36_0
- numexpr=2.6.1=np111py36_2
- numpy=1.11.3=py36_0
- numpydoc=0.6.0=py36_0
- odo=0.5.0=py36_1
- openpyxl=2.4.1=py36_0
- openssl=1.0.2k=1
- pandas=0.19.2=np111py36_1
- pandoc=1.15.0.6=0
- pango=1.40.3=1
- partd=0.3.7=py36_0
- path.py=10.0=py36_0
- pathlib2=2.2.0=py36_0
- patsy=0.4.1=py36_0
- pcre=8.39=1
- pep8=1.7.0=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.0.0=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- ply=3.9=py36_0
- prompt_toolkit=1.0.9=py36_0
- protobuf=3.2.0=py36_0
- psutil=5.0.1=py36_0
- ptyprocess=0.5.1=py36_0
- py=1.4.32=py36_0
- pyasn1=0.1.9=py36_0
- pycosat=0.6.1=py36_1
- pycparser=2.17=py36_0
- pycrypto=2.6.1=py36_4
- pycurl=7.43.0=py36_2
- pyflakes=1.5.0=py36_0
- pygments=2.1.3=py36_0
- pygpu=0.6.4=py36_0
- pylint=1.6.4=py36_1
- pyopenssl=16.2.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- pytables=3.3.0=np111py36_0
- pytest=3.0.5=py36_0
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=3
- qtawesome=0.4.3=py36_0
- qtconsole=4.2.1=py36_1
- qtpy=1.2.1=py36_0
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py36_0
- requests=2.12.4=py36_0
- rope=0.9.4=py36_1
- ruamel_yaml=0.11.14=py36_1
- scikit-image=0.12.3=np111py36_1
- scikit-learn=0.18.1=np111py36_1
- scipy=0.18.1=np111py36_1
- seaborn=0.7.1=py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- singledispatch=3.4.0.3=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- snowballstemmer=1.2.1=py36_0
- sockjs-tornado=1.0.3=py36_0
- sphinx=1.5.1=py36_0
- spyder=3.1.2=py36_0
- sqlalchemy=1.1.5=py36_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py36_1
- sympy=1.0=py36_0
- tensorflow=1.1.0=np111py36_0
- terminado=0.6=py36_0
- theano=0.9.0=py36_0
- tk=8.5.18=0
- toolz=0.8.2=py36_0
- tornado=4.4.2=py36_0
- traitlets=4.3.1=py36_0
- unicodecsv=0.14.1=py36_0
- wcwidth=0.1.7=py36_0
- werkzeug=0.11.15=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=1.2.6=py36_0
- wrapt=1.10.8=py36_0
- xlrd=1.0.0=py36_0
- xlsxwriter=0.9.6=py36_0
- xlwt=1.2.0=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- r-assertthat=0.1=r3.3.2_4
- r-backports=1.0.4=r3.3.2_0
- r-base=3.3.2=1
- r-base64enc=0.1_3=r3.3.2_0
- r-bh=1.62.0_1=r3.3.2_0
- r-bitops=1.0_6=r3.3.2_2
- r-boot=1.3_18=r3.3.2_0
- r-broom=0.4.1=r3.3.2_0
- r-car=2.1_4=r3.3.2_0
- r-caret=6.0_73=r3.3.2_0
- r-catools=1.17.1=r3.3.2_2
- r-class=7.3_14=r3.3.2_0
- r-cluster=2.0.5=r3.3.2_0
- r-codetools=0.2_15=r3.3.2_0
- r-colorspace=1.3_1=r3.3.2_0
- r-crayon=1.3.2=r3.3.2_0
- r-curl=2.3=r3.3.2_0
- r-data.table=1.10.0=r3.3.2_0
- r-dbi=0.5_1=r3.3.2_0
- r-dichromat=2.0_0=r3.3.2_2
- r-digest=0.6.10=r3.3.2_0
- r-dplyr=0.5.0=r3.3.2_0
- r-essentials=1.5.2=r3.3.2_0
- r-evaluate=0.10=r3.3.2_0
- r-forcats=0.1.1=r3.3.2_0
- r-foreach=1.4.3=r3.3.2_0
- r-foreign=0.8_67=r3.3.2_0
- r-formatr=1.4=r3.3.2_0
- r-ggplot2=2.2.0=r3.3.2_0
- r-gistr=0.3.6=r3.3.2_0
- r-glmnet=2.0_5=r3.3.2_0
- r-gtable=0.2.0=r3.3.2_0
- r-haven=1.0.0=r3.3.2_0
- r-hexbin=1.27.1=r3.3.2_0
- r-highr=0.6=r3.3.2_0
- r-hms=0.3=r3.3.2_0
- r-htmltools=0.3.5=r3.3.2_0
- r-htmlwidgets=0.8=r3.3.2_0
- r-httpuv=1.3.3=r3.3.2_0
- r-httr=1.2.1=r3.3.2_0
- r-irdisplay=0.4.4=r3.3.2_0
- r-irkernel=0.7.1=r3.3.2_0
- r-iterators=1.0.8=r3.3.2_0
- r-jsonlite=1.1=r3.3.2_0
- r-kernsmooth=2.23_15=r3.3.2_0
- r-knitr=1.15.1=r3.3.2_0
- r-labeling=0.3=r3.3.2_2
- r-lattice=0.20_34=r3.3.2_0
- r-lazyeval=0.2.0=r3.3.2_0
- r-lme4=1.1_12=r3.3.2_0
- r-lubridate=1.6.0=r3.3.2_0
- r-magrittr=1.5=r3.3.2_2
- r-maps=3.1.1=r3.3.2_0
- r-markdown=0.7.7=r3.3.2_2
- r-mass=7.3_45=r3.3.2_0
- r-matrix=1.2_7.1=r3.3.2_0
- r-matrixmodels=0.4_1=r3.3.2_0
- r-mgcv=1.8_16=r3.3.2_0
- r-mime=0.5=r3.3.2_0
- r-minqa=1.2.4=r3.3.2_2
- r-mnormt=1.5_5=r3.3.2_0
- r-modelmetrics=1.1.0=r3.3.2_0
- r-modelr=0.1.0=r3.3.2_0
- r-munsell=0.4.3=r3.3.2_0
- r-nlme=3.1_128=r3.3.2_0
- r-nloptr=1.0.4=r3.3.2_2
- r-nnet=7.3_12=r3.3.2_0
- r-openssl=0.9.5=r3.3.2_0
- r-pbdzmq=0.2_4=r3.3.2_0
- r-pbkrtest=0.4_6=r3.3.2_0
- r-plyr=1.8.4=r3.3.2_0
- r-pryr=0.1.2=r3.3.2_0
- r-psych=1.6.9=r3.3.2_0
- r-purrr=0.2.2=r3.3.2_0
- r-quantmod=0.4_7=r3.3.2_0
- r-quantreg=5.29=r3.3.2_0
- r-r6=2.2.0=r3.3.2_0
- r-randomforest=4.6_12=r3.3.2_0
- r-rbokeh=0.5.0=r3.3.2_0
- r-rcolorbrewer=1.1_2=r3.3.2_3
- r-rcpp=0.12.8=r3.3.2_0
- r-rcppeigen=0.3.2.9.0=r3.3.2_0
- r-readr=1.0.0=r3.3.2_0
- r-readxl=0.1.1=r3.3.2_0
- r-recommended=3.3.2=r3.3.2_0
- r-repr=0.10=r3.3.2_0
- r-reshape2=1.4.2=r3.3.2_0
- r-rmarkdown=1.3=r3.3.2_0
- r-rpart=4.1_10=r3.3.2_0
- r-rprojroot=1.1=r3.3.2_0
- r-rvest=0.3.2=r3.3.2_0
- r-scales=0.4.1=r3.3.2_0
- r-selectr=0.3_0=r3.3.2_0
- r-shiny=0.14.2=r3.3.2_0
- r-sourcetools=0.1.5=r3.3.2_0
- r-sparsem=1.74=r3.3.2_0
- r-spatial=7.3_11=r3.3.2_0
- r-stringi=1.1.2=r3.3.2_0
- r-stringr=1.1.0=r3.3.2_0
- r-survival=2.40_1=r3.3.2_0
- r-tibble=1.2=r3.3.2_0
- r-tidyr=0.6.0=r3.3.2_0
- r-tidyverse=1.0.0=r3.3.2_0
- r-ttr=0.23_1=r3.3.2_0
- r-uuid=0.1_2=r3.3.2_0
- r-xml2=1.0.0=r3.3.2_0
- r-xtable=1.8_2=r3.3.2_0
- r-xts=0.9_7=r3.3.2_2
- r-yaml=2.1.14=r3.3.2_0
- r-zoo=1.7_13=r3.3.2_0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - et-xmlfile==1.0.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - prompt-toolkit==1.0.9
  - pypyodbc==1.3.4
  - rope-py3k==0.9.4.post1
  - tables==3.3.0
prefix: /home/Sysadmin/anaconda3

Regards,
Bryan

**Comment by pasapepe** [comment]
Hello,

I think you should "restart" the execution in a new environment. It is easy, safe and you can track version number for everything.

You can follow the same URI I provide you a post ago but summarizing:

-Create new environment:
conda create -n MyNEWEnvironment python
-Activate created environment:
source activate MyNEWEnvironment

[At this point you will have a more or less isolated framework for your Python code. Please note that the Python binary you can run once the environment is activated is the Anaconda one, it doesnt matter if your default Python version, prior activating the environment, is 2.7 for example]

-Install/enable packages for this environment: Only the packages installed/enabled will be available in this environment
For example:
conda install -n MyNEWEnvironment pip
conda install -n MyNEWEnvironment pyodbc==3.0.10
....
All you need.
[TIP: you can use always conda list -n MyNEWEnvironment  to check installed packages/version]

Now you are ready to run your Python code into a controlled environment.
First runs will through you a lot of package not available/installed... keep calm and install everything (but minimun) you need.

[TIP: When you activate an environment your Linux prompt will change to allow you see which environment are you in, To exit an environment, simply run source deactivate]


I hope this can allows you to go ahead a little bit more.


Regards

Alex

**Comment by bankyha** [comment]
Thanks Alex, 
It works!!
With new environment with minimum package(python and pyodbc), it doesn't generate the same error.. 
Thank you so much for advising and it really helps me a lot. 
Once I find out which package cause the issue, I'll post it here. 
Thanks again!
Regards,
Bryan

**Comment by bankyha** [comment]
So far, 
I've installed following packages on new environment, and still it's working fine.. 

conda install -n snowflakes pyodbc=3.0.10
conda install -n snowflakes pip
conda install -n snowflakes pandas=0.19.2
conda install -n snowflakes scipy=0.18.1=np111py36_1
conda install -n snowflakes scikit-learn=0.18.1=np111py36_1
conda install -n snowflakes ipython=5.1.0=py36_0
conda install -n snowflakes jupyter=1.0.0=py36_3
conda install -n snowflakes tensorflow=1.1.0=np111py36_0
conda install -n snowflakes theano=0.9.0=py36_0
conda install -n snowflakes keras=2.0.2=py36_0
conda install -n snowflakes seaborn=0.7.1=py36_0
conda install -n snowflakes -c r r-essentials

I would need to compare all packages between old and new environment and test it.. 
Regards,
Bryan

**Comment by pasapepe** [comment]
Hello,

going back to this issue I found in other resources another solution

Simply run:

> root@machine:/home/aiadmin/python_test# conda update libgcc
> Fetching package metadata .........
> Solving package specifications: .
> 
> Package plan for installation in environment /opt/anaconda:
> 
> The following packages will be UPDATED:
> 
>     libgcc: 4.8.5-2 --> 5.2.0-0
> 
> Proceed ([y]/n)? y

And everything will work again ;)

Regards

Alex

**Comment by dpezim** [comment]
I am getting the "Can't open lib" error while trying to run code on FloydHub. I don't get the same error on my local machine. I don't think I can do the new environment solution on floydhub, and libgcc does not seem to exist on either the FH machine or my local machine -- can anyone explain that solution further?

**Comment by costrouc** [comment]
I have the same issue when building a docker container

**Comment by v-chojas** [comment]
You can try to `strace` the process to see which file it is trying to open and failing to. The error message is only the driver library name, but it can also occur if one of its dependencies (and their transitive dependencies) fails to load.

**Comment by costrouc** [comment]
@v-chojas I found out that the issue has to do with the microsoft deb package for debian not being packaged properly. When I ran `ldd` on the shared library `libssl` and `libcrypto` were not found. Since I am building a docker image that will be used in production I did not want to resort to hacks. I instead used an ubuntu image and the ubuntu deb packaging to mssql odbc driver works fine.

**Comment by v-chojas** [comment]
@costrouc please ensure you are using correct package for the version of Debian. The 8 and 9 packages have slightly different dependencies.

**Comment by sprankle** [comment]
Microsoft changed the package name

change `msodbcsql` to `msodbcsql17`

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017&viewFallbackFrom=ssdt-18vs2017

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Comment by corey-dawson** [comment]
I am having the same issue, however, i dont see this as a pyton issue as i get the error running isql from the command line, This is in a docker image. OS info here:

NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"

i have added the odbc trace option in the odbinst.ini file. The full error:

[ODBC][31][1642685080.665980][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x561eac6f9b80
[ODBC][31][1642685080.666012][SQLAllocHandle.c][377]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x561eac6f9b80
                UNICODE Using encoding ASCII 'ANSI_X3.4-1968' and UNICODE 'UCS-2LE'

[ODBC][31][1642685080.666215][SQLAllocHandle.c][513]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x561eac700050
[ODBC][31][1642685080.666236][SQLDriverConnect.c][748]
                Entry:
                        Connection = 0x561eac700050
                        Window Hdl = (nil)
                        Str In = [DRIVER={ODBC Driver 17 for SQL Server};server=TSVMAEPHQDB019;UID=SubSitesDataRead;PWD=**********][length = 96 (SQL                                                 _NTS)]
                        Str Out = 0x7ffded5a5620
                        Str Out Max = 2048
                        Str Out Ptr = (nil)
                        Completion = 0
[ODBC][31][1642685080.669342][SQLConnect.c][1140]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.2' : file not found
[ODBC][31][1642685080.669379][SQLError.c][424]
                Entry:
                        Connection = 0x561eac700050
                        SQLState = 0x7ffded5a9c36
                        Native = 0x7ffded5a9c30
                        Message Text = 0x7ffded5a9c40
                        Buffer Length = 500
                        Text Len Ptr = 0x7ffded5a9c2e
[ODBC][31][1642685080.669414][SQLError.c][474]
                Exit:[SQL_SUCCESS]
                        SQLState = 01000
                        Native = 0x7ffded5a9c30 -> 0 (32 bits)
                        Message Text = [[unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.2' : file                                                  not found]
[01000][unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.2' : file not found
[ODBC][31][1642685080.669438][SQLError.c][424]
                Entry:
                        Connection = 0x561eac700050
                        SQLState = 0x7ffded5a9c36
                        Native = 0x7ffded5a9c30
                        Message Text = 0x7ffded5a9c40
                        Buffer Length = 500
                        Text Len Ptr = 0x7ffded5a9c2e
[ODBC][31][1642685080.669461][SQLError.c][474]
                Exit:[SQL_NO_DATA]
[ODBC][31][1642685080.669476][SQLError.c][424]
                Entry:
                        Environment = 0x561eac6f9b80
                        SQLState = 0x7ffded5a9c36
                        Native = 0x7ffded5a9c30
                        Message Text = 0x7ffded5a9c40
                        Buffer Length = 500
                        Text Len Ptr = 0x7ffded5a9c2e
[ODBC][31][1642685080.669501][SQLError.c][474]
                Exit:[SQL_NO_DATA]
[ISQL]ERROR: Could not SQLDriverConnect
[ODBC][31][1642685080.669524][SQLFreeHandle.c][290]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x561eac700050
[ODBC][31][1642685080.669553][SQLFreeHandle.c][339]
                Exit:[SQL_SUCCESS]
[ODBC][31][1642685080.669569][SQLFreeHandle.c][220]
                Entry:
                        Handle Type = 1
                        Input Handle = 0x561eac6f9b80

Some important notes:
1) i have followed microsofts exact instructions, uninstalling unixODBC before installing: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17
2) i ran chmod 777 -R to verify there was no permissions issues on the driver / path
3) verified the path to the driver is correct and the driver's name is correct. 

odbcinst.ini file below:

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.2
UsageCount=1

[ODBC]
Trace=Yes
TraceFile=/dev/stdout

**Comment by v-chojas** [comment]
You can use strace to find out which file it is not finding.
