### ISSUE TITLE
Truncated and unicode encoded column names with Apache Drill data source

### ISSUE THREAD

**Issue by iandow** [mkleehammer/pyodbc#242]
### Environment

- Python: 2.7.6
- pyodbc: 4.0.16
- OS: Ubuntu 14.04
- DB: csv
- driver: libdrillodbc_sb64.so

#### Expected behavior:
I’m trying to read a csv file using from Apache Drill. I expect my column names in the resulting data frame to reflect what I see in the csv file.

```
$ head -n 1 /mapr/my.cluster.com/tmp/salary_data.csv2
name,salary,years_experience
```

#### Observed behavior:
My column names are all truncated and encoded as unicode, as shown below:

```
>>> conn = pyodbc.connect("DSN=drill64", autocommit=True)
>>> df=pd.read_sql("SELECT * FROM dfs.tmp.`salary_data.csv2`", conn)
>>> df.columns.values
array([u'n\x00a\x00', u's\x00a\x00l\x00',
       u'y\x00e\x00a\x00r\x00s\x00_\x00e\x00x\x00', u'f\x00q',
       u'f\x00i\x00l\x00e\x00', u'f\x00i\x00l\x00e\x00', u's\x00u\x00f\x00'], dtype=object)
```

**Comment by mkleehammer** [comment]
We'll have to experiment a bit, but it shouldn't be too hard.  Unicode was not well defined in the ODBC specification, so drivers do different things.  The default encoding pyodbc uses for everything is UTF16LE, but it looks like you might need to try:

    cnxn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-32le')

What does that produce?

The [Unicode Wiki page](https://github.com/mkleehammer/pyodbc/wiki/Unicode) may be helpful.

**Comment by iandow** [comment]
The utf-32le encoding worked!  Thanks for suggesting that.
