### ISSUE TITLE
Problem inserting Unicode into MSSQL with non-parameterized queries

### ISSUE THREAD

**Issue by timnyborg** [mkleehammer/pyodbc#244]
### Setup
- Python: 2.7
- pyodbc: 4.0.16
- OS: Debian 8
- DB: MSSQL2014 (Latin1_General_CI_AS encoding), but the issue was also present on MSSQL2005
- driver: FreeTDS 7.1

### Issue
If I insert unicode characters passed as parameters, everything works as expected:

cur = cnxn.cursor()
q = cur.execute(u'insert into person (surname) values (?)', u'Ż')  
q.commit()
cur.execute('select top 1 surname from person order by id desc').fetchall()
[(u'\u017b', )]

But if the value is included inline, the character gets corrupted:

q = cur.execute(u'insert into person (surname) values (\'Ż\')')
or
q = cur.execute(u'insert into person (surname) values (N\'Ż\')')
q.commit()
cur.execute('select top 1 surname from person order by id desc').fetchall()
[(u'{', )]

Decoding Unicode is always fine, and inserting such characters via FreeTDS' tsql tool also works fine

**Comment by gordthompson** [comment]
Is your Python source file saved as a UTF-8 encoded text file? Have you included

```python
# -*- coding: utf-8 -*-
```

as the first line of that file?

**Comment by timnyborg** [comment]
Yes, it's a utf-8 file with the coding string at the top

**Comment by gordthompson** [comment]
Please post the results of `tsql -C`.

**Comment by timnyborg** [comment]
Compile-time settings (established with the "configure" script)
                            Version: freetds v0.91
             freetds.conf directory: /etc/freetds
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 4.2
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes

Since it wasn't compiled with a higher TDS version as default, I connect with "TDS_VERSION=7.1"

**Comment by gordthompson** [comment]
I was able to reproduce your issue with FreeTDS 0.91, the version that was installed via the Ubuntu 16.04 repositories.

The problem did not occur after I downloaded the latest stable version of FreeTDS, currently

ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.40.tar.gz

built it using

```
./configure --with-tdsver=7.3 --enable-msdblib
make
sudo make install
```

and then replaced my old entry in /etc/odbcinst.ini ...

```
[FreeTDS_ODBC]
Description=FreeTDS ODBC
Driver=/usr/lib/i386-linux-gnu/odbc/libtdsodbc.so
```

... with this:

```
[FreeTDS_ODBC]
Description=FreeTDS ODBC
Driver=/usr/local/lib/libtdsodbc.so
```

**Comment by timnyborg** [comment]
And it works!
Thank you **so** much.  I'd been trying to deal with this issue for an absolute age.
