### ISSUE TITLE
pyodbc import error

### ISSUE THREAD

**Issue by wookeanfei** [mkleehammer/pyodbc#245]
### Environment

Windows 7 Professional 32-bit service pack 1
Spyder 3.14
pyodbc-4.0.16

### Issue

1. I installed Anaconda Spyder 3.14 version (the latest as I submit this issue) on my Windows 7 Pro 32 bit machine.
2. I then installed pyodbc package via conda.exe, using the command "conda install -c anaconda pyodbc=4.0.16"
3. The package resides in the "Users" folder with the following structure:
"C:\Users\XXXX\AppData\Local\Continuum\Anaconda3\pkgs\pyodbc-4.0.16-py36_0\Lib\site-packages\pyodbc.cp36-win32.pyd"
"C:\Users\test.engineer\AppData\Local\Continuum\Anaconda3\pkgs\pyodbc-4.0.16-py36_0\Lib\site-packages\pyodbc-4.0.16-py3.6.egg-info"
4. I then launch Spyder and run a basic "import pyodbc as db" and it returns me with the following error:

> runfile('C:/Users/test.engineer/.spyder-py3/temp.py', wdir='C:/Users/test.engineer/.spyder-py3')
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-272fd6d6ca10>", line 1, in <module>
>     runfile('C:/Users/test.engineer/.spyder-py3/temp.py', wdir='C:/Users/test.engineer/.spyder-py3')
> 
>   File "C:\Users\test.engineer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\test.engineer\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/test.engineer/.spyder-py3/temp.py", line 1, in <module>
>     import pyodbc as odbc
> 
> ImportError: DLL load failed: The specified procedure could not be found.

![pyodbc_error_log_](https://cloud.githubusercontent.com/assets/18824650/26394918/11d822c4-40a1-11e7-9381-f6f9856221bc.png)

ps: I repeated the steps with another computer (a 64-bit Windows 7) and I got the same error

**Comment by tyokota** [comment]
I ran into the same issue on a Windows 7 64-bit machine running Anaconda 3.6. I uninstalled and re-installed an older version; here's a [link](https://anaconda.org/anaconda/pyodbc/files) for reference to older versions.
``````

**Comment by wookeanfei** [comment]
Thanks, it helps! I removed the 4.0.16 version and installed the older 3.0.10 and it works!
