### ISSUE TITLE
Connection Object Timeout?

### ISSUE THREAD

**Issue by alexisrolland** [mkleehammer/pyodbc#247]
Hello
I have a question which is not a bug. I looked in the Wiki as well as on the web and did not find any answer so I'm asking it here.

I have a script which initiates a Pyodbc connection to a Teradata database when it starts. After 1h20 minutes, the script is reusing the connection object to execute a query on Teradata (using pandas). The query is very simple and I know it is correct because I have tested it manually. When the script executes it, I get the following error message:

`oData = pandas.read_sql(oQuery, oConnexion)`

> Error message: (, DatabaseError("Execution failed on sql: SELECT DATA_QUALITY_INDICATOR\n ,DATA_QUALITY_INDICATOR_PARAMETER\n
> ,DATA_QUALITY_INDICATOR_PARAMETER_VALUE\n FROM AUDIT_VIEWS.AUDIT_DATA_QUALITY_INDICATOR_PARAMETER A\n JOIN AUDIT_VIEWS.AUDIT_DATA_QUALITY_INDICATOR B ON A.DATA_QUALITY_INDICATOR_KEY=B.DATA_QUALITY_INDICATOR_KEY\n
> WHERE DATA_QUALITY_INDICATOR='DATA_COMPLETENESS_DNA_EXPORT_COUNTER_VS_CSV_DATA'\n AND DATA_QUALITY_INDICATOR_PARAMETER='oMeasures';\n('HY000', 'The driver did not supply an error!')\nunable to rollback",), )

Although it's not explicit, I'm thinking the execution failed because the connection object may have timed out (note that no time out is set when creating the connection object). Would you know a way to:

- Keep the connection object alive during the whole process?
- Test if the connection object is still valid prior executing a query?

Thanks

PS: question also posted on StackOverflow:
https://stackoverflow.com/questions/44364401/test-pyodbc-connection-object

**Comment by alexisrolland** [comment]
One solution I'm thinking about but it's not very elegant is to run a simple query prior executing the actual query I want to run. Maybe something simple like `select '1'` just to test if the connection is still open.
What do you think?

**Comment by alexisrolland** [comment]
I implemented the following workaround which confirms it was a timeout issue with the connection object. Before reusing the connection object I'm testing and reopen a connection if the test fails.

```
 import pyodbc
 try:
 #test current connection object in global variable
      oConnexion = oGlobalVariable['oConnexion']
      oCursor = oConnexion.cursor()
      oCursor.execute("select '1'")
      oCursor.close()
 except:
      #if test fails re-open connection
      oConnexionString = fGetParameterFile(pFileName="global_parameter.ini", pSectionName="AUDIT", pParameterName="oConnexionString")
      oConnexion = pyodbc.connect(oConnexionString, autocommit=True)
      oConnexion.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
      oConnexion.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
      oConnexion.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-8')
      oConnexion.setencoding(encoding='utf-8')
      oGlobalVariable['oConnexion'] = oConnexion
      return oConnexion
 else:
      return oGlobalVariable['oConnexion']
```

**Comment by ChaminW** [comment]
Any proper solution for this other than above connection validation prior to use?

**Comment by v-chojas** [comment]
@ChaminW this is handled by the driver. Some e.g. SQL Server have "idle connection resiliency" feature which will reconnect, or there may be a "keepalive" option, but otherwise if connection is interrupted you will need to reconnect manually.
