### ISSUE TITLE
32768-65535 parameters reported as negative (exact counts might vary by platform) (patch included)

### ISSUE THREAD

**Issue by dfackrell** [mkleehammer/pyodbc#250]
Expected behavior:

Number of parameters should always be reported as a non-negative number

Observed behavior:

```
ProgrammingError: ('The SQL contains -21374 parameter markers, but 44162 parameters were supplied', 'HY000')
```

This is due to treating an unsigned 16-bit value as signed, and then casting to a larger signed integer type.

Resolution:

Expect a one-character pull request

**Comment by dfackrell** [comment]
My configuration needs some work before I can contribute directly to public projects. Here's a patch in lieu of the promised pull request:

```
diff --git a/src/params.cpp b/src/params.cpp
index 4d152d2..57aa978 100644
--- a/src/params.cpp
+++ b/src/params.cpp
@@ -738,7 +738,7 @@ bool PrepareAndBind(Cursor* cur, PyObject* pSql, PyObject* original_params, bool
         FreeParameterInfo(cur);

         SQLRETURN ret = 0;
-        SQLSMALLINT cParamsT = 0;
+        SQLUSMALLINT cParamsT = 0;
         const char* szErrorFunc = "SQLPrepare";

         const TextEnc* penc;
```

**Comment by dfackrell** [comment]
Note: This patch doesn't help with counts > 65535, such as this one:

```
ProgrammingError: ('The SQL contains 28984 parameter markers, but 225592 parameters were supplied', 'HY000')
```

I haven't dived into the protocol with the various database engines to see whether a longer unsigned integer type can be used from the start.

**Comment by keitherskine** [comment]
The params counter for SQLNumParams is defined as a SQLSMALLINT:
https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlnumparams-function?view=sql-server-ver15#syntax

Having more than 32K parameter markers would seem unusual.
