### ISSUE TITLE
running on big endian systems

### ISSUE THREAD

**Issue by dangowrt** [mkleehammer/pyodbc#253]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- MIPS32r2 (big endian)
- Python 3.6.1
- pyodbc 4.0.17
- OS Linux (OpenWrt/LEDE)
- DB PostgreSQL 9.6.3
- driver psqlodbcw (and psqlodbca as well)

### Issue

While everything works nicely on all little endian systems, things break on big-endian boxes:
```
root@LEDE:/# python3
Python 3.6.1 (default, Jul 10 2017, 04:39:25) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> cnxn = pyodbc.connect("DRIVER={PostgreSQL Unicode};SERVER=localhost;DATABASE=template1;UID=postgres;PWD=password;PORT=5432")
>>> c = cnxn.cursor()
>>> c.execute("SELECT 'test' AS test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42601', '[42601] ERROR: syntax error at or near "匀䔀䰀䔀䌀吀\u2000✀琀攀猀琀✀\u2000䄀匀\u2000琀攀猀琀";\nError while executing the query (1) (SQLExecDirectW)')
>>> 
```
Note that ODBC generally works fine on the box, connecting to the same database using `isql` performing the same query is no problem:

```
root@LEDE:/etc# isql psqlodbc_test_dsn
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> SELECT 'test' AS test;
+-----+
| test|
+-----+
| test|
+-----+
SQLRowCount returns 1
1 rows fetched
```

Also note that on an otherwise identical little endian MIPS32r2 it works just fine, ie.
```
root@LEDE:/# python3
imporPython 3.6.1 (default, Jul 10 2017, 09:34:47) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
        
>>> import pyodbc
>>> cnxn = pyodbc.connect("DRIVER={PostgreSQL Unicode};SERVER=localhost;DATABASE=template1;UID=postgres;PWD=password;PORT=5432")
>>> c = cnxn.cursor()
>>> c.execute("SELECT 'test' AS test")
<pyodbc.Cursor object at 0x9576d0>
>>> 
```

**Comment by gordthompson** [comment]
Have you tried experimenting with the `cnxn.setencoding` and `cnxn.setdecoding` properties as described on the [Unicode wiki page](https://github.com/mkleehammer/pyodbc/wiki/Unicode)?

**Comment by dangowrt** [comment]
@gordthompson Thanks! That was a very helpful reference.
> By default, pyodbc uses UTF-16LE and SQL_C_WCHAR for reading and writing all Unicode as recommended in the ODBC specification. 
Wouldn't it make sense to default to UTF-16BE on big-endian systems? Or does the ODBC spec explicitely state to use UTF-16LE no matter what (in that case it should be changed in psqlodbc).

**Comment by dangowrt** [comment]
So `cnxn.setencoding('utf-16-be')` did the trick on the big-endian box.
I also tried using the automatic `utf-16` type, but as it seems unixODBC (or at least the official PostgreSQL driver) doesn't support the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) which then preceeds every string.

My goal here is to make stuff work out-of-the-box independently of the platform chosen.
So things just work on little-endian without explicitely setting the encoding but on a big-endian box manually setting the encoding is required (note that both the ODBC client application and the database server are running on the same box). So now there are several ways to interpret the situation:

1. PostgreSQL's ODBC driver violates the spec by chosing UTF-16BE as a default for SQL_WCHAR and should rather always use UTF-16LE unless expecitely told otherwise.
2. unixODBC somehow misses to enforce UTF-16LE no-matter-what and that should be fixed.
3. pyODBC sets UTF-16LE no-matter-what and that should be changed to default to the native endian.

What do you think? @gordthompson @mkleehammer

**Comment by gordthompson** [comment]
> So things just work on little-endian without explicitely setting the encoding but on a big-endian box manually setting the encoding is required

Would this suffice?

```python
if sys.byteorder == 'big':
    cnxn.setencoding('utf-16-be')
```

**Comment by dangowrt** [comment]
@gordthompson Yes, that'd work around the problem. And it's exactly what I'd like to avoid -- having to take care of hardware-specific details in the Python code...

**Comment by keitherskine** [comment]
This speaks to the wider issue of pyodbc detecting the environment it is being used in - OS, OS byte-width, driver, RDBMS, etc. - and changing internal settings automatically (unless explicitly set by the client of course).  It seems this should be possible for the most part.

**Comment by dangowrt** [comment]
My current fix looks like this (assuming answer **_3_** to the question above)
https://github.com/openwrt/packages/blob/master/lang/python/pyodbc/patches/100-connection-assume-SQL_C_WCHAR-is-native-endian.patch
