### ISSUE TITLE
VarChar and LVarChar Handling with IBM Informix

### ISSUE THREAD

**Issue by a-musing-moose** [mkleehammer/pyodbc#260]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.2
- pyodbc: 4.0.17
- OS: Linux & MacOS
- DB: Informix
- driver: Informix ODBC driver from IBM

### Issue
When attempting to insert more than 255 characters into a Varchar field we get the following error: 

`('HY000', '[HY000] [Informix][Informix ODBC Driver][Informix]No cast from text to lvarchar. (-9634) (SQLParamData)')`

It seems that a quirk of Informix is that all varchar fields require data to be sent as the `SQL_VARCHAR` type (see: https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.odbc.doc/ids_odbc_083.htm) irrelevant of length.  Only Text fields need to be sent as `SQL_LONGVARCHAR`.

I'm not a C programmer, but we managed to adapt the code to make it work for us by really just using `SQL_VARCHAR`. But clearly this breaks both `Text` fields and likely everyone else use of PyODBC which is far from ideal.

**Comment by mkleehammer** [comment]
I think a solution to #213 would help you here.  I've been holding off on that because I don't have a good "Pythonic" way to pass it, but I think it is time to come up with something.

Do you have *something* working for you for now?

**Comment by highway900** [comment]
No unfortunately this doesn't do the trick.
e.g.
`cursor.execute('insert into t_temp(lvarname) values(cast(? as lvarchar(5000)))', 'p'*256)` still returns the `No cast from text to lvarchar. ` error
`cursor.execute('insert into t_temp(lvarname) values(cast(? as varchar(5000)))', 'p'*256)` returns `Maximum varchar size has been exceeded` which should be right. But our situation is interesting due to the quirk mentioned in the issue.
`pyODBC` will use `GetColumnSize` in `cnxninfo.cpp` to query the max length of SQL_VARCHAR from the informix ODBC driver, this will always return 255.

**Comment by v-chojas** [comment]
Yes, this is definitely another case where parameters need to be bound with the exact SQL type the server is expecting, despite the fact that to Python there is no difference and they are the same (i.e. string) types. Extending setinputsizes() to specify the type too seems like the way to solve this without resorting to potentially slow SQLDescribeParam (not sure what its performance is like with Informix.)

**Comment by v-chojas** [comment]
With the contents in https://github.com/v-chojas/pyodbc/tree/setinputsizes I have extended the setinputsizes() function to, in addition to its original purpose of specifying column lengths, allow specifying the type, length, and scale/precision too --- `cursor.setinputsizes([ [pyodbc.SQL_VARCHAR] ])` should then allow you to force the SQL type to be SQL_VARCHAR for the first column,

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
