### ISSUE TITLE
VARCHAR is not same length as in db

### ISSUE THREAD

**Issue by stanep** [mkleehammer/pyodbc#261]
Setup
Python: 3.6.2
pyodbc: 4.0.17
OS: windows 10
DB: MSSQL2012 (Latin1_General_CI_AS encoding)

return from dbo (column is VARCHAR(15))

'KGH', db_length 3, pyodbc.length(4) -> 'KGH '

**Comment by gordthompson** [comment]
I am unable to reproduce your issue with

```python
import pyodbc
import sys
print("Python version " + sys.version)
print("pyodbc version " + pyodbc.version)
conn_str = 'DSN=SQLmyDb'
cnxn = pyodbc.connect(conn_str, autocommit=True)
print("ODBC driver version " + cnxn.getinfo(pyodbc.SQL_DRIVER_VER))
crsr = cnxn.cursor()
crsr.execute("CREATE TABLE #tmp (id INT PRIMARY KEY, txt VARCHAR(15))")
crsr.execute("INSERT INTO #tmp (id, txt) VALUES (1, 'KGH')")
txt = crsr.execute("SELECT txt FROM #tmp WHERE id=1").fetchval()
print(repr(txt))
print([ord(x) for x in txt])
crsr.close()
cnxn.close()
```

which gives me

```
Python version 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
pyodbc version 4.0.17
ODBC driver version 11.00.6518
'KGH'
[75, 71, 72]
```

Can you try the `print([ord(x) for x in txt])` trick to see just what your fourth (trailing) character is?

**Comment by gordthompson** [comment]
Also, be aware that the T-SQL [LEN](https://technet.microsoft.com/en-us/library/ms190329(v=sql.110).aspx) function

> Returns the number of characters of the specified string expression, excluding trailing blanks.

so if you are using `LEN(...)` to check the length of the string on the server and that string really does have a trailing blank then `LEN(...)` will deceive you. For example,

```python
crsr.execute("INSERT INTO #tmp (id, txt) VALUES (1, 'KGH ')")
row = crsr.execute("SELECT txt, LEN(txt) AS lentxt FROM #tmp WHERE id=1").fetchone()
print(row)
```

prints

```
('KGH ', 3)
```

even though the string is really four (4) characters long including the trailing blank.

**Comment by stanep** [comment]
Hi I tried print([ord(x) for x in txt]) and got chr(32) ' '

**Comment by stanep** [comment]
TSQL lies :)

select
      ,DATALENGTH(FacilityAbbreviations_1) as ad
      ,LEN(FacilityAbbreviations_1) as len
will give you 4 and 3

**Comment by gordthompson** [comment]
Thanks for the update. If the mystery has been solved then you can close this issue.

**Comment by stanep** [comment]
It was column that has extra space on the end , closing issue
