### ISSUE TITLE
unable to connect to the database: Can't open lib 'MySQL ODBC 3.51 Driver' 

### ISSUE THREAD

**Issue by shravankumar147** [mkleehammer/pyodbc#264]
### Issue
unable to connect with the database: 
Error: 
('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'MySQL ODBC 3.51 Driver' : file not found (0) (SQLDriverConnect)")

### Environment

- Python: 2.7
- pyodbc: latest from pip install
- OS: ubuntu 16.04 x64
- DB:MySQL
- driver:MySQL ODBC 3.51 Driver

**Comment by gordthompson** [comment]
Have you actually installed the ODBC driver for MySQL? If so, did you register the driver so that it appears in `odbcinst.ini`, for example:

```
[MySQL ODBC 3.51 Driver]
Driver=/home/gord/Downloads/mysql-connector-odbc-3.51.30-linux-glibc2.3-x86-64bit/lib/libmyodbc3.so
UsageCount=1
```

You should be able to use the `odbcinst -j` command to check the location of `odbcinst.ini`. On Ubuntu it is typically `/etc/odbcinst.ini`.

**Comment by shravankumar147** [comment]
Tried and worked Thanks

**Comment by kevalshah90** [comment]
It appears that I have MySQL ODBC 8.0 Driver installed. Content of odbcinst.ini - 

[ODBC Drivers]
MySQL ODBC 8.0 Unicode Driver = Installed
MySQL ODBC 8.0 ANSI Driver    = Installed

[ODBC Connection Pooling]
PerfMon    = 0
Retry Wait = 

[MySQL ODBC 8.0 Unicode Driver]
Driver = /usr/local/mysql-connector-odbc-8.0.15-macos10.14-x86-64bit/lib/libmyodbc8w.so

[MySQL ODBC 8.0 ANSI Driver]
Driver = /usr/local/mysql-connector-odbc-8.0.15-macos10.14-x86-64bit/lib/libmyodbc8a.so

However, I am getting the following error when running - 

connstr = pyodbc.connect(Driver='{MySQL ODBC 8.0 Driver}',
                                              server='localhost',
                                              Database='dbname1',
                                              UID='root',
                                              PWD='xxxxxx')

Error: ('01000', u"[01000] [unixODBC][Driver Manager]Can't open lib 'MySQL ODBC 8.0 Driver' : file not found (0) (SQLDriverConnect)")

**Comment by v-makouz** [comment]
When specifying the driver in the connection string it has to match exactly what appears in odbcinst.ini, so in this case it should be either `Driver='{MySQL ODBC 8.0 Unicode Driver}'` or `Driver={MySQL ODBC 8.0 ANSI Driver}`

**Comment by kevalshah90** [comment]
@v-makouz Thanks. I have attempted both of those, still getting the same error.

**Comment by kevalshah90** [comment]
Error: ('01000', u"[01000] [unixODBC][Driver Manager]Can't open lib 'MySQL ODBC 8.0 Unicode Driver' : file not found (0) (SQLDriverConnect)")

Error: ('01000', u"[01000] [unixODBC][Driver Manager]Can't open lib 'MySQL ODBC 8.0 ANSI Driver' : file not found (0) (SQLDriverConnect)")

**Comment by v-makouz** [comment]
@kevalshah90 If the name is correct, but the driver can't be loaded you can try to check is there is any problem with the driver file itself:
`ottol -L /usr/local/mysql-connector-odbc-8.0.15-macos10.14-x86-64bit/lib/libmyodbc8w.so`

**Comment by v-makouz** [comment]
@kevalshah90 Also try 
`isql -v -k "DRIVER={MySQL ODBC 8.0 Unicode Driver};SERVER=<server>;UID=<user>;PWD=<password>"`
It might give a more informative message about what it's not finding

**Comment by kevalshah90** [comment]
Unfortunately, same message upon running the above line of code. 

`Can't open lib 'MySQL ODBC 8.0 Unicode Driver' : file not found (0) (SQLDriverConnect)"). `

I wonder if it is looking in the right place for the file.

**Comment by v-makouz** [comment]
@kevalshah90 If isql shows this and not the filename it means that the Driver Manager still can't match `MySQL ODBC 8.0 Unicode Driver` with an entry in odbcinst.ini. So the next thing to check is to run `odbcinst -j`, it will display (among other things) something like this:
`DRIVERS............: /usr/local/etc/odbcinst.ini`
Make sure that the odbcinst.ini that the Driver Manager expects is the one that has the MySQL entries

**Comment by kevalshah90** [comment]
So, here are the paths for the driver - 

[MySQL ODBC 8.0 Unicode Driver]
Driver = /usr/local/mysql-connector-odbc-8.0.15-macos10.14-x86-64bit/lib/libmyodbc8w.so

[MySQL ODBC 8.0 ANSI Driver]
Driver = /usr/local/mysql-connector-odbc-8.0.15-macos10.14-x86-64bit/lib/libmyodbc8a.so

whereas the output of `odbcinst -j` suggests /usr/local/**etc/**odbcinst.ini. 

I wonder if that the discrepancy?

**Comment by v-makouz** [comment]
@kevalshah90 I mean when you are looking at the odbcinst.ini, is that the same odbcinst.ini that's listed by `odbcinst -j`?

**Comment by kevalshah90** [comment]
Different paths. The one I am looking at is /Library/ODBC/odbcinst.ini and the one listed by `odbcinst -j` is /usr/local/etc/odbcinst.ini.

**Comment by v-makouz** [comment]
@kevalshah90 You'll need to copy the entries (or the whole file) to `/usr/local/etc/odbcinst.ini` because that's the one that the Driver Manager is reading

**Comment by kevalshah90** [comment]
Thanks for your help. For the record, `MySQL ODBC 8.0 ANSI Driver` works.

**Comment by gisael** [comment]
> @kevalshah90 You'll need to copy the entries (or the whole file) to `/usr/local/etc/odbcinst.ini` because that's the one that the Driver Manager is reading
> 
> To copy the whole file you can run `cp /Library/ODBC/odbcinst.ini /usr/local/etc/odbcinst.ini` which will **overwrite everything** in the destination.

You are amazing. Your very detailed explanation made my date. I appreciate your elaborated help here. Thanks!

**Comment by clcneogeek325** [comment]
Hey dudes I had the same problem, I did something that the developer we don´t do more often,
read the oficial documentation: https://dev.mysql.com/doc/connectors/en/connector-odbc-installation-binary-unix-tarball.html , you are welcome.

**Comment by jose598** [comment]
Thank you! This helps me to find a solution!

**Comment by Seamen11** [comment]
Good day, I have followed your recommendations, but always get a problem: pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/local/mysql-connector-odbc-8.1.0-macos13-arm64/lib/libmyodbc8a.so' : file not found (0) (SQLDriverConnect)")
how can I fix it?(this file exist and cmd cat is running with this)

**Comment by v-chojas** [comment]
Run `otool -L` on that file and see if there are missing dependencies. "file not found" can refer to the file itself or one of its dependencies.
