### ISSUE TITLE
Connection randomly hangs

### ISSUE THREAD

**Issue by Belval** [mkleehammer/pyodbc#266]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.5
- pyodbc:  4.00
- OS:  Ubuntu 16.04
- DB: SQL Server 2016
- driver: FreeTDS 1.00.51 (Built from source) with UnixODBC, the same problem happens with ODBC Driver 13 for SQL Server

### Issue

**Observed behavior**

Using this little snippet of code:

    import time
    for i in range(0, 1000):
        import pyodbc
        start = time.time()
        try:
            conn = pyodbc.connect('DSN=dbs;Uid=username;Pwd=pass;Connection Timeout=1')
            conn.timeout = 1
            cur = conn.cursor()
        except Exception as e:
            print(e)
            print('[{}] Time: {}'.format(i, time.time() - start))
        del pyodbc
        time.sleep(0.2)

FreeTDS : I get time ranging from 0.001 sec to 138 secs
Driver 13 : I get time ranging from 0.01 to 30 secs where 30 secs are `[unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired (0) (SQLDriverConnect)`
 
My config for FreeTDS (freetds.conf) is:

    [dbs]
    host = db_domain
    port = 1433
    tds version = 7.4
    client charset = UTF-8

My config for UnixODBC (odbc.ini) is:

    [dbs]
    Driver=FreeTDS
    TDS_Version=7.4
    Servername=dbs
    Port=1433
    Database=DbName

My config for UnixODBC (odbcinst.ini)

    [ODBC]
    Trace=No
    TraceFile=/tmp/odbc.log

    [FreeTDS]
    Description=FreeTDS
    Driver=/usr/lib/libtdsodbc.so
    UsageCount=10

    [ODBC Driver 13 for SQL Server]
    Description=Microsoft ODBC Driver 13 for SQL Server
    Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.0
    UsageCount=1

**Expected behavior**

Connection timeout should work.
Connection time should be the same accross all requests.

**Comment by v-chojas** [comment]
Which exact version of Python 3.5 are you using: 3.5.4, 3.5.3, etc.?
Similarly, are you using pyODBC 4.0­ **.0** or some other 4.0.x version (in which case, please specify x)? You can `print(pyodbc.version)` to determine this.

**Comment by Belval** [comment]
Python 3.5.2
Pyodbc 4.0.16

Using ODBC SQL Driver 13.1 (and 13) I get `[unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired (0) (SQLDriverConnect)` every few requests randomly. Is that a know issue?

**Comment by keitherskine** [comment]
It seems very odd to import and delete the `pyodbc` module within a loop.  Is that a deliberate part of the test?  If you just import `pyodbc` once at the very beginning do you get the same error?

**Comment by Belval** [comment]
Part of the test, doing first did not change the outcome.On Aug 9, 2017 07:33, Keith Erskine <notifications@github.com> wrote:It seems very odd to import and delete the pyodbc module within a loop.  Is that a deliberate part of the test?  If you just import pyodbc once at the very beginning do you get the same error?

**Comment by v-chojas** [comment]
I have tested your script with

- Ubuntu 16.04
- Python 3.5.2
- pyODBC 4.0.16
- Microsoft ODBC Driver 13 for SQL Server, v13.1.9.0
- SQL Server 2016

and several thousand iterations completed successfully. There is one more variable --- what version of unixODBC are you using? You can see it with `odbcinst -j` command. I am using 2.3.4. Otherwise I suspect the problem could be in the network layer and not related to pyODBC.

**Comment by Belval** [comment]
Today we tried running it with another SQL Server and it seems to be working. Knowing this I'd be very surprised if it was a pyodbc issue and will therefore close it.
