### ISSUE TITLE
msodbcsql on ubuntu16.04(wsl) gets ascii not utf-8

### ISSUE THREAD

**Issue by fenchu** [mkleehammer/pyodbc#267]
Hi
I'm completely new to mssql and was surprised to see how easy it was to get the client up and running on ubuntu, but I have some encoding errors. database is afaik standard in Azure.
I've tried lots of *.setencoding() and .*setdecoding() variations without any differences.
the strange thing is that it is always correct in powershell, and always error in ubuntu under linux windows subsystem. But it is strange it gets 'ascii' I believed all in python3 should be 'utf-8'

Will it work with older version of msodbcsql? 13.1.9.0-1, but I was unable to find any older in the same repo.

Any help debugging,workaround very appreciated, thanks

--
Morten Bjørnsvik, Sensio, Norway

```
$ dpkg -l msodbcsql mssql-tools
    Name                                           Version                      Architecture                 Description
ii  msodbcsql                                      13.1.9.0-1                   amd64                        ODBC Driver for Microsoft(R) SQL Server(R)
ii  mssql-tools                                    14.0.6.0-1                   amd64                        Tools for Microsoft(R) SQL Server(R)
```

```
$ cat /opt/microsoft/msodbcsql/etc/odbcinst.ini
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.0
```

```
$ pip freeze | grep pyodbc
pyodbc==4.0.17
```

Simple example database is in azure, default setup
```
import pyodbc
server = 'XXXXXXXX.database.windows.net'
database = 'XXXXX'
username = 'XXXXX'
password = 'XXXXX'
driver= '{ODBC Driver 13 for SQL Server}'
conn = pyodbc.connect('DRIVER='+driver+';PORT=1433;SERVER='+server+';PORT=1443;DATABASE='+database+';UID='+username+';PWD='+ password)
#conn.setdecoding(pyodbc.SQL_WCHAR, encoding='latin1')
conn.setencoding('utf-8')
conn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
conn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cursor = conn.cursor()
cursor.execute("select projectId, name from Projects where projectId='{:s}'".format('29F54913-B615-411D-BBB3-FF2BA3F795BD'))
row = cursor.fetchone()
while row:
    try:
        print("{}".format(row))
    except UnicodeEncodeError as e:
        print("Error:{}".format(e))
        pass
    print("{}".format(str(row).encode('utf-8')))
    row = cursor.fetchone()
```

running under ubuntu 16.04 python 3.6.2
```
$ ./get-projects.py
Error:'ascii' codec can't encode character '\xf8' in position 48: ordinal not in range(128)
b"('29F54913-B615-411D-BBB3-FF2BA3F795BD', 'Innend\xc3\xb8rs Posisjonering 10. Etg')"
```

Powershell python3.6.2 it gets correct
```
PS D:\sensio-data\python-mssql> python.exe .\get-projects.py
('29F54913-B615-411D-BBB3-FF2BA3F795BD', 'Innendørs Posisjonering 10. Etg')
b"('29F54913-B615-411D-BBB3-FF2BA3F795BD', 'Innend\xc3\xb8rs Posisjonering 10. Etg')"
```

It also works in sqlcmd (from mssql-tools):
```
1> select projectId, name from projects where projectid='29F54913-B615-411D-BBB3-FF2BA3F795BD';
2> go                                                                                          
projectId                            name                                                      
------------------------------------ ----------------------------------------------------------
29F54913-B615-411D-BBB3-FF2BA3F795BD Innendørs Posisjonering 10. Etg                           
```                                                                          

I have no idea to get collation from inside pyodbc, just says not supported:
`'ODBC SQL type -150 is not yet supported.  column-index=0  type=-150', 'HY106'`

collation in sqlcmd
```
1> select serverproperty('collation');
SQL_Latin1_General_CP1_CI_AS
```

**Comment by keitherskine** [comment]
Are you certain `./get-projects.py` is running under python 3.6.2 and not some default Python installation?  If you run `python3 ./get-projects.py`, do you get the same error?

**Comment by v-chojas** [comment]
'\xf8' is the ø character encoded in Latin-1 (i.e. ISO-8859-1/Windows-1252), which is also the default character set of your database.

With Ubuntu 16.04 + Python 3.6.2 + pyODBC 4.0.17 + msodbcsql 13.1.9.0 I cannot reproduce that error, both without and with the setencoding/setdecoding calls. The ø character is retrieved and displayed correctly, from both a varchar and nvarchar column containing it.

**Comment by gordthompson** [comment]
@fenchu re: 

> I believed all in python3 should be 'utf-8'

No, in Python 3 all strings are **Unicode**. Unicode is the character *set* (integer values named *code points* that represent characters). UTF-8 is an *encoding* (sequences of bytes that represent code Unicode code points). See [this article](http://www.joelonsoftware.com/articles/Unicode.html) for more information.

The Unicode *encoding* that Python 3 itself uses internally is really irrelevant. pyodbc's `setencoding` and `setdecoding` methods are its way of controlling how Unicode *characters* - integer code points - in Python are converted to (and from) the streams of bytes it sends to (and receives from) the ODBC driver. For msodbcsql that *encoding* is UTF16-LE, which is the default encoding that pyodbc uses.

**Comment by gordthompson** [comment]
@fenchu - I am unable to recreate your issue under Windows Subsystem for Linux (WSL). For my test table

```sql
CREATE TABLE projects (id INT IDENTITY PRIMARY KEY, name VARCHAR(100))
```

and my test code

```python
import pyodbc
import sys
print("Python version " + sys.version.replace("\n", " "))
print("pyodbc version " + pyodbc.version)
conn_str = (
    "Driver=ODBC Driver 13 for SQL Server;"
    "Server=192.168.1.114,49242;"
    "Database=myDb;"
    "UID=sa;PWD=whatever;"
)
cnxn = pyodbc.connect(conn_str)
print("ODBC driver version " + cnxn.getinfo(pyodbc.SQL_DRIVER_VER))
crsr = cnxn.cursor()
crsr.execute("SELECT name FROM projects WHERE id=1")
row = crsr.fetchone()
print("{}".format(row))
cnxn.close()
```

I get

```
(py3pyodbc) gord@WEEZER:~$ python3 pyotest.py
Python version 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
pyodbc version 4.0.17
ODBC driver version 13.01.0009
('Innendørs Posisjonering 10. Etg', )
```

**Comment by gordthompson** [comment]
Additional information: WSL originally installed itself with only python3 but I noticed that when I installed virtualenv I also got python27 as part of the deal. My test code above also fails to reproduce the error with python27, although it doesn't print the actual `ø` character when I print the row:

```
(py2pyodbc) gord@WEEZER:~$ python pyotest.py
Python version 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
pyodbc version 4.0.17
ODBC driver version 13.01.0009
(u'Innend\xf8rs Posisjonering 10. Etg', )
```

**Comment by fenchu** [comment]
Hi 

This located to my user setup, I'm unable to enter utf-8 codes when using sudo
(sudo su - mortenb)

Found that if I change my default user from root to mortenb it all works.
same error if I sudo to root.

I've not done anything with my usersetup except for adding pyenv to ~/.bash_profile

I see the same error if I start sshd under WSL and log in via putty I see excatly the same behaviour. 

```
PS C:\Users\morten.sensio> LxRun.exe /setdefaultuser mortenb
Found UNIX user: mortenb
Default UNIX user set to: mortenb
```



```
root@MB-PC:/mnt/d/sensio-data/python-mssql# ./pyodbc-mssql-test.py
python version:sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
pyodbc version:4.0.17
('29F54913-B615-411D-BBB3-FF2BA3F795BD', 'Innendørs Posisjonering 10. Etg')
b"('29F54913-B615-411D-BBB3-FF2BA3F795BD', 'Innend\xc3\xb8rs Posisjonering 10. Etg')"
```

**Comment by gordthompson** [comment]
> I've not done anything with my usersetup except for adding pyenv to ~/.bash_profile

Do you get more consistent results if you apply those same changes to ~/.bashrc ?

**Comment by v-chojas** [comment]
This suggests the root user has a different environment encoding than your normal one. You can try to run `locale` command or inspect LC_* environment variable's value to determine the difference between the two environments. I suspect root's locale/encoding is set to C, whereas your normal one is UTF-8.

**Comment by gordthompson** [comment]
@v-chojas - Aha! I think you may be onto something. In my normal WSL shell the `locale` command shows me

```
gord@WEEZER:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
...
```

but after I do `sudo su - gord` I see

```
gord@WEEZER:~$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
...
```

**Comment by fenchu** [comment]
I need to run this as root and restart service:

```
sudo update-locale LANG=en_US.UTF8
sc restart lxssmanager
```

[Relevant bug#564](https://github.com/Microsoft/BashOnWindows/issues/564)

As I use Norwegian:
```
sudo apt install language-pack-nb language-pack-nb-base manpages
sudo update-locale LANG=nb_NO.UTF-8
```

And then when I log in it all works, also works on ssh:
```
Last login: Thu Aug 17 11:55:03 2017 from ::1
mortenb@MB-PC:~$ python --version
Python 3.6.2
mortenb@MB-PC:~$ locale
LANG=nb_NO.UTF-8
LANGUAGE=
LC_CTYPE="nb_NO.UTF-8"
LC_NUMERIC="nb_NO.UTF-8"
LC_TIME="nb_NO.UTF-8"
LC_COLLATE="nb_NO.UTF-8"
LC_MONETARY="nb_NO.UTF-8"
LC_MESSAGES="nb_NO.UTF-8"
LC_PAPER="nb_NO.UTF-8"
LC_NAME="nb_NO.UTF-8"
LC_ADDRESS="nb_NO.UTF-8"
LC_TELEPHONE="nb_NO.UTF-8"
LC_MEASUREMENT="nb_NO.UTF-8"
LC_IDENTIFICATION="nb_NO.UTF-8"
LC_ALL=
mortenb@MB-PC:~$ /mnt/d/sensio-data/python-mssql/pyodbc-mssql-test.py
python version:sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
pyodbc version:4.0.17
('29F54913-B615-411D-BBB3-FF2BA3F795BD', 'Innendørs Posisjonering 10. Etg')
b"('29F54913-B615-411D-BBB3-FF2BA3F795BD', 'Innend\xc3\xb8rs Posisjonering 10. Etg')"
```

So it all sums down to a wsl issue not being able to properly extract LOCALE when starting.

Thanks to gord and v-chojas for Your precious time and insights.
