### ISSUE TITLE
Force overwrite table on MS Access query

### ISSUE THREAD

**Issue by Mdelaf** [mkleehammer/pyodbc#269]
I am using PYODBC to deal with MS Access (.accdb) files and it works very well, congratulations.

In MS Access files you can have queries that creates new tables (these queries are differentiated by an exclamation mark). When I run one of these queries manually, a popup appears warning that I will overwrite an existing table, so I click on "Yes" and it gets executed fine. Here it is how it looks:

![image](https://user-images.githubusercontent.com/11620077/29248132-5fd424bc-7fe6-11e7-83d7-e06d1e931169.png)

The problem is that when I try to run these queries through `pyodbc`, I got the following console error (warning that the table already exists so it cannot be overwritten):
`pyodbc.ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Microsoft Access Driver] Table 'movimientos' already exists
. (-1303) (SQLExecDirectW)")`

The code I am using is the following:
```python
import pyodbc

connStr = (
    r"Driver={Microsoft Access Driver (*.mdb, *.accdb)};"
    r"DBQ=C:\Users\Administrador\Desktop\Bases Access\Rosmini.accdb;"
    )
cnxn = pyodbc.connect(connStr)
sql = """\
{CALL MovimientosWeb}
"""
crsr = cnxn.execute(sql)
cnxn.commit()
crsr.close()
cnxn.close()
```

I've been searching for some "force" option or something similar but I didn't find anything. Do you know how can I force overwriting the table without raising that exception?

Thank you in advance.
Martín.

**Comment by gordthompson** [comment]
The "Overwrite?" option is offered to you by the user interface of the Microsoft Access application. To handle that from your Python code you will have to drop the table yourself:

```python
try:
    crsr.execute("DROP TABLE movimientos")
except pyodbc.ProgrammingError as pe:
    if pe.args[0] != "42S02":
        raise
crsr.execute("{CALL MovimientosWeb}")
```

**Comment by Mdelaf** [comment]
Thanks for your quick response @gordthompson .

Well, I have already thought about that solution, but it was something I was trying to avoid, because **my query creates a table in a separated access file**. That means that I would have to do two connections: one to drop the table in the destination access file and the other to run the creation query. If you also consider that I have to do this to multiple files which all have different destination files, it becomes a bit annoying.

Anyway, thank you again.

**Comment by gordthompson** [comment]
> That means that I would have to do two connections: one to drop the table in the destination access file and the other to run the creation query.

Actually, no, the Access Database Engine lets us use a connection to one database and manipulate tables in another database, even if those tables are not explicitly linked. Note that in the example below I connect to "Database1.accdb" and then drop a table in "OtherDatabase.accdb":

```python
conn_str = (
    r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};'
    r'DBQ=C:\Users\Public\Database1.accdb;'
)
cnxn = pyodbc.connect(conn_str, autocommit=True)
crsr = cnxn.cursor()
try:
    crsr.execute(r"DROP TABLE [C:\Users\Public\OtherDatabase.accdb].movimientos")
except pyodbc.ProgrammingError as pe:
    if pe.args[0] != "42S02":
        raise
crsr.execute("{CALL MovimientosWeb}")  # saved query in Database1.accdb
```

**Comment by Mdelaf** [comment]
Nice! I didn't know that functionality. It seems to be a very useful shortcut to avoid multiple connections, I'll give it a try.

Thanks!
