### ISSUE TITLE
Unable to enter backslash "\" properly for username connection to MSSQL

### ISSUE THREAD

**Issue by vsub21** [mkleehammer/pyodbc#272]
### Environment

- Python: 3.5.1
- pyodbc: 4.0.17
- OS: Ubuntu 16.04, Windows 10
- DB: Microsoft SQL Server 2012
- driver: OBDC Driver 13 for SQL Server

### Issue

My company enters usernames in the format of '[domain]\[username]' with a single backslash between the domain and the username. I found that when I try to pyodbc.connect() with the proper connection string where I enter any of these three:

r"UID=[domain]\[username]"
'''UID=[domain]\[username]'''
"UID=[domain]\\[username]"

I receive an error stating "Login failed for [domain]\\[username]", where the backslash has been converted to a double backslash. Is there a way to correct or account for these types of authentication systems? Connection for single backslash [domain]\[username] systems is supported by pymssql and I believe many companies use a similar system for usernames.'

Is it perhaps an issue with SQLDriverConnect? I checked the documentation for SQLDriverConnect in MSDN where it states:

"Because of connection string and initialization file grammar, keywords and attribute values that contain the characters []{}(),;?*=!@ not enclosed with braces should be avoided. The value of the DSN keyword cannot consist only of blanks and should not contain leading blanks. Because of the grammar of the system information, keywords and data source names cannot contain the backslash (\) character."

The solution to my problem was to use a dev SQL Server without proper authentication (given a service account with no backslash), but this would not work in production. I believe this issue should be addressed -- any ideas?

**Comment by gordthompson** [comment]
The doubling of the backslash is simply a display artifact:

```
>>> r'WEEZER\gord'
'WEEZER\\gord'
>>>
```

As for the login failing, I'm fairly certain that the Linux flavour of the "ODBC Driver xx for SQL Server" only supports Windows authentication via [Kerberos](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication#using-integrated-authentication-to-connect-to-includessnoversionincludesssnoversionmdmd-from-an-odbc-application).

**Comment by vsub21** [comment]
Are you sure about that? I tried to a development server using credentials that did not require the [domain]\[username] format (just had a username with no special characters) and I was able to connect properly -- can't do for production though because of security issues I need to use a [domain]\[username] account.

**Comment by gordthompson** [comment]
Does the development server have SQL Server Authentication mode enabled? Normally, logins for SQL Server Authentication use "plain" usernames (like `sa`), while logins for Windows Authentication are defined as `domain\username`.

**Comment by v-chojas** [comment]
The UID/PWD keywords are for SQL Server Authentication which uses a completely independent set of credentials from Windows logins etc. When using Windows Integrated Authentication, although usernames are effectively of the form DOMAIN\user or COMPUTER\user, it is not explicitly specifiable since the "integrated" means it automatically uses the credentials of the current user context. If you are using integrated authentication, then specify `Trusted_Connection=Yes` in the connection string instead of UID/PWD.

**Comment by vsub21** [comment]
@gordthompson Yes, it does have SQL Server Authentication mode enabled. I have tried the "plain" username (without the domain in the front) and the domain\username format, and neither have worked.

@v-chojas  I believe I do not have integrated authentication due to the fact I am running pyodbc on Ubuntu 16.04 within a Docker for Mac container and I have also tried this within the bash shell on Mac as well. Since I am not using a Windows machine, and there are no Windows credentials associated with the current user context, how would I go about running this using Windows credentials?

**Comment by v-chojas** [comment]
If you are using credentials for SQL Server authentication (which are different from Windows/domain credentials), then ensure that any other special characters in your username and/or password are escaped correctly in the connection string.

If you wish to use Integrated authentication on Linux or Mac using Kerberos, please see https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication for more information.

**Comment by gordthompson** [comment]
This is not really a pyodbc issue. pyodbc essentially just passes the connection string parameters along to the ODBC driver, and it is up to the driver to interpret them as it sees fit. As far as I know, neither "msodbcsql (for Linux)" nor "FreeTDS_ODBC" support the passing of Windows credentials from a Linux box to an instance of SQL Server, except via Kerberos.

If you need to connect to the production server from Linux then you really probably should set up Kerberos. However, you *might* be able to connect using the jTDS JDBC driver if you ...

- download "jtds-1.3.1.jar" from [here](https://sourceforge.net/projects/jtds/files/),
- install a Java Runtime Environment (e.g., `sudo apt install default-jre`),
- install JayDeBeApi via `pip`

... and then use code like this

```python
import jaydebeapi
cnxn = jaydebeapi.connect(
    "net.sourceforge.jtds.jdbc.Driver",
    "jdbc:jtds:sqlserver://192.168.1.114:49242/myDb;DOMAIN=DOMAIN_NAME",
    ["gord", "myWindowsPassword"],
    "/home/gord/.m2/repository/net/sourceforge/jtds/jtds/1.3.1/jtds-1.3.1.jar"
    )
crsr = cnxn.cursor()
crsr.execute("SELECT SYSTEM_USER AS me")
print(crsr.fetchone()[0])
```

**Comment by mkleehammer** [comment]
So, should this be closed?
