### ISSUE TITLE
Unable to install pyodbc on Windows 10 using Bash for windows

### ISSUE THREAD

**Issue by ryan-z-johnson** [mkleehammer/pyodbc#273]
- Python: 2.7 
- pyodbc: 4.0.17 
- OS: 64bit windows
- DB: MSSQL
- driver:Microsoft ODBC Driver 13 for Linux 
### Issue

I am trying to install pyodbc and receive the falling error on install:
![image](https://user-images.githubusercontent.com/29990023/29398102-6101d192-82d7-11e7-997d-2031864146d0.png)
I have also attempted to install with windows odbc drivers as well. No luck

**Comment by gordthompson** [comment]
> src/pyodbc.h:45:20: fatal error: Python.h: No such file or directory

The pyodbc build procedure cannot find the Python header files. If you are trying to install pyodbc for Python27 you need to

```
sudo apt install python-dev
```
