### ISSUE TITLE
sql update speed is slower than v3.1.1?

### ISSUE THREAD

**Issue by ChuanPoLee** [mkleehammer/pyodbc#274]
### Environment
- Python: 2.7.13
- pyodbc: 4.0.17
- OS: windows server 2008 R2 x64
- DB: SQL server
- driver: sql server native client 10.0

### Issue
Dear mkleehammer:
    I used pyodbc v3.1.1 in a stable situation. Today, I upgrade pyodbc with pip install --upgrade pyodbc. After this upgrade, I found that the speed of data insert and update became slow. For instance, I have a procedure that parse text file and insert into database, in pyodbc v3.1.1 it takes about 20seconds. but in pyodbc v4.0.17 it ran over 40 seconds. The text files are same in both situation. and I switched two versions many times, and get the same result.
    Any idea?

**Comment by gordthompson** [comment]
I haven't found v4.x to be noticeably slower than v3.x. Can you provide a [Minimum, Complete, and Verifiable Example](https://stackoverflow.com/help/mcve) to reproduce the difference in performance that you are experiencing?

**Comment by v-chojas** [comment]
- When posting Python code, be sure to preserve indentation.
- You can post an ODBC trace for both versions, so they can be compared to determine the difference more quickly. See https://docs.microsoft.com/en-us/sql/odbc/admin/setting-tracing-options for more information.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
