### ISSUE TITLE
Query with Application Resource Locks Terminated during Processing

### ISSUE THREAD

**Issue by Betulaphobe** [mkleehammer/pyodbc#277]
### Environment

- Python: 3.6.1 (32-bit), 3.4.3
- pyodbc: 4.0.17, 4.0.16
- OS: Windows, Linux
- DB: SQL Server 2012, SQL Server 2016
- driver: ODBC Driver 13 for SQL Server, ODBC Driver 11 for SQL Server, SQL Server Native Client 11.0

### Issue

I have a stored procedure that takes in a list of identifiers and then deletes those identifiers' data from a series of about thirty tables. In my context, it's very possible that multiple copies of this stored procedure could be running concurrently (working on different identifiers), or that other stored procedures writing to those same thirty tables will be running at the same time (again, with different identifiers). In order to avoid deadlocks from table-level locks taken out by the delete statements and the other procedures trying to run, I wrapped every delete statement in this stored procedure in an application resource lock. It looks something like the below.

```SQL
CREATE PROCEDURE [dbo].[deleteData] @IDs dbo.IDTableType READONLY
AS
BEGIN

DECLARE @result INT;

EXEC @result = sp_getapplock @Resource = 'MyTable1', @LockOwner = 'Session', @LockMode = 'Exclusive';
DELETE FROM mydb.dbo.MyTable1 WHERE ID in (SELECT ID FROM @IDS);
EXEC @result = sp_releaseapplock @Resource = 'MyTable1', @LockOwner = 'Session';

EXEC @result = sp_getapplock @Resource = 'MyTable2', @LockOwner = 'Session', @LockMode = 'Exclusive';
DELETE FROM mydb.dbo.MyTable2 WHERE ID in (SELECT ID FROM @IDS);
EXEC @result = sp_releaseapplock @Resource = 'MyTable2', @LockOwner = 'Session';

--... (etc) ...

EXEC @result = sp_getapplock @Resource = 'MyTable30', @LockOwner = 'Session', @LockMode = 'Exclusive';
DELETE FROM mydb.dbo.MyTable30 WHERE ID in (SELECT ID FROM @IDS);
EXEC @result = sp_releaseapplock @Resource = 'MyTable30', @LockOwner = 'Session';
END
```
I execute the stored procedure through something like the following python script:

```python
import pyodbc

connection_string = 'Driver=ODBC Driver 13 for SQL Server;ApplicationIntent=ReadWrite;MultiSubnetFailover=No;' \
                            'Trusted_Connection=yes;Server=localhost;Database=mydb'
db_handle = pyodbc.connect(connection_string, autocommit=True)

query = 'DECLARE @IDs [dbo].IDTableType; ' \
          'INSERT INTO @IDs (ID) VALUES (1) ' \
          '{call [mydb].[dbo].deleteData(@IDs)};'
print('SQL DELETE QUERY:\n%s' % (query))
db_handle.execute(query)
```

When I run the following statement through pyodbc, the stored procedure winds up getting terminated partway through processing. So, I'll wind up with a number of the tables having their data cleared out and a number not. The number not cleared out isn't always the same, but it's never zero, so re-running the query numerous times never achieves the intended result. Perhaps worth noting, is that pyodbc doesn't fail or anything; the SQL statement's execution is aborted, but my python program continues to run fine (perhaps because I'm not capturing and examining some output...).

Intriguingly, if I remove the application resource lock blocks from around the delete statements in the stored procedure, pyodbc runs it to completion, as I expect. Also, just running the procedure (with the applock blocks) directly in SQL Server Management Studio works as I'd expect, as does running the stored procedure through other connections, like Perl's DBI module. I'm mostly curious as to whether I'm doing something wrong in my use of pyodbc, or whether this might actually be some bug. I've had a hard time finding relevant-looking problems and documentation in searches over the past couple days.

**Comment by v-chojas** [comment]
This may be due to session environment differences between the ODBC driver as it is used by pyODBC, and SSMS (which uses the .NET `SqlClient`). One of the reasons for a statement being terminated in processing is if a deadlock is detected, which leads me to ask what values do sp_getapplock / sp_releaseapplock return? Is [`@@LOCK_TIMEOUT`](https://docs.microsoft.com/en-us/sql/t-sql/functions/lock-timeout-transact-sql) set, and if so, to what value?

You can provide an ODBC trace (instructions for [Windows](https://docs.microsoft.com/en-us/sql/odbc/admin/setting-tracing-options) and [Linux, Mac](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/data-access-tracing-with-the-odbc-driver-on-linux)) to more clearly determine the cause, which will include any error/warning messages the ODBC driver and SQL Server emit.

**Comment by Betulaphobe** [comment]
Bear in mind that the same [correct] behavior is exhibited by perl's DBI module for me as in SSMS, so if it's an environmental difference, I don't think it depends on the driver, because DBI and pyodbc are using the same driver. The connection strings I'm using for the two drivers look as below:

```python
connection_string = 'Driver=ODBC Driver 13 for SQL Server;ApplicationIntent=ReadWrite;MultiSubnetFailover=No;' \
                            'Trusted_Connection=yes;Server=MYPC;Database=mydb'
db_handle = pyodbc.connect(connection_string, autocommit=True)
```

```perl
$db_handle = DBI->connect("dbi:ODBC:driver={ODBC Driver 13 for SQL Server};server=MYPC;database=mydb;Trusted_Connection=yes;", undef, undef, {PrintError => 1}) or die "Couldn't connect to database.\n";
```

I do not know what sp_getapplock and sp_releaseapplock return, exactly, in this particular case - I have not experimented with logging to capture their outputs yet. A deadlock seems unlikely to me, considering that each application resource lock we're using is distinct from the next one in the statement, that these were implemented specifically to avoid automatic deadlocks, and lastly because, again, they work fine through other modules. However, perhaps this would be a good place to look next.

@@LOCK_TIMEOUT is not set, which means that the default is no timeout. I've experimented with this, giving it intentionally large values, and it's had no effect on the issue.

I've been doing testing with traces directly through the ODBC Administrator (as you mentioned) on Windows, and also through SQL Server Profiler 2016. The SQL Server Profiler 2016 tracing hasn't yielded much useful output - I can see the statements begin and end, but they just always end with "2 -
 Abort." On the other hand, I can't quite make heads or tails out of the logs from the ODBC administrator, although the lines that I believe indicate execution of the stored procedure look fishy:

```
my_script_name abc-25d3	ENTER SQLExecDirectW 
		HSTMT               0x002AE0C8
		WCHAR *             0x02A35038 [    9385] ""
		SDWORD                  9385

my_script_name abc-25d3	EXIT  SQLExecDirectW  with return code 0 (SQL_SUCCESS)
		HSTMT               0x002AE0C8
		WCHAR *             0x02A35038 [    9385] ""
		SDWORD                  9385
```
because it contrasts with how executing other statements in my script looks, where the script is actually present:

```
my_script_name abc-25d3	ENTER SQLExecDirectW 
		HSTMT               0x002AE0C8
		WCHAR *             0x00548B20 [      89] "UPDATE [mydb].[dbo].[MyTable30] SET Status = 0 WHERE ID IN (1);"
		SDWORD                    89

my_script_name abc-25d3	EXIT  SQLExecDirectW  with return code 0 (SQL_SUCCESS)
		HSTMT               0x002AE0C8
		WCHAR *             0x00548B20 [      89] "UPDATE [mydb].[dbo].[MyTable30] SET Status = 0 WHERE ID IN (1);"
		SDWORD                    89
```

I think this might be a difference between the way that pyodbc handles "batches" of statements rather than single statements. This thought comes from how DBI handles those two things separately, only doing a "SQLBatch" (according to the Profiler) for the multi-statement statements, and instead running single-statement commands through a stored procedure. Also, the above blank ("") contrasts with [perl's] DBI's execution, which I've traced, and shows the full statement (although with a "UCHAR *" instead of a "WCHAR *;" I'm unfamiliar with these terms' meanings):

```
perl  my_script abc-25d4	ENTER SQLPrepare 
		HSTMT               0x0000000002B19FF0
		UCHAR *             0x0000000002B0AFB8 [      -3] "\ a                DECLARE @IDs [dbo].IDTableType;\ a                INSERT INTO @IDs (ID)\ a                 VALUES (1);\ a                {call [mydb].[dbo].deleteData(@IDs)};\ a              \ 0"
		SDWORD                    -3

perl  my_script abc-25d4	EXIT  SQLPrepare  with return code 0 (SQL_SUCCESS)
		HSTMT               0x0000000002B19FF0
		UCHAR *             0x0000000002B0AFB8 [      -3] "\ a                DECLARE @IDs [dbo].IDTableType;\ a                INSERT INTO @IDs (ID)\ a                 VALUES (1);\ a                {call [mydb].[dbo].deleteData(@IDs)};\ a              \ 0"
		SDWORD                    -3

perl  my_script abc-25d4	ENTER SQLExecute 
		HSTMT               0x0000000002B19FF0

perl  my_script abc-25d4	EXIT  SQLExecute  with return code 0 (SQL_SUCCESS)
		HSTMT               0x0000000002B19FF0
```
I have, unfortunately, not seen any obvious errors or warnings popping up through any traces that I've done, so I'm still somewhat at a loss of where to look for clues.

**Comment by v-chojas** [comment]
After thinking about this a bit more and studying how DBI uses the ODBC API, I believe the behaviour you're seeing is [because you haven't consumed all the resultsets the stored procedure generated](https://github.com/mkleehammer/pyodbc/issues/262). The reason why it seems to work without the locks is because there are fewer resultsets generated than will fill the write buffer, and why it works with the locks in SSMS and DBI is because they automatically read all the generated resultsets. To test this theory, you can (recommended) add [`SET NOCOUNT ON`](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-nocount-transact-sql) inside your SP at the beginning --- before all the other statements, and/or add this after the execute to read all the pending resultsets (you will have to use cursor.execute() to get an explicit cursor handle):

```
while cursor.nextset():
    pass
```

**Comment by Betulaphobe** [comment]
Thank you tremendously for pointing me at that documentation, both of the former issue and of SET NOCOUNT ON! I did look at that issue before, and read through all its discussion, but decided it probably wasn't the same issue, because I had a "fix" (removing the application resource locks), and didn't consider that they would be adding to the result counts. This was a bad oversight...

Anyway, I implemented the SET NOCOUNT ON approach, and everything appears to be working great.

Would you recommend that I do both approaches in the future, the SET NOCOUNT ON in the stored procedure, as well as the "cursor.nextset() pass" in the python script? Or do you think just the first approach will suffice? I understand that stylistically, it might make sense to do the latter, particularly if there's ever a procedure that of course needs SET NOCOUNT OFF. So, perhaps I should just make a note of both and when to use either.

**Comment by v-chojas** [comment]
Good to hear that you have resolved the issue.

SET NOCOUNT ON is recommended in general if you do not need the information that it would otherwise provide (number of affected rows), and can actually enhance performance by reducing network traffic.

I would say that nextset() is not only recommended, but obligatory whenever you execute statements which can generate multiple results; as your issue has shown, the client needs to consume all the results generated, to prevent the server from filling up its write buffer.

**Comment by mkleehammer** [comment]
Great job @v-chojas.  Thanks.
