### ISSUE TITLE
Paypal - Beer?

### ISSUE THREAD

**Issue by nutztherookie** [mkleehammer/pyodbc#28]
OMG THANK YOU! :+1: 

I'm trying to get odbc working with Informix (and python3.4 on linux 64bit).

With version 3.0.7 I got 
('t\x00e\x00s\x00t\x00b\x00r\x00a\x00i\x00n\x00', 'i\x00n\x00f\x00o\x00r\x00m\x00i\x00x\x00', 's\x00p\x00', 's\x00p\x00_\x00n\x00r\x00', ... 
for a `cur.columns`.
And trying to run `cursor.execute('...')` would throw the funniest charset-Informix-bugs.

Anyways. I just realized you had a github-repo, which is newer and it fixed _all_ my problems. 
**nerdgasm**
Do you have a paypal-link, so I can buy you a beer? :)

**Comment by mkleehammer** [comment]
I hope things are still working with 3.0.10.  I appreciate the offer but I don't have a link.  Good luck.
