### ISSUE TITLE
V 4.0 release note has bad unicode documentation link

### ISSUE THREAD

**Issue by HHest** [mkleehammer/pyodbc#282]
Hello. This release note https://github.com/mkleehammer/pyodbc/releases/tag/4.0.0 provides a bad link to the  "Unicode documentation". Could you please fix? Thank you.

**Comment by v-chojas** [comment]
The documentation [has moved](https://github.com/mkleehammer/pyodbc/commit/28af951e05ba84d8c100b083958f7d05b4239078) since then; I believe this is what you're looking for:
https://github.com/mkleehammer/pyodbc/wiki/Unicode

**Comment by HHest** [comment]
Thank you very much.

**Comment by mkleehammer** [comment]
I also updated the the release notes.  Thanks.
