### ISSUE TITLE
error in column name of cursor_description

### ISSUE THREAD

**Issue by among29** [mkleehammer/pyodbc#285]
Python 3.5
pyodbc (4.0.17)
database: informix
in windows ，it work well.

but in linux,  
` self.cnxn = pyodbc.connect('DSN=%s' % DSN, ansi=True, timeout=2)
ENC='gbk'
self.cnxn.setencoding(encoding=ENC)
self.cnxn.setdecoding(sqltype=pyodbc.SQL_CHAR, encoding=ENC)
self.cnxn.setdecoding(sqltype=pyodbc.SQL_WCHAR, encoding=ENC)`
sql = "select * from sysmaster:sysdbslocale"
cursor = self.cnxn.cursor()
cursor.execute(sql)
case = cursor.fetchone()
 print(case)
print(case.cursor_description)
rst = dict()
collist = [ls1[0] for ls1 in case.cursor_description]
 print(collist)
 for x in collist:
       print(x)
`

result output:
(('d\x00b\x00s\x00_\x00d\x00b', <class 'str'>, None, 128, 128, 0, True), ('d\x00b\x00s\x00_\x00c\x00o', <class 'str'>, None, 32, 32, 0, True))
['d\x00b\x00s\x00_\x00d\x00b', 'd\x00b\x00s\x00_\x00c\x00o']
dbs_db
dbs_co

d\x00b\x00s\x00_\x00d\x00b :  this true value is: dbs_dbsname
d\x00b\x00s\x00_\x00c\x00o :  this true value is: dbs_collate

**Comment by gordthompson** [comment]
Further to comment from @v-chojas it looks like you also need to specify

```python
self.cnxn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-16le')
```

**Comment by among29** [comment]
cnxn = pyodbc.connect('DSN=%s;UID=%s;PWD=%s' % (DSN, UID, PWD), timeout=2)
cnxn.setdecoding(sqltype=pyodbc.SQL_CHAR, encoding='gbk')
cnxn.setdecoding(sqltype=pyodbc.SQL_WCHAR, encoding='gbk')
cnxn.setencoding(encoding='gbk')
if platform.system() != 'Windows':
	cnxn.setdecoding(sqltype=pyodbc.SQL_WMETADATA, encoding='utf-32le')
cursor = cnxn.cursor()
cursor.execute(sql)

Now，it‘s OK。

Thanks All
