### ISSUE TITLE
Executing queries with parameters: Amazon Redshift

### ISSUE THREAD

**Issue by fabiopicchi** [mkleehammer/pyodbc#288]
### Environment

- Python: Python 3.6.1 :: Anaconda custom (64-bit)
- pyodbc: 4.0.17-py36_0
- OS: Debian 9 Stretch
- DB: Redshift
- driver: Amazon Redshift driver downloaded from http://docs.aws.amazon.com/redshift/latest/mgmt/install-odbc-driver-linux.html

### Issue

I can't seem to pass parameters to my stored queries. The error can be easily reproduced with a simple query:
`cursor.execute("SELECT TOP ? hash FROM opauto_homolog.opauto_offer", 1)`

Thrown exception:
`pyodbc.ProgrammingError: ('42601', '[42601] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42601] ERROR:  syntax error at or near "("\nLINE 1: SELECT TOP ($1) hash FROM opauto_homolog.opauto_offer\n                   ^\n (30) (SQLPrepare)')`

**Comment by v-chojas** [comment]
Not all datasources support parameterisation of arbitrary query expressions. For example, SQL Server requires "SELECT TOP (?)" (with the parentheses). pyODBC does not process queries nor perform parameterisation itself, and leaves this to the ODBC driver. Please consult the Redshift documentation for more information.

**Comment by fabiopicchi** [comment]
Oh, didn't know about that! Thank you :)

Couldn't find the documentation on how to use it so I am preparing the query myself with string formatting.
