### ISSUE TITLE
Python 2.6 vs pyodbc.connect(... encoding)

### ISSUE THREAD

**Issue by JodyGoldberg** [mkleehammer/pyodbc#289]
The code in https://github.com/mkleehammer/pyodbc/blob/master/src/pyodbcmodule.cpp
as of https://github.com/mkleehammer/pyodbc/commit/f0eec084db26373b774bfe22693976cf97ac90cc

has what looks like a bug in the python 2.6 state.   It generates an error on
         if (!PyString_Check(value) || !PyUnicode_Check(value))
pretty sure that should be an &&

**Comment by v-chojas** [comment]
Line 454? Yes, I think so too.

**Comment by mkleehammer** [comment]
Yikes.  Thanks.
