### ISSUE TITLE
ci session error in connectivity of php 7.0 ,codeigniter 3.1.6,sql server 2016 and xampp-win32-7.0.24

### ISSUE THREAD

**Issue by Gitanjalee-Chinchole** [mkleehammer/pyodbc#296]
I am trying to connect sql server 2016 with php 7.0 & codeigniter 3.1.6 using xampp,but I am getting the error as follows :-
Error Number: 42S02/208

[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid object name 'ci_sessions'.

SELECT "data" FROM "ci_sessions" WHERE "id" = 'ca4680ccaa1d99c9a97e4a4a8d639f7f2b9e374e'

how do I resolve this error?

**Comment by keitherskine** [comment]
You may need to include the name of the database and the schema for table `ci_sessions`, e.g.:
```
SELECT data
FROM your_database_name.dbo.ci_sessions
WHERE id = 'ca4680ccaa1d99c9a97e4a4a8d639f7f2b9e374e'
```
(the default schema name in SQL Server is `dbo`)

**Comment by v-chojas** [comment]
This is the pyODBC project. If you are using PHP, please place issues at https://github.com/Microsoft/msphpsql instead.
