### ISSUE TITLE
Connect to SQL server via MSOLAP.4

### ISSUE THREAD

**Issue by eroncastro** [mkleehammer/pyodbc#297]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.5.2
- pyodbc: 4.0.21
- OS: Ubuntu 16.04
- DB: SQL Server
- driver: ODBC Driver 13 for SQL Server

### Issue

I am trying to connect to SQL server via MSOLAP.4
I have the following tag inside a .odc file
<odc:ConnectionString>Provider=MSOLAP.4;Integrated Security=SSPI;Persist Security Info=True;Data Source=data0001;Initial Catalog=FIRST_CATALOG</odc:ConnectionString>

I was wondering if it would be possible to connect to a SQL server using the string 
**Provider=MSOLAP.4;Integrated Security=SSPI;Persist Security Info=True;Data Source=data0001;Initial Catalog=FIRST_CATALOG**

Right now, I have tried the following:

```python
import pyodbc

pyodbc.connect('DRIVER={ODBC Driver 13 for SQL Server};Provider=MSOLAP.4;Integrated Security=SSPI;Persist Security Info=True;Data Source=data0001;Initial Catalog=FIRST_CATALOG')
```
But all I get is 
```
OperationalError: ('08001', '[08001] [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Neither DSN nor SERVER keyword supplied (0) (SQLDriverConnect)')
```

Can this be accomplished?

Thanks in advance,

Eron

**Comment by v-chojas** [comment]
MSOLAP.4 is the Analysis Services _OLE DB_ provider, which is a completely different interface than ODBC and Windows-only.
