### ISSUE TITLE
Memory buildup/leak using fast_executemany

### ISSUE THREAD

**Issue by Finndersen** [mkleehammer/pyodbc#299]
Hi,
I'm using pyodbc-4.0.21 on RHEL6 with ODBC Driver 13 for SQL Server, connecting to SQLServer instance.

I'm doing a database migration by selecting records from a SQLite database and inserting into the SQLServer database. 

I'm using the fast_executemany option for increased performance, however I've noticed there's some kind of memory leak issue with it. After each bulk insert, it's as if the inserted data is retained in memory and continuously builds up until the application is killed. 

Doing nothing but turning the fast_executemany option back off solves the issue. 

I would really like to use the fast_executemany functionality because it improves speed by like 10x but is unusable with this memory buildup issue

**Comment by v-chojas** [comment]
The parameter array [should be freed](https://github.com/mkleehammer/pyodbc/blob/675189632752a05b9711b849af05e418dcda7a35/src/params.cpp#L1735)...  Do you have more details, a repro script, or perhaps Valgrind output which would make it easier to locate the leak?

**Comment by Finndersen** [comment]
I would imagine the issue would be easy to reproduce, here's the basic idea of my code:

```
with db_wrapper(args,job.log) as sqlserver_conn:
	num_batches=math.ceil(num_records/batch_size)
	for batch in range(num_batches):
		#Get records from source SQLITE daatbase
		stmt="SELECT * FROM RecordTable_{} LIMIT {} OFFSET {}".format(args.feed.upper(),batch_size,batch*batch_size)
		source_records=sqlite_conn.execute(stmt).fetchall()
		#Insert records into destination SQLServer table
		sqlserver_conn.insert_records(dest_fields,source_records,commit=False)

	sqlserver_conn.conn.commit()
```

Database wrapper class:

```
class db_wrapper(object):
	def __init__(self,args,log):
		self.log=log
		db_creds=db_config.db_credentials['etl']
		#Establish connection to event database
		self.conn=pyodbc.connect(driver='{ODBC Driver 13 for SQL Server}',server=db_config.db_address[args.site],database='DATA_{}'.format(args.feed.upper()),uid=db_creds['user'],pwd=db_creds['password'])
		self.cur=self.conn.cursor()
		self.cur.fast_executemany=False

         def insert_records(self,ordered_fields,record_dicts,batch_size=20000,commit=True):
		'''Insert list of record dictionaries into database'''
		
		placeholders=','.join(['?']*len(ordered_fields))
		#Convert list of record dictionaries to list of ordered lists
		record_lists=[[record[fieldname] for fieldname in ordered_fields] for record in record_dicts]
                #Insert records into table
		self.cur.executemany('INSERT INTO staging VALUES ({})'.format(placeholders),record_lists)
```

Simply changing self.cur.fast_executemany=False to self.cur.fast_executemany=True causes the issue

I can post a valgrind result in a bit

**Comment by Finndersen** [comment]
Here's result. Not sure if this is the right output, I havent used Valgrind before

fast_executemany=True

```
==11910== HEAP SUMMARY:
==11910==     in use at exit: 138,281,234 bytes in 1,002,342 blocks
==11910==   total heap usage: 16,051,111 allocs, 15,048,769 frees, 2,311,878,961 bytes allocated
==11910==
==11910== LEAK SUMMARY:
==11910==    definitely lost: 0 bytes in 0 blocks
==11910==    indirectly lost: 0 bytes in 0 blocks
==11910==      possibly lost: 5,352 bytes in 10 blocks
==11910==    still reachable: 138,275,882 bytes in 1,002,332 blocks
==11910==         suppressed: 0 bytes in 0 blocks
==11910== Rerun with --leak-check=full to see details of leaked memory
==11910==
==11910== For counts of detected and suppressed errors, rerun with: -v
==11910== Use --track-origins=yes to see where uninitialised values come from
==11910== ERROR SUMMARY: 2242 errors from 117 contexts (suppressed: 113 from 9)
```


fast_executemany=False
```
==16448== HEAP SUMMARY:
==16448==     in use at exit: 1,591,361 bytes in 1,986 blocks
==16448==   total heap usage: 28,047,930 allocs, 28,045,944 frees, 12,739,750,406 bytes allocated
==16448==
==16448== LEAK SUMMARY:
==16448==    definitely lost: 0 bytes in 0 blocks
==16448==    indirectly lost: 0 bytes in 0 blocks
==16448==      possibly lost: 7,336 bytes in 13 blocks
==16448==    still reachable: 1,584,025 bytes in 1,973 blocks
==16448==         suppressed: 0 bytes in 0 blocks
==16448== Rerun with --leak-check=full to see details of leaked memory
==16448==
==16448== For counts of detected and suppressed errors, rerun with: -v
==16448== Use --track-origins=yes to see where uninitialised values come from
==16448== ERROR SUMMARY: 2629 errors from 109 contexts (suppressed: 104 from 9)
```

I ran the job for roughly the same number of batches but not exactly. The fast_executemany=False probably ran for a bit longer. but you can see the "in use at exit" amount is much higher for fast_executemany=True

**Comment by v-chojas** [comment]
Thanks for the information, we are currently investigating it.

**Comment by v-chojas** [comment]
I've found and fixed the leak in my branch here, please give it a try:
https://github.com/v-chojas/pyodbc/tree/fix-executemany-memleak

There is a PR for it here: https://github.com/mkleehammer/pyodbc/pull/304

**Comment by mkleehammer** [comment]
Merged.  Will be in next build today.

**Comment by gizmo93** [comment]
Hi,
where can i get pyodbc binaries for windows including this fix? Inserting 2 million rows in 10k chunks uses up to 2GB of RAM at the end :-)

**Comment by maxiuboldi** [comment]
Hi,

is this problem fix? i'm having the same issue with pyodbc 4.0.23 and ODBC Driver 13 for SQL Server...

**Comment by v-chojas** [comment]
Leave a comment The fix [is there in 4.0.23](https://github.com/mkleehammer/pyodbc/blob/4.0.23/src/params.cpp#L1739), unless you are referring to a different leak?

**Comment by maxiuboldi** [comment]
Hi, thanks for your reply. I really don't know, i'm inserting 10 million rows in 10k chunks with fast_executemany=True and the memory uses up to 4GB of RAM. if i set fast_executemany=False fix the issue, but i need the feature... it's seems to be the same problem, but maybe it's a different leak...

**Comment by v-chojas** [comment]
Please open a new issue with the details, it could be a different leak but won't know for sure until the details (version, schema, etc.) are provided.

Note that fast_executemany does use more memory than not, since it has to allocate the whole parameter array to send at once (and that's where it gets its speed).

**Comment by maxiuboldi** [comment]
Hi, again, thanks for your reply. if i insert rows in 5K chunks, it's normal again. I wil test more before open a new issue. Maybe it's my problem. Sorry for the inconvenience.
