### ISSUE TITLE
('HY000', '[HY000] [Microsoft][ODBC SQL Server Driver]Connection is busy with results for another hstmt (0) (SQLExecDirectW)')

### ISSUE THREAD

**Issue by dalalkrish** [mkleehammer/pyodbc#300]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit: 

- Python: 3.6.0 (64-bit)
- pyodbc: 4.0.17
- OS: Windows 10
- DB: 
- driver: SQL Server

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
I am getting following error trying to read data from SQL server into pandas data frame:

> pandas.io.sql.DatabaseError: Execution failed on sql 'select distinct top 500000 * from dbo.KrishAnalyticsAllCalls': ('HY000', '[HY000] [Microsoft][ODBC SQL Server Driver]Connection is busy with results for another hstmt (0) (SQLExecDirectW)')

I had executed the function with a SQL Query before and interrupted the execution with ctrl+k as I wanted to make a change in the function. Now, after making the change when I'm trying to execute the function I am getting the above error. I have shut down the Python Shell from where I was running the previous Query.

 How should I kill this "Zombie" connection?

**Comment by v-chojas** [comment]
The error message suggests that you have only one connection, but are attempting to use another statement on it while it is still executing a previous one.

pyodbc 4.0.21 [adds support for cursor.cancel()](https://github.com/mkleehammer/pyodbc/issues/158), and will let you cancel executing queries. If you cannot use this version of pyodbc, then your application will have to handle the cancellation itself, by making new connections or using the [MARS](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars) feature (note: use of MARS may reduce performance, especially on connections with low bandwidth and high latency.)

**Comment by nomadavid9** [comment]
cursor.close() did the job for me, using Pyodbc 4.0.30
