### ISSUE TITLE
Invalid precision exception raised when binding on numeric(12,5) columns for some values

### ISSUE THREAD

**Issue by isosphere** [mkleehammer/pyodbc#302]
### Environment

- Python: 3.6.3 (64 bit)
- pyodbc: 4.0.21
- OS: Windows 10 64-bit
- DB: Microsoft SQL Server 2012 Express
- driver: SQL Server Native Client 11.0 (64 bit)

### Issue
```
import pyodbc 
from decimal import Decimal

cnxn = pyodbc.connect('DSN=Datasource')
cursor = cnxn.cursor()

for testval in (Decimal(8550123.2), Decimal(85000.2)):
    print("Testing with value: '%s'" % testval)
    cursor.execute(
        "SELECT * FROM [table] WHERE [table].[value] = ?",
        testval
    )

    row = cursor.fetchone()
    if row:
        print(row)
    else:
        print("Executed successfully, but no results.")
```

[table].[value] is a numeric(12, 5) not null

Expected result:
```
Testing with value: '8550123.1999999992549419403076171875'
Executed successfully, but no results.
Testing with value: '85000.199999999997089616954326629638671875'
Executed successfully, but no results.
```

Observed result:
```
Testing with value: '8550123.1999999992549419403076171875'
Executed successfully, but no results.
Testing with value: '85000.199999999997089616954326629638671875'
Traceback (most recent call last):
  File "pyodbc_bug_reproduce.py", line 12, in <module>
    testval
pyodbc.Error: ('HY104', '[HY104] [Microsoft][SQL Server Native Client 11.0]Invalid precision value (0) (SQLBindParameter)')
```

Any assistance is appreciated! I haven't given up on troubleshooting within pyodbc, though it may take me a long time to run this to ground alone.

**Comment by v-chojas** [comment]
From the [decimal documentation](https://docs.python.org/3/library/decimal.html)

> If value is a float, the binary floating point value is losslessly converted to its exact decimal equivalent. This conversion can often require 53 or more digits of precision. For example, Decimal(float('1.1')) converts to Decimal('1.100000000000000088817841970012523233890533447265625').

The precision of a numeric value in SQL Server can be at most 38. Observe that the closest exact floating-point representation of 8550123.2 requires only 35 digits of precision, while that of 85000.2 requires 41 digits, hence the error.

**Comment by isosphere** [comment]
Would it be reasonable for us to address this by rounding decimals to 35 digits when interacting with SQL Server?

**Comment by v-chojas** [comment]
The whole point of using Decimal datatype is to be exact, so I would consider this a by-design behaviour. To avoid the error, you can either give the exact value as strings to Decimal constructor,
```
for testval in (Decimal('8550123.2'), Decimal('85000.2')):
```
or use floating point datatype directly:
```
for testval in (8550123.2, 85000.2):
```

**Comment by isosphere** [comment]
Interesting!

I've fixed this problem for me by using float directly instead in python and also using the float type in my database. Thank you!

I added a note in the "Tips and Tricks by Database Platform" wiki in case someone else runs into this, feel free to remove if that was inappropriate.

I'm coming at this problem via django-pyodbc-azure which is a Microsoft SQL Server specific database engine for Django. I suppose since that module supports the decimal.Decimal type and it is specific to Microsoft SQL Server, then perhaps it would be best for it to handle this idiosyncrasy one way or another.

I'll close this issue and proceed in that direction. I'm an outsider for both projects so please feel free to correct me if I'm misguided.
