### ISSUE TITLE
DSN-less connection not working on OS X

### ISSUE THREAD

**Issue by pasiorovuo** [mkleehammer/pyodbc#303]
### Environment

- Python: Python 3.6.3 (installed via homebrew, running in a virtualenv)
- pyodbc: 4.0.21
- OS: OS X El Capitan 10.11.6
- DB: MS SQL Server (Microsoft SQL Azure (RTM) - 12.0.2000.8)
- driver: Microsoft ODBC Driver 13 for SQL Server

### Issue

With connection string `DRIVER={ODBC Driver 13 for SQL Server};SERVER=host-name;PORT=1433;DATABASE=database-name;UID=user-name;PWD=password` an error is thrown:

```
Traceback (most recent call last):
  File "app.py", line 67, in <module>
    print( 'pyodbc: {t}'.format( t = timeit.timeit( stmt = try_pyodbc, number = 5 ) ) )
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/timeit.py", line 233, in timeit
    return Timer(stmt, setup, timer, globals).timeit(number)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "app.py", line 43, in try_pyodbc
    autocommit = False
pyodbc.InterfaceError: ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found, and no default driver specified (0) (SQLDriverConnect)')
```

If I add a DSN to the connection string: `DRIVER={ODBC Driver 13 for SQL Server};SERVER=host-name;PORT=1433;DATABASE=database-name;UID=user-name;PWD=password;DSN=DUMMYDSN` no error is thrown. /usr/local/etc/odbc.ini contains only:

```
[DUMMYDSN]
Driver = ODBC Driver 13 for SQL Server
```

I have a test script which executes the same connection string with both **pyodbc** and **pypyodbc** and only **pyodbc** fails if DSN is not present. This leads me to think the issue could be in **pyodbc** rather than UnixODBC.

**Comment by v-chojas** [comment]
[Enable ODBC tracing](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/data-access-tracing-with-the-odbc-driver-on-linux) and compare the connection strings that pyodbc and pypyodbc use.

**Comment by pasiorovuo** [comment]
I can't see the full string as it gets truncated, but the main difference seems to be that **pyodbc** starts with `Str In = [connectString=DRIVER={ODBC Driver 13 for SQL Server};` and **pypyodbc** with `Str In = [DRIVER={ODBC Driver 13 for SQL Server};`. Note the `connectString=` part.

**Comment by v-chojas** [comment]
Please post the fragment of Python which illustrates the way in which you are connecting with pyodbc.

**Comment by pasiorovuo** [comment]
```python
conn_params = {
    'DRIVER': '{ODBC Driver 13 for SQL Server}',
    'SERVER': 'xxxxx-xxxxx-xxxxxxxx.database.windows.net',
    'PORT': '1433',
    'DATABASE': 'xxxxx-xxxxxxxx-xxxx',
    'UID': 'xxxxx-xxxxxxxxxx-xxxxxx',
    'PWD': 'xxxxxxxxxxxxxxxx',
}

def try_pyodbc2():
    conn = pyodbc.connect(
        connectString = ';'.join( ['='.join( (k, v) ) for k, v in conn_params.items()] ),
        autocommit = False
    )
    run_q( conn, 'select * from mobile_item_search_v1( ? )', ( '208', ), 5 )
    conn.close()

```

Just realized that the issue is in `connectString =` named parameter which - I'm not sure why - does not throw an error but gets added to the string. If I remove it, it works.

Might not be an issue in **pyodbc** after all. Just different behavior.

**Comment by v-chojas** [comment]
[Yes, connect() processes named parameters as described here in the documentation.](https://github.com/mkleehammer/pyodbc/wiki/Module#connect) The erroneous `connectString` keyword hides the `DRIVER` keyword, in fact causing the driver manager to parse it as a key of `connectString` with a value of `DRIVER={ODBC Driver 13 for SQL Server}`.

**Comment by Slowly** [comment]
> With connection string `DRIVER={ODBC Driver 13 for SQL Server};SERVER=host-name;PORT=1433;DATABASE=database-name;UID=user-name;PWD=password` an error is thrown:

> If I add a DSN to the connection string: `DRIVER={ODBC Driver 13 for SQL Server};SERVER=host-name;PORT=1433;DATABASE=database-name;UID=user-name;PWD=password;DSN=DUMMYDSN` no error is thrown. 

right, it appears that pyodbc does NOT support dsn-less connections because I've googled and googled for hours on this and everybody in the world that uses pyodbc uses local DSNs that are not shareable. Not even the documentation here is complete enough about this issue.

**Comment by v-chojas** [comment]
If you are experiencing problems please open a new issue, as explained above the OP had the wrong syntax in the connection string.

**Comment by Slowly** [comment]
OK...my windows 10 x64 ODBC administrator applet can connect using the file dsn to the server OK, but if I then use the file dsn in the pyodbc connect function it generates an error. Could you as a developer of the module give me some hints as to where I could look to find out what pyodbc is having an issue with? for example, on the windows platform does it look for windows environment variables containing proxy information and generates an exception if it doesn't find them?

Thank you for your time I know you are very busy, as am I 🙂


John Bonifas

Software Engineer, Salt River Project

MS Applied Geospatial Science, Northern Arizona University

BS Geography, Arizona State University Tempe Campus

BS Applied Computing, Arizona State University West Campus

(480) 815-0679
https://www.linkedin.com/in/johnbonifas/
https://github.com/jbb26354?tab=repositories
http://www.deckerd26354.net/sites/blog/
https://www.hackerrank.com/jb3379
http://www.deckerd26354.net/sites/AboutMeLocal/
http://www.deckerd26354.net/sites/shared/resume/
<https://www.hackerrank.com/jb3379>

________________________________

**Comment by v-makouz** [comment]
@Slowly 
Can you open a new issue and provide a repro script in python, as well as the error output?

**Comment by Slowly** [comment]
I did,  with pics. Thanx :)
