### ISSUE TITLE
[unixODBC][Driver Manager]Can't open lib 'libsqliteodbc.so'

### ISSUE THREAD

**Issue by loorke** [mkleehammer/pyodbc#305]
A next code
```
import pyodbc
cnxn = pyodbc.connect('Driver=SQLite;DATABASE=testdb')
cursor = cnxn.cursor()
```
cause a following error:
```
Traceback (most recent call last):
  File "test1.py", line 4, in <module>
    cnxn = pyodbc.connect('Driver=SQLite;DATABASE=testdb')
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'libsqliteodbc.so' : file not found (0) (SQLDriverConnect)")
```
So, I can't use pyodbc with SQLite. I'm using Ubuntu 17.10. Next packages is already installed:
- unixodbc-dev
- libsqliteodbc

Can you help me with this?

**Comment by gordthompson** [comment]
Python has [built-in support for SQLite](https://docs.python.org/3/library/sqlite3.html). Is there a particular reason why you need to use pyodbc?

**Comment by loorke** [comment]
@gordthompson, I need _pyodbc_ because of _[aioodbc](https://github.com/aio-libs/aioodbc)_. I'm writing a Telegram bot and I need asynchronous port for SQLite for this, if you're interested. _[aiosqlite](https://github.com/jreese/aiosqlite.git)_ isn't good enough and have its own problems.

**Comment by gordthompson** [comment]
See if your `/etc/odbcinst.ini` file contains a driver entry like this:

```
[SQLite]
Description=SQLite ODBC Driver
Driver=libsqliteodbc.so
Setup=libsqliteodbc.so
UsageCount=1
```

If so, then try editing it to use the full path to the .so file, which will be something like this:

```
[SQLite]
Description=SQLite ODBC Driver
Driver=/usr/lib/x86_64-linux-gnu/odbc/libsqliteodbc.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libsqliteodbc.so
UsageCount=1
```

and see if that helps.

**Comment by loorke** [comment]
I got a cause of the problem. A very, very foolish mistake. I need SQLite3, so I installed SQLite3 drivers. But I forgot to change "Driver=SQLite;" to "Driver=SQLite3". Thanks for your time, anyway.
