### ISSUE TITLE
Mac OS X 10.10 - build for unixODBC

### ISSUE THREAD

**Issue by ad-lebedev** [mkleehammer/pyodbc#31]
pyodbc 3.0.7 cannot be compiled with unixODBC support on 10.10
I fixed it by myself with
```python
elif sys.platform == 'darwin':
        # OS/X now ships with iODBC.
        settings['libraries'].append('odbc')
```

but may be it's better to add some installation option or something else.

**Comment by tarkatronic** [comment]
This has presented a huge speed bump in my development process and, judging from a quick google search, it looks like many people are having to apply this same solution manually. @mkleehammer are there any plans to fix this?

**Comment by mkleehammer** [comment]
Updated in 3.0.8.  The source distribution has been pushed to PyPI, so `pip install` should work.
