### ISSUE TITLE
Support for SQL Server 2017

### ISSUE THREAD

**Issue by ChethanChandra** [mkleehammer/pyodbc#310]
I'm trying to setup a new development environment on my mac

- Development OS: MacOS 10.13.2
- Python: 3.6
- pyodbc: 4.0.21
- driver manager: unixODBC 2.3.4
-driver: FreeTDS 1.00.79
- DB: MS SQL Server 2017 Developer [Microsoft SQL Server 2017 14.0.3008.27 (X64) Developer Edition (64-bit) on Linux (Ubuntu 16.04.3 LTS)] downloaded from [https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker#pull-and-run-the-container-image](url)

### Issue
telnet to mssql-linux2017 docker image on 1433 is fine

sqlcmd fails with below error

ideally I want to do
pyodbc.connect('DRIVER=ODBC Driver 13 for SQL _Server;SERVER=localhost;PORT:1433;DATABASE=<_SOMEDB_>;UID=SA;PWD=<_myPass_>')_

[ODBC][22520][1512841146.847871][SQLGetDiagFieldW.c][815]
		Entry:
			Connection = 0x7fcbe2010c00
			Rec Number = 2
			Diag Ident = 5
			Diag Info Ptr = 0x7ffeec672b3c
			Buffer Length = -6
			String Len Ptr = 0x0
[ODBC][22520][1512841146.848022][SQLGetDiagFieldW.c][835]
		Exit:[SQL_SUCCESS]
[ODBC][22520][1512841146.848195][SQLGetDiagFieldW.c][815]
		Entry:
			Connection = 0x7fcbe2010c00
			Rec Number = 2
			Diag Ident = 6
			Diag Info Ptr = 0x7fcbe200d200
			Buffer Length = 2050
			String Len Ptr = 0x7ffeec672b40
[ODBC][22520][1512841146.848367][SQLGetDiagFieldW.c][835]
		Exit:[SQL_SUCCESS]
[ODBC][22520][1512841146.848539][SQLGetDiagFieldW.c][815]
		Entry:
			Connection = 0x7fcbe2010c00
			Rec Number = 2
			Diag Ident = 4
			Diag Info Ptr = 0x7ffeec672b44
			Buffer Length = 12
			String Len Ptr = 0x7ffeec672b40
[ODBC][22520][1512841146.848711][SQLGetDiagFieldW.c][835]
		Exit:[SQL_SUCCESS]
[ODBC][22520][1512841146.848939][SQLGetConnectAttrW.c][211]Error: SQL_INVALID_HANDLE

**Comment by cricket007** [comment]
Check this. 

https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Mac-OSX

**Comment by ChethanChandra** [comment]
Thank you! Those the steps I followed and am still somehow stuck. I wonder if its the MS SQL 2017 version thats causing, so the issue is posted in the same repo.

**Comment by ChethanChandra** [comment]
ok, my bad the docker image wasn't saved after I changed password policy and password on SQL Server 2017 Dev Edn. FreeTDS logging was enabled and this was obvious.

Still strugglign with pyodbc setup for FreeTDS, however pymssql works like charm. I don't want to use pymssql because its some code change to make.

**Comment by gordthompson** [comment]
Answered here:

https://stackoverflow.com/a/47738072/2144390

**Comment by ChethanChandra** [comment]
ok, my bad the docker image wasn't saved after I changed password policy and password on SQL Server 2017 Dev Edn. FreeTDS logging was enabled and this was obvious.

Still strugglign with pyodbc setup for FreeTDS, however pymssql works like charm. I don't want to use pymssql because its some code change to make.
