### ISSUE TITLE
Accepting numpy.int64 for SQL's BIGINT

### ISSUE THREAD

**Issue by konstantinmiller** [mkleehammer/pyodbc#312]
I'm using `pyodbc` with Microsoft SQL server.

When I call the `cursor.executemany()` method to insert some data into columns with `BIGINT` type, I'm getting the error

`pyodbc.ProgrammingError: ('Invalid parameter type.  param-index=2 param-type=numpy.int64', 'HY105')`

It's true, the parameter in question is `numpy.int64` but it's exactly the correct type for `BIGINT`. Is it the case that `pyodbc` is only accepting native types? But in this case, there is actually no way to provide an integer which is guaranteed to have 64 bits, right?

**Comment by v-chojas** [comment]
You can see [here](https://github.com/mkleehammer/pyodbc/wiki/Data-Types) for all the supported types in pyODBC.

If you wish to insert a value of at least 64 bits, then a Python 2 long integer or Python 3 integer will have enough range for it.

**Comment by konstantinmiller** [comment]
As far as I know, in Python 3 an int is not guaranteed to have 64 bits, or is it?

**Comment by v-chojas** [comment]
In Python 3, integers are arbitrary precision.

**Comment by mkleehammer** [comment]
I'm assuming this answers the question so I'm closing.  Please reopen if there is more.

**Comment by mosqueteiro** [comment]
If you are using pandas you can change the `int64` dtype to [`Int64`](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html) and pyodbc will accept it and it loads into (PostgreSQL, at least) database.

I was using [this type](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html) to deal with `pd.Series` that had nulls and were automatically being converted to `float64`. I noticed that these values would load but the default `int64` was throwing errors.

**Comment by stdkoehler** [comment]
sqlite3 has the same issue but offers a function called register_adapter:
`sqlite3.register_adapter(np.int64, int)`
Is something like that available or possible?

**Comment by CoreyBurger** [comment]
> If you are using pandas you can change the `int64` dtype to [`Int64`](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html) and pyodbc will accept it and it loads into (PostgreSQL, at least) database.

Pandas 0.25 connecting to SQL Server 2012. This is still throwing errors for me, despite converting all the numpy.int64 to Pandas Int64

**Comment by pat-hearps** [comment]
This is pretty bizarre that pyodbc cannot accept the very widely used numpy data types that are native to pandas and numpy. I strongly suggest that this be treated as a bug/insufficient functionality and addressed.
