### ISSUE TITLE
How to config connection params if I my sqlserver account is a domain account

### ISSUE THREAD

**Issue by ryang420** [mkleehammer/pyodbc#314]
Hi,
In JDBC connection, I am using **jdbc:jtds:sqlserver://abtest.mycompany.tan:1433;domain=tan** to connect sql server 2012. But in pyodbc settings, where to fill the domain name? Because I am using my company domain account to login all apps including sql server. I am using below settings to connect my db. However, I get error message "pyodbc.InterfaceError: ('28000', "[28000] [unixODBC][Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Login failed for user 'tan\\dyang1'. (18456) (SQLDriverConnect)")". Is the right place to fill domain name at the beginning of username? 

conn = pyodbc.connect(
    r'DRIVER={ODBC Driver 13 for SQL Server};'
    r'SERVER=abtest.mycompany.tan;'
    r'DATABASE=mydb;'
    r'UID=tan\dyang1;'
    r'PWD=123'
    )

**Comment by v-chojas** [comment]
If you are using Windows and SQL Server is configured for Integrated Windows Authentication, then you do not need to provide username or password since it uses the credentials of the current user automatically when you specify `Trusted_Connection=Yes` in your connection string. Please see https://github.com/mkleehammer/pyodbc/issues/272 for more information.

**Comment by ryang420** [comment]
Cool! I am using jaydebeapi. It solved my problem. Thanks a lot!

**Comment by kstohr** [comment]
Ok, but if you are on a Mac how do you specify the domain explicitly?

**Comment by v-chojas** [comment]
For Linux and Mac the domain is not specified for each connection but as part of the Kerberos configuration: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication

**Comment by zplnco** [comment]
Thank you all for being so responsive on this channel. I'm working with my colleage (kstohr); and using Username/Password for SQL Server Authentication we seem to be hitting some issues getting pyodbc.connect:
`OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')`

This occurs when using both Mac and Linux (debian & ubuntu). The reason this is curious, is we are able to authenticate from the same client using the same credentials via TSQL. 

Is there a way to see more details on the pyodbc.connection attempt, to understand where the failure is occurring? The SQL server logs are not showing any events.

**Comment by v-chojas** [comment]
You can use ODBC tracing.

If the credentials work when connecting via other means, I would suspect faulty escaping of the connection string: https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-databases

**Comment by keitherskine** [comment]
It might help to see the connection string, @zplnco (with credentials redacted of course).  I'm not sure I understand what you mean by authentication works "via TSQL".  Do you mean with Azure Data Studio, or sqlcmd, or what?

**Comment by zplnco** [comment]
Sorry if I wasn't very clear.
Here is my connection string that I'm trying:
`pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=<IP.ADDRESS>;DATABASE=<DATABASE>;UID=<DOMAIN\USERNAME>;PWD=<PASSWORD>;)`

I've tried the above string w/ and w/o postpending `Trusted_Connection=No;` without any success.

When I use the same values in from the linux command line, I am able to successfully connect:
`$ tsql -S <IP.ADDRESS> -U <DOMAIN\USERNAME> -P <PASSWORD> -d <DATABASE>`

**Comment by v-chojas** [comment]
Did you ensure to escape backslash correctly?

**Comment by zplnco** [comment]
What is the preferred method for that? 

I've tried using `\`, `\\`, as well as `%5C`, w/ and w/o raw strings.

**Comment by keitherskine** [comment]
These are just a few random ideas, sorry I can't be more definitive:
The fact that the connection request is timing out suggests pyodbc can't get through to that server at all, never mind log into the database.  This suggests a network-type issue to me.  Are you sure the relevant port is open?  It's not being blocked by some firewall?  1433 is the default SQL Server port, but 1434 is sometimes used.  The FreeTDS `tsql` utility connects using the TDS protocol, which might be using port 5000.
You could try connecting using the `isql` utility from unixODBC (which I'm assuming you already have installed on your Linux box).
Perhaps try dropping the username and password from the connection string and insert `Trusted_Connection=Yes` instead.  You might not be able to log into the database but you might at least connect to the server using your Windows account.
One last thing, perhaps try `Server=tcp:1.2.3.4,1433` (replacing 1.2.3.4 with your IP) to specify the tcp protocol and port 1433.

**Comment by alokbhatt84** [comment]
What if the **domain name** and **user name** is different than the windows login account? I am struggling with this for past couple days but unable to get any solution.

**Comment by v-chojas** [comment]
You can use `runas` command.

**Comment by kradamaker** [comment]
This is a problem with passing a single backslash fullstop.
This has nothing to do with credentials or network

**Comment by azegas** [comment]
> Sorry if I wasn't very clear. Here is my connection string that I'm trying: `pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=<IP.ADDRESS>;DATABASE=<DATABASE>;UID=<DOMAIN\USERNAME>;PWD=<PASSWORD>;)`
> 
> I've tried the above string w/ and w/o postpending `Trusted_Connection=No;` without any success.
> 
> When I use the same values in from the linux command line, I am able to successfully connect: `$ tsql -S <IP.ADDRESS> -U <DOMAIN\USERNAME> -P <PASSWORD> -d <DATABASE>`

@zplnco did you find a solution to this? I am experiencing exactly the same probelem.
