### ISSUE TITLE
Connection Error - SQLDriverConnect (Win10, py2.7.6, 64-bit)

### ISSUE THREAD

**Issue by clevernyyyy** [mkleehammer/pyodbc#318]
#### Expected behavior
Connection and subsequent iteration.  After all, I have the driver installed when I browse to `Control Panel > Administrative Tools > ODBC Data Sources (64-bit) > Drivers`.
#### Observed behavior
Error upon connection:
```
pyodbc.InterfaceError: ('IM002', u'[IM002] [unixODBC][Driver Manager]
Data source name not found, and no default driver specified (0) (SQLDriverConnect)')
```

### Code
```python
  conn = pyodbc.connect(
    r'DRIVER={ODBC Driver 13 for SQL Server};'
    r'SERVER=tcp:servername,1433;'
    r'DATABASE=database;'
    r'UID=username'
    r'PWD=password;'
  )
  cursor = conn.cursor()
  cursor.execute('SELECT * FROM [schema].[table]')

  for row in cursor:
    print('row = %r' % (row,))
```

### Environment
- Python: 2.7.6 - 64bit
- OS: Windows 10 - 64bit
- DB: MSSQL Server
- driver: ODBC Driver 13 for SQL Server

**Comment by gordthompson** [comment]
You say that you are using Windows 10, but the error message says

> [unixODBC][Driver Manager]

Are you by chance running your code under the Windows Subsystem for Linux?

**Comment by clevernyyyy** [comment]
You're correct, I'm running from Windows bash.

**Comment by gordthompson** [comment]
> I'm running from Windows bash.

Then you need to install the SQL Server ODBC driver for Linux as described [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server). WSL does not use the Windows-native ODBC drivers that appear in the Control Panel.

**Comment by clevernyyyy** [comment]
Thanks
