### ISSUE TITLE
Python 3.6 compatability with pyodbc connect and pychef

### ISSUE THREAD

**Issue by hobbitten123** [mkleehammer/pyodbc#319]
I have code that works on Python 2.7 Windows/Linux that uses both pyodbc and pychef it works ... but under Python 3.6 ... converting over .... If I import pychef ...do not even use ... then pyodbc connect breaks. If I comment out import pychef it works ... using impala db 

Python 2.7
32 bit
PyChef==0.3.0
pyodbc==4.0.17

Python 3.6
64 bit
PyChef==0.3.0
pyodbc==4.0.21

### Issue

Get the following error on 3.6 with pychef imported ...

Traceback (most recent call last):
  File "C:\pycharm_projects\micro-services_1.9Correct\lib\datalake_util\datalake.py", line 31, in _connect
    self.conn = pyodbc.connect(self.connString, autocommit=True)
pyodbc.InterfaceError: ('IM003', '[IM003] Specified driver could not be loaded due to system error  182:  (Cloudera ODBC Driver for Impala, C:\\Program Files\\Cloudera ODBC Driver for Impala\\lib\\ClouderaImpalaODBC64.dll). (160) (SQLDriverConnect)')

Otherwise works.

**Comment by hobbitten123** [comment]
It work under Linux ... but not Windows either 7 or 2012 ... 

Linux 
Python 3.6
64 bit
PyChef==0.3.0
pyodbc==4.0.21

**Comment by v-chojas** [comment]
Your ODBC driver likely uses OpenSSL libraries which conflict with PyChef.

Please see https://support.sisense.com/hc/en-us/community/posts/221224308-ODBC-driver-is-unable-to-be-loaded for a possible solution.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
