### ISSUE TITLE
Use pyodbc with SQLAlchemy / Teradata?

### ISSUE THREAD

**Issue by dclong** [mkleehammer/pyodbc#326]
Is it possible to use pyodbc with SQLAlchemy for query Teradata?

**Comment by v-chojas** [comment]
ODBC drivers for Teradata are available: https://downloads.teradata.com/download/connectivity

**Comment by dclong** [comment]
@v-chojas 
Thank you! But I'm asking about integration with SQLAlchemy.

**Comment by mkleehammer** [comment]
Closing this due to age.  I'm assuming this was asked of the SQLAlchemy group.  Please add any more information you found for others - thanks.
