### ISSUE TITLE
change datetime.date return type to string?

### ISSUE THREAD

**Issue by Omortis** [mkleehammer/pyodbc#329]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.13 (Windows 10 64-bit), 2.7.14 (Linux)
- pyodbc: 4.0.21 (Windows 10 64-bit), 3.0.7-0ubuntu2 (Linux)
- DB: SQL Server 12.0.5000
- driver: MS ODBC 13

### Issue

I have moved the codebase for a large existing python 2 project from pymssql to pyodbc. The move was easy, everything builds and runs fine, except that pyodbc returns SQL Server columns of type `time` as `datetime.date`, where pymssql (as well as the postgres native drivers) return strings.

Meaning, I receive `datetime.time(11, 54, 13, 161000)` instead of `11:54:13.161000`.  Is there any way I can change this behavior globally without resorting to a stored procedure of some sort? Handling a returned object instead of a returned string will involve several days worth of refactoring and testing.

Suggestions?

Thanks,

John

**Comment by v-chojas** [comment]
You can add an output converter to stringify data of specific types:

https://github.com/mkleehammer/pyodbc/wiki/Using-an-Output-Converter-function

**Comment by Omortis** [comment]
@v-chojas thanks, I was just reading through that (in the middle of a meeting). Will try it out, looks like exactly what I'm looking for. Receiving a `datetime.date` object will be useful later on! Let me try and will get back.

**Comment by Omortis** [comment]
The value being returned in a query (for an SQL Server column type `time(7)` is:

`(datetime.time(11, 54, 13, 161000), ... )`

For that data type, pyodbc/wiki/Data-Types provides `SQL_TYPE_TIME` and `SS_TIME2`. The datum is "passed through" using `pyodbc.SQL_TYPE_TIME` unaffected as usual, and `pyodbc.SS_TIME2`  yields an error:

`AttributeError: 'module' object has no attribute 'SS_TIME2'`

**Comment by Omortis** [comment]
@v-chojas great - thanks for the doc pointers - works like a charm!
