### ISSUE TITLE
add_output_converter trap for SQL-S datetime and datetime2

### ISSUE THREAD

**Issue by Omortis** [mkleehammer/pyodbc#331]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  2.7.13 (Windows 10 64-bit), 2.7.14 (Linux)
- pyodbc: 4.0.21 (Windows 10 64-bit), 3.0.7-0ubuntu2 (Linux)
- DB: SQL Server 12.0.5000
- driver: MS ODBC 13

### Issue

Building on [issue 329](https://github.com/mkleehammer/pyodbc/issues/329) I am having trouble trapping the SQL Server datatypes `datetime` and `datetime2`.

According to the [data-types](https://github.com/mkleehammer/pyodbc/wiki/Data-Types) wiki page the datatype for the python2 return type `datetime.datetime` is SQL_TIMESTAMP but this type is not defined in the pyodbc source. No mention of `datetime2` is made anywhere. Where are the other data types defined?

I was able to trap `datetime.time` as above with:

`    conn.add_output_converter(pyodbc.SQL_SS_TIME2, handleSQL_SS_TIME2)`

How do I trap `datetime` and `datetime2`?

`TypeError: datetime.datetime(2018, 1, 11, 11, 50, 16) is not JSON serializable`

Edit: Looking at getdata.cpp::

    case SQL_TYPE_TIMESTAMP:
        pytype = (PyObject*)PyDateTimeAPI->DateTimeType;
        break;

I can trap `datetime`.

**Comment by v-chojas** [comment]
According to [the ODBC driver documentation](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-date-time/data-type-support-for-odbc-date-and-time-improvements) (you may have to turn off stylesheets if you do not see all the columns in the table) `SQL_TIMESTAMP` is for ODBC 2.0 while 3.0 uses `SQL_TYPE_TIMESTAMP`.

`datetime` and `datetime2` both map to SQL type `SQL_TYPE_TIMESTAMP`.

**Comment by Omortis** [comment]
Ok, cool. Thanks. Interstingly, I only see `SQL_TIMESTAMP_STRUCT` here:

https://github.com/Microsoft/ODBC-Specification/blob/master/Windows/inc/sqltypes.h

I will close this issue. On a related note - Ive been all around the internet looking for the ODBC source spec and the only thing I can find is the github link above. Is there a better one?

**Comment by v-chojas** [comment]
Yes, `SQL_TIMESTAMP_STRUCT` is the correct data format for those.

Do you mean the [ODBC Programmer's Reference](https://cdn.simba.com/wp-content/uploads/2016/03/ODBC_specification.pdf)?

**Comment by Omortis** [comment]
Thanks. That from MSDN? Though I prefer the source on github ;-)

**Comment by Omortis** [comment]
The actual `unpack` format  for `SQL_TIMESTAMP_STRUCT ` is fairly arcane. A link for the full analysis is [here](https://stackoverflow.com/questions/48346046/how-do-i-unpack-a-sql-server-datetime-in-a-pyodbc-output-converter-function), in case anyone gets here via related search.
