### ISSUE TITLE
String data right truncation error when using parameterised values within an SQL function

### ISSUE THREAD

**Issue by a-musing-moose** [mkleehammer/pyodbc#336]
### Environment

- Python: 3.6
- pyodbc: 4.022
- OS: OSX (but also seen on Linux)
- DB: Informix 12.7
- driver: Informix ODBC Driver

### Issue

Given the following statement:
```
SELECT COUNT(*) as __count from my_table 
WHERE LOWER(my_table.field_name) LIKE LOWER(?)
```

When passed a params list of `("%aaaaaaaaaaaaaaa%")` I would expect a response that included a count of all rows matching the LOWERed value passed in. 

Instead I get an error from the informix ODBC driver - `[22001] [Informix][Informix ODBC Driver]String data right truncation. (-11023) (SQLPutData)`

If I replace the `?` placeholder with the hardcoded value it works as expected.

If I remove the second `LOWER` it works as expected.

If the total length of the value passed as a parameter is 16 characters or less it works as expected. 

### Additional notes:

We set have some encoding/decoding specific to our setup:

```
connection.decoding(pyodbc.SQL_WCHAR, encoding='UTF-8')
connection.setdecoding(pyodbc.SQL_CHAR, encoding='UTF-8')
connection.setencoding(encoding='UTF-8')
````

For the time being, we have downgraded to 4.0.21 which works as expected. Thanks for your efforts, any information or suggestions you can provide would be much appreciated

**Comment by v-chojas** [comment]
You can post an ODBC trace.

**Comment by mkleehammer** [comment]
Please upgrade to 4.0.23 which reverts the problematic commits from 4.0.22.
