### ISSUE TITLE
String data, right truncation

### ISSUE THREAD

**Issue by NewVadim** [mkleehammer/pyodbc#337]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.5
- pyodbc: 4.0.22
- OS: Debian 9.0 (stretch)
- DB: MSSQL 2012
- driver: {ODBC Driver 13 for SQL Server}

### Issue
I use pyodbc with aioodbc and I get the error:
```
"Traceback (most recent call last):", 
...
"  File \"/usb/src/app/server/apps/api/models/auth.py\", line 27, in get_secret_key", 
"    await self.cursor.execute(query, args)", 
"  File \"/usr/lib/python3.5/asyncio/futures.py\", line 380, in __iter__", 
"    yield self  # This tells Task to wait for completion.", 
"  File \"/usr/lib/python3.5/asyncio/tasks.py\", line 304, in _wakeup", 
"    future.result()", 
"  File \"/usr/lib/python3.5/asyncio/futures.py\", line 293, in result", 
"    raise self._exception", 
"  File \"/usr/lib/python3.5/concurrent/futures/thread.py\", line 55, in run", 
"    result = self.fn(*self.args, **self.kwargs)", 
"pyodbc.DataError: ('String data, right truncation: length 30 buffer 24', '22001')"
```
#### SQL
```
SELECT TOP 1 * FROM
    [test].[dbo].[service]
WHERE
    [test].[dbo].[service].[name] = "test";
```

**Comment by v-chojas** [comment]
That error message occurs only if you are using parameterised queries, but your SQL does not contain any parameters.

**Comment by gordthompson** [comment]
Very possibly related to #334

**Comment by VickiFu** [comment]
I have similar problem, then i found that one of column is defined as too short to take the insert value. So I re-create the table with longer length for one column and solve this problem.

**Comment by iarp** [comment]
Win 7, 10, 2008R2, 2012
Python 3.4
pyodbc 4.0.22
SQL: 2012

Failure occurs on TEXT fields no matter the length.

```
CREATE TABLE test (
    id INT PRIMARY KEY NOT NULL IDENTITY,
    data TEXT,
    tmp VARCHAR(255),
)
```

```
conn = pyodbc.connect('DRIVER={{SQL Server}};SERVER={};DATABASE={};UID={};PWD={};'.format(
    hostname, database, username, password
))
c = conn.cursor()
c.execute('INSERT INTO test (data) VALUES (?)', ('1',))
```

```
pyodbc.DataError: ('String data, right truncation: length 2 buffer 4294967294', '22001')
```

Also the following wasn't an issue before:

```
c.execute('INSERT INTO test (tmp) VALUES (?)', (609444832,))
```

but now

```
pyodbc.ProgrammingError: ('Numeric overflow', 'HY000')
```

**Comment by v-chojas** [comment]
^ Is that a 32 or 64-bit Python?

Also note that the `SQL Server` driver is extremely old (I believe it's from SQL Server 6.x) and does not support all the datatypes of newer SQL Server versions.

**Comment by iarp** [comment]
32-bit across all machines. `{SQL Server}` just happened to be in an old project that I had opened when i copied the connection example. My newer projects using `{ODBC Driver 13 for SQL Server}` were also having the same issue.

**Comment by mkleehammer** [comment]
Please upgrade to 4.0.23 which reverts the problematic commits from 4.0.22.
