### ISSUE TITLE
Fast executemany on SQL Server fails to insert more than one row at a time

### ISSUE THREAD

**Issue by pinkerltm** [mkleehammer/pyodbc#339]
### Issue
I am using fast executemany to bulk insert a lot of rows (>1 Mio.) containing columns with different data types into a SQL Server table. The data was already imported over pyodbc single executing INSERT Statements, but to speed things up, executemany and Fast-executemany should be used. 

You can find a sample Code including real world sample data and all DDL needed to set up the database table in the following GIST (https://gist.github.com/pinkerltm/9cb8a85a5df5c2f0ba2a6f66b8306815).

I would expect that executemany would work with 2 (or more) rows in the values list as it does with a list containing only one row. 

Instead I get the following error:

> pyodbc.DataError: ('String data, right truncation: length 89 buffer 73', '22001')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/_work/Devel/streetapps-import-export/tests/scratch.py", line 82, in <module>
>     cursor.executemany(sql, params)
> SystemError: <class 'pyodbc.DataError'> returned a result with an error set

If I pass a list containing only one single row, everything works fine, although the INSERTs run much slower than simply INSERTING them one by one with `cursor.execute()`.

Also if I turn off `Cursor.fast_executemany = False`, again at the cost of execution time.

### Environment
- Python 3.5.2 (64-Bit)
- pyodbc 4.0.22 
- OS: Windows 10
- DB: SQL Server 2012

**Comment by v-chojas** [comment]
I notice that you are using the `SQL Server` ODBC driver, which is the original one from SQL Server 6.0 and thus has very limited support for the newer datatypes such as `geometry` --- fast_executemany depends on accurate metadata, which for the newer datatypes would not be correctly detected by the older driver. Try the [`ODBC Driver 13.1 for SQL Server`](https://www.microsoft.com/en-us/download/details.aspx?id=53339) instead.

**Comment by pinkerltm** [comment]
Thanks @v-chojas ! As it worked with simple single INSERT executes, I did not realize that it could be just a Driver Problem. Unfortunately I am running in an string truncate error now but thats another issue on parameterized queries

**Comment by mkleehammer** [comment]
Please upgrade to 4.0.23 which reverts the problematic commits from 4.0.22.
