### ISSUE TITLE
order of information in connection string changes outcome

### ISSUE THREAD

**Issue by replabrobin** [mkleehammer/pyodbc#340]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: python 2.7.13 amd64
- pyodbc: 4.0.22
- OS: Windows 7 amd64
- DB: access 2003 mdb
- driver: {Microsoft Access Driver (*.mdb, *.accdb)}

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
This works
`>>> conn = pyodbc.connect('DSN=sample_mdb;DRIVER={Microsoft Access Driver (*.mdb, *.accdb)}')`

this fails
`>>> conn = pyodbc.connect('DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DSN=sample_mdb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY000', u"[HY000] [Microsoft][ODBC Microsoft Access Driver]General error Unable to open registry key Tem
porary (volatile) Ace DSN for process 0xc50 Thread 0x13c8 DBC 0x22f6ef8
             Jet'. (63) (SQLDriverConnect); [HY000] [Microsoft][ODBC Microsoft Access Driver]General error Unable to ope
n registry key Temporary (volatile) Ace DSN for process 0xc50 Thread 0x13c8 DBC 0x22f6ef8
                               Jet'. (63); [HY000] [Microsoft][ODBC Microsoft Access Driver]General error Unable to open
 registry key Temporary (volatile) Ace DSN for process 0xc50 Thread 0x13c8 DBC 0x22f6ef8
                              Jet'. (63); [HY000] [Microsoft][ODBC Microsoft Access Driver]General error Unable to open
registry key Temporary (volatile) Ace DSN for process 0xc50 Thread 0x13c8 DBC 0x22f6ef8
                             Jet'. (63)")`

given that the information in both is the same I would expect both to work or both to fail.

**Comment by gordthompson** [comment]
This is not a pyodbc issue. It is a more general ODBC issue, possibly related to the specific behaviour of the Access ODBC driver. I was able to reproduce similar results using VBScript and ADODB.

A valid ODBC DSN already contains the `DRIVER=` information, so if you want to establish a connection using `DSN=` then you should specify *just* the `DSN=`, not `DSN=` and `DRIVER=`. If you want to specify the driver name and the database path then you should use `DRIVER=` and `DBQ=`.

**Comment by replabrobin** [comment]
Yes that's my workaround for the present; DBQ needs the driver, but DSN doesn't.

**Comment by v-chojas** [comment]
The driver manager uses the presence of `DRIVER` or `DSN` in the connection string to decide how it will find and load the driver; it is not unreasonable to expect that specifying both may confuse it. Either you use a DSN and do _not_ specify the driver, putting only the information the driver needs in the DSN and connection string, or use DRIVER and specify everything in the connection string and not use a DSN.
