### ISSUE TITLE
Fields are truncated and only insert the first Character fast_executemany

### ISSUE THREAD

**Issue by vertigo235** [mkleehammer/pyodbc#342]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit: 64 bit

- Python: 3.6.4
- pyodbc: 4.0.22
- OS: Windows
- DB: SQL Server 2012
- driver:  Both {SQL Server} and {SQL Server Native Client 11.0}

### Issue

I can't figure out why i does this, but only certain fields seem to get truncated and only the first character is inserted. It doesn't seem to happen every time either, sometimes it will insert the whole thing. 

Issue with 4.0.22, inserting rows using fast_executemany, I switched to 4.0.21 and the problem does not exist with this version.

**Comment by v-chojas** [comment]
This appears to be related to #334 #336 #337  which we are currently still investigating.

**Comment by vertigo235** [comment]
Excellent

**Comment by vertigo235** [comment]
I saw other issues, but didn't see anything like what I was experiencing though, where there is no error, and it does insert data.  Although only the first character of the data.

Also very odd that it is not repeatable, it appears happen sometimes and not other times with the same data set, very odd.

**Comment by v-chojas** [comment]
If you can create a minimal repro script, we can also investigate this one. The intermittent nature of it is unusual.

**Comment by mkleehammer** [comment]
Please upgrade to 4.0.23 which reverts the problematic commits from 4.0.22.
