### ISSUE TITLE
ETL package on the top of PyODBC

### ISSUE THREAD

**Issue by CedricAnover** [mkleehammer/pyodbc#344]
Hi Everyone,

I'm planning on building my own package on the top of PyODBC for performing Data Migration & ETL. But before I start this project I just want to ask if anyone knows any python ETL tool package that is built on the top of pyodbc? Or is pyodbc alone capable of doing this?

**Comment by msinghnatt** [comment]
check for petl package. 
[https://pypi.org/project/petl/](url)
