### ISSUE TITLE
ubuntu:16.06 -> new msodbc driver={ODBC Driver 17 for SQL Server} => fail to restart

### ISSUE THREAD

**Issue by fenchu** [mkleehammer/pyodbc#345]
I did a `sudo apt update; sudo apt upgrade` and I got a new msodbcsql driver:
v13 was out and in with v17:

Our test containers have the following mssql config:

```
RUN /usr/bin/curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    /usr/bin/curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssqlrelease.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install msodbcsql mssql-tools unixodbc-dev -y && \
```

```
$ dpkg-query -l | grep msodbcsql
ii  msodbcsql                         17.0.1.1-1                                 amd64        ODBC Driver for Microsoft(R) SQL Server(R)
$ dpkg-query -L msodbcsql | grep .ini
/opt/microsoft/msodbcsql/etc/odbcinst.ini
$ cat /opt/microsoft/msodbcsql/etc/odbcinst.ini
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-17.0.so.1.1 
```
But when the system came up again, pyodbc complained missing driver, This is naturally because the
the version number is in the driver, so it was only to change it in my connectors *ini file:
driver = {ODBC Driver 13 for SQL Server}

But my question is how can I prevent this from happening in production next time
MS decides to upgrade their driver?

Thanks

**Comment by gordthompson** [comment]
One solution would be to maintain a dev/test box, perform routine updates there to catch any issues, and then update the production machine only after you're satisfied that the updates won't break anything.

You could also put a "hold" on the current driver version so `apt upgrade` won't upgrade it automatically (details [here](https://askubuntu.com/q/18654/323236)):

```
sudo apt-mark hold msodbcsql mssql-tools
```

**Comment by fenchu** [comment]
Thanks Gord, I my case I install from scratch so I have no version to keep, but I found a
similar solution:

Today v17.0.1.1-1 was revoked, so it failed again. do not know why because it worked fine for me, but I looked at whats out there:
```
https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/m/mssql-tools/
https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/m/msodbcsql/
```
I just changed my build container to use the latest versions still there, so now it wont be affected
if it changes.

```
RUN /usr/bin/curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    /usr/bin/curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssqlrelease.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install msodbcsql=13.1.9.2-1 mssql-tools=14.0.6.0-1 unixodbc-dev -y && \
```

**Comment by gordthompson** [comment]
Microsoft has re-released v17 under a different name so existing v13 installs ("msodbcsql") will not get clobbered by the v17 version ("msodbcsql17").
