### ISSUE TITLE
Fast_Executemany sporadic failures in pyodbc-4.0.22

### ISSUE THREAD

**Issue by nmcbride1** [mkleehammer/pyodbc#346]
Hi,

Environment is Amazon-Linux and we use pyodbc to interact with Amazon Redshift using the official AWS drivers. I believe it is Python 2.7.12.

The issue is that we have been happily using the fast_executemany functionality that was in pyodbc-4.0.22b but after upgrading yesterday to pyodbc-4.0.22 we have found that the command sometimes fails with errors such as:

('String data, right truncation: length 63 buffer 62', '22001')
('String data, right truncation: length 90 buffer 89', '22001')

Reverting back to 22b fixes the issue. I can't seem to find any pattern as to when it occurs.

Typical usage would be:
cursor.fast_executemany = True
cursor.executemany("""insert into table (
                                        field1,
                                        fieldx
                                        )
                                        values (
                                        ?,
                                        ?
                                        )""", insertparams)

A sanitised version of insertparams is:

[(datetime.datetime(2018, 2, 8, 20, 22, 35), 'found in staging', u'20180208', u'0', 'df-0109490WVLZM7GN9KZF', 'prod01-testing', 'testing-eu-west-1-prod01', 'testing/serverlog', 'testing/serverlog/staging/testing.csv.log-201802081518103801-100--3-30.gz', 'testing.csv.log-201802081518103801-100--3-30.gz', 'testing.csv.log-201802081518103801-100--3-30.gz', 25171697, 'STANDARD', None, '992cb89', 'master', u'df-0109490WVLZM7GN9KZF_1518121209451'), (datetime.datetime(2018, 2, 8, 20, 22, 35), 'found in staging', u'20180208', u'0', 'df-0109490WVLZM7GN9KZF', 'prod01-testing', 'testing-eu-west-1-prod01', 'testing/serverlog', 'testing/serverlog/staging/testing.csv.log-201802081518107401-100--2-190.gz', 'testing.csv.log-201802081518107401-100--2-190.gz', 'testing.csv.log-201802081518107401-100--2-190.gz', 27618571, 'STANDARD', None, '992cb89', 'master', u'df-0109490WVLZM7GN9KZF_1518121209451'), (datetime.datetime(2018, 2, 8, 20, 22, 35), 'found in staging', u'20180208', u'0', 'df-0109490WVLZM7GN9KZF', 'prod01-testing', 'testing-eu-west-1-prod01', 'testing/serverlog', 'testing/serverlog/staging/testing.csv.log-201802081518107401-100--3-30.gz', 'testing.csv.log-201802081518107401-100--3-30.gz', 'testing.csv.log-201802081518107401-100--3-30.gz', 27101071, 'STANDARD', None, '992cb89', 'master', u'df-0109490WVLZM7GN9KZF_1518121209451')]

Prior to using 22b we had been using pyodbc with Redshift for a year or so without issue.

**Comment by v-makouz** [comment]
What are the column types for the inserts that fail? I'm looking at smalldatetime which has that issue, but I'm wondering if there are other types that might cause that

**Comment by nmcbride1** [comment]
The columns in the target table are:

integer
timestamp
varchar (various sizes)
date
bigint

One column is an identity column, if that helps in any way.

**Comment by v-makouz** [comment]
OK, thank you, I'll investigate this further

**Comment by v-makouz** [comment]
Also, can you provide an ODBC trace for some of the failing inserts?

**Comment by mkleehammer** [comment]
I've released 4.0.23 with reverts most of the 4.0.22 changes.  Can you retest?

**Comment by neil-cloudbi** [comment]
We've not experienced any issues with Redshift since this release.
