### ISSUE TITLE
Error when inserting bit data

### ISSUE THREAD

**Issue by boumboum** [mkleehammer/pyodbc#355]
When I'm parsing an xml file and I get a boolean field, I get this error message when I try to insert:
`pyodbc.DataError: ('String data, right truncation: length 10 buffer 2', '22001')`
Here is the code for making some tests:
```
import pyodbc
connstr = my connection string here
db = pyodbc.connect(connstr)
cr = db.cursor()
a = 'bbb'
b = 'false'
sql = "insert into xx (a, b) values (?, ?)"
cr.execute(sql, a, b)
db.commit()
```

But when I do the insert directly to SQL Server over SSMS, it works without any issue
```
create table xx (a varchar(10), b bit)
insert into xx (a, b) values ('bbb', 'false')
```
Also, if I'm not using the parametrized query but building the query string by myself there is no error neither (so same behavior as using the DB server directly)
```
sql = f"insert into xx (a, b) values ('{a}', '{b}')"
cr.execute(sql)
db.commit()
```
I suspect, this is again the same type of anomaly I've already reported for the decimal values

**EDIT:**
I have same type of issue if I insert datetime value as parameter
If I do the insert with a formatted string it works:
```
d = '2014-12-14T00:00:00'
sql = f"select * from bd_mytable where start_date = '{d}'"
```
So I thing you should think globally about the paramterized queries :-(

**Comment by gordthompson** [comment]
This is another manifestation of the parameter substitution issues in pyodbc 4.0.22 as discussed in #334 and elsewhere. Those issues are under investigation. For now you can
- downgrade to pyodbc 4.0.21, or
- pass your parameter value as a true boolean (`b = False`) instead of a string (`b = 'false'`)

**Comment by mkleehammer** [comment]
I've backed out the problematic changes from 4.0.22.  Please try 4.0.23.  I'll close because I expect this to fix it, but please reopen if it does not.

**Comment by boumboum** [comment]
It seems to work. Thank you.
I've tried with decimal and bit values, everything is in good shape
But now it seems that you have changed the default autocommit behavior to True.
Previously it's default value was False and I had to commit explicitly.
This is not good because I have to rewrite ALL of our programs :-(

**Comment by boumboum** [comment]
Well it is even worse than I was thought. The autocommit feature doesn't work.
Even if I set it explicitely to False, it commits the changes to the database.

**Comment by mkleehammer** [comment]
Investigating and will add unit test right now - I don't know of any changes to do that.

**Comment by boumboum** [comment]
OK.
I'm using SQL Server
here is the code I use:
```
with pyodbc.connect(connstr, autocommit=False) as db:
    print(db.autocommit) # This prints False as expected
    cr = db.cursor()
    a = 10
    b = '0.99999999999999999998'
    c = 1
    d = '2018-02-12T12:30:48'
    cr.execute("create table xx (a int, b decimal(5,2), c bit, d datetime)")
    cr.execute("insert into xx(a, b, c, d) values (?, ?, ?, ?)", a, b, c, d)
    rows = cr.execute("select * from xx").fetchall()
    for row in rows:
        print(row.a, row.b, row.c, row.d)
```
After that I have tested the existence of the table xx as well as the inserted record in SSMS and the table and the data was there.
Normally after exiting the with block it should revert all changes. Am I wrong?

**Comment by mkleehammer** [comment]
The `with` statement commits the connection if an exception is not raised.  I think it is working as expected.  If you remove the `with` and replace with some other block like `if 1`, I think you'll find it works as you expected.

**Comment by boumboum** [comment]
OK. Fine. I didn't see it in the documentation. But good to know.
Thanks anyway (great job).
But there is still an error when I try to insert with executemany
[(10, '0.99999999999999999998', 'false', '2018-02-12T12:30:48')]
pyodbc.ProgrammingError: ('String data, right truncation: length 44 buffer 10', 'HY000')

**Comment by mkleehammer** [comment]
@v-chojas Any comments on the right truncation part?  (I haven't tried this yet and I'm assuming it is fast_executemany only.).  What is the right answer - I would think it is whatever SQL Management Studio would do?

**Comment by boumboum** [comment]
Confirmed. It is fast_executemany related.
If it's set to False it works like a charm
