### ISSUE TITLE
capped at 100k entries when using fetchall()

### ISSUE THREAD

**Issue by eloiup** [mkleehammer/pyodbc#360]
### Environment

windows 64 bit

- Python:  2.7
- pyodbc: most recent
- DB: MS SQL

### Issue

hi

i am making a cursor and executing a fetchall on a simple query such as :

`select id from users`

i was expecting about 120k entries, but i get exact 100k entries.

i tried to skip some rows by:

`select id from users except top X id from users`

but i get 100k - X entries.

ive checked the db and it does indeed have ~120k entries
i wld expect fetchall to be uncapped since there are the fetchmany() and fetchval() commands.

what cld be happening? thx

**Comment by gordthompson** [comment]
Perhaps somewhere earlier in your code it does a `SET ROWCOUNT 100000` on that connection?

ref: [SET ROWCOUNT](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-rowcount-transact-sql)

**Comment by eloiup** [comment]
nope, its as straightforward as it can be. im checking with who gave me an user/access to see if he limited it by accident

**Comment by eloiup** [comment]
fixed. the db provided was capped at 100k for some reason and the person/department failed to inform so. thx.
