### ISSUE TITLE
How to set SQL_ATTR_METADATA_ID for connection

### ISSUE THREAD

**Issue by kokosing** [mkleehammer/pyodbc#364]
Hi,

How to set SQL_ATTR_METADATA_ID for connection? Documentation suggest that I can set attributes like `autocommit, `ansi` or `timeout`. 

In the code https://github.com/mkleehammer/pyodbc/blob/master/src/connection.cpp#L150, I see there are attributes passed which are then passed to `SQLSetConnectAttr`. 

What do I need to pass to `pyodbc.connect` to set `SQL_ATTR_METADATA_ID` to `SQL_TRUE` or `SQL_FALSE`?

**Comment by v-chojas** [comment]
`conn = pyodbc.connect("<Your connection string here>", attrs_before = { 10014:1 })`

`SQL_ATTR_METADATA_ID` is 10014, and `SQL_TRUE` is 1. You can use 0 for `SQL_FALSE`. pyODBC does not have these constants already defined so you need to look up their values yourself to use them.

**Comment by kokosing** [comment]
Thank you!
