### ISSUE TITLE
Column type in cursor.description is changed to 'str' with add_output_converter

### ISSUE THREAD

**Issue by spivachek** [mkleehammer/pyodbc#366]
- Python: 3.6.1
- pyodbc: 4.0.22
- OS: Win 7 32-bit
- DB: MS Excel, TopSpeed, possibly others

Hi! When I add output converter original column type (say decimal.Decimal or float) in cursor.description is changed to str. I expected it to stay the same. This way column types are lost.

Without output converter (float column type in description):
```
s = r"Driver={Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)};DBQ=d:\work\sandbox\data.xlsx"
con = pyodbc.connect(s, autocommit=True)
cur = con.cursor()
cur.execute("select * from `data$`").description
# (('num', <class 'float'>, None, 53, 53, 0, True),)
cur.fetchone()
# (1.123456, )
```

With converter (str type in description):
```
list(cur.columns(table='data$'))
# [('d:\\work\\sandbox\\trash\\data.xlsx', None, 'data$', 'num', 8, 'NUMBER', 53, 8, None, 2, 1, None, None, 8, None, None, 1, 'YES', 1)]
con.add_output_converter(8, lambda x: 10)
cur.execute("select * from `data$`").description
# (('num', <class 'str'>, None, 53, 53, 0, True),)
cur.fetchone()
# (10, )
```

**Comment by v-chojas** [comment]
In [getdata.cpp:672](https://github.com/mkleehammer/pyodbc/blob/master/src/getdata.cpp#L672)
```
    int conv_index = GetUserConvIndex(cur, type);
    if (conv_index != -1)
        return (PyObject*)&PyString_Type;
```
This appears to be by design --- when an output converter is used, the type is explicitly set to a string. Perhaps @mkleehammer may be able to explain why this is done?

**Comment by spivachek** [comment]
Thanks for quick reply. That will be interesting to know. What I'm doing in my app is saving rows to csv and also placing general column type (like string, integer, float, date) next to column name. And I get this general type by looking into cursor.description. But output converters mess the type. Other ways for me to do it would be to look into values (not straightforward because of nulls, empty tables) or cursor.columns (more work, more types to compare) or do the conversion myself (kinda unnecessary).

**Comment by gordthompson** [comment]
@v-chojas (cc: @mkleehammer) re: "when an output converter is used, the type is explicitly set to a string"

This could be a remnant of Python2. If an output converter function is in play then pyodbc always receives the column value as bytes and passes them to the function for further manipulation. In Python2, `str` was the "sequence of bytes" data type.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
