### ISSUE TITLE
Error message strings include \x00 byte codes

### ISSUE THREAD

**Issue by joseph-jnl** [mkleehammer/pyodbc#369]
#251 

- Python: 3.6.4
- pyodbc: 4.0.22
- OS: linux64-mint 18.3 
- DB: Netezza
- driver: IBM Netezza

### Issue

Using the following connections settings as described in https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-Netezza
```
cnxn = pyodbc.connect('DSN=NZSQL')
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-8')
cnxn.setencoding(encoding='utf-8')
cursor = cnxn.cursor()
```

The connection works great but if there is ever an error in the SQL code, the warning includes '\x00' byte codes in the error message.

> ProgrammingError: ('42000', '[42000] E\x00R\x00R\x00O\x00R\x00:\x00 \x00 \x00\'\x00X\x00I\x00S\x00T\x00S\x00;\x00 \x00L\x00I\x00M\x00I\x00T\x00 \x005\x00 \x00 \x00 \x00 \x00 \x00 \x00\'\x00\n\x00e\x00r\x00r\x00o\x00r\x00 \x00 \x00 \x00^\x00 \x00f\x00o\x00u\x00n\x00d\x00 \x00"\x00E\x00X\x00I\x00S\x00T\x00S\x00"\x00 \x00(\x00a\x00t\x00 \x00c\x00h\x00a\x00r\x00 \x000\x00)\x00 \x00e\x00x\x00p\x00e\x00c\x00t\x00i\x00n\x00g\x00 \x00a\x00 \x00k\x00e\x00y\x00w\x00o\x00r\x00d\x00 (27) (SQLExecDirectW)')

Is there a setting I can use to parse the error messages without the byte code?

**Comment by mkleehammer** [comment]
Errors are retrieved using SQL_WMETADATA encoding.  In this case, the error is in UCS4, not UTF-8. 

The metadata encoding is used in two places:

* error messages
* column names

Can you confirm that column names are being read properly?  If they also are corrupted, then you can simply change the encoding.  If they are correct, then we have to make a change to allow them to use individual encodings.  (This example may not work exactly in Netezza, so please modify as necessary.)

    cursor.execute("select 1 as abc")
    colname = cursor.description[0][0]
    print(colname, repr(colname), len(colname))

Thanks.

**Comment by joseph-jnl** [comment]
It looks like column names are being read properly:

```
cursor.execute("select 1 as abc")
colname = cursor.description[0][0]
print(colname, repr(colname), len(colname))
```

> ABC 'ABC' 3

**Comment by v-chojas** [comment]
That error message looks more like UTF-16(LE) to me.

**Comment by mkleehammer** [comment]
Correct - it is UTF-16.  I saw 3 zeros in a row in the middle and assumed.

The bad news is the metadata and errors are using different encodings.  It would be great if driver writers followed specifications *or* were at least consistent.

It's odd that the page specifically says you might need UTF16-LE for column names some times. 

@joseph-jnl Is it possible to set your ODBC [Unicode Translation Option](https://www.ibm.com/support/knowledgecenter/en/SSULQD_7.1.0/com.ibm.nz.datacon.doc/c_datacon_odbc_driver_properties.html) to UTF16?  If so, perhaps the metadata (column names) would also change and you could set that to 'utf16-le'?  At least as a work around?

**Comment by joseph-jnl** [comment]
@mkleehammer Yes, that works!

```
[NetezzaSQL]          
 Driver           = /usr/local/nz/lib/libnzsqlodbc3.so      
 Setup            = /usr/local/nz/lib/libnzsqlodbc3.so   
 APILevel         = 1     
 ConnectFunctions = YYN       
 Description      = Netezza ODBC driver       
 DriverODBCVer    = 03.51             
 DebugLogging     = false        
 LogPath          = /tmp         
 UnicodeTranslationOption = utf16                   
 CharacterTranslationOption = all     
 PreFetch         = 256             
 Socket           = 16384  
```

```
cnxn = pyodbc.connect('DSN=NZSQL')
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-16le')
cnxn.setencoding(encoding='utf-8')
cursor = cnxn.cursor()
```

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
