### ISSUE TITLE
Synergy with turbodbc [question]

### ISSUE THREAD

**Issue by nrhy** [mkleehammer/pyodbc#373]
Hey folks,

I'm currently using pyodbc for my work and came across turbodbc lately. I was wondering if there were opportunities for synergy? It looks interesting with the numpy/asycio/pyarrow support. Just thought to ask :) Would be interested in getting involved. 

-T

**Comment by v-chojas** [comment]
Perhaps you should ask at https://github.com/blue-yonder/turbodbc  instead? I'm not familiar with Synergy but they may know more about how well its ODBC driver will work there.

**Comment by nrhy** [comment]
@v-chojas Thanks for getting back. Actually, i meant synergy in the literal sense - in other words if there were any opportunities of incorporating features that turbodbc offers.

Nowadays it's easy for outsiders to look at two projects and wish they were one, so i don't mean to be disrespectful in anyway, was just curious if the pyodbc and turbodbc team have been in touch :)

**Comment by mkleehammer** [comment]
The code bases are quite different, so any actual code sharing would not be possible.

For sending data, the fast_executemany provides the same kind of array handling under the covers.  I used to be a numpy user and would be interested in making pyodbc work with it natively, but don't get requests for it much.
