### ISSUE TITLE
ImportError with Python 3 and Django 1.8

### ISSUE THREAD

**Issue by mpwoodward** [mkleehammer/pyodbc#38]
This may be something Django-specific but thought I'd ask here in addition to on the Django list.

On Ubuntu Server 14.04 64-bit, Python 3.4, and pyodbc 3.0.8 (which I believe is the only version that works with Python 3?), pyodbc installs fine, and works fine from a regular Python interpreter, but fails in a Django shell.

For example if I do python3 and then import pyodbc, no problems.

If, however, I do python3 manage.py shell and then import pyodbc, I get the following:
http://pastebin.com/cNDrmvcb

Any ideas? Thanks.

**Comment by mkleehammer** [comment]
I am just now fixing a bug that causes this exact error when importing the decimal module.  I was not clearing the import error after attempting to import "cdecimal", so it would fail to load.  I'm not sure if it is the same, but I'll push the fix now and you can try.  Sorry about that.

**Comment by mpwoodward** [comment]
Thanks! About to give that a shot. Also seeing what apparently is an old encoding-related but (reported in https://code.google.com/p/pyodbc/issues/detail?id=110 on the old google code site) but I'll try this new version and create another issue if I can't get that one sorted out.

Really, really appreciate the quick response!

**Comment by mpwoodward** [comment]
That did the trick! Thanks SO MUCH!
