### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by dalalkrish** [mkleehammer/pyodbc#381]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.23
- OS: Ubuntu 16.04
- DB: TestDB
- driver: FreeTDS

### Issue

I have I'm inserting the ~1M rows per batch into SQL Server table using `pyodbc.fast_executemany=True`. I am getting ###Segmentation fault (core dumped) error. 

Can you please help in identifying the solution? If I change `pyodbc.fast_executemany=False` it works but then inserts takes considerably long time.
 
Also, using `fast_executemany` with `concurrent.futures` parallel programming, program returns ###Memory Error.

**Comment by dalalkrish** [comment]
Yes, I installed Microsoft ODBC Driver 13 and it worked. Thank you for your response.

**Comment by suprakashworking** [comment]
fast_executemany doesn't work on Linux. Using the Microsoft ODBC driver mentioned below. But there are no changes whatsoever. There is segmentation fault everytime.

**Comment by suprakashworking** [comment]
It works sometimes but fails at other times. This lack of consistency is most highly infuriating.

**Comment by Ahmed1Arshed** [comment]
I am getting the same issue while using ODBC 17
It's not allowing me to use multiprocessing in my code if some know about that solution
