### ISSUE TITLE
non latin characters stored incorrectly in Teradata

### ISSUE THREAD

**Issue by mitchea5** [mkleehammer/pyodbc#382]
### Environment

- Python: Anaconda 3.6
- pyodbc: pyodbc-4.0.17
- OS:  Red Hat 4.8.5-11
- DB: Teradata 15.10
- driver: Teradata ODBC 15.10

### Issue

I am attempting to insert data in the form of a list of lists into target Teradata columns defined as varchar Unicode. The data is a mix of ascii, kanji (and other non western character sets), and latin. The below example is one element in the list I am trying to insert, all target Unicode columns and list elements have the same problem.

When the data is inserted, when viewed through any gui tool (jdbc/odbc/bteq)

It looks like this:

`ClassificaÃ§Ã£o Brasileira de OcupaÃ§Ãµes`

When I run Teradata's char2hexint function, I get the following, which translates to the above character string.

`0043006C0061007300730069006600690063006100C300A700C300A3006F002000420072006100730069006C00650069007200610020006400650020004F006300750070006100C300A700C300B500650073`

I am expecting this:

`Classificação Brasileira de Ocupações`

If I print the list directly before the insert, it looks correct:

`Classificação Brasileira de Ocupações`

If, instead of inserting the list, I execute a hard coded insert statement with those characters from within the python script, it looks as expected.

If I execute a select in python against the incorrect columns and print it to the console, the value is correct.

If I set `cnxn.setencoding(encoding='latin1')` the data looks correct in GUI tools, but this won't work because there are non latin characters in the data.

Per documentation I set up the connection information like the below. I also set charset to UTF8 in the DSN and connection string.

      
`cnxn = pyodbc.connect('DSN={0:s};UID={1:s};PWD={2:s};'.format(str(teradata_tdpid),
str(teradata_userid),str(teradata_passwd )))

cnxn.autocommit = True

pyodbc.pooling = False

cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')

cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')

cnxn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-8')

cnxn.setencoding(encoding='utf-8')`

**Comment by gordthompson** [comment]
Can you try a very simple round-trip? Something like this (tested with SQL Server; no Teradata available to me, unfortunately):

```python
crsr = cnxn.cursor()
strIn = 'Classificação Brasileira de Ocupações'
sql = "SELECT ? AS foo"
strOut = crsr.execute(sql, strIn).fetchval()
if strOut == strIn:
    print("Success")
else:
    print("FAIL")
```

**Comment by mitchea5** [comment]
I tried the simple round trip and it worked.

After that I tried selecting the value stored in the Teradata column and comparing to the string and that failed.

I compared the string to the value in the list right before executemany, and that was successful. 

I also tried switching from executemany to execute w/ a loop. 

Finally, I changed the target column to latin, but am getting the same results. 

I'll see about installing 4.0.23.

**Comment by mitchea5** [comment]
One thing I observe in the ODBC stack trace is that the hard coded values sent to the database (which look correct) include the single quote, but still resolve to the bad characters, whereas the parameter execute is sending the strings w/o the single quotes:

TS:37210:[140104824379200]    2A0  00436C6173736966696361C383C2A7C3  Classifica
TS:37210:[140104824379200]    2B0  83C2A36F2042726173696C6569726120    o Brasileira
TS:37210:[140104824379200]    2C0  6465204F63757061C383C2A7C383C2B5 de Ocupa


TS:580:[140025468192576]    1D0  2D33302D30373A3030272C2027436C61 -30-07:00', 'Cla
TS:580:[140025468192576]    1E0  73736966696361C3A7C3A36F20427261 ssifica    o Bra
TS:580:[140025468192576]    1F0  73696C65697261206465204F63757061 sileira de Ocupa
TS:580:[140025468192576]    200  C3A7C3B56573272C202730272C202742     es'

**Comment by mitchea5** [comment]
Updating to the latest pyodbc (4.0.23) hasn't changed the result. 

The ODBC driver on the machine will be upgraded to 16.20 soon, there are some changes that will bring it more inline with the ODBC spec. Hopefully that helps.

**Comment by mitchea5** [comment]
In the mean time I've been experimenting with the  `odbc.ini` file and noticed some interesting behavior. 

In my `odbc.ini` I have:

`InstallDir=/opt/teradata/client/ODBC_64
Trace=1
TraceFile=odbctrace.out
TraceDll=/opt/teradata/client/ODBC_64/lib/odbctrac.so
 `
Under

`[ODBC]`
 As well as:

`myDSN=tdata.so`

in 
`[ODBC Data Sources]`

If I run `tdxodbc64` and do a few queries, the trace file shows up, but if I do it in pyodbc I get no trace output.

It's almost like python isn't respecting the `odbc.ini` file location or some of its parameters. If I print out the value of `ODBCINI` in the python script, it shows the location of the `odbc.ini` file that I expect and that works with tdxodbc64.

**Comment by mitchea5** [comment]
Yes it does.

**Comment by gordthompson** [comment]
You could try creating an `/etc/odbcinst.ini` symlink that points to the Teradata odbcinst.ini

**Comment by ToastWithCoffee** [comment]
just found a solution... (not pretty, but it works)

With the oracle database function convert(source attribute,'WE8ISO8859P1','AL32UTF8') I got the correct values. Maybe teradata also has a function like this?

I also tested the code page ISO8859 p1 in my script, but still get the wrong values. Probably there is a bug in pyodbc or in the odbc driver itself.

**Comment by mitchea5** [comment]
The  `16.20.00.04` drivers seems to have resolved the issue. In fact there is no need to set any encoding/decoding parameters in the pyodbc connection . Just make sure the odbc.ini entry has the entry

`CharacterSet=UTF16`

I do notice executemany is slower, not sure if it's related or not. Could be network traffic, database resources, etc.
