### ISSUE TITLE
pip install pyodbc fails on macos 10.12 with Python 2.7.15

### ISSUE THREAD

**Issue by DonPasquale** [mkleehammer/pyodbc#385]
### Environment

- Python: 2.7.15 for macos from python.org, 64bit only, for 10.9 onwards
- pyodbc: pip tries to build "pyodbc-4.0.23.tar.gz"
- OS: MacOS 10.12, all updates applied
- DB: n/a, as pip install fails
- driver: n/a, as pip install fails

### Issue

-  "expected behavior" 

expected pip install pyodbc to work "out of the box". We have been working with it on MacOS for many years (originally 10.4, then 10.6 and 10.7) and it used to be very easy and did never cause any trouble (using "setup.py" directly at the time).

-  "observed behavior".

Install fails with the following error message:

"    In file included from src/buffer.cpp:12:
    src/pyodbc.h:56:10: fatal error: 'sql.h' file not found
    #include <sql.h>
             ^~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jw/g7hfq88d7858lbhwm_l5x4vm0000gp/T/pip-install-YWb77A/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jw/g7hfq88d7858lbhwm_l5x4vm0000gp/T/pip-record-HWU1qg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jw/g7hfq88d7858lbhwm_l5x4vm0000gp/T/pip-install-YWb77A/pyodbc/

**Comment by v-chojas** [comment]
sql.h is part of the Driver Manager. According to https://github.com/mkleehammer/pyodbc/wiki/Drivers-and-Driver-Managers "iODBC is another driver manager for Unix platforms. It used to be pre-installed as the default driver manager on Mac OSX, but since around early 2015, this is no longer the case." The preferred DM is now unixODBC, please install it and try again.

**Comment by DonPasquale** [comment]
I believe, even today it is still pre-installed (at least as of 10.12, will check 10.13), as 'ls -als /usr/lib/libiodbc*' gives the following result:

ls -als /usr/lib/libiodbc*
480 -rwxr-xr-x  1 root  wheel  565344 29 Apr  2017 /usr/lib/libiodbc.2.1.18.dylib
  8 lrwxr-xr-x  1 root  wheel      21  1 Mai  2017 /usr/lib/libiodbc.2.dylib -> libiodbc.2.1.18.dylib
  8 lrwxr-xr-x  1 root  wheel      21  1 Mai  2017 /usr/lib/libiodbc.dylib -> libiodbc.2.1.18.dylib
136 -rwxr-xr-x  1 root  wheel  154448 29 Apr  2017 /usr/lib/libiodbcinst.2.1.18.dylib
  8 lrwxr-xr-x  1 root  wheel      25  1 Mai  2017 /usr/lib/libiodbcinst.2.dylib -> libiodbcinst.2.1.18.dylib
  8 lrwxr-xr-x  1 root  wheel      25  1 Mai  2017 /usr/lib/libiodbcinst.dylib -> libiodbcinst.2.1.18.dylib

**Comment by mkleehammer** [comment]
There are a couple of things to unpack here.

First, I think the most precise explanation of the error message is that the iODBC development files are no longer part of macOS.  The libraries exist, but not the "sql.h" header file you see in the error message:

    mdfind -name sql.h

When I run this, I get quite a few files with this name, but none are from iODBC.

Second, the error surprises me because I would expect it to have tried to download a pre-build binary wheel.  I provide prebuilt macOS binaries for 2.7 (64-bit) and 3.4-3.7.  Can you try this with just pip instead of setuptools:

    pip install pyodbc
    pip2.7 install pyodbc.  # might need if pip has been replaced by a later version

The next problem would be that you need a unixODBC driver instead of an iODBC driver.  I install unixODBC using brew.

I would like to support both unixODBC and iODBC, but I can't build a single binary that supports both since they have different data sizes.  (I don't remember the details right now.). The iODBC group has opened an issue, but I don't remember getting any suggestions on how to support both.

If you wanted to build an iODBC version, you'd need to modify the setup.py file in the 'darwin' section.  Unless you care about a particular driver, I would suggest trying the unixODBC route first.

**Comment by mkleehammer** [comment]
Did this answer your question?  How did it go?

**Comment by loulombard** [comment]
This worked for me:
`brew install unixodbc`
`pip install pyodbc`

**Comment by LivSith** [comment]
> This worked for me

Thank you! It worked here

**Comment by randalrand** [comment]
@loulombard your solution worked from me as well. Thank you.

**Comment by akvrdata** [comment]
> This worked for me:
> `brew install unixodbc`
> `pip install pyodbc`

**Comment by ievgenk** [comment]
Thanks from 2019

**Comment by DonPasquale** [comment]
> Did this answer your question? How did it go?

Mike,

I must admit I am a bit embarrased for replying only after 18 months. But: yes, it does answer my question.

As I am "stuck" with iodbc though -- I use pyodbc to regularly write data to a FileMaker database -- I was following this route, as suggested as a second alternative, i.e. changing setup.py:

https://stackoverflow.com/questions/48084708/how-to-build-pyodbc-with-links-to-iodbc-in-macos

I was wondering though if it was possible to give those who cannot migrate to unixODBC the possibility to build pyodbc from source by specifying some environment variable? Maybe something like:

python setup.py build --use-iodbc
OR
USE_IODBC=true pip install pyodbc

"lxml" is doing something similar:

python setup.py build --static-deps
OR
STATIC_DEPS=true pip install lxml
( https://lxml.de/build.html#building-lxml-on-macos-x )

Not sure if this is the right place for this, or rather #444 .

Many thanks!

**Comment by funcelot** [comment]
OK, still works for Python 3.8 MacOS 10.13.6 from 2020. and will work in 2021.

**Comment by funcelot** [comment]
https://github.com/mkleehammer/pyodbc/issues/385#issuecomment-425216885
[https://github.com/mkleehammer/pyodbc/issues/385#issuecomment-425216885](url)

OK, still works for Python 3.8 MacOS 10.13.6 from 2020. and will work in 2021.

**Comment by zamion84** [comment]
newbie here with m1 MacBook air . Using pycharm, I had to use these commands within my 3.10 virtual environment terminal not my base environment terminal and it worked for me. jessemarkboyd, do you have multiple virtual environments?

> > > > This worked for me: `brew install unixodbc` `pip install pyodbc`
> > > 
> > > 
> > > 2021 now, but this didn't work for me. Still gives the same error, 'sql.h' file not found
> > 
> > 
> > Same here on macbook pro M1 pro don't know if it's related.
> > Edit: Fix with
> > ```
> > brew install unixodbc
> > export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.9_1/lib"
> > export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9_1/include"
> > pip install pyodbc
> > ```
> 
> Yeah, M1 here too. Sounds like it's not supported. #846

**Comment by alexandrerays** [comment]
> > > This worked for me: `brew install unixodbc` `pip install pyodbc`
> > 
> > 
> > 2021 now, but this didn't work for me. Still gives the same error, 'sql.h' file not found
> 
> Same here on macbook pro M1 pro don't know if it's related.
> 
> Edit: Fix with
> 
> ```
> brew install unixodbc
> export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.9_1/lib"
> export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9_1/include"
> pip install pyodbc
> ```

I almost arrived in 2022 without this. It just worked with the exports for me.

Python 3.8.9
macOs 12.0.1 Monterey

**Comment by BrianThomasRoss** [comment]
For anyone who runs into the same problem. I couldn't get this to work by using the exports one at a time I had to copy

```
export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.9_1/lib"
export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9_1/include"
pip install pyodbc
```

All at once to the clipboard and paste to the terminal and execute. Not entirely sure why this works this way.

**Comment by BejanSadeghian** [comment]
> > > This worked for me: `brew install unixodbc` `pip install pyodbc`
> > 
> > 
> > 2021 now, but this didn't work for me. Still gives the same error, 'sql.h' file not found
> 
> Same here on macbook pro M1 pro don't know if it's related.
> 
> Edit: Fix with
> 
> ```
> brew install unixodbc
> export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.9_1/lib"
> export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9_1/include"
> pip install pyodbc
> ```

2022 this works on my M1X MPB with Python 3.10.1 and OSX 12.1 

Thank you!

**Comment by rbkprod** [comment]
> > > This worked for me: `brew install unixodbc` `pip install pyodbc`
> > 
> > 
> > 2021 now, but this didn't work for me. Still gives the same error, 'sql.h' file not found
> 
> Same here on macbook pro M1 pro don't know if it's related.
> 
> Edit: Fix with
> 
> ```
> brew install unixodbc
> export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.9_1/lib"
> export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9_1/include"
> pip install pyodbc
> ```

Thank you so much, this was the only thing that worked for me. M1 on Monterey

**Comment by KantiCodes** [comment]
> brew install unixodbc
> export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.9_1/lib"
> export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.9_1/include"

Legend! Thank you

**Comment by nssalian** [comment]
```
brew install unixodbc
export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.11/lib"
export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.11/include"
pip install pyodbc
```

**Comment by furick1** [comment]
arch -arm64 brew install unixodbc
pip3 install pyodbc

on latest mac as of today

**Comment by UmkaBea** [comment]
New in this, tell me please, where do I need to run this commands?
brew install unixodbc
export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.11/lib"
export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.11/include"
pip install pyodbc
brew doesn't run in PyCharm
pip doesn't run in Terminal

**Comment by mikenerone** [comment]
> brew install unixodbc
> export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/2.3.11/lib"
> export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/2.3.11/include"
> pip install pyodbc

Just a tip that you can set these environment variables up in a way that tracks with version upgrades like this (I'm not a long-time Mac user, so maybe this is a recent thing in homebrew):
```
export LDFLAGS="-L/opt/homebrew/opt/unixodbc/lib"
export CPPFLAGS="-I/opt/homebrew/opt/unixodbc/include"
```
