### ISSUE TITLE
Why is this statement "prepared"?

### ISSUE THREAD

**Issue by mpf82** [mkleehammer/pyodbc#387]
### Environment

- Python: 3.4.3
- pyodbc: 4.0.23
- OS: Windows 10, 64bit
- DB: MariaDB (mariadb-10.2.14-winx64)
- driver: MariaDB ODBC 3.0 Driver (mariadb-connector-odbc-3.0.3-win64)

### Issue

I am trying to create a trigger via pyodbc, however the statement always fails with the error:

> pyodbc.Error: ('HY000', '[HY000] [ma-3.0.3][10.2.14-MariaDB]This command is not supported in the prepared statement protocol yet (1295) (SQLExecDirectW)')

Here's my statement, which runs fine if I execute it in a SQL Manager Tool:

```
sql = """
CREATE OR REPLACE TRIGGER mdemployeetab_ucut
BEFORE UPDATE ON mdemployeetab
FOR EACH row
BEGIN
    SET NEW.utime = 5;
END;
""".strip()

cursor.execute( sql )
# cursor.execute( sql, None ) # same error
```

As far as I understand, the statement should not be prepared, because I am not passing any parameters, however my ODBC log looks like this:

> test_pyodbc     2c8c-e00	ENTER SQLPrepareW 
> 		HSTMT               0x00000000058A1010
> 		WCHAR *             0x00000000054AE6E0 [     122] "CREATE OR REPLACE TRIGGER mdemployeetab_ucut\ aBEFORE UPDATE ON mdemployeetab\ aFOR EACH row\ aBEGIN\ a    SET NEW.utime = 5;\ aEND;"
> 		SDWORD                   122
> 
> test_pyodbc     2c8c-e00	EXIT  SQLPrepareW  with return code -1 (SQL_ERROR)
> 		HSTMT               0x00000000058A1010
> 		WCHAR *             0x00000000054AE6E0 [     122] "CREATE OR REPLACE TRIGGER mdemployeetab_ucut\ aBEFORE UPDATE ON mdemployeetab\ aFOR EACH row\ aBEGIN\ a    SET NEW.utime = 5;\ aEND;"
> 		SDWORD                   122
> 
> 		DIAG [HY000] [ma-3.0.3][10.2.14-MariaDB-log]This command is not supported in the prepared statement protocol yet (1295) 
> 
> test_pyodbc     2c8c-e00	ENTER SQLGetDiagRecW 
> 		SQLSMALLINT                  3 <SQL_HANDLE_STMT>
> 		SQLHANDLE           0x00000000058A1010
> 		SQLSMALLINT                  1 
> 		SQLWCHAR *          0x00000000007EE8D0
> 		SQLINTEGER *        0x00000000007EE8C8
> 		SQLWCHAR *          0x00000000007EE8E0 
> 		SQLSMALLINT               1023 
> 		SQLSMALLINT *       0x00000000007EF138
> 
> test_pyodbc     2c8c-e00	EXIT  SQLGetDiagRecW  with return code 0 (SQL_SUCCESS)
> 		SQLSMALLINT                  3 <SQL_HANDLE_STMT>
> 		SQLHANDLE           0x00000000058A1010
> 		SQLSMALLINT                  1 
> 		SQLWCHAR *          0x00000000007EE8D0 [       5] "HY000"
> 		SQLINTEGER *        0x00000000007EE8C8 (1295)
> 		SQLWCHAR *          0x00000000007EE8E0 [      99] "[ma-3.0.3][10.2.14-MariaDB-log]This command is not supported in the prepared statement protocol yet"
> 		SQLSMALLINT               1023 
> 		SQLSMALLINT *       0x00000000007EF138 (99)

So it's no wonder the statement fails, because ``CREATE TRIGGER`` is indeed not a supported Prepared Statement, as stated in the docs: https://mariadb.com/kb/en/library/prepare-statement/

But how can I execute the statement "unprepared"?

Is this a bug in pyodbc, or in the ODBC driver? Or am I missing something else here?

Cheers =)

**Comment by v-makouz** [comment]
Do you have a complete repro script? I tried running this statement with the latest pyODBC code and it seems to be doing the correct thing, i.e. determining that there are no parameters and so going for SQLExecuteDirect without SQLPrepare.

**Comment by mpf82** [comment]
@v-makouz : thanks for your reply.

Here's a minimal script to reproduce the issue and the complete traceback:

```
import pyodbc

print("version:", pyodbc.version) # 4.0.23

cnxn = pyodbc.connect('Driver={MariaDB ODBC 3.0 Driver};Server=localhost;Database=MY_DB;User=MY_USER;Password=MY_PWD;')

cursor = cnxn.cursor()

print( cursor.execute( "select version()" ).fetchall()[0] ) # ('10.2.14-MariaDB', )

sql = """
create or replace TABLE mdemployeetab
( recid bigint(30) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ucount int not null default 0,
  utime int not null default 0
)
""".strip()
cursor.execute( sql )

sql = """
CREATE OR REPLACE TRIGGER mdemployeetab_ucut
BEFORE UPDATE ON mdemployeetab
FOR EACH row
BEGIN
    SET NEW.utime = 5;
END;
""".strip()
cursor.execute( sql )
```

> Traceback (most recent call last):
>   File "D:\mpf\mpf.test\test_pyodbc2.py", line 28, in <module>
>     cursor.execute( sql )
> pyodbc.Error: ('HY000', '[HY000] [ma-3.0.3][10.2.14-MariaDB]This command is not supported in the prepared statement protocol yet (1295) (SQLExecDirectW)')
>

**Comment by gordthompson** [comment]
@mpf82 - I just tried your repro code using MySQL Connector/ODBC 5.3.4 against MySQL 5.6.13 and I didn't get an error from executing "CREATE TABLE ..." via pyodbc 4.0.23. I notice that your traceback mentions `...  (SQLExecDirectW)` and the ODBC trace of my test confirms that SQLExecDirectW is invoked:

```
main            13e0-21ac	EXIT  SQLExecDirectW  with return code 0 (SQL_SUCCESS)
        HSTMT               0x00000000006ED8C0
        WCHAR *             0x0000000002A22750 [     111] "CREATE TRIGGER mdemployeetab_ucut\ aBEFORE UPDATE ON mdemployeetab\ aFOR EACH row\ aBEGIN\ a    SET NEW.utime = 5;\ aEND;"
        SDWORD                   111
```

It looks like you might be encountering a particular issue with the MariaDB ODBC driver. Perhaps check its documentation for any mention of new-ish options like "always prepare statements" or something like that.

**Comment by mpf82** [comment]
It's getting stranger ...

I recorded a new complete ODBC Trace of the code I posted above, only to find that ``SQLPrepareW`` is no longer executed - however the error is still the same.

Relevant part:

> test_pyodbc2    3494-aec	ENTER SQLExecDirectW 
> 		HSTMT               0x0000000006461010
> 		WCHAR *             0x0000000005C0E6E0 [     122] "CREATE OR REPLACE TRIGGER mdemployeetab_ucut\ aBEFORE UPDATE ON mdemployeetab\ aFOR EACH row\ aBEGIN\ a    SET NEW.utime = 5;\ aEND;"
> 		SDWORD                   122
> 
> test_pyodbc2    3494-aec	EXIT  SQLExecDirectW  with return code -1 (SQL_ERROR)
> 		HSTMT               0x0000000006461010
> 		WCHAR *             0x0000000005C0E6E0 [     122] "CREATE OR REPLACE TRIGGER mdemployeetab_ucut\ aBEFORE UPDATE ON mdemployeetab\ aFOR EACH row\ aBEGIN\ a    SET NEW.utime = 5;\ aEND;"
> 		SDWORD                   122
> 
> 		DIAG [HY000] [ma-3.0.3][10.2.14-MariaDB]This command is not supported in the prepared statement protocol yet (1295) 
> 

Complete Trace (expires in 1 month): https://pastebin.com/HxYPuPdv

@gordthompson from what I've seen by looking at the [MariaDB ODBC Connector Sources](https://github.com/MariaDB/mariadb-connector-odbc/search?utf8=%E2%9C%93&q=prepare&type=), the statement should only be prepared if it has parameters - same as pyodbc. And the ODBC trace above now also shows ``SQLExecDirectW``.

**Comment by mpf82** [comment]
**Update 3:** Using ``MySQL ODBC 8.0 Unicode Driver`` with my instance of MariaDB server also works fine, so the culprit is the MariaDB connector. I will close this issue, since I can live with this constellation, and it's not a pyodbc issue. Thanks for all the replies.

Cheers =)
