### ISSUE TITLE
Cannot call SqlGetInfo for most convert info types

### ISSUE THREAD

**Issue by JordanBoltonMN** [mkleehammer/pyodbc#389]
### Environment

- Python: 2.7.14 64b
- pyodbc: 4.0.22
- OS: Windows 10 Enterprise 64b
- DB: Snowflake 64b
- driver: 2.14

### Issue

I am using pyodbc to help diagnose a ODBC driver issue and I'm running into issues with calls to SqlGetInfo.

    conn = pyodbc.connect(connection_string)

    # executes without issues
    conn.getinfo(pyodbc.SQL_CONVERT_VARCHAR) # 70, SQL_CONVERT_VARCHAR in sqlext.h

    # fails, along with every other type of SQL_CONVERT info type
    conn.getinfo(67) # SQL_CONVERT_TIMESTAMP in sqlext.h

This is due to the whitelist of [allowed info types](https://github.com/mkleehammer/pyodbc/blob/master/src/connection.cpp#L506) containing no converts other than varchar. Is there a reason why the other converts cannot be added to `aInfoTypes`?

**Comment by JordanBoltonMN** [comment]
Is there anything consequential to adding more constants? I created a test fork and it seemed to work fine, so I [created a PR](https://github.com/mkleehammer/pyodbc/pull/390) with my changes.

**Comment by mkleehammer** [comment]
Merged!  Thanks for the update.
