### ISSUE TITLE
Fetch Multi-Results from one execute

### ISSUE THREAD

**Issue by endora22** [mkleehammer/pyodbc#392]
Hello, I want to execute more than one select sql at once, and get all the data it should return, but I can't find any solution or any similar issues.

### Environment
- Python: 3.5 x64
- pyodbc: 4.0.23
- OS: Win 7
- DB:Microsoft SQL SERVER 2014
- driver:SQL Server

## observed behavior
when I run this code: mycursor.execute("SELECT * FROM TABLE1;SELECT * FROM TABLE2").fetchall(),
I get no error, but only one table return to me
## observed behavior
I want to get multi datasets from one execution, how can I achieved that?

**Comment by v-chojas** [comment]
Use the [url=https://github.com/mkleehammer/pyodbc/wiki/Cursor#nextset]cursor.nextset()[/url] method. fetchall() only returns all the rows of _one_ resultset.
