### ISSUE TITLE
error: cast from 'unsigned char*' to 'SQLUINTEGER' loses precision

### ISSUE THREAD

**Issue by darwinyip** [mkleehammer/pyodbc#393]
### Environment

- Python: 2.7
- pyodbc:  4.0.23
- OS: Redhat 5
- DB: None - failed to install
- driver:  None - failed to install

### Issue

pyodbc fails to build with the below error:
`  cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
  src/params.cpp: In function 'bool ExecuteMulti(Cursor*, PyObject*, PyObject*)':
  src/params.cpp:1600: error: cast from 'unsigned char*' to 'SQLUINTEGER' loses precision
  error: command 'gcc' failed with exit status 1
`

**Comment by v-chojas** [comment]
What is the output of `gcc --version` ?

**Comment by darwinyip** [comment]
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55)

**Comment by v-chojas** [comment]
What version of unixODBC do you have (use `odbcinst -j` to check), and is this a 32 or 64-bit Python/Linux?
The line in question: https://github.com/mkleehammer/pyodbc/blob/master/src/params.cpp#L1600 has a cast to SQLULEN, not SQLUINTEGER, so unless your ODBC headers are in a strange state, I don't see how such an error could occur.

**Comment by darwinyip** [comment]
unixODBC info:
odbcinst -j
unixODBC 2.2.11
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
USER DATA SOURCES..: <folder>/odbc.ini

Python is Python 2.7.14 x64-bit
Red Hat Enterprise Linux Server release 5.10 (Tikanga) x64

Could this be due to my system being too old?

**Comment by v-makouz** [comment]
This does seem to have to do with unixODBC, for the version 2.2.11 it has to be compiled with BUILD_REAL_64_BIT_MODE defined in order for this error to not occur, you can also try installing the newest unixODBC (2.3.6) as it contains a LOT of bugfixes and uses the "real 64 bit mode" by default

**Comment by darwinyip** [comment]
I don't have sudo access so in order to compile and install unixODBC, I will need to specify a different make prefix. Through the pyodbc installation, is there a way to specify a non-default path for unixODBC?

**Comment by v-makouz** [comment]
I'm afraid I don't know if there is such a way, it looks like pyODBC uses 'odbc_config --cflags' and 'odbc_config --libs' to determine unixODBC paths, so it looks like it relies on default installation

**Comment by v-chojas** [comment]
You can compile and install unixODBC in a different prefix, as long as the libraries and executables are in your PATH before the existing installation, it should work.

**Comment by darwinyip** [comment]
That worked. Thanks!
