### ISSUE TITLE
('22001', u'[22001] [Microsoft][ODBC Driver 17 for SQL Server]String data, right truncation (0) (SQLExecDirectW)')

### ISSUE THREAD

**Issue by EdwardNian** [mkleehammer/pyodbc#396]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.13
- pyodbc: lastest
- OS: Debian 8
- DB:SQL Server 2012
- driver:Microsoft ODBC Driver 17 for SQL Server & Microsoft ODBC Driver 13 for SQL Server

### Issue
I insert string value ("lang": "en#English#\U0001f1f5\U0001f1ed") into field(nvarchar max), got 
('22001', u'[22001] [Microsoft][ODBC Driver 17 for SQL Server]String data, right truncation (0) (SQLExecDirectW)')
<sql_server.pyodbc.compiler.SQLUpdateCompiler object at 0x7fe40a574590>

**Comment by v-makouz** [comment]
Can you provide repro script and/or an ODBC trace?

**Comment by EdwardNian** [comment]
@v-makouz My code is in my django project. 
```
def execute(self, sql, params=None):
    self.last_sql = sql
    sql = self.format_sql(sql, params)
    params = self.format_params(params)
    self.last_params = params
    try:
        return self.cursor.execute(sql, params)
    except Database.Error as e:
        self.connection._on_error(e)
        raise
```
With debugging ,found the try self.cursor.execute(sql, params) throw the exception.
The variable sql is "u'SET NOCOUNT OFF; UPDATE [Profile_region] SET [region_name] = ?, [sns_app_id] = ?, [config_info] = ?, [receive_monthly_report] = ?, [receiver_mail_list] = ? WHERE [Profile_region].[region_code] = ?'"
The variable params is (u'\u83f2\u5f8b\u5bbe', 1, u'{\r\n    "lang": "en#English#\u83f2\u5f8b\u5bbe",\r\n    "tz": "Asia/Manila"}', 1, u'', u'philippine')

**Comment by v-makouz** [comment]
It seems that I can execute this query without errors on my end, can you post ODBC trace? It would be helpful to see how variables are bound and such

**Comment by EdwardNian** [comment]
@v-makouz Sorry for my poor knowledge about C/C++, could you tell me how I can get ODBC trace😓？I could only debug Python code, and pyodbc  was installed via pip. Thanks for your response☺!

**Comment by v-makouz** [comment]
On Linux to enable ODBC tracing put the following at the beginning of odbcinst.ini:

[ODBC]
Trace=yes
TraceFile=/path/to/file/name.log

odbcinst.ini is usually located in /etc/odbcinst.ini, but you can check its location by running

odbcinst -j


More information about tracing:
https://www.simba.com/blog/odbc-troubleshooting-tracing/

**Comment by EdwardNian** [comment]
@v-makouz I got the following trace

[ODBC][72][1527736383.286806][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x7f041424f380
[ODBC][72][1527736383.286867][SQLSetEnvAttr.c][189]
                Entry:
                        Environment = 0x7f041424f380
                        Attribute = SQL_ATTR_ODBC_VERSION
                        Value = 0x3
                        StrLen = 4
[ODBC][72][1527736383.286895][SQLSetEnvAttr.c][363]
                Exit:[SQL_SUCCESS]
[ODBC][72][1527736383.286922][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x7f041424f380
[ODBC][72][1527736383.286948][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x7f04142bc390
[ODBC][72][1527736383.287171][SQLDriverConnectW.c][290]
                Entry:
                        Connection = 0x7f04142bc390
                        Window Hdl = (nil)
                        Str In = [UID=Dev-Dbuser;DATABASE=Ph-Dev;DRIVER=ODBC Driver 17 for SQL Server;MARS_Connection=yes;SERVER=sq...][length = 252]
                        Str Out = (nil)
                        Str Out Max = 0
                        Str Out Ptr = (nil)
                        Completion = 0
                UNICODE Using encoding ASCII 'ISO8859-1' and UNICODE 'UCS-2LE'

[ODBC][72][1527736383.642489][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x7f0414342fc0
[ODBC][72][1527736383.642582][SQLGetEnvAttr.c][157]
                Entry:
                        Environment = 0x7f0414342fc0
                        Attribute = 65002
                        Value = 0x7f0418e2a100
                        Buffer Len = 128
                        StrLen = 0x7f0418e2a09c
[ODBC][72][1527736383.642633][SQLGetEnvAttr.c][264]
                Exit:[SQL_SUCCESS]
[ODBC][72][1527736383.642683][SQLFreeHandle.c][219]
                Entry:
                        Handle Type = 1
                        Input Handle = 0x7f0414342fc0

**Comment by v-chojas** [comment]
What version of unixODBC are you using? You can try the latest [here](https://github.com/lurcher/unixODBC) to get a more informative trace.

Also worth posting is the table schema.

**Comment by v-chojas** [comment]
Latest unixODBC is 2.3.6, with 2.3.7 coming sometime soon. Yes, please install from source @ www.unixodbc.org

**Comment by EdwardNian** [comment]
@v-chojas I reinstall unixODBC from source. 
![image](https://user-images.githubusercontent.com/3196342/40869574-346dbd82-6650-11e8-8a68-4f19f568727e.png)
And got the follow trace.
[ODBC][30544][1527906488.193342][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x7f6d7424ed40
[ODBC][30544][1527906488.193443][SQLSetEnvAttr.c][189]
                Entry:
                        Environment = 0x7f6d7424ed40
                        Attribute = SQL_ATTR_ODBC_VERSION
                        Value = 0x3
                        StrLen = 4
[ODBC][30544][1527906488.193470][SQLSetEnvAttr.c][363]
                Exit:[SQL_SUCCESS]
[ODBC][30544][1527906488.193497][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x7f6d7424ed40
[ODBC][30544][1527906488.193524][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x7f6d742bbd50
[ODBC][30544][1527906488.193835][SQLDriverConnectW.c][290]
                Entry:
                        Connection = 0x7f6d742bbd50
                        Window Hdl = (nil)
                        Str In = [UID=Dev-Dbuser;DATABASE=Ph-Dev;DRIVER=ODBC Driver 17 for SQL Server;MARS_Connection=yes;SERVER=sq...][length = 252]
                        Str Out = (nil)
                        Str Out Max = 0
                        Str Out Ptr = (nil)
                        Completion = 0
                UNICODE Using encoding ASCII 'ISO8859-1' and UNICODE 'UCS-2LE'

[ODBC][30544][1527906490.781621][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x7f6d74369990
[ODBC][30544][1527906490.781709][SQLGetEnvAttr.c][157]
                Entry:
                        Environment = 0x7f6d74369990
                        Attribute = 65002
                        Value = 0x7f6d7b597100
                        Buffer Len = 128
                        StrLen = 0x7f6d7b59709c
[ODBC][30544][1527906490.781760][SQLGetEnvAttr.c][264]
                Exit:[SQL_SUCCESS]
[ODBC][30544][1527906490.781809][SQLFreeHandle.c][219]
                Entry:
                        Handle Type = 1
                        Input Handle = 0x7f6d74369990

**Comment by v-chojas** [comment]
Please try the unixODBC 2.3.7-pre [on GitHub here](https://github.com/lurcher/unixODBC), there is a bug with the logging that was fixed in it.

**Comment by mkleehammer** [comment]
I'm going to close this due to inactivity, and because it sounds like many other "right truncation" issues that were fixed in a recent release.  Please reoopen if this is still a problem.
