### ISSUE TITLE
pyodbc.connect abort on macOS with ODBC Driver 17 for SQL Server

### ISSUE THREAD

**Issue by kitsuyui** [mkleehammer/pyodbc#399]
Perhaps this issue may be bug on msodbcsql17 (not on pyodbc).

### Maybe related issues

- https://stackoverflow.com/questions/50361149/sql-server-pyodbc-driver-issue-libcabi-dylib-terminating-with-uncaught-excep
- https://github.com/michiya/django-pyodbc-azure/issues/164

### Environment

- Python: 3.6.5
- pyodbc: latest master (3d14d4) on GitHub, 4.0.23, 4.0.22
- OS: macOS (Darwin MBP-14-003 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64)
- DB: SQL Server 2017
- driver: [ODBC Driver 17 for SQL Server -- msodbcsql17](https://docs.microsoft.com/en-US/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)

### Issue

```python
import pyodbc
pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}', ...)
```

### expected behavior

- Successing without error. Or occuring usual database error.

### observed behavior

- Aborting with suddenly dies on C++ error. It cannot catching exception in python.

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for C/en_US.UTF-8/C/C/C/C
Abort trap: 6
```

This error is not happened on following environments.

- macOS with ODBC Driver 13 for SQL Server
- Linux with ODBC Driver 17 for SQL Server

### my mitigation

When resetting locale before connection, this error will not happen.

```python
import pyodbc
import locale
locale.resetlocale()
pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}', ...)
```

Or running python with environment variable `LC_CTYPE=C`, this error is suppressed.
But forcing locales like this mitigation breaks some backward compatibility.

**Comment by v-chojas** [comment]
This is not a pyODBC issue; do you have `en_US.UTF-8` locale installed?

**Comment by kitsuyui** [comment]
This will be fixed in next version of mysqlodbc17.
https://github.com/Microsoft/homebrew-mssql-release/issues/18#issuecomment-397420786
