### ISSUE TITLE
Update from 3.0.7 to 3.0.9, fails SQL Server connection

### ISSUE THREAD

**Issue by AdamPoolman** [mkleehammer/pyodbc#40]
I've recently upgraded from using 3.0.7 of this library to 3.0.9 and get the following error when it tries to connect to Microsoft SQL Server.

Traceback (most recent call last):
  File "test_query_guide.py", line 71, in <module>
    spec_cursor.execute("SELECT * FROM [SQL API]")
pyodbc.ProgrammingError: ('42000', "[42000] [FreeTDS][SQL Server]Could not find stored procedure 'S'. (2812) (SQLExecDirectW)")

For now, I've rolled back to 3.0.7.

**Comment by mkleehammer** [comment]
What version of Python are you using.  This looks like a Unicode vs ANSI string issue.

I've been trying to get some free time for v3.1 which will let you set the encoding to UTF-8, ANSI, or UTF16.  The actual ODBC specification requires either ANSI or UTF16 and pyodbc switches between them based on the ansi parameter to connect.  I'm going to replace that with an encoding.

**Comment by AdamPoolman** [comment]
Using Python 3.4.0

**Comment by mkleehammer** [comment]
I'm going to close this as a duplicate of #41.  This should be fixed on the master branch.  I'll make an official release once I fix a couple of other bugs.
