### ISSUE TITLE
Out Of Memory when i exec fetchall()

### ISSUE THREAD

**Issue by JansSan** [mkleehammer/pyodbc#402]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: Python 3.6.5
- pyodbc: 4.0.23
- OS: Centos6 8G Memory
- DB: Sybase 12
- driver: freetds 0.91 unixODBC 2.3.6

~/.odbc.ini
-------------------------------------
[Sybase]
Driver=TDS
Descrption=Sybase Server
Trace=No
Server= *
Database=*
Port= *

odbcinst.ini
------------------------------------
[PostgreSQL]
Description=ODBC for PostgreSQL
Driver=/usr/lib/psqlodbc.so
Setup=/usr/lib/libodbcpsqlS.so
Driver64=/usr/lib64/psqlodbc.so
Setup64=/usr/lib64/libodbcpsqlS.so
FileUsage=1
[MySQL]
Description=ODBC for MySQL
Driver=/usr/lib/libmyodbc5.so
Setup=/usr/lib/libodbcmyS.so
Driver64=/usr/lib64/libmyodbc5.so
Setup64=/usr/lib64/libodbcmyS.so
FileUsage=1
[TDS]
Driver = /usr/local/lib/libtdsodbc.so
[ODBC Drivers]
Devart ODBC Driver for ASE x64=installed
[FreeTDS]
Driver = /usr/local/lib/libtdsodbc.so
[sybase]
Driver = /usr/local/lib/libtdsodbc.so

freetds.conf
------------------------------------
[global]
        # TDS protocol version
        tds version = 5.0
        text size = 64512
[egServer50]
        host = symachine.domain.com
        port = 5000
        tds version = 5.0
[egServer70]
        host = ntmachine.domain.com
        port = 1433
        tds version = 7.0
[Sybase]
        host = 192.168.100.251
        port = 7000
        tds version = 5.0

### Issue
I can get almost all tables data from Sybase but for  a table A , it's deathful because python process willbe killed when the table A is be selected;

When i exec SQL 'select top 1 * from {table A}' ,later, when i exec fetchone, many, all(), Python process will be blocked, and when i check my systeminfo from exec' htop ', I find: the cpu is used 100%, and memory from 100M rise sharply until fill all memory and swap memory, then Python process will be killed by System. 

it will be occured every time ，so i need to restart the process everytime,.

anyone can give a suggestion ? Thanks!(My english is not well, please forgive me.)

**Comment by JansSan** [comment]
Just about 1000 rows, 
I don't know the question should belong to Sybase or Pyodbc?

**Comment by v-chojas** [comment]
Could you provide an ODBC trace?
