### ISSUE TITLE
pyodbc drops millisecond precision from datetime values on MySQL

### ISSUE THREAD

**Issue by amorphous1** [mkleehammer/pyodbc#406]
### Environment

- Python: 3.6.5
- pyodbc: 4.0.23
- OS: Ubuntu 16.04.1
- DB: MySQL 5.7.22-0ubuntu0.16.04.1
- driver:  libmyodbc 5.1.10-2

### Issue

Starting with version 5.5, MySQL supports DATETIME columns with microseconds precision. pyodbc  loses the fractional seconds when writing to or reading from those columns. The following is basically copy/past/adapt from Issue #235 (describing the same thing for MSSQL):

I have the following table on my MySQL database:

```sql
CREATE TABLE pyodbc_datetime_test (pyodbc_version varchar(8) not null, inserted_at datetime(6) not null);
```

and the following test script:

```python
from datetime import datetime
import pyodbc

print('pyodbc version: %s' % pyodbc.version)
conn = pyodbc.connect("DSN=localTim", autocommit=True)
cursor = conn.cursor()
now = datetime.now()
print(now)
cursor.execute("INSERT INTO pyodbc_datetime_test VALUES (?, utc_timestamp(6))", [pyodbc.version])
cursor.execute("INSERT INTO pyodbc_datetime_test VALUES (?, ?)", [pyodbc.version, now])
cursor.execute("SELECT inserted_at FROM pyodbc_datetime_test ORDER BY inserted_at DESC")
inserted_at = cursor.fetchone()[0]
print(inserted_at)
conn.close()
assert inserted_at == now, "%s is not equal to %s" % (inserted_at, now)
```

I get the following output when running the script:

```
pyodbc version: 4.0.23
2018-06-14 11:52:07.252640
2018-06-14 11:52:07
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    assert inserted_at == now, "%s is not equal to %s" % (inserted_at, now)
AssertionError: 2018-06-14 11:52:07 is not equal to 2018-06-14 11:52:07.252640
```

**Comment by v-chojas** [comment]
Could you provide an [ODBC trace](https://www.simba.com/blog/odbc-troubleshooting-tracing/) ? It will more easily determine what is happening.

**Comment by amorphous1** [comment]
Sure - [odbc.log](https://github.com/mkleehammer/pyodbc/files/2105296/odbc.log)  contains the trace from running above test script a single time.

**Comment by v-chojas** [comment]
This appears to be bug in the MySQL ODBC driver --- it reports (via SQLGetTypeInfo) that datetime has a column size of 21, and a minimum/maximum scale of 0. Due to this, pyODBC only binds it with that size and a scale of 1, as can be seen on line 315 of your log.

In contrast, msodbcsql driver for MSSQL reports a column size of 27 and mini/max scale of 0/7 for its datetime2 type, which allows pyODBC to insert with full fractional precision correctly.

**Comment by scarytom** [comment]
The MySQL ODBC driver does indeed seem to define datetime as 21/0

https://github.com/mysql/mysql-connector-odbc/blob/3385c155b7d49d39cd5052a4b1f36185c9393ca0/driver/info.cc#L1010

**Comment by v-chojas** [comment]
Please open an issue there. Note that simply changing the hardcoded constants would break backward compatibility for those using older servers that don't have the fractional precision; that really has to be determined based on the connected server version/capabilities.

**Comment by amorphous1** [comment]
Thanks, I just sent off an email to the myodbc mailing list to open an issue there.
