### ISSUE TITLE
Error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bp91** [mkleehammer/pyodbc#411]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.12
- pyodbc: latest
- OS: ubuntu 16.04
- DB: Oracle

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

Hi, I followed the wiki in order to check the connection to a remote oracle db.

here are my files:
odbcinst.ini
```
[Oracle]
Description=ODBC for Oracle
Driver=/usr/lib/oracle/11.2/client64/lib/libsqora.so.11.1
UsageCount=1
FileUsage=1
```

odbc.ini
```
[ejabberd]
Driver = Oracle
DSN = Oracle
ServerName =  //x.x.x.x:1521/DB_SID
UserID = admin
Password = admin
```
I tried to check the connection with:
```
python -c "import pyodbc; print(pyodbc.connect('DRIVER=Oracle;DBQ=//x.x.x.x:1521/DB_SID;UID=admin;PWD=admin'))"
```

but I received first:
`Segmentation fault (core dumped)`
than
`<pyodbc.Connection object at 0x7f94cbfdd2e8>`.

What is wrong? please help. Thanks

**Comment by v-chojas** [comment]
Could you run python with `gdb` and give a stack trace (`bt`) when it crashes?

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
