### ISSUE TITLE
"Login timeout expired" on Centos 7

### ISSUE THREAD

**Issue by ttback** [mkleehammer/pyodbc#412]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7
- pyodbc: 4.0.23
- OS: Centos 7
- DB: MS SQL Server 6.01.7601.17514
- driver: ODBC Driver 17 for SQL Server

### Issue
"expected behavior": Connect to MS SQL Server's database
"observed behavior": pyodbc.OperationalError: ('HYT00', u'[HYT00] [unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

Code related to PYODBC:
````
conn = pyodbc.connect(
    r'DRIVER={ODBC Driver 17 for SQL Server};'
    r'SERVER={HOST},{PORT};'
    r'DATABASE={DATABASE};'
    r'UID={UID};'
    r'PWD={PWD}'
    )
````
I was able to connect to the Database with `sqlcmd -S {Host},{Port} -U {USER} -P {PWD} -Q "use {Database};"` so I wonder if it is me doing it wrong with conn string. My code reference was https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Windows

I can reproduce the error with sqlcmd if I remove the port from the command, so maybe the conn_string I am passing to pyodbc is not in the correct format?

**Comment by v-chojas** [comment]
Try not using `{` and `}` quoting for host and port. I.e. if host is example.com and port is 1433, try `SERVER=example.com,1433`

**Comment by ttback** [comment]
Oh, the {} is not there, it is placeholder for the question, this is the actual one:

conn = pyodbc.connect(
    r'DRIVER={ODBC Driver 17 for SQL Server};'
    r'SERVER=example.com,1111;'
    r'DATABASE=name_of_db;'
    r'UID=uid;'
    r'PWD=pwd'
    )

**Comment by ttback** [comment]
It looks like it started to work if I use ip address instead of hostname. Is there any configuration in pyodbc to make sure it resolves hostname correctly?

**Comment by v-chojas** [comment]
Hostname resolution is not the concern of pyODBC, it just passes connection string to DM and the DM passes it to the ODBC driver. Your connection string is correct and I could not reproduce this error. Please check your network DNS configuration.

**Comment by ttback** [comment]
@v-chojas yeah, closing this issue. The problem seems to be network DNS related.

**Comment by saad-gh** [comment]
> @v-chojas yeah, closing this issue. The problem seems to be network DNS related.

How did you resolve the DNS issue?

**Comment by luizfelipevbll** [comment]
> > @v-chojas yeah, closing this issue. The problem seems to be network DNS related.
> 
> How did you resolve the DNS issue?

You should use the IP instead of DNS :/
You can get that using nslookup on CLI

**Comment by khivarkar** [comment]
I used the IP instead of DNS still I am facing this issue:
[ODBC Driver 17 for SQLServer]Login timeout expired (0) (SQLDriverConnect)'

Here is my conn string:
pyodbc.connect(
        r'DRIVER={ODBC Driver 17 for SQL Server};'
        r'SERVER=IP,1433;' 
        r'DATABASE=db_name;'
        r'UID=uid;'
        r'PWD=pwd;'
    )
