### ISSUE TITLE
pyodbc with db2 i series database & sql alchemy

### ISSUE THREAD

**Issue by sidnaik03** [mkleehammer/pyodbc#418]
Please first make sure you have looked at:
### Environment

- Python: 3.5
- pyodbc: 4.0.23
- OS: Linux (Ubuntu 16.04)
- DB: IBM I series
- driver: ODBC

 I am using ibm_db_sa and as400 drivers to connect db2 for i. When I am going to fetch data from the table which is not exists in db, then without giving proper message application throws following error (Expected error is : Table does not exists or something related to that)
Segmentation fault (core dumped)

My code snippet is below:

```
def connect_db2():
    try:
        e = create_engine("ibm_db_sa+pyodbc400://u000****:XXXXXX@172.29.XXX.XX/T10050sp",
                          pool_size=20, echo=False, poolclass=QueuePool).connect()
    except Exception as ex:
        raise ex
    return e
```

```
def conn_test():
    try:
        conn = connect_db2()
        if conn:
            data =conn.execute('select * from sourcedb.customers1')
        for row in data:
            print(row)
    except Exception as ex:
        print(ex.__str__())
```

I want to use pyodbc with db2 i series database & sql alchemy. How could I achieve that ? I there any support for the same?

**Comment by v-chojas** [comment]
Try connecting with `isql` and running the same query there. If it also crashes, then the problem is in ODBC driver and not pyODBC.

**Comment by sidnaik03** [comment]
Yeah. Issue was with drivers. I have updated drivers. Now its resolved. Thanks
