### ISSUE TITLE
Incorrect Results for Int data

### ISSUE THREAD

**Issue by detroitcoder** [mkleehammer/pyodbc#42]
A select query of integer data returns incorrect results when I am running pyodbc 3.0.7 with python 2.7 on RHEL6 against a Sybase database. I do not experience this issue when running on 3.0.3

Here is a basic example of incorrect results for int data

    import pyodbc
    dbconn = pyodbc.connect("DSN=....")
    c = dbconn.cursor()
    c.execute("select 0, 1, 2")
    print c.fetchone()

    >> (210453397504, 210453397505, 210453397506)

All of the integers consistently add 2^32 * 2^7 (210453397504) to the correct value. This remains true until the value gets to 2^31 (2147483648), at which point results are correctly converted to type Long. 

When I explicitly cast the data to numeric, it returns correctly:

    c.execute("select cast(0 as numeric), cast(1 as numeric), cast(2 as numeric)")
    print c.fetchone()

    >> (Decimal('0'), Decimal('1'), Decimal('2'))

Likewise if I explicitly add a decimal to the values, it will return the correct values as Decimal instances

    c.execute("select 0.0, 1.0, 2.0")

    >> (Decimal('0'), Decimal('1'), Decimal('2'))

However when I try to cast the data as Ints, I get the same incorrect results as I do by default:

    c.execute("select cast(0 as int), cast(1 as int), cast(2 as int)")
    print c.fetchone()

    >> (210453397504, 210453397505, 210453397506)

There are a couple other users that have experienced the same issue on code.google.com
https://code.google.com/p/pyodbc/issues/detail?id=360

**Comment by mkleehammer** [comment]
Finally confirmed - I had to rebuild a new test VM.

**Comment by mkleehammer** [comment]
The problem is that unixODBC requires 2-byte wide characters (which actually matches the ODBC specification, so bravo) but sizeof(SQLWCHAR) is 4.  In fact if you run one of the unit test scripts with "-v" it should show this.  I might just hardcode to 2 for now since that is what Windows and unixODBC use and see what other driver managers people have problems with.  That will give me more information needed to choose sizes.

**Comment by mkleehammer** [comment]
git bisect points finger at 916c69e
