### ISSUE TITLE
Error returned on executemany with subquery

### ISSUE THREAD

**Issue by ayatsss** [mkleehammer/pyodbc#421]
Hi, 

I'm getting this error while using executemany:

> pyodbc.ProgrammingError: ('42000', '[42000] [Informix][Informix ODBC Driver][Informix]A syntax error has occurred. (-201) (SQLPrepare)')

In my program I have this part working well:
```
def odbc_QF(params):
	DSN = 'SYLOB7_SOC1_PRECIX'
	cnxn = pyodbc.connect(dsn = DSN)
	cursor = cnxn.cursor()
	req = """
	update bas_gamop
	set cns5 = ?
	where no_oper = ?
	and no_art matches 'S*'
	"""
	cursor.executemany(req, params)
	cursor.commit()

liste_q_fixe = [(80,1140),(120,1110),(240,1120),(360,1130),(90,1160),(90,1170),(90,1180),(90,1910),(48,1190),(48,1880)]

odbc_QF(liste_q_fixe)
```

But this part generates the error above:
```
def odbc_coeff(article, params):
	DSN = 'SYLOB7_SOC1_PRECIX'
	cnxn = pyodbc.connect(dsn = DSN)
	cursor = cnxn.cursor()
	req = """
	insert into zz_rebutgam
	select no_art, '', 1, ord_oper, 1, ?, today
	from bas_gamop
	where no_oper = ?
	and no_art[1, 2] matches '{}*'
	""".format(article)
	print(req)
	cursor.executemany(req, params)
	cursor.commit()

liste_coeff_SL = [
	(1.05, 1160),
	(1.1, 1170),
	(1.1, 1180),
	(1.1, 1910),
	(1.25, 1030),
	(1.5, 1800),
	(1, 1020)
	]

odbc_coeff('SL', liste_coeff_SL)
```

I'm using python3, pyodbc 4.0.23, informix database
Don't understand why this is not working, maybe because of the INSERT(SELECT) statement ? 

This is the output of the print(req):

> insert into zz_rebutgam
>         select no_art, '', 1, ord_oper, 1, ?, today
>         from bas_gamop
>         where no_oper = ?
>         and no_art[1, 2] matches 'SL*'

Thanks a lot

**Comment by v-chojas** [comment]
Please check your SQL syntax. https://stackoverflow.com/questions/37351347/informix-select-into-syntax-error

**Comment by mkleehammer** [comment]
I'm assuming that the article answers the question, so I'll close this.  If not, please reopen.
