### ISSUE TITLE
Cannot connect to Azure service: KeyError

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [mkleehammer/pyodbc#422]
### Environment
- Python: 3.6 x64
- pyodbc: 4.0.23
- OS: Windows 10
- DB: Azure SQL server
- driver: ODBC Driver 13 for SQL Server/SQL Server/SQL Native Client 11.0

### Issue
Cannot connect to Azure Service. Error is KeyError: 'ODBC Driver 13 for SQL Server' (or other driver name)
My connection string is:

conn = pyodbc.connect('DRIVER={ODBC Driver 13 for SQL Server};SERVER={0};PORT=1433;DATABASE={1};UID={2};PWD={3}'.format(AzureServerPrefix + '.database.windows.net', DB, User, Pwd))
accordingly to suggestions from microsoft 
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connect-query-python

Tried also other drivers SQL Server/SQL Native Client 11.0. All of them are available in my machine for ODBC x64 for system DSN. 
===============
also tried other format for connection strings that suggested under 
https://www.connectionstrings.com/sql-azure/
but have no luck as well :
'Data source name not found and no default driver specified (0) (SQLDriverConnect)')'

**Comment by v-chojas** [comment]
Try to put the connection string directly as in `pyodbc.connect('driver={ODBC Driver 13 for SQL Server};server=yourserver;database=yourdb;uid=youruser;pwd=yourpass')`, also notice that Azure SQL does not have a fixed port number so do not specify the port in the connection string.

Provide an [ODBC trace](https://www.simba.com/blog/odbc-troubleshooting-tracing/) for further assistance.

**Comment by SergiyIvanovAtGTI** [comment]
bug is not valid
