### ISSUE TITLE
Stored Procedure Fails with 'HY000', 'The driver did not supply an error!'

### ISSUE THREAD

**Issue by billmccord** [mkleehammer/pyodbc#424]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.6 x64 and 3.7.0 x64
- pyodbc: 4.0.22 and 4.0.23
- OS: Mac High Sierra and Windows Server 2016
- DB: SQL Server
- driver: ODBC SQL 17 2.0.1

### Issue

This is a very strange issue. Basically, I have a stored procedure and whenever I execute it using pyodbc I get the following error:
`pyodbc.Error: ('HY000', 'The driver did not supply an error!')`

If I execute it using SQL Operations Studio OR using SQL Server Management Studio 17, it works fine. Even stranger, if I create the stored procedure with a *different name* and the exact same SQL it works! I'm completely stumped and not convinced it is a pyodbc problem, but not sure where to go with it.

The code that executes it looks like the following:
`cursor.execute('EXEC p_build_analytics_model ?', import_id)`

Apologies that I can't provide minimal working example because the SP is quite complex and removing some of the code does seem to eliminate the problem. What doesn't make sense to me is why renaming it would allow it to succeed!

Here are all the things I have tried:

* Dropping and recreating the stored procedure (didn't help)
* Using CALL syntax instead of EXEC (didn't help)
* Hardcoding the parameter value instead of passing it (didn't help)
* Removing some of the SQL statements within the SP (through trial and error I was able to remove statements until it worked, but haven't figured out exactly which statements are the root cause yet because it is a very long procedure)
* Creating the stored procedure with a different name (this works, but it makes me nervous!)

I've also included two ODBC dumps if it helps to identify the root cause. One called SQL_error.LOG shows the error occurring when the SP is called p_build_analytics_model. The other called SQL_no_error.LOG shows no error occurring when I simply recreate the exact same SP with the name p_build_analytics_model_temp.

[SQL_error.LOG](https://github.com/mkleehammer/pyodbc/files/2190772/SQL_error.LOG)
[SQL_no_error.LOG](https://github.com/mkleehammer/pyodbc/files/2190773/SQL_no_error.LOG)

**Comment by v-makouz** [comment]
Looking at the trace it seems that the error returned from the server is:

DIAG [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The server failed to resume the transaction. Desc:7700000001. (3971) 

DIAG [01000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The transaction active in this session has been committed or aborted by another session. (3926) 

Unfortunately there are many things that can cause that, is it possible that something else is calling that stored procedure by the name? That would explain why renaming it might help.

**Comment by billmccord** [comment]
Hi @v-makouz thanks so much for having a look. I also saw that in the logs and I looked through all of the stored procedures on that DB in detail and there is no reference to that procedure except where it is named, i.e. no other procedures call that procedure. Further, this is on a testing database that only I have access to and I ran this test in isolation many times with the same result.

Do you think that perhaps this is an issue with ODBC Driver 17 and, if so, do you have any idea where I might be able to file a bug report against it? I couldn't find any official place. The best I found was thie [Technet forums](https://social.technet.microsoft.com/Forums/sqlserver/en-US/home)

There was [one issue reported there](https://social.technet.microsoft.com/Forums/sqlserver/en-US/f54d150d-949f-47db-b3ab-0862f538fb45/the-server-failed-to-resume-the-transaction-descd200000003?forum=sqldataaccess) that looked similar. I am **not** calling commit after executing my stored procedures because I assumed that they would automatically be committed. Is that a safe assumption or should I be calling commit on the connection?

It is kind of irrelevant though because I get an exception on the execute and never have an opportunity to call commit and have tested calling the stored procedure in isolation (without anything else happening on the connection before or after.)

**Comment by billmccord** [comment]
Created a question here as well:
https://social.technet.microsoft.com/Forums/sqlserver/en-US/aaf8bec5-2fad-410e-bc0c-2661b3336f88/stored-procedure-fails-always-fails-but-exact-copy-of-it-always-succeeds?forum=sqldataaccess

**Comment by billmccord** [comment]
I understand that this is a PHP issue, but I wonder if it could be related? Is it possible that pyodbc isn't calling the equivalent of 'SQLMoreResults'?
https://knowledgebase.progress.com/articles/Article/5977

**Comment by v-chojas** [comment]
> I am not calling commit after executing my stored procedures because I assumed that they would automatically be committed. Is that a safe assumption or should I be calling commit on the connection?

One point of note is that pyODBC defaults to autocommit _off_, and this may also be responsible for causing the strange error if your stored procedure itself does something with transactions. To turn autocommit _on_ (which is the default of the ODBC driver), use `autocommit=True` in `connect()`, as explained [here](https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management).

Another thing to check is if there are any triggers referencing the stored procedure.

**Comment by billmccord** [comment]
Thanks for the suggestion, I think we are making progress!

One thing that I noticed is that if I create the connection with autocommit=True and execute the following:
```
with cnxn.cursor() as cursor:
        cursor.execute('EXEC p_build_analytics_model ?', import_id)
```

Then it succeeds using the original stored procedure! However, if I create the connection without setting autocommit and adjust it dynamically like so:
```
cnxn.autocommit = True
with cnxn.cursor() as cursor:
        cursor.execute('EXEC p_build_analytics_model ?', import_id)
cnxn.autocommit = False
```

Then I get the following error:
`pyodbc.Error: ('HY000', '[HY000] [Microsoft][ODBC Driver 17 for SQL Server]Connection is busy with results for another command (0) (SQLSetConnectAttr)')`

Any idea what may be happening?

Note that because of the issue #371 I'm using `pyodbc==4.0.22`

**Comment by v-chojas** [comment]
- That behaviour is certainly indicative of the stored procedure itself doing something with transactions
- Attempting to turn off autocommit with an active transaction causes an error.
- Check the database for triggers or other objects which may be referencing the stored procedure by name

**Comment by billmccord** [comment]
Thanks for continuing to help me. I generated a script that dumped the entire DB schema and verified that there are no triggers. I also verified that there isn't any other place where this stored procedure is called and this stored procedure isn't calling any others. However, I did find two things that might be useful:

1. Exec is used in many places in the procedure to execute dynamically generated SQL. As far as I can tell though, none of the SQL is doing anything except for select intos, table alters, creating a synonym, and creating an index. Therefore, I don't think this is the culprit.

2. At the end of the procedure, there are two select statements being executed. I found [this obscure SO answer](https://stackoverflow.com/a/48802887) where it seems someone is having a similar issue. So I modified the procedure to drop the selects. Unfortunately, this also didn't help.

Attached is SQL_error_autocommit_on.LOG, the ODBC log from the test where I set autocommit to True before calling the procedure and False after. I have also attached SQL_autocommit_on_removed_selects.LOG, the ODBC log where I removed the select statements from the procedure and ran it again. It doesn't seem that there was any difference though.

I can see from the logs that I'm getting an error when I'm turning SQL_AUTOCOMMIT_OFF, but not sure where to go from here.

[SQL_autocommit_on_removed_selects.LOG](https://github.com/mkleehammer/pyodbc/files/2209374/SQL_autocommit_on_removed_selects.LOG)
[SQL_error_autocommit_on.LOG](https://github.com/mkleehammer/pyodbc/files/2209375/SQL_error_autocommit_on.LOG)

**Comment by gordthompson** [comment]
Might you (unwittingly) be dealing with [implicit transactions](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-implicit-transactions-transact-sql?view=sql-server-2017)?

**Comment by billmccord** [comment]
Alas, no... I searched the entire schema including stored procedures and found no reference to IMPLICIT_TRANSACTIONS.

**Comment by gordthompson** [comment]
In the page I cited did you see the comment

> Implicit transactions may unexpectedly be ON due to ANSI defaults. For details see SET ANSI_DEFAULTS (Transact-SQL).

**Comment by billmccord** [comment]
@gordthompson Thanks so much for helping.

I searched and didn't fine any reference to ANSI_DEFAULTS. I also ran this query:
```
SELECT @@OPTIONS AS [user_options],
       CASE WHEN @@OPTIONS & 2 = 2 THEN 'ON' ELSE 'OFF' END AS [implicit_transactions],
       CASE WHEN @@OPTIONS & 4 = 4 THEN 'ON' ELSE 'OFF' END AS [cursor_close_on_commit],
       CASE WHEN @@OPTIONS & 8 = 8 THEN 'ON' ELSE 'OFF' END AS [ansi_warnings],
       CASE WHEN @@OPTIONS & 16 = 16 THEN 'ON' ELSE 'OFF' END AS [ansi_padding],
       CASE WHEN @@OPTIONS & 32 = 32 THEN 'ON' ELSE 'OFF' END AS [ansi_nulls],
       CASE WHEN @@OPTIONS & 256 = 256 THEN 'ON' ELSE 'OFF' END AS [quoted_identifier],
       CASE WHEN @@OPTIONS & 1024 = 1024 THEN 'ON' ELSE 'OFF' END AS [ansi_null_dflt_on],
       -- all above options combined
       CASE WHEN @@OPTIONS & 1342 = 1342 THEN 'ON' ELSE 'OFF' END AS [ansi_defaults]
```
Per https://dba.stackexchange.com/questions/141374/determine-ansi-defaults-setting-on-or-off

And it said both implicit transactions and ansi defaults were off.

**Comment by v-chojas** [comment]
From

https://docs.microsoft.com/en-us/sql/t-sql/statements/set-ansi-defaults-transact-sql

"The SQL Server Native Client *ODBC driver* and SQL Server Native Client OLE DB Provider for SQL Server automatically set ANSI_DEFAULTS to ON when connecting. The driver and Provider then set CURSOR_CLOSE_ON_COMMIT and IMPLICIT_TRANSACTIONS to OFF. The OFF settings for SET CURSOR_CLOSE_ON_COMMIT and SET IMPLICIT_TRANSACTIONS can be configured in ODBC data sources, in ODBC connection attributes, or in OLE DB connection properties that are set in the application before connecting to SQL Server. The default for SET ANSI_DEFAULTS is OFF for connections from DB-Library applications."

You can retrieve the value of @@TRANCOUNT at interesting points in your code, to determine if it is indeed opening a transaction and leaving it open.

**Comment by billmccord** [comment]
I've more or less given up on this. I managed to track it down to a few 100 lines of SQL, but they are interrelated and commenting out some blocks causes it to allow the stored procedure to succeed finishing. Commenting out other blocks makes it looks like it succeeded, but I write inserts into another table to track the progress and even though it returns a success response, it actually doesn't complete all of the steps in the procedure. It's too large to debug, but I suspect it has something to do with the fact that there are a number of "Warning: Null value is eliminated by an aggregate or other SET operation" messages that occur in the procedure when I run it from SSMS or SQL Operations Studio.

I've gone ahead and ported code to C# to call the stored procedures and it is working fine. Super bizarre!

**Comment by Amadeus111** [comment]
Has anybody figured out what the problem with this unknown error? I am having the same issue. I am running a Python script to update tables in  Access (.mdb) and Excel files by using pyodbc. I did not have any problem until this week. 
Now I am having " pyodbc.Error: ('HY000', 'The driver did not supply an error!') " error. 
I have an update on Excel from Windows. Would it be related to that?
I do not want to update over 600 tables manually :( 
Any Help appreciated, thank you!

**Comment by gordthompson** [comment]
@Amadeus111 - "('HY000', 'The driver did not supply an error!')" is a generic error that can have many causes. Your environment is very different than the one that prompted this issue, so please create a [new issue](https://github.com/mkleehammer/pyodbc/issues/new) that includes a complete description of your environment and a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Amadeus111** [comment]
> @Amadeus111 - "('HY000', 'The driver did not supply an error!')" is a generic error that can have many causes. Your environment is very different than the one that prompted this issue, so please create a [new issue](https://github.com/mkleehammer/pyodbc/issues/new) that includes a complete description of your environment and a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

I created new entry. Sorry I am new to github
