### ISSUE TITLE
executemany with rows that have one value.

### ISSUE THREAD

**Issue by darindf** [mkleehammer/pyodbc#426]
I'm trying to insert into a table a list where each row is one item using a statement like

```INSERT INTO table ( c1 ) VALUES ( ? )```

I found if I format the list of values as ```[(3),(4)]``` that this would fail as this is represented by ```[3,4]```, as the type for ```type( (3) )``` (tuple with one element) is just the value in the tuple, which in this case is int. The work around is to use list instead of tuple for single element rows, i.e. ```[[3], [4]]```.

**Comment by gordthompson** [comment]
As you have discovered, `(3)` does not produce a tuple because in that context the round brackets are simply interpreted as controlling the order of operations in an expression, e.g., `(1+2)*3`. If you want to create a single-value tuple you need to add a comma, e.g., `(3,)`.

**Comment by v-chojas** [comment]
In any case, to summarise, this is not an issue in pyODBC, but rather by-design behaviour of Python language itself.
