### ISSUE TITLE
DatabaseError: Execution failed on sql 'select column1 from [table]': ('08S01', u'[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 (10054) (SQLExecDirectW)')

### ISSUE THREAD

**Issue by suganya301** [mkleehammer/pyodbc#427]
Environment
Python: 2.7
pyodbc: 4.0.23
OS: UBUNTU (version16.4)
DB: SQL Azure(12.0.2000.8)
driver: Microsoft ODBC Driver 17 for SQL Server 

Issue:

am getting below error frequently.when i try to insert/update/select.  

DatabaseError: Execution failed on sql 'INSERT INTO table(column1 ) values (value 1)': ('08S01', u'[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x2746 (10054) (SQLExecDirectW)')

DatabaseError: Execution failed on sql ' ': ('08S01', u'[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)')

**Comment by v-makouz** [comment]
Can you post ODBC trace?

This error is "connection reset by peer", which could mean a number of things, does this happen intermittently or does it always happen with a particular command/set of data?

**Comment by suganya301** [comment]
[odbc_trrace.log](https://github.com/mkleehammer/pyodbc/files/2213450/odbc_trrace.log)

attached ODBC trace (unixodbc version (2.3.1-4.1))
1. "TCP Provider: Error code 0x2746 (10054) (SQLExecDirectW)" error am getting  when i trying to insert records in parallel or in loop continuously trying to insert in azure dB .
2. "TCP Provider: Error code 0x68 (104) (SQLExecDirectW)" error am getting when my dependent  job is taking long to complete, upon the completion then when i try to update a row in Azure DB.

**Comment by v-chojas** [comment]
Azure is known to start dropping connections and timing out if you have reached usage limits.

https://docs.microsoft.com/en-us/azure/sql-database/sql-database-resource-limits#what-happens-when-database-resource-limits-are-reached

**Comment by mkleehammer** [comment]
Since 10054 is 'connection reset', I'm assuming we can close this.  Please reopen otherwise.

**Comment by dev-pasa** [comment]
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)')

Is this really connection reset? I'm getting dropped within few seconds. I'm trying to push data to Azure, I have one particular column with different characters from device snapshot. Is this also a  security policy by Azure team to prevent something like a sql injection? Is there a way to fix this?

I did look into this:
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-resource-limits#what-happens-when-database-resource-limits-are-reached

**Comment by v-chojas** [comment]
104 is also Connection Reset By Peer:

https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/errno.h

**Comment by avalanche-tm** [comment]
Is there any update on this issue? I'm having the same problem, random disconnects with the same message. DatabaseError: Execution failed on sql ' ': ('08S01', u'[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLExecDirectW)')

**Comment by v-chojas** [comment]
Doesn't have anything to do with pyODBC. You can try asking AWS support.

**Comment by aditi-dhal** [comment]
I am also receiving this same issue.I have my machine running and it is running properly but all of a sudden it gave me this error but on the next run my app was automatically able to connect without restarting my machine and read and write.But the last db write that failed was not able to complete. I am using pyodbc driver.

**Comment by v-chojas** [comment]
Doesn't have anything to do with pyODBC.

**Comment by ratna1723** [comment]
does anybody resolved this issue?
