### ISSUE TITLE
Strings 16 characters or longer are improperly inserted into MS Access Database

### ISSUE THREAD

**Issue by arenius** [mkleehammer/pyodbc#428]
Observed Behavior:

I'm trying to insert data into an MS Access .mdb file.  I'm on Linux using unixODBC with the commercial Easysoft ODBC-Access driver.  When I try to insert strings into a text column in the database if the strings are longer than 15 characters then instead of them being inserted normally the are inserted with a NULL character between each of the characters that should be there.

When I try the same thing using the unixODBC utility isql the strings are inserted correctly.

Environment:

- Python: 3.4
- pyodbc: 4.0.21
- OS: Ubuntu Linux 14.04
- DB: MS Access
- driver: Easysoft ODBC-Access

To Reproduce:

    import pyodbc

    test_values = [(''), ('abcdefghijklmno'), ('abcdefghijklmnop')]

    print('Version: {}'.format(pyodbc.version))

    create_statement = """
    CREATE TABLE test_text (
        cola TEXT
    );
    """

    insert_statement = """
    INSERT INTO test_text
    VALUES (?)
    ;
    """

    select_statement = """
    SELECT
        cola,
        char_length(cola),
	    length(cola)
    FROM
        test_text
    ;
    """

    drop_statement = """
    DROP TABLE test_text
    ;
    """

    with pyodbc.connect('dsn=emptymdb') as conn:
	with conn.cursor() as cur:
            cur.execute(create_statement)
            for string in test_values:
		cur.execute(insert_statement, string)
            cur.execute(select_statement)
            for row in cur.fetchall():
		print(row)
            #cur.execute(drop_statement)

Output from above python code:
```
Version: 4.0.21
('', 0, 0)
('abcdefghijklmno', 15, 15)
('a\x00b\x00c\x00d\x00e\x00f\x00g\x00h\x00i\x00j\x00k\x00l\x00m\x00n\x00o\x00p\x00', 32, 1)
```

Viewing this in isql:
```
SQL> insert into test_text values ('0123456789abcdefghijklmnopqrstuv');
SQL> select cola, char_length(cola), length(cola) from test_text;

-----------------------------------+------------+------------+
| COLA                             |char_length |length      |
-----------------------------------+------------+------------+
|                                  | 0          | 0          |
| abcdefghijklmno                  | 15         | 15         |
| a                                | 32         | 1          |
| 0123456789abcdefghijklmnopqrstuv | 32         | 32         |
-----------------------------------+------------+------------+

```

**Comment by v-chojas** [comment]
This appears to be related to character encoding (UTF-16 being interpreted as UTF-8 or other single-byte encoding). Can you provide an ODBC trace?

**Comment by arenius** [comment]
Here is an ODBC trace of the above test case.
[odbc.log](https://github.com/mkleehammer/pyodbc/files/2242321/odbc.log)

**Comment by arenius** [comment]
From the correspondence I've had with the driver vendor I think it may be an issue with the difference between UCS2 and UCS4 builds of Python.  I'm not really sure though.

**Comment by v-chojas** [comment]
Can you try a newer pyODBC (e.g. .22 or .23)?

**Comment by mkleehammer** [comment]
Can you try with 4.0.24, which was released today with fix for Unicode?  I don't have that driver.

**Comment by arenius** [comment]
I will try with 4.0.24.  I won't be able to work on this till next week but its still on my todo.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
