### ISSUE TITLE
Athena - Simba driver. Connection string limit of 600 chars is too short

### ISSUE THREAD

**Issue by stephenconnolly1** [mkleehammer/pyodbc#429]
I can see from the code that there is a hard limit of 600 characters on the length of the connection string. 

600 chars is generous, but when using the Simba ODBC driver with a DSN-less connection string, it's perfectly possible to exceed this limit.

I'm using STS assume role, so the driver requires a SessionToken value. Since this is about 300 characters long, it's very easy to breach the 600 char limit.
Can the buffer length be increased to say 1024??
And can the error message be updated from a simple 'too long' to include what the limit actually _is_.

**Comment by v-chojas** [comment]
The limit appears to be arbitrary --- nothing else in pyODBC places a limit of 600 characters on the connection string. Notably, there is an absence of fixed-size buffers or anything similar that could impose such limits.

PR #430 has removed the limit completely from pyODBC, please try it.

Note that driver managers and drivers may have their own limits (e.g. unixODBC's limit is 2K, and Windows' DM may have [a limit of 1K](https://msdn.microsoft.com/en-us/library/system.data.odbc.odbcconnection.connectionstring(v=vs.110).aspx))

**Comment by stephenconnolly1** [comment]
@v-chojas thanks for such a quick response. 

It's a while since there's been a release. I'm building a docker container and it would be a lot easier if this fix could be pulled in from an released package. Does @mkleehammer know when the next release is likely to be??

**Comment by gordthompson** [comment]
Just a note that the [Windows article](https://msdn.microsoft.com/en-us/library/system.data.odbc.odbcconnection.connectionstring(v=vs.110).aspx) @v-chojas cited says

> If an ODBC driver supports connection strings longer than 1024 characters, you can use a data source name (DSN) to exceed the maximum length limitation.

**Comment by mkleehammer** [comment]
#430 was released in 4.0.24.

Thanks @v-chojas for the fix
