### ISSUE TITLE
cursor.executemany() (insert) correctly fills the table but finishes with the exit code -1073741571

### ISSUE THREAD

**Issue by AlexVolkov1** [mkleehammer/pyodbc#431]
### Environment

- Python:  python-3.6.5
- pyodbc: pyodbc-4.0.23
- OS: Windows 10 x64
- DB: MsSQL server 2014 
- driver: ODBC Driver 13/17 for SQL Server; SQL Server Native Client 11.0; SQL Server

### Issue
When I use cursor.executemany() with cursor.fast_executemany = False to insert data to MSSQL table it works fine, but too slow (about 1h to write ~100000 rows).

When I use cursor.executemany() with cursor.fast_executemany = True it works fast (about 1m to write the ~100000 rows) and write exactly the same data with the first case but the process finishes with exit code -1073741571 (0xC00000FD) and error <built-in method executemany of pyodbc.Cursor object at 0x000001DE578AA210> returned a result with an error set occurs.

What's wrong with it?

Below I apply:

- an example of data for insert (file outfile.txt);

In archive "Test.zip":
- file (Create_table_for_test.sql) with creation table for insert SQL script
- file (test.py) with running exception Python script.

Hope it will help you.

Thank you.

[outfile.txt](https://github.com/mkleehammer/pyodbc/files/2223802/outfile.txt)
[Test.zip](https://github.com/mkleehammer/pyodbc/files/2222863/Test.zip)

**Comment by gordthompson** [comment]
In your post above, the first link ("Uploading outfile.txt…") simply points to this issue page. It looks like your upload may have failed.

**Comment by AlexVolkov1** [comment]
The problem returns if I convert my .py project files in .exe file by pyinstaller.

**Comment by v-chojas** [comment]
Could you elaborate and provide example repro code?

**Comment by ashutoshyadav9807** [comment]
@v-chojas We're facing same error with executemany(). It seems like some bug in executemany() type-casting. In our case, using cursor.setinputsizes() before executemany() resolved the issue.

**Comment by v-chojas** [comment]
The fast_executemany feature needs to know the types of the parameters before allocating the parameter array and binding them, and it uses SQLDescribeParam function of the driver to do so. If the driver does not support SQLDescribeParam or its limitations prevent the query from being described, then it will default to a small character type (I believe it is varchar(255)) and setinputsizes() will need to be used to specify the types of the parameters explicitly.

**Comment by keitherskine** [comment]
@v-chojas You say `fast_executemany` defaults to some nominal type if the field type cannot be determined.  I must say, that's a bit concerning.  It sounds like there could be a possibility of data loss or other odd errors.  Would it not be better if pyodbc simply raises an exception if a `fast_executemany` SQL operation cannot be executed by pyodbc with 100% confidence?  Sorry if this is going over old ground, but I have held back from using `fast_executemany` so far because there seems to be teething issues with it.  I'd much rather be given an error back if there's any possibility of the SQL update not happening correctly.  I'd rather get an error, and then add a bunch of setinputsizes() to my code than run the risk of corrupted data.

**Comment by v-chojas** [comment]
The server does conversions itself (and will do so in the non-fast_executemany case too, but a lot more of them --- which fast_executemany tries to avoid), and if the conversion is invalid, the server will return an error.

**Comment by gordthompson** [comment]
@v-chojas  re: "The server does conversions itself"
 
... but in at least some cases the conversion happens before the data gets to the server. Consider a modified case of my repro code from #295
 
```python
import pyodbc

cnxn = pyodbc.connect(
    "DRIVER=ODBC Driver 17 for SQL Server;"
    "SERVER=192.168.0.187,49242;"
    "DATABASE=myDb;"
    "Trusted_Connection=yes;"
)
crsr = cnxn.cursor()

crsr.execute("""\
CREATE TABLE #issue295 (
    lang VARCHAR(10) PRIMARY KEY, 
    word NVARCHAR(50)
    )""")

sql = "INSERT INTO #issue295 (lang, word) VALUES (?, ?)"
params = [('Greek','Ώπα')]

crsr.fast_executemany = False
crsr.executemany(sql, params)
```

When run under Python_3 with the pyodbc code from PR #467 ( cc: @v-makouz ), Wireshark shows that the Greek characters are being sent from the client to the server as UTF-16LE "Ώπα" (`0x038f 0x03c0 0x03b1`)

```
0000   00 22 68 d2 c1 c4 40 2c f4 34 c0 d3 08 00 45 00   ."hÒÁÄ@,ô4ÀÓ..E.
0010   01 55 6b 01 40 00 80 06 0b e3 c0 a8 00 b3 c0 a8   .Uk.@....ãÀ¨.³À¨
0020   00 bb c2 e9 c0 5a 87 03 ac 71 b4 14 ca 34 50 18   .»ÂéÀZ..¬q´.Ê4P.
0030   40 23 a1 da 00 00 03 01 01 2d 00 00 01 00 16 00   @#¡Ú.....-......
0040   00 00 12 00 00 00 02 00 01 00 00 00 33 00 00 00   ............3...
0050   01 00 00 00 ff ff 0d 00 00 00 00 01 26 04 00 00   ....ÿÿ......&...
0060   00 e7 ff ff 09 04 d0 00 34 fe ff ff ff ff ff ff   .çÿÿ..Ð.4þÿÿÿÿÿÿ
0070   ff 40 00 00 00 40 00 50 00 31 00 20 00 6e 00 76   ÿ@...@.P.1. .n.v
0080   00 61 00 72 00 63 00 68 00 61 00 72 00 28 00 31   .a.r.c.h.a.r.(.1
0090   00 30 00 29 00 2c 00 40 00 50 00 32 00 20 00 6e   .0.).,.@.P.2. .n
00a0   00 76 00 61 00 72 00 63 00 68 00 61 00 72 00 28   .v.a.r.c.h.a.r.(
00b0   00 36 00 29 00 00 00 00 00 00 00 e7 ff ff 09 04   .6.).......çÿÿ..
00c0   d0 00 34 fe ff ff ff ff ff ff ff 68 00 00 00 49   Ð.4þÿÿÿÿÿÿÿh...I
00d0   00 4e 00 53 00 45 00 52 00 54 00 20 00 49 00 4e   .N.S.E.R.T. .I.N
00e0   00 54 00 4f 00 20 00 23 00 69 00 73 00 73 00 75   .T.O. .#.i.s.s.u
00f0   00 65 00 32 00 39 00 35 00 20 00 28 00 6c 00 61   .e.2.9.5. .(.l.a
0100   00 6e 00 67 00 2c 00 20 00 77 00 6f 00 72 00 64   .n.g.,. .w.o.r.d
0110   00 29 00 20 00 56 00 41 00 4c 00 55 00 45 00 53   .). .V.A.L.U.E.S
0120   00 20 00 28 00 40 00 50 00 31 00 2c 00 20 00 40   . .(.@.P.1.,. .@
0130   00 50 00 32 00 29 00 00 00 00 00 00 00 e7 14 00   .P.2.).......ç..
0140   09 04 d0 00 34 0a 00 47 00 72 00 65 00 65 00 6b   ..Ð.4..G.r.e.e.k
0150   00 00 00 e7 0c 00 09 04 d0 00 34 06 00 8f 03 c0   ...ç....Ð.4....À
0160   03 b1 03                                          .±.
```

When I use `crsr.fast_executemany = True` those characters are being sent to the server as ASCII "?pa" (`0x3f 0x70 0x61`)

```
0000   00 22 68 d2 c1 c4 40 2c f4 34 c0 d3 08 00 45 00   ."hÒÁÄ@,ô4ÀÓ..E.
0010   00 75 69 fe 40 00 80 06 0d c6 c0 a8 00 b3 c0 a8   .uiþ@....ÆÀ¨.³À¨
0020   00 bb c2 e5 c0 5a 7d bb f5 d4 93 ef 7b 21 50 18   .»ÂåÀZ}»õÔ.ï{!P.
0030   3f 6d 18 d7 00 00 03 01 00 4d 00 00 01 00 16 00   ?m.×.....M......
0040   00 00 12 00 00 00 02 00 01 00 00 00 33 00 00 00   ............3...
0050   01 00 00 00 ff ff 0c 00 00 00 00 00 26 04 04 01   ....ÿÿ......&...
0060   00 00 00 00 00 a7 ff 00 09 04 d0 00 34 05 00 47   .....§ÿ...Ð.4..G
0070   72 65 65 6b 00 00 a7 ff 00 09 04 d0 00 34 03 00   reek..§ÿ...Ð.4..
0080   3f 70 61                                          ?pa
```

**Comment by keitherskine** [comment]
If I understand you correctly, @gordthompson , that looks like data corruption to me.  It's an edge case for sure, but still, it scares me that this appears to be a silent failure.  I'd much rather pyodbc blew up in this case rather than assuming the server will raise errors where appropriate.

**Comment by v-chojas** [comment]
@gordthompson you can use `UseFMTOnly=yes` in your connection string with ODBC Driver 17 for SQL Server to use a different method of SQLDescribeParam, which works for that case.

Adding a `strict` option to fast_executemany may be possible, we will think about it. If describing parameters fails, the default varchar(255) is usually not a problem, it is only in Unicode case and non-UTF-8 client that the conversion may be lossy.

**Comment by v-makouz** [comment]
@AlexVolkov1 It looks like @v-chojas PR https://github.com/mkleehammer/pyodbc/pull/482 should fix this issue, by making sure the actual error (string data, right truncation) is returned to the application (instead of unhelpful generic exception)

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
