### ISSUE TITLE
\x00 characters inserted on fast_executemany if first value is None

### ISSUE THREAD

**Issue by billmccord** [mkleehammer/pyodbc#432]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.0
- pyodbc: 4.0.22
- OS: OS X 10.13.6 and Windows 10
- DB: Azure SQL Server
- driver: ODBC Driver for Microsoft(R) SQL Server(R) 17.2.0.1

### Issue

When using fast_executemany I have observed that if the first value in a column is None then all subsequent values will have \x00 characters inserted between each character.

### Sample Code
```
import pyodbc

cnxn = pyodbc.connect(
    'DSN={};UID={};PWD={}'.format(
        DATABASE_DSN,
        DATABASE_USERNAME,
        DATABASE_PASSWORD,
    ))

test_values = [
    [None],
    ['dead'],
    ['beef']
]

with cnxn.cursor() as cur:
    cur.execute('BEGIN TRY DROP TABLE [test] END TRY BEGIN CATCH END CATCH')
    cur.execute('CREATE TABLE test ([test] [varchar](16) NULL)')
    cur.fast_executemany = True
    cur.executemany('INSERT INTO test (test) VALUES(?)', test_values)
    cur.execute('SELECT * FROM test')
    for row in cur.fetchall():
        print(row)
```

### Expected Result
This can be seen by commenting out the line `cur.fast_executemany = True`

```
(None, )
('dead', )
('beef', )
```

### Actual Result
```
(None, )
('d\x00e\x00a\x00d\x00', )
('b\x00e\x00e\x00f\x00', )
```

Please see SQL ODBC logs from Windows 10 attached.

[SQL_null_chars.LOG](https://github.com/mkleehammer/pyodbc/files/2227695/SQL_null_chars.LOG)

**Comment by logicalextreme** [comment]
It looks like `None` being the first value for a column triggers all text for that column to be encoded as UTF-16LE — which is fine if the column's an `nvarchar` or `nchar` (SQLWCHAR) but isn't a supported encoding for `varchar` or `char` (SQLCHAR), as noted [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/programming-guidelines?view=sql-server-2017#character-set-support).

As with #371 you can explicitly encode strings as `utf8` but this adds overhead that you don't want when you're trying to take advantage of `fast_executemany`.

**Comment by billmccord** [comment]
@logicalextreme You're correct. If I manually set the encoding on the strings in my test program then I don't see the \x00 characters. I also discovered that if I set the encoding on the connection for SQL_CHAR this also resolves the issue:
`cnxn.setencoding(encoding='utf-8', ctype=pyodbc.SQL_CHAR)`

I'll try this as a workaround. Fingers-crossed...

**Comment by billmccord** [comment]
Ran a few tests on my Macbook and it worked fine. Tried running the same tests on Windows and it failed with the error: `pyodbc.DataError: ('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server]String data, right truncation (0) (SQLExecute)')`

Here's the ODBC trace from the Windows machine. Is there some difference in how encodings are handled on Mac vs Windows?

[SQL_right_truncation.LOG](https://github.com/mkleehammer/pyodbc/files/2228607/SQL_right_truncation.LOG)

**Comment by logicalextreme** [comment]
Yeah, Windows is annoying with encodings (UCS2 internally I think, and either UCS2/UTF-16 for strings containing Unicode outside of the locale's character set and usually an ISO-8859 one for the locale's charset; whereas Linux and Mac should consistently use UTF-8.

From what it says in that Microsoft link it may be that you actually need to set the SQL_CHAR encoding to that of your locale rather than UTF-8 which I'd guess is probably CP1252…as a `varchar` will use one byte per character and UTF-8 could use up to 4, which might be causing the overflow on a column if you have Unicode characters? I think I saw something like this earlier actually.

I've only recently started using pyodbc again, and was using pythonnet to do SqlBulkCopy for inserts until fast_executemany came along, so I'm a little rusty and was unaware of the setencoding method. Back to the docs for me!

**Comment by billmccord** [comment]
@logicalextreme What I don't understand is why I would get different results if I set the encoding to UTF-8 on both Mac and Windows? Same exact code, data, and encoding. Why is it different?

**Comment by billmccord** [comment]
Alright, I can see that for some reason when I set the encoding to UTF-8 on SQL_CHAR, it also changes the behavior of SQL_WCHAR for some reason, but only on Windows! It doesn't change the behavior on my Mac. Here is some sample code:

```
import pyodbc

cnxn = pyodbc.connect(
    'DSN={};UID={};PWD={}'.format(
        DATABASE_DSN,
        DATABASE_USERNAME,
        DATABASE_PASSWORD,
    ))

encoding_tests = [None, 'utf-8']

with open('results.txt', 'w', encoding='utf-8') as f:
    for encoding in encoding_tests:
        f.write('Setting SQL_CHAR encoding to {}\n'.format(encoding))
        if encoding is not None:
            cnxn.setencoding(encoding=encoding, ctype=pyodbc.SQL_CHAR)
        test_values = [
            [None, None],
            ['normal', 'string'],
            ['normal'.encode('utf-8'), 'string'],
            ['凱甯', '浅岡'],
            ['凱甯'.encode('utf-8'), '浅岡']
        ]

        with cnxn.cursor() as cur:
            cur.execute(
                'BEGIN TRY DROP TABLE [test] END TRY BEGIN CATCH END CATCH'
            )
            cur.execute('CREATE TABLE test ([test1] [varchar](16) NULL, '
                        '[test2] [nvarchar](16) NULL)')
            cur.fast_executemany = True
            cur.executemany('INSERT INTO test (test1, test2) VALUES(?, ?)',
                            test_values)
            cur.execute('SELECT * FROM test')
            count = 0
            for row in cur.fetchall():
                f.write(
                    'ori1: {} len={}, ori2: {} len={}\n'
                    'res1: {} len={}, res2: {} len={}\n'.format(
                        test_values[count][0], len(test_values[count][0] or ''),
                        test_values[count][1], len(test_values[count][1] or ''),
                        row.test1, len(row.test1 or ''),
                        row.test2, len(row.test2 or ''),
                    )
                )
                count += 1

        f.write('\n\n')
```

These are the results I see on my Mac:
```
Setting SQL_CHAR encoding to None
ori1: None len=0, ori2: None len=0
res1: None len=0, res2: None len=0
ori1: normal len=6, ori2: string len=6
res1: normal len=12, res2: string len=6
ori1: b'normal' len=6, ori2: string len=6
res1: normal len=6, res2: string len=6
ori1: 凱甯 len=2, ori2: 浅岡 len=2
res1: ñQ/u len=4, res2: 浅岡 len=2
ori1: b'\xe5\x87\xb1\xe7\x94\xaf' len=6, ori2: 浅岡 len=2
res1: å‡±ç”¯ len=6, res2: 浅岡 len=2


Setting SQL_CHAR encoding to utf-8
ori1: None len=0, ori2: None len=0
res1: None len=0, res2: None len=0
ori1: normal len=6, ori2: string len=6
res1: normal len=6, res2: string len=6
ori1: b'normal' len=6, ori2: string len=6
res1: normal len=6, res2: string len=6
ori1: 凱甯 len=2, ori2: 浅岡 len=2
res1: å‡±ç”¯ len=6, res2: 浅岡 len=2
ori1: b'\xe5\x87\xb1\xe7\x94\xaf' len=6, ori2: 浅岡 len=2
res1: å‡±ç”¯ len=6, res2: 浅岡 len=2
```

These are the results I see on Windows:
```
Setting SQL_CHAR encoding to None
ori1: None len=0, ori2: None len=0
res1: None len=0, res2: None len=0
ori1: normal len=6, ori2: string len=6
res1: normal len=12, res2: string len=6
ori1: b'normal' len=6, ori2: string len=6
res1: normal len=6, res2: string len=6
ori1: 凱甯 len=2, ori2: 浅岡 len=2
res1: ñQ/u len=4, res2: 浅岡 len=2
ori1: b'\xe5\x87\xb1\xe7\x94\xaf' len=6, ori2: 浅岡 len=2
res1: å‡±ç”¯ len=6, res2: 浅岡 len=2


Setting SQL_CHAR encoding to utf-8
ori1: None len=0, ori2: None len=0
res1: None len=0, res2: None len=0
ori1: normal len=6, ori2: string len=6
res1: normal len=6, res2: string len=6
ori1: b'normal' len=6, ori2: string len=6
res1: normal len=6, res2: string len=6
ori1: 凱甯 len=2, ori2: 浅岡 len=2
res1: å‡±ç”¯ len=6, res2: æµ…å²¡ len=6
ori1: b'\xe5\x87\xb1\xe7\x94\xaf' len=6, ori2: 浅岡 len=2
res1: å‡±ç”¯ len=6, res2: æµ…å²¡ len=6
```

Key takeaways:
- When None is the first value set in a column, something messes up SQL_CHAR data encoding. Notice that the length of the string 'normal' becomes 12 instead of 6 because there are \x00 character placed in between each character indicating that it is being converted to UTF-16. If you remove the [None, None] values from the executemany parameter set, this issue goes away.
- If I change the SQL_CHAR encoding using setencoding on pyodbc, it also has an effect on SQL_WCHAR decoding on Windows. Notice that on the last test with Chinese characters the NVARCHAR characters are mangled when reading back on Windows, but fine on Mac. The VARCHAR characters are also mangled, but we expected that after putting them in a VARCHAR field.
- By setting the encoding manually on strings to be pushed into VARCHAR fields, we avoid the issues.

So, until there is a fix it seems that there are two plausible workarounds, but neither are ideal:
- Ensure that we never insert None into VARCHAR fields (no NULLs, use empty strings instead.) Unfortunately, this may affect current logic that is doing NULL checking instead of checking for NULL or empty string.
- Manually encode all VARCHAR values to utf-8 in all places where we might push VARCHARs to SQL SERVER. Unfortunately, this is a large effort as we can't just apply it on all strings since applying utf-8 encoding to NVARCHARs mangles certain characters.

**Comment by billmccord** [comment]
Manually encoding seemed to work well in the tests I ran. At least there is that...

**Comment by mkleehammer** [comment]
@v-chojas Have you looked at this?  It is related to fast_executemany.  Should we expect the WCHAR change, and only on Windows.  I haven't dug into the code for this yet.

**Comment by v-chojas** [comment]
@mkleehammer  We are investigating it along with @v-makouz  . The symptoms (lack of encoding) appear to be related to #450 too, and it seems may be fixed along with that one.

**Comment by gordthompson** [comment]
I reproduced [the original issue](https://github.com/mkleehammer/pyodbc/issues/432#issue-344403654) using Python 3.6 and pyodbc 4.0.22 on Windows, and just confirmed that the issue does not occur when running the code in PR #467
