### ISSUE TITLE
Connection string too long

### ISSUE THREAD

**Issue by a087861** [mkleehammer/pyodbc#435]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit: Windows 64-bit

- Python: 3.6.1
- pyodbc: 4.0.23
- OS: Windows
- DB: NA
- driver: NA

### Issue

I am working with a connection to hadoop that requires MANY arguments to set all of the parameters correctly.  When I create this connection string, I get an error when using pyodbc.connect() that says 'connection string too long'.   

As an attempt to debug, I tried changing line 66 of the /src/connection.cpp file to
`const int cchMax = 5000;`
and reinstall the package using `python setup.py install', but this did not fix the issue.  (I admit that I am very naive when it comes to c++)

I have tried alternative approaches to constructing my connection string but have ran into other errors as well.  For instance:
```
pyodbc.connect("Driver={Hortonworks Hive ODBC Driver}",
"allowselfsignedservercert=1",
"applysspwithqueries=1",
"asyncexecpollinterval=100",...)
```
returns 'function takes at most 1 non-keyword argument'.  Another approach was:
```
pyodbc.connect(Driver="{Hortonworks Hive ODBC Driver}",
allowselfsignedservercert="1",
applysspwithqueries="1",
asyncexecpollinterval="100",
ssp_hive.execution.engine="tez", ...)
```

but this returned 'keyword can't be an expression'.

Ideally, if I could pass this entire connection string as a single string and not hit the length limit, I think that would be my most ideal situation.

Any help is greatly appreciated!

P.S. I have tried my connection string in other languages and have successfully connected so I do not believe there is an issue with my connection string contents.

**Comment by gordthompson** [comment]
Related: PR #430

**Comment by v-chojas** [comment]
Note that you have to do `python setup.py build` first, to compile pyODBC, before installing it (it's not like a Python script where you can immediately run after editing!) I have removed the connection string limit (it is arbitrary and not actually significant - could've been left over from when there was a fixed-length buffer sometime ago) in PR430 mentioned above.

The connection string should be specified as a single parameter to the `connect()` function.

**Comment by a087861** [comment]
Thanks a ton for specifying the build portion.  After running build and checking again, everything worked like a charm.  Thanks a ton to both of you for the feedback - you guys are awesome!
