### ISSUE TITLE
cannot install pyodbc under ubuntu 16.04

### ISSUE THREAD

**Issue by SergiyIvanovAtGTI** [mkleehammer/pyodbc#436]
The problem is:
pip install pyodbc
=========
Collecting pyodbc
Installing collected packages: pyodbc
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/pyodbc.cpython-35m-x86_64-linux-gnu.so'
Consider using the `--user` option or check the permissions.

/usr/local/lib/python3.5/dist-packages$ ls -la
total 8
drwxrwsr-x 2 root staff 4096 сер  1  2017 .
drwxrwsr-x 3 root staff 4096 сер  1  2017 ..

Should manually change rights on folder...

**Comment by v-makouz** [comment]
`/usr/local/lib` is owned by root on Ubuntu, so you can either use `sudo` to install it there or use the `--user` option to install it in your home directory instead.

More info: https://stackoverflow.com/questions/42988977/what-is-the-purpose-pip-install-user
