### ISSUE TITLE
storing connection string for SQL Server tests in setup.cfg file

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#438]
In an attempt to save myself some typing, I created a "setup.cfg" file in the root of my local pyodbc repo:

```
C:\Users\Gord\git\pyodbc>dir setup.*
 Volume in drive C is OS
 Volume Serial Number is 1234-5678

 Directory of C:\Users\Gord\git\pyodbc

2018-08-10  12:58               133 setup.cfg
2018-02-08  13:08            11,410 setup.py
               2 File(s)         11,543 bytes
               0 Dir(s)  310,209,105,920 bytes free
```

which contains

```
[sqlservertests]
connection-string=DRIVER={ODBC Driver 11 for SQL Server};SERVER=.\SQLEXPRESS;DATABASE=myDb;Trusted_Connection=yes
```

Yet when I try to run a test ...

```
C:\Users\Gord\git\pyodbc>\Users\Gord\AppData\Local\Programs\Python\Python36\python.exe tests3\sqlservertests.py
```

... I get the messsage that I can use a "setup.cfg" file

```
Usage: sqlservertests.py [options] connection_string

Unit tests for SQL Server.  To use, pass a connection string as the parameter.
The tests will create and drop tables t1 and t2 as necessary.

These run using the version from the 'build' directory, not the version
installed into the Python directories.  You must run python setup.py build
before running the tests.

You can also put the connection string into a setup.cfg file in the root of the project
(the same one setup.py would use) like so:

  [sqlservertests]
  connection-string=DRIVER={SQL Server};SERVER=localhost;UID=uid;PWD=pwd;DATABASE=db

The connection string above will use the 2000/2005 driver, even if SQL Server 2008
is installed:

  2000: DRIVER={SQL Server}
  2005: DRIVER={SQL Server}
  2008: DRIVER={SQL Server Native Client 10.0}


Options:
  -h, --help            show this help message and exit
  -v, --verbose         Increment test verbosity (can be used multiple times)
  -d, --debug           Print debugging items
  -t TEST, --test=TEST  Run only the named test
```

It works if I supply the same connection string on the command line, but that's a nuisance. Am I missing something here?

**Comment by v-chojas** [comment]
I strace'd this on Linux and found that it is looking for `setup.cfg` in `tests2/tmp/setup.cfg` if you do `python tests2/sqlservertests.py` .

**Comment by v-makouz** [comment]
It looks like the comments in the tests are inconsistent, `freetdstests.py` says:

    You can also put the connection string into tmp/setup.cfg like so:

    [freetdstests]
    connection-string=DSN=xyz;UID=test;PWD=test


And in `testutils.py` there is this code:

    FILENAME = 'setup.cfg'
    KEY      = 'connection-string'

    path = join(dirname(dirname(abspath(__file__))), 'tmp', FILENAME)

So it looks like the `freetdstests` have the correct description

**Comment by gordthompson** [comment]
Thanks for the help. I relocated my setup.cfg to

```
tests3\tmp\setup.cfg
```

and 

```
tests2\tmp\setup.cfg
```

and when I invoke the tests for Python2 with ...

```
C:\Users\Gord\git\pyodbc>\Python27\python.exe tests2\sqlservertests.py
```

... the tests run fine, but when I try the same for Python3 with ...

```
C:\Users\Gord\git\pyodbc>\Users\Gord\AppData\Local\Programs\Python\Python36\python.exe tests3\sqlservertests.py
```

... I get the same "usage" message cited in my original post.

**Comment by gordthompson** [comment]
Ah, okay. The `load_setup_connection_string` functions in tests2\testutils.py and tests3\testutils.py are different. The one in tests3 calls `dirname` twice ...

```
path = join(dirname(dirname(abspath(__file__))), 'tmp', FILENAME)
```

... so `path` evaluates to ...

```
'C:\\Users\\Gord\\git\\pyodbc\\tmp\\setup.cfg'
```

... instead of ...

```
'C:\\Users\\Gord\\git\\pyodbc\\tests3\\tmp\\setup.cfg'
```

**Comment by mkleehammer** [comment]
I had put it into tmp/setup.cfg since we'd all have different setup strings.

When setup.cfg was originally introduced, it seemed like it was for local configuration and the file should not be checked in.  That is certainly not the case now since a lot of tools look for their settings in setup.cfg.

Does anyone think we should introduce a new, unrelated-to-Python configuration file for this?  Something in the root of the project, in .gitignore, and with an example you copy?

**Comment by gordthompson** [comment]
Sounds fine to me. The current approach *does* permit different connection strings for tests2 and tests3, but I'm not sure that is likely to be particularly useful.

**Comment by mkleehammer** [comment]
Merged the PR, so closing.  Thanks.
