### ISSUE TITLE
Not working with Python 3.4.3 on OS X (Vertica driver)

### ISSUE THREAD

**Issue by jeunito** [mkleehammer/pyodbc#44]
I am getting the following error when connecting to Vertica: 

```bash
>>> res = cursor.execute("select version()")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42601', '[42601] ERROR 4856:  Syntax error at or near "��������� (4856) (SQLExecDirectW)')
```

Wondering if this has been encountered before. Works on Python 2 on the same host so I doubt it's iODBC.

**Comment by mkleehammer** [comment]
Apple has stopped shipping the iODBC driver manager and everyone is recommending using unixODBC going forward.  Is that a possibility - do you have a Vertica driver?

What version of pyodbc are you using?  If it is not 3.0.10, can you try it.

Do you get the same error with all SQL such ash "select 1"?  If so, it must be Unicode related.

**Comment by jeunito** [comment]
> What version of pyodbc are you using? If it is not 3.0.10, can you try it.

Tried the latest from github (3.0.11). Same error. 

> Do you get the same error with all SQL such ash "select 1"? If so, it must be Unicode related.

Yes. 

I will try unixODBC.

**Comment by mkleehammer** [comment]
I predict it will work.  BTW, I've uploaded binaries (compiled for unixODBC) for OS X 10.10 to PyPI, so `pip install pyodbc` should grab them.

The reason I think it will work is unixODBC follows the ODBC specification and uses 2-byte UCS2 Unicode encoding, like Windows, and that's what 3.0.10 is built for now.  iODBC is apparently not doing that on your build - I would expect it is using 4-byte.  The code could handle that, but I'd need to make a flag in setup.py to set the character size.  I *will* need to do that sometime, so if you require I could start.

**Comment by jeunito** [comment]
Still getting the same but I am on OS X 10.9.5: 

```bash
(joshp3)$ sudo pip install pyodbc
Collecting pyodbc
  Downloading pyodbc-3.0.10.tar.gz (68kB)
    100% |████████████████████████████████| 69kB 2.5MB/s
Installing collected packages: pyodbc
  Running setup.py install for pyodbc
Successfully installed pyodbc-3.0.10
(joshp3)$ python odbc.py
Traceback (most recent call last):
  File "odbc.py", line 4, in <module>
    res = curr.execute("select 1")
pyodbc.ProgrammingError: ('42601', '[42601] ERROR 4856:  Syntax error at or near "�������𠁓 (4856) (SQLExecDirectW)')
```

Does it matter if I upgrade to 10.10?

**Comment by jeunito** [comment]
Ok so installed unixodbc via homebrew and ran pip install again. I still get the same error.

**Comment by mkleehammer** [comment]
Can you generate an ODBC trace for this?  I've not seen the issue.  I don't have Vertica at the moment.

**Comment by mkleehammer** [comment]
According to Vertica's (Setting the Locale for ODBC Sessions)[http://my.vertica.com/docs/5.0/HTML/Master/13632.htm] page, this should be working correctly.  unixODBC and pyodbc are both going to default to UCS2.

Any luck on the trace?  I'm at a loss so far.

**Comment by mkleehammer** [comment]
Here's something else that might be using:

http://stackoverflow.com/questions/19311687/unicode-converter-buffer-over-flow

It recommends adding DriverUnicodeType=1.  Can you try this?

**Comment by jeunito** [comment]
Thanks for helping me out on on this! I really appreciate it. 

I'll get back to you on the stackoverflow solution tomorrow. I have tried putting all sorts of settings in odbc.ini though and nothing seems to work. But I will still try this. 

Not sure how to start generating a trace. Could you give me some leads (links) on that?

**Comment by mkleehammer** [comment]
Sure: http://www.easysoft.com/support/kb/kb00945.html

**Comment by jeunito** [comment]
@mkleehammer we have just decided to use another approach instead. Thanks so much for helping out.

**Comment by JeffAMcGee** [comment]
I'm seeing this error as well on MacOS 10.11.5 .  I tested it with the same script and odbc.ini using pyodbc 3.0.10 on both python 2.7.11 and 3.5.1 . It works on python 2 and fails on python 3.  I can reproduce the failure in python 2 by passing a unicode string to execute: `execute(u"select version())"`.  This is shown in `odbc_trace_2_unicode`. Here are the traces:

https://gist.github.com/JeffAMcGee/777f5c54dd180113c40d8e21db911a42

There is a small difference on line 28 of the files, but the traces really start to differ on line 149 when SQLExecDirect is called in python 2 with the byte string and SQLExecDirectW is called in python 3 and in python 2 with a unicode string.

**Comment by JeffAMcGee** [comment]
After some more experimentation and comparing to a Linux box, I can get it to work in python 3 if I set the `VERTICAINI` environment variable, and I set `DriverManagerEncoding=UTF-16` in vertica.ini.  It is likely that this is not a bug in pyodbc. It is just hard to get the system configuration right.

**Comment by sfc-gh-martz** [comment]
> VERTICAINI

What do you set this value to?

**Comment by v-chojas** [comment]
Please see https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/ConnectingToVertica/ClientODBC/ODBCDriverSettingsForLinuxAndUnixLikePlatforms.htm
