### ISSUE TITLE
~/homebrew/include not exists

### ISSUE THREAD

**Issue by reznoa** [mkleehammer/pyodbc#440]
have to use `os.path.expanduser('~/homebrew/include')`.

**Comment by v-chojas** [comment]
Could you provide more information?

**Comment by reznoa** [comment]
python don't know '~' basicaly.
so have to expand it using 'expanduser' function.
it expand '~' to real path.
ex) ~/homebrew/include ==> /Users/reznoa/homebrew/include

**Comment by v-chojas** [comment]
How is this relevant to pyODBC?

**Comment by reznoa** [comment]
setup.py

**Comment by mkleehammer** [comment]
Fixed.  Thanks.
