### ISSUE TITLE
fatal error: sql.h: No such file or directory

### ISSUE THREAD

**Issue by Roland4444** [mkleehammer/pyodbc#441]
when pip install pyodbc 
got error 
  #include <sql.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-e89qqq9z/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-_itwd76b/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-e89qqq9z/pyodbc/

**Comment by gordthompson** [comment]
You don't have the required ODBC header files on your machine. For example, on Ubuntu you would need to do

```
sudo apt install unixodbc-dev
```

**Comment by mkleehammer** [comment]
Thanks @gordthompson .

**Comment by porthunt** [comment]
RedHat/CentOS:
```bash
dnf install unixODBC-devel
```

**Comment by paulsuk1982** [comment]
This worked for me 

yum install unixODBC-devel in rhel 7
Thanks for the suggesiton.

**Comment by Relent97** [comment]
Please how do I Install it for Windows. Currently trying to install Pyodbc in a Docker file but getting the same error. All the solutions I have seen involve running on Ubuntu.

**Comment by v-chojas** [comment]
unixODBC is not for Windows. Windows already has a driver manager.

**Comment by Relent97** [comment]
Ok thank you but how can I get the Windows ODBC  into the docker container so that my pyodbc library can fully install in the container also.

**Comment by Relent97** [comment]
This is the error below 
 " In file included from src/buffer.cpp:12:
    src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
     #include <sql.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1"

**Comment by v-chojas** [comment]
What exactly is the environment you're using? You mention Windows, but then also Docker (Linux?) and the error message you get mentions gcc and has Linux-style pathnames.

**Comment by Relent97** [comment]
so I created a virtual environment using virtual env, my current O.S is Windows and I am trying to deploy a dash app in Azure through Docker. 

This is my current syntax in the dockerfile

"FROM python:3.8.0

RUN mkdir /app4
WORKDIR /app4
ADD requirements.txt /app4/


RUN pip install -r requirements.txt


ADD . /app4/

ENTRYPOINT ["python", "app4.py"]"

and my requirements file 
"
click==7.1.1
dash==1.11.0
dash-core-components==1.9.1
dash-html-components==1.0.3
dash-renderer==1.4.0
dash-table==4.6.2
Flask==1.1.2
Flask-Compress==1.4.0
future==0.18.2
itsdangerous==1.1.0
Jinja2==2.11.1
MarkupSafe==1.1.1
numpy==1.18.2
pandas==1.0.3
plotly==4.6.0
pyodbc==4.0.30
python-dateutil==2.8.1
pytz==2019.3
retrying==1.3.3
six==1.14.0
Werkzeug==1.0.1
xlrd==1.2.0"

Hope I have clarified things a bit.

**Comment by v-chojas** [comment]
Everything you have posted suggests Linux... so which distro are you using in the docker?

**Comment by Relent97** [comment]
I don't understand what you mean by distro please. I'm really new with
this, about 2 days old

**Comment by gordthompson** [comment]
"distro" is short for "distribution", a particular variant of Linux. For example: Debian, Ubuntu, RHEL, CentOS, etc..

**Comment by Relent97** [comment]
I want to use Ubuntu version 18.04, thank you for mentioning this made me try out a few things. At the moment this is what my docker file looks like 

FROM python:3.8.0

FROM ubuntu:18.04


RUN apt-get update && apt-get install -y \
    curl apt-utils apt-transport-https debconf-utils gcc build-essential g++-5\
    && rm -rf /var/lib/apt/lists/*

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list


RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql unixodbc-dev
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"

RUN apt-get update && apt-get install -y \
    python-pip python-dev python-setuptools \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN apt install python3.8

RUN pip install --upgrade pip





RUN mkdir /app4
WORKDIR /app4




ADD requirements.txt /app4/


RUN pip install -r requirements.txt


ADD . /app4/

ENTRYPOINT ["python", "app4.py"]

**Comment by v-chojas** [comment]
> Ubuntu

See Gord's comment from Aug 15 above.

**Comment by Relent97** [comment]
Hi v-chojas and Gord unfortunately I can't use the suggestion because I am using cmd on Windows 10. The O.S i am using to build the docker is windows. Is there a windows CMD version for sudo apt install unixodbc-dev. Or will I have to build the docker image with a machine running with Ubuntu.

**Comment by v-chojas** [comment]
The commands you posted above (which includes invocations of `apt`!) are clearly Linux commands.
It is still very unclear what you are trying to accomplish here

**Comment by Relent97** [comment]
Hi v-chojas yes it was Linux, my apologies I was actually very confused about how docker works.
I did find a way around the problem. Thank you

**Comment by funcelotwork** [comment]
> You don't have the required ODBC header files on your machine. For example, on Ubuntu you would need to do
> 
> ```
> sudo apt install unixodbc-dev
> ```

still, works. yeas passes, something stays still

**Comment by JanuaryThomas** [comment]
sudo yum install unixodbc-*

**Comment by Hestaron** [comment]
@akshaybhan23  or @Relent97  how did you solve the problem?

I get the same error when trying to build a docker container with pyodbc. When I run
`RUN apt install unixodbc-dev`
I get the warning "apt does not have a stable CLI interface. Use with caution in scripts.
Then I get the error: "E: Unable to locate package unixodbc"

I'm using a windows computer but creating a dockerfile (in Linux).


```
FROM python:3.8

EXPOSE 8080

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Get the required ODBC header files
RUN apt install unixodbc-dev

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install --upgrade pip && \
python -m pip install -r requirements.txt

WORKDIR /app/
ADD augment.py augment_functions.py ./
ADD reference/ reference/
ADD models/ models/
ADD queries queries/

# During debugging, this entry point will be overridden. 
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "-k", "uvicorn.workers.UvicornWorker", "augment:app"]

```

**Comment by hecomlilong** [comment]
I got the following error when I build my golang project on centos7
# github.com/alexbrainman/odbc/api
../../pkg/mod/github.com/alexbrainman/odbc@v0.0.0-20200426075526-f0492dfa1575/api/api_unix.go:14:18: fatal error: sql.h: No such file or directory
 // #include <sql.h>
                  ^
compilation terminated.
make: *** [linux] Error 2

and just execute the following command to fix it
sudo yum install unixODBC-devel

**Comment by thyagorc-edd** [comment]
tks to you all. the simple yum install unixODBC-devel solved the problem!

**Comment by northtree** [comment]
for osx: `brew install unixodbc`

**Comment by antman2** [comment]
@Hestaron 
> I get the same error when trying to build a docker container with pyodbc. When I run `RUN apt install unixodbc-dev` I get the warning "apt does not have a stable CLI interface. Use with caution in scripts. Then I get the error: "E: Unable to locate package unixodbc"

You can reproduce your error by running the following:
```sh
docker run -it --rm python:3.8 apt install unixodbc-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package unixodbc-dev
```

What this means is that there's no catalog entry for `unixodbc-dev` in the image's apt cache entries. This is because temp files and caches are usually stripped out of Docker images to reduce their image size - they're wasted space and lead to larger downloads.

You can verify this by running the following, which repopulates the apt cache and then installs `unixodbc-dev` successfully:

```sh
docker run -it --rm python:3.8 /bin/bash -c "apt update ; apt install --yes unixodbc-dev"
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [180 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
Fetched 8573 kB in 3s (3358 kB/s)                         
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libodbc1 odbcinst odbcinst1debian2
...
```

To fix this in your `Dockerfile` use:

```Dockerfile
# Get the required ODBC header files
RUN \
    apt update && \
    apt install --yes unixodbc-dev
```

To make you own local images smaller you can also follow this up with `apt-get clean`, i.e.:

```Dockerfile
# Get the required ODBC header files
RUN \
    apt update && \
    apt install --yes unixodbc-dev && \
    apt-get clean
```
