### ISSUE TITLE
Wiki documentation needs an update?

### ISSUE THREAD

**Issue by ruebrenda** [mkleehammer/pyodbc#443]
### Environment

- Python: 2.7.12
- pyodbc: 4.0.24
- OS: Mac OS X 10.12.6 (Sierra)
- DB: SqlServer
- driver: freetds 1.00.94 with unixodbc 2.3.7

### Issue

After following the instructions at https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Mac-OSX and banging my head against the wall for a few hours, I discovered I had two odbc.ini files and two odbcinst.ini files. One set in /usr/local/etc and another set in /usr/local/Cellar/unixodbc/2.3.7/.bottle/etc. I edited the unixodbc set and could not get my python connection to work. After editing the other set, it worked as expected.

Maybe a mention in the doc is warranted.

**Comment by v-makouz** [comment]
The Wiki page suggests checking `odbcinst -j` to determine the correct location of odbcinst.ini, was it pointing at the wrong one?

**Comment by ruebrenda** [comment]
Hmmm. It was... but I also had a terrible time installing and a bit of a mess from a previous attempt to use pymssql. So maybe something was off. I ended up removing everything and starting over and it's now reporting the right location. Sorry for the false alarm.
