### ISSUE TITLE
Cache select query

### ISSUE THREAD

**Issue by romkazor** [mkleehammer/pyodbc#445]
Hello guys. I used a simple code to print every n seconds result from db:

```
with pyodbc.connect(**odbcconnection) as cnxn:
    cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
    cnxn.setencoding(encoding='utf-8')
    while True:
        cursor = cnxn.cursor()
        time.sleep(2)
        cursor.execute("SELECT * FROM table GROUP by `name` DESC LIMIT 100")
        rows = cursor.fetchall()
        for row in rows:
            print(row)
```
All ok, but if i change some information on db its nothing change when print show output
Only if i restarted script i see a changed iformation

Whats i am doing wrong?! Thanks.

**Comment by keitherskine** [comment]
Without an `ORDER BY` clause on your SQL, the results from the query are indeterminate, particularly so with a LIMIT on it.  Put an `ORDER BY` clause on the SQL query and try again.

(also, minor point, but the line `cursor = cnxn.cursor()` does not need to be in the loop, it could be placed before the `while` statement)

**Comment by gordthompson** [comment]
I was able to reproduce your issue under MySQL. You can ensure that you get the latest results by adding

```python
cnxn.rollback()
```

at the end of your `while True:` loop.

**Comment by romkazor** [comment]
Thanks for answer but its same.

**Comment by romkazor** [comment]
Big thanks guys!!! The position cnxn.cursor() dose note mater in that case but cnxn.rollback() solved problem.

**Comment by gxara** [comment]
I had the same problem and solved it by adding rollback() after every select query.
It took me a long time to figure that it was some kind of session cache with pyodbc (my initial belief was that the sql server instance was with RESULT_SET_CACHING on).
Is this behavior expected? Coudn't find anything related to cache on docs.

**Comment by keitherskine** [comment]
@gxara When the database connection is originally established, if the `autocommit` parameter is set as False (the default), all SELECT queries will potentially hold locks on the relevant tables until either a commit or rollback is called to complete the database transaction.  Hence, when a subsequent SELECT query on the same table is made, it might be blocked by the first query.
Adding rollback() after each query is a good solution, or perhaps you just need to set `autocommit=True` on your original call to `pyodbc.connect()`.

**Comment by gxara** [comment]
> @gxara When the database connection is originally established, if the `autocommit` parameter is set as False (the default), all SELECT queries will potentially hold locks on the relevant tables until either a commit or rollback is called to complete the database transaction. Hence, when a subsequent SELECT query on the same table is made, it might be blocked by the first query.
> Adding rollback() after each query is a good solution, or perhaps you just need to set `autocommit=True` on your original call to `pyodbc.connect()`.

Make sense! Thanks for the explanation @keitherskine
