### ISSUE TITLE
Use a common tests3/sqlservertests.py for multiple drivers?

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#452]
I noticed that there was a tests2/freetdstests.py but no tests3/freetdstests.py. I wanted to see how up-to-date the FreeTDS support was, so instead of cloning tests2/freetdstests.py (which seemed quite old) I cloned tests3/sqlservertests.py and applied the minimal tweaks it to make it run. It worked quite well: out of 208 tests there were only 3 errors and 2 failures.

Given the massive duplication between my tests3/freetdstests.py and tests3/sqlservertests.py, it occurs to me that it might be good to simply add conditional logic to tests3/sqlservertests.py for multiple SQL Server drivers. We could add a function to inspect `cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)` to see if we're using

- msodbcsql ("ODBC Driver x for SQL Server"),
- FreeTDS, or
- some other driver (e.g., OpenLink's offering)

... and then tweak the tests accordingly.

Does that sound like the best approach?

**Comment by mkleehammer** [comment]
I think it is a great idea.  It might be easier to use if we could shorten it by using a property or something.  What if we had a property just named `driver`?

    ddl_rowcount = (0 if self.driver == 'freetds' else -1)

**Comment by gordthompson** [comment]
Thanks for the feedback.

I like the function because if I fat-finger the driver tag `self.driver_type_is('freedts')` will throw an exception whereas `self.driver == 'freedts'` will simply be False.

Of course, we could just call the function `driver` but I thought `driver_type_is` was a bit more descriptive.

**Comment by mkleehammer** [comment]
Merged - thanks.  I guess I should add "Closes xxx" comments when I squash and merge.
