### ISSUE TITLE
Is there a way to remove a single output converter function?

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#457]
The Connection object does have the [.clear_output_converters](https://github.com/mkleehammer/pyodbc/wiki/Connection#clear_output_converters) method to remove all output converter functions, but there doesn't seem to be a way to remove just one specified output converter function, e.g.,

```python
cnxn.add_output_converter(pyodbc.SQL_WVARCHAR, decode_sketchy_utf16)
# do stuff
# ...
# restore default behaviour for SQL_WVARCHAR
cnxn.remove_output_converter(pyodbc.SQL_WVARCHAR)
```

I tried using

```python
cnxn.add_output_converter(pyodbc.SQL_WVARCHAR, None)
```

but after that if I try to retrieve a SQL_WVARCHAR I get

> TypeError: 'NoneType' object is not callable

**Comment by v-chojas** [comment]
I agree that it's reasonable to expect setting None to remove the output converter for that type.
