### ISSUE TITLE
fast_executemany causes a core dump

### ISSUE THREAD

**Issue by liudvikasakelis** [mkleehammer/pyodbc#459]
## Brief

Hi, I checked out the other issues, there are some similarities, but I think mine is unique enough. Essentialy, I get a core dump when and only when I `executemany` with `fast_executemany = True`. 

### Environment

- Python: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531] on linux
- pyodbc:  4.0.24.0
- OS: Arch Linux (4.18.5-arch1-1-ARCH kernel)
- DB: Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64) 
	Mar 18 2018 09:11:49 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
- driver: unixodbc 2.3.7-1, freetds 1.00.96-1

### Issue
Check out my small script to reproduce:

    import pyodbc 

    cnxn = pyodbc.connect(
        'Driver={FreeTDS};Server=192.168.0.0;Database=DB;Port=1433;UID=uid; PWD=pwd;',
        autocommit=True
    )

    crsr = cnxn.cursor()
    crsr.execute("CREATE TABLE terp (rn INT, OTP NVARCHAR(500));")
    crsr.fast_executemany = True

    values = [(1, 'one'), (2, 'two')]
    insert_query = "INSERT INTO terp VALUES (?, ?);"

    crsr.executemany(insert_query, values)

    cnxn.close()

I execute this with python and get 

    Segmentation fault (core dumped)

Whether I run as a script or interactively. The core dump doesn't say much to me, and I'm afraid I can't attach it because of my credentials in it. The table gets created, and running interactively confirms that it's the `executemany` that crashes everything.

**Important note:** everything works a-ok with `crsr.fast_executemany = False`.

**Comment by v-makouz** [comment]
This may be similar to https://github.com/mkleehammer/pyodbc/issues/381, it seems that FreeTDS might not support parameter arrays, which fast_executemany relies on, that user was able to resolve the problem by switching to Microsoft ODBC Driver. 

I tried your repro script with the Microsoft ODBC Driver 17.2 on Windows 10 and Ubuntu 17.04 and it worked correctly for python 2 and 3, so if that's an option I would recommend using that one.

**Comment by mkleehammer** [comment]
Has anyone run fast_executemany with valgrind or something similar?

I'm going to close this for now since we think it is a driver issue.
