### ISSUE TITLE
Query: DSN connection without login credentials

### ISSUE THREAD

**Issue by Fraser1994** [mkleehammer/pyodbc#460]
Whilst reading the [following section of the wiki](https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Windows#using-a-dsn) you mention that DSN's 'possibly' store login credentials which would mean there is no need to pass UID and PWD when using connect() if a DSN is supplied. When is this the case? Is it only when the login credentials are your windows credentials? (is Trusted_Connection defaulted to yes when you do not supply UID and PWD?)

I have a DB connection I'm looking to set up and don't want to hard code in db credentials. I am aware there are several ways I could abstract the credentials away (one method being the use of environment variables) but I wondered if there was an even better way I can do this using the DSN I have already configured on my laptop.

**Comment by v-chojas** [comment]
It is driver-dependent. What driver are you using?

**Comment by Fraser1994** [comment]
Its a ms sql server

[Microsoft][SQL Server Native Client 11.0][SQL Server]

**Comment by v-chojas** [comment]
That driver does not store PWD in the DSN, only UID.
You can set Trusted_Connection=Yes in the DSN to connect without supplying credentials, if you have Windows Integrated authentication set up.
