### ISSUE TITLE
Cannot query data from Teradata using pyodbc after upgrading Python from 2.7.12 to 3.6.3 on Linux

### ISSUE THREAD

**Issue by ChanatP** [mkleehammer/pyodbc#462]
Hi,

### Environment
- Python: 64 bit version 3.6.3
- pyodbc: 4.0.17
- OS: Linux Red Hat 4.4.7-1
- DB: Teradata
- driver: UnixODBC 2.3.4

### Issue
I cannot query data from Teradata DB after upgrading Python from 2.7 to 3.6.

>>> pyodbc.pooling=False
>>> con=pyodbc.connect('DSN=TERAPROD_WH',autocommit=True)
>>> cur=con.cursor()
>>> cur.execute('select top 1 parm1 from db.table1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY000', 'The driver did not supply an error!')

I checked whether I have access to the driver as below.
>>> print(os.access('/opt/teradata/client/16.00/odbc_64/lib/tdata.so', os.R_OK))
True

However, I was able to run the same SQL as above without error when using Python 2.7.12.
What could be the problem?

Thanks.

**Comment by v-chojas** [comment]
Post the ODBC traces with Python 2 and 3, and then you can compare them to see the difference.

**Comment by mkleehammer** [comment]
Shoot.  I'm guessing the encoding of the connection string.  If you could get two ODBC traces, that would help a lot.

**Comment by abitrolly** [comment]
[Getting ODBC traces](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log#linux).

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
