### ISSUE TITLE
can we download images in sql server using pyodbc??. My Sql sever has a table with paths to the files in it hosted on amazon rds.

### ISSUE THREAD

**Issue by narayana1043** [mkleehammer/pyodbc#468]

**Comment by v-chojas** [comment]
No. In your case pyODBC will let you access the database and retrieve those paths. What you do with the paths is beyond the scope of this project.

**Comment by narayana1043** [comment]
Thanks chojas, I was actually able to download the data from the azure storage containers and then use the paths.
