### ISSUE TITLE
Problems with detecting parameter markers

### ISSUE THREAD

**Issue by jamartinh** [mkleehammer/pyodbc#47]
pyodbc.ProgrammingError: ('The SQL contains 0 parameter markers, but 12 parameters were supplied', 'HY000')

I have this problem when using insert into x values (?,?)

**Comment by jamartinh** [comment]
It seems is a problem with ODBC API ?

**Comment by keitherskine** [comment]
If you really want help with this issue Jose, you're going to have to provide a lot more information.  What version of pyodbc are you using?  What system are you running on (Windows/Linux)?  What version of Python are you using?  Better still, provide some sample code that demonstrates the error.

**Comment by jamartinh** [comment]
Hello keitherskine, thanks for reply.
Fortunately, I found the problem. The database where I was trying to make an insert (Hive) does not support insert into (current version) and it returned some code that the ODBC API can't understand. The problem is that in this case, pyodbc as pypyodbc returns that the problem is in the wrong number of parameters instead of just returning unkown error simply or compile error.

I had to step into pyodbc source to see the problem.

Thanks,
Jose

**Comment by keitherskine** [comment]
You found the source of the issue?  Excellent.  Is it worth letting everybody know what the error you received was, and what line of the pyodbc source code was affected by this?  That would be helpful.

**Comment by jamartinh** [comment]
https://github.com/mkleehammer/pyodbc/blob/master/src/params.cpp#L653

function bool PrepareAndBind

The errors raises in:
https://github.com/mkleehammer/pyodbc/blob/master/src/params.cpp#L731

But the problems is in the value of variable ret. ODBC API returns that the query string is good. Maybe the problem is that Hive does not return an error.

**Comment by mkleehammer** [comment]
Perhaps the error message could be updated, but it does tell you what you need to know:

> The SQL contains 0 parameter markers, but 12 parameters were supplied

Parameter markers are the question marks "?".  There are no question marks in the SQL (0 parameter markers) but you provided 12 parameters.
