### ISSUE TITLE
executemany use too long memory 

### ISSUE THREAD

**Issue by gromoc** [mkleehammer/pyodbc#474]
Hi,
I'm using pyodbc whith executemay and its configuration:
"cursor.fast_executemany = True"
I have a problem with the memory, when insert a tuple with more than 400 thousend rows my script use 800MB of ram memory.

Can I low the consumition of memory?

### Environment
 
- Python: 
- pyodbc: 
- OS: Windows 10 x64
- DB: SQL Server 2017
- driver: ODBC Driver 13 for SQL Server

Thank you

**Comment by v-chojas** [comment]
`fast_executemany` is fast because it constructs the entire array of parameters in memory and writes it to the server in a single call. This necessarily means you must have enough memory to hold the entire parameter array. To reduce memory consumption, you can split your rows into blocks of _n_ and insert those with fast_executemany. You can experiment with _n_ to determine the balance between memory use and speed that you desire.

**Comment by a-rosenberg** [comment]
Hello, 

I'm seeing the same problem with the executemany method on tiny chunks of data when in `fast_executemany = True`.  I originally tried doing 1000 rows at a time but it error'ed out immediately.  It tries once with 10 rows (a model with only 5 small columns) before throwing a MemoryError:

```
  File "sandbox.py", line 86, in insert_to_table_executemany
    cursor.executemany(insert_sql, data)
MemoryError
```

I brought it down to 5 rows at a time without throwing the MemoryError.  However, if I increased the chunk to 10, it immediately throws again.

To follow suit from the original poster; my environment is:
- Python 3.6
- Using pyodbc 4.0.24 (also tried 4.0.22 and 4.0.19)
- Windows 10 x64
- SQL Server 2017
- ODBC Driver "SQL Server"

**Comment by v-chojas** [comment]
How wide are your rows? What's the table schema/types of the parameters you're inserting?

**Comment by a-rosenberg** [comment]
Thank you for checking this out!

The row is 5 columns wide.

The table schema: 
```
CREATE TABLE TA_EmployeeIds
(
	EmployeeId NVARCHAR(24) NOT NULL PRIMARY KEY,
	PreferredName NVARCHAR(120) NULL,
	WorkerType NVARCHAR(30) NULL,
	WorkerActive INT NULL,
	BusinessTitle NVARCHAR(140) NULL
);
```

**Comment by keitherskine** [comment]
If you're using the ODBC that's called "SQL Server", be aware that's a very old driver.  You may want to try the latest Microsoft ODBC driver ("ODBC Driver 17 for SQL Server"), download here:
https://www.microsoft.com/en-us/download/details.aspx?id=56567

**Comment by v-makouz** [comment]
I've attempted to reproduce this, but was able to insert 2.000.000 rows with fast_executemany with no issues, even in low memory conditions I saw increase in swapping, but no memory errors. Do you have a repro script I could try?

**Comment by a-rosenberg** [comment]
Thanks for the tips on this.  It appears that the memory issue is only related to the older, "SQL Server" driver.  Finally got the newer driver up and it solved the MemoryError.

Aaron
