### ISSUE TITLE
Fetching NULL in DATE column gives ValueError: year 0 is out of range

### ISSUE THREAD

**Issue by paul-lilley** [mkleehammer/pyodbc#475]
### Environment - where the ValueError is given
- Python: Python 3.6.5
- pyodbc: 4.0.25b14 (compiled against unixODBC 2.3.7)
- OS: Red Hat Enterprise Linux Server release 7.5 (Maipo) 3.10.0-862.11.6.el7.x86_64
- DB: DB2 v10.5.0.7
- driver: unixODBC 2.3.7

### Issue
When fetching NULL from a nullable DATE column (or a DATE variable set to NULL) pyodbc raises
ValueError: year 0 is out of range
I'd expect it to return None (which it in fact does when run in Anaconda on Windows against the same DB2).  I've not tested against other databases.

Code to recreate the issue:
```python
import pyodbc

if __name__ == '__main__':
    expected = None
    create_var = "CREATE VARIABLE null_date DATE DEFAULT NULL;"
    sql_select = "SELECT null_date FROM sysibm.systables fetch first 1 row only;"
    drop_var = "DROP VARIABLE null_date;"

    con = pyodbc.connect("DSN=XXXXXX;UID=XXXXXX;PWD=XXXXXX;")

    cursor = con.cursor()
    cursor.execute(create_var)
    try:
        row = cursor.execute(sql_select).fetchone()
        result = row[0]
        if result != expected:
            print(f'Null in a DATE column returned {result} instead of the expected {expected}')
        else:
            print('OK')
    finally:
        cursor.execute(drop_var)
```

**Comment by paul-lilley** [comment]
unixODBC log attached.
[sql_pyodbc_linux.log](https://github.com/mkleehammer/pyodbc/files/2498482/sql_pyodbc_linux.log)

ODBC log from windows (where the issue does not appear with pyodbc 4.0.24 installed from pypi)
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/2498487/SQL.LOG)

**Comment by paul-lilley** [comment]
I can workaround with an output converter function:
def null_date_converter(value):
    val_str = value.decode('utf-8')  # ? is it really utf-8
    #print(f'{__name__} value: {val_str}')
    if value is None:
        return None
    else:
        return datetime.datetime.strptime(val_str, "%Y-%m-%d").date()
con.add_output_converter(pyodbc.SQL_TYPE_DATE, null_date_converter)

Although the workaround behaves OK on both platforms it is not an ideal solution.

**Comment by paul-lilley** [comment]
Dug a bit more - the problem appears to be
sizeof(SQLLEN) != sizeof(SQL_NULL_DATA)
which means that the returned NULL is not picked up in getdata.cpp by
if (cbFetched == SQL_NULL_DATA)
        Py_RETURN_NONE;
(cbFetched is defined as SQLLEN)

**Comment by paul-lilley** [comment]
Compiler warnings that I failed to notice last night:
src/connection.cpp: In function ‘PyObject* Connection_getinfo(PyObject*, PyObject*)’:
src/connection.cpp:835:40: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         SQLUINTEGER n = *(SQLUINTEGER*)szBuffer; // Does this work on PPC or do we need a union?
                                        ^
src/connection.cpp:848:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         result = PyInt_FromLong(*(SQLUSMALLINT*)szBuffer);

**Comment by paul-lilley** [comment]
The NULL detection for output converters seems to work, GetDataUser calls ReadVarColumn which uses this:
```c++
if (ret == SQL_SUCCESS && (int)cbData < 0)
{
    // HACK: FreeTDS 0.91 on OS/X returns -4 for NULL data instead of SQL_NULL_DATA
    // (-1).  I've traced into the code and it appears to be the result of assigning -1
    // to a SQLLEN.  We are going to treat all negative values as NULL.
    ret = SQL_NULL_DATA;
    cbData = 0;
}
```
rather than a direct comparison of cbData to SQL_NULL_DATA - note also the explicit cast (int)cbData.
I confess that I don't fully understand why the explicit cast to int is needed.

I'm tempted to suggest replacement of the current NULL test in GetDataTimestamp (and presumably any other places where we check for NULL from SQLGetData) with that used in ReadVarColumn, i.e.
replace
```c++
if (cbFetched == SQL_NULL_DATA)
```
with
```c++
if ((int)cbFetched < 0)  // HACK: FreeTDS 0.91 on OS/X returns -4 for NULL data instead of SQL_NULL_DATA (-1)
```


Does this sound reasonable?  If so I'm happy to try putting together a pull-request.
I'd also appreciate any deeper insight into what is really going on here, explicitly casting to int seems to fix the issue but feels a bit hackish.

**Comment by paul-lilley** [comment]
Hi, thanks for the comment.
I agree that it looks like a 32/64bit issue (or possibly unsigned/signed long).
I'm pretty sure I have odbc compiled as 64bit:
```-sh-4.2$ odbcinst -j
unixODBC 2.3.7
DRIVERS............: /usr/local/unixODBC/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/unixODBC/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/unixODBC/etc/ODBCDataSources
USER DATA SOURCES..: /home/xxxxxx/xxxxxx/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

**Comment by v-chojas** [comment]
That further narrows it down to the ODBC driver, the unixODBC configuration appears correct.

**Comment by paul-lilley** [comment]
I think I've found the problem, as you suggested in the ODBC driver.
I'd incorrectly installed the DB2 driver as the 64bit CLI driver (libdb2.so) which is also a 32bit ODBC driver, rather than the specific 64bit ODBC Manager driver (libdb2o.so).
This mistake was hidden in the logging from unixODBC which explictly casts the SQLLEN to int before logging it.  I'll put a patch request together to unixODBC to improve the logging and show the SQLLEN as a long if it is defined as such.
I think the change in pyodbc I suggested above is this not required for my problem, though someone who uses FreeTDS 0.91 on OS/X may get some mileage from it.

Thanks for your input @v-chojas !

**Comment by manjunathsudheer666** [comment]
What is the workaround for this error?

**Comment by 8orbs** [comment]
same question

**Comment by chinmaykel** [comment]
@paul-lilley @v-chojas 
How were you able to establish that TRACE which gave you the _cbFetched_ value?

**Comment by v-chojas** [comment]
https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log ?
