### ISSUE TITLE
Pyodbc unresponsive, 100% CPU, fast_executemany=True

### ISSUE THREAD

**Issue by MoorsTech** [mkleehammer/pyodbc#476]
### Environment

- Python: 2.7.12
- pyodbc: 4.0.24
- OS: Ubuntu 16.04
- DB: SQL Server 2017 Developer (64bit) v14.0.1000.169
- driver: SQL Server ODBC driver 17.2.0.1

### Issue
TL;DR
Pyodbc locks up completely. Timeouts and ctrl+c are not honored, CPU usage sticks to 100% and the `executemany` method never returns (I've left it running for over a week in one case).

To reproduce this:

1. Create a table with IGNORE_DUP_KEY = ON
2. Use a dataset with duplicate primary keys
3. Insert using fast_executemany = True
4. Use batch sizes > 100k (go with 500k to be sure)
5. Its seems to be sufficient for the duplicate primary keys to show up in the same cursor. Committing transactions between batches does not make a difference.

```
cursor = conn.cursor()
cursor.fast_executemany = True
cursor.executemany('INSERT INTO "db".dbo."TestTable" ("id", "some_val") VALUES(?, ?)', [(1, 123), (2,124),(...)])
# cursor.commit() # optional, pyodbc will hang either way
cursor.executemany('INSERT INTO "db".dbo."TestTable" ("id", "some_val") VALUES(?, ?)', [(1, 123), (2,124),(...)])
cursor.commit()
```
In my case, batch sizes of at least 80k rows are required. Smaller batches (say ~1k) will still run fine, alas extremely slowly (about 1% of normal throughput).
The issue is also limited to inserts with the fast_executemany=True option. Slow motion batch inserts without the fast_executemany option still work.

My experience with pyodbc and MS SQL servers is limited, but my expectation would've been for this to run regardless of the number of duplicate primary keys.

**Comment by gordthompson** [comment]
If you are using unixODBC from the Ubuntu 16.04 repositories (version 2.3.1) then consider upgrading to the latest stable release (version 2.3.7) and see if it works any better. There have been a number of bugs fixed in unixODBC since 2.3.1 was released.

FWIW I just tried using pyodbc 4.0.24 and unixODBC 2.3.7 under Python 2.7.12 to run

```python
import pyodbc

cnxn = pyodbc.connect(
    'DRIVER=ODBC Driver 17 for SQL Server;'
    'SERVER=192.168.0.179,49242;'
    'DATABASE=myDb;'
    'UID=sa;PWD=_whatever_;',
    autocommit=True
)
crsr = cnxn.cursor()

if 0 == crsr.execute("SELECT COUNT(*) FROM sys.tables WHERE name='issue476'").fetchval():
    crsr.execute("CREATE TABLE issue476 (id INT PRIMARY KEY WITH (IGNORE_DUP_KEY = ON), some_value INT)")

params = [(x, x*2) for x in range(100000)]
sql = "INSERT INTO issue476 (id, some_value) VALUES (?,?)"
crsr.fast_executemany = True
crsr.executemany(sql, params)
    
cnxn.close()
```

and it seems to be working fine for me.

**Comment by MoorsTech** [comment]
Interesting, yes, upgrading unixODBC to 2.3.7 seems to have solved the issue for me. I can't reproduce it post upgrade anyway.

**Comment by MoorsTech** [comment]
Yup, upgrading to 2.3.7 from 2.3.1 seems to have resolved the issue. I can't reproduce the problem anymore at any rate.
