### ISSUE TITLE
Executing sql with parameters results in error

### ISSUE THREAD

**Issue by alexsilva** [mkleehammer/pyodbc#477]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7
- pyodbc:  4.0.24
- OS:  Windows 10 x64
- DB: Sql Server 2016
- driver: Sql Server 
- Django 1.9.9
- Django backend: https://github.com/michiya/django-pyodbc-azure

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

Excerpt from code that generates sql:
```
from django.db.models.functions import Concat, Coalesce
from django.db.models import F, CharField, Func

search = self._querydict.get('search[value]', None)
if search:
args = []
for column in self.table.columns:
	if column['queryset']['search_join']:
		args.append(
			Coalesce(F(column['queryset']['column']), functions.Value(""))
		)
if len(args) > 1:
      column_name = "search_join_all" 
      qs = qs.annotate(**{column_name: Concat(*args, output_field=CharField())})
      filter_method = self.get_filter_method()
      qs = qs.filter(**{column_name + "__" + filter_method: search})
 ```

Sql execute (Generated in django with the users table related to group):

```
SELECT COUNT_BIG(*) FROM (SELECT [plus_manager_user_groups].[id] AS Col1, CONCAT(COALESCE([plus_manager_user].[first_name], '?'), COALESCE([plus_manager_user].[last_name], '?')) AS [search_join_all] FROM [plus_manager_user_groups] INNER JOIN [plus_manager_user] ON ([plus_manager_user_groups].[user_id] = [plus_manager_user].[id]) WHERE ([plus_manager_user_groups].[group_id] = ? AND UPPER(CONCAT(COALESCE([plus_manager_user].[first_name], '?'), COALESCE([plus_manager_user].[last_name], '?'))) LIKE UPPER(?) ESCAPE '\') GROUP BY [plus_manager_user_groups].[id], CONCAT(COALESCE([plus_manager_user].[first_name], '?'), COALESCE([plus_manager_user].[last_name], '?'))) subquery
```

Python params
```
('', '', 11, '', '', u'%b%', '', '')
```

Error: 'The SQL contains 2 parameter markers, but 8 parameters were supplied', 'HY000'

I do not understand the reason for the error. It has 8 '?' in sql but pyodbc does not recognize as valid.

**Comment by v-chojas** [comment]
`'?'` is a string constant containing a single question mark, and not a parameter marker.
Please remove the quotes from around the question marks and try your query again.

**Comment by alexsilva** [comment]
@v-chojas  You're correct. Thank you.
