### ISSUE TITLE
SELECT EXISTS on Postgres returns str

### ISSUE THREAD

**Issue by niksabaldun** [mkleehammer/pyodbc#478]
When doing a SELECT EXISTS query, I would expect that the result type be boolean, or at least integer. However, a string '0' or '1' is returned. Is this behavior by design?

Python 3.5.3 64bit
Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64
PostgreSQL 9.6

```
from pyodbc import connect
conn = connect('DSN={0}'.format('TEST'))
sql = 'SELECT EXISTS(SELECT 0 FROM user WHERE num=?)'
params = '777' # Existing record
rows = conn.cursor().execute(sql, params).fetchall()
rows[0][0]
'1'
params = '999' # Non-xisting record
rows = conn.cursor().execute(sql, params).fetchall()
rows[0][0]
'0'

```

odbcinst.ini
```
[PostgreSQL ANSI]
Description=PostgreSQL ODBC driver (ANSI version)
Driver=psqlodbca.so
Setup=libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1

[PostgreSQL Unicode]
Description=PostgreSQL ODBC driver (Unicode version)
Driver=psqlodbcw.so
Setup=libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1

```

odbc.ini
```
[TEST]
Driver = PostgreSQL Unicode
Servername = localhost
Port = 5432
Protocol = 9.6
UserName = ******
Password = ******
Database = test
MaxVarcharSize = 1073741824

```

**Comment by v-chojas** [comment]
This is probably because the driver is returning the results as a character type. Post an [ODBC trace](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/data-access-tracing-with-the-odbc-driver-on-linux) if you would like to know more.

**Comment by niksabaldun** [comment]
Indeed. ODBC trace shows result to be of type SQL_CHAR. This is either a bug in PostgreSQL ODBC driver or a very strange design decision. Thanks for the help, this obviously has nothing to do with pyodbc.

**Comment by niksabaldun** [comment]
Upon further investigation, it appears that ODBC actually has a setting for this, BoolsAsChar, which strangely defaults to true. After putting BoolsAsChar = 0 in odbc.ini, booleans are correctly returned.
