### ISSUE TITLE
crsr.rowcount always returns -1 for crsr.executemany

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#481]
(Further to [this comment](https://github.com/mkleehammer/pyodbc/issues/480#issuecomment-433997258) in #480)

pyodbc version: #467
driver version: ODBC Driver 17 for SQL Server

`crsr.executemany` ignores SQLRowCount values returned by SQL Server. `crsr.rowcount` always returns -1.

repro code:

```python
import pyodbc

cnxn = pyodbc.connect(
    r"DRIVER=ODBC Driver 17 for SQL Server;"
    r"SERVER=localhost,49242;"
    r"DATABASE=myDb;"
    r"Trusted_Connection=yes;"
    r"UseFMTOnly=yes;"
)
cnxn.autocommit = True
crsr = cnxn.cursor()

crsr.execute("""\
CREATE TABLE #foo (
    id INT PRIMARY KEY, 
    val INT
    )""")
crsr.execute("INSERT INTO #foo (id, val) VALUES (1,1),(2,2),(3,3)")

sql = "UPDATE #foo SET val=val+1 WHERE id>?"
params = [(1,),(2,)]
crsr.fast_executemany = False
crsr.executemany(sql, params)
print(crsr.rowcount)
```

[SQL_LOG.txt](https://github.com/mkleehammer/pyodbc/files/2529743/SQL_LOG.txt) shows that `SQLRowCount` is returning the row counts for the two separate queries generated (`crsr.fast_executemany = False`):

[line 510]

```
main            1a40-1e2c	EXIT  SQLRowCount  with return code 0 (SQL_SUCCESS)
		HSTMT               0x000000000052E2E0
		SQLLEN *            0x000000000021F680 (2)
```

[line 572]
```
main            1a40-1e2c	EXIT  SQLRowCount  with return code 0 (SQL_SUCCESS)
		HSTMT               0x000000000052E2E0
		SQLLEN *            0x000000000021F680 (1)
```

but they are apparently being ignored.

**Comment by gordthompson** [comment]
Additional information: The above code with `fast_executemany = True` does not call `SQLRowCount` at all after `executemany` invokes `SQLExecute`.

[fast_executemany_true_LOG.txt](https://github.com/mkleehammer/pyodbc/files/2529914/fast_executemany_true_LOG.txt)

**Comment by v-chojas** [comment]
According to the [API spec](https://www.python.org/dev/peps/pep-0249/#rowcount) the rowcount is valid for `execute()` only. Thus, this works

```
for p in params:
    crsr.execute(sql, p)
    print(crsr.rowcount)
```
and prints
```
2
1
```

**Comment by keitherskine** [comment]
I'm sure the end users wouldn't object if `rowcount` was used for `executemany` as well as `execute`.  Indeed, I think they'd be extremely grateful.  I know I would be.  I don't want to create a ton of work for you @v-chojas , this is uncompensated OSS of course, but it's always good to find out from the database how many records were actually affected rather than making assumptions about such things.  If it can be done reasonably easily, I would certainly appreciate it.

**Comment by gordthompson** [comment]
At least in some cases a workaround would be to use fast_executemany to upload the rows to a temporary table (for faster transfer) and then use plain old `execute` to do the INSERT/UPDATE/MERGE and get the `rowcount` from that.
