### ISSUE TITLE
cursor level commit/rollback

### ISSUE THREAD

**Issue by boumboum** [mkleehammer/pyodbc#484]
This is rather a feature request.

Would it be possible to implement a cursor level commit and rollback rather a connection level one?

I'm implementing a web server which makes a lot of concurrent inserts and updates to a MSSQL database.
I would like to reduce the time needed for connection to the database upon each request.
Instead of this I would like to make a connection at startup of the web server and use the existing connection for creating a cursor by request and work with that cursor (and also commit or rollback the transaction of that query) during the request.
As each request is making some  "long running" transactions, if I commit or rollback a transaction of a cursor it commits or rolls back all other cursor's transaction in the middle as well, what of course is not a desired behavior.

How can I implement this required behavior?
How are the busy sites (google, facebook, etc.) handling this issue? Are they establishing a connection at each request? I can't believe that.

**Comment by v-chojas** [comment]
[Transactions in ODBC are managed at the connection level](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/odbc/performing-transactions-in-odbc]).

You may be able to use [connection pooling](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/driver-manager-connection-pooling) to improve performance.

**Comment by boumboum** [comment]
I know all this. But it does not help me with my busy site.
I've tried to have just one connection but then I came to some strange issues where several requests mixed up themselves. An a query of a function has rolled back the queries of an other function.

On the other hand I suppose pyodbc is using connection pooling by default.

**Comment by v-chojas** [comment]
Connection pooling has to be enabled by the DM --- pyODBC does not control this setting.

Also, if you are using unixODBC on Linux/macOS and not the Windows DM, be aware that older versions of it have some bugs related to connection pooling.

**Comment by mkleehammer** [comment]
These guys are right (and provide lots of links ;) ), there isn't anything we can do.  Connection pooling really is your answer.  If you are on Windows, it is integrated and works great.

Multiple cursors on the same connection will get just as tangled as when you tried to share a connection - that's just how they work.  You have to use multiple connections somehow.

Good luck.
