### ISSUE TITLE
read_sql too slow with python 3.6 vs very efficient in python 2.6

### ISSUE THREAD

**Issue by dusanenikhil** [mkleehammer/pyodbc#485]
I have a simple select query fetching few rows from Oracle database using pandas.read_sql, and pyodbc's connection string.
It works extremely well (with execution time of around 0.56 sec ) when executed in Python 2 kernel.

The same code takes 50 sec when executed via Python 3 kernel.

**Comment by dusanenikhil** [comment]
Thank you for your reply. I think it's more of a Pandas or Python issue. I have posted my question on StackOverflow here:
[https://stackoverflow.com/questions/53251448/pandas-read-sql-is-extremely-slow-on-python-3-kernel-compared-to-python-2](url)

**Comment by mkleehammer** [comment]
I'll close this for now, then.  Please reopen if you find out it is pyodbc.  Thanks for taking the time to respond.
