### ISSUE TITLE
pyodbc.Error on SELECT Query on Cloudera - Impala

### ISSUE THREAD

**Issue by JacquesVergine** [mkleehammer/pyodbc#486]
## Environment

- Python: 3.6 64-bit
- pyodbc: 4.0.23
- OS: Windows 7 Enterprise 64-bit
- DB: Impala
- driver: Cloudera ODBC Driver for Impala

## Issue

I would like to run this query :
```
SELECT 
    CAST(substr(li.barcode_pos_item_id, 12, 5) AS INT) / 100 as original_val
    , CAST(substr(li.barcode_pos_item_id, 17, 5) AS INT) / 100 as reduced_val
FROM (
    SELECT '821008531010006000025' as barcode_pos_item_id
) as li
```

But I get the following pyodbc.Error: 

> ('HY000', '[HY000] [Cloudera][ImpalaODBC] (110) Error while executing a query in Impala: [HY000] : AnalysisException: Syntax error in line 1:
> ...s_item_id`, 12, 5 ) AS INT(32767))/100) AS `original_v...
>                              ^
> Encountered: (
> Expected: BLOCK_SIZE, COMMENT, COMPRESSION, DEFAULT, ENCODING, INTERMEDIATE, LOCATION, NOT, NULL, PRIMARY, COMMA
> 
> CAUSED BY: Exception: Syntax error
>  (110) (SQLExecDirectW)')

* The error seems to come from the "INT(32767)" but it doesn't exist in my original query.
* I don"t get an error when I run the same query using another interface for querying Impala (HUE or Aqua data Studio)
* I've run a multitude of query using pyodbc before without getting any error.

Tell me if you need more information or if I missed something.

Jacques

**Comment by v-chojas** [comment]
Please post an ODBC trace, this could be a limitation of the ODBC driver and not pyODBC.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
