### ISSUE TITLE
Jupyter Notebook kernel dying when trying to connect to SQL Server with odbc

### ISSUE THREAD

**Issue by dpezim** [mkleehammer/pyodbc#487]
### Environment

- Python: 3.6.4
- pyodbc: 4.0.23
- OS: MacOS Mojave 10.14
- DB: SQL Server
- driver: ODBC Driver 17 for SQL Server

### Issue

I am currently trying to connect to SQL Operations Studio (SQL Server for mac) through Jupyter Notebook. In Terminal, I use this code to install the driver:

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
brew install --no-sandbox msodbcsql17 mssql-tools`

And I used this command (from this question: [)](https://stackoverflow.com/questions/44527452/cant-open-lib-odbc-driver-13-for-sql-server-sym-linking-issue?rq=1) to fix a driver problem:

`sudo ln -s /usr/local/etc/odbcinst.ini /etc/odbcinst.ini
sudo ln -s /usr/local/etc/odbc.ini /etc/odbc.ini`

Now I try to run the following code in Jupyter:

`import pyodbc

cnxn = pyodbc.connect('driver={ODBC Driver 17 for SQL Server},\
                  server=###,\
                  database=###,\
                  uid=###,\
                  pwd=###')

cur = cnxn.cursor()

db_cmd = "SELECT TOP (10) * FROM [dbo].[ChargePoints]"

res = cur.execute(db_cmd)`

Then get this error message: "The kernel appears to have died. It will restart automatically." I've tested it and I know it is dying on the second line, pyodbc.connect. I have never tried to do SQL queries from python before so I have no clue where to go from here.

**Comment by v-chojas** [comment]
Please post an ODBC trace: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/data-access-tracing-with-the-odbc-driver-on-linux

**Comment by dpezim** [comment]
I'm having trouble getting that trace to work. Bit of extra information though:

The Terminal is giving me this error:
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for UTF-8

**Comment by v-chojas** [comment]
That could be related to https://github.com/Microsoft/homebrew-mssql-release/issues/18 ,

**Comment by dpezim** [comment]
@v-chojas this ended up being correct. I appended the bash_profile with the UTC-8 locale and it fixed the issue. Thanks!

**Comment by vengal21** [comment]
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user = "root",    # user
                               pw = "vengalrao21@",      # passwrd
                               db = "spam"))
sql = 'SELECT * FROM spam'
spam = pd.read_sql_query(sql, engine).convert_dtypes()
spam.shape

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '@localhost' ([Errno 11003] getaddrinfo failed)") 
i have facing this issue during the connection of sql and juypter notbook

**Comment by v-chojas** [comment]
Look up what error 11003 is, and you should probably start a new issue because everything else in the previous comments here is irrelevant to your situation.

**Comment by Ankucheeku** [comment]
someone please please help me .... i m trying to connect my jupyter notebook with sql and it shows me that "kernel is dead and it will restart automatically "
i m usind dell i3 laptop 
windows 10
jupyter notebook 7.0..
sql version 8.0..

my three line of code is like this 

pip install mysql-connector-python
import mysql.connector as cont
con=cont.connect(user='root',password='1234',host='localhost')
