### ISSUE TITLE
What should i use for Driver for oracle in linux?

### ISSUE THREAD

**Issue by mese79** [mkleehammer/pyodbc#49]
Hi
I want to connect to an oracle db on my linux machine but i don't know what should i put as driver in connection string?
I've tried:
```
connStr = "Driver={/usr/lib/oracle/product/11.2.0/xe/lib/libsqora.so.11.1};Server=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))(CONNECT_DATA=(SID=XE)));Uid=me;Pwd=mypass;"
```
And i got this error:
```
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/lib/oracle/product/11.2.0/xe/lib/libsqora.so.11.1' : file not found (0) (SQLDriverConnect)")
```
But the file is there:
```
$ ls -l /usr/lib/oracle/product/11.2.0/xe/lib/libsqora.so.11.1
-rwxr-xr-x 1 oracle dba 790904 Aug 29  2011 /usr/lib/oracle/product/11.2.0/xe/lib/libsqora.so.11.1
```
This is my odbcinst.ini file:
```
$ cat /etc/odbcinst.ini 

[Oracle 11g ODBC driver]
Description     = Oracle ODBC driver for Oracle 11g
Driver          = /usr/lib/oracle/product/11.2.0/xe/lib/libsqora.so.11.1
Setup           =
FileUsage       =
CPTimeout       =
CPReuse         = 
```
Please help me through this problem.
Thanks.

**Comment by mkleehammer** [comment]
I don't have a copy to test with right now, but the Driver keyword should reference an entry in odbcinst.ini.  I'm going to take a guess on the others, but you really need to find the driver's documentation.  What goes in the string is completely up to each driver.

Driver={Oracle 11g ODBC driver};Server=127.0.0.1;Uid=scott;Pwd=tiger
