### ISSUE TITLE
Problem inserting spatial data on sqlserver with executemany

### ISSUE THREAD

**Issue by joluinfante** [mkleehammer/pyodbc#490]
This is the code (and execution):
create table SERVICIOS(seq int identity, srv_codigo int, origen tinyint, the_geom geometry)
cursor.executemany(insert into SERVICIOS(srv_codigo, origen, the_geom) values (?, ?, ?), [(890121, 1, 'POINT(5433592.74204 6500996.88667 22185)'), (1074588, 1, 'POINT(5440204.47007 6353642.56903 22185)'), (100687, 1, 'POINT(5431739.9555 6358820.54638 22185)'), (1012367, 1, 'POINT(5439243.90449 6355538.24641 22185)'), (1043668, 1, 'POINT(5544769.18908 6259123.163 22185)'), (834662, 1, 'POINT(5431339.04474 6355936.49149 22185)'), (1181148, 1, 'POINT(5428373.58199 6359226.32157 22185)'), (869878, 1, 'POINT(5530694.24439 6274481.16897 22185)'), (485399, 1, 'POINT(5531160.12489 6273375.67546 22185)'), (473386, 1, 'POINT(5531406.07286 6274389.44644 22185)')])
Traceback (most recent call last):
pyodbc.DataError: ('22018', u'[22018] [Microsoft][ODBC Driver 17 for SQL Server]Invalid character value for cast specification (0) (SQLPutData)')

Any idea?
If I disable fast_executemany, there is no error, but, the performance is like to insert each record at time.

**Comment by joluinfante** [comment]
This is the code (and execution):
create table SERVICIOS(seq int identity, srv_codigo int, origen tinyint, the_geom geometry)
cursor.executemany(insert into SERVICIOSX(srv_codigo, origen, the_geom) values (?, ?, ?), [(890121, 1, 'POINT(5433592.74204 6500996.88667 22185)'), (1074588, 1, 'POINT(5440204.47007 6353642.56903 22185)'), (100687, 1, 'POINT(5431739.9555 6358820.54638 22185)'), (1012367, 1, 'POINT(5439243.90449 6355538.24641 22185)'), (1043668, 1, 'POINT(5544769.18908 6259123.163 22185)'), (834662, 1, 'POINT(5431339.04474 6355936.49149 22185)'), (1181148, 1, 'POINT(5428373.58199 6359226.32157 22185)'), (869878, 1, 'POINT(5530694.24439 6274481.16897 22185)'), (485399, 1, 'POINT(5531160.12489 6273375.67546 22185)'), (473386, 1, 'POINT(5531406.07286 6274389.44644 22185)')])
Traceback (most recent call last):
pyodbc.DataError: ('22018', u'[22018] [Microsoft][ODBC Driver 17 for SQL Server]Invalid character value for cast specification (0) (SQLPutData)')

Any idea?
If I disable fast_executemany, there is no error, but, the performance is like to insert each record at time.

**Comment by v-chojas** [comment]
Could you provide more information about your environment (OS versions, server version, driver version, etc.) and an ODBC trace?

**Comment by keitherskine** [comment]
See https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting:-Generating-an-ODBC-trace-log for generating a trace file.  If you're running your Python from Ubuntu, enable the tracing in the `odbcinst.ini` file there.  You should be able to find the location of the `odbcinst.ini` file by running `odbcinst -j`.

**Comment by gordthompson** [comment]
I was able to reproduce the issue on Windows:

Python 3.6.4  
pyodbc #467 
ODBC Driver 17 for SQL Server  

```python
crsr.execute("""\
create table ##SERVICIOS(seq int identity, srv_codigo int, origen tinyint, the_geom geometry)
""")

sql = "insert into ##SERVICIOS(srv_codigo, origen, the_geom) values (?, ?, ?)"
params =  [
    (890121, 1, 'POINT(5433592.74204 6500996.88667 22185)'),
    (1074588, 1, 'POINT(5440204.47007 6353642.56903 22185)'),
]
crsr.fast_executemany = True  ## no error if this line is commented out
crsr.executemany(sql, params)
```

[SQL_LOG.txt](https://github.com/mkleehammer/pyodbc/files/2648908/SQL_LOG.txt)

**Comment by joluinfante** [comment]
Exaclty the problem reproduced by gordthompson. if you set fast_executemany to false, the routine send the records one to one. then, we are lossing the performance of the database if it receiving all records in a one big message.

**Comment by v-chojas** [comment]
This is because the geometry type is actually a UDT, and in fast_executemany mode pyODBC binds it directly as a UDT which expects a binary value (in [MS-SSCLRT](https://msdn.microsoft.com/en-us/library/ee320529.aspx) format) instead of a string.

You can use the `setinputsizes` function to set your geometry column's type to SQL_WVARCHAR, and then the string values will work:
```
crsr.setinputsizes([None, None, (pyodbc.SQL_WVARCHAR, 0, 0)])
```
Alternatively, if your input data source can be configured to output in the binary format, then that would likely be a better performer to insert directly:
```
params = [
    (890121, 1,  'A9560000010857957D2F3EBA54418733BF38A1CC5841'),
    (1074588, 1, 'A956000001087BA0151EB3C05441CEFC6AA4BA3C5841'),
]
```

**Comment by joluinfante** [comment]
Ok. I'll check the setinputsizes option. If I'd like to use the second binary format, what is the method to convert (in python) the wkt "point(x, y)" string to binary format?

**Comment by mkleehammer** [comment]
@v-chojas Should this be closed?  Is there something we should / could do to make this easier?
