### ISSUE TITLE
Regression in Unicode support between version 3.0.9 and 3.0.10

### ISSUE THREAD

**Issue by mattrtaylor** [mkleehammer/pyodbc#50]
There seems to have been a regression in Unicode support in 3.0.10.
*This might also be the actual cause of issue #47*

Test Code
======================
```python
import pyodbc

def pyodbc_test(db, query, username):
    try:
        curs = db.cursor()
        curs.execute(query, (username, ))
        return curs.fetchone()
    except Exception, e:
        return e
    return None

db = pyodbc.connect("DSN=...")
print pyodbc_test(db, u"SELECT * FROM [Users] WHERE username = ?", u'foo')
print pyodbc_test(db, b"SELECT * FROM [Users] WHERE username = ?", u'foo')
print pyodbc_test(db, u"SELECT * FROM [Users] WHERE username = ?", b'foo')
print pyodbc_test(db, b"SELECT * FROM [Users] WHERE username = ?", b'foo')
db.close()
```

Results
======================
Version 3.0.10
```python
('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')
None
('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')
(u'f\x00o\x00o\x00', u'M\x00r\x00.\x00 \x00F\x00o\x00o\x00')
```
Version 3.0.9 (and earlier)
```python
(u'foo', u'Mr. Foo')
(u'foo', u'Mr. Foo')
(u'foo', u'Mr. Foo')
(u'foo', u'Mr. Foo')
```

Environment
======================
### Client
* OS X 10.9.5
* Python 2.7
* libiodbc-3.52.9
* freetds-0.91

### Server
* Windows 7 x64
* MS SQL Server 2012

**Comment by mkleehammer** [comment]
Very organized - thanks.  Are you sure it is still using iodbc?  Part of 3.0.10 was to switch the OS X build to unixODBC.  In the meantime I'll have to setup my Windows test VM with SQL Server and run the freetds tests.

**Comment by mattrtaylor** [comment]
Thank you for the hint regarding the underlying library -- my build of 3.0.10 was linking with iODBC, when, as you point out, changes have been made to support unixODBC instead.

Sorry about the false alarm!
