### ISSUE TITLE
pyodbc.cursor.columns doesn't always return table column information

### ISSUE THREAD

**Issue by villekr** [mkleehammer/pyodbc#501]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7
- pyodbc: 4.0.25
- OS: Docker python:3.7 i.e. Debian 9 (Docker running on MacOS Mojave)
- DB: Netsuite (some Oracle SQL database flavour)
- driver: Netsuite ODBC driver Linux64bit 7.2.0.0050

### Issue

I can execute queries against database and get data very reliably. Also getting column description using Cursor.description works fine. The problem is that with Cursor.columns sometimes I get data and sometimes not. When data is available is fully correct. I haven't been able to draw any specific pattern when it works and when not. 

"expected behavior"
crsr.columns(table='<table_name>') should return always the column description for the given table

"observed behavior".
crsr.columns(table='<table_name>') sometimes iterator is empty i.e. no data for table columns is available

Simple test code:
```
def get_table_cols():
    crsr = cnxn.cursor()
    col_count = {}
    for table_name in ['ACCOUNTS', 'COUNTRIES', 'TRANSACTION_LINES', 'SUBSIDIARIES']:
        cols = crsr.columns(table=table_name)
        col_count.update({table_name: len(list(cols))})
    print(col_count)


def loop():
    for x in range(6):
        get_table_cols()


loop()
```
Output:
```
{'ACCOUNTS': 33, 'COUNTRIES': 0, 'TRANSACTION_LINES': 157, 'SUBSIDIARIES': 61}
{'ACCOUNTS': 0, 'COUNTRIES': 0, 'TRANSACTION_LINES': 157, 'SUBSIDIARIES': 61}
{'ACCOUNTS': 0, 'COUNTRIES': 0, 'TRANSACTION_LINES': 157, 'SUBSIDIARIES': 0}
{'ACCOUNTS': 0, 'COUNTRIES': 0, 'TRANSACTION_LINES': 157, 'SUBSIDIARIES': 0}
{'ACCOUNTS': 0, 'COUNTRIES': 0, 'TRANSACTION_LINES': 157, 'SUBSIDIARIES': 0}
{'ACCOUNTS': 0, 'COUNTRIES': 0, 'TRANSACTION_LINES': 157, 'SUBSIDIARIES': 0}
```

**Comment by v-chojas** [comment]
What version of unixODBC are you using?
Please post an [ODBC trace](https://www.simba.com/blog/odbc-troubleshooting-tracing/).

**Comment by RaiKoHoff** [comment]
Got the same problem for Microsoft Access Driver (*.mdb) - (older) 32-bit "Jet" ODBC driver:
Using following code to check if column in table exists:
```
column = cursor.columns(table=table_name, column=column_name).fetchone()
if column:
    return True
return False
```
While this works fine for `pyodbc.cp36-win32.4.0.24`, it seems to be broken in `pyodbc.cp36-win32.4.0.25` (for some runs - not always?).

Following workaround is working reliable for both versions v.4.0.24 and v.4.0.25:
```
xcrsr = cursor.columns(table=table_name)
columns = [dict(zip([col[0] for col in xcrsr.description], row)) for row in xcrsr.fetchall()]
column = [info for info in columns if info['column_name'] == column_name]
if column:
    return True
return False
```

**Comment by v-chojas** [comment]
Please post an [ODBC trace](https://www.simba.com/blog/odbc-troubleshooting-tracing/)

**Comment by RaiKoHoff** [comment]
Attachment: Zip of ODBC Trace files (SUCCESS log (v.4.0.24) and FAIL log (v.4.0.25).
Only difference for creating logs: `pyodbc.pyd` exchanged (v.4.0.24 - v.4.0.25).
[sql_logs.zip](https://github.com/mkleehammer/pyodbc/files/2767966/sql_logs.zip)

**Comment by v-chojas** [comment]
@gisofer If you are using the ODBC driver named "SQL Server", that is a _very_ old one and I suggest upgrading to ODBC Driver 17 for SQL Server (https://www.microsoft.com/en-us/download/details.aspx?id=56567).

**Comment by mkleehammer** [comment]
This seems to be the same as #506 which is fixed in master but not yet released.  If I had put that together I would have closed #506 as a duplicate, but since I posted to patch against it I will close this as a duplicate.  If master doesn't fix it, please reopen this, but I'm pretty sure it will.

**Comment by RaiKoHoff** [comment]
Current master (https://github.com/mkleehammer/pyodbc/commit/d5a8a7b357a5cfea0e35ced83b9f135c3327d9f4) solved [my problems](https://github.com/mkleehammer/pyodbc/issues/501#issuecomment-454763704) - thanx.

**Comment by shvthr** [comment]
I have the same issue.

**Comment by andrew-3D** [comment]
I have the same problem as @gisofer 
Python: 2.7.14, pyodbc: 4.0.26  OS: Windows 10 64bit, Driver: 2010 Access Database Engine ---->fails
Older version however,
Python: 2.7.13, pyodbc: 4.0.22  OS: Windows 10 64bit, Driver: 2010 Access Database Engine ---->works

**Comment by andrew-3D** [comment]
Same problem with IBM i Series Access ODBC Driver

**Comment by andrew-3D** [comment]
Python: 3.7.3, pyodbc: 4.0.26 OS: Windows 10 64bit, Driver: 2010 Access Database Engine ---->works

Python: 2.7.14, pyodbc: 4.0.26 is definitely still an issue.  " pip install pyodbc --upgrade "  reports that pyodbc 4.0.26 IS the latest version, so that road is closed, Update python then?

**Comment by a2xchip** [comment]
```
columns = [row[3] for row in msCursor.columns(table=t)]
```
