### ISSUE TITLE
Multiprocessing, cursor.fetcall and 'TypeError(“can't pickle pyodbc.Row objects”,)'

### ISSUE THREAD

**Issue by sotriant** [mkleehammer/pyodbc#508]
I am using Spyder and Python 2.7 and pyodbc module. i run a script with multiprocessing and in a method i use cursor.fetcall() to get data from a database.  Using logger i can see that it returns all the data but it shows:
 MaybeEncodingError: Error sending result: '[[(Decimal('14674'), u'\u0391', u'\u03a7\u039b', 1, 101, 4256815.0, 464554.0, u'117275892689', Decimal('187143225'), Decimal('1001002488331661'), u'1.31670565', u'\u0395\u039b\u0395\u03a5\u0398. \u0392\u0395\u039d\u0399\u0396\u0395\u039b\u039f\u03a5 46'),......]]'. Reason: 'TypeError("can't pickle pyodbc.Row objects",)'

Any ideas how to solve this?

**Comment by v-chojas** [comment]
Could be related:
https://github.com/mkleehammer/pyodbc/issues/433
https://github.com/mkleehammer/pyodbc/issues/446

**Comment by keitherskine** [comment]
Testing pyodbc version 4.0.30, `pyodbc.Row` objects appear to be picklable:
```python
rows = crsr.execute(sql).fetchall()
print(pickle.dumps(rows))
```
If you can't pickle a `pyodbc.Row` object with your setup, try converting the row to a list of simply-typed objects first, i.e.:
`picklable_row = list(row)`.
