### ISSUE TITLE
Teradata 64-Bit ODBC Long/Int Cast Issues

### ISSUE THREAD

**Issue by lycovian** [mkleehammer/pyodbc#51]
With Teradata 14.00 64-bit ODBC using unixODBC (Linux 12.04) running pyodbc (3.11b8) integer values are incorrectly represented:

```
In [16]: cur.execute("select 1").fetchall()
Out[16]: [(140376711102465, )]

In [17]: cur.execute("select cast(1 as int)").fetchall()
Out[17]: [(140376711102465, )]
```

In order to work I need to cast the values manually to bigint:

```
In [18]: cur.execute("select cast(1 as bigint)").fetchall()
Out[18]: [(1L, )]
```

Verified this issue also exists in `pyodbc` 3.0.7 as well.

Per Teradata's docs a integer type is signed 4-byte (-2.147B - 2.147B) number.  The value returned by `pyodbc` appears to far larger than that though.

Problem appears similar to: https://github.com/mkleehammer/pyodbc/issues/42

**Comment by lycovian** [comment]
Interesting to note that all integers in pyodbc with talking with the Teradata 64-bit driver have problems.  See below for output from the `columns` metadata function.  Note that the datatype value integers have been converted to these large integer values:

    In [21]: cur.columns(table='console_users_report_raw', schema='stage').fetchall()
    Out[21]:
    [(None, 'stage', 'console_users_report_raw', 'id', 140634409140228, 'INTEGER', 140634409140234, 140634409140228, 140634409140224, 1>
     (None, 'stage', 'console_users_report_raw', 'channel_id', 140634409140236, 'VARCHAR', 140634409140479, 140634409140479, None, None>
     (None, 'stage', 'console_users_report_raw', 'channel_status', 140634409140236, 'VARCHAR', 140634409140479, 140634409140479, None, >
     (None, 'stage', 'console_users_report_raw', 'created_at', 140634409140317, 'TIMESTAMP', 140634409140256, 140634409140240, 14063440>

**Comment by yinhao** [comment]
Hi Lycovian,

Have you ever solved this problem?

**Comment by jnlaia** [comment]
I also have this problem with Teradata. I've tested with versions 3.0.3, 3.0.7 and 3.0.10. It happens with them all, so this issue was not fixed as #42 was.

Do you guys have any hint on what may be causing the problem? 

It is interesting that when I cast one of the columns as bigint, the entire row seems to be properly retrieved.

cur.execute("select 1, 2, 3").fetchall()
[(139663746531328, 139663746531329, 139663746531330)]

cur.execute("select cast(1 as bigint), 2, 3").fetchall()
[(0L, 1, 2)]

**Comment by mkleehammer** [comment]
Is this still a problem?   Can you not select integers with Teradata?  I know there are Teradata users out there.  If so, has anyone tried with 4.0.8+?

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
