### ISSUE TITLE
possible documentation mistake on cursor/transaction

### ISSUE THREAD

**Issue by jmarshall9120** [mkleehammer/pyodbc#511]
I believe the lines in the documentation:

```
params = [ ('A', 1), ('B', 2) ]
cursor.autocommit = False
cursor.executemany("insert into t(name, id) values (?, ?)", params)
cursor.commit()
cursor.autocommit = True
```

posted [here](https://github.com/mkleehammer/pyodbc/wiki/Cursor)

are incorrect.  I do not believe the autocommit attribute is part of the cursor object, but is indeed part of the connection object. 

Possible change would be:
```
params = [ ('A', 1), ('B', 2) ]
cnxn =  pyodbc.connect(strConectionString)
cnxn.autocommit = False
cursor = cnxn.cursor()
cursor.executemany("insert into t(name, id) values (?, ?)", params)
cnxn.commit()
cnxn.autocommit = True

```
This is supported by the error I get when running the current example:
`Message: 'pyodbc.Cursor' object has no attribute 'autocommit'`

and the documentation at the top of the same page referenced above: 
`Note, cursors do not manage database transactions, transactions are committed and rolled-back from the connection.`

**Comment by v-chojas** [comment]
Documentation is a wiki, you may make the changes yourself.

**Comment by jmarshall9120** [comment]
@v-chojas I have made the change as suggested.
