### ISSUE TITLE
Suggestion: Allow for more testing before new release

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#513]
4.0.25 introduced a couple of regressions: #501 , #506 , #509 . Certainly the latter could have been caught by simply running accesstests.py prior to release.

Now I'm not suggesting that @mkleehammer or any other team member should be expected to maintain every possible test environment and run all of the tests single-handedly. However, if we could give motivated volunteers the opportunity to test environments for which they have a particular interest (and ready access) we could potentially avoid "gotchas" after a release. For example, I would have been happy to run accesstests.py myself.

One option would simply be to merge a number of PRs, possibly tag the result as something like "4.0.26b1" or "4.0.26rc1", announce its availability, and let the volunteer testers build their own versions. (Not sure if there is a GitHub feature to help out with the notification part.) That would represent a very small incremental load on the core development team.

Another option would be to actually build the wheels and deploy them to PyPI as pre-release versions, similar to what SQLAlchemy does. As of this posting the latest official release of SQLAlchemy is 1.2.16, but 1.3.0b1 is available for the asking by simply doing `pip install SQLAlchemy==1.3.0b1`. This option would be more work for @mkleehammer , but it would also presumably make it easier to recruit volunteer testers because they won't have to build the module themselves. (It's easy enough on Linux, but it's a bit more of a chore on Windows.)

Comments welcome.

**Comment by mkleehammer** [comment]
I agree.  I'll make a beta since #506 could be important - we haven't seen it but I think it could mess up Cursor.description also.
