### ISSUE TITLE
fast_executemany causes varchar data to be altered

### ISSUE THREAD

**Issue by MarkiesFredje** [mkleehammer/pyodbc#515]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.3
- pyodbc: 4.0.25
- OS: RHEL 7.5
- DB: SybaseIQ (SAP)
- driver: IQ-16_0

### Issue

I'm using pandas.to_sql function
Which itself uses a sqlalchemy object (sybase+pyodbc)
My table contains a column with strings (lenght < 30 chars)

**Observed behaviour:**
Everything works fine when I don't use fast_executemany = True (though its SLOW)
my dataframe's numeric data is correctly inserted into the database
my dataframe's string data has been altered before being inserted into the database
Part of the previous record's string overwrites a part of the current record's string
e.g: (this_is_line_1, this_is_line2) becomes (this_is_line_1, line_1s_line2)

**Expected behaviour:**
No data alterations should happen

**Workaround I found to correct the issue:**
I manually changed the inputsizes before the cursor executes, as shown in the code snippet below.

```
from sqlalchemy import event
import pyodbc

@event.listens_for(syst_database_engine, 'before_cursor_execute')
def receive_before_cursor_execute(conn, cursor, statement, params, context, executemany):
    if executemany:
        cursor.setinputsizes([(pyodbc.SQL_BIGINT), (pyodbc.SQL_BIGINT), (pyodbc.SQL_WVARCHAR, 50, 0)])
        cursor.fast_executemany = True

```

**Comment by MarkiesFredje** [comment]
I was on 4.0.24 when I first got the issue and updated to 4.0.25

**Comment by v-makouz** [comment]
Can you post ODBC trace?

This feature was originally designed for SQL Server and relies on SQLDescribeParam to get the sizes of the parameters, so if it behaves differently with different DB/Driver this may be the reason. It could also be due to how parameter arrays are handed

It looks like the contents of the first string get written into the second one, which likely means that the size for the strings was allocated incorrectly.

**Comment by MarkiesFredje** [comment]
Unfortunately I could not activate the ODBC traces, I did not have required rights on the machine.

**Comment by v-chojas** [comment]
Another thing to check is the version of unixODBC. You can do this by using `odbcinst -j` command.

Unfortunately if you cannot provide an ODBC trace then it is pretty much impossible to see what the problem is.

**Comment by MarkiesFredje** [comment]
As requested, took a while to get the required rights, bloody corporate red tape 👎 

> unixODBC 2.3.4
> DRIVERS............: /etc/odbcinst.ini
> SYSTEM DATA SOURCES: /etc/odbc.ini
> FILE DATA SOURCES..: /etc/ODBCDataSources
> USER DATA SOURCES..: /var/opt/cat/Progress/DataDirect/Connect64_for_ODBC_71/odbc.ini
> SQLULEN Size.......: 8
> SQLLEN Size........: 8
> SQLSETPOSIROW Size.: 8

[sql.log](https://github.com/mkleehammer/pyodbc/files/2801939/sql.log)

**Comment by v-chojas** [comment]
I do not have Sybase but the following worked correctly with SQL Server
```
stmt.execute('create table issue515(c1 int, c2 int, c3 nvarchar(30))')
stmt.fast_executemany = True
stmt.executemany('insert into issue515 values(?,?,?)', [ [ 1, 2, 'this_is_line_1' ], [ 3, 4, 'this_is_line_2' ] ])
```

**Comment by v-chojas** [comment]
If you have a minimal and complete repro script, that would be very useful; but I believe this may be a fault of the ODBC driver not correctly handling parameter arrays.

**Comment by MarkiesFredje** [comment]
Turns out I could update unixODBC in my conda environment,so no need for an admin, awesome!
But it did not do anything for this bug. 
Any other ideas or insights?

**Comment by v-chojas** [comment]
@gordthompson in fast_executemany mode, the C type is from the Python object, so a Python 3.x string will become SQL_C_WCHAR. The SQL type is what the database believes the type to be, retrieved using SQLDescribeParam, so it appears that was inserting into a varchar column.

**Comment by gordthompson** [comment]
@v-chojas  - Thanks for the explanation.

@MarkiesFredje - Can you confirm that the `householdtypology_gfk` column is indeed VARCHAR, as opposed to NVARCHAR (or the Sybase equivalents)?

**Comment by MarkiesFredje** [comment]
In this case `householdtypology_gfk` is indeed varchar and not nvarchar.

**Comment by mkleehammer** [comment]
Does the test v-chojas posted work when changed to varchar?

**Comment by MarkiesFredje** [comment]
@mkleehammer I don't understand what I should test?
If you see my workaround, changing types to VARCHAR does indeed solve the problem

**Comment by gordthompson** [comment]
@MarkiesFredje - Actually, your workaround specifies `SQL_WVARCHAR` ...

```python
    if executemany:
        cursor.setinputsizes([(pyodbc.SQL_BIGINT), (pyodbc.SQL_BIGINT), (pyodbc.SQL_WVARCHAR, 50, 0)])
        cursor.fast_executemany = True
````

Does it also work if you specify `pyodbc.SQL_VARCHAR` ...?

**Comment by MarkiesFredje** [comment]
@gordthompson 
Yes, I tested today and it works fine when I specify `pyodbc.SQL_VARCHAR`

**Comment by gordthompson** [comment]
Historical note: This issue was raised before I created the external [sqlalchemy-sybase](https://github.com/gordthompson/sqlalchemy-sybase) dialect for SQLAlchemy (May 2020) so it must have been using the (now deprecated) internal `sybase` dialect.
