### ISSUE TITLE
Login fails on Ubuntu server (error 18456 state=8)

### ISSUE THREAD

**Issue by d0325mgray** [mkleehammer/pyodbc#517]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:   3.6.7
- pyodbc:  4.0.25
- OS:         Ubuntu 18.04 Linux mssql.thecivithing.com 4.15.0-44-generic #47-Ubuntu SMP Mon Jan 14 11:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- DB:        Microsoft SQL Server 2019 (CTP2.2) - 15.0.1200.24 (X64)   Dec  5 2018 16:51:26   Copyright (C) 2018 Microsoft Corporation  Express Edition (64-bit) on Linux (Ubuntu 18.04.1 LTS) <X64>
- driver:   ODBC Driver 17 for SQL Server

### Issue

Code

`import pyodbc

details = {
 'server' : 'localhost',
 'database' : 'AdventureWorks2017',
 'username' : 'd0325mgray',
 'password' : 'DI28616!',
 }

connect_string = 'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};PORT=1443; DATABASE={database};UID={username};PWD=password)'.format(**details)

connection = pyodbc.connect(connect_string)
print(connection)

Executing this fails with the message:

`Traceback (most recent call last):
  File "AWconnect.py", line 14, in <module>
    connection = pyodbc.connect(connect_string)
pyodbc.InterfaceError: ('28000', "[28000] [unixODBC][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'd0325mgray'. (18456) (SQLDriverConnect)")
`
I checked the log and confirmed state=8

The password is correct. I have connected with sqlcmd and SSMS. I have no idea what is wrong

**Comment by gordthompson** [comment]
Is `PWD=password` a typo or is it really not `PWD={password}` ...?

**Comment by d0325mgray** [comment]
I had tried a couple of different things. It should have had the curly brackets. I get the same result, though

**Comment by v-makouz** [comment]
Can you try `isql -v -k "<connection string>"` from the client machine? Ideally with a copy pasted string from the test app to isolate weather it's the issue happening on the driver side or pyODBC

I don't know if that's relevant, but usually default port is 1433.

**Comment by v-chojas** [comment]
Two more items to provide more information for diagnosis---

- What version of unixODBC are you using? (Check with `odbcinst -j`)
- An ODBC trace of the connection failure

**Comment by d0325mgray** [comment]
1. unixODBC 2.3.4
2. I don't know how to an ODBC trace. Give me a few minutes

**Comment by d0325mgray** [comment]
By the way, instead of using the details dictionary, I assigned each of the values to a scalar variable. Now it just times out

**Comment by v-chojas** [comment]
How to ODBC trace: https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting:-Generating-an-ODBC-trace-log

This is the list of supported connection string keywords: http://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute . PORT is not one of them. You need to specify port in Server keyword if you are using a non-default port. See here for more information: https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client

**Comment by d0325mgray** [comment]
output of ODBC trace

[odbctrace.txt](https://github.com/mkleehammer/pyodbc/files/2813688/odbctrace.txt)

**Comment by v-chojas** [comment]
Please try to write your connection string directly, to determine whether it is really a problem in pyODBC or just how you are generating it:

`conn = pyodbc.connect('Driver=ODBC Driver 17 for SQL Server;server=localhost;UID=...');`

The syntax of a connection string is documented at https://sqlprotocoldoc.blob.core.windows.net/productionsqlarchives/MS-ODBCSTR/%5BMS-ODBCSTR%5D.pdf

**Comment by gordthompson** [comment]
Remove the trailing round bracket. It is being appended to your password value, which explains why the login fails.

**Comment by d0325mgray** [comment]
@gordthompson You get the prize. Problem solved but I still would like to know how to execute a python program with a trace that would show the values in the connection string when it is executed.

**Comment by v-chojas** [comment]
@d0325mgray `print(connect_string)`
