### ISSUE TITLE
Invalid option when running: brew install freetds --with-unixodbc

### ISSUE THREAD

**Issue by Allan-Gong** [mkleehammer/pyodbc#519]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: python 3.6
- pyodbc: 
- OS:  MAC
- DB:
- driver:

### Issue

Following instructions from this doc:
https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Mac-OSX

When running `brew install freetds --with-unixodbc`, got an error:
Error: invalid option: --with-unixodbc

Please help

**Comment by v-makouz** [comment]
This doesn't appear to be related to pyODBC. The homebrew github (https://github.com/Homebrew/brew/issues) is probably a more appropriate place to ask this. Or the FreeTDS (https://github.com/FreeTDS/freetds/issues) although this looks more like a homebrew issue.

**Comment by gordthompson** [comment]
If @keitherskine wants to update his wiki page it might help if you tell us what version of macOS you are running.

**Comment by raagha-b** [comment]
@Allan-Gong Is there a issue created anywhere for freetds or unixodbc ?
I am facing the same issue from mac 10.14 onwards.

**Comment by v-chojas** [comment]
Please try the [Microsoft ODBC driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/microsoft-odbc-driver-for-sql-server).
