### ISSUE TITLE
File in the wiki has a colon in the name

### ISSUE THREAD

**Issue by keitherskine** [mkleehammer/pyodbc#523]
This is a small thing, but the file for "Troubleshooting:-Generating-an-ODBC-trace-log" in the wiki has a colon in it, which isn't allowed in Windows filenames.  It would be kinda nice if the colon could be removed.  I haven't been able to figure out how to rename a file in a GitHub wiki.  I could just delete the old page and replace it but it might be better to keep the history.

**Comment by gordthompson** [comment]
Hi @keitherskine 

If I open that page in GitHub in a regular browser (Desktop version) and click the "Edit" button it looks like I can just change the title there. Would that change the "filename" on Windows? 

Sorry for the inconvenience, and apologies for sounding a bit thick, but I'm not sure 
1. how Windows filenames factor into this, and
2. why such filenames wouldn't be encoded as "Troubleshooting%3A ...".

**Comment by keitherskine** [comment]
Hi @gordthompson 

GitHub wikis are just git repos, of course.  It looks like the first time a wiki page is created, the git filename for it is taken from the title.  Hence, if the title has a colon in it, then the filename will have a colon in it.  Yes, changing the title of the wiki page is certainly possible, but I wasn't sure if that changed the name of the underlying file in git.  Maybe it does.  I confess I never tried.

The thing is, colons are not allowed in Windows filenames, so when I clone the pyodbc wiki to my Windows machine, the colon is removed from the filename.  This in turn makes git think I've renamed the file.

GitHub recommends not including certain characters in the titles of wiki pages:
https://help.github.com/en/articles/adding-or-editing-wiki-pages#about-wiki-filenames

This is very minor, I know.  I just wondered if you knew of a better way of solving this.

**Comment by gordthompson** [comment]
@keitherskine - Editing the title does in fact change the file name. See if the new title/file_name works better for you on Windows. (Seems okay to me on Xubuntu.)

**Comment by keitherskine** [comment]
That seems to have worked, @gordthompson .  The filename on Windows is now `Troubleshooting-–-Generating-an-ODBC-trace-log.md`.  Many thanks!  I'll remember that.
