### ISSUE TITLE
Decimal separator isn't detected properly

### ISSUE THREAD

**Issue by lauritzen** [mkleehammer/pyodbc#53]
We are running with the iSeries Access for Linux driver to DB2 on AS/400. When pyodbc initializes chDecimal is set incorrectly to the Python locale's decimal separator rather than the locale of the database driver. In our environment the driver is apparently English (.) and Python Danish (,) which ends up converting the unicode decimal number incorrectly as the separator is ignored.

**Comment by mkleehammer** [comment]
Commit c81ad64 adds the ability to configure this.
