### ISSUE TITLE
pyodbc connect string error

### ISSUE THREAD

**Issue by emiliajin** [mkleehammer/pyodbc#531]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.8 64bit
- pyodbc: 4.0.25, 4.0.26
- OS: Windows
- DB: SQL server 2017
- driver: SQL Server Native Client 11.0, ODBC Driver 13 for SQL Server, ODBC Driver 17 for SQL Server

### Issue
connection string **work** in this format:

 conn = pyodbc.connect('Driver={SQL Server Native Client 11.0};'
                       'Server=XXX\SQLEXPRESS;'
                       'PORT=1433;'
                       'USER=XX;'
                       'PASSWORD=XX;'
                       'Database=XX;'
                       'Trusted_Connection=yes;')

connection string **does not work** in this format:
 conn = pyodbc.connect('Driver={SQL Server Native Client 11.0};'
                       'Server=XXX\SQLEXPRESS, 1433;'
                       'USER=XX;'
                       'PASSWORD=XX;'
                       'Database=XX;'
                       'Trusted_Connection=yes;')
error when try to use this format: 
[08001] [Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 13 for SQL Server]Invalid connection string attribute (0); [08001] [Microsoft][ODBC Driver 13 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)'

Since I use django-pyodbc-azure, which construct the connection string of the 'not working' format if I explicitly specify port should be 1433, then this problem comes out. However, I search other examples, the 'not working' format are demonstrated in many examples. I think this should be a valid format. The second format is expected to work.

**Comment by mkleehammer** [comment]
You'll have to open a bug with django-pyodbc-azure - pyodbc does not use the connection string at all.  It simply passes it to the driver, so the driver is in charge of what is allowed and what is not.  I'm pretty sure the first format is correct and the second is what SQL Server Management Studio allows, but I think it was so they didn't have to put another GUI input field on the screen for something that isn't used very often.

Sorry I couldn't help.

**Comment by v-chojas** [comment]
This is the list of keywords which are supported by the ODBC Driver for SQL Server:
https://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute

Do not trust unofficial examples too much. They may have just copied it from somewhere else, and thus propagated the error.
