### ISSUE TITLE
MSSQL Warnings cause "Previous SQL Not a Query" Errors

### ISSUE THREAD

**Issue by ApoxyB** [mkleehammer/pyodbc#534]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7 32-bit
- pyodbc: 4.0.16
- OS: Windows 10
- DB: MSSQL (Mgmt studio 17.9.1, not sure of actual DB version)
- driver: unsure

### Issue

If I run a query that generates warnings, pyodbc will fail, claiming the SQL is not a query. I contend that MSSQL warnings should not nullify your query execution in pyodbc.  I'd expect that I could at least set a flag on the query to ignore warnings.  

I've trolled through the internet for several years hoping for a resolution to this but have never found a satisfactory one.  I eliminate warnings in my SQL whenever I can, but not all the entities I use are under my control, and some of those are (I am assured by their authors) not able to suppress the warnings. 
 (This is true primarily with some null aggregation warnings that occur in a view that performs a pivot.)  

Currently I toggle ansi_warnings off and on around the offending code, but that solution doesn't support cross-server queries which can be problematic when shifting from UAT to production environments.  It also causes some entities to fail with the followwing eror:

`Heterogeneous queries require the ANSI_NULLS and ANSI_WARNINGS options to be set for the connection. This ensures consistent query semantics. Enable these options and then reissue your query.
`

My hope is that this might also resolve the problem where SET NOCOUNT ON is required.

Thanks for all your fine work!

**Comment by v-makouz** [comment]
Can you give an example of such a query and DB schema?

**Comment by v-chojas** [comment]
Please also post [an ODBC trace](https://docs.microsoft.com/en-us/sql/odbc/admin/setting-tracing-options)

**Comment by ApoxyB** [comment]
Will do.  Working on a good example now - it seems my trivial one doesn't
reproduce so there may be additional complexities here that I'm trying to
track down.

Not sure if I'll be able to get an ODBC trace for you since I'm not an
admin but I'll speak w/ our DBAs and see what I can do.

**Comment by ApoxyB** [comment]
The exercise of putting together a naive reproduction of this has led me to believe that either the problem no longer exists or we mis-diagnosed it in the first place.  

The errors I was encountering today were actually due to the heterogeneous query error caused by my "set ansi_warnings off" on the cross-server query, which I did because I've always been convinced that null aggregate warnings will break my script.

I'll close this issue out.  Thanks a lot for your quick response and sorry for taking up your time!
