### ISSUE TITLE
Oracle multiple result sets

### ISSUE THREAD

**Issue by Lexcon** [mkleehammer/pyodbc#535]
Not really a bug report but is there any way to return multiple result sets in Oracle?

SQL Server is so easy:
select 1 as first
select 2 as second

and voilà, two resultsets. This seems to me like the bread and butter of even the most rudimentary database system. Oracles documentation seems to indicate that you need a stored procedure to return multiple result sets. But with a stored procedure you need to push the result of your select-statement into an 'output variable' as in:

OPEN C1 FOR SELECT 1 as First from dual;
OPEN C2 FOR SELECT 2 as Second from dual;

but these output parameters need to be passed INTO the query (Oracle logic). I don't want (and can't) pass output parameters into my query. I just want to query the database and receive the results.

Is that possible at all?

**Comment by gordthompson** [comment]
So what happens if you try this?

```python
sql = """\
select 1 as first FROM DUAL;
select 2 as second FROM DUAL;
"""
crsr.execute(sql)
rows = crsr.fetchall()
while True:
    print(rows)
    if crsr.nextset():
        rows = crsr.fetchall()
    else:
        break
```

**Comment by Lexcon** [comment]
Computer says no:)Oracle just won't accept that syntax.Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Gord Thompson <notifications@github.com> 
Datum: 01-03-19  20:55  (GMT+01:00) 
Aan: mkleehammer/pyodbc <pyodbc@noreply.github.com> 
Cc: Lexcon <robert@dotdata.nl>, Author <author@noreply.github.com> 
Onderwerp: Re: [mkleehammer/pyodbc] Oracle multiple result sets (#535) 

So what happens if you try this?
sql = """\
select 1 as first FROM DUAL;
select 2 as second FROM DUAL;
"""
crsr.execute(sql)
rows = crsr.fetchall()
while True:
    print(rows)
    if crsr.nextset():
        rows = crsr.fetchall()
    else:
        break

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mkleehammer/pyodbc","title":"mkleehammer/pyodbc","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mkleehammer/pyodbc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gordthompson in #535: So what happens if you try this?\r\n\r\n```python\r\nsql = \"\"\"\\\r\nselect 1 as first FROM DUAL;\r\nselect 2 as second FROM DUAL;\r\n\"\"\"\r\ncrsr.execute(sql)\r\nrows = crsr.fetchall()\r\nwhile True:\r\n    print(rows)\r\n    if crsr.nextset():\r\n        rows = crsr.fetchall()\r\n    else:\r\n        break\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/mkleehammer/pyodbc/issues/535#issuecomment-468791439"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mkleehammer/pyodbc/issues/535#issuecomment-468791439",
"url": "https://github.com/mkleehammer/pyodbc/issues/535#issuecomment-468791439",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by keitherskine** [comment]
This is Oracle, so maybe try:
```python
sql = """\
BEGIN
select 1 as first FROM DUAL;
select 2 as second FROM DUAL;
END;
"""
...
```

**Comment by Lexcon** [comment]
Thanks. I tried a lot. This included. Oracle just can't do this. I even think it's documented but i figured maybe there is a workaround.Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Keith Erskine <notifications@github.com> 
Datum: 01-03-19  22:50  (GMT+01:00) 
Aan: mkleehammer/pyodbc <pyodbc@noreply.github.com> 
Cc: Lexcon <robert@dotdata.nl>, Author <author@noreply.github.com> 
Onderwerp: Re: [mkleehammer/pyodbc] Oracle multiple result sets (#535) 

This is Oracle, so maybe try:
sql = """\
BEGIN
select 1 as first FROM DUAL;
select 2 as second FROM DUAL;
END;
"""
...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mkleehammer/pyodbc","title":"mkleehammer/pyodbc","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mkleehammer/pyodbc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@keitherskine in #535: This is Oracle, so maybe try:\r\n```python\r\nsql = \"\"\"\\\r\nBEGIN\r\nselect 1 as first FROM DUAL;\r\nselect 2 as second FROM DUAL;\r\nEND;\r\n\"\"\"\r\n...\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/mkleehammer/pyodbc/issues/535#issuecomment-468824198"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mkleehammer/pyodbc/issues/535#issuecomment-468824198",
"url": "https://github.com/mkleehammer/pyodbc/issues/535#issuecomment-468824198",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by reedjosh** [comment]
Couldn't you do: 
```sql
select 1 as first FROM DUAL
union all
select 2 as second FROM DUAL;
```
?

**Comment by Lexcon** [comment]
No because the resultsets are of different sorts:

- select * from persons where personid = 123
- select * from orders where personid = 123
- select * from payments where personid = 1234

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
