### ISSUE TITLE
cannot use servername\instancename

### ISSUE THREAD

**Issue by gwsampso** [mkleehammer/pyodbc#537]
For some reason i cannot pass an instance name in the connection string?

I've tried a range a range of tests outlined below.

### Environment

- Python: 3.6.7
- pyodbc: 4.0.25
- OS: Ubuntu 18.04.2 LTS
- DB: MS SQL 2017
- driver: ODBC 17

### Tests

**Test 1 - works using ODBC 17**
```
sqlcmd -S IPAddress\\DEV01,1433 -U user -P 'Password' -Q "SELECT @@version;"
```

**Test 2 - works using freeTDS** 
```
import pyodbc
conn = pyodbc.connect('DRIVER={freetds};SERVER=IPAddress\DEV01;PORT=1433;DATABASE=CHAMP_DW;UID=user;PWD=Password;')
cursor = conn.cursor()
cursor.execute("SELECT @@version")
row = cursor.fetchone()
if row:
    print(row)
```

** test 3 - FAIL**
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
```
import pyodbc
conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=IPAddress\DEV01;DATABASE=CHAMP_DW;UID=user;PWD=Password;')
```

** test 4 - FAIL**
```
import pyodbc
conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=IPAddress\DEV01;PORT=1433;DATABASE=CHAMP_DW;UID=user;PWD=Password;')
```

** test 5 - FAIL**
```
import pyodbc
conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=IPAddress\\DEV01;DATABASE=CHAMP_DW;UID=user;PWD=Password;')
```

** test 6 - WORKS**
```
import pyodbc
conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=IPAddress;PORT=1433,DATABASE=CHAMP_DW;UID=user;PWD=Password;')
```

**Comment by v-makouz** [comment]
Named instances are not yet enabled on Linux version of the ODBC Driver 17 for SQL Server.

**Comment by v-chojas** [comment]
You can connect to a named instance by finding its port and explicitly specifying it in the connection string.

**Comment by gordthompson** [comment]
re: comment from @v-chojas 

> You can connect to a named instance by finding its port and explicitly specifying it in the connection string.

or you can use my [sqlserverport](https://github.com/gordthompson/sqlserverport) utility as a workaround.

**Comment by gwsampso** [comment]
I thought named instances are enabled, as I connect using ODBC 17 and the following 

`sqlcmd -S IPAddress\\DEV01,1433 -U user -P 'Password' -Q "SELECT @@version;"`

Interesting to note django-pyodbc-azure connects with named instance

**Comment by gordthompson** [comment]
@gwsampso  - At least for your `sqlcmd` example, you are already providing the port number so the instance name that you (try to) provide is being ignored.

I have a box with an instance named `\SQLEXPRESS` listening on port 49242. Yes, this works on Linux ...

```
sqlcmd -S 192.168.0.179\\SQLEXPRESS,49242 -U sa -P _whatever_
```

... but so does this ...

```
sqlcmd -S 192.168.0.179\\NONEXISTENT,49242 -U sa -P _whatever_
```

OTOH, this does *not* work on Linux ...

```
sqlcmd -S 192.168.0.179\\SQLEXPRESS -U sa -P _whatever_
```

... and neither does this:

```
sqlcmd -S 192.168.0.179\SQLEXPRESS -U sa -P _whatever_
```
