### ISSUE TITLE
Error connecting to the database : Database driver issue?

### ISSUE THREAD

**Issue by kevalshah90** [mkleehammer/pyodbc#544]
### Environment

- Python: 3.7.0
- pyodbc: 4.0.24
- OS: Mac OS Mojave 10.14.3
- DB: MySQL
- driver: MySQL ODBC 8.0 Driver

### Issue

Unable to connect to the database. Getting the following error when attempting to connect to the DB. 

Error: ('01000', u"[01000] [unixODBC][Driver Manager]Can't open lib 'MySQL ODBC 8.0 Driver' : file not found (0) (SQLDriverConnect)")

Code: 

connstr = pyodbc.connect(Driver='{MySQL ODBC 8.0 Driver}',
server='localhost',
Database='dbname1',
UID='root',
PWD='xxxxxx')

Contents of odbcinst.ini file - 

[ODBC Drivers]
MySQL ODBC 8.0 Unicode Driver = Installed
MySQL ODBC 8.0 ANSI Driver = Installed

[ODBC Connection Pooling]
PerfMon = 0
Retry Wait =

[MySQL ODBC 8.0 Unicode Driver]
Driver = /usr/local/mysql-connector-odbc-8.0.15-macos10.14-x86-64bit/lib/libmyodbc8w.so

[MySQL ODBC 8.0 ANSI Driver]
Driver = /usr/local/mysql-connector-odbc-8.0.15-macos10.14-x86-64bit/lib/libmyodbc8a.so

**Comment by gordthompson** [comment]
Does [this comment in another issue](https://github.com/mkleehammer/pyodbc/issues/264#issuecomment-474499754) imply that this issue can be closed now? If so, then please close this.
