### ISSUE TITLE
pyodbc + msodbcsql on macOS may cause segmentation fault.

### ISSUE THREAD

**Issue by kitsuyui** [mkleehammer/pyodbc#545]
(This is transcribe from https://github.com/Microsoft/homebrew-mssql-release/issues/30 .)

I have running Python + pyodbc + msodbcsql on my macOS.
And I have encountered segmentation fault on several times.

I created following reproduction code. This become always segmentation fault on my environment.

```python
import threading

import pyodbc


def task():
    connection_string = (
        'DRIVER={ODBC Driver 17 for SQL Server};'
        'SERVER={127.0.0.1};'
        'UID={sa};'
        'PWD={...}'
    )
    conn = pyodbc.connect(connection_string)
    conn.execute("SELECT 1")
    conn.close()


def main():
    threads = []
    for i in range(100):
        thread = threading.Thread(target=task)
        thread.start()
        threads.append(thread)

    for thread in threads:
        thread.join()


if __name__ == '__main__':
    main()
```

## Expected behavior

All threads works and complete the process.

```
$ python3 repro.py
$ 
```

## Actual

Suddenly process crash with segmentation fault.
I can't access the usual python error stack trace.

```
$ python3 repro.py
Segmentation fault: 11
$
```

# Environment

### macOS version

macOS Mojave 10.14.3 (18D109)

## Homebrew installation version

```
microsoft/mssql-release/msodbcsql17: stable 17.3.1.1
unixodbc: stable 2.3.7 (bottled)
```

## Python version

Python3 installed with homebrew.

```
Python 3.7.2 (default, Feb 12 2019, 08:15:36)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
```

## pyodbc version

```
pyodbc==4.0.27b1
```

# Stack trace

```
Thread 17 Crashed:
0   ???                           	0x000000010e567ddb 0 + 4535516635
1   ???                           	0x000000010e518952 0 + 4535191890
2   ???                           	0x000000010e5259df 0 + 4535245279
3   org.python.python             	0x000000010dfc4668 _PyMethodDef_RawFastCallKeywords + 545
4   org.python.python             	0x000000010dfc3bd3 _PyCFunction_FastCallKeywords + 44
5   org.python.python             	0x000000010e0595f0 call_function + 636
6   org.python.python             	0x000000010e052231 _PyEval_EvalFrameDefault + 7016
7   org.python.python             	0x000000010dfc3fae function_code_fastcall + 112
8   org.python.python             	0x000000010e052548 _PyEval_EvalFrameDefault + 7807
9   org.python.python             	0x000000010dfc3fae function_code_fastcall + 112
10  org.python.python             	0x000000010e059665 call_function + 753
11  org.python.python             	0x000000010e052218 _PyEval_EvalFrameDefault + 6991
12  org.python.python             	0x000000010dfc3fae function_code_fastcall + 112
13  org.python.python             	0x000000010e059665 call_function + 753
14  org.python.python             	0x000000010e052218 _PyEval_EvalFrameDefault + 6991
15  org.python.python             	0x000000010dfc3fae function_code_fastcall + 112
16  org.python.python             	0x000000010dfc4931 _PyObject_Call_Prepend + 150
17  org.python.python             	0x000000010dfc3ce1 PyObject_Call + 136
18  org.python.python             	0x000000010e0c0eee t_bootstrap + 71
19  org.python.python             	0x000000010e087847 pythread_wrapper + 25
20  libsystem_pthread.dylib       	0x00007fff6c44e305 _pthread_body + 126
21  libsystem_pthread.dylib       	0x00007fff6c45126f _pthread_start + 70
22  libsystem_pthread.dylib       	0x00007fff6c44d415 thread_start + 13
```

# Note

I also tried with pyodbc commenting-out  `Py_BEGIN_ALLOW_THREADS` and `Py_END_ALLOW_THREADS` and built by my own.

Then it works properly (It runs without error).

https://github.com/mkleehammer/pyodbc/blob/36e79af13da09ae9514b010ed445b0a4df306fab/src/connection.cpp#L113-L115

**Comment by v-chojas** [comment]
After some more investigation it appears this is a problem in the ODBC driver related to retrieving diagnostic messages from multiple threads during connection. Your workaround, which disables multithreaded connections, will decrease performance but should suffice to prevent the crashing until a newer version of the ODBC driver is available with the bug fixed.

**Comment by kitsuyui** [comment]
Hi, @v-chojas. I am sorry to have delayed in in replying.

> ... this is a problem in the ODBC driver ...

Which of these do you mean the problem is in?

1. Microsoft ODBC Driver
2. Unix ODBC
3. pyodbc

If you mean 1 or 2, I think we had better to move this issue to the appropriate project.

**Comment by v-chojas** [comment]
The problem is in the ODBC driver and will be fixed in the next release (17.4).

**Comment by kitsuyui** [comment]
I found msodbcsql17 17.4.1.1 has been released.
And it seems to work properly.

**Comment by v-chojas** [comment]
Good to hear. You may close this issue if everything works for you.

**Comment by kitsuyui** [comment]
Many thanks!
