### ISSUE TITLE
Unable to convert to string 

### ISSUE THREAD

**Issue by AvinashKallem** [mkleehammer/pyodbc#546]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 
- pyodbc: 
- OS: 
- DB:
- driver:

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
I have obtained a list from sql server - table - row values as below and enumerated the list

0 Esurance
1 NYCM
2 AAA Michigan
3 Sentry
4 NGIC

but in the dictionary the values are displayed as below

{0: ('Esurance', ), 1: ('NYCM', ), 2: ('AAA Michigan', ), 3: ('Sentry', ), 4: ('NGIC', )}

 Which Customer would you like to choose?
    Enter a number or * for all:        1
You Selected [('NYCM', )]....

How to print the customer name as ['NYCM'] or dictionary values should be like 
{0: Esurance, 1: NYCM, 2: AAA Michigan, 3: Sentry, 4: NGIC}

Below is the code:

import pyodbc

sqlconn = pyodbc.connect('Driver={SQL Server Native Client 11.0};'
                                                        'Server=SERVER; '
                                                        'Database=DATABASE; '
                                                         'Trusted_Connection=yes; ' )
cursor = sqlconn.cursor()
customers= cursor.execute('SELECT DISTINCT CustomerName FROM dbo.Table')
customers = cursor.fetchall()
customer_list = []

for count, row in enumerate(customers):
    print(count, row.CustomerName)

customer_list = dict(enumerate(customers))
print(customer_list)

customer_Num= input(''' Which Customer would you like to choose?
    Enter a number or * for all:        ''')

if customer_Num == '*':
    custs = customer_list.values()
    print(f'You selected ALL customers....')
else:
    custs = str([customer_list.get(int(customer_Num))])
    print(f'You Selected {str(custs)}....')

cursor.commit()
sqlconn.close()

**Comment by gordthompson** [comment]
`fetchall` returns a list of `pyodbc.Row` objects. `('Esurance', )` is the printed representation of a `Row` object containing a single value, much like a tuple.

If you want to convert those `Row` objects to simple strings then use

```python
customer_list = dict(enumerate(item[0] for item in customers))
```

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Comment by ImMahima** [comment]
Thank you so much gordthompson! I was stuck in a similar situation for a week. Your solution saved me.
