### ISSUE TITLE
Inserting into SQL server with fast_executemany results in MemoryError

### ISSUE THREAD

**Issue by dherrebout** [mkleehammer/pyodbc#547]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.8
- pyodbc: 4.0.26
- OS: Alpine 3.8
- DB: Azure SQL Database
- driver: Microsoft ODBC Driver 17 for SQL Server

### Issue
I'm loading data from a SQL Server 2016 towards Azure SQL Database. When inserting rows with a parameterized insert statement and fast_executemany=False, it works perfectly fine. When turning fast_executemany on, a very brief error message is displayed:
`in bulk_insert_rows
    cursor.executemany(sql, row_chunk)
MemoryError`

This is all I get. I've tried setting different encodings on the connection, such as described here: https://github.com/mkleehammer/pyodbc/wiki/Unicode. It fails every single time with fast_executemany on True and succeeds every single time with it turned off.

Looking for other ideas to troubleshoot. Thanks.

**Comment by v-chojas** [comment]
How many rows are you trying to insert, what is the schema of the table, and how much memory do you have?

The `fast_executemany` feature constructs the entire rowset in memory to send all at once to the driver, which is how it gets its performance, but that also means it requires far more memory than regular executemany.

**Comment by dherrebout** [comment]
The batch sizes are only 100 rows and 10 columns wide. Without fast_executemany there are even more insert statement than with, if I'm right? But I've also tried with 10 rows and even then no luck.

Also, the error message is very brief, but to me memory error sounds like something else than memory overload?

**Comment by v-chojas** [comment]
What are the types of the columns? Could you post an ODBC trace as well?

**Comment by dherrebout** [comment]
Is there any way to make pyodbc itself more verbose? It would be useful to have a longer error message than just 'MemoryError'. 

I've made an ODBC trace with one table as example. It happened with all tables and all kinds of column types, but this specific table has the following types:
- datetime2
- uniqueidentifier
- ntext

Here is the ODBC trace of the last SQL statement that executed before the error occured. The only other thing that happened was reading data from another source, which succeeded. It was a MERGE INTO statement, but the error also occurred with INSERT INTO. 

Please remind that this exact setup works perfectly when setting `cursor.fast_executemany=False`.

ODBC trace:
`[ODBC][43][1553422489.399663][SQLDriverConnectW.c][290]
		Entry:
			Connection = 0x55c831bd68e0
			Window Hdl = (nil)
			Str In = [driver=ODBC Driver 17 for SQL Server;server=xxxx.database.windows.net;uid=xxxx@xxxx;pwd=xxxx;database=xxxx...][length = 144 (SQL_NTS)]
			Str Out = (nil)
			Str Out Max = 0
			Str Out Ptr = (nil)
			Completion = 0
		UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UTF-16LE'

[ODBC][43][1553422491.794425][SQLDriverConnectW.c][914]
		Exit:[SQL_SUCCESS_WITH_INFO]                    
			Connection Out [[NULL]]
[ODBC][43][1553422491.803928][SQLSetConnectAttr.c][399]
		Entry:
			Connection = 0x55c831bd68e0
			Attribute = SQL_ATTR_AUTOCOMMIT
			Value = (nil)
			StrLen = -5
[ODBC][43][1553422491.858737][SQLSetConnectAttr.c][862]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422491.866251][SQLAllocHandle.c][540]
		Entry:
			Handle Type = 3
			Input Handle = 0x55c831bd68e0
[ODBC][43][1553422491.870757][SQLAllocHandle.c][1085]
		Exit:[SQL_SUCCESS]
			Output Handle = 0x55c831bd7d70
[ODBC][43][1553422491.887481][SQLFreeStmt.c][144]
		Entry:
			Statement = 0x55c831bd7d70
			Option = 0
[ODBC][43][1553422491.892978][SQLFreeStmt.c][266]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422491.898865][SQLPrepareW.c][165]
		Entry:
			Statement = 0x55c831bd7d70
			SQL = [MERGE INTO xxxx.xxxx AS Target USING (SELECT * FROM (VALUES (?,?,?,?,?,?,?)) AS t (ID, CreatedOn, UpdatedO...][length = 717]
[ODBC][43][1553422491.905985][SQLPrepareW.c][346]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422491.911176][SQLNumParams.c][144]
		Entry:
			Statement = 0x55c831bd7d70
			Param Count = 0x7ffd7e3276be
[ODBC][43][1553422491.919205][SQLNumParams.c][231]
		Exit:[SQL_SUCCESS]
			Count = 0x7ffd7e3276be -> 7
[ODBC][43][1553422491.924571][SQLDescribeParam.c][185]
		Entry:
			Statement = 0x55c831bd7d70
			Parameter Number = 1
			SQL Type = 0x55c831c88a42
			Param Def = 0x55c831c88a48
			Scale = 0x55c831c88a50
			Nullable = 0x7ffd7e327788
[ODBC][43][1553422492.024730][SQLDescribeParam.c][338]
		Exit:[SQL_SUCCESS]                
			SQL Type = 0x7ffd7e327210                
			Param Def = 0x7ffd7e327300                
			Scale = 0x7ffd7e3273f0                
			Nullable = 0x7ffd7e3274e0
[ODBC][43][1553422492.041028][SQLDescribeParam.c][185]
		Entry:
			Statement = 0x55c831bd7d70
			Parameter Number = 2
			SQL Type = 0x55c831c88aaa
			Param Def = 0x55c831c88ab0
			Scale = 0x55c831c88ab8
			Nullable = 0x7ffd7e327788
[ODBC][43][1553422492.059479][SQLDescribeParam.c][338]
		Exit:[SQL_SUCCESS]                
			SQL Type = 0x7ffd7e327210                
			Param Def = 0x7ffd7e327300                
			Scale = 0x7ffd7e3273f0                
			Nullable = 0x7ffd7e3274e0
[ODBC][43][1553422492.070956][SQLDescribeParam.c][185]
		Entry:
			Statement = 0x55c831bd7d70
			Parameter Number = 3
			SQL Type = 0x55c831c88b12
			Param Def = 0x55c831c88b18
			Scale = 0x55c831c88b20
			Nullable = 0x7ffd7e327788
[ODBC][43][1553422492.083527][SQLDescribeParam.c][338]
		Exit:[SQL_SUCCESS]                
			SQL Type = 0x7ffd7e327210                
			Param Def = 0x7ffd7e327300                
			Scale = 0x7ffd7e3273f0                
			Nullable = 0x7ffd7e3274e0
[ODBC][43][1553422492.093793][SQLDescribeParam.c][185]
		Entry:
			Statement = 0x55c831bd7d70
			Parameter Number = 4
			SQL Type = 0x55c831c88b7a
			Param Def = 0x55c831c88b80
			Scale = 0x55c831c88b88
			Nullable = 0x7ffd7e327788
[ODBC][43][1553422492.104143][SQLDescribeParam.c][338]
		Exit:[SQL_SUCCESS]                
			SQL Type = 0x7ffd7e327210                
			Param Def = 0x7ffd7e327300                
			Scale = 0x7ffd7e3273f0                
			Nullable = 0x7ffd7e3274e0
[ODBC][43][1553422492.114322][SQLDescribeParam.c][185]
		Entry:
			Statement = 0x55c831bd7d70
			Parameter Number = 5
			SQL Type = 0x55c831c88be2
			Param Def = 0x55c831c88be8
			Scale = 0x55c831c88bf0
			Nullable = 0x7ffd7e327788
[ODBC][43][1553422492.126630][SQLDescribeParam.c][338]
		Exit:[SQL_SUCCESS]                
			SQL Type = 0x7ffd7e327210                
			Param Def = 0x7ffd7e327300                
			Scale = 0x7ffd7e3273f0                
			Nullable = 0x7ffd7e3274e0
[ODBC][43][1553422492.137909][SQLDescribeParam.c][185]
		Entry:
			Statement = 0x55c831bd7d70
			Parameter Number = 6
			SQL Type = 0x55c831c88c4a
			Param Def = 0x55c831c88c50
			Scale = 0x55c831c88c58
			Nullable = 0x7ffd7e327788
[ODBC][43][1553422492.146936][SQLDescribeParam.c][338]
		Exit:[SQL_SUCCESS]                
			SQL Type = 0x7ffd7e327210                
			Param Def = 0x7ffd7e327300                
			Scale = 0x7ffd7e3273f0                
			Nullable = 0x7ffd7e3274e0
[ODBC][43][1553422492.156634][SQLDescribeParam.c][185]
		Entry:
			Statement = 0x55c831bd7d70
			Parameter Number = 7
			SQL Type = 0x55c831c88cb2
			Param Def = 0x55c831c88cb8
			Scale = 0x55c831c88cc0
			Nullable = 0x7ffd7e327788
[ODBC][43][1553422492.165468][SQLDescribeParam.c][338]
		Exit:[SQL_SUCCESS]                
			SQL Type = 0x7ffd7e327210                
			Param Def = 0x7ffd7e327300                
			Scale = 0x7ffd7e3273f0                
			Nullable = 0x7ffd7e3274e0
[ODBC][43][1553422492.174531][SQLBindParameter.c][217]
		Entry:
			Statement = 0x55c831bd7d70
			Param Number = 1
			Param Type = 1
			C Type = -8 SQL_C_WCHAR
			SQL Type = -11 
			Col Def = 36
			Scale = 0
			Rgb Value = 0x10
			Value Max = 72
			StrLen Or Ind = 0x58
[ODBC][43][1553422492.183767][SQLBindParameter.c][434]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.192958][SQLBindParameter.c][217]
		Entry:
			Statement = 0x55c831bd7d70
			Param Number = 2
			Param Type = 1
			C Type = -8 SQL_C_WCHAR
			SQL Type = -11 
			Col Def = 36
			Scale = 0
			Rgb Value = 0x60
			Value Max = 72
			StrLen Or Ind = 0xa8
[ODBC][43][1553422492.201846][SQLBindParameter.c][434]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.216360][SQLBindParameter.c][217]
		Entry:
			Statement = 0x55c831bd7d70
			Param Number = 3
			Param Type = 1
			C Type = 93 SQL_C_TYPE_TIMESTAMP 
			SQL Type = 93 SQL_TYPE_TIMESTAMP
			Col Def = 27
			Scale = 7
			Rgb Value = 0xb0
			Value Max = 16
			StrLen Or Ind = 0xc0
[ODBC][43][1553422492.228062][SQLBindParameter.c][434]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.238050][SQLBindParameter.c][217]
		Entry:
			Statement = 0x55c831bd7d70
			Param Number = 4
			Param Type = 1
			C Type = 93 SQL_C_TYPE_TIMESTAMP 
			SQL Type = 93 SQL_TYPE_TIMESTAMP
			Col Def = 27
			Scale = 7
			Rgb Value = 0xc8
			Value Max = 16
			StrLen Or Ind = 0xd8
[ODBC][43][1553422492.247999][SQLBindParameter.c][434]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.260835][SQLBindParameter.c][217]
		Entry:
			Statement = 0x55c831bd7d70
			Param Number = 5
			Param Type = 1
			C Type = 93 SQL_C_TYPE_TIMESTAMP 
			SQL Type = 93 SQL_TYPE_TIMESTAMP
			Col Def = 27
			Scale = 7
			Rgb Value = 0xe0
			Value Max = 16
			StrLen Or Ind = 0xf0
[ODBC][43][1553422492.271122][SQLBindParameter.c][434]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.280138][SQLBindParameter.c][217]
		Entry:
			Statement = 0x55c831bd7d70
			Param Number = 6
			Param Type = 1
			C Type = 93 SQL_C_TYPE_TIMESTAMP 
			SQL Type = 93 SQL_TYPE_TIMESTAMP
			Col Def = 27
			Scale = 7
			Rgb Value = 0xf8
			Value Max = 16
			StrLen Or Ind = 0x108
[ODBC][43][1553422492.289149][SQLBindParameter.c][434]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.298582][SQLBindParameter.c][217]
		Entry:
			Statement = 0x55c831bd7d70
			Param Number = 7
			Param Type = 1
			C Type = -8 SQL_C_WCHAR
			SQL Type = -10 
			Col Def = 1073741823
			Scale = 0
			Rgb Value = 0x110
			Value Max = 2147483646
			StrLen Or Ind = 0x8000010e
[ODBC][43][1553422492.307352][SQLBindParameter.c][434]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.317084][SQLFreeStmt.c][144]
		Entry:
			Statement = 0x55c831bd7d70
			Option = 3
[ODBC][43][1553422492.328063][SQLFreeStmt.c][266]
		Exit:[SQL_SUCCESS]
[ODBC][43][1553422492.337245][SQLEndTran.c][417]
		Entry:                
			Connection = 0x55c831b78810                
			Completion Type = 1
[ODBC][43][1553422492.377272][SQLGetInfo.c][236]
		Entry:
			Connection = 0x55c831b78810
			Info Type = SQL_CURSOR_COMMIT_BEHAVIOR (23)
			Info Value = 0x55c831b79c88
			Buffer Length = 2
			StrLen = 0x7ffd7e32781e
[ODBC][43][1553422492.386953][SQLGetInfo.c][236]
		Entry:
			Connection = 0x55c831b78810
			Info Type = SQL_CURSOR_ROLLBACK_BEHAVIOR (24)
			Info Value = 0x55c831b79c8a
			Buffer Length = 2
			StrLen = 0x7ffd7e32781e
[ODBC][43][1553422492.396740][SQLEndTran.c][566]
		Exit:[SQL_SUCCESS]`

**Comment by dherrebout** [comment]
After a lot of testing I found out that the problem is with the specific NTEXT column type, and not with all column types as I thought before. I just have a lot of tables including this column type so that made me think it happens for all types.

As a test, I've altered the NTEXT columns in a table to NVARCHAR(max) in the database I'm writing to. This "resolved" the issue and everything worked. However, I don't have the ability to change everything in all destinations.

Apparently, the issue is that the fast_executemany cursor can't handle NTEXT types, while executemany with fast_executemany=False can.

**Comment by v-chojas** [comment]
The driver returns TEXT/NTEXT as having a maximum size of 2GB --- so in fast_executemany mode, it will attempt to allocate a 2GB buffer for each cell of that type, certainly leading to the memory error you're experiencing.

**Comment by v-chojas** [comment]
In contrast, (n)varchar(max) is described as having a size of 0 ( "unlimited" ), causing fast_executemany to use a different strategy (DAE) to handle those columns.

**Comment by dherrebout** [comment]
So, would it make sense to plot that same strategy on the TEXT/NTEXT fields?

**Comment by gordthompson** [comment]
@v-chojas - Might it be possible to work around the issue by using [setinputsizes](https://github.com/mkleehammer/pyodbc/wiki/Cursor#setinputsizeslist_of_value_tuples) to map the NTEXT columns to `pyodbc.SQL_WVARCHAR`?

**Comment by v-chojas** [comment]
@gordthompson yes, using SQL_WVARCHAR works:

```
cursor.setinputsizes([(pyodbc.SQL_WVARCHAR, 0, 0)])
```
(The (0, 0) for size and precision instructs the driver to bind as nvarchar(max) instead of regular nvarchar --- and is needed if you want to insert >4000 characters.)

**Comment by will133** [comment]
I have experienced this issue as well.  It turned out that there's something buggy on the SQLDescribeParam() call on a column with nvarchar(max) using the DataDirect odbc manager on Linux with MSSQL server.  The returned ColumnSize set is like 1GB instead of 0 like what's defined in the MSSQL server documentation.

Since ColumnSize is not 0, DAE is not used and the buffer is set to ColumnSize * sizeof(WCHAR) = 2GB in my case.  Thus, each row would need to allocate a 2GB buffer to hold this.  This is obviously bad as it may work when 1-2 rows are added but will definitely cause issues for many rows.  It may not be obvious to the user to set the setinputsizes to override the behavior.

Does it make more sense if the code can make a first pass to determine the input argument's string lengths based purely on the input strings, then allocate the buffers and walk over it again?  It'll be more inefficient but at least it'll take some of these guesswork away.

**Comment by will133** [comment]
Due to the ColumnSize of some of these varchar columns may be up to 4000, it may not be very memory efficient if you allocate a fixed-width buffer for all strings with that width in the executemany case.

Maybe it would make sense to basically bound the max non-DAE buffer length to a user-configurable values (say somthing smaller like 300 or even less).  Thus, if the ColumnSize for a varchar/nvarchar column would exceed this, you would force the DAE always?

**Comment by zzzeek** [comment]
there seem to be a whole lot of issues like this sitting open, which is unfortunate, however ideally pyodbc's feature should be chunking the data rather than using the entire batch at once.   Compare to psycopg2's feature https://www.psycopg.org/docs/extras.html#fast-execution-helpers which has a default page size that is also configurable.

**Comment by Andrej730** [comment]
Met the same issue. 
To summarize - issue is caused by table columns with `ntext`/`text` type. 

> The driver returns TEXT/NTEXT as having a maximum size of 2GB --- so in fast_executemany mode, it will attempt to allocate a 2GB buffer for each cell of that type, certainly leading to MemoryError

Current solution is to change type for `ntext`/`text` columns to `nvarchar(max / n)` or `nchar(n)` (or `varchar` or `char`). Which sounds more than reasonable given that those types are deprecated - https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2016

The other solution is to try to map ntext to nvarchar(max) using the following statement. Which seems like not always working (atleast for me, using ODBC Driver 17 for SQL Server)
```python
cursor.setinputsizes([(pyodbc.SQL_WVARCHAR, 0, 0)])
```
Also make sure that the driver you're using supports fast_executemany - https://github.com/mkleehammer/pyodbc/wiki/Driver-support-for-fast_executemany

One my suggestion about the issue is to change code and add check to `cursor.executemany` function executed with `fast_executemany` that will make sure `ntext` or `text` types are not used or will raise an descriptive exception otherwise (or atleast will warn about possible consequences).
