### ISSUE TITLE
Empty string results in invalid string or buffer error when using fast_executemany on SQL Server

### ISSUE THREAD

**Issue by dherrebout** [mkleehammer/pyodbc#548]
### Environment

To diagnose, we usually need to know the following, including version numbers. On Windows, be
sure to specify 32-bit Python or 64-bit:

Python: 3.6.8
pyodbc: 4.0.26
OS: Alpine 3.8
DB: Azure SQL Database
driver: Microsoft ODBC Driver 17 for SQL Server

### Issue

When trying to load data from a source table on SQL Server 2016 to a destination table (with the exact same schema) on Azure SQL Database and cursor.fast_executemany=True, I get an error `ERROR - ('HY090', '[HY090] [Microsoft][ODBC Driver 17 for SQL Server]Invalid string or buffer length (0) (SQLExecute)')`. The ODBC trace is included in this post. This error does not occur when cursor.fast_executemany=False.

The source table has the following data types:
- VARCHAR(30)
- DATETIME
- SMALLINT
- DECIMAL(7,2)
- TINYINT
- VARCHAR(256)
- UNIQUEIDENTIFIER
- CHAR(2)
- DATETIME2

### Hypothesis
Two of the VARCHAR(256) columns sometimes contain empty strings (type = string and length = 0), this is the only thing that makes this table different from other ones. [This post](https://github.com/mkleehammer/pyodbc/issues/371) made me think it would have something to do with empty strings. 

### Attempts on solving the problem
As mentioned in the post above, I've tried:
- Setting the empty strings to None
- Setting the empty strings to a non empty string (a whitespace)
These two didn't work.

- Disabling fast_executemany
This works, but is not desired.

I've also tried to modify empty strings directly in the SELECT query from source with `CASE WHEN len(column) = 0 THEN NULL END`, also without any luck. 

The post I mentioned above ends with the solution of switching to the latest ODBC driver, but I'm already using the latest driver (built fresh from source, exactly following Microsoft's instructions).

ODBC trace:
[20190325 ODBC trace invalid string buffer.log](https://github.com/mkleehammer/pyodbc/files/3003485/20190325.ODBC.trace.invalid.string.buffer.log)

**Comment by v-chojas** [comment]
I am not sure what you mean by "built fresh from source, exactly following Microsoft's instructions" because the Microsoft ODBC Driver for SQL Server is not open-source.

What version of unixODBC are you using? You can check with `odbcinst -j`

**Comment by dherrebout** [comment]
I meant downloaded the latest package and added it to the repo, as in [here ](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017). I'm using unixODBC 2.3.7.

**Comment by v-chojas** [comment]
Your trace shows SQLDescribeParam returning SQL_ERROR, which suggests that the server may be having difficulty identifying the parameter types.

Please try to enable `ColumnEncryption` or `UseFMTOnly` options in your connection string; this will use a different method of discovering metadata which might work instead of the default.

**Comment by urwa** [comment]
@dherrebout Were you able to solve it? I am having the exact same issue.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
