### ISSUE TITLE
MakeConnectionString does not appear to work for high unicode values.

### ISSUE THREAD

**Issue by tim-mitchell** [mkleehammer/pyodbc#550]
To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.13 64bit
- pyodbc: 3.0.7
- OS:  Windows 10 64bit
- DB:  "D:\Unicode 💀\Strat Sequence drillholes.accdb"
- driver:  Microsoft Access Driver (*.mdb, *.accdb)

### Issue
Connecting to an MS Access database with high-end unicode characters in the file path works if I use a single connection string, but fails if I use keyword parameters.  The skull face in the path above displays as \U0001f480 in my debugger and is 2 characters long.

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
This works (with unicode literals):
```
db = 'D:\\Unicode \U0001f480\\Strat Sequence drillholes.accdb'
conn_str = 'DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=' + db
pyodbc.connect(conn_str)
```
but this causes a traceback:
```
conn_info = {'DRIVER': 'DRIVER=Microsoft Access Driver (*.mdb, *.accdb)',
             'DBQ': 'D:\\Unicode \U0001f480\\Strat Sequence drillholes.accdb',
             }
pyodbc.connect(**conn_info)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)
```
I would expect both forms to work.

**Comment by v-makouz** [comment]
Try adding:
```
import sys  
reload(sys)  
sys.setdefaultencoding('utf8')
```
at the beginning of your file, that fixed the repro for me
