### ISSUE TITLE
Execution with TVP failed if user-defined table has identity column

### ISSUE THREAD

**Issue by killua8q8** [mkleehammer/pyodbc#551]
To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.12
- pyodbc: 4.0.26
- OS: Ubuntu 16.04.6
- DB: Microsoft SQL Server 2012 - 11.0.2100.60 (X64)
- driver: ODBC Driver 17 for SQL Server
- ODBC: unixODBC 2.3.7

### Issue

Trying to execute a stored procedure with TVP that has identity column, it failed with one of the following errors:
* `('42000', u'[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Trying to pass a table-valued parameter with 2 column(s) where the corresponding user-defined table type requires 3 column(s). (500) (SQLParamData)')`
* `('42000', u'[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]INSERT into an identity column not allowed on table variables. (1077) (SQLParamData)')`

Definition of SP and Table Type:
```python
try:
    crsr.execute('DROP TYPE TVP_TWO;')
    crsr.commit()
except Exception as e:
    pass

crsr.execute('''
CREATE TYPE TVP_TWO AS TABLE (
  c01 INT IDENTITY(1, 1),
  C02 NVARCHAR(16),
  c03 DATE
)
''')
crsr.commit()

proc_name = str(uuid.uuid4())
crsr.execute('CREATE PROCEDURE [' + proc_name + '] @TVP TVP_TWO READONLY AS SELECT * FROM @TVP;')
crsr.commit()
```

The first error occurs when skipping the value of identity column, which make the TVP parameter has one less value then its table definition.
```python
c01 = [1, 2, 3]
c02 = ['a', 'b', 'c']
c03 = [date(1997, 8, 29), date(1, 1, 1), date(9999, 12, 31)]

param_array = []
for i in range(3):
    param_array.append([c02[i], c03[i]])

result_array = crsr.execute('EXEC [' + proc_name + '] ?', [param_array]).fetchall()
```
[trace_1.txt](https://github.com/mkleehammer/pyodbc/files/3025130/trace_1.txt)

I would expect this should be the correct way to perform the execution as we usually not inserting any value manually into identity column unless with IDENTITY_INSERT. But if there is better way to do this, I would like to follow.
___
The second error occurs when including the identity column value.
```python
c01 = [1, 2, 3]
c02 = ['a', 'b', 'c']
c03 = [date(1997, 8, 29), date(1, 1, 1), date(9999, 12, 31)]

param_array = []
for i in range(3):
    param_array.append([c01[i], c02[i], c03[i]])

result_array = crsr.execute('EXEC [' + proc_name + '] ?', [param_array]).fetchall()
```
[trace_2.txt](https://github.com/mkleehammer/pyodbc/files/3025132/trace_2.txt)

___
Unexpected behavior also observed when the following code executed, but that is not intended to test.
```python
c01 = [1, 2, 3]
c02 = ['a', 'b', 'c']
c03 = [date(1997, 8, 29), date(1, 1, 1), date(9999, 12, 31)]

param_array = []
for i in range(3):
    param_array.append([c01[i], None, c03[i]])

try:
    result_array = crsr.execute('EXEC [' + proc_name + '] ?', [param_array]).fetchall()
except Exception as e:
    print(e)
finally:
    crsr.execute('DROP PROCEDURE [' + proc_name + '];')
    crsr.commit()
```
[trace_3.txt](https://github.com/mkleehammer/pyodbc/files/3025134/trace_3.txt)

Exception is catched when executing stored procedure
`('HY090', u'[HY090] [unixODBC][Driver Manager]Invalid string or buffer length (0) (SQLBindParameter)')`,
but then another exception raises when dropping procedure
`('HY024', u'[HY024] [Microsoft][ODBC Driver 17 for SQL Server]Invalid attribute value, SQL_SOPT_SS_PARAM_FOCUS (must be zero at execution time) (0) (SQLExecDirectW)')`.

**Comment by v-makouz** [comment]
It doesn't appear to be possible to pass a table type TVP with an identity column to a stored procedure. Without context it's hard to know what the solution should be, but if the stored procedure is meant to insert the data into a table one can either pass all three columns (but make all of them regular non-identity columns for the TVP type) and the 'SET IDENTITY_INSERT <table_name> ON', or remove the first column altogether and have the SP insert it the other two parameters normally. But, as I said I don't know if either of those works for your situation as I don't know what the SP is ultimately supposed to do.

**Comment by killua8q8** [comment]
Thanks for clarifying. Though, I have already walked around to drop and create the user table type without any identity column.

The database that I am working on is linked to an old executable that from 2 decades ago. Those tables don't even have a auto increment concept on some columns that require this behavior, and I don't want to mess with their schema, or that executable will just stop working without any warning.

I have an external API to replace the executable and the SP is part of it. I was just try to see if the TVP supports the identity column so I don't have to handle it at code. Looks can't skip it, lol.
