### ISSUE TITLE
pyodbc.ProgrammingError: ('The SQL contains 5 parameter markers, but 1 parameters were supplied', 'HY000')

### ISSUE THREAD

**Issue by MeRyyK** [mkleehammer/pyodbc#552]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.6 64bit, 
- pyodbc: 4.0.23
- OS: Win 8.1
- DB:SQlServer 2017
- driver: ODBC Driver 17 for SQL Server

### Issue
pyodbc.ProgrammingError: ('The SQL contains 5 parameter markers, but 1 parameters were supplied', 'HY000') is thrown by this code
 for p in x:   
        stmt.execute("""INSERT INTO dbo.DevicesA(remotecontrol_id, device_id, alias,groupid,
        online_state)) 
        values(?, ?, ?, ?, ?)""", p)
Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
observed behavior

**Comment by v-chojas** [comment]
It is exactly as the error message says --- you have supplied 1 parameter but the SQL statement requires 5. You need to supply 5 parameters:

```stmt.execute("INSERT INTO ... (?,?,?,?,?)", p1, p2, p3, p4, p5)```

**Comment by MeRyyK** [comment]
Thanks v-chojas!

I am doing something like p[10, p[2], p[3]...Not sure if that;s correct as it's now throwing
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near ')'. (102) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)

Why is this?

**Comment by MeRyyK** [comment]
Changed the INSERT to this:
for p in x:   
        stmt.execute("INSERT INTO dbo.TVDevicesA(remotecontrol_id, device_id, alias,groupid, online_state)) values(?, ?, ?, ?, ?), p[1], p[2], p[3], p[4], p[5]")
Gives me this:
pyodbc.Error: ('07002', '[07002] [Microsoft][ODBC Driver 13 for SQL Server]COUNT field incorrect or syntax error (0) (SQLExecDirectW)')

Does your product actually work with SQLServer? I am begging to have doubts.

**Comment by keitherskine** [comment]
You appear to have too many parentheses in your SQL query, and the closing double quote is misplaced.  There are two parentheses after "online_state" when it's looks like there should be only one, and the parameter values should not be part of the query.  Try something like:
```python
stmt.execute("INSERT INTO dbo.TVDevicesA (remotecontrol_id, device_id, alias, groupid, online_state) values (?, ?, ?, ?, ?)", p[1], p[2], p[3], p[4], p[5])
```
(And yes, pyodbc does indeed work with SQL Server, and has been doing so successfully for many years).

**Comment by MeRyyK** [comment]
keitherskine
1st sorry about the comment! 2nd I revamped my code as you describe. It now throws this:

pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near ')'. (102) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")

Again thanks!

**Comment by MeRyyK** [comment]
Hello Keitherskine>

Ok, I got it figured out looks like the parameters should start with p[0], I think.

Thanks again

**Comment by MeRyyK** [comment]
Tried some other things, now getting 
TypeError: function takes exactly 2 arguments (6 given)
Not that it works correctly anyway, running out of ideas, Think I am going to have to drop this and go back to C#

**Comment by MeRyyK** [comment]
Ok, I got it, FINALLY! this does it! And I need to lay off the hard stuff!
params = [(x["remotecontrol_id"]), (x["device_id"]), (x["alias"]), (x["groupid"]), (x["online_state"])]

thanks again!

**Comment by MartinRiddar** [comment]
> Ok, I got it, FINALLY! this does it! And I need to lay off the hard stuff!
> params = [(x["remotecontrol_id"]), (x["device_id"]), (x["alias"]), (x["groupid"]), (x["online_state"])]
> 
> thanks again!

Can you please close this issue since it seems that it is solved?

**Comment by jcnunez007** [comment]
And how the heck does the author's solution make any sense? ¯\_(ツ)_/¯
