### ISSUE TITLE
Connection close still leave sleeping SPID in MSSQL server

### ISSUE THREAD

**Issue by codeReader51** [mkleehammer/pyodbc#553]
### Environment

- Python: 64-bit
- pyodbc: 4.0.23
- OS: Windows
- DB: MSSQL
- Driver: SQL Server

### Issue

Consider the code snippet:
```
import pyodbc
conn = pyodbc.connect('connection string') 

csr = conn.cursor()  
csr.close()
conn.close() 
```

It closes the object `conn` properly (expected) and if I try to use it again, it'll yield `ProgrammingError` trying to use a closed connection (expected). However, when I use MSSQL studio and run `exec sp_who2`, I still see the connection to the database in sleeping state. If I try to drop the database, there'll be error: database in use.

Expected: the `conn.close()` will also kill the SPID in the db itself i.e. `exec sp_who2` should not show any connection to that db (assumming that the script is the only place accessing the db, and you are calling `sp_who2` from master db).

**Comment by gordthompson** [comment]
Perhaps try calling

```python
pyodbc.pooling = False
```

before opening your connection with `pyodbc.connect`. The ODBC Driver Manager on Windows supports connection pooling and the SQL Server ODBC drivers have pooling enabled by default.

**Comment by codeReader51** [comment]
@gordthompson Thanks for the pointer. Two questions:
1. So would this disable pooling on the SQL Server ODBC drivers permanently (i.e. for all future connections?) 
2. What if certain connections were connected before `pyodbc.pooling` was set to `False`? Is there away to close them too?

**Comment by gordthompson** [comment]
1. No, that would only affect the current ODBC connection. Completely disabling pooling for a particular driver would be done by double-clicking the driver name on the "Connection Pooling" tab of the ODBC Administrator applet in the Windows Control Panel (odbcad32.exe).

2. You would have to open a separate connection using credentials with sufficient permissions on the server and then kill the processes associated with the other connections. However, they should time out themselves after the "Pool Timeout" (default 60 seconds).

**Comment by codeReader51** [comment]
@gordthompson Thanks. You are the man!
