### ISSUE TITLE
pyodbc.Error: ('HYC00', '[HYC00] [Microsoft][ODBC SQL Server Driver]Optional feature not implemented (0) (SQLBindParameter)')

### ISSUE THREAD

**Issue by serak** [mkleehammer/pyodbc#554]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.26
- OS: Windows 10 x64
- DB: MSSQL 2017 
- driver: { SQL Server }

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
this works on pypyodbc but throws the below error on pyodbc

Traceback (most recent call last):
  File "c:/Users/Serak/Desktop/CRM STAGING TABLE/DemographicMigration.py", line 44, in <module>
    sql_cursor.execute("INSERT INTO [dbo].[CUSTOMER] VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",result_customer)
pyodbc.Error: ('HYC00', '[HYC00] [Microsoft][ODBC SQL Server Driver]Optional feature not implemented (0) (SQLBindParameter)')

**Comment by v-chojas** [comment]
The `SQL Server` driver is very old and does not support features of newer servers. Please try the Microsoft ODBC Driver 17 for SQL Server: https://www.microsoft.com/en-us/downloads/details.aspx?id=56567

**Comment by serak** [comment]
Thank you very much this is working now after i installed the ODBC Driver 17 and changed the connection string

`Driver={ODBC Driver 17 for SQL Server};`

**Comment by gordthompson** [comment]
@serak - Good to hear that you got it working. Please close this issue.
