### ISSUE TITLE
pyodbc compiles against iODBC but doesn't connect (Abort trap: 6)

### ISSUE THREAD

**Issue by paulolindoso** [mkleehammer/pyodbc#555]
### Environment
- Python: 3.7.3 
- pyodbc: 4.0.26
- OS: OSX Mojave 10.14.3
- DB: SQL Server
- driver: TDS

### Issue
I have successfully compiled pyodbc with iODBC; to do so, I had to alter setup.py to point to LIB and INCLUDE for iODBC files.  iODBC sqltypes.h did not include BYTE definition, so I added it manually and I also followed advice from issue #444.

Compilation was successful with no warnings.

Created a quick script to test:
import pyodbc
import locale
locale.resetlocale()
cnxn = pyodbc.connect('Driver=TDS64;'
                      'Server=<XXX>;'
                      'Database=<YYY>;'
                      'Trusted_Connection=yes;')
 
cursor = cnxn.cursor()
cursor.execute('SELECT top 10 *  FROM table')
 
for row in cursor:
    print(row)

EXPECTED BEHAVIOUR:
Script runs and prints ten rows from table and exits or conventional connection error.

OBSERVED BEHAVIOUR:
Script aborts with "Abort trap: 6"

ADDITIONAL INFO:
ODBC Trace
=========
python          11B6C25C0 ENTER SQLDriverConnectW
		SQLHDBC           0x7fb1c6400790
		SQLPOINTER        0x0
		SQLWCHAR        * 0x10ceba2a8
		SQLSMALLINT       -3 (SQL_NTS)
		SQLWCHAR        * 0x0
		SQLSMALLINT       0
		SQLSMALLINT     * 0x0
		SQLUSMALLINT      0 (SQL_DRIVER_NOPROMPT)

python          11B6C25C0 EXIT  SQLDriverConnectW with return code -1 (SQL_ERROR)
		SQLHDBC           0x7fb1c6400790
		SQLPOINTER        0x0
		SQLWCHAR        * 0x10ceba2a8
		SQLSMALLINT       -3 (SQL_NTS)
		SQLWCHAR        * 0x0
		SQLSMALLINT       0
		SQLSMALLINT     * 0x0
		SQLUSMALLINT      0 (SQL_DRIVER_NOPROMPT)

python          11B6C25C0 ENTER SQLDriverConnect
		SQLHDBC           0x7fb1c6400790
		SQLPOINTER        0x0
		SQLCHAR         * 0x10cec6398
				  | Driver=TDS64;Server=sql.pontodev.com.br; |
				  | Database=filetes;Trusted_Connection=yes; |
		SQLSMALLINT       -3 (SQL_NTS)
		SQLCHAR         * 0x0
		SQLSMALLINT       0
		SQLSMALLINT     * 0x0
		SQLUSMALLINT      0 (SQL_DRIVER_NOPROMPT)

python          11B6C25C0 EXIT  SQLDriverConnect with return code -1 (SQL_ERROR)
		SQLHDBC           0x7fb1c6400790
		SQLPOINTER        0x0
		SQLCHAR         * 0x10cec6398
		SQLSMALLINT       -3 (SQL_NTS)
		SQLCHAR         * 0x0
		SQLSMALLINT       0
		SQLSMALLINT     * 0x0
		SQLUSMALLINT      0 (SQL_DRIVER_NOPROMPT)

python          11B6C25C0 ENTER SQLGetDiagRecW
		SQLSMALLINT       2 (SQL_HANDLE_DBC)
		SQLHDBC           0x7fb1c6400790
		SQLSMALLINT       1
		SQLWCHAR        * 0x7ffee375d4b4
		SQLINTEGER      * 0x7ffee375cc94
		SQLWCHAR        * 0x7ffee375ccb0
		SQLSMALLINT       1023
		SQLSMALLINT     * 0x7ffee375ccae

python          11B6C25C0 EXIT  SQLGetDiagRecW with return code 0 (SQL_SUCCESS)
		SQLSMALLINT       2 (SQL_HANDLE_DBC)
		SQLHDBC           0x7fb1c6400790
		SQLSMALLINT       1
		SQLWCHAR        * 0x7ffee375d4b4
		SQLINTEGER      * 0x7ffee375cc94 (0)
		SQLWCHAR        * 0x7ffee375ccb0
		SQLSMALLINT       1023
		SQLSMALLINT     * 0x7ffee375ccae (53)

executed script with sudo dtruss python login/sql.py 1 > out.txt 2>&1 as well.  Trace doesn't indicate that either iODBC or FreeTDS libs were accessed or opened; however, odbc.ini and odbcinst.ini were fully accessed and read.

Any help would be dearly appreciated.

Thanks!

**Comment by paulolindoso** [comment]
*update*
installed python 2.7.16; same issue.

Further debugging pointed out the fact that apparently python setup.py install was not copying the compiled pyodbc.so to the lib directory in python; once I copied it manually, the error (Abort trap: 6) still remains, but tracing the syscalls now seem to point the issue to FreeTDS.

As I continue to investigate, I will post it here.

That said, I would still appreciate any feedback!

**Comment by v-chojas** [comment]
Did you also fix the bugs in iODBC noted in #444 ? The "abort trap" message on macOS is similar to Segmentation Fault in Linux, as noted there. If you did, then it could be another bug in iODBC.

If you can, I recommend using the Microsoft ODBC Driver for SQL Server with unixODBC instead: https://docs.microsoft.com/en-us/sql/connect/odbc/microsoft-odbc-driver-for-sql-server

**Comment by paulolindoso** [comment]
I've given up trying to use iODBC and re-installed my entire ODBC libs from scratch using BREW.  Then following up the instructions v-chojas kindly supplied, I was able to run my script!

The only thing left to fix was that the script could only run properly with SUDO.

Anty thoughts?
