### ISSUE TITLE
HY000 database disk image is malformed when database file is not malformed

### ISSUE THREAD

**Issue by ruisen2000** [mkleehammer/pyodbc#556]
### Environment

- Python: 2.7.15 32-bit
- pyodbc: 4.0.25
- OS: Windows 10
- DB: SQLITE 3
- driver: SQLite 3 ODBC driver v0.9996.00.00

### Issue
Observed:
When querying a local SQLite 3 database file, sometimes I get the error:
 pyodbc.Error: ('HY000', u'[HY000] database disk image is malformed (11) (11) (SQLExecDirectW)')
even though re-executing the query on the same database file will succeed.   This always happens on the same query and not on any of the others:

"SELECT path, name, comp FROM ((SELECT * FROM COMP_TABLE  WHERE  c_comp > 10) as comp LEFT JOIN FUNC_TABLE as func on func.id = comp.func_id LEFT JOIN FILES as file ON file.file_id = func.file_id WHERE comp.end_date = ?)"

Nothing different is done when this error happens, seems to happen randomly.   The local database file is downloaded to the machine via REST API.

**Comment by gordthompson** [comment]
Just curious: Why are you using SQLite ODBC when Python has built-in support for SQLite?

**Comment by v-chojas** [comment]
Please check whether the filesystem is working correctly, and that the database file is not corrupted.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
