### ISSUE TITLE
Intersystem Cache

### ISSUE THREAD

**Issue by jersonjunior** [mkleehammer/pyodbc#557]
Hello everyone, I am trying to connect to an Intersystem Caché database but without success, does pyodbc support this db?

Here is the error I get when connecting to db:

```
import pyodbc
con = pyodbc.connect('DRIVER=InterSystems ODBC;SERVER=192.168.0.9;DATABASE=CCMM_PREVIEW_DSN;UID=sysadmin;PWD=teste1')
```

Error: ('S1000', '[S1000] [Cache ODBC][State : S1000][Native Code 417]\r\n[C:\\Users\\jerson.junior\\AppData\\Local\\Continuum\\anaconda3\\python.exe]\r\nAcesso Negado (417) (SQLDriverConnect); [S1000] [Microsoft][ODBC Driver Manager] O driver não oferece suporte à versão de comportamento de ODBC solicitada pelo aplicativo (consulte SQLSetEnvAttr). (0)')

**Comment by gordthompson** [comment]
According to Google Translate, the error message says:

> The driver does not support the application-requested version of ODBC behavior

**Comment by v-chojas** [comment]
"Acesso Negado" = "Access Denied"

Ensure your credentials are correct, and that any special characters in passwords are escaped in the connection string (and Python string).

**Comment by gordthompson** [comment]
You could check an [ODBC trace](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) to see if this ODBC call is failing:

```
main            14b4-1fe8	ENTER SQLSetEnvAttr 
        SQLHENV             0x025D1AB8
        SQLINTEGER                 200 <SQL_ATTR_ODBC_VERSION>
        SQLPOINTER                 3 <SQL_OV_ODBC3>
        SQLINTEGER                   4 
```

If so, then you may need to dig up a newer version of the ODBC driver (if one exists).

**Comment by jersonjunior** [comment]
Works fine now, thanks:

import pyodbc 
import time
import pandas as pd

#input("Hit any key to start")

dsn = 'blablabla'
server = 'localhost' 
database = 'blablabla' 
username = 'sysadmin'
port ='1972'
password = 'blablabla' 
cnxn = pyodbc.connect('DRIVER={InterSystems ODBC};SERVER='+server+'; PORT='+port+'; DATABASE='+database+';UID='+username+';PWD='+ password)
#sql = "Select * From eAgentLoginStat"
#data = pandas.read_sql(sql,cnxn)
df = pd.read_sql('Select Timestamp, AgentLogin, AgentGivenName, EventType, Duration From eAgentLoginStat', con=cnxn)
df.dropna()

**Comment by InfoAlenia** [comment]
what was now the solution???????

**Comment by keitherskine** [comment]
I don't have a definitive answer to this, @InfoAlenia , but judging by the InterSystems pyodbc [example](https://docs.intersystems.com/irisforhealthlatest/csp/docbook/Doc.View.cls?KEY=BNETODBC_support#BNETODBC_support_pyodbc_test), it looks like you have to use their "InterSystems ODBC35" driver which supports ODBC version 3.5 (as opposed to the older "InterSystems ODBC" drivers).

Here's a [comment](https://community.intersystems.com/post/odbc-drivers) about where you can download ODBC drivers.
