### ISSUE TITLE
No encode involved when binding a fast_executemany parameter when sizeof(Py_UNICODE) != sizeof(SQLWCHAR)

### ISSUE THREAD

**Issue by will133** [mkleehammer/pyodbc#561]
It seems like if the unicode_enc is something other than UCS, it seems like this code would not go through the properl PyCodec_Encode?

https://github.com/mkleehammer/pyodbc/blob/45395fe723b837e836643897ff3df57034c05b22/src/params.cpp#L369-L390

If the size matches, it seems to just do a copy of the data in terms of PyUnicode_AS_DATA there.  For instance, if the driver takes in a say a UTF16 or UTF8 encoding, isn't that incorrect to just copy the python internal unicode representation into the buffer?  Or am I missing something?

**Comment by mkleehammer** [comment]
I believe that code has been reworked so I'm going to close this.  If you are still having an issue, please reopen.
