### ISSUE TITLE
Using DAE with fast_executemany causes segfault

### ISSUE THREAD

**Issue by will133** [mkleehammer/pyodbc#562]
It seems like the code here would simply call SQLParamData and set the pInfo pointer:

https://github.com/mkleehammer/pyodbc/blob/45395fe723b837e836643897ff3df57034c05b22/src/params.cpp#L1893-L1897

When I stepped through this code with my debugger, it seems like the SQLParamData would always return the same pointer location for the same parameters on different rows!  This causes a segfault on my code where the pInfo->cell get deferenced later on for multiple times when you iterate through the rows.

It seems like the documentation describes this behavior for the bind array case:

https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/using-arrays-of-parameters?view=sql-server-2017#data-at-execution-parameters

If I understand the doc correctly, it seems like the SQLParamData itself is not sufficient to get the pointer and you need to add other meta info on it.

In order for this to work , it seems like the code needs to set something like:

```c++
SQLULEN rows_processed = 0;

SQLSetStmtAttr(cur->hstmt, SQL_ATTR_PARAMS_PROCESSED_PTR, &rows_processed, SQL_IS_UINTEGER));
```

(while defining the rows_processed), and after the SQLParamData call, you need to do something like (where rowlen is the byte length of the row):

```c++
pInfo = (DAEParam*)(((char*)pInfo) + ((rows_processed - 1) * rowlen));
// you probably need to add the offset as well?
```

I'm not sure if there's another more elegant way to get the current row and the pointer location.  As-is though, I don't think the DAE is really correct.

**Comment by v-chojas** [comment]
> it seems like the SQLParamData would always return the same pointer location for the same parameters on different rows

What driver are you using? Could you provide more information about your environment?

The following script inserts 6 cells into a SQL Server table using fast_executemany DAE with ODBC Driver 17 for SQL Server:
```
conn = pyodbc.connect('<my connection string>', autocommit = True)
stmt = conn.cursor()
stmt.execute('create table test562(c1 varchar(max), c2 varchar(max))')
stmt.fast_executemany = True
stmt.executemany('insert into test562 values(?,?)', [ ['row1col1', 'row1col2'], ['row2col1', 'row2col2'], ['row3col1', 'row3col2'] ])
```
In the ODBC trace I can see the return value of SQLParamData is different for each cell, as expected.

**Comment by will133** [comment]
This is really strange.  I'm using pyodbc compiled with the DataDirect data manager (7.1.6, which is quite old but I can't upgrade due to constraints).  The part that I found puzzling is the ODBC API description such as this in my previous link:

> This means the value returned by SQLParamData is not sufficient to specify the parameter for which the application needs to send data; the application also needs to consider the current row number.

I interpreted this (and in the code I ran I also saw this behavior as well) as meaning that the pointer pInfo returned by the SQLParamData call is actually fixed and you need to use the row number to determine the exact position of the argument.  In my case, if I don't really move the pointer based on the row number I'll be referring to the same cell each time and obviously that would not work.

**Comment by v-chojas** [comment]
What driver are you using? Could you provide more information about your environment?

Note that pyODBC works best with unixODBC, and fast_executemany was developed with the Microsoft ODBC Driver for SQL Server in mind. The behaviour with any other DM or driver may not be optimal.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
