### ISSUE TITLE
Pyodbc error in databricks

### ISSUE THREAD

**Issue by kaarthickprabhu** [mkleehammer/pyodbc#565]
Hi,
    I'm using the pyodbc in databricks to connect to Azure sql using service principal, I'm using the following code

SQL_COPT_SS_ACCESS_TOKEN = 1256 
connString = "Driver={ODBC Driver 17 for SQL Server};SERVER=tcp:sqlserver.database.windows.net,1433;DATABASE=dbname"
             
#get bytes from token obtained
tokenb = bytes(get_token['access_token'], "UTF-8")
exptoken = b'';
for i in tokenb:
  exptoken += bytes({i});
  exptoken += bytes(1);
tokenstruct = struct.pack("=i", len(exptoken)) + exptoken;

conn = pyodbc.connect(connString, attrs_before = { SQL_COPT_SS_ACCESS_TOKEN:tokenstruct})

I'm getting the following error:

InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user ''. (18456) (SQLDriverConnect)")

Please help me...

Regards,
Kaarthick

**Comment by v-makouz** [comment]
I looks like the message is from the server, saying that credentials are incorrect, so it seems like there is something wrong with the access token

**Comment by kaarthickprabhu** [comment]
Thank you, will check it

**Comment by kaarthickprabhu** [comment]
Hi, I'm using the following code

authority_url = 'https://login.microsoftonline.com/<<Tenant>>'
context = adal.AuthenticationContext( authority_url, api_version=None )

token = context.acquire_token_with_client_credentials( 
    "https://database.windows.net/",
    'clientid',
    'clientsecret')

SQL_COPT_SS_ACCESS_TOKEN = 1256 
connString = "Driver={ODBC Driver 17 for SQL Server};SERVER=tcp:<<Servername>>.database.windows.net,1433;DATABASE=<<DBName>>"
print(token)
#get bytes from token obtained
tokenb = bytes(token["accessToken"], "UTF-8")
exptoken = b"";
for i in tokenb:
    exptoken += bytes({i});
    exptoken += bytes(1);
tokenstruct = struct.pack("=i", len(exptoken)) + exptoken;

conn = pyodbc.connect(connString, attrs_before = { SQL_COPT_SS_ACCESS_TOKEN:tokenstruct});

1. I created the application and added to the SQL db which has AAD admin

But still I'm getting the same error..

**Comment by v-chojas** [comment]
Please enclose code in triple-backticks in order to preserve the spaces, this is especially important for Python code!

Is your Access Token in the correct format? I believe they currently look like a base64 string that starts with `eyJ0e`, and has to be expanded with 0-padding between each byte, but if you are already getting the latter format then a double-expansion could be causing the problem.

Also, what is your OS and other environment information (including unixODBC version if you are using Linux/Mac)?

**Comment by kaarthickprabhu** [comment]
my current token starts with "eyJ0e", so should I change the padding code?

**Comment by v-chojas** [comment]
That looks like the correct form of access token.
Depending on the Python version, there are some differences in how to use an access token.
Please see the details here: https://github.com/mkleehammer/pyodbc/issues/228

**Comment by kaarthickprabhu** [comment]
Actually I'm using the same code which you sent in ref.. :(

SQL_COPT_SS_ACCESS_TOKEN = 1256 
connString = ''Driver={ODBC Driver 17 for SQL Server};SERVER=tcp:<<ServerName>>.database.windows.net,1433;DATABASE=<<DBName>>''

#get bytes from token obtained
tokenb = bytes(token["accessToken"], "UTF-8")
exptoken = b'';
for i in tokenb:
    exptoken += bytes({i});
    exptoken += bytes(1);
tokenstruct = struct.pack("=i", len(exptoken)) + exptoken;

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
