### ISSUE TITLE
Stack Buffer Overrun error with QODBC

### ISSUE THREAD

**Issue by jamiebull1** [mkleehammer/pyodbc#567]
### Environment

- Python: 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
- pyodbc: 4.0.26
- OS: Windows Server 2019
- DB: QuickBooks: Premier Plus Contractor Edition 2018
- driver: QODBC QRemote 64-bit

### Issue

When I try to fetch results from QODBC tables, the python process terminates with a `(0xC0000409) STATUS_STACK_BUFFER_OVERRUN` error. An MCVE below:

```
import pyodbc
con = pyodbc.connect(f"DSN=QuickBooks Data 64-bit QRemote;OLE DB Services=-2;")
cur = con.execute("SELECT TOP 10 * FROM Invoice")
cur.fetchone()

Process finished with exit code -1073740791 (0xC0000409)
```

I've tested in the QODBC QB Demo.vb app and the "SELECT TOP 10 * FROM Invoice" query runs with no error.

This doesn't happen with all tables. I've found the error occurs with "Account", "Invoice" and "InvoiceLine" so far. I've also tried with the "SP_TABLES" stored procedure, and the "AccountTaxLineInfo" table and not had the error.

**Comment by v-chojas** [comment]
Please provide an ODBC trace, it will help greatly to determine where the problem is.

**Comment by jamiebull1** [comment]
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/3158034/SQL.LOG)

**Comment by v-chojas** [comment]
I see in the trace that the table has 29 columns, but it abruptly cuts off after reading the data for the 2nd column. Could you try selecting the columns one at a time, and see which one(s) cause the crash? The ODBC driver you're using only supports a very early version (2.5) of the ODBC standard, but I don't see anything that would absolutely prevent pyODBC from working with it (that error you see is just pyODBC trying to determine which datatypes are supported.)

**Comment by jamiebull1** [comment]
I've had this working before so I know that pyODBC at least used to work for this. There was an update for QuickBooks recently which may have meant a change to the datatypes.

Table spec with details of the columns is [here](https://doc.qodbc.com/qodbc/usa/TableDetails.php?tableName=Account).

Fails on:
- TimeCreated (type 11 TIMESTAMP)
- TimeModified (type 11 TIMESTAMP)
- OpenBalanceDate (type 9 DATE)

Succeeds on everything else. Maybe worth noticing that these three are the only date/time-related columns, although they are two different datatypes.

**Comment by gordthompson** [comment]
It looks like the 

```
pydevconsole    2fa8-2380	EXIT  SQLGetTypeInfo  with return code -1 (SQL_ERROR)
        HSTMT               0x00000242A0BED2C0
        SWORD                       -9 <SQL_WVARCHAR>

        DIAG [HY004] [Microsoft][ODBC Driver Manager] SQL data type out of range (0) 
```

error is unrelated. As @v-chojas said, that is happening during the initial connection setup as pyodbc is determining what certain data types "look like" when using a particular driver.

The rest of the latest SQL.LOG looks normal except that it is truncated, presumably at the point that the Python interpreter tanks. pyodbc had just successfully completed a `SQLGetData` so it looks like the sequence of bytes returned by the ODBC driver were in a form that pyodbc did not expect.

Two possibilities for further troubleshooting:

1. Run the same query in QODBC's Demo.vb app and provide the ODBC trace from that run for comparison.

2. Perhaps Wireshark might be useful to see what is in the data payload that the server is returning in response to the `SQLGetData` request.

**Comment by jamiebull1** [comment]
I've just received confirmation that this is due to a bug in QODBC Desktop. Thanks for the help in narrowing down the symptoms, and I'll close the issue.
