### ISSUE TITLE
 '[HY000] Cannot open server  requested by login

### ISSUE THREAD

**Issue by UGuntupalli** [mkleehammer/pyodbc#569]
- Python: 3.6.5 (64-bit) 
- pyodbc: 4.0.23
- OS: Windows 10
- DB: Microsoft SQL Server on Azure 
- driver: Output of pyodbc.drivers() 
['SQL Server',
 'SQL Server Native Client 11.0',
 'ODBC Driver 11 for SQL Server',
 'ODBC Driver 13 for SQL Server',
 'ODBC Driver 17 for SQL Server']

### Issue
"expected behavior" : https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connect-query-python 

"observed behavior": 
Error: ('HY000', '[HY000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open server "<companyname>.com" requested by the login.  The login failed. (40532) (SQLDriverConnect); [HY000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0); [HY000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open server "<companyname>.com" requested by the login.  The login failed. (40532); [HY000] [Microsoft][ODBC Driver 17 for SQL Server]Invalid connection string attribute (0)')

My code with credentials hidden: 

`
import pyodbc

server   = 'xxxx.database.windows.net' 
database = 'xxxx'
username = 'xxxx@xxx.com'
password = 'xxxx'
driver = '{ODBC Driver 17 for SQL Server}'
connection = pyodbc.connect('DRIVER='+driver+';PORT=1433;SERVER='+server+
                            ';DATABASE='+database+';UID='+username+';PWD='+ password
                           )
`

**Comment by v-makouz** [comment]
It sounds like something is going wrong with the connection string. Can you assign it to variable first, and print it out before passing it to `pyodbc.connect()` ?

**Comment by v-makouz** [comment]
Also, `port` is not a valid connection string attribute, it is 1433 by default, but if you need to specify a different one see: https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-2017

**Comment by v-chojas** [comment]
Make sure that the password is escaped if it contains special characters, by enclosing it with `{` and `}` and doubling and `}` that appear inside.

**Comment by v-chojas** [comment]
Make sure the password is escaped if it contains special characters, by enclosing it in `{` and `}` and doubling any `}` that appear inside.

**Comment by UGuntupalli** [comment]
@v-chojas  and @v-makouz , 
 Thanks a lot for your responses and suggestions. 

I updated my password as: 
password = '{xxxxx}'

Removed the port  from connect() call. 

My new code looks like this: 


`import pyodbc

server   = 'xxxxxx.database.windows.net' 
database = 'xxxx’
username = 'xxxxxxxxx@xxxxxxx.com'
password = '{xxxxxxxx}'
driver = '{ODBC Driver 17 for SQL Server}'
conn_str = ('DRIVER='+driver+';SERVER='+server+
        ';DATABASE='+database+';UID='+username+';PWD='+ password
      )
connection = pyodbc.connect(conn_str)


'DRIVER={ODBC Driver 17 for SQL Server};SERVER='xxxxxx.database.windows.net;DATABASE=EDW;UID=xxxxxxxxx@xxxxxxx.com;PWD={xxxxxxxx} '

`
The error still continues.

**Comment by gordthompson** [comment]
The connection string you show has a spurious `'` at `SERVER='xxxxxx`, but that's probably just a typo.

You could also try wrapping the UID in curly brackets as well. I just tried `UID={gord@example.com};` and it worked for me.

**Comment by v-chojas** [comment]
ActiveDirectoryPassword selects authentication using a user in Azure Active Directory, if you are only using a SQL Server username/password then it will not work (and vice-versa)

pyODBC does not care about the contents of the connection string; it just passes it through to the driver.

**Comment by UGuntupalli** [comment]
@v-chojas ,
   Can you please point me to an example or documentation which shows what is the right way using pyodbc to perform ActiveDirectoryPassword authentication ?

**Comment by v-chojas** [comment]
Put UID and PWD in connection string as usual. Add `Authentication=ActiveDirectoryPassword`.
Note that if you are not using Azure Active Directory then it won't work. The document you have linked to has all the details.

**Comment by v-makouz** [comment]
It seems like the Azure server gives back a slightly nu-intuitive login failure message, it says "can't open server" followed by whatever is after the "@" in the UID, but actual problem is authentication failure

**Comment by h369kr** [comment]
The important parameter is where the “username and password” were set, we are replacing it with “Trusted_Connection=yes” so the user account logged into Windows is used instead.

import pyodbc

conn_str = ("Driver={SQL Server};"
                           "Server=<server-name>;"
                            "Database=<db-name>;"
                            "Trusted_Connection=yes")
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()
