### ISSUE TITLE
KeyError: 'SQL Server'

### ISSUE THREAD

**Issue by YizeD** [mkleehammer/pyodbc#574]
### Environment

- Python: 3.5.2
- pyodbc: 4.0.16
- OS: Windows 10
- DB: Microsoft SQL Server 2017
- driver: ODBC Driver 17 for SQL Server

### Issue

I get the error:
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    create_database()
  File "test.py", line 17, in create_database
    cnxn = pyodbc.connect(connection_string.format("master"), autocommit=True)
KeyError: 'SQL Server'

when attempting to connect to my SQL server with the following code

```
connection_string = "Driver = {SQL Server}; Server = server_name; Database={0}; UID=uid; PWD=pwd"

cnxn = pyodbc.connect(connection_string.format("master"), autocommit=True)
```

Can't seem to find a similar issue. I've also tried to run using DSN with:

```
connection_string = "DSN=dsn;UID=uid;PWD=pwd"
cnxn = pyodbc.connect(connection_string.format("master"), autocommit=True)
```

but then this error comes up:
pyodbc.Error: ('IM014', '[IM014] [Microsoft][ODBC Driver Manager] The specified DSN contains an architecture mismatch between the Driver and Application (0) (SQLDriverConnect)')

**Comment by v-chojas** [comment]
I believe the `SQL Server` driver is the very old one from SQL Server 6.x, if you want msodbcsql17 then you need to specify `Driver=ODBC Driver 17 for SQL Server` in your connection string.

The "architecture mismatch" error occurs when the application and driver are different bitness --- you need to use a 32-bit driver with a 32-bit Python, and the 64-bit driver with a 64-bit Python.

**Comment by YizeD** [comment]
Thank you! The second problem is solved. However, the first problem still persists even after I make the suggested change. Now, when I run

```
connection_string = "Driver = {ODBC Driver 17 for SQL Server}; Server = servername; Database={0}; UID=uid; PWD=pwd"

cnxn = pyodbc.connect(connection_string.format("master"), autocommit=True)
```
it shows 
KeyError: 'ODBC Driver 17 for SQL Server'

Since I can connect now, it's fine. But I'm still curious as to why the error happens.

I've also tried without the {}, but then the error returned becomes:
cnxn = pyodbc.connect(connection_string.format("master"), autocommit=True)
pyodbc.Error: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')

**Comment by v-chojas** [comment]
The error occurs because you are incorrectly creating the connection string. Try to write all of it directly:

```pyodbc.connect("Driver=ODBC Driver 17 for SQL Server;Server=<server>;Database=<db>;UID=<username>;PWD=<password>");```

Remember to escape any special characters in passwords etc. by quoting them with `{` and `}`, and doubling any `}` that occurs inside a quoted value. If you are literally specifying them in a Python string, then Python's own character escaping rules need to be followed too. The detailed syntax of an ODBC connection string is described in

https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-odbcstr/13b4e848-b36c-4b11-acce-d6bf199d5391

and for Python string escaping, refer to

https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

**Comment by mkleehammer** [comment]
Exactly.  If you really want to use `format`, escaping the braces as v-chojas suggestions would look like this:

```python
connection_string = "Driver = {{ODBC Driver 17 for SQL Server}}; Server = servername; Database={0}; UID=uid; PWD=pwd"

cnxn = pyodbc.connect(connection_string.format("master"), autocommit=True)
```

Notice the double braces around the driver name, but only a single around the '0'.
