### ISSUE TITLE
sql.h not found when trying to build setup.py

### ISSUE THREAD

**Issue by Oratronic** [mkleehammer/pyodbc#575]
OS: macOS Sierra 10.12.6
PyCharm Community 2019.1.3

I tried to install the module in pycharm and got the error "Module not found", so I tried to install it manually via Terminal and as I ran "python setup.py build" I recieved the error, that sql.h that is referenced in src/pyodbc.h was not found.

**Comment by v-makouz** [comment]
Lack of sql.h often indicates that the unixODBC is not installed, try `brew install unixodbc`

**Comment by mkleehammer** [comment]
Thanks @v-makouz.  Closing now since we haven't heard back (and that is usually the fix).
