### ISSUE TITLE
Question - maximum limit of the parameters that can be bound to a query

### ISSUE THREAD

**Issue by kabirbaidhya** [mkleehammer/pyodbc#576]
I want to know, let's say for MS SQL Server 2017, is there a limit of how many parameters you can bind into a prepared query that you execute with pyodbc?
 
Also, is this something specific to every vendor? 

I tried to search through the wiki and also through MS SQL docs but couldn't get any idea in this. 

In a query like this - what would be the max number of params I can bind:
```sql
cursor.execute("insert into products(id, name) values (?, ?)", 'pyodbc', 'awesome library')
```

PS - have already gone through these:
- https://github.com/mkleehammer/pyodbc/wiki/Binding-Parameters
- https://github.com/mkleehammer/pyodbc/wiki/Getting-started

**Comment by v-chojas** [comment]
You are correct, this is specific to the DB and driver. pyODBC itself has no limitation beyond available memory.

For SQL Server, see https://docs.microsoft.com/en-us/sql/sql-server/maximum-capacity-specifications-for-sql-server

A statement with parameters is executed using a system stored procedure (e.g. sp_executesql), and the maximum number of parameters to a stored procedure is 2100.

**Comment by kabirbaidhya** [comment]
@v-chojas Makes sense. Thanks so much!

> A statement with parameters is executed using a system stored procedure (e.g. sp_executesql), and the maximum number of parameters to a stored procedure is 2100.

That means the hard limit for bound params would be: (2100 - [other `sp_executesql` params]). Right?

Also, what is the case for other driver like for Postgres? How are bound params sent?

**Comment by v-chojas** [comment]
Yes. The best thing to do is to try it --- and I'll add that if you're thinking of creating a stored procedure with that many parameters, there is probably a much better way to accomplish something.

I don't know what other databases' limits are. It is likely to be in their documentation.

**Comment by kabirbaidhya** [comment]
Sure. Thanks. 

Closing the issue - my case was specific to understanding how pyodbc handles bound params for mssql. 

If any other folks want to add anything on how this is being done for other drivers eg: postgres, please do.
