### ISSUE TITLE
Memory Leak encountered with fast_executemany on insertion into a wide table

### ISSUE THREAD

**Issue by yamen321** [mkleehammer/pyodbc#577]
### Environment

- Python: 3.7 (64-bit)
- pyodbc: 4.0.26
- OS: Windows 10 (64-bit)
- DB: SQL Server 2014
- driver: ODBC Driver 17 for SQL Server
- Total RAM: 32GB

### Issue

Hello,

I've created this build that extracts large amounts of data from an API and inserts it into my database. I keep running into a pyodbc MemoryError when inserting the data into my database. I've done some tests to find out why inserting into my database causes such a surge in memory usage, and it turns out that this issue is the result of running cursor.executemany() with the fast_executemany set to True.

This occurs when I attempt to insert 300,000 rows of data at a time into a table that is 155 columns wide. The memory spike is about 10GB for the duration of the executemany and does get recycled before the next batch of 300,000 rows. I have tested out reducing the number of rows inserted at once, and it seems to reduce the memory usage almost proportionally. I have no issues whenever I set fast_executemany to False; however, that greatly affects my performance so I'd prefer not to.

I did look into issue #299, although I assume my version of pyodbc should already have that fix right? Also, I understand that executemany will allocate the parameter array, but is the parameter array supposed to use up this much memory for what is around 300 MB of raw data being inserted?

Since reducing the number of rows being inserted at once will reduce the spike in memory at any one time, I will be doing so to workaround the issue, but I'd appreciate any insight since I'd prefer not to reduce my batch size.

I've attached a portion of the trace containing the data insertion into my db. Please let me know if I can clarify anything, or provide any extra details! I really appreciate the help!

[ExecuteTrace.txt](https://github.com/mkleehammer/pyodbc/files/3316201/ExecuteTrace.txt)

**Comment by v-chojas** [comment]
The trace that you have provided doesn't show any insertion, only a lot of data fetching. However, at the end it prepares a query that has 192 parameters, but since the trace stops there, I can't see what the type of each parameter is and thus how much memory it would need for each cell.

Keep in mind that fast_executemany has to allocate an array for each row, and each array will be the maximum size that the parameter row could be; your numbers suggest ~33K per row, which is not surprising given the 192 parameters --- especially if you have many string parameters. (E.g. if your row has only 4 varchar(8000) columns, that would already take nearly 32K per row.)

**Comment by yamen321** [comment]
Sorry about the Trace cutting off! There is some sensitive information in there so I'm trying not to upload the entire thing. I've attached the continuation of the trace that goes through the 192 parameters, which I hope could give you a better insight.

Also here is my table definition:

> CREATE TABLE [Staging].[TdDailyPerformance]
> 
> (
> 	[SYS_OPERATION] CHAR(8) NULL,
> 	[HashCode] BINARY(65) NULL,
> 	[Ad Environment] NVARCHAR(1024) NULL,
> 	[Ad Format] NVARCHAR(10) NULL,
> 	[Ad Group] NVARCHAR(1024) NULL,
> 	[Ad Group ID] NVARCHAR(32) NULL,
> 	[Ad Server Creative Placement ID] NVARCHAR(1024) NULL,
> 	[Ad Server Name] NVARCHAR(1024) NULL,
> 	[Advertiser] NVARCHAR(1024) NULL,
> 	[Advertiser Currency Code] NVARCHAR(1024) NULL,
> 	[Advertiser ID] NVARCHAR(32) NULL,
> 	[App] NVARCHAR(1024) NULL,
> 	[Browser] NVARCHAR(30) NULL,
> 	[Campaign] NVARCHAR(1024) NULL,
> 	[Campaign ID] NVARCHAR(32) NULL,
> 	[Carrier ID] INT NULL,
> 	[Carrier Name] NVARCHAR(1024) NULL,
> 	[City] NVARCHAR(50) NULL,
> 	[Country] NVARCHAR(50) NULL,
> 	[Creative] NVARCHAR(1024) NULL,
> 	[Creative Duration In Seconds] INT NULL,
> 	[Creative ID] NVARCHAR(32) NULL,
> 	[Date] NVARCHAR(1024) NULL,
> 	[Device Make] NVARCHAR(32) NULL,
> 	[Device Type] NVARCHAR(15) NULL,
> 	[Fold] NVARCHAR(128) NULL,
> 	[Language] NVARCHAR(1024) NULL,
> 	[Market Type] NVARCHAR(32) NULL,
> 	[Media Type] NVARCHAR(32) NULL,
> 	[Metro] NVARCHAR(128) NULL,
> 	[Metro Code] INT NULL,
> 	[Operating System] NVARCHAR(32) NULL,
> 	[Operating System Family] NVARCHAR(1024) NULL,
> 	[Partner ID] NVARCHAR(32) NULL,
> 	[Partner Name] NVARCHAR(32) NULL,
> 	[Region] NVARCHAR(128) NULL,
> 	[Site] NVARCHAR(1024) NULL,
> 	[Site List Name] NVARCHAR(1024) NULL,
> 	[Supply Vendor] NVARCHAR(25) NULL,
> 	[Timezone] NVARCHAR(1024) NULL,
> 	[Video Playback Type] NVARCHAR(32) NULL,
> 	[Whitelist Site] NVARCHAR(32) NULL,
> 	[Partner Currency Code] NVARCHAR(32) NULL,
> 	[Additional Fee Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Additional Fee Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Additional Fee Cost (USD)] DECIMAL(37,15) NULL,
> 	[Advertiser Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Advertiser Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Advertiser Cost (USD)] DECIMAL(37,15) NULL,
> 	[All Last Click + View Conversions] INT NULL,
> 	[Clicks] INT NULL,
> 	[Companion Clicks] INT NULL,
> 	[Companion Impressions] INT NULL,
> 	[Data Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Data Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Data Cost (USD)] DECIMAL(37,15) NULL,
> 	[Fee Features Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Fee Features Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Fee Features Cost (USD)] DECIMAL(37,15) NULL,
> 	[IAS Display Fully In View 0 Seconds] INT NULL,
> 	[IAS Display Fully In View 1 Second] INT NULL,
> 	[IAS Display Fully In View 15 Seconds] INT NULL,
> 	[IAS Display Fully In View 5 Seconds] INT NULL,
> 	[IAS Display In View 1 Second] INT NULL,
> 	[IAS Display In View 15 Seconds] INT NULL,
> 	[IAS Display In View 5 Seconds] INT NULL,
> 	[IAS High Risk Impression Count] INT NULL,
> 	[IAS Low Risk Impression Count] INT NULL,
> 	[IAS Moderate Risk Impression Count] INT NULL,
> 	[IAS Non GVIT Impression Count] INT NULL,
> 	[IAS Suspicious Activity] INT NULL,
> 	[IAS Total Impression Count] INT NULL,
> 	[IAS Very High Risk Impression Count] INT NULL,
> 	[IAS Video 25% Complete] INT NULL,
> 	[IAS Video 50% Complete] INT NULL,
> 	[IAS Video 75% Complete] INT NULL,
> 	[IAS Video Completed Views] INT NULL,
> 	[IAS Video Muted] INT NULL,
> 	[IAS Video Viewable 25% Complete] INT NULL,
> 	[IAS Video Viewable 50% Complete] INT NULL,
> 	[IAS Video Viewable 75% Complete] INT NULL,
> 	[IAS Video Viewable Completed Views] INT NULL,
> 	[Impressions] INT NULL,
> 	[In-banner Player Impressions] INT NULL,
> 	[Large Player Impressions] INT NULL,
> 	[Media Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Media Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Media Cost (USD)] DECIMAL(37,15) NULL,
> 	[Medium Player Impressions] INT NULL,
> 	[MOAT Display In View Time 10 Seconds] INT NULL,
> 	[MOAT Display In View Time 15 Seconds] INT NULL,
> 	[MOAT Display In View Time 30 Seconds] INT NULL,
> 	[MOAT Display In View Time 5 Seconds] INT NULL,
> 	[MOAT Display On Screen] INT NULL,
> 	[MOAT Display Universal Interaction] INT NULL,
> 	[MOAT Display Universal Interaction Time 10 Seconds] INT NULL,
> 	[MOAT Display Universal Interaction Time 15 Seconds] INT NULL,
> 	[MOAT Display Universal Interaction Time 30 Seconds] INT NULL,
> 	[MOAT Display Universal Interaction Time 5 Seconds] INT NULL,
> 	[MOAT Video Audible and Visible on Complete] INT NULL,
> 	[MOAT Video In View Time 3 Seconds] INT NULL,
> 	[MOAT Video In View Time 5 Seconds] INT NULL,
> 	[MOAT Video Visible on Complete] INT NULL,
> 	[Non-USD Currency Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Non-USD Currency Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Non-USD Currency Cost (USD)] DECIMAL(37,15) NULL,
> 	[Partner Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Partner Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Partner Cost (USD)] DECIMAL(37,15) NULL,
> 	[Player 25% Complete] INT NULL,
> 	[Player 50% Complete] INT NULL,
> 	[Player 75% Complete] INT NULL,
> 	[Player Audible Event] INT NULL,
> 	[Player Close] INT NULL,
> 	[Player Collapse] INT NULL,
> 	[Player Completed Views] INT NULL,
> 	[Player Engaged Views] INT NULL,
> 	[Player Errors] INT NULL,
> 	[Player Expansion] INT NULL,
> 	[Player Full Screen] INT NULL,
> 	[Player Invitation Accept] INT NULL,
> 	[Player Mute] INT NULL,
> 	[Player Pause] INT NULL,
> 	[Player Playing Event] INT NULL,
> 	[Player Resume] INT NULL,
> 	[Player Rewind] INT NULL,
> 	[Player Skip] INT NULL,
> 	[Player Starts] INT NULL,
> 	[Player Total Playing Seconds] INT NULL,
> 	[Player Unmute] INT NULL,
> 	[Player Views] INT NULL,
> 	[Predictive Clearing Savings (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Predictive Clearing Savings (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Predictive Clearing Savings (USD)] DECIMAL(37,15) NULL,
> 	[Profit (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Profit (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Profit (USD)] DECIMAL(37,15) NULL,
> 	[Sampled Tracked Impressions] INT NULL,
> 	[Sampled Viewed Impressions] INT NULL,
> 	[Small Player Impressions] INT NULL,
> 	[Total Audible Seconds] INT NULL,
> 	[Total Bid Amount (Adv Currency)] DECIMAL(37,15) NULL,
> 	[Total Bid Amount (Partner Currency)] DECIMAL(37,15) NULL,
> 	[Total Bid Amount (USD)] DECIMAL(37,15) NULL,
> 	[Total Custom CPA Conversions] INT NULL,
> 	[Total Seconds In View] INT NULL,
> 	[TTD Cost (Adv Currency)] DECIMAL(37,15) NULL,
> 	[TTD Cost (Partner Currency)] DECIMAL(37,15) NULL,
> 	[TTD Cost (USD)] DECIMAL(37,15) NULL,
> 	[TTD Margin (Adv Currency)] DECIMAL(37,15) NULL,
> 	[TTD Margin (Partner Currency)] DECIMAL(37,15) NULL,
> 	[TTD Margin (USD)] DECIMAL(37,15) NULL,
> 	[Video In View Event] INT NULL,
> 	[White Ops SIVT Bids Avoided] INT NULL,
> 	[CreatedOn] DATETIME2 NULL CONSTRAINT df_Staging_TdDailyPerformance_CreatedOn DEFAULT SYSUTCDATETIME(),
> 	[ModifiedOn] DATETIME2 NULL CONSTRAINT df_Staging_TdDailyPerformance_ModifiedOn DEFAULT SYSUTCDATETIME(),
> 	[Retired] BIT NULL CONSTRAINT df_Staging_TdDailyPerformance_Retired DEFAULT 0
> )

Is there a reason that SQL is counting 192 parameters when I'm only inserting into 154 columns?
Furthermore, I went ahead and added up the max allocation for each column above and I ended up with ~20K per row. 20K per 300,000 rows being inserted at a time should amount to 6GB; however, it seems like my memory spikes up by 8-9 GB during the executemany. 

Regardless, I see now that there's no avoiding this high memory usage for my wide column, but now I'm really curious what those extra parameters showing up in the trace are about.

I really appreciate the clarification @v-chojas! 
[excManyPt2.txt](https://github.com/mkleehammer/pyodbc/files/3322660/excManyPt2.txt)

**Comment by v-chojas** [comment]
> Furthermore, I went ahead and added up the max allocation for each column above and I ended up with ~20K per row

I did a rough count and got 35,857 bytes (~35KB); don't forget that NVARCHARs are UCS-2/UTF-16 so each of those NVARCHAR(1024) are 2KB. You have 16 of those, that's 32KB already. The rest of the columns contribute the remainder to 35KB. 35KB * 300,000 is just a bit over the 10GB that you mentioned earlier.

(I suspect some of those columns could be narrower, e.g. I don't think "Date" deserves a 2K NVARCHAR, nor does "Timezone" or "Language"...)

**Comment by yamen321** [comment]
I definitely forgot about counting my NVARCHARs properly...

Regarding the columns you mentioned, there is definitely some room for optimization. We're still in the development process so we gave most columns a safeguard as we weren't too sure the data we are pulling is what we think it is.

Thank you so much for all the help! I have a much better understanding now, and I'll be sure to apply it to my app
