### ISSUE TITLE
Bind Parameter in Subquery

### ISSUE THREAD

**Issue by mjack24** [mkleehammer/pyodbc#578]
Is it possible to pass a parameter to a subquery in PYODBC?

**Comment by v-chojas** [comment]
Yes, if it is supported by the ODBC driver you are using.

**Comment by mjack24** [comment]
I can't paste the entire code because it is too long.  I would like the ? to be the variable; however, I get the following error:

': ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'r'. (4145) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. (8180)")

Partial SQL Statement:

`WHERE
     (((DM_DAILY.daily_id In( (SELECT DD.daily_id  FROM DM_EVENT DE,  DM_DAILY 
     DD  WHERE DE.well_id = CD_WELL.well_id AND DE.event_id = DM_EVENT.event_id 
     AND  DE.well_id = DD.well_id AND DE.event_id = DD.event_id AND 
     DE.event_code = 'DRL' AND  DATEDIFF(DAY,  0,  DD.date_report) = 
     DATEDIFF(DAY,  **?**, 1,  GETDATE())))) AND (DM_EVENT.event_code = 'DRL') AND 
     (DM_RIG_OPERATION.date_rig_pickup = (SELECT Max(DRO.date_rig_pickup)  FROM 
     DM_RIG_OPERATION DRO  WHERE DRO.rig_id = CD_RIG.rig_id AND  DATEDIFF(DAY,  
     0,  DRO.date_rig_pickup) <= DATEDIFF(DAY,  0,  DM_DAILY.date_report))))) 
     AND ((DM_EVENT.well_id = DM_DAILY.well_id AND DM_EVENT.event_id = 
     DM_DAILY.event_id) AND (CD_WELL.well_id = DM_EVENT.well_id) AND 
     (CD_SITE.site_id = CD_WELL.site_id) AND 
     (DM_RIG_OPERATION_EVENT_LINK.well_id=DM_EVENT.well_id AND 
     DM_RIG_OPERATION_EVENT_LINK.event_id=DM_EVENT.event_id) AND 
     (DM_RIG_OPERATION.rig_id = DM_RIG_OPERATION_EVENT_LINK.rig_id AND 
     DM_RIG_OPERATION.rig_operation_id = 
     DM_RIG_OPERATION_EVENT_LINK.rig_operation_id) AND (CD_RIG.rig_id = 
     DM_RIG_OPERATION.rig_id))`

`df = pd.read_sql(query, cnxn, params = [days])`

**Comment by v-chojas** [comment]
1. The error message mentions nothing about a parameter, and in fact it is about an expression that is not boolean found in a place where the server is expecting a boolean. The only hint is "near 'r'", so check the query again carefully.

2. The "SQL Server" driver is very old and may not support all features of newer servers; the latest ODBC driver for SQL Server is `ODBC Driver 17 for SQL Server` which can be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=56567

**Comment by mjack24** [comment]
Sorry I had left out part of the error.

`ProgrammingError                          Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in execute(self, *args, **kwargs)
   1377             else:
-> 1378                 cur.execute(*args)
   1379             return cur

ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'r'. (4145) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared. (8180)")

During handling of the above exception, another exception occurred:

DatabaseError                             Traceback (most recent call last)
<ipython-input-46-3657c5fb7fa0> in <module>
   3480 """
   3481 # Read SQL Query to Pandas and Sort
-> 3482 df = pd.read_sql(query, cnxn, params = [days])
   3483 df.columns = ['RI5', 'RgNm5', 'RgTyp5', 'Cnty', 'SI', 'WlUpdtDt_Max1', 'WI1', 'CsgDtMax_WI1', 'AI1_CsgDtMax', 'WlUpdtDt_Max2', 'WI2', 'CsgDtMax_WI2', 'AI2_CsgDtMax', 'WlUpdtDt_Max3', 'WI3', 'CsgDtMax_WI3', 'AI3_CsgDtMax', 'WlNmCom1', 'CsgStrng1', 'WlNmCom2', 'CsgStrng2', 'WlNmCom3', 'CsgStrng3', 'Pad', 'Lat', 'Long', 'TGI_CW', 'Bsn', 'WlNmCom', 'WlNmCom0', 'WI', 'MvSt4', 'ROI4', 'StrtDrl4', 'RR4', 'StrtDrlInt1_Min1', 'StrtDrlInt1_Min2', 'StrtDrlRR4', 'MvSt3', 'ROI3', 'StrtDrl3', 'RR3', 'StrtDrlRR3', 'MvSt2', 'ROI2', 'StrtDrl2', 'RR2', 'StrtDrlRR2', 'MvSt1', 'ROI1', 'StrtDrl1', 'RR1', 'StrtDrlRR1', 'TmSmEnd_Max', 'StrtDrlSurf_Min', 'CsgRptDt_Max0', 'AI0_CsgRptDt_Max0', 'LstCsgSetSz', 'DtmElv_Dflt', 'LstCsgSetDpth', 'WBI_Pilot', 'Wlbr_Cnt', 'DlyDtPrev', 'DIPrev', 'MDOthrWB_Max1', 'FtgDrldLtrl', 'MDPrev', 'NPTHrsDlyDt', 'NPTHrsEvnts_All', 'Cst_Totl', 'CstAFE', 'CsgStrng0', 'Cst_DlyDt', 'DI', 'DlyDt', 'DrctnlCo', 'MDCrvLnd', 'MDCurr', 'Geo', 'MdPlnd', 'FtgDrld', 'DM_DAILY.reviewer', 'CurrOps', 'WSM', 'Eng', 'FldSprntndt', 'DrlgSprntndt', 'NxtWl', 'WBI_DD', 'EvntCd5', 'EI', 'EvntObj5', 'DFS_Calc', 'MvSt5r', 'MvSt5we', 'RRPUB_Curr', 'PUB5', 'StrtDrl5', 'StrtDrlRR5', 'StrtDrlRRR_Totl', 'RI_DROEL', 'ROI_DROEL', 'NWSM']
   3484 sorted_columns = ['Bsn', 'RgNm5', 'RgTyp5', 'DrctnlCo', 'WlNmCom', 'Cnty', 'CurrOps', 'LstCsgSetSz', 'LstCsgSetDpth', 'FtgDrld', 'MDCurr', 'MdPlnd', 'MDCrvLnd', 'FtgDrldLtrl', 'RRPUB_Curr', 'StrtDrlRR5', 'StrtDrlRRR_Totl', 'NPTHrsDlyDt', 'NPTHrsEvnts_All', 'Cst_DlyDt', 'Cst_Totl', 'CstAFE', 'Eng', 'Geo', 'DrlgSprntndt', 'FldSprntndt', 'WSM', 'Pad', 'WlNmCom0', 'CsgStrng0', 'WlNmCom1', 'CsgStrng1', 'WlNmCom2', 'CsgStrng2', 'WlNmCom3', 'CsgStrng3', 'Lat', 'Long', 'NxtWl', 'DlyDt', 'DFS_Calc', 'SI', 'WI', 'EI', 'DI', 'WBI_DD', 'EvntCd5', 'EvntObj5', 'TGI_CW', 'WBI_Pilot', 'RI_DROEL', 'ROI_DROEL', 'MvSt5r', 'MvSt5we', 'PUB5', 'StrtDrl5', 'RI5', 'TmSmEnd_Max', 'StrtDrlSurf_Min', 'StrtDrlInt1_Min1', 'StrtDrlInt1_Min2', 'DtmElv_Dflt', 'MDOthrWB_Max1', 'DlyDtPrev', 'DIPrev', 'MDPrev', 'Wlbr_Cnt', 'CsgRptDt_Max0', 'AI0_CsgRptDt_Max0', 'WlUpdtDt_Max1', 'WI1', 'CsgDtMax_WI1', 'AI1_CsgDtMax', 'WlUpdtDt_Max2', 'WI2', 'CsgDtMax_WI2', 'AI2_CsgDtMax', 'WlUpdtDt_Max3', 'WI3', 'CsgDtMax_WI3', 'AI3_CsgDtMax', 'MvSt4', 'ROI4', 'StrtDrl4', 'RR4', 'StrtDrlRR4', 'MvSt3', 'ROI3', 'StrtDrl3', 'RR3', 'StrtDrlRR3', 'MvSt2', 'ROI2', 'StrtDrl2', 'RR2', 'StrtDrlRR2', 'MvSt1', 'ROI1', 'StrtDrl1', 'RR1', 'StrtDrlRR1', 'DM_DAILY.reviewer', 'NWSM']

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in read_sql(sql, con, index_col, coerce_float, params, parse_dates, columns, chunksize)
    379             sql, index_col=index_col, params=params,
    380             coerce_float=coerce_float, parse_dates=parse_dates,
--> 381             chunksize=chunksize)
    382 
    383     try:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
   1411 
   1412         args = _convert_params(sql, params)
-> 1413         cursor = self.execute(*args)
   1414         columns = [col_desc[0] for col_desc in cursor.description]
   1415 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in execute(self, *args, **kwargs)
   1388             ex = DatabaseError(
   1389                 "Execution failed on sql '%s': %s" % (args[0], exc))
-> 1390             raise_with_traceback(ex)
   1391 
   1392     @staticmethod

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\compat\__init__.py in raise_with_traceback(exc, traceback)
    402         if traceback == Ellipsis:
    403             _, _, traceback = sys.exc_info()
--> 404         raise exc.with_traceback(traceback)
    405 else:
    406     # this version of raise is a syntax error in Python 3

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\sql.py in execute(self, *args, **kwargs)
   1376                 cur.execute(*args, **kwargs)
   1377             else:
-> 1378                 cur.execute(*args)
   1379             return cur
   1380         except Exception as exc:

DatabaseError: Execution failed on sql`

**Comment by mkleehammer** [comment]
The second part is actually not relevant.  As v-chojas pointed out, there is a problem with the SQL itself.  I use parameters for subqueries all the time, so that part is safe.

I'm going to close this now because I think that will answer your question.

And I would also recommend upgrading to the latest, or at least a later, driver.  Just in case.
