### ISSUE TITLE
Insert result set resulting in "pyodbc.ProgrammingError: ('String data, right truncation: length 8 buffer 4', 'HY000')" error.

### ISSUE THREAD

**Issue by dvarna** [mkleehammer/pyodbc#579]
I am using pyodbc 4.0.26 version. Inserting result-set (containing a decimal result) with "fastexecutemany" set to TRUE results in "pyodbc.ProgrammingError: ('String data, right truncation: length 8 buffer 4', 'HY000')" error.

**Comment by gordthompson** [comment]
Please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and/or an [ODBC trace](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log), along with the name and version of the ODBC driver you are using.

**Comment by dvarna** [comment]
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/3347173/SQL.LOG)
Hi, I have attached the ODBC trace.
Below are the versions of Software I am using

Python Version: 3.7
pyodbc version: 4.0.26
DB: Teradata
Driver: Teradata 15.10.01.03
OS: Win10

**Comment by gordthompson** [comment]
The previous version of the issue title indicates that you are using "fastexecutemany". Does the error go away if you use `fast_executemany=False` (the default)? If so, then the Teradata ODBC driver may simply not support "parameter arrays", the internal ODBC feature that allows `fast_executemany=True` to work.

**Comment by dvarna** [comment]
Yes. It works when fast_executemany= False.  I have used fast_executemany = True on the same Teradata driver for other tables. It worked. I am having issue for this one table. could it be an issue in the data I am inserting? the data I am inserting is extracted from a VSAM file (Mainframe).

**Comment by gordthompson** [comment]
The error

> pyodbc.ProgrammingError: ('String data, right truncation: length 8 buffer 4', 'HY000')

clearly indicates that a string parameter value is overflowing the space allocated to it. Are you passing the decimal parameter values as strings? If so, can you try passing those parameter values as `Decimal` instead of `str`, e.g., `Decimal('3.14')` instead of `'3.14'`?

**Comment by dvarna** [comment]
Yes. I am passing decimal parameter values as string. I passed those values as decimal. It worked.  Thanks so much for your inputs.

**Comment by gordthompson** [comment]
You're welcome. Glad to hear that you got it working. You can close this issue now.
