### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 4: invalid start byte

### ISSUE THREAD

**Issue by ravi9884** [mkleehammer/pyodbc#581]
### Environment
- Python: 3.6 64 bit
- pyodbc: 4.0.26
- OS: "Debian GNU/Linux"
- DB: Hive with Knox
- driver: clouderahiveodbc_2.6.4.1004-2_amd64.deb

### Issue
I'm able to connect to the server using isql. But not able to connect through pyodbc. I looked at the other issues, they deal with running sql statements. But I get error even when connecting.

```

RUN isql hive_knox -v
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
```

But when I try to connect from pyodbc, I get error
```
import pyodbc
pyodbc.pooling = False
cnxn = pyodbc.connect(DSN='hive_knox')
pd.read_sql(sql="show tables",con=cnxn)
```
Error
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-9-57255d5c3b22> in <module>
      1 import pyodbc
      2 pyodbc.pooling = False
----> 3 cnxn = pyodbc.connect(DSN='hive_knox')
      4 pd.read_sql(sql="show tables",con=cnxn)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf9 in position 4: invalid start byte
```

**Comment by ravi9884** [comment]
Issue resolved after adding 
`DriverManagerEncoding=UTF-16`

**Comment by paulsuk1982** [comment]
we are getting same error when connecting to IBM DB2 database, and tried the mentioned solution does not work in our env, while creating connection object getting this issue.

Python: 3.6 64 bit
pyodbc: 4.0.27
OS: "RHEL 7.7/Linux"
DB:  as400 i series DB2 database 
driver: db2 for i Access Client Solutions

Could you please re-open this issue and have look into the solution for DB2 connection. Or I need to open a new issue.

**Comment by v-chojas** [comment]
Please open a new issue if the existing one is already closed.

**Comment by paulsuk1982** [comment]
Already did.
