### ISSUE TITLE
Column names (sometimes) improperly decoded from Db2 for i Access Client Solutions

### ISSUE THREAD

**Issue by soundstripe** [mkleehammer/pyodbc#582]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.3
- pyodbc: 4.0.26
- OS: Debian 9.9 (docker python:3.7-slim-stretch)
- DB: Db2 for i 7.2
- driver: Db2 for i Access Client Solutions ODBC 64-bit (1.1.0.12-1.0.amd64.deb)
- unixodbc 2.3.7 (from source)

### Issue

From the following code:
    
    db2_sys = 'SYSTEM=*.*.*.*;UID=*****;PWD=*****;DRIVER={iSeries Access ODBC Driver}'
    q = "SELECT 1  AS this_is_a_really_long_column_name_more_than_30_chars FROM sysibm.SYSDUMMY1"
    for _ in range(2):
        with pyodbc.connect(db2_sys) as conn:
            print(conn.getinfo(pyodbc.SQL_MAX_COLUMN_NAME_LEN))
            c = conn.cursor()
            c.execute(q)
            print(list(c.description))

I expected to see
```
    128
    [('THIS_IS_A_REALLY_LONG_COLUMN_NAME_MORE_THAN_30_CHARS', <class 'int'>, None, 10, 10, 0, False)]
    128
    [('THIS_IS_A_REALLY_LONG_COLUMN_NAME_MORE_THAN_30_CHARS', <class 'int'>, None, 10, 10, 0, False)]
```

but actually I see:
```
    128
    [('THIS_IS_A_REALLY_LONG_COLUMN_N\x00\x00兓彌䕄䍓啟华䝉䕎D]\x00\x00嶠鶴嘅\x00嶰鶴嘅\x00', <class 'int'>, None, 10, 10, 0, False)]
    128
    [('THIS_IS_A_REALLY_LONG_COLUMN_NAME_MORE_THAN_30_CHARS', <class 'int'>, None, 10, 10, 0, False)]
```

(the garbage data varies and sometimes cannot be decoded and throws an exception).

The data on the wire is encoded in EBCDIC, but the data being passed to pyodbc is UTF-16le (I've experimented with setdecoding).

The first connection always shows garbage data after 30 characters and all subsequent connections work fine. IBM documentation as well as the SQLGetInfo() call states that 128 characters should be supported.

The unixodbc trace (attached) seems to show that SQLDescribeCol is being called the first time, instead of SQLDescribeColW (although I am not an expert at reading odbc logs).

[odbc.log](https://github.com/mkleehammer/pyodbc/files/3374370/odbc.log)

**Comment by soundstripe** [comment]
For now I am using pyodbc via sqlalchemy and have found a workaround to keep my column aliases below 30 characters in length:

    from ibm_db_sa.pyodbc import AS400Dialect_pyodbc

    class CustomAS400Dialect(AS400Dialect_pyodbc):
        max_identifier_length = 30

**Comment by v-chojas** [comment]
According to your log, the corrupted column name appears to be correct for the first 30 characters, and is then followed by two nulls (bringing the total to 32 --- a suspiciously round value) and then the ASCII string "SQL_DESC_UNSIGNED" (which has been interpreted as Unicode). I don't have DB2 nor the rest of your environment, but I'd start debugging this by tracing into unixODBC and see how it calls the driver, and whether the buffers returned there are correct. It could be a bug in the ODBC driver.

**Comment by soundstripe** [comment]
The text sent to pyodbc by the driver is UTF-16le so two bytes each. It does seem like it might be null terminated but that would be 62 bytes not 32.

The number of characters returned by pyodbc is always the expected number of characters unless the decoding fails with an error.

The data following the the 30 initial characters is not always the same, and appears to just be whatever was there from previously freed memory.


________________________________

**Comment by kadler** [comment]
Hey @soundstripe, I'm the lead developer for the IBM i Access driver. I'm not able to reproduce this problem, can you get a driver trace? Here's how to do so:

```
# enable tracing and set output path to current directory
/opt/ibm/iaccess/bin/cwbtrc /dt:1 /dpath:.

# run recreate here

# disable trace
/opt/ibm/iaccess/bin/cwbtrc /dt:0
```

A file named cwbdetail64-<program>-<pid in hex>.csv will be created.

**Comment by soundstripe** [comment]
I will try to get a trace this week. Will that trace tool work for ODBC connections as well as CLI connections?

**Comment by kadler** [comment]
I'm not sure what you're referring to by "CLI connections", but it affects all connections using the IBM i Access ODBC driver and nothing else.

**Comment by soundstripe** [comment]
Here is the requested trace. I appreciate your time, sorry this took a while for me to get back to.

I did revert to unixodbc version 2.3.6 prior to running this (as 2.3.7 made no difference in this issue, and 2.3.6 is in the debian apt repo).

[cwbdetail64-python-9.zip](https://github.com/mkleehammer/pyodbc/files/3678020/cwbdetail64-python-9.zip)

By CLI I was referring to the binary driver that gets downloaded with the ibm_db package on PYPI (in this case, CLI = DB2® Call Level Interface).

**Comment by kadler** [comment]
Thanks for the trace. I was able to recreate this internally as well. From what I can tell, it only seems to affect the first time a remote job is used. After that, the column names get returned correctly.

This definitely seems like a bug in either our driver or with the server. Can you please open a ticket with IBM to get this resolved?

**Comment by kadler** [comment]
Regarding CLI, I had a hunch you were speaking about that. That's a completely separate driver from a different team (used to be IBM, now Rocket Software).

**Comment by soundstripe** [comment]
> Thanks for the trace. I was able to recreate this internally as well. From what I can tell, it only seems to affect the first time a remote job is used. After that, the column names get returned correctly.

Glad to know it is reproducible. It does only occur the first time the job is used for me as well--I had forgotten about that once I got it to reproduce reliably. I'll try to get a ticket opened and with that, I'm going to close this issue as it seems unrelated to pyodbc.
