### ISSUE TITLE
PyODBC Driver Not working on MacOS

### ISSUE THREAD

**Issue by ss3456** [mkleehammer/pyodbc#584]
Hello,

I managed to install pyodbc by doing a pip install, and am trying to use it with a MySQL server, but I think I need to install the driver first.

I've downloaded the MacOS DMG file from https://dev.mysql.com/downloads/connector/odbc/ 

Every time I run a pyodbc.connect command in python, I get this error:
Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'MySQL ODBC 8.0 Driver' : file not found (0) (SQLDriverConnect)")

The driver won't install properly either. I have tried using the compress tar files and this doesn't work either
<img width="617" alt="Screen Shot 2019-07-13 at 22 01 53" src="https://user-images.githubusercontent.com/23143397/61176510-005b6300-a5ba-11e9-8a16-be961b41f614.png">

Please can someone recommend what to do about this, and if I need the driver or not? Any help is much appreciated. I'm very new to MySQL and Pyodbc 😀

**Comment by v-makouz** [comment]
You definitely need the driver in order for pyODBC to work, so you do need to figure out how to install it.
Because this is a problem with MySQL driver installation, it's probably best to look at their forums: https://forums.mysql.com/
