### ISSUE TITLE
Load a Flat text file to Informix database

### ISSUE THREAD

**Issue by rajesshh** [mkleehammer/pyodbc#586]
Hi,

I am trying to load a file to **Informix** database using python dataframe to_sql  but getting error.  I think to_sql doesnt support Informix Database. i am able to connect to Database using pyodbc.connect and also use cursor.execute for querying .Is there a way to load the file using Pyodbc cursor? 

code:
con = pyodbc.connect(constr, autocommit=True)
file ='/home/webload/be_merchant_current_10241_final.unl'
df = pd.read_csv(file, sep="\t")
df.to_sql(name='be_merchant_current', schema='informix',con=con, if_exists='append', index=False  )

Error:
 python connect1.py
/home/webload/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2531: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype, method=method)
Traceback (most recent call last):
  File "/home/webload/anaconda3/lib/python3.7/site-packages/pandas/io/sql.py", line 1431, in execute
    cur.execute(*args)
pyodbc.ProgrammingError: ('42S02', '[42S02] [Informix][Informix ODBC Driver][Informix]The specified table (sqlite_master) is not in the database. (-206) (SQLPrepare)')

Thanks,
Rajesh

**Comment by gordthompson** [comment]
This is not a pyodbc issue. The documentation for pandas' [to_sql](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html) method states:

> con : sqlalchemy.engine.Engine or sqlite3.Connection
> 
> Using SQLAlchemy makes it possible to use any DB supported by that library. Legacy support is provided for sqlite3.Connection objects.

That is, if the second argument to `to_sql` (the `con` argument) is not a SQLAlchemy `Engine` object then pandas treats it like a SQLite `Connection` object. You will either need to 

- find a SQLAlchemy dialect for Informix and use it to create an `Engine` object, or 
- use some other method to upload the contents of the DataFrame, possibly by using pandas' [itertuples](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html?highlight=itertuples#pandas.DataFrame.itertuples) method along with pyodbc's [executemany](https://github.com/mkleehammer/pyodbc/wiki/Cursor#executemanysql-params-with-fast_executemanyfalse-the-default) method.

**Comment by rajesshh** [comment]
Thanks Gord, let me check on this.

**Comment by PyodbcUnix** [comment]
@rajesshh  is it possible for you to connect to informix with pyodbc version bigger than 5.x.x and the unicode version SQLDriversConnectW() function?
