### ISSUE TITLE
Pyodbc is not working with stored procedure via Mssql server

### ISSUE THREAD

**Issue by jaganrajagopalme** [mkleehammer/pyodbc#587]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: Python 3.7.4 
- pyodbc: pyodbc 4.0.26
- OS: Window 10
- DB: Sql server 2016
- driver:

### Issue

Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: Python 3.7.4 
- pyodbc: pyodbc 4.0.26
- OS: Window 10
- DB: Sql server 2016
- driver:

### Issue

Basically, i am fetching the data from ms-sql via pyodc by using stored procedure with passing input parameter , but the record count always show as -1.
Please find the code as mention in below

import os.path
import pathlib
import pyodbc as db
folder=os.listdir(r'D:\\Projects\\rop source')
#\\tlstack\ALCSReports\Ajay\rops jagan
#db connection string -MICRASQL01 - Production
conn = db.connect("Driver={SQL Server Native Client 11.0};"
                     "Server=DEV-SERVER;"
                     "Database=DBApps;"
                    "Trusted_Connection=yes;")

 
for myfile in folder:
    extension=myfile.split(".")[-1]
    empno=myfile.split("-")[0]
    documentName=myfile.split("-")[-1]
    filename=myfile.split(".")[0]
    #show the file name 
    #print(myfile)
    #show the file name without extension
    print (myfile)
    #show the file extension
    #print (extension)
    #call the stored prcodure https://github.com/mkleehammer/pyodbc/wiki/Calling-Stored-Procedures
    #params = (filename)
    #fileList.append(filename)
    cursor = conn.cursor()
    param=(myfile)
    
    
    cursor.execute("{CALL get_employee(?)}", param)
    cursor.commit()
    ##print (sql)
    
    #cursor.execute(sql)
   # print (cursor.fetchval())
    print (cursor.rowcount)

    for row in cursor.fetchall():
         print ("row:", row[0])
         print ("rowcount:", cursor.rowcount)

         
cursor.close()
conn.close()

Regards
Jagan

**Comment by v-chojas** [comment]
Please format the code consistently by enclosing it in triple-backticks (`so that  spaces  are   preserved`), it is nearly impossible to read Python with no indentation.

cursor.rowcount uses the [SQLRowCount](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlrowcount-function) function, which is intended only for UPDATE, INSERT, or DELETE statements. As the pyODBC documentation says:

https://github.com/mkleehammer/pyodbc/wiki/Cursor

> The number of rows **modified** by the last SQL statement.

**Comment by jaganrajagopalme** [comment]
Thanks for response. Could please provide the sample code , how to fetch data using storedprocedure with input parameter in mssql server via pyodbc. Hope that will help alot. I am eagerly waiting for your reply

**Comment by gordthompson** [comment]
@jaganrajagopalme 

https://github.com/mkleehammer/pyodbc/wiki/Calling-Stored-Procedures

**Comment by mkleehammer** [comment]
It sounds like the documentation gordthompson provided will do, so I'll close this.  Please reopen if you find a problem.
