### ISSUE TITLE
cur.execute("insert into {} SELECT * FROM{}") python, sql

### ISSUE THREAD

**Issue by hengorin** [mkleehammer/pyodbc#589]
Hi,
I am trying to run cur.execute("insert into {} SELECT * FROM{}") 
but it is not insert any data
do you now how should I fix it?
thanks

**Comment by v-makouz** [comment]
"insert into {} SELECT * FROM{}" doesn't appear to be correct SQL, is this meant to expand into something?
It seems like the {} need to be substituted with something

**Comment by v-chojas** [comment]
Also, please post more information about your environment.

**Comment by mkleehammer** [comment]
I'm closing due to lack of response.  Please reopen if you have more information.  Thanks.
