### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by sameer-kumar** [mkleehammer/pyodbc#592]
I'm getting this error when I try to run a MSsql query in my python file:
**_ImportError: DLL load failed: The specified module could not be found._**

I'm running a python file in a windows nano 2019 docker container. 
I've pip installed pyodbc and SQLAlchemy in my docker image.
This is complete trace:

> Traceback (most recent call last):
>   File "./getSqlData.py", line 16, in <module>
>     db = create_engine('mssql+pyodbc:///?odbc_connect=%s' % params, fast_executemany=True)
>   File "c:\Python\AppPackages\sqlalchemy\engine\__init__.py", line 435, in create_engine
>     return strategy.create(*args, **kwargs)
>   File "c:\Python\AppPackages\sqlalchemy\engine\strategies.py", line 87, in create
>     dbapi = dialect_cls.dbapi(**dbapi_args)
>   File "c:\Python\AppPackages\sqlalchemy\connectors\pyodbc.py", line 37, in dbapi
>     return __import__("pyodbc")
> ImportError: DLL load failed: The specified module could not be found.

Environment:
Windows Nano 2019 docker container.
Python: 3.6.8
PyOdbc: 4.0.26
SqlAlchemy: 1.3.6

Am I the only one getting this?

**Comment by v-chojas** [comment]
You can try to use tool such as Process Monitor to determine which file it is not finding.
It will either be the pyodbc module DLL itself, or one of its dependencies.

**Comment by sameer-kumar** [comment]
After, looking at ProcMon logs it seems that **odbc32.dll** is missing in windows nano container. I copied that manually from my host into the container at c:\windows\system32\. Now I get this:

> RuntimeError: Can't initialize module pyodbc.  SQLAllocEnv failed.

**Comment by gordthompson** [comment]
[This TechNet thread](https://social.technet.microsoft.com/Forums/en-US/dbffabb5-5126-43f6-977c-7d9760540f4a/how-to-install-odbc-driver-on-microsoft-nano-serverdocker-container?forum=NanoServer) suggests that what you are attempting may not be possible.

**Comment by sameer-kumar** [comment]
So, what is a recommended way to interact with MSSQL from Python running in Windows Nano then?

**Comment by v-chojas** [comment]
It should be possible, as long as you have all the correct files and registry settings in place.
odbc32.dll is the Windows driver manager. The registry settings are described here:

https://docs.microsoft.com/en-us/sql/odbc/reference/install/registry-entries-for-odbc-components
https://docs.microsoft.com/en-us/sql/odbc/reference/install/registry-entries-for-data-sources

**Comment by gordthompson** [comment]
@v-chojas - When I use Process Monitor to capture events when I do `import pyodbc` from a Python console I see that python.exe accesses both

C:\Windows\System32\odbc32.dll

and

C:\Windows\System32\odbcint.dll

@sameer-kumar - Are you seeing the new "SQLAllocEnv failed." message when you execute `import pyodbc` or is it happening later on in your script?

**Comment by sameer-kumar** [comment]
I don't think this is something trivial. I may have to use pymssql instead of pyodbc.

**Comment by v-makouz** [comment]
If the driver manager was missing then was the driver itself installed? Sometimes SQLAllocEnv fails because of inability to load the driver.

**Comment by v-chojas** [comment]
I believe pymssql uses FreeTDS, which is also an ODBC driver.

**Comment by gordthompson** [comment]
@v-chojas - FreeTDS can be compiled to produce an ODBC driver, but it is also a native TDS API that can be called directly from an application like pymssql (without the ODBC layer in between).

**Comment by sameer-kumar** [comment]
I tried pymssql and it works in my Windows Nano container without any issues.
I was leaning towards pyodbc because of its better security model for Windows world AFAIK. Do you think I should investigate further to make pyodbc work in Windows Nano which seems significant in nature versus keep using the pymsssql?

**Comment by gordthompson** [comment]
> Do you think I should investigate further to make pyodbc work in Windows Nano which seems significant in nature versus keep using the pymsssql?

That's a very broad question that only you can answer. pymssql will have some limitations, but if your business requirements can be satisfied by what pymssql can offer then it does make sense to use it.

**Comment by v-chojas** [comment]
@gordthompson thanks for the clarification.

@sameer-kumar I am not sure what you mean by "its better security model for Windows world'. If you are able to get ODBC working in Nano Server then you would be able to use other ODBC drivers, including the official Microsoft ODBC Driver for SQL Server. The latter has some features to support the newer versions of SQL Server, which may not be found in FreeTDS.

**Comment by sameer-kumar** [comment]
I mean with pymssql I need to integrate OpenSSL vs pyodbc which I assume is secure oob. Is my assumption correct?

**Comment by gordthompson** [comment]
@sameer-kumar - Yes. The pre-compiled wheel files for pymssql are statically linked to FreeTDS *without* SSL support. If you want pymssql with SSL on Windows then you'll either need to 

- find a compiled version that uses dynamic linking and supply the required DLLs for OpenSSL, or
- build your own pymssql on Windows from source.

More details available [here](http://pymssql.org/en/latest/freetds.html#windows) (although I'm not sure how up-to-date they are).

**Comment by sameer-kumar** [comment]
Thanks for the pointers. I guess I know what to do from here.
