### ISSUE TITLE
pyodbc.Error mangled with unicode characters

### ISSUE THREAD

**Issue by deadbird99** [mkleehammer/pyodbc#594]
environment:
- Windows 10
- Python 3.7.3
- Database: Filemaker
- Driver: Filemaker ODBC driver

Here is the piece of code that causes the issue:
```
    try:
        fmsConnector = pyodbc.connect(fmsConnectionString)
    except pyodbc.Error as e:
        error = str(e)
        print (error)
```

The the connect fails, it returns a string completely mangled with unicode characters, UTF16 I guess:

```
pyodbc.InterfaceError: ('28000', '[28000] [FileMaker][FileMaker]  (212): Invalid account/password\x00\u75c0*\u75c0*\u33e4*\x1f\x00\u6029\u4ed6\uf278\u011e\u65aa\u669b\u4ae0+\u75c0*\u6029\u4ed6\uf270\u011e\x00\x00\x00\x00\u36a8\x1b\x00\x00\x01\x00\x1f\x00\x01\x00\uf28c\u011e\uf290\u011e\u351a\u669e\x06\x00\ub0201\uf2b8\u011e\ua975\u66a0\x00\x00\x1f\x00 (212) (SQLDriverConnect); [28000] [FileMaker][FileMaker]  (212): Invalid account/password\x00\u75c0*\u75c0*\u33e4*\x1f\x00\u6029\u4ed6\uf278\u011e\u65aa\u669b\u4ae0+\u75c0*\u6029\u4ed6\uf270\u011e\x00\x00\x00\x00\u36a8\x1b\x00\x00\x01\x00\x1f\x00\x01\x00\uf28c\u011e\uf290\u011e\u351a\u669e\x06\x00\ub0201\uf2b8\u011e\ua975\u66a0\x00\x00\x1f\x00 (212)')
``` 

Note: I use
```
        fmsConnector.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
        fmsConnector.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
        fmsConnector.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-16')
        fmsConnector.setencoding(encoding='utf-8')
```

but right after that, no luck :(

**Comment by deadbird99** [comment]
Also: this problem only happens on windows. The same script runs perfectly on a mac.

**Comment by gordthompson** [comment]
On the Mac does the error message contain any text after "Invalid account/password"?

**Comment by deadbird99** [comment]
Whole error message is: "Error is: ('28000', '[28000] [FileMaker][FileMaker ODBC]  (213): Password incorrect (213) (SQLDriverConnect)')"

**Comment by gordthompson** [comment]
Interesting that on Windows you get error (212) while on Mac you get error (213). In any case it looks like the error message on Windows is a null-terminated string (`Invalid account/password\x00`) whose length is being mis-reported by the driver, similar to #328 . (An ODBC trace might help confirm that.) If so, then an output converter function similar to [this one](https://github.com/mkleehammer/pyodbc/issues/328#issuecomment-419655266) might help work around the problem.

**Comment by deadbird99** [comment]
I tried the following:
```
    try:
        fmsConnector = pyodbc.connect(fmsConnectionString)
    except pyodbc.Error as e:
        n = str(e).index('\0x00')
        s = str(e).index[:n]
```

With this:

```
pyodbc.InterfaceError: ('28000', '[28000] [FileMaker][FileMaker]  (212): Invalid account/password\x00\u75c0�\u75c0�\u33e4�\x1f\x00\ud4a5\ua776\uedd8�\u65aa\u669b\u4ae0�\u75c0�\ud4a5\ua776\uedd0�\x00\x00\x00\x00\u30d8\u012b\x00\x00\x01\x00\x1f\x00\x01\x00\uedec�\uedf0�\u351a\u669e\x06\x00\ub020�\uee18�\ua975\u66a0\x00\x00\x1f\x00 (212) (SQLDriverConnect); [28000] [FileMaker][FileMaker]  (212): Invalid account/password\x00\u75c0�\u75c0�\u33e4�\x1f\x00\ud4a5\ua776\uedd8�\u65aa\u669b\u4ae0�\u75c0�\ud4a5\ua776\uedd0�\x00\x00\x00\x00\u30d8\u012b\x00\x00\x01\x00\x1f\x00\x01\x00\uedec�\uedf0�\u351a\u669e\x06\x00\ub020�\uee18�\ua975\u66a0\x00\x00\x1f\x00 (212)')
```

And I got this:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Utilisateur\Documents\Repos\mts\SQLImportFromFMS\SQLImportFromFMS.py", line 297, in <module>
    n = str(e).index('\0x00')
ValueError: substring not found
```

It's becoming pure madness ^^

**Comment by gordthompson** [comment]
`n = str(e).index('\0x00')` won't work, but `n = str(e).index('\x00')` should.

**Comment by deadbird99** [comment]
Still the same.

**Comment by v-chojas** [comment]
Please post an [ODBC trace](https://docs.microsoft.com/en-us/sql/odbc/admin/setting-tracing-options).

**Comment by deadbird99** [comment]
There you go. I ran the script a few times to be sure you have avery piece of information you need.
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/3428164/SQL.LOG)

**Comment by v-chojas** [comment]
```
SQLImportFromFM 418c-d74	EXIT  SQLGetDiagRecW  with return code 0 (SQL_SUCCESS)
		SQLSMALLINT                  2 <SQL_HANDLE_DBC>
		SQLHANDLE           0x00987728
		SQLSMALLINT                  1 
		SQLWCHAR *          0x005EFA14 [       5] "28000"
		SQLINTEGER *        0x005EF1F0 (212)
		SQLWCHAR *          0x005EF214 [     110] "[FileMaker][FileMaker]  (212): Invalid account/password\ 0?l?l?l\1f\ 0???^???m?l???^\ 0\ 0\ 0\ 0??\ 0\ 0\ 1\ 0\1f\ 0\ 1\ 0?^?^??\ 6\ 0?s?^??\ 0\ 0\1f\ 0"
		SQLSMALLINT               1023 
		SQLSMALLINT *       0x005EF1F4 (110) <---- the problem is here
```
The actual length of the error message is 55 characters, which is 110 bytes in UTF-16, but the driver is returning a byte count instead of a character count. This is incorrect according to the ODBC specification:

https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdiagrec-function

> [Output] Pointer to a buffer in which to return the total number of **characters** (excluding the number of characters required for the null-termination character)

**Comment by deadbird99** [comment]
Oh my, I know FileMaker is a huge pile of crap, but even their ODBC driver...I will report the bug to them, hope they will fix it asap. Thanks a lot for your help @v-chojas and @gordthompson , I'm closing the issue.
