### ISSUE TITLE
AWS Lambda PYODBC no module named 

### ISSUE THREAD

**Issue by aarontanzk** [mkleehammer/pyodbc#599]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7
- pyodbc: 4.0.27
- OS: WINDOWS
- DB: MS SQL SERVER 
- driver: SQL SERVER

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

Expected behavior:
I have a working python script with pyodbc installed via pip which executes the sql well.
I am trying to move this script to be executed via AWS Lambda.

Expected behavior is to execute successfully as per my local machine.

Observed behavior:
To package it as a zip file to send to AWS, I have done pip install pyodbc -t . , which creates a pyodbc-4.0.27.dist-info and pyodbc.cp37-win32.pyd.

Unlike other packages, it does not come with a pyodbc folder.

When executed on AWS, I'm getting the error:

[ERROR] Runtime.ImportModuleError: Unable to import module 'main': No module named 'pyodbc'

which means that there is no readable py files from pyodbc.

======================================================

Any idea how to resolve?

Thanks!

**Comment by v-chojas** [comment]
Check the module path:
```
import sys
print(sys.path)
```
and ensure the pyODBC module can be found in one of them.
