### ISSUE TITLE
ODBC API to Python Method mapping 

### ISSUE THREAD

**Issue by rooparam** [mkleehammer/pyodbc#602]
Hi ,

I was  looking for a mapping list of Supported Python Methods to corresponding ODBC API .

https://github.com/mkleehammer/pyodbc/wiki/Features-beyond-the-DB-API

In this link we have a table under Miscellaneous ODBC Functions. I was looking for other ODBC API also .

I went to the wiki page but couldn't get any . Can you please help me with this. 

Regards
Roopa

**Comment by v-chojas** [comment]
Which one in particular are you looking for? You can search the source code for the API you want; if it's not there, then it has not been implemented. The list of methods available for cursor objects is here:

https://github.com/mkleehammer/pyodbc/blob/master/src/cursor.cpp#L2272

**Comment by mkleehammer** [comment]
Closing due to lack of response.
