### ISSUE TITLE
Documentation issue - Unicode page

### ISSUE THREAD

**Issue by blackgis** [mkleehammer/pyodbc#607]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.4/64bit
- pyodbc: 4.0.27
- OS: Win10
- DB: SQL SERVER
- driver: 10.00.18362

pyodbc.connect('Driver={SQL Server};'

### Issue
Source: https://github.com/mkleehammer/pyodbc/wiki/Unicode

My collation is "SQL_Latin1_General_CP1_CI_AS", and when i add 

`cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='latin1', to=str) 
cnxn.setencoding(str, encoding='latin1')`

I always get the error

> TypeError: 'to' is an invalid keyword argument for this function

Removing **to=str** just leads to

> TypeError: argument 1 must be str, not type

So far I could execute all the select statements without an issue, but today i looked something up and found that and tried it out and failed.

**Comment by blackgis** [comment]
pyodbc.connect('Driver={SQL Server};'..

**Comment by v-chojas** [comment]
The `to` keyword is only available when using Python 2.x . See [source](https://github.com/mkleehammer/pyodbc/blob/master/src/connection.cpp#L1516) for the full keyword list.

**Comment by blackgis** [comment]
@v-chojas I overread the python 2.7 info that is mentioned in the side, sorry
