### ISSUE TITLE
Install fails 3.0.10 on Yosemite

### ISSUE THREAD

**Issue by Bobspadger** [mkleehammer/pyodbc#61]
Hi

Build fails:

running

`sudo python setup.py build install`

```
returns
x-10.6-intel-2.7/pyodbc.so
ld: library not found for -lodbc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit status 1
```

I can install from 3.0.7 using the same technique fine.

**Comment by tekknolagi** [comment]
Did you install ODBC? Perhaps with Homebrew?

**Comment by Bobspadger** [comment]
Hi,

ODBC was installed using http://www.odbcmanager.net/

I have it all working fine on 3.0.7 but as soon as I try to install with 3.0.10 I get the compiler issues.

**Comment by pendolf** [comment]
```brew install mysql-connector-odbc``` work with 3.0.10

**Comment by mkleehammer** [comment]
This is correct.  Apple stopped shipping iODBC.
