### ISSUE TITLE
pyodbc arabic text coming as illegal characters

### ISSUE THREAD

**Issue by ziaul-haque** [mkleehammer/pyodbc#613]
- Python: Python 3.5.2
- pyodbc: 4.0.26
- OS: ubuntu 16.04
- DB:mssql server
- driver:FreeTDS 

### Issue
arabic text coming as illegal characters

**Comment by gordthompson** [comment]
Do you get correct results if you run this (substituting your own SERVER, UID, and PWD values)?

```python
import pyodbc

connection_string = (
    'DRIVER=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so;'
    'SERVER=192.168.0.179,49242;'
    'TDS_Version=7.1;'
    'UID=sa;PWD=_whatever_;'
)
cnxn = pyodbc.connect(connection_string)
crsr = cnxn.cursor()
sql = "SELECT ?"
params = ('\u0645\u0627\u0621',)
print(crsr.execute(sql, params).fetchval())  # ماء

**Comment by v-chojas** [comment]
Could you provide more details?

Also, try the [Microsoft ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server).

**Comment by mkleehammer** [comment]
I'm going to close this due to lack of response.  Please reopen if you want to continue troubleshooting this.
