### ISSUE TITLE
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server Native Client 11.0' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by Chenhonli** [mkleehammer/pyodbc#616]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: python3.6.0
- pyodbc: 4.0.27
- OS: centos7
- DB: sqlserver
- driver: SQL Server Native Client 11.0

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by v-makouz** [comment]
Can you attach the contents of `/etc/odbcinst.ini`? And in there there should be something like
```
[SQL Server Native Client 11.0]
Driver=/path/to/driver.so
```

Can you also post the output of `ldd /path/to/driver.so`?

**Comment by mkleehammer** [comment]
Closing due to lack of response.

**Comment by Manibandaru** [comment]
Hi ,

Found any solutions , if yes please share it
