### ISSUE TITLE
Correct parameter of setinputsizes: pyodbc.SQL_TIMESTAMP 

### ISSUE THREAD

**Issue by washolive** [mkleehammer/pyodbc#622]
The pyodbc returned a error when I tried to use the literal "SQL_TIMESTAMP" as parameter for setinputsizes(list_of_value_tuples). Eg: setinputsizes([pyodbc.SQL_TIMESTAMP]).

This is the syntax according to wiki Data Types: 
https://github.com/mkleehammer/pyodbc/wiki/Data-Types

Luckly, I changed to "pyodbc.**SQL_TYPE_TIMESTAMP**" and it worked !
May review the wiki ?
Thanks.

### Environment
- Python: 3.7
- pyodbc: 4.0.27
- OS: Windows 10
- DB: Microsoft SQL Server
- driver: Microsoft SQL Server 13

**Comment by gordthompson** [comment]
Feel free to update the wiki with any corrections or improvements you may wish to offer. That's what a wiki is for!

**Comment by mkleehammer** [comment]
Does anyone know why ODBC named most of these constants `SQL_<DBTYPE>` but the date and time constants `SQL_TYPE_<DBTYPE`?  For example, `SQL_NUMERIC` and `SQL_TYPE_DATE`?

**Comment by mkleehammer** [comment]
Also, thanks for the Wiki update, whoever did it.

**Comment by v-chojas** [comment]
@mkleehammer SQL_xxx were there since ODBC 1.x, while the SQL_TYPE_xxx were introduced in ODBC 3.0. See https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/datetime-data-types for more information.
