### ISSUE TITLE
MS Access: "SELECT ? AS ..." returns incorrect value for Decimal parameter

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#624]
I suspect that this may be a bug in the Access ODBC driver, but because it involves a Python `decimal.Decimal` parameter value I can't try the usual trick of doing the same thing from VBScript, C#, or whatever. I'm hoping that someone with a better understanding of pyodbc internals might see something in the ODBC trace to support or refute my suspicion.

My `decimal.Decimal` parameter works fine for inserting a value into a `DECIMAL` column, but using that same parameter value in `SELECT ? AS ...` yields an incorrect (and very small) Decimal result.

Repro code:

```python
print(sys.version)
# 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
print(pyodbc.version)
# 4.0.27

print(connection_string)
# DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\__tmp\gord_test.accdb;ExtendedAnsiSQL=1;

cnxn = pyodbc.connect(connection_string, autocommit=True)
print(f'{cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
# ACEODBC.DLL, version: Microsoft Access database engine

crsr = cnxn.cursor()

table_name = "decimal_table"
try:
    crsr.execute(f"DROP TABLE {table_name}")
except:
    pass
crsr.execute(f"CREATE TABLE {table_name} (decimal_field DECIMAL(18, 4))")
sql = f"INSERT INTO {table_name} (decimal_field) VALUES (?)"
decimal_pi = Decimal('3.14')
crsr.execute(sql, decimal_pi)
sql = f"SELECT decimal_field AS from_table, ? AS from_param FROM {table_name}"
row = crsr.execute(sql, decimal_pi).fetchone()
print(f"from_table: {repr(row.from_table)}")
# from_table: Decimal('3.1400')
print(f"from_param: {repr(row.from_param)}")
# from_param: Decimal('6.2865046510420328852781736E-21')
```

ODBC trace: 
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/3639174/SQL.LOG)

**Comment by v-chojas** [comment]
I tried your repro with the ODBC Driver 17 for SQL Server using basically the exact same syntax and steps, and it returns correctly `Decimal('3.1400')` and `Decimal('3.14')` for the two respectively, so I'm also inclined to think this is a bug in the Access driver.

The significand of the incorrect value is amazingly close to twice 3.14 that I suspect some sort of misinterpretation of values is occurring.

**Comment by gordthompson** [comment]
Thanks for checking, @v-chojas .

> The significand of the incorrect value is amazingly close to twice 3.14

I noticed that, too, but I tried with different values like 1.11 and I didn't get any consistent pattern except that the numbers are all *really* small. The other thing that looks odd is the difference between the two `SQLDescribeColW` results:

```
main            19a0-7e0	EXIT  SQLDescribeColW  with return code 0 (SQL_SUCCESS)
        HSTMT               0x000000F0A0E421F0
        UWORD                        1 
        WCHAR *             0x000000F09D95EF40 [      10] "from_table"
        SWORD                      300 
        SWORD *             0x000000F09D95EF08 (10)
        SWORD *             0x000000F09D95EF04 (2)
        SQLULEN *           0x000000F09D95EF18 (18)
        SWORD *             0x000000F09D95EF10 (4)
        SWORD *             0x000000F09D95EF0C (1)
```

versus

```
main            19a0-7e0	EXIT  SQLDescribeColW  with return code 0 (SQL_SUCCESS)
        HSTMT               0x000000F0A0E421F0
        UWORD                        2 
        WCHAR *             0x000000F09D95EF40 [      10] "from_param"
        SWORD                      300 
        SWORD *             0x000000F09D95EF08 (10)
        SWORD *             0x000000F09D95EF04 (2)
        SQLULEN *           0x000000F09D95EF18 (1033)
        SWORD *             0x000000F09D95EF10 (0)
        SWORD *             0x000000F09D95EF0C (1)
```

**Comment by v-chojas** [comment]
I also notice in the ODBC log that the Access driver actually returns the string ".0000000000000000000062865046510420328852781736", which if you take only the significand as an integer, it becomes the bytes `a8 7a 00 00 00 00 00 00 31 00 34`, from which you can see 7aa8, or 31400 in decimal, as well as the characters '1' and '4'. The driver is definitely very confused here.
