### ISSUE TITLE
fetchmany() keeps returning the last n rows at the end instead of an empty set

### ISSUE THREAD

**Issue by arielnmz** [mkleehammer/pyodbc#625]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.4 (64 bit)
- pyodbc: 4.0.27
- OS: Linux (docker alpine)
- DB: Access MDB file (kinda old, tried accessing it with MS access 2013 and works fine)
- driver: MDBTools 0.7.1

### Issue

Take this query for example:

    SELECT * From Contracts

This table has 16,000 rows, and when I execute the following code:

```
while True:
    r=cur.fetchmany(1000)
    if not r:
        break
    print(len(r))
```

It prints 16 batches of 1000 rows, but then instead of returning an empty set, it keeps returning the last 11 rows. Why? `fetchall()` works fine and returns just 16,000 rows.

**Comment by gordthompson** [comment]
Can you reproduce the issue on a smaller scale? For example, if you have a table with 5 rows and you use `fetchmany(3)` do you eventually wind up getting the last 2 rows over and over? If so, then an [ODBC trace log](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) may offer some insights.

However, I tried to reproduce your issue with odbc-mdbtools 0.7.1 on Xubuntu 18.04 but I could not get it to work *at all*. I strongly suspect that you have simply encountered a defect in the ODBC driver.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Comment by arielnmz** [comment]
Shoot I had a response in the mail but for some reaon it never went out. I just noticed now that I got this mail. Sorry. I'll see if it's still an issue and will come back if I find anything
