### ISSUE TITLE
pyodbc.connect fails with: No message found for message number 2 of module 'Operating System'

### ISSUE THREAD

**Issue by villekr** [mkleehammer/pyodbc#626]
### Environment

- Python: 3.7
- pyodbc: 4.0.27
- OS: Debian GNU/Linux 9 (stretch) in Docker for macOS 2.1.0.0
- DB: Netsuite (Some Oracle flavour?)
- driver: Netsuite ODBC Linux64bit: Release 8.1.0.0089, March 2019

### Issue

ODBC connection fails with below message.
```
conn_str = DRIVER={NetSuite ODBC Drivers 8.1};Host=odbcserver.eu2.netsuite.com;Port=1708;Encrypted=1;Truststore=/opt/netsuite/odbcclient/cert/ca.cer, /opt/netsuite/odbcclient/cert/ca2.cer, /opt/netsuite/odbcclient/cert/ca3.cer;SDSN=NetSuite.com;UID=***;PWD=***;CustomProperties=AccountID=***;RoleID=***

pyodbc.connect(conn_str, timeout=10),
--> pyodbc.Error  ('HY000', "[HY000] [NetSuite][ODBC 64 bit driver][64 bit Client]No message found for message number 2 of module 'Operating System'. (0) (SQLDriverConnect)")
```

ODBC connection has been working with older Netsuite odbc version, where only differences to current configuration were:
- driver: Netsuite ODBC Linux64bit: Release 7.2, Build Number 7.2.0.0050, September 2015
- conn_str = DRIVER={NetSuite ODBC Drivers 7.2};...
I'm trying to update to newer driver to find a fix for another problem where query fails with odbc error.

**Comment by v-chojas** [comment]
Could you use the `isql` command to try connecting, instead of through pyODBC?

`isql -v -k 'your connection string here'`

If that also does not work, the problem is not in pyODBC but your driver's configuration.

**Comment by villekr** [comment]
Thanks for that tip. Apparently the issue was not related to pyodbc. Based on isql output I may have figured out what need to change in driver configuration.

```
isql -v -k "DRIVER={NetSuite ODBC Drivers 8.1};Host=odbcserver.eu2.netsuite.com;Port=1708;Encrypted=1;Truststore=/opt/netsuite/odbcclient/cert/ca.cer,/opt/netsuite/odbcclient/cert/ca2.cer,/opt/netsuite/odbcclient/cert/ca3.cer;SDSN=NetSuite.com;UID=***;PWD=***;CustomProperties=AccountID=***;RoleID=***"
[S1000][NetSuite][ODBC 64 bit driver][64 bit Client]No message found for message number 2 of module 'Operating System'.
[S1000][NetSuite][ODBC 64 bit driver][64 bit Client]Problem with certificate from file /opt/netsuite/odbcclient/cert/ca.cer.
[01S00][NetSuite][ODBC 64 bit driver]Invalid attribute in connection string: CustomProperties.
[01S00][NetSuite][ODBC 64 bit driver]Invalid attribute in connection string: RoleID.
[ISQL]ERROR: Could not SQLDriverConnect
```
