### ISSUE TITLE
lost synchronization with server on query with many parameters

### ISSUE THREAD

**Issue by sogartar** [mkleehammer/pyodbc#627]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7 64-bit
- pyodbc: 4.0.27
- OS: Ubuntu 16.04
- DB: Postgresql 11
- driver: PostgreSQL Unicode (psqlODBC)

### Issue

I have the following query
```
SELECT * FROM (VALUES (?),(?)...) t(val)
```
Then execute with
```
cursor.execute(query, params)
```

If the number of query parameters is large ~2^14, this query fails with
```
pyodbc.Error: ('HY000', '[HY000] lost synchronization with server: got message type "t", length 65542\n;\nError while preparing parameters (1) (SQLExecDirectW)')
```

The query should complete without errors.

I tried the same query with psycopg2. There even with 2^24 parameters the query is executed successfully.

**Comment by gordthompson** [comment]
I am able to reproduce your issue with the following code:

```python
print(f"Python version {sys.version}")
# Python version 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]

print(f"pyodbc version {pyodbc.version}")
# pyodbc version 4.0.27

connection_string = get_conn_str()
print(connection_string)
# DSN=PostgreSQL35W

cnxn = pyodbc.connect(connection_string)
print(f'{cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
# PSQLODBC35W.DLL, version: 11.01.0000

crsr = cnxn.cursor()

num_params = 7499
print(f"Attempting {num_params} parameters ...")
qmark_string = ",".join(["(?)" for x in range(num_params)])
sql = "SELECT * FROM (VALUES " + qmark_string + ") t(val)"
params = tuple(range(num_params))
crsr.execute(sql, params)
n = 0
for row in crsr:
    n += 1
print(f"{n} row(s) returned")
```

The code works with num_params ≤ 7498, but fails for anything larger.

However, I was also able to reproduce the issue using `System.Data.Odbc` in .NET, although the failure point there was 32768 and the error was

```
Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Data.Odbc.OdbcParameterCollection.Bind(OdbcCommand command, CMDWrapper cmdWrapper, CNativeBuffer parameterBuffer)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at System.Data.Odbc.OdbcCommand.ExecuteReader(CommandBehavior behavior)
   at odbcConsoleApp.Program.Main(String[] args) in C:\Users\Gord\source\repos\odbcConsoleApp\Program.cs:line 31
```

So it looks like there is some sort of limitation on the number of parameters that the ODBC driver can handle.

**Comment by v-chojas** [comment]
If you need that many parameters, consider redesigning your query. All databases have their limits which are considered reasonable and it's not a good idea to try exceeding or even approaching them.

**Comment by mkleehammer** [comment]
I have to agree with @v-chojas on this - I can't imagine that you really want to use that many parameters.  Perhaps there is a bulk copy you can use?

Anyway, as this seems to be an environment / driver / DB issue, I'm going to close.
