### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 18: ordinal not in range(128)

### ISSUE THREAD

**Issue by dbrennand** [mkleehammer/pyodbc#628]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 2.7.5 and 3.6.8
- pyodbc: 4.0.27
- OS: Red Hat 4.8.5 - CentOS
- DB: SQL Server.
- driver: ODBC Driver 17 for SQL Server

### Issue
I am receiving the following error:
```UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 18: ordinal not in range(128)```

I have tried:
```
cnxn.setencoding(str, 'utf-8')
cnxn.setencoding(unicode, 'utf-8')
# and
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='latin1', to=str)
cnxn.setencoding(str, encoding='latin1')
# also
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-8')
cnxn.setencoding(str, encoding='utf-8')
cnxn.setencoding(unicode, encoding='utf-8')
```

With no luck. Any advice on how to proceed?

**Comment by dbrennand** [comment]
I also just tried in Python 3. Same error. I'm going to try another driver version.

**Comment by dbrennand** [comment]
Tried using `ODBC Driver 13 for SQL Server` and `ODBC Driver 17 for SQL Server` both fail with the same error.

**Comment by dbrennand** [comment]
In Python 3 I have tried adding `cnxn.setencoding('utf-8')` to the connection factory.

**Comment by dbrennand** [comment]
I have also tried `cnxn.setencoding(encoding='utf-8', ctype=pyodbc.{SQL_CHAR and SQL_WCHAR})`

**Comment by v-makouz** [comment]
Do you have a repro script with the string that gives that error?

**Comment by dbrennand** [comment]
```
import pyodbc
server = 'xxxx'
database = 'xxx'
username = ''
password = r''
cnxn = pyodbc.connect('DRIVER={ODBC Driver 13 #or 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()
for rows in cursor.execute('SELECT x, x, x FROM x.x.x').fetchall():
    for row in rows:
        print(row)
```

Pretty simple.

**Comment by dbrennand** [comment]
Resolved. The solution was in Python 3.

```
cnxn = pyodbc.connect()
cnxn.setencoding('utf-8')
cursor = cnxn.cursor()
for row in cursor.execute(xxx).fetchall():
    for column in row:
        col = column
        if isinstance(col, str):
            col = col.encode('utf-8')
        print(col)

**Comment by gauravphagrehpe** [comment]
what was the solution here ? I am also getting the same error...
