### ISSUE TITLE
SQLExecDirectW exception with pyodbc and SQL Server

### ISSUE THREAD

**Issue by piskvorky** [mkleehammer/pyodbc#636]
A `cursor.execute("SELECT …")` query against SQL Server with pyodbc is giving me this error:

*pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]HdfsBridge::recordReaderFillBuffer - Unexpected error encountered filling record reader buffer: NumberFormatException: For input string: "5,41E+18" (107090) (SQLExecDirectW)')*

Any idea where that is coming from? Is it fixable on my (=pyodbc's) side? (The SQL DB is not under my control.)

### Environment

- Python: `Python 3.7.3 (default, Aug 20 2019, 17:04:43) [GCC 8.3.0] on linux`
- pyodbc: `pyodbc==4.0.26`
- OS: Ubuntu 19.04
- DB: SQL Server
- driver: ODBC Driver 17 for SQL Server

**Comment by gordthompson** [comment]
Can you narrow it down to a particular column that causes the error? If so, what is the data type of that column? Also be sure to specify if the query simply retrieves the column directly, or if it tries to do a CAST/CONVERT (or similar) on it.

**Comment by v-chojas** [comment]
Do you have a repro? That error is coming from the server.

**Comment by piskvorky** [comment]
I have more:

*pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]External file access failed because the specified path name '/OK/FILESERVER/PRODUTO/2019/10/07' does not exist. Enter a valid path and try again. (105002) (SQLExecDirectW)")*

and 

*pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]HdfsBridge::recordReaderFillBuffer - Unexpected error encountered filling record reader buffer: HadoopExecutionException: Not enough columns in this line. (107090) (SQLExecDirectW)')*

I'm not sure how the SQL server is set up, these logs came from the client, I don't have direct access. But googling around, the errors seem related to Parquet or HDFS or Hadoop… maybe some SQL adapter? Is there such thing?

I've not seen this before, but I'm thinking the error could be related to the SQL adapter configuration, rather than pyodbc.

@gordthompson there's no CAST/CONVERT, this is a straight up `SELECT {columns} FROM [db_name].[schema_name].[table_name]`.

**Comment by v-chojas** [comment]
You are correct, those error messages are all coming from the server. pyODBC just passes through the query and otherwise has no involvement in this.

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
