### ISSUE TITLE
cannot install on windows 10 python 3.8 x64 

### ISSUE THREAD

**Issue by CRCGlobal** [mkleehammer/pyodbc#638]
C:\Python38>pip install pyodbc
Collecting pyodbc
  Using cached https://files.pythonhosted.org/packages/75/29/aa190749bac37ede0f11a68a75e7055254699c11572bd94213f1163dfd8f/pyodbc-4.0.27.tar.gz
Installing collected packages: pyodbc
    Running setup.py install for pyodbc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\taskrunner\\AppData\\Local\\Temp\\pip-install-4vqdclpn\\pyodbc\\setup.py'"'"'; __file__='"'"'C:\\Users\\taskrunner\\AppData\\Local\\Temp\\pip-install-4vqdclpn\\pyodbc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\taskrunner\AppData\Local\Temp\pip-record-wcc3z0yx\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\taskrunner\AppData\Local\Temp\pip-install-4vqdclpn\pyodbc\
    Complete output (99 lines):
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\buffer.cpp /Fobuild\temp.win-amd64-3.8\Release\src\buffer.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    buffer.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\cnxninfo.cpp /Fobuild\temp.win-amd64-3.8\Release\src\cnxninfo.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    cnxninfo.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\connection.cpp /Fobuild\temp.win-amd64-3.8\Release\src\connection.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    connection.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    src\connection.cpp(145): warning C4312: 'type cast': conversion from 'unsigned long' to 'SQLPOINTER' of greater size
    src\connection.cpp(149): warning C4312: 'type cast': conversion from 'long' to 'SQLPOINTER' of greater size
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\cursor.cpp /Fobuild\temp.win-amd64-3.8\Release\src\cursor.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    cursor.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\errors.cpp /Fobuild\temp.win-amd64-3.8\Release\src\errors.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    errors.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    src\errors.cpp(295): warning C4365: 'argument': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    src\errors.cpp(331): warning C4996: 'PyUnicode_GetSize': deprecated in 3.3
    c:\python38\include\unicodeobject.h(177): note: see declaration of 'PyUnicode_GetSize'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\getdata.cpp /Fobuild\temp.win-amd64-3.8\Release\src\getdata.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    getdata.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\params.cpp /Fobuild\temp.win-amd64-3.8\Release\src\params.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    params.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    src\params.cpp(86): warning C4365: '=': conversion from 'SQLULEN' to 'SQLLEN', signed/unsigned mismatch
    src\params.cpp(94): warning C4365: '=': conversion from 'SQLULEN' to 'SQLLEN', signed/unsigned mismatch
    src\params.cpp(127): warning C4365: '=': conversion from 'SQLULEN' to 'SQLLEN', signed/unsigned mismatch
    src\params.cpp(274): warning C4365: '=': conversion from 'SQLCHAR' to 'SQLSCHAR', signed/unsigned mismatch
    src\params.cpp(275): warning C4365: '=': conversion from 'bool' to 'SQLCHAR', signed/unsigned mismatch
    src\params.cpp(316): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'std::size_t', signed/unsigned mismatch
    src\params.cpp(362): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'std::size_t', signed/unsigned mismatch
    src\params.cpp(387): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'std::size_t', signed/unsigned mismatch
    src\params.cpp(407): warning C4365: 'initializing': conversion from 'int' to 'SQLUINTEGER', signed/unsigned mismatch
    src\params.cpp(435): warning C4365: '=': conversion from 'int' to 'SQLUINTEGER', signed/unsigned mismatch
    src\params.cpp(473): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'std::size_t', signed/unsigned mismatch
    src\params.cpp(538): warning C4365: '=': conversion from 'bool' to 'SQLCHAR', signed/unsigned mismatch
    src\params.cpp(556): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'long', possible loss of data
    src\params.cpp(571): warning C4365: '=': conversion from 'SQLCHAR' to 'SQLSCHAR', signed/unsigned mismatch
    src\params.cpp(1183): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLINTEGER', possible loss of data
    src\params.cpp(1183): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLSMALLINT', possible loss of data
    src\params.cpp(1193): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLUSMALLINT', possible loss of data
    src\params.cpp(1193): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'SQLUSMALLINT', signed/unsigned mismatch
    src\params.cpp(1200): warning C4365: '=': conversion from 'Py_ssize_t' to 'SQLULEN', signed/unsigned mismatch
    src\params.cpp(1420): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLSMALLINT', possible loss of data
    src\params.cpp(1430): warning C4365: 'initializing': conversion from 'SQLULEN' to 'Py_ssize_t', signed/unsigned mismatch
    src\params.cpp(1458): warning C4365: 'argument': conversion from 'SQLULEN' to 'Py_ssize_t', signed/unsigned mismatch
    src\params.cpp(1696): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLUSMALLINT', possible loss of data
    src\params.cpp(1696): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'SQLUSMALLINT', signed/unsigned mismatch
    src\params.cpp(1760): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLUSMALLINT', possible loss of data
    src\params.cpp(1760): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'SQLUSMALLINT', signed/unsigned mismatch
    src\params.cpp(1771): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLSMALLINT', possible loss of data
    src\params.cpp(1772): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLSMALLINT', possible loss of data
    src\params.cpp(1773): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLSMALLINT', possible loss of data
    src\params.cpp(1774): warning C4244: 'argument': conversion from 'Py_ssize_t' to 'SQLSMALLINT', possible loss of data
    src\params.cpp(1783): warning C4365: 'argument': conversion from 'Py_ssize_t' to 'std::size_t', signed/unsigned mismatch
    src\params.cpp(1918): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
    src\params.cpp(1926): warning C4996: 'PyUnicode_EncodeUTF8': deprecated in 3.3
    c:\python38\include\cpython/unicodeobject.h(821): note: see declaration of 'PyUnicode_EncodeUTF8'
    src\params.cpp(1929): warning C4996: 'PyUnicode_EncodeUTF16': deprecated in 3.3
    c:\python38\include\cpython/unicodeobject.h(863): note: see declaration of 'PyUnicode_EncodeUTF16'
    src\params.cpp(1932): warning C4996: 'PyUnicode_EncodeUTF16': deprecated in 3.3
    c:\python38\include\cpython/unicodeobject.h(863): note: see declaration of 'PyUnicode_EncodeUTF16'
    src\params.cpp(1935): warning C4996: 'PyUnicode_EncodeUTF16': deprecated in 3.3
    c:\python38\include\cpython/unicodeobject.h(863): note: see declaration of 'PyUnicode_EncodeUTF16'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\pyodbccompat.cpp /Fobuild\temp.win-amd64-3.8\Release\src\pyodbccompat.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    pyodbccompat.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\pyodbcdbg.cpp /Fobuild\temp.win-amd64-3.8\Release\src\pyodbcdbg.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    pyodbcdbg.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\pyodbcmodule.cpp /Fobuild\temp.win-amd64-3.8\Release\src\pyodbcmodule.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    pyodbcmodule.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\row.cpp /Fobuild\temp.win-amd64-3.8\Release\src\row.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    row.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC_VERSION=4.0.27 -Ic:\python38\include -Ic:\python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpsrc\textenc.cpp /Fobuild\temp.win-amd64-3.8\Release\src\textenc.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd4127 /wd4191
    textenc.cpp
    c:\python38\include\cpython/abstract.h(77): warning C4365: 'return': conversion from 'std::size_t' to 'Py_ssize_t', signed/unsigned mismatch
    creating C:\Users\taskrunner\AppData\Local\Temp\pip-install-4vqdclpn\pyodbc\build\lib.win-amd64-3.8
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:/usr/lib:/usr/local/lib /LIBPATH:c:\python38\libs /LIBPATH:c:\python38\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" odbc32.lib advapi32.lib /EXPORT:PyInit_pyodbc build\temp.win-amd64-3.8\Release\src\buffer.obj build\temp.win-amd64-3.8\Release\src\cnxninfo.obj build\temp.win-amd64-3.8\Release\src\connection.obj build\temp.win-amd64-3.8\Release\src\cursor.obj build\temp.win-amd64-3.8\Release\src\errors.obj build\temp.win-amd64-3.8\Release\src\getdata.obj build\temp.win-amd64-3.8\Release\src\params.obj build\temp.win-amd64-3.8\Release\src\pyodbccompat.obj build\temp.win-amd64-3.8\Release\src\pyodbcdbg.obj build\temp.win-amd64-3.8\Release\src\pyodbcmodule.obj build\temp.win-amd64-3.8\Release\src\row.obj build\temp.win-amd64-3.8\Release\src\textenc.obj /OUT:build\lib.win-amd64-3.8\pyodbc.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\src\pyodbc.cp38-win_amd64.lib
    pyodbcmodule.obj : warning LNK4197: export 'PyInit_pyodbc' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.8\Release\src\pyodbc.cp38-win_amd64.lib and object build\temp.win-amd64-3.8\Release\src\pyodbc.cp38-win_amd64.exp
    Generating code
    c:\users\taskrunner\appdata\local\temp\pip-install-4vqdclpn\pyodbc\src\params.cpp(1683) : warning C4706: assignment within conditional expression
    c:\users\taskrunner\appdata\local\temp\pip-install-4vqdclpn\pyodbc\src\params.cpp(1783) : warning C4706: assignment within conditional expression
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\taskrunner\\AppData\\Local\\Temp\\pip-install-4vqdclpn\\pyodbc\\setup.py'"'"'; __file__='"'"'C:\\Users\\taskrunner\\AppData\\Local\\Temp\\pip-install-4vqdclpn\\pyodbc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\taskrunner\AppData\Local\Temp\pip-record-wcc3z0yx\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

C:\Python38>

**Comment by v-chojas** [comment]
`LINK : fatal error LNK1158: cannot run 'rc.exe'`

Do you have an rc.exe in the same directory as the cl.exe and link.exe ?

**Comment by CRCGlobal** [comment]
I dont have RC.exe anywhere.  Is this an additional file that I need to download somewhere?  Why is none of this mentioned in the install instructions.  Crazy that I need almost 5gb of microsoft bs installed to install one tiny python extension

**Comment by CRCGlobal** [comment]
ok, I did some internet research, and it looks like RC.exe has been removed from the latest Visual C++ build tools 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/06675e6d-9a0b-46f5-8de0-10237fab1ece/link-error-lnk1158?forum=vcgeneral

the solution was to copy rc.exe and rc.bin from 
C:\Program Files (x86)\Windows Kits\8.1\bin\x86
to
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

**Comment by gordthompson** [comment]
> I need almost 5gb of microsoft bs installed to install one tiny python extension

I expect that the next pyodbc release will include pre-compiled Windows wheel files for Python 3.8.

**Comment by v-chojas** [comment]
FYI you do not need whole Visual Studio to build the pyODBC, only the compiler, which you can find here:

https://visualcpp.myget.org/feed/dailymsvc/package/nuget/VisualCppTools.Community.Daily.VS2017Layout

**Comment by PepeBorgelt** [comment]
> lude pre-compiled Windows wheel files for Python 3.8.

I need the pre-compiled version for 3.8 aswell. We dont have Visual Studio Licenses in my company, which are needed for C++ build tools. Can someone add in the release?

**Comment by gordthompson** [comment]
@PepeBorgelt - For the time being you can get the Windows wheel files for Python 3.8 from here:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc

**Comment by PepeBorgelt** [comment]
Thanks! It worked!
> 
> 
> @PepeBorgelt - For the time being you can get the Windows wheel files for Python 3.8 from here:
> 
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc

**Comment by pramodmandali** [comment]
I am getting the same error too, where should I place the wheel file in my Python folder?

**Comment by gordthompson** [comment]
@pramodmandali - You don't just drop the wheel file in your Python folder; you download it to any convenient location and then do

```
pip install \path\to\______.whl
```

**Comment by pramodmandali** [comment]
@gordthompson ..Actually I am ended up with this error below.


ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptoo
ls, tokenize; sys.argv[0] = '"'"'C:\\Users\\Krish.Mandali\\AppData\\Local\\Temp\
\3\\pip-install-l1itpowb\\pyodbc\\setup.py'"'"'; __file__='"'"'C:\\Users\\Krish.
Mandali\\AppData\\Local\\Temp\\3\\pip-install-l1itpowb\\pyodbc\\setup.py'"'"';f=
getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\
n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' i
nstall --record 'C:\Users\Krish.Mandali\AppData\Local\Temp\3\pip-record-s1wo4saa
\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Krish.Mandali\AppData\Local\Temp\3\pip-install-l1itpowb\p
yodbc\
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC
\14.23.28105\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYODBC
_VERSION=4.0.27 "-Ic:\program files\python38\include" "-Ic:\program files\python
38\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC
\Tools\MSVC\14.23.28105\include" /EHsc /Tpsrc\buffer.cpp /Fobuild\temp.win-amd64
-3.8\Release\src\buffer.obj /Wall /wd4514 /wd4820 /wd4668 /wd4711 /wd4100 /wd412
7 /wd4191
    buffer.cpp
    C:\Users\Krish.Mandali\AppData\Local\Temp\3\pip-install-l1itpowb\pyodbc\src\
pyodbc.h(19): fatal error C1083: Cannot open include file: 'windows.h': No such
file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Buil
dTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exi
t status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python
.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Kri
sh.Mandali\\AppData\\Local\\Temp\\3\\pip-install-l1itpowb\\pyodbc\\setup.py'"'"'
; __file__='"'"'C:\\Users\\Krish.Mandali\\AppData\\Local\\Temp\\3\\pip-install-l
1itpowb\\pyodbc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file_
_);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(co
de, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Krish.Mandali\AppData
\Local\Temp\3\pip-record-s1wo4saa\install-record.txt' --single-version-externall
y-managed --compile Check the logs for full command output.

**Comment by v-chojas** [comment]
See https://github.com/mkleehammer/pyodbc/issues/639
Do you have Windows SDK installed?

**Comment by gordthompson** [comment]
@pramodmandali - You are still trying to install from source. That is not necessary. Just go to

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc

and download either 

pyodbc‑4.0.27‑cp38‑cp38‑win32.whl

or

pyodbc‑4.0.27‑cp38‑cp38‑win_amd64.whl

and then use pip to install it. For example, I used

```
pip install \Users\Gord\Downloads\pyodbc‑4.0.27‑cp38‑cp38‑win32.whl
```

**Comment by adventefong** [comment]
> @pramodmandali - You are still trying to install from source. That is not necessary. Just go to
> 
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc
> 
> and download either
> 
> pyodbc‑4.0.27‑cp38‑cp38‑win32.whl
> 
> or
> 
> pyodbc‑4.0.27‑cp38‑cp38‑win_amd64.whl
> 
> and then use pip to install it. For example, I used
> 
> ```
> pip install \Users\Gord\Downloads\pyodbc‑4.0.27‑cp38‑cp38‑win32.whl
> ```

Hi there, I'm running into the same error as pramodmandali.  I tried using wheels, but I'm getting the following error:  

C:\>pip install C:\Users\EFO382\Downloads\pyodbc-4.0.27-cp27-cp27m-win_amd64.whl
ERROR: pyodbc-4.0.27-cp27-cp27m-win_amd64.whl is not a supported wheel on this platform.

C:\>pip install C:\Users\EFO382\Downloads\pyodbc-4.0.27-cp27-cp27m-win32.whl
ERROR: pyodbc-4.0.27-cp27-cp27m-win32.whl is not a supported wheel on this platform.

I am on Windows 10.  I have the latest version of python (3.8.0).  And I do have Visual Studio 2019 installed as well as the Windows SDK installed.  I tried looking around my computer to find out where the windows.h file is, and it is located in:  

C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um

Any help would be greatly appreciated!

**Comment by pramodmandali** [comment]
Installing wheel file solved my issue Thanks @gordthompson

**Comment by bkline** [comment]
> I expect that the next pyodbc release will include pre-compiled Windows wheel files for Python 3.8.

Anyone have any idea when that might happen?

**Comment by gordthompson** [comment]
@bkline - Last year [I asked @Santa for assistance](https://github.com/mkleehammer/pyodbc/pull/467#issuecomment-447166637). Maybe he'll be able to help out again this year.

**Comment by emersonjsouza** [comment]
> @pramodmandali - You are still trying to install from source. That is not necessary. Just go to
> 
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc
> 
> and download either
> 
> pyodbc‑4.0.27‑cp38‑cp38‑win32.whl
> 
> or
> 
> pyodbc‑4.0.27‑cp38‑cp38‑win_amd64.whl
> 
> and then use pip to install it. For example, I used
> 
> ```
> pip install \Users\Gord\Downloads\pyodbc‑4.0.27‑cp38‑cp38‑win32.whl
> ```

Thank you. It´s works for me :)

**Comment by mkleehammer** [comment]
There are now prebuilt Windows binaries for 2.7 & 3.6-38, both 32-bit and 64-bit.

**Comment by Sadiyakotwal** [comment]
How to install pyodbc in pycharm

**Comment by gordthompson** [comment]
@Sadiyakotwal - Are you having a problem with PyCharm installing pyodbc in particular? If so, then please open a new issue with details like the OS you're using, the steps you've taken, and the results (e.g., error messages) you get.
