### ISSUE TITLE
Documentation -> Tips and Tricks -> Column names

### ISSUE THREAD

**Issue by rubdos** [mkleehammer/pyodbc#64]
I cite:

> Of course you can always extract the value by index:
> ```
>    count = cursor.execute("select count(*) from users").fetchone()[0]
>    print('{} users'.format(row.user_count)
> ```

Should obviously be:

> Of course you can always extract the value by index:
> ```
>    count = cursor.execute("select count(*) from users").fetchone()[0]
>    print('{} users'.format(count)
> ```

on https://mkleehammer.github.io/pyodbc/ that page. I can't find where to file a pull request for it, so just leaving that here.

**Comment by mkleehammer** [comment]
Thanks.
