### ISSUE TITLE
Autocommit=False is not respected within context manager

### ISSUE THREAD

**Issue by maedox** [mkleehammer/pyodbc#643]
### Environment

- Windows Server 2016 64-bit
- Python 3.8 64-bit
- pyodbc 4.0.27
- SQL Server 10.0.6556.0
- driver: "SQL Server"

### Issue

I am connecting to the database with autocommit=False then creating cursors inside functions like this:
`with db_conn.cursor() as crsr: ...`

When running these functions and I don't explicitly either crsr.rollback() or crsr.commit(), the transaction is committed to the database.
Printing `f"{db_conn.autocommit=}"` shows it is in fact `False` inside the `with` block. 

As I read the documentation it should automatically send a rollback. What am I doing wrong?

**Comment by gordthompson** [comment]
Are you using a context manager (`with` block) when working with the cursors? If so, then that would explain the behaviour. See also #43

**Comment by maedox** [comment]
I realize that an explicit commit is needed to commit, but I was of the impression that an explicit rollback would not be required. Context manager or not. 
Doing an explicit rollback is fine, but the docs don't seem to agree with this. 

My current app is getting big, but I'll try to make a simpler one to test this. Either way I'll get rid of the context managers.

**Comment by mkleehammer** [comment]
Well, this is surprising to me too as I do this all the time, though without the with clause.

    def fun():
        cnxn = db.connect()
        cursor = cnxn.cursor()
        cursor.execute("delete from x")
        raise SystemExit('testing')

In code like this, the delete is rolled back because cursor and cnxn and cursor both have reference counts that drop to zero.  (The internals are careful to make sure the references only go one way to allow this.)

Perhaps the context is keeping a reference and the rollback just hasn't happened yet?  Or is it really commited?

**Comment by gordthompson** [comment]
@mkleehammer - The description at

https://github.com/mkleehammer/pyodbc/wiki/Connection#connection-objects-and-the-python-context-manager-syntax

seems to suggest that an implicit commit will happen if no errors occur.

**Comment by maedox** [comment]
@mkleehammer, the transaction is very much committed, because I'm checking it in SQL Management Studio.

I am setting up the connection as a global, then using that in every function. I would expect an implicit rollback when the function is finished, but I'm seeing the opposite. Perhaps it works if I also set up the connection in every function, or some sort of connection pooling class is preferred? I am doing lots of small queries and updates so creating a new connection every time would be less than ideal.

**Comment by gordthompson** [comment]
@maedox - On Windows, the ODBC driver manager supports connection pooling and it is enabled by default for Microsoft's ODBC drivers for SQL Server. So, using short-lived connections with limited scope may not be as bad as you think it is.

**Comment by v-chojas** [comment]
You can get an ODBC trace to see if it is actually pyODBC issuing commits, or perhaps something with the driver.
Note that the `SQL Server` ODBC driver is very old (I believe it originates from SQL 6.x/7.x), you could see if the same behaviour occurs with the latest `ODBC Driver 17 for SQL Server`: https://www.microsoft.com/en-us/download/details.aspx?id=56567

**Comment by gordthompson** [comment]
Apologies. My earlier comment re: the wiki entry was confusing the two cases:

1. context manager on a Connection object
2. context manager on a Cursor of an existing Connection object

### 1. context manager on a Connection object

This code ...

```python
print(f'driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
# driver: msodbcsql17.dll version 17.04.0001

print(f'server: {cnxn.getinfo(pyodbc.SQL_DBMS_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DBMS_VER)}')
# server: Microsoft SQL Server, version: 14.00.2027

print(cnxn.autocommit)  # False

with cnxn.cursor() as crsr:
    sql = "INSERT INTO issue643 (txt) VALUES (?)"
    crsr.execute(sql, datetime.datetime.now())
    print('exit "with" without commit() ...')
```

... causes pyodbc to call `SQLEndTran` twice

**with.LOG:513**

```
main            1f78-1144   EXIT  SQLEndTran  with return code 0 (SQL_SUCCESS)
        SQLSMALLINT                  2 <SQL_HANDLE_DBC>
        SQLHANDLE           0x008077E8
        SQLSMALLINT                  0 
```

**with.LOG:539**

```
main            1f78-1144   EXIT  SQLEndTran  with return code 0 (SQL_SUCCESS)
        SQLSMALLINT                  2 <SQL_HANDLE_DBC>
        SQLHANDLE           0x008077E8
        SQLSMALLINT                  1 
```

[with.LOG](https://github.com/mkleehammer/pyodbc/files/3812075/with.LOG)

... and the change IS committed.

### 2. context manager on a Cursor of an existing Connection object

Replacing the `with` block with the following ...

```python
crsr = cnxn.cursor()
sql = "INSERT INTO issue643 (txt) VALUES (?)"
crsr.execute(sql, datetime.datetime.now())
print('closing cursor without commit() ...')
crsr.close()
```
... causes pyodbc to only call `SQLEndTran` once ...

**without.LOG:529**

```
main            1cac-10bc   EXIT  SQLEndTran  with return code 0 (SQL_SUCCESS)
        SQLSMALLINT                  2 <SQL_HANDLE_DBC>
        SQLHANDLE           0x012577E8
        SQLSMALLINT                  1 
```

[without.LOG](https://github.com/mkleehammer/pyodbc/files/3812078/without.LOG)

... and the change is NOT committed.

**Comment by keitherskine** [comment]
@maedox As you have observed, the pyodbc context managers do force a commit even when `autocommit` is False, and yes, that is somewhat counter-intuitive (although this behaviour appears to be the way other python ODBC modules operate, see #43 for examples).  This is why I personally don't use pyodbc context managers.  If I need them, I write my own.

**Comment by maedox** [comment]
The fact that the context manager way behaves differently is very confusing. This is a bug in my opinion. At least a docs bug.

@gordthompson, thank you for your thorough testing. So I'm not crazy! 😄 

I have installed the latest ODBC driver and am not taking any chances. I like to be explicit anyway, so I got rid of the context manager and create a new connection and cursor in any function dealing with them.
So far so good.

**Comment by keitherskine** [comment]
Wiki entries for connections and cursors have been updated [here ](https://github.com/mkleehammer/pyodbc/wiki/Connection#context-manager) and [here](https://github.com/mkleehammer/pyodbc/wiki/Cursor#context-manager).  Hopefully this clarifies the context managers.

**Comment by alexlambson** [comment]
The way the context manager behaves makes it very difficult to make sure data isn't persisted between test runs. 

We have it setup to roll back changes when tests are cleaned up, but if anywhere in our code uses `with connection.cursor() as cursor:` then all of our fixtures get persisted.

**Comment by keitherskine** [comment]
@alexlambson  The built-in context managers for [connections](https://github.com/mkleehammer/pyodbc/wiki/Connection#context-manager) and [cursors](https://github.com/mkleehammer/pyodbc/wiki/Cursor#context-manager) have very specific behaviours.  If that is not the behaviour you need (and it often isn't) then you can always build your own.  For example:
https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager
I do this regularly.
