### ISSUE TITLE
Jupyterhub kernel died when using pyodbc 

### ISSUE THREAD

**Issue by DimaKluchnikov** [mkleehammer/pyodbc#646]
I use the same env in Jupyterhub and in Jupyter notebook, but in Jupyterhub kernel dies on following line of code:
`import pyodbc`
`conn = pyodbc.connect('DSN=mydnsname',CHARSET='UTF8')`

**Comment by gordthompson** [comment]
Are you really trying to do the`import` and the `connect` on the same line, or is that just a formatting issue in your post?

**Comment by DimaKluchnikov** [comment]
that was a a formatting issue

**Comment by v-chojas** [comment]
Could you provide more information about your environment, including an ODBC trace?
