### ISSUE TITLE
SQL Server Error when using "USE" statement

### ISSUE THREAD

**Issue by spmunc** [mkleehammer/pyodbc#647]
I am using Windows 10, python 3.5, pyodbc 4.0.27 and connecting using the ODBC Driver 17 for SQL Server. 

When there is a `USE <DB_NAME>` statement in the query, pydobc returns the error:

`pyodbc.ProgrammingError: No results.  Previous SQL was not a query.`

Usually when this error occurs it is due to having multiple selects, so I can use `SET NOCOUNT ON;` and it works just fine. This does not work with `USE`. I am able to use `USE` statements when using the python package `pymssql` and the correct resultset is returned. 

I know that I can (1) specify an initial database in the connection string or (2) call `nextset()` before attempting to get data. Neither of these work in my particular case because (1) the calling code doesn't know the db specified in the injected connection string and (2) the data is being read into a pandas data frame using `read_sql`. 

Is there a way for pyodbc to return the correct result set in SQL Server when there is a `USE` statement in the query.

**Comment by mkleehammer** [comment]
I can't think of a way to intelligently do that automatically.   (Suggestions are, of course, welcome.)

However, it might be possible to have a *setting*, both global and per cursor, to have `nextset` called automatically, repeatedly, until a result set is found or we run out.  If we run out, we would still have to raise the same error.

For backwards compatibility, the setting would need to be default to off, but I think it would make sense to default it to on in v5 and above.

Does anyone see problems with this?

**Comment by spmunc** [comment]
Thanks for the very quick response. A setting of this sort would be great for me as I only ever need 1 (the last) result set. In the meantime, I have worked around the issue by just re-connecting with a modified version of the the injected conn string to have the database that I need. Just posted issue here in case others come across this.

**Comment by tweakimp** [comment]
You can use a `While True` loop to call the next result set until you get no error trying to fetch the result. Be sure to break when next set returns `False`.
Something like this:
```python
while True:
    try:
        # try to fetch
        result = cursor.fetchall()
        return result
    except pyodbc.ProgrammingError:
        # couldnt fetch, are there other results?
        if cursor.nextset() is False:
            # no other results, return None?
            return None
        else:
            # there are other results, try again with next result set
            continue
```

**Comment by gordthompson** [comment]
@spmunc - Is the formatting of the SQL text sufficiently consistent that you can reliably parse out the USE statement, execute that first, and then pass the rest of the string on to `read_sql`?

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
