### ISSUE TITLE
how to insert python line to mssql ?

### ISSUE THREAD

**Issue by ericwang321** [mkleehammer/pyodbc#653]
**1. Environment:**

- Python: Python 3.6.8 
- pyodbc: pip3 install pyodbc   #pyodbc-4.0.27 
- OS: ubuntu 18.04 64bit
- DB:windows server 2012 R2 MSSQL 2012
- driver:Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1

**2. Issue**
  p3.py
```
import pyodbc 

list1 = ['2019-10-14 10:48:45,3,n12,/home/toor/1_192.168.1.2_191013104845_33.jpg',
'2019-10-14 10:48:45,3,n12,/home/toor/1_192.168.1.2_191013104845_33.jpg',
'2019-10-14 10:48:45,3,n12,/home/toor/1_192.168.1.2_191013104845_33.jpg']

conn = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                    'Server=192.168.1.10;'
                    'Database=tms;'
                    'Trusted_Connection=no;'
		     'UID=tmsdb;'
		      'PWD=123')
cursor = conn1.cursor()
sqlconn = "insert into tmsdb.dbo.ip2(time,cnt,ip,path),VALUES(? ,? ,? ,?)"
number = cursor.executemany(sqlconn,list1)
conn.commit()
```
when run python3 p3.py,the following error is displayed
> Traceback (most recent call last):
>   File "p3.py", line 29, in <module>
>     number = cursor.executemany(sqlconn,list1)
> TypeError: ('**_Params must be in a list, tuple, or Row', 'HY000'_**

Google multiple documents, changes many times, still gives an error,how deal with it?
Thanks for any suggestion.

**Comment by gordthompson** [comment]
Your `list1` is a list of scalar (`str`) values. `executemany` expects `list1` to be a list of lists, tuples, or Rows. Since your `str` values appear to be comma-separated I suspect that what you really want is

```python
list1 = [
    ('2019-10-14 10:48:45',3,'n12','/home/toor/1_192.168.1.2_191013104845_33.jpg'),
    ('2019-10-14 10:48:45',3,'n12','/home/toor/1_192.168.1.2_191013104845_33.jpg'),
    ('2019-10-14 10:48:45',3,'n12','/home/toor/1_192.168.1.2_191013104845_33.jpg'),
    ]
```

**Comment by ericwang321** [comment]
**Thank you for your reply**
That ’s it. I corrected it and it **_works_**.
