### ISSUE TITLE
libodbc.so.2: cannot open shared object file: No such file or directory (in aws lambda)

### ISSUE THREAD

**Issue by almahmudshahjahan** [mkleehammer/pyodbc#654]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.27
- OS: unix
- DB: ms sql server on aws rds
- driver:

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

Lambda is unable to import main module using pyodbc after successful circle ci package deploy using pip and venv

**Comment by v-chojas** [comment]
You need to install unixODBC.

**Comment by almahmudshahjahan** [comment]
Thanks, this is already part of the pyodbc Python package install for lambda; does the Unix odbc also need to be packed up into the lambda ?

**Comment by v-makouz** [comment]
Yes, according to the install documents, Unix ODBC is needed for pyODBC to work on Linux:
https://github.com/mkleehammer/pyodbc/wiki/Install

**Comment by almahmudshahjahan** [comment]
So is there a zip package for that to include with the Python lambda? didn’t see that in the instructions

**Comment by v-makouz** [comment]
Can you describe your setup a bit more? Like what's the OS and what exactly do you do in order to install pyODBC in the first place?

If the machine uses pip install for pyODBC, can it not also use a package manger to install unixODBC in the same manner? (i.e. `sudo apt install unixodbc-dev` for example)

I'm afraid I'm not familiar with Lambdas and how exactly they function, but it seems like if it can install pyODBC it should be able to install unixODBC in a similar manner

**Comment by v-makouz** [comment]
I found this set of instructions, that includes how to install unixODBC on AWS Lambda:
https://medium.com/faun/aws-lambda-microsoft-sql-server-how-to-66c5f9d275ed

As I said, I don't have any experience with those, so I can't vouch for this article, but hopefully it can help

**Comment by almahmudshahjahan** [comment]
Thanks for your note.  I saw the article as well but it seems overly complex to include this package with a Python lambda and refers to an earlier version of Python.  I am using pip to pull in pyodbc on a Linux image in circle ci with Python 3.6 which does make use of unixodbc during the packaging process. somehow reference to the file mentioned in the issue seems to be off.  So I am trying to resolve to be able to use the package. If there is a zip available for Python 3.6 that would be a great help.

**Comment by almahmudshahjahan** [comment]
thanks for your pointers. i was able to load up in a lambda layer using python 3.7; versions are important--python 3.8 doesn't like it; the instructions are useful but the final step was needed to update the driver in the config files 

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1
UsageCount=1
