### ISSUE TITLE
https://github.com/mkleehammer/pyodbc/wiki/Calling-Stored-Procedures

### ISSUE THREAD

**Issue by almahmudshahjahan** [mkleehammer/pyodbc#656]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7
- pyodbc: 
- OS: Lambda/Unix
- DB: MS SQL 2017
- driver: 

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".
I'm running into an issue getting a return value from a stored procedure that takes 2 inputs, one nullable and with a bit output (Stored Procedure and python code snippet below; the Decision is a bit that's all I need back from the result set)

Expected Behavior:
 . Stored Procedure resultset return

Observed Behavior
No resultset

create PROCEDURE [sampleDataRead]
(
	@p_Id INT 
	@m_Id VARCHAR 
)  
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER  AS  BEGIN  ATOMIC WITH   
(  TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = 'english')

  SELECT 
	col1, 
        col2,
	Decision
  FROM 
	Table1 
  WHERE
	        @p_Id= col1 AND @m_Id= col2
END  
GO

in python code
    cn = pyodbc.connect(connstring)
    crs = cn.cursor()
    id = 'TestId'
    prm = (id)
    sql = """\
    DECLARE @rv bit;
    EXEC @rv = [sampleDataRead] @p_Id=NULL, @m_Id  = ?;
    SELECT @rv AS return_value;
    """
    crs.execute(sql, prm)
    return_value = crs.fetchval()

**Comment by v-makouz** [comment]
I'm going to try to reproduce this, but how do I create the `Table1`, what's the schema, and does it need any data to repro?

Also which version of unixODBC do you use (`odbcinst -j`)?

**Comment by gordthompson** [comment]
@almahmudshahjahan - Is `Table1.col2` a `varchar(1)` column? Your SP declares an input parameter as `@m_Id VARCHAR` and sometimes T-SQL interprets an unqualified `VARCHAR` as `VARCHAR(1)`. If you pass 'Gord' as an argument then `@m_Id` might just contain `G`.

**Comment by almahmudshahjahan** [comment]
@v-makouz thanks
unixODBC-2.3.7
we're using inmemory tables, base schema below; left out some additional cols to simplify
 
@gordthompson, nope more than one; funny thing is that when i call the sp from code, i get a null resultset, no errors



USE [someDB];
GO
/****** Object:  Table1   Script Date: 8/16/2019 9:47:27 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE Table1
(      rowid int NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[OId] [varchar](45) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OIdType] [int] NOT NULL,
	col2 [VARCHAR] NOT NULL,
	col1 [int] NOT NULL,
	Decision [bit] NULL,

INDEX [IX_OId] NONCLUSTERED HASH 
(
	[OId]
)WITH ( BUCKET_COUNT = 131072),
INDEX [IX_PolicyTextVersionId] NONCLUSTERED HASH 
(
	[col1]
)WITH ( BUCKET_COUNT = 131072),
 PRIMARY KEY NONCLUSTERED 
(
	[DataShareAgreementId] ASC
)
)WITH ( MEMORY_OPTIMIZED = ON , DURABILITY = SCHEMA_AND_DATA )
GO


create PROCEDURE [sampleDataRead]
(
	@Id INT 
	@pId VARCHAR 
)  
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER  
AS 
BEGIN  ATOMIC WITH   
(  TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = 'english')

  SELECT 
	col1, 
        col2,
	Decision
  FROM 
	Table1 
  WHERE
	    @Id	= col1
	AND @pId= col2
  
END  
GO

**Comment by gordthompson** [comment]
@almahmudshahjahan 

```
1> SELECT @@VERSION;
2> go

----------------------------------------------------------------------------
Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64)
        Jun 15 2019 00:26:19
        Copyright (C) 2017 Microsoft Corporation
        Express Edition (64-bit) on Windows 8.1 Pro 6.3 <X64> (Build 9600: )

(1 rows affected)
1> CREATE TABLE qweasd (id int PRIMARY KEY, vc VARCHAR);
2> go
1> SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'qweasd';
2> go
TABLE_NAME  COLUMN_NAME  DATA_TYPE  CHARACTER_MAXIMUM_LENGTH
----------  -----------  ---------  ------------------------
qweasd      id           int                            NULL
qweasd      vc           varchar                           1

(2 rows affected)
1> DROP TABLE qweasd;
2> go
```

**Comment by v-makouz** [comment]
It seems like when I try to create the stored procedure I get the following error:
`Cannot schema bind procedure 'sampleDataRead' because name 'Table1' is invalid for schema binding. Names must be in two-part format and an object cannot reference itself.`

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
