### ISSUE TITLE
SQL server enterprise 2016: ssl provider: packet size too large for ssl encrypt/decrypt operation

### ISSUE THREAD

**Issue by PrithaDalmia** [mkleehammer/pyodbc#657]
### Environment

To diagnose, we usually need to know the following, including version numbers. On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.9
- pyodbc: 4.0.27
- OS:  Windows Server 64 Bit
- DB: Windows Server 2016 Enterprise
- driver: ODBC 17

### Issue
The connection strings are as follows:

```
params1 = urllib.parse.quote_plus("driver={ODBC Driver 17 for SQL Server};server=LP-MUM-01-00032;database=XX_XX_XX;Uid=Pritha;Pwd=;Encrypt=yes;TrustServerCertificate=yes,Connection Timeout=30;")
engine2 = create_engine('mssql+pyodbc:///?odbc_connect={}'.format(params1), fast_executemany=True)

```
While uploading a large file (50 MB, 500,000 records) using fast_executemany to the database using the application UI, the following error is coming:
`"ssl provider: packet size too large for ssl encrypt/decrypt operation".`

I have tried to include "Packet Size = 400000000" to the connection string without avail.

Any guidance would be appreciate.

**Comment by v-makouz** [comment]
Looking at the error it may have to do with DB configuration rather then the drivers. I'm not familiar with this problem, but there is some discussion here:
https://social.technet.microsoft.com/Forums/en-US/d8d5f455-9769-4f9b-80c7-f5761434bd6b/ssl-providerpacket-size-too-large-for-ssl-encryptdecrypt-operation?forum=sqlintegrationservices
They suggest setting packet size smaller (16383) maybe it'll be of help

"Packet Size" is not a valid ODBC connection string keyword (and neither is "Connection Timeout"), so it wouldn't have any effect. Here is the doc on the connection string keywords:
https://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver15

**Comment by mkleehammer** [comment]
I'm marking this as a driver / environment issue for now.  Any more results on this @PrithaDalmia ?

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
