### ISSUE TITLE
"ProgrammingError" ('Type mismatch between TVP row values', 'HY000')

### ISSUE THREAD

**Issue by Lijo-CheeranJoseph** [mkleehammer/pyodbc#659]
I have following working code that successfully inserted 10K records into SQL Server using Table Valued Parameter (TVP). When I run the code with 400K records, I got error "_**"ProgrammingError" ('Type mismatch between TVP row values', 'HY000')**_".  How to resolve this?

import pyodbc 
from datetime import datetime

def main():
    
  now_MainStart = datetime.now()
  print(now_MainStart)

  f = open('C:/Source/test_public.pem', 'rb')
  f1 = open('C:/Source/test_private.pem', 'rb')
  public = RSA.importKey(f.read())
  private = RSA.importKey(f1.read())
    
  cnxn = pyodbc.connect("Driver={ODBC Driver 13 for SQL Server};Server=dataserver;UID=UserName;PWD=Passwrd;Database=MySQLServerDB;")
  dfInput = pd.read_sql('exec dbo.usp_Temp_GetAllUsers ?', cnxn, params=['None'] )
    
  df_Store = pd.DataFrame(columns=['PatientText', 'EncryptedResult'])

  for index, row in  dfInput.iterrows():
    y = row['PatientText']
    message = base64.b64encode(y.encode("utf-8"))
    dataNew = base64.b64decode(message)
    
    encoded = my_encrypt(dataNew, public)
    decryptedResult = decrypt_New(encoded, private)
    
    df_Store = df_Store.append({'PatientText': y, 'EncryptedResult': encoded}, ignore_index=True)
           
  now_EncryptionDone = datetime.now() 
  print(now_EncryptionDone)

  try:
    cursor = cnxn.cursor()
    result_array = cursor.execute("EXEC dbo.usp_InsertUsers ?", [df_Store.values]).fetchall()
    cursor.commit()  #very important to commit
    #print(result_array)
    
    now_UpdateDone = datetime.now()
    print(now_UpdateDone)
    
  except Exception as ex:
    print("Failed to execute SP with TVPt")
    print("Exception: [" + type(ex).__name__ + "]", ex.args)

if __name__== "__main__":
  main()

**Comment by gordthompson** [comment]
Possibly related: #596

**Comment by mkleehammer** [comment]
Now that #596 is closed, is this still happening @Lijo-CheeranJoseph ?

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
