### ISSUE TITLE
4.0.28 Release Request

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#660]
@mkleehammer - Please consider a 4.0.28 "holiday release" to provide Python 3.8 wheels (#638) and the fix for #596.

**Comment by matthew-black** [comment]
While we're on holiday wishes, I'd be overjoyed to wake up to falling snow and a carefully wrapped box that contains a release that #652 has been merged into. :)

**Comment by mkleehammer** [comment]
On a related note, 2020 is a good time to release 5.0 with Python 3.x stable ABI so it can be used on any new versions.  I will try to keep up with releases but I've been under the weather for quite a while.  Back on my feet now.

**Comment by gordthompson** [comment]
Thanks. Does "release 5.0 with Python 3.x stable ABI so it can be used on any new versions" mean that you would no longer have to do separate builds for cp37, cp38, etc.?

**Comment by mkleehammer** [comment]
@gordthompson That is the expectation.  A single binary wheel for all 3.x and above such as 3.5 or so.  I would maintain the 4.x line for fixes but not add any new features to it.

**Comment by gordthompson** [comment]
@mkleehammer - I notice that https://pypi.org/project/pyodbc/#files for 4.0.28 does not include Windows wheels for 32-bit Python. Was that intentional?

**Comment by mkleehammer** [comment]
I am using a different laptop for Windows builds and forgot to setup a virtual environment for it.  I didn’t setup any 32-but it looks like.  I’ll correct that when I get a chance, but Christmas wil make it difficult to get to

**Comment by daybarr** [comment]
For those following this issue, the Windows wheels were uploaded for this 4.0.28 release on December 26th. https://pypi.org/project/pyodbc/4.0.28/#files

👍 thanks @mkleehammer
