### ISSUE TITLE
No matching distribution found for pyobdc==virtuoso-2.1.9-beta1

### ISSUE THREAD

**Issue by donttal** [mkleehammer/pyodbc#661]
when I want to install virtuoso using pip
the Error is appear：
`Collecting pyodbc==virtuoso-2.1.9-beta14 (from virtuoso)
  Could not find a version that satisfies the requirement pyodbc==virtuoso-2.1.9-beta14 (from virtuoso) (from versions: 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 3.0.3, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.1.1, 4.0.1, 4.0.2, 4.0.3, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.24, 4.0.25, 4.0.26, 4.0.27)
No matching distribution found for pyodbc==virtuoso-2.1.9-beta14 (from virtuoso)
`
Then pip install pyobdc==virtuoso-2.1.9-beta14

**ERROR: Could not find a version that satisfies the requirement pyobdc==virtuoso-2.1.9-beta14 (from versions: none)**

how can I get this requirement version？？？Or other  method

**Comment by gordthompson** [comment]
You are trying to install a package that was last updated almost nine (9) years ago. According to the documentation it requires a patch to a (presumably) very old version of pyodbc ...

> At the time of this writing it requires a patch for pyodbc as documented in: http://river.styx.org/ww/2010/10/pyodbc-spasql/index

... however that page is long gone.

You could try downloading the [.tar.gz file](https://files.pythonhosted.org/packages/95/3b/110a435f7bed5e9dbade1a6f213ddb98352a70524e92a09ddc2e5df0a59f/virtuoso-0.12.6.tar.gz), remove the

```python
"pyodbc==virtuoso-2.1.9-beta14"
```

line from setup.py and then see if 

```
pip install /path/to/where/you/unpacked/the/distribution
```

will install it for you.
