### ISSUE TITLE
extra '<EOF>' added to SQL statements for Hive

### ISSUE THREAD

**Issue by zpz** [mkleehammer/pyodbc#662]
- Python:  3.6.8
- pyodbc: 4.0.27
- OS:         ubuntu 18.04
- DB:         Hive 0.13
- driver:    Hortonworks ODBC driver for Hive downloaded at http://public-repo-1.hortonworks.com/HDP/hive-odbc/2.1.2.1002/debian/hive-odbc-native_2.1.2.1002-2_amd64.deb

### Issue

connected with 

```
pyodbc.connect('host=abc', driver='...', 
                    HiveServerType=2,
                    port=10000,,
                    uid='username',
                    password='password',
                    AuthMech=3,
                    ssl=1,
                    AllowSelfSignedServerCert=1,
                    AutoCommit=1,
                    UseNativeQuery=1,
)
```

Obtained cursor. Then

```
cursor.execute('show databases')
```

returns

```
>>> hh._cursor.execute("show databases")                                                                                            
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY000', "[HY000] [Hortonworks][Hardy] (80) Syntax or semantic analysis error thrown in server while execurint query. Error message from server: Error while compiling statement: FAILED: ParseException line 1:14 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' (80) (SQLExecDirectW)")

('HY000', "[HY000] [Hortonworks][Hardy] (80) Syntax or semantic analysis error thrown in server while execurint query. Error message from server: Error while compiling statement: FAILED: ParseException line 1:14 cannot recognize input near '<EOF>' '<EOF>' '<EOF>' (80) (SQLExecDirectW)")
>>>  
```

**Comment by gordthompson** [comment]
In a terminal wondow, use the command `nano -w ~/.odbc.ini` to create a file for user DSNs and then put the following content in that file:

```
[myHiveTest]
driver=...
host=abc
HiveServerType=2
port=10000
uid=yourusername
password=yourpassword
AuthMech=3
ssl=1
AllowSelfSignedServerCert=1
AutoCommit=1
UseNativeQuery=1
```

Then use the command

```
isql myHiveTest yourusername yourpassword -v
```

to connect to the server. If successful, then at the `SQL>` prompt issue the command

```
show databases
```

Do you get the same error as when you try to use pyodbc?

**Comment by zpz** [comment]
Yes, `isql` works fine both for `UseNativeQuery=1` and `UseNativeQuery=0`

**Comment by gordthompson** [comment]
What version of unixODBC are you using? You can use `odbcinst -j` to check.

**Comment by zpz** [comment]
```
$ odbcinst -j
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /etc/odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

**Comment by zpz** [comment]
`pyodbc` 4.0.28, 4.0.24 have the same problem. 4.0.16, 3.1.1 have worse problems ("stack smashing detected").

**Comment by zpz** [comment]
I just tested `turbodbc`. `show databases;` has passed. I've yet to see how well it works overall.

**Comment by gordthompson** [comment]
Can you provide an [ODBC trace](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) from a failed attempt using pyodbc, preferably pyodbc 4.0.28?

**Comment by gordthompson** [comment]
You could also set the Unicode encoding/decoding to UTF-8 as described [here](https://github.com/mkleehammer/pyodbc/wiki/Unicode#mysql-and-postgresql) (for MySQL and PostgreSQL, but can be applicable to other drivers as well).

**Comment by mkleehammer** [comment]
First, please test with UseUnicodeSqlCharacterTypes=1 also.  It's documentation indicates it refers to data sent *from* the database, but it would not surprise me if it also affected data being sent to it.

Second, as gordthompson mentioned, setting the Unicode encoding correctly is probably necessary.  The (Unicode)[https://github.com/mkleehammer/pyodbc/wiki/Unicode] wiki page explains the details.  The best thing is to find out what encoding the driver is using.  I didn't find it with a quick Google search but maybe you have a support contact.  If you can't, try UTF-8 configuration detailed in the link gordthompson provided.

**Comment by zpz** [comment]
Will try these ideas in a few days. Thanks for helping.

**Comment by mkleehammer** [comment]
Any feedback @zpz ?

**Comment by hrpomrx** [comment]
I was seeing this same issue also, today. Will try the mentioned suggestions tomorrow morning and feedback.

**Comment by hrpomrx** [comment]
FYI: Setting the encoding, as suggested by gordthompson, fixed it for me:

`# Python 3.x
cnxn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
cnxn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
cnxn.setencoding(encoding='utf-8')`

**Comment by zpz** [comment]
I will try this encoding setting. `turbodbc` has been working for me, so haven't got the time to dig deep here. But I may revisit `pyodbc` in order to use `aioodbc`, which is based on `pyodbc`.

**Comment by zpz** [comment]
setting encoding solved the Hive issue for me. thanks.
