### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured exception with the latest 4.0.28 release

### ISSUE THREAD

**Issue by tommckennon** [mkleehammer/pyodbc#666]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.3
- pyodbc: 4.0.28 (latest release)
- OS: Windows 10
- DB: Microsoft SQL Server 2017 
- driver: ODBC Driver 17 for SQL Server
- Django: 2.2 LTS

### Issue

With the above specifications, the latest 4.0.28 release causes the following exception in Django 2.2 LTS version:
**django.core.exceptions.ImproperlyConfigured: Error loading pyodbc module: DLL load failed: The specified module could not be found.** 

I had to downgrade to the previous version of pyodbc 4.0.27 in order to resolve this issue.

**Comment by gordthompson** [comment]
Related: #663

**Comment by cheenamalhotra** [comment]
@tommckennon 

Installing latest "**Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, 2019**" shall resolve the issue as confirmed by @gordthompson in https://github.com/mkleehammer/pyodbc/issues/663#issuecomment-569365502.

You may not need to downgrade pyodbc version. Please try and confirm the same!

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
