### ISSUE TITLE
PyPy3.6 on OSX - Failed to build pyodbc

### ISSUE THREAD

**Issue by hayneshealthcare** [mkleehammer/pyodbc#672]
# Environment  
OSX 10.14.6
PyPy3.6-v7.3.0-osx64

### Issue
All other pip installs are compiling without error.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(base) Matts-MacBook-Pro-2:bin Matt$ ./pip3.6 install pyodbc
Collecting pyodbc
  Downloading https://files.pythonhosted.org/packages/31/14/124da4b15df927c8a9192c44a42523e289e5a815acd437fd5ce5c2cbc515/pyodbc-4.0.28.tar.gz (264kB)
     |████████████████████████████████| 266kB 2.1MB/s
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-wheel-mf_3rni6 --python-tag pp373
       cwd: /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pyodbc' extension
  creating build
  creating build/temp.macosx-10.14-x86_64-3.6
  creating build/temp.macosx-10.14-x86_64-3.6/src
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/buffer.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/cnxninfo.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/cnxninfo.o -Wno-write-strings -Wno-deprecated-declarations
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/connection.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/connection.o -Wno-write-strings -Wno-deprecated-declarations
  src/connection.cpp:91:29: error: conversion from 'Object' to 'void *' is ambiguous
          if (PyUnicode_Check(encoding))
                              ^~~~~~~~
  src/wrapper.h:55:5: note: candidate function
      operator PyObject*()
      ^
  src/wrapper.h:60:5: note: candidate function
      operator PyVarObject*() { return (PyVarObject*)p; }
      ^
  /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
  PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                         ^
  src/connection.cpp:194:24: error: use of undeclared identifier 'PyCodec_Encode'
          stringholder = PyCodec_Encode(value, strencoding ? strencoding : "utf-16le", "strict");
                         ^
  src/connection.cpp:266:30: error: conversion from 'Object' to 'void *' is ambiguous
              (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                               ^~~~~~~~
  src/wrapper.h:55:5: note: candidate function
      operator PyObject*()
      ^
  src/wrapper.h:60:5: note: candidate function
      operator PyVarObject*() { return (PyVarObject*)p; }
      ^
  /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
  PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                         ^
  src/connection.cpp:266:76: error: use of undeclared identifier 'PyCodec_Encode'
              (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                                                             ^
  src/connection.cpp:1371:10: error: use of undeclared identifier 'PyCodec_KnownEncoding'
      if (!PyCodec_KnownEncoding(encoding))
           ^
  5 errors generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc
    Running setup.py install for pyodbc ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-record-bowkithw/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/
    Complete output (45 lines):
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build/temp.macosx-10.14-x86_64-3.6
    creating build/temp.macosx-10.14-x86_64-3.6/src
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/buffer.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/cnxninfo.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/cnxninfo.o -Wno-write-strings -Wno-deprecated-declarations
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/connection.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/connection.o -Wno-write-strings -Wno-deprecated-declarations
    src/connection.cpp:91:29: error: conversion from 'Object' to 'void *' is ambiguous
            if (PyUnicode_Check(encoding))
                                ^~~~~~~~
    src/wrapper.h:55:5: note: candidate function
        operator PyObject*()
        ^
    src/wrapper.h:60:5: note: candidate function
        operator PyVarObject*() { return (PyVarObject*)p; }
        ^
    /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
    PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                           ^
    src/connection.cpp:194:24: error: use of undeclared identifier 'PyCodec_Encode'
            stringholder = PyCodec_Encode(value, strencoding ? strencoding : "utf-16le", "strict");
                           ^
    src/connection.cpp:266:30: error: conversion from 'Object' to 'void *' is ambiguous
                (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                 ^~~~~~~~
    src/wrapper.h:55:5: note: candidate function
        operator PyObject*()
        ^
    src/wrapper.h:60:5: note: candidate function
        operator PyVarObject*() { return (PyVarObject*)p; }
        ^
    /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
    PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                           ^
    src/connection.cpp:266:76: error: use of undeclared identifier 'PyCodec_Encode'
                (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                                                               ^
    src/connection.cpp:1371:10: error: use of undeclared identifier 'PyCodec_KnownEncoding'
        if (!PyCodec_KnownEncoding(encoding))
             ^
    5 errors generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-r08mcq_u/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-record-bowkithw/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
(base) Matts-MacBook-Pro-2:bin Matt$ ls
chardetect		iptest3			jupyter			jupyter-migrate		libpypy3-c.dylib	pip3.6			wheel
easy_install-3.6	ipython			jupyter-kernel		jupyter-run		pip			pygmentize
iptest			ipython3		jupyter-kernelspec	jupyter-troubleshoot	pip3			pypy3
(base) Matts-MacBook-Pro-2:bin Matt$ ./pip install pyodbc
Collecting pyodbc
  Using cached https://files.pythonhosted.org/packages/31/14/124da4b15df927c8a9192c44a42523e289e5a815acd437fd5ce5c2cbc515/pyodbc-4.0.28.tar.gz
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-wheel-r5np00k6 --python-tag pp373
       cwd: /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pyodbc' extension
  creating build
  creating build/temp.macosx-10.14-x86_64-3.6
  creating build/temp.macosx-10.14-x86_64-3.6/src
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/buffer.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/cnxninfo.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/cnxninfo.o -Wno-write-strings -Wno-deprecated-declarations
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/connection.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/connection.o -Wno-write-strings -Wno-deprecated-declarations
  src/connection.cpp:91:29: error: conversion from 'Object' to 'void *' is ambiguous
          if (PyUnicode_Check(encoding))
                              ^~~~~~~~
  src/wrapper.h:55:5: note: candidate function
      operator PyObject*()
      ^
  src/wrapper.h:60:5: note: candidate function
      operator PyVarObject*() { return (PyVarObject*)p; }
      ^
  /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
  PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                         ^
  src/connection.cpp:194:24: error: use of undeclared identifier 'PyCodec_Encode'
          stringholder = PyCodec_Encode(value, strencoding ? strencoding : "utf-16le", "strict");
                         ^
  src/connection.cpp:266:30: error: conversion from 'Object' to 'void *' is ambiguous
              (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                               ^~~~~~~~
  src/wrapper.h:55:5: note: candidate function
      operator PyObject*()
      ^
  src/wrapper.h:60:5: note: candidate function
      operator PyVarObject*() { return (PyVarObject*)p; }
      ^
  /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
  PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                         ^
  src/connection.cpp:266:76: error: use of undeclared identifier 'PyCodec_Encode'
              (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                                                             ^
  src/connection.cpp:1371:10: error: use of undeclared identifier 'PyCodec_KnownEncoding'
      if (!PyCodec_KnownEncoding(encoding))
           ^
  5 errors generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc
    Running setup.py install for pyodbc ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-record-ehmizhpb/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/
    Complete output (45 lines):
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build/temp.macosx-10.14-x86_64-3.6
    creating build/temp.macosx-10.14-x86_64-3.6/src
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/buffer.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/cnxninfo.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/cnxninfo.o -Wno-write-strings -Wno-deprecated-declarations
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.28 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/connection.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/connection.o -Wno-write-strings -Wno-deprecated-declarations
    src/connection.cpp:91:29: error: conversion from 'Object' to 'void *' is ambiguous
            if (PyUnicode_Check(encoding))
                                ^~~~~~~~
    src/wrapper.h:55:5: note: candidate function
        operator PyObject*()
        ^
    src/wrapper.h:60:5: note: candidate function
        operator PyVarObject*() { return (PyVarObject*)p; }
        ^
    /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
    PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                           ^
    src/connection.cpp:194:24: error: use of undeclared identifier 'PyCodec_Encode'
            stringholder = PyCodec_Encode(value, strencoding ? strencoding : "utf-16le", "strict");
                           ^
    src/connection.cpp:266:30: error: conversion from 'Object' to 'void *' is ambiguous
                (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                 ^~~~~~~~
    src/wrapper.h:55:5: note: candidate function
        operator PyObject*()
        ^
    src/wrapper.h:60:5: note: candidate function
        operator PyVarObject*() { return (PyVarObject*)p; }
        ^
    /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
    PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                           ^
    src/connection.cpp:266:76: error: use of undeclared identifier 'PyCodec_Encode'
                (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                                                               ^
    src/connection.cpp:1371:10: error: use of undeclared identifier 'PyCodec_KnownEncoding'
        if (!PyCodec_KnownEncoding(encoding))
             ^
    5 errors generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-twbglgl_/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-record-ehmizhpb/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by gordthompson** [comment]
You could try

```
pip install pyodbc==4.0.27
```

and see if that uses a wheel file and avoids trying to build from source.

**Comment by hayneshealthcare** [comment]
Thanks for the quick response, and great suggestion.

Unfortunately, I got basically the same errors.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

(base) Matts-MacBook-Pro-2:bin Matt$ ./pip install pyodbc==4.0.27
Collecting pyodbc==4.0.27
  Using cached https://files.pythonhosted.org/packages/75/29/aa190749bac37ede0f11a68a75e7055254699c11572bd94213f1163dfd8f/pyodbc-4.0.27.tar.gz
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-wheel-qv80hzwi --python-tag pp373
       cwd: /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pyodbc' extension
  creating build
  creating build/temp.macosx-10.14-x86_64-3.6
  creating build/temp.macosx-10.14-x86_64-3.6/src
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.27 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/buffer.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.27 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/cnxninfo.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/cnxninfo.o -Wno-write-strings -Wno-deprecated-declarations
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.27 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/connection.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/connection.o -Wno-write-strings -Wno-deprecated-declarations
  src/connection.cpp:91:29: error: conversion from 'Object' to 'void *' is ambiguous
          if (PyUnicode_Check(encoding))
                              ^~~~~~~~
  src/wrapper.h:55:5: note: candidate function
      operator PyObject*()
      ^
  src/wrapper.h:60:5: note: candidate function
      operator PyVarObject*() { return (PyVarObject*)p; }
      ^
  /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
  PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                         ^
  src/connection.cpp:194:24: error: use of undeclared identifier 'PyCodec_Encode'
          stringholder = PyCodec_Encode(value, strencoding ? strencoding : "utf-16le", "strict");
                         ^
  src/connection.cpp:266:30: error: conversion from 'Object' to 'void *' is ambiguous
              (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                               ^~~~~~~~
  src/wrapper.h:55:5: note: candidate function
      operator PyObject*()
      ^
  src/wrapper.h:60:5: note: candidate function
      operator PyVarObject*() { return (PyVarObject*)p; }
      ^
  /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
  PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                         ^
  src/connection.cpp:266:76: error: use of undeclared identifier 'PyCodec_Encode'
              (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                                                             ^
  src/connection.cpp:1371:10: error: use of undeclared identifier 'PyCodec_KnownEncoding'
      if (!PyCodec_KnownEncoding(encoding))
           ^
  5 errors generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc
    Running setup.py install for pyodbc ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-record-7w2da4j_/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/
    Complete output (45 lines):
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build/temp.macosx-10.14-x86_64-3.6
    creating build/temp.macosx-10.14-x86_64-3.6/src
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.27 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/buffer.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.27 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/cnxninfo.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/cnxninfo.o -Wno-write-strings -Wno-deprecated-declarations
    gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DPYODBC_VERSION=4.0.27 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/Matt/pypy3.6-v7.3.0-osx64/include -c src/connection.cpp -o build/temp.macosx-10.14-x86_64-3.6/src/connection.o -Wno-write-strings -Wno-deprecated-declarations
    src/connection.cpp:91:29: error: conversion from 'Object' to 'void *' is ambiguous
            if (PyUnicode_Check(encoding))
                                ^~~~~~~~
    src/wrapper.h:55:5: note: candidate function
        operator PyObject*()
        ^
    src/wrapper.h:60:5: note: candidate function
        operator PyVarObject*() { return (PyVarObject*)p; }
        ^
    /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
    PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                           ^
    src/connection.cpp:194:24: error: use of undeclared identifier 'PyCodec_Encode'
            stringholder = PyCodec_Encode(value, strencoding ? strencoding : "utf-16le", "strict");
                           ^
    src/connection.cpp:266:30: error: conversion from 'Object' to 'void *' is ambiguous
                (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                 ^~~~~~~~
    src/wrapper.h:55:5: note: candidate function
        operator PyObject*()
        ^
    src/wrapper.h:60:5: note: candidate function
        operator PyVarObject*() { return (PyVarObject*)p; }
        ^
    /Users/Matt/pypy3.6-v7.3.0-osx64/include/pypy_decl.h:846:40: note: passing argument to parameter 'arg0' here
    PyAPI_FUNC(int) PyUnicode_Check(void * arg0);
                                           ^
    src/connection.cpp:266:76: error: use of undeclared identifier 'PyCodec_Encode'
                (PyUnicode_Check(encoding) ? PyBytes_AsString(encodingholder = PyCodec_Encode(encoding, "utf-8", "strict")) :
                                                                               ^
    src/connection.cpp:1371:10: error: use of undeclared identifier 'PyCodec_KnownEncoding'
        if (!PyCodec_KnownEncoding(encoding))
             ^
    5 errors generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/Matt/pypy3.6-v7.3.0-osx64/bin/pypy3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/setup.py'"'"'; __file__='"'"'/private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-install-8cxy50r8/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/xv/ktgz0vfj12v5vxr46jrxkm0h0000gn/T/pip-record-7w2da4j_/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
Matt Haynes
President
Haynes Healthcare Group, LLC
W) 404.267.1350
C) 404.808.3185
E) matt.haynes@hayneshealthcare.com

**Comment by v-chojas** [comment]
The errors seem to come from the fact that it cannot find the declarations of the Python API functions `PyCodec_Encode` and `PyCodec_KnownEncoding`. Could you make sure you are actually using the correct Python version and not something much older? Perhaps a reinstall?

**Comment by hayneshealthcare** [comment]
This is from an install of PyPy3.6 downloaded in the last 2-3 days right off the PyPy site.

pyodbc should work with PyPY, correct?

Thanks,

M

**Comment by v-chojas** [comment]
It seems you're the first to try using it with PyPy, and in that case I'm not surprised it doesn't work. Presumably that's why https://github.com/jiangwen365/pypyodbc exists.

**Comment by hayneshealthcare** [comment]
Thanks.  I will try switching to that module instead.

M

**Comment by whyzdev** [comment]
Have same build problem on Linux. 

Looks like most or all build failures are due to incompatible or unimplemented PyPy 3.6 Python C codec related APIs (see include/pypy_decl.h and PyPy issues on Bitbucket). 
Not sure when PyPy3 will address them to match CPython C 3.x APIs.

Pyodbc may be changed for PyPy3 to support some common and basic encodings first, before all encodings. At least build and work basically in PyPy3.

**Comment by v-chojas** [comment]
Take a look at https://github.com/jiangwen365/pypyodbc , it is probably what you want instead.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Comment by stonebig** [comment]
alternative solutions:
- ceodbc
- pypyodbc fork at https://github.com/pypyodbc/pypyodbc/releases

**Comment by meitham** [comment]
with ``pypyodbc`` no longer maintained, and ``pyodbc`` is a direct dependency of ``aiodbc`` what is the solution today to build ``pyodbc`` with pypy3.10?
