### ISSUE TITLE
Procedure Call Returns No Rows When Using RAISERROR (MSSQL)

### ISSUE THREAD

**Issue by Solonotix** [mkleehammer/pyodbc#673]
### Environment

- Python: 2.7.16 (64-bit on win32)
- pyodbc: 4.0.26

- Pyhon: 3.7.5 (64-bit on win32)
- pyodbc: 4.0.28

- OS: Windows 10 Professional (Version 10.0.18362.535)
- DB: Microsoft SQL Server 2016 (SP2-CU2) (KB4340355) - 13.0.5153.0 (X64) Enterprise Edition
- driver: SQL Server Native Client 11.0

### Issue

Expected Behavior:
Rows to be returned from procedure calls

Observed Behavior:
When utilizing the RAISERROR function-call to provide messages to the caller, the Cursor object determines that there are no rows to be returned from the procedure. This specifically seems to be the case when RAISERROR happens before any rows are returned.

I installed pyodbc in Python 3 as well to confirm it wasn't a deprecated issue.

SQL Code to reproduce error:
```
drop procedure if exists 
    dbo.usp_test_pyodbc;
go

create procedure dbo.usp_test_pyodbc
    (@param varchar(100))
as
    begin
        raiserror('Begin', 0, 0) with nowait;

        select
            concat('Input Value: "', @param, '"') as input_value,
            len(@param) as input_length;
    end;
go
```
Python Code:
```
connection = pyodbc.connect('Driver={SQL Server Native Client 11.0};Server=MyServer;Database=MyDb;Trusted_Connection=yes;', autocommit=True)
cursor = connection.cursor()
cursor.execute("exec dbo.usp_test_pyodbc '?';", "This is a test")
cursor.fetchall()
```
Error message received:
`pyodbc.ProgrammingError: No results.  Previous SQL was not a query.`

**Comment by gordthompson** [comment]
Can you retrieve your results of you call `.nextset()` before you call `.fetchall()`?

**Comment by Solonotix** [comment]
@gordthompson yes, if I call `.nextset()` on the cursor object, it moves to the results in the sample I provided. In my actual code, however, there are a series of messages being printed to the console by way of the RAISERROR function. Is there some way, short of a while loop that tries `.fetchall()` and gets `.nextset()` in the except block? There's over 10 console messages I had to skip through in my actual code.

RAISERROR shouldn't be coming through as a result set, since it is technically a console message, in the same vein as an exception.

**Comment by gordthompson** [comment]
It sounds like your situation is related to #495

**Comment by Solonotix** [comment]
If you addressed that one, such as piping diagnostic messages out to something unrelated to result sets, then that would probably alleviate this current problem, but I'm not trying to read these messages.

The short of it is that I'm trying to figure out why my procedure call isn't persisting data when the procedure called is performing DML before returning the results of the affected rows. My thought was that I'll just iterate through the returned rows to determine if they were malformed in passing to SQL Server, but instead I was unable to retrieve the data rows. It would seem that the ODBC connection is yielding to the caller on the first "result set" of RAISERROR, and since I never call `.nextset()` it exits without ever persisting.

```
def log_test_case(test_summary):
    """
    Future implementation for logging test cases using custom logging classes

    :param test_summary: Summary of tests executed during run-time
    :type test_summary: TestSummary
    """
    conn_string = 'Driver={SQL Server Native Client 11.0};Server=MyServer;Database=MyDb;Trusted_Connection=yes;'
    query_string = "{CALL [log].[sp_test_case_run_bulk] (?)};"

    with pyodbc.connect(conn_string, autocommit=True) as cnxn:
        with cnxn.cursor() as cursor:
            cursor.execute(query_string, test_summary.json)
```

But if I call the exact same code outside of a function call, it persists back to the database. I know this isn't the issue reported, but that's because the original issue is a phantom, since it works in one case, and not in another. While diagnosing it, I was led to the RAISERROR problem, which was easily reproducible and so I reported it as I found it.

**Comment by gordthompson** [comment]
> when the procedure called is performing DML before returning the results of the affected rows

In that case does starting your SP with `SET NOCOUNT ON;` help any?

**Comment by Solonotix** [comment]
I am already using the `SET NOCOUNT ON;` option. My procedure definition looks like this:
```
drop procedure if exists
    [log].sp_test_case_run_bulk;
go

create procedure [log].sp_test_case_run_bulk
    (@json nvarchar(max))
as
/*
----------------------------------------------------------------------------------------------------------------------------
    DocString
------------------------------------------------------------------------------------------------------------------------------
*/
    begin
        /*******************/
        -- Setup 
        /*******************/
        set nocount on;
        set xact_abort on;
        set transaction isolation level read uncommitted;

        /********************/
        -- Local Variables
        /********************/
        declare @current_environment sysname;

        /*******************/
        -- Staging 
        /*******************/
        declare
            @input
        table
            (
            -- Columns
            );

        declare
            @valid_test_type
        table
            (
            test_type_pattern varchar(100) not null,
            test_type_override varchar(100) not null primary key
            );

        declare @raw_tags table
            (
            -- Columns
            );

        /*******************/
        -- Initialize Locals 
        /*******************/

        insert into @input
            ...
        from
            OPENJSON(@json)
        with
            (
            -- Columns
            );

        raiserror('Input rows: %d', 0, 0, @@ROWCOUNT) with nowait;

        /*******************/
        -- Query Definition 
        /*******************/

        /********************/
        -- Begin Users
        /********************/
        
        -- Create New Users
        ...

        raiserror('New users created: %d', 0, 0, @@ROWCOUNT) with nowait;

        /**********************/
        -- Begin Test Type
        /**********************/
        
        ...
        raiserror('New test types defined: %d', 0, 0, @@ROWCOUNT) with nowait;


        /*******************/
        -- Begin Verticals
        /*******************/
        
        -- Create New Verticals
        ...

        raiserror('New verticals created: %d', 0, 0, @@ROWCOUNT) with nowait;

        /*****************************/
        -- Begin Projects
        /****************************/

        -- Create new projects within vertical
        ...

        raiserror('New projects defined: %d', 0, 0, @@ROWCOUNT) with nowait;

        /*****************************/
        -- Begin Products
        /****************************/

        -- Create new products within project
        ...

        raiserror('New products defined: %d', 0, 0, @@ROWCOUNT) with nowait;
        
        ...
        ...
        ...

        raiserror('New references tagged: %d', 0, 0, @@ROWCOUNT) with nowait;

        -- Return input set with internal references populated (no purpose as of this writing)
        select
            *
        from
            @input;

        set xact_abort off;
        set nocount off;
    end;
go
```

**Comment by Solonotix** [comment]
What I've done for now, and confirmed it works (though it's sloppy) is the following:
```
def log_test_case(test_summary):
    """
    Future implementation for logging test cases using custom logging classes

    :param test_summary: Summary of tests executed during run-time
    :type test_summary: TestSummary
    """
    conn_string = 'Driver={SQL Server Native Client 11.0};Server=MyServer;Database=MyDb;Trusted_Connection=yes;'
    query_string = "{CALL [log].[sp_test_case_run_bulk] (?)};"

    with pyodbc.connect(conn_string, autocommit=True) as cnxn:
        with cnxn.cursor() as cursor:
            cursor.execute(query_string, test_summary.json)
            while cursor.nextset():
                continue
```
I wouldn't consider this fixed, but at least I have something to get me through the problem.

**Comment by gordthompson** [comment]
> RAISERROR shouldn't be coming through as a result set, since it is technically a console message

I just did a quick test and the two cases look exactly the same in an ODBC trace. When I run your original example SP I see

```
main            df0-1228	EXIT  SQLExecute  with return code 1 (SQL_SUCCESS_WITH_INFO)
        HSTMT               0x046A0268

        DIAG [01000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Begin (50000) 

main            df0-1228	ENTER SQLFreeStmt 
        HSTMT               0x046A0268
        UWORD                        3 <SQL_RESET_PARAMS>

main            df0-1228	EXIT  SQLFreeStmt  with return code 0 (SQL_SUCCESS)
        HSTMT               0x046A0268
        UWORD                        3 <SQL_RESET_PARAMS>

main            df0-1228	ENTER SQLRowCount 
        HSTMT               0x046A0268
        SQLLEN *            0x00B7F378

main            df0-1228	EXIT  SQLRowCount  with return code 0 (SQL_SUCCESS)
        HSTMT               0x046A0268
        SQLLEN *            0x00B7F378 (-1)

main            df0-1228	ENTER SQLNumResultCols 
        HSTMT               0x046A0268
        SWORD *             0x00B7F374

main            df0-1228	EXIT  SQLNumResultCols  with return code 0 (SQL_SUCCESS)
        HSTMT               0x046A0268
        SWORD *             0x00B7F374 (0)
```

When I replace your `raiserror('Begin', 0, 0) with nowait;` with `PRINT 'Gord was here!';` I see

```
main            5ec-890	EXIT  SQLExecute  with return code 1 (SQL_SUCCESS_WITH_INFO)
        HSTMT               0x047B0248

        DIAG [01000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Gord was here! (0) 

main            5ec-890	ENTER SQLFreeStmt 
        HSTMT               0x047B0248
        UWORD                        3 <SQL_RESET_PARAMS>

main            5ec-890	EXIT  SQLFreeStmt  with return code 0 (SQL_SUCCESS)
        HSTMT               0x047B0248
        UWORD                        3 <SQL_RESET_PARAMS>

main            5ec-890	ENTER SQLRowCount 
        HSTMT               0x047B0248
        SQLLEN *            0x00C6F858

main            5ec-890	EXIT  SQLRowCount  with return code 0 (SQL_SUCCESS)
        HSTMT               0x047B0248
        SQLLEN *            0x00C6F858 (-1)

main            5ec-890	ENTER SQLNumResultCols 
        HSTMT               0x047B0248
        SWORD *             0x00C6F854

main            5ec-890	EXIT  SQLNumResultCols  with return code 0 (SQL_SUCCESS)
        HSTMT               0x047B0248
        SWORD *             0x00C6F854 (0)
```

and I still get the "No results.  Previous SQL was not a query." error so even a `PRINT` console message is consuming the first "result" response that comes back from the server.

**Comment by Solonotix** [comment]
The inherent problem is that there is no clean way to deduce the first **_real_** result set. If you call `.rowcount` [the documentation states](https://github.com/mkleehammer/pyodbc/wiki/Cursor#rowcount):
> **rowcount**
> The number of rows modified by the last SQL statement.
> 
> This is -1 if no SQL has been executed or if the number of rows is unknown. Note that it is not uncommon for databases to report -1 immediately after a SQL select statement for performance reasons. (The exact number may not be known before the first records are returned to the application.)

You may get -1 even if rows are present, so that's not reliable, but all other methods of fetching rows will raise an exception if there aren't any rows to be had. What's more, the procedure isn't running to completion in certain contexts because control was yielded back to the caller when reaching a PRINT or RAISERROR statement.

[From the documentation](https://github.com/mkleehammer/pyodbc/wiki/Cursor#nextset) on `.nextset()`
> **nextset()**
> This method will make the cursor skip to the next available result set, discarding any remaining rows from the current result set. If there are no more result sets, the method returns False. Otherwise, it returns a True and subsequent calls to the fetch methods will return rows from the next result set.
> 
> This method is primarily used if you have stored procedures that return multiple results.

This implies that `.nextset()` will bring me to the next result set, but instead it is taking me to the next PRINT/RAISERROR statement. What's more, I can't do anything with either of those statements in the current form of the PyODBC library, according to the state of #495 .

I hope I'm not coming off as griping. I inherited this project from a predecessor, and I'd rather not have to migrate libraries to something like pymssql if I don't have to.

**Comment by nyabutid** [comment]
I ran into the same issue. My workaround is to skip all exceptions except one that has a result set.

```cursor.execute(sql, params) 
rows = None
#this section will only return the last result from the query
while cursor.nextset():
    try:
        rows = cursor.fetchall()
    except Exception as e:
        print("Skipping non rs message: {}".format(e))
    continue```

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
