### ISSUE TITLE
pyodbc cursor.columns() does not return column names with unixDriver on rhel 7.7

### ISSUE THREAD

**Issue by kikumar3189** [mkleehammer/pyodbc#674]
- Python: 3.6.5
- pyodbc: 4.0.28
- OS: RHEL 7.7
- DB: Oracle
- driver: unixODBC 2.3.1

### Issue
I am using below code snippet to get the columns of an Oracle DB table.
import pyodbc
connectString = 'DRIVER=MyOracle;DBQ=<host>:<port>/<db>;UID=<username>;PWD=<password>'
conn = pyodbc.connect(connectString)
cursor=conn.cursor()
cursor = cursor.columns(table=<table_name>)
print(cursor.fetchall())
conn.close()

Expected behavior : Above code should return list of tuples where each tuple represent details for column. This code works fine on a windows 10 machine where driver is "Microsoft ODBC for Oracle".

Actual behavior: Above code returns empty list when used on RHEL 7.7 machine with unixODBC driver. Please note that DB connection is properly established and i am able to fetch rows using cursor.execute(sql) but cursor.columns(table=tablename) does not return any output.

**Comment by gordthompson** [comment]
Can you upgrade unixODBC to the latest version (2.3.7)? There have been a lot of bugs fixed since 2.3.1 was released over eight (8) years ago.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
