### ISSUE TITLE
Is it possible to reuse a parameter within a query?

### ISSUE THREAD

**Issue by woodlee** [mkleehammer/pyodbc#675]
### Environment

- Python: 3.7.4
- pyodbc: 4.0.28
- OS: MacOS 10.14.6
- DB: SQL Server 2017 (RTM-CU17)
- driver: ODBC Driver 17 for SQL Server

#### Short version

If I want to use a parameter's value more than once within a SQL query, is there any established way to do so in pyodbc without passing it multiple times in the parameter list to `execute`?

#### Longer version

I was recently faced with a need to write a query that does a batched read of a table in SQL Server backwards by its primary key, which happened to be a composite key formed from two columns. Something like this, where the PK is (OrderID, TagID):

```
cursor.execute('''
	SELECT TOP (1000) *
	FROM dbo.OrderTag
	WHERE OrderID < ? OR (OrderID = ? AND TagID < ?)
	ORDER BY OrderID DESC, TagID DESC
''', (last_read_order_id, last_read_order_id, last_read_tag_id))
```

AFAICT, pyodbc only supports positional parameters via the `?` placeholder, so the above seemed the most straightforward way to write the query even though it meant repeating the parameter. 

The query executes fine, but I've found that SQL Server generates a poorly performing plan for it because it doesn't understand that the first and second parameters are "the same", and so has to resort to an index scan. (SQL Server seems to dislike descending reads in general, but for purposes of this issue we can set that aside!)

I have managed to work around this with the following restructuring:

```
cursor.execute('''
	DECLARE @K0 INT = ?, @K1 INT = ?;

	SELECT TOP (1000) *
	FROM dbo.OrderTag
	WHERE OrderID < @K0 OR (OrderID = @K0 AND TagID < @K1)
	ORDER BY OrderID DESC, TagID DESC
''', (last_read_order_id, last_read_tag_id))
```

...and this indeed fixes the performance issue, but it feels hacky, and I want to ensure I'm not missing a more obvious or straightforward solution. Am I? Thank you!

**Comment by gordthompson** [comment]
The workaround you propose, which is often called an "anonymous code block", is what I would have recommended. Or, if you want something a little more formal you can create a temporary stored procedure. Just get into the habit of starting them with `SET NOCOUNT ON;`.

**Comment by woodlee** [comment]
Gotcha. I hadn't considered temporary sprocs and will look more closely into that. Thanks very much for the quick reply @gordthompson !
