### ISSUE TITLE
New issue in Pyodbc 4.0.28: hands when many connections are done

### ISSUE THREAD

**Issue by zlev-intel** [mkleehammer/pyodbc#676]
The issue is new in this release ( previously I worked with 4.0.26 ). Our system uses Tox to test itself; We are opening connection to MS SQL server, using it and close the connection a lot of times; ( do not close a connection, just exit from scope; we expect that this closes it)
New version hangs after few iterations. No error message, no exception - just halt.

Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 
- pyodbc: 
- OS: 
- DB:
- driver:

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by v-chojas** [comment]
Could you provide more information about your environment, as well as an [ODBC trace](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log)? A repro script to demonstrate would also be very useful.

**Comment by gordthompson** [comment]
FWIW, SQLAlchemy has a pretty intensive test suite and I've just confirmed that running it under tox has no problems with pyodbc 4.0.28:

```
=== 10052 passed, 1173 skipped in 1809.01s (0:30:09) ===
```

**Comment by zlev-intel** [comment]
[SQL.zip](https://github.com/mkleehammer/pyodbc/files/4049268/SQL.zip)

**Comment by zlev-intel** [comment]
this one is a trace of good run with pyodbc 4.0.24
[SQL1.LOG](https://github.com/mkleehammer/pyodbc/files/4049539/SQL1.LOG)
The first one is hang on one test, the second one is continuing to run to next test;
difference is visible starting line 32445(bad)/32462(good)
from this point on 4.0.28 starting endless loop with SQLDescribeParam/SQLBindParameter

**Comment by zlev-intel** [comment]
is there any news with this?

**Comment by v-chojas** [comment]
```DIAG [23000] [Microsoft][ODBC SQL Server Driver][SQL Server]Cannot insert the value NULL into column 'Signal_Type', table 'cloudcds_dev.ddr.Txac'; column does not allow nulls. INSERT fails. (515) ```

That looks like a problem with your data/schema. Also, please provide more information about your environment if you want more assistance.

**Comment by zlev-intel** [comment]
In our tests we are making hundreds of accesses, successful and failing, in different modes; It is OK that access can fail; It is not OK that pyodbc is hang in this case; old one worked OK, new one hangs;
BTW, it does not hang when the tests runs one-by-one manually, but hangs in sequential execution by tox

**Comment by v-makouz** [comment]
Is there a way to have a repro script? Without more detailes it may be difficult to know what causes the hang

**Comment by zlev-intel** [comment]
I can try to log all queries and results, and database tables params. But it will take some time - overloaded now...

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Comment by zlev-intel** [comment]
Was fixed in later version

Thanks,
Lev Zlotin
***@***.***
+972-4-8656740
+972-53-5207679
WIKI: https://wiki.ith.intel.com/display/AETIDC (HTTP://GOTO/AETIDC )
