### ISSUE TITLE
Contributing to the documentation?

### ISSUE THREAD

**Issue by FlipperPA** [mkleehammer/pyodbc#68]
Sorry if I missed something obvious, but is there a way we can easier contribute changes / enhancements to the documentation on github.io?

**Comment by keitherskine** [comment]
There's always the wiki:
https://github.com/mkleehammer/pyodbc/wiki
Anybody can edit that.

**Comment by FlipperPA** [comment]
Ah, good suggestion. I had followed the link from the GitHub README which took me to the github.io page.

**Comment by keitherskine** [comment]
Indeed, I suspect a lot of pyodbc users don't even know the wiki exists.

**Comment by mkleehammer** [comment]
Documentation updates would be great.  The documentation is on the gh-pages branch.  It is using "Github Pages": https://help.github.com/pages
