### ISSUE TITLE
Error code 0x68 (104) (SQLGetData)

### ISSUE THREAD

**Issue by ViRaL95** [mkleehammer/pyodbc#680]
I am getting the following error when I am fetching 1,000,000 rows using the fetchmany method. I am doing this fetch many hundred times, and it fails randomly after several hundred times of running. I am running ODBC Driver 17, but I am connecting to Microsoft SQL Server 2014

```
Exception: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLGetData)'). Traceback: Traceback (most recent call last):
  File "/home/ubuntu/strata_extract/some_file.py", line 26, in main
    for file in some_object.write(crsr, directory):
  File "/home/ubuntu/some_package/modules/some_module.py", line 24, in write
    for rows in sql.get_results(cursor=cursor):
  File "/home/ubuntu/some_package/modules/some_module.py", line 30, in get_results
    results = cursor.fetchmany(result_size)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x68 (104) (SQLGetData)')
```

**Comment by v-makouz** [comment]
This error code is "connection reset by peer" so the server forcefully closes the connection for some reason

**Comment by v-chojas** [comment]
Do you have any network firewalls etc. between the client and server? You can do a packet capture with tool like Wireshark to see if there is intermittent packet loss.

Also worth posting some more information about your environment.

**Comment by rlivianu** [comment]
Did you find out what was going on? I am having the same issue and can't figure it out.

**Comment by Upmabatra22** [comment]
Hi There, did you find solution to this issue. We are facing same error and no luck.
All firewall rules have been re-verified.

**Comment by v-chojas** [comment]
Unless both of you have the exact same environment, the circumstances may be different.
Please provide full details about your environment if you need any assistance!

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.

**Comment by tgahura** [comment]
Any update on this? We are facing exactly the same issue. I noticed keepalive packets missing in the network but not sure if it is result or cause.

**Comment by v-chojas** [comment]
This is a networking issue, nothing to do with pyODBC.

**Comment by tgahura** [comment]
Thank you, but do you know the cause in the network?
