### ISSUE TITLE
Error pyodbc.Cursor at xxxxx

### ISSUE THREAD

**Issue by fabienarnaud** [mkleehammer/pyodbc#682]
Hi all,

I've been trying to use pyodbc from my Azure Databricks for the first time but am struggling to use it to connect to Azure SQL DB.
I installed the pyodbc package and unixodbc-dev, installed the mssqlodbc drivers.
I configured the connection string in my python notebook which seems to be working because I receive an error:

`ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'lnd.lnd_man_currencyxxx'. (208) (SQLExecDirectW)")`

 when running a SELECT on a table that doesn't exist in my database.

However when the SELECT points to an existing table, I receive the following error:

`Out[11]: <pyodbc.Cursor at 0x7f06249e9030>`

Below is the code:

```
conn = pyodbc.connect( 'DRIVER={ODBC Driver 17 for SQL Server};'
                       'SERVER=xxx.database.windows.net;'
                       'DATABASE=xxx;UID=xxx;'
                       'PWD=xxx')

cursor = conn.cursor()
testSQL = "SELECT count(*) FROM [lnd].[lnd_man_currency]"
cursor.execute(testSQL)
```

Any idea what the error actually means and what I could be missing?

**Comment by gordthompson** [comment]
It's not an error. The `execute` method is simply returning the cursor object. To retrieve the results you can call `cursor.fetchall()` after you `execute` your query.

**Comment by fabienarnaud** [comment]
oh... : )
no wonder I couldn't find any reference to this "error"....
thanks a lot!!
