### ISSUE TITLE
Log query

### ISSUE THREAD

**Issue by nmhub** [mkleehammer/pyodbc#683]
Is there any way to log the query generated by execute(sql, *parameters)?

**Comment by v-chojas** [comment]
You may find it in the ODBC trace: https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log

**Comment by nmhub** [comment]
Sorry, I should have mentioned that I looked at that. Thanks for raising it.

The SQL.LOG (from Windows Server) was reporting things like "SQLBindParameter  with return code 0 (SQL_SUCCESS)". The one or two examples of SQL did not actually show the parameters inserted on the fly e.g. "VALUES (?,?,?,?,?,?"

**Comment by v-chojas** [comment]
To see such things you would need to use DBMS-specific logging functionality, pyODBC itself does not process parameters or queries and merely passes them through to the driver. Consult the documentation for your DBMS for more information.
