### ISSUE TITLE
Ship driver for MSSQL

### ISSUE THREAD

**Issue by abitrolly** [mkleehammer/pyodbc#686]
If #685 is merged, it might be possible to ship some MS SQL drivers with `pyodbc` to make it work out of the box.

**Comment by v-chojas** [comment]
pyODBC is a generic ODBC access layer, it shouldn't be driver-specific.

**Comment by abitrolly** [comment]
How can it become driver-specific just by shipping some drivers in a wheel?

**Comment by v-chojas** [comment]
There are many ODBC drivers and DBMS, and any licensing issues aside, it would only invite "why not include driver for X / I don't need driver for Y" discussion --- so pyODBC should really remain neutral and you can use it with whatever driver you need.

**Comment by abitrolly** [comment]
It could provide extra wheels with drivers. There is no need to do it in main `pyodpc` wheel. Then this Python dependency could be used in different virtualenv like any other lib in `requirements.txt`.
