### ISSUE TITLE
Implicit dependency on unixodbc and unixodbc-dev 

### ISSUE THREAD

**Issue by mirekphd** [mkleehammer/pyodbc#688]
Please state explicitly dependencies on external system packages `unixodbc` and/or `unixodbc-dev` in the docs, especially in the installation notes on PyPI.

Without these dependencies `pip install` of `pyodbc` fails when `gcc` tries to include missing `sql.h` header:
```
fatal error: sql.h: No such file or directory
```
You can replicate it in `ubuntu:bionic` docker containers with python 3.7.

**Comment by v-chojas** [comment]
Using pyODBC assumes you already have an ODBC driver, and an ODBC driver will itself already require the driver manager.

**Comment by gordthompson** [comment]
https://github.com/mkleehammer/pyodbc/wiki/Install

**Comment by mirekphd** [comment]
It's a strong assumption, not met in official LTS Ubuntu (see `docker pull ubuntu:bionic`). A workaround for this issue (which was initially reported in 2017) currently has around 60 upvotes. Is that evidence of a well documented feature? See [`src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory`](https://github.com/mkleehammer/pyodbc/issues/252)

**Comment by v-chojas** [comment]
As mentioned above, any issues would be due to dependency of the ODBC driver itself, and you have not specified which one in particular.

**Comment by mirekphd** [comment]
At the moment of `pip install` I don't need to have any drivers in the
system. They will be needed only during connection. It's just a missing C++
headers problem IMO. Most packages bundle these with the python package, to
ensure installation always suceeds.

**Comment by v-chojas** [comment]
The purpose of pyODBC is to allow you to use an ODBC driver; if you don't have an ODBC driver, then it is of no use to have pyODBC.

Those headers are part of unixODBC, not pyODBC, so it wouldn't make sense to include them. There are also others trying to use pyODBC with iODBC, and while unixODBC is recommended, it is not the only ODBC DM available.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
