### ISSUE TITLE
pyodbc.Error: 'HY000', 'The driver did not supply an error!' while accessing Access database

### ISSUE THREAD

**Issue by Amadeus111** [mkleehammer/pyodbc#693]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

**Environment**
To diagnose, we usually need to know the following, including version numbers. On Windows, be
sure to specify 32-bit Python or 64-bit:

Python: 2.7 32-bit
pyodbc: 4.0.28
OS: Windows 10
DB: Access (.mdb) 32-bit
driver: Driver do Microsoft Access (.mdb), Driver do Microsoft Excel(.xls)

**Issue**
I am running a Python script to update tables in Access (.mdb) and Excel files by using pyodbc. I did not have any problem until this week.
Now I am having " pyodbc.Error: ('HY000', 'The driver did not supply an error!') " error.

Basically the script accesses to an Excel sheet and copies everything in that sheet into an Access table. 

` 
        
       pending_permits_xl = code3_prefix + '_pending_permits.xls'
        if os.path.exists(pending_permits_xl):
            print(pending_permits_xl)
            conn1 = pyodbc.connect(
                'DRIVER={Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)};DBQ=' + pending_permits_xl,
                autocommit=True)
            cursor_pendings = conn1.cursor()
            excel_pendings = cursor_pendings.execute(
                'SELECT PERMIT_NUM, CNTY_CD, QUAD_DESC, PER_NAME, REGION_COD, DATE_RECEI, 
               STATUS_DAT, STATUS, '
                'STATUS_DES, LAT_DEG, LAT_MIN, LAT_SEC, LNG_DEG, LNG_MIN, LNG_SEC, APP_TYPE, 
                ACRES_PPSD, MINE_TYPES '
                'FROM [' + code3 + '_pending_permits$]').fetchall()

            conn = pyodbc.connect(
                r'Driver={Microsoft Access Driver (*.mdb, *.accdb)};'
                r'DBQ=' + code3_path + '\\Mine_Histories.mdb;', autocommit=True)
            mdb_cursor = conn.cursor()
            if mdb_cursor.tables(table='pending', tableType='TABLE').fetchone():
                mdb_cursor.execute('DROP TABLE pending')
            mdb_cursor.execute('CREATE TABLE pending (PERMIT_NUM varchar(255), CNTY_CD Number, 
           QUAD_DESC varchar(255), '
                               'PER_NAME varchar(255), REGION_COD varchar(255), DATE_RECEI datetime, '
                               'STATUS_DAT datetime, STATUS varchar(255), STATUS_DES varchar(255), LAT_DEG 
                              Number, '
                               'LAT_MIN Number, LAT_SEC Number, LNG_DEG Number, LNG_MIN Number, 
                                LNG_SEC Number, '
                               'APP_TYPE varchar(255), ACRES_PPSD varchar(255), MINE_TYPES varchar(255));')
            mdb_cursor.executemany('INSERT INTO pending (PERMIT_NUM, CNTY_CD, QUAD_DESC, 
                                                    PER_NAME, REGION_COD, '
                                   'DATE_RECEI, STATUS_DAT, STATUS, STATUS_DES, LAT_DEG, LAT_MIN, LAT_SEC, 
                                      LNG_DEG, '
                                   'LNG_MIN, LNG_SEC, APP_TYPE, ACRES_PPSD, MINE_TYPES) VALUES '
                                   '(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', excel_pendings)
            cursor_pendings.close()
            conn1.close()
            mdb_cursor.close()
            conn.close() `

I had an update on Excel from Windows last week. Would it be related to that?
I do not want to update over 600 tables manually :(
Any Help appreciated, thank you!

**Comment by gordthompson** [comment]
Which operation is failing: the read from Excel, the CREATE TABLE, or the INSERT INTO Access?

**Comment by Amadeus111** [comment]
> Which operation is failing: the read from Excel, the CREATE TABLE, or the INSERT INTO Access?

It seems even connection itself is failing because  cmpiling stops at  this line: 
`'DRIVER={Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)};DBQ=' + pending_permits_xl, autocommit=True) `

**Comment by gordthompson** [comment]
Run `\Windows\SysWOW64\odbcad32.exe` and switch to the "Drivers" tab. What does it report as the Version for "Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)"? I just tested on my machine with driver version 15.00.4695.1000 and it works fine for me. My latest Excel update was January 15 (KB4484234).

**Comment by Amadeus111** [comment]
I just noticed Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb) and Microsoft Access Driver (*.mdb, *.accdb) lost from my drivers. I was still able to compile the script using 
Microsoft Excel Driver (*.xls) and Microsoft Access Driver (*.mdb). 
Now, it is working but I have no idea why the drivers got lost that I was previously using.

**Comment by gordthompson** [comment]
If you want to test your ACE (.accdb/.xlsx) driver setup you could use [AceOdbcCheck](https://github.com/gordthompson/AceOdbcCheck).

**Comment by Amadeus111** [comment]
> If you want to test your ACE (.accdb/.xlsx) driver setup you could use [AceOdbcCheck](https://github.com/gordthompson/AceOdbcCheck).

Ok, I will check that out. Thanks!
