### ISSUE TITLE
Wrong error message when driver version is not found

### ISSUE THREAD

**Issue by hypdeb** [mkleehammer/pyodbc#699]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7 64-bit
- pyodbc: 4.0.28
- OS: Windows 10 Pro
- DB: 13.0.5081.1
- driver: Multiple

### Issue

Expected : specifying driver version that isn't installed gives error message which suggests the driver  that is specified is not found.

Actual : error message says driver is not specified at all, although it is.

This error message can be very frustrating as it will lead you to believe your connection string is badly formatted (the driver part is not recognized), while it's actually caused by the driver version not being installed.

**Comment by v-chojas** [comment]
Which error message are you referring to? I doubt this is a fault of pyODBC, since it only passes the connection string down the layers to the ODBC DM.

**Comment by hypdeb** [comment]
Sorry I forgot to insert the actual error message which is :
> (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')

**Comment by gordthompson** [comment]
> Is their a layer between pyodbc and the driver ?

Yes, it's called the Driver Manager (DM). Keith wrote up an explanation [here](https://github.com/mkleehammer/pyodbc/wiki/Drivers-and-Driver-Managers).

That message is coming from the Driver Manager, and pyodbc is just passing along the bad news.

**Comment by keitherskine** [comment]
I agree, it's a particularly badly worded error message, but unfortunately there's not much that pyodbc can do about it.  It's generated elsewhere.

**Comment by hypdeb** [comment]
I understand. Sorry for wasting your time.
