### ISSUE TITLE
Cursor.fetchone() works only after cursor.nextset() on a seemingly correct query script

### ISSUE THREAD

**Issue by Semiarty** [mkleehammer/pyodbc#700]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.6.final.0 64-bit
- pyodbc: 4.0.28
- OS: Windows 10 64-bit
- DB: MS SQL
- driver: SQL Server / ODBC Driver 17 for SQL Server (tried both)

### Issue
```python
import pyodbc
import sys
from contextlib import contextmanager
import textwrap
import pandas as pd

@contextmanager
def open_db_connection(connection_string):
    pyodbc.pooling = False
    connection = pyodbc.connect(connection_string)

    try:
        yield connection
    except pyodbc.DatabaseError as err:
        error, = err.args
        sys.stderr.write(error.message)
    finally:
        connection.close()

def create_query_string(sql_full_path):
    with open(sql_full_path, 'r') as f_in:
        lines = f_in.read()

    query_string = textwrap.dedent("""{}""".format(lines))
    return query_string

def query(server, database, driver, queryObj):

    connection_string = 'DRIVER={};SERVER={};DATABASE={};Trusted_Connection=yes'.format(driver, server, database)
    
    noCount = """ SET NOCOUNT ON; """
    with open_db_connection(connection_string) as conn:
        res = pd.read_sql_query(noCount+queryObj, conn)

    return res


def get_data_set(sql_file_name, db_info):
    query_string = create_query_string(sql_file_name+'.sql')
    server = db_info['server']
    database = db_info['database']
    driver = db_info['driver']
    df = query(server, database, driver, query_string)
    #df.to_excel(sql_file_name+'_backup.xlsx', index=False)
    return df

db_info = {'server' : 'wsp', 'database' : 'fin', 'driver' : 'SQL Server'}

df = get_data_set('equities', db_info)
```
SQL part 
```sql
IF OBJECT_ID('tempdb..#tmp') IS NOT NULL DROP TABLE #tmp;
select * 
into #tmp 
from fin.dbo.items_info

IF OBJECT_ID('tempdb..#test1') IS NOT NULL DROP TABLE #test1;
select t.PositionID, b.SecurityID
into #test1
from #tmp as t
inner join fin.dbo.items  as b on (b.PositionID = t.PositionID and b.StudyDate = '20191230')
where t.ast = 'eq';

IF OBJECT_ID('tempdb..#beta_index') IS NOT NULL DROP TABLE #beta_index;
select distinct isin, beta_index into #beta_index from md.data.equity; 

IF OBJECT_ID('tempdb..#test2') IS NOT NULL DROP TABLE #test2;
select t.PositionID,    
       case
       when count(i.beta_index)=0 then 1
       else count(i.beta_index)
       end as noIndex
into #test2 
from #test1 as t 
   left join #beta_index as i on (t.SecurityID = i.isin)
   group by t.PositionID;

select * from #test2
```
#### Problem description
Initially I figured it had something to do with pandas read_from_sql() function, however I tried manually fetching a table from database by using pyodbc, which resulted in the same error.
 
I am trying to fetch #test2 table, however it results in "ProgrammingError: No results.  Previous SQL was not a query.". If I try to fetch #test1, it works fine. It may has something to do with counting/grouping, I am not sure. No issues with other lengthy queries with insert, update, group though.

Additionally, this query works fine when running it in SSMS v18.4 and I get results from #test2.

While doing further research, I have found a "potential" solution, but it won't help me as I need pandas to pull data.
After connecting to the base manually and executing a query:
cursor.fetchone() (fails with the aforementioned error)
cursor.nextset() (Results: True)
cursor.fetchone() (Returns expected output)

It may be down to my lack of knowledge in SQL and my query is not properly written or it could be something else. Could you please advise?

#### Expected Output
I expect to get an output from #test2 table. The select statement should return a non empty table (which it does in SSMS). However cursor.fetchone()/fetchall() throws an error initially and only after calling cursor.nextset(), fetching is working.

**Comment by gordthompson** [comment]
Put

```
SET NOCOUNT ON;
```

at the beginning of your SQL code block.

**Comment by Semiarty** [comment]
I am using it currently (excerpt from the code above)    
noCount = """ SET NOCOUNT ON; """
    with open_db_connection(connection_string) as conn:
        res = pd.read_sql_query(noCount+queryObj, conn)

Hence the issue ticket. I get no problems with other sql queries. Just this particular #test2 table.

**Comment by v-chojas** [comment]
Do you have a minimal schema (including some data) which can be run to reproduce this issue?

**Comment by Semiarty** [comment]
So I just realized that I was ignoring/disregarding warning messages in SSMS, which, I believe, results in cursor not being a query and pyodbc throwing ProgrammingError "No results. Previous SQL was not a query."

The warning:
Warning: Null value is eliminated by an aggregate or other SET operation.

SET ANSI_WARNINGS OFF solved the issue, therefore it's not a bug. Thank you both.
