### ISSUE TITLE
pyodbc 4.0.{29,30} unavailable for Mac OS X

### ISSUE THREAD

**Issue by cbcoutinho** [mkleehammer/pyodbc#704]
When installing `pyodbc` into a fresh virtualenv, `pip` downloads v4.0.28 - wheels for later versions are not available

**Comment by mkleehammer** [comment]
Thanks.  I built them and forgot to upload.  They are there now.  Actually only 4.0.30 is there now.  Version 29 was not officially released.

**Comment by keitherskine** [comment]
Just FYI @mkleehammer , I don't know if it takes a while for new files to appear at https://pypi.org/project/pyodbc/#files, but I'm looking at that page now, and I don't see any Mac OSX files there.

**Comment by keitherskine** [comment]
Ah, I see the Mac OSX files have been published to PyPi, just under a different version number (4.0.30b1 as opposed to 4.0.30):
https://pypi.org/project/pyodbc/4.0.30b1/#files
