### ISSUE TITLE
pyodbc.Error: ('HY000', '[HY000] [unixODBC][Oracle][ODBC][Ora]ORA-28009: connection as SYS should be as SYSDBA or SYSOPER\n (28009) (SQLDriverConnect)')

### ISSUE THREAD

**Issue by alexisrolland** [mkleehammer/pyodbc#707]
Hi Michael,

First of all I would like to thank you for the great work you've done on this page:
https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-Oracle-from-RHEL-or-Centos

After struggling so bad with Oracle's documentation, your documentation to install Oracle ODBC driver on Linux is the most succint, clear and efficient!

I have successfully installed the driver in my Python Docker image. I think it works fine because I am able to reach the database and receive the error message:

> pyodbc.Error: ('HY000', '[HY000] [unixODBC][Oracle][ODBC][Ora]ORA-28009: connection as SYS should be as SYSDBA or SYSOPER\n (28009) (SQLDriverConnect)')

When connecting to Oracle db with SQL plus, this kind of message can be avoided with a connection string like: `$ sqlplus sys/1234@//localhost:1521/ORCLCDB as sysdba`

I would like to know if you are aware of any ODBC driver parameter which would allow to provide the role `sysdba` in pyodbc connection string. Here is the string I am using:

```py
import pyodbc
connection_string = "driver={Oracle};dbq=db-oracle:1521/orclcdb;uid=sys;pwd=1234"
connection = pyodbc.connect(connection_string)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY000', '[HY000] [unixODBC][Oracle][ODBC][Ora]ORA-28009: connection as SYS should be as SYSDBA or SYSOPER\n (28009) (SQLDriverConnect)')
```

**Comment by alexisrolland** [comment]
In case it would help Im trying to workaround this issue by creating another database user for pyodbc.
```sql
CREATE USER oracle IDENTIFIED BY 1234-abcd;
GRANT CREATE SESSION TO oracle;
```

**Comment by reedjosh** [comment]
FYI @alexisrolland  you can do what you were trying to do by putting as sysdba in the password field.
So,
"driver={Oracle};dbq=db-oracle:1521/orclcdb;uid=sys;pwd=1234 as sysdba"
I wound up here trying to do the same thing... : )
