### ISSUE TITLE
Installation tries to use iODBC on Mac OS 10.7.5

### ISSUE THREAD

**Issue by ozgurakcali** [mkleehammer/pyodbc#71]
I'm on Mac OS 10.7.5, I've installed and configured freetds and unixodbc. I've used pip to install pyodbc (3.0.10). It should be using unixodbc by default, but when I try to connect to a db with the following piece of code on python2.7:

pyodbc.connect('DSN=DSN;UID=USER;PWD=PASS')

I get the following error: 

"pyodbc.Error: ('IM002', '[IM002] [iODBC][Driver Manager]Data source name not found and no default driver specified. Driver could not be loaded (0) (SQLDriverConnect)')"

Looks like it's still trying to use iODBC.

I can connect to the db with isql using the same configuration.

**Comment by ozgurakcali** [comment]
After upgrading to Mac OS 10.10.5, and reinstalling the packages (pyodbc, freetds and unixodbc), I can now connect to the db through pyodbc.

**Comment by mkleehammer** [comment]
Thanks for the update.  I'm not sure what did it, but I'll close this.
