### ISSUE TITLE
Call to cursor.fetchmany results in an exception of ValueError: microsecond must be in 0..999999

### ISSUE THREAD

**Issue by sonicd007** [mkleehammer/pyodbc#710]
### Environment
- Python: 3.6.9
- pyodbc: Tried both 4.0.30b1 and 4.0.28 and 4.0.23
- OS: Debian GNU/Linux 10 (buster) on an ARMv7 Processor rev 4 (v7l)
- DB: Oracle (Retail Pro Point of Sale software which uses an Oracle database)
- driver: Easysoft Oracle ODBC Driver (https://www.easysoft.com/products/data_access/odbc_oracle_driver/#section=tab-1)

### Issue

I'm migrating a python 2.7 codebase to python 3.6 and the code for the most part is exactly the same aside from minor syntax changes. Same hardware, same ODBC driver, different pyodbc and different python version.  The pyodbc used in the 2.7 codebase was 3.0.6 and came from the debian package repo (python-pyodbc).  No issues were encountered in the 2.7 code base and data was retrieved. pyodbc was installed using pip in the 3.6 code base and throws the ValueError exception after getting data back from the database. The versions tried for the pip package were 4.0.30b1 and 4.0.28

**Expected outcome**: pyodbc.cursor.fetchmany(size) should return data from the database
**Actual outcome**: pyodbc.cursor.fetchmany(size) throws a ValueError: microsecond must be in 0..999999

I'm assuming there must be a row that contains a datetime stamp that has more than 6 decimal values and is causing pyodbc to throw this exception. I would expect pyodbc to truncate the value to 6 decimals if this is indeed the issue. The query is a simple select * from table.

**Comment by gordthompson** [comment]
Can you post an MCVE with DDL and sample data?

**Comment by sonicd007** [comment]
I've narrowed down the cause to a CREATED_DATE field.
I've attached the column definition, as well as test python code. You'll need to get a trial version of the Easysoft ODBC driver to test with and an oracle database to test against.  The Oracle database version used in this scenario is:

[('Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production', 0.0), ('PL/SQL Release 12.1.0.2.0 - Production', 0.0), ('CORE\t12.1.0.2.0\tProduction', 0.0), ('TNS for 64-bit Windows: Version 12.1.0.2.0 - Production', 0.0), ('NLSRTL Version 12.1.0.2.0 - Production', 0.0)]


![ColumnDefinition](https://user-images.githubusercontent.com/9023078/74468129-476b4880-4e68-11ea-886c-ed580b6376d9.png)

[test.py.txt](https://github.com/mkleehammer/pyodbc/files/4200428/test.py.txt)

[odbc.ini.txt](https://github.com/mkleehammer/pyodbc/files/4200436/odbc.ini.txt)

I've attached all the information I have. I hope this helps.  Be sure to update the odbc file with the database you setup to test with. The odbc.ini file goes into the /etc folder as such: /etc/odbc.ini
The python test script will throw the exception at the fetch call. Also update the select query depending on what test column/db is created.

**Comment by gordthompson** [comment]
I am unable to reproduce your issue under Windows. The following test code works fine, indicating that pyodbc does not have a problem with Oracle DATE columns *per se*. You may want to ask for assistance from Easysoft.

```python
import sys
import pyodbc

print(f"Python version {sys.version}")
# Python version 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]

print(f"pyodbc version {pyodbc.version}")
# pyodbc version 4.0.30

cnxn = pyodbc.connect(
    "DSN=oracle1;UID=SYSTEM;PWD=_whatever_",
    autocommit=True
)
print(f'driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
# driver: SQORA32.DLL, version: 18.04.0000

crsr = cnxn.cursor()
try:
    crsr.execute("DROP TABLE CUSTOMER")
except:
    pass
crsr.execute(
    "CREATE TABLE CUSTOMER ("
    "ID INT PRIMARY KEY, "
    "CREATED_DATE DATE DEFAULT SYSDATE"
    ")"
)
crsr.execute("INSERT INTO CUSTOMER (ID) VALUES (1)")
x = crsr.execute("SELECT CREATED_DATE FROM CUSTOMER WHERE ID=1").fetchval()
print(x)  # 2020-02-15 17:15:10

crsr.execute("DROP TABLE CUSTOMER")
```

**Comment by sonicd007** [comment]
I'll see if Easysoft can help out. I tried seeing if I could debug the pyodbc library using gdb and it seems like I'm having some success. I was able to call python using gdb and compiled pyodbc with debug flags enabled. Pointed gdb to the src directory for pyodbc and set the breakpoint to the GetDataTimestamp function as that's where I suspected it was throwing an error. It seems to be entering the PyDateTime_FromDateAndTime instead of the case statement for SQL_TYPE_DATE.

Here's a screenshot from gdb with the values and indeed the micros value would cause an exception to get thrown since it's over the allowed value of 99999. Should it even be entering PyDateTime_FromDateAndTime for an oracle date type? If it shouldn't then I suspect the Easysoft driver might be returning the data as the wrong sql type.  Please let me know if I'm onto something.

![image](https://user-images.githubusercontent.com/9023078/74757031-76f0cb00-5243-11ea-9b2c-638616d9dc24.png)

**Comment by keitherskine** [comment]
Good debugging detective work, @sonicd007 .

According to the "fraction" description in note (b) [here](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/c-data-types), the fractional value is billionths of a second and therefore should never be more than 9 digits. "2130685884" is ten digits so appears to be invalid.  It will be interesting to see where it came from.  Perhaps it came from a bug in the driver, perhaps it's junk bytes that have been dragged in at the end of a struct.

The ODBC type of "SQL_TYPE_TIMESTAMP" appears to be correct because the "SQL_TYPE_DATE" ODBC type covers only calendar days (year, month, date).  See [here](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/sql-data-types) for details.  The Oracle SQL data type "DATE" actually includes a time as well (hour, minute, second), hence "SQL_TYPE_TIMESTAMP" must be used (but in this scenario, the fractional value should, it would seem, be zero).

**Comment by sonicd007** [comment]
Ah you're right about the Types, I didn't take into account pyodbc's types vs Oracle's types.

Setting the micros seconds to be under 1 billion seems to fix issue of the exception getting thrown. I'm going to reach out to the vendor about their driver, maybe it's a bug in the driver software that we're getting a value over one billion for the microseconds. 

I think there should still be a check on the value returned by the driver to check that the value fits within pythons datetime range. I can confirm that adding
`if (value.faction > 1000000000) value.fraction = 999999999;`
allows me to retrieve data with no exception being thrown.  There should be checks to make sure the value falls from 0 to 1000000000 as the docs specify imo. 

I'm going to reach out to the vendor so they can check if there's a bug in their driver. I might just use this workaround for now to continue with work on my end.

**Comment by gordthompson** [comment]
Just out of curiosity: What do you get if you launch `isql` from a terminal window ...

```
isql ORACLE_SAMPLE -v
```

... and then run the query ...

```
SELECT CREATED_DATE FROM CMS.CUSTOMER
```

... ?

**Comment by sonicd007** [comment]
It connects and returns rows.

![image](https://user-images.githubusercontent.com/9023078/74793893-bd6c1700-528f-11ea-9503-1ea7c8aaf7ca.png)

**Comment by sonicd007** [comment]
I received an update from Easysoft. The fractions value was unset in their driver somewhere. The issue is fixed in their 1.3.3 driver.  I'm good on my end! Do you want me to leave this issue open for a check to be added in on the pyodbc side or should it stay as is?

**Comment by gordthompson** [comment]
It's good to hear that your issue is resolved, but IMO pyodbc shouldn't be checking for every possible bug in an ODBC driver.

**Comment by v-chojas** [comment]
Agreed. In this case it is checking implicitly, which was certainly sufficient --- to allow this issue to be created.

**Comment by sonicd007** [comment]
Okay, I'm going to close this issue then. Thanks.
