### ISSUE TITLE
Source package for 4.0.30 missing

### ISSUE THREAD

**Issue by edwardreed81** [mkleehammer/pyodbc#712]
My package manager (poetry) is having trouble updating because 4.0.30 is the most recent version, but the source package isn't available at https://pypi.org/project/pyodbc/4.0.30/.

**Comment by keitherskine** [comment]
The v4.0.30 Linux and MacOSX v30 distributables were uploaded separately and can be found here:
https://pypi.org/project/pyodbc/4.0.30b1/#files

Perhaps try `pip install pyodbc==4.0.30b1`, or `pip install pyodbc==4.0.28` for the previous version.

**Comment by edwardreed81** [comment]
That doesn't really help if some other package specifies 4.0.30 as a dependency. What's the reason for the separate versions?

**Comment by nehaljwani** [comment]
I agree with @edwardreed81 . Why are macOS and Linux beta but Windows is not?

**Comment by mkleehammer** [comment]
I apologize.  The 4.0.30 tag was created on the Windows build box after final tests, but I forgot to pull the tag to the other boxes.  The code is identical to v4.0.29-b01 but properly tagged now.

I should change from a shell script to a Python script for building releases - it would be easier to add a check to make sure the current tip of master is tagged properly.
