### ISSUE TITLE
SqlServer backup deletion at connection end  ?

### ISSUE THREAD

**Issue by omigeon** [mkleehammer/pyodbc#72]
If I run a Sql Server database backup from pyodbc, the backup file is deleted at the end of my script.
Since the backup takes some times, I can see the file being written, but it disappears after execution.

It could be a problem when pyodbc tries to close the connection, since when If I raise an exception after the backup instruction, the backup file is not deleted.

I don't have the problem when I use the regular win32all odbc module.

``` python
con = pyodbc.connect("Driver={SQL Server};Server=(local);Trusted_Connection=yes", autocommit=True)
cur = con.cursor()
cur.execute("BACKUP DATABASE {source} TO DISK = N'{backup_filename}'")
# raise Exception("anything") # uncomment to actually get the backup file.
```

**Comment by circuitBurn** [comment]
+1, though I'm only closing the cursor and not the connection.

**Comment by mkleehammer** [comment]
I'm going to close this only because I really don't think it is a pyodbc issue as opposed to a SQL Server driver issue.  If you want to examine this further, can you provide an ODBC trace file?

**Comment by antonyferguson** [comment]
I'm having this issue now.
What is the correct solution for this?

**Comment by v-chojas** [comment]
Read all the resultsets coming from the server.

...and search for a solution before asking, others have seen this before: https://github.com/mkleehammer/pyodbc/issues/740
