### ISSUE TITLE
Error with select query when using PostgreSQL 12

### ISSUE THREAD

**Issue by tqa236** [mkleehammer/pyodbc#720]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.30
- Host OS: Ubuntu 18.04
- DB: PostgreSQL
- driver: PostgreSQL Unicode
- Docker Image for PostgreSQL: [postgres:12.2-alpine](https://hub.docker.com/layers/postgres/library/postgres/12.2-alpine/images/sha256-05e2ec8c0b8248201d410a6f2944606b28692622daf20ba6ba3fe6ef87059469?context=explore)
- All code runs on docker containers.
(Note: The error doesn't occur for PostgreSQL 11.7, I believe it only affects PostgreSQL 12+, please see the StackOverflow question below.)

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

- Observed behavior:

When I execute a select query, this error occurs but I still receive the result of the query.

```bash
ERROR:  column c.relhasoids does not exist at character 245
STATEMENT:  select n.nspname, c.relname, a.attname, a.atttypid, t.typname, a.attnum, a.attlen, a.atttypmod, a.attnotnull, c.relhasrules, c.relkind, c.oid, pg_get_expr(d.adbin, d.adrelid), case t.typtype when 'd' then t.typbasetype else 0 end, t.typtypmod, c.relhasoids, attidentity from (((pg_catalog.pg_class c inner join pg_catalog.pg_namespace n on n.oid = c.relnamespace and c.oid = 16395) inner join pg_catalog.pg_attribute a on (not a.attisdropped) and a.attnum > 0 and a.attrelid = c.oid) inner join pg_catalog.pg_type t on t.oid = a.atttypid) left outer join pg_attrdef d on a.atthasdef and d.adrelid = a.attrelid and d.adnum = a.attnum order by n.nspname, c.relname, attnum
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

Related: https://stackoverflow.com/questions/58461178/how-to-fix-error-column-c-relhasoids-does-not-exist-in-postgres 

- Expected behavior: This error doesn't happen.

**Comment by gordthompson** [comment]
It sounds like you might need to upgrade your ODBC driver. The following works for me:

```python
import pyodbc

cnxn = pyodbc.connect("DSN=PostgreSQL35W")
print(f'driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
# driver: PSQLODBC35W.DLL, version: 12.00.0000

print(crsr.execute("SELECT 1 AS foo").fetchall())
# [(1, )]
```

**Comment by tqa236** [comment]
Thank you very much for your quick reply. Unfortunately, this solution doesn't work for me.

Can you tell me this driver is for Windows or Linux, please?

I tried updating the driver for Linux but it seems that my driver is up-to-date.

```bash
odbc-postgresql is already the newest version (1:10.01.0000-1)
unixodbc is already the newest version (2.3.7). 
```

Here are the drivers that is available for me:

```python
>>> import pyodbc
>>> print(pyodbc.drivers())
['MySQL ODBC 8.0 Driver', 'MySQL ODBC 8.0', 'PostgreSQL ANSI', 'PostgreSQL Unicode', 'ODBC Driver 17 for SQL Server']
```

Only `PostgreSQL Unicode` works (with the error above)

When I tried your query (`print(crsr.execute("SELECT 1 AS foo").fetchall())
`), it also works well. But for any more complex query, like `SELECT id from table`, this error appears.

**Comment by gordthompson** [comment]
Please post result of

```python
print(f'driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}')
```

after you connect with `PostgreSQL Unicode`.

**Comment by tqa236** [comment]
Here it is: `driver: psqlodbcw.so, version: 10.01.0000`

**Comment by gordthompson** [comment]
Okay so your ODBC driver is up-to-date as far as the Ubuntu 18.04 repositories are concerned, but Ubuntu repos often distribute rather old versions of stuff like this. You're using a v10 driver and apparently it doesn't work with a v12 server. You'll need to get a newer version of the ODBC driver directly from PostgreSQL.

**Comment by tqa236** [comment]
Thank you very much for your help. I think version 11.7 will work too.
