### ISSUE TITLE
Results from select statement.. Long text truncation in results. How to retrieve entire value 

### ISSUE THREAD

**Issue by stmiller14** [mkleehammer/pyodbc#724]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 
- pyodbc: 
- OS: 
- DB:
- driver:

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by stephendmiller1991** [comment]
IBM DB2 ODBC driver
>python 3
windows

**Comment by gordthompson** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
