### ISSUE TITLE
NULLABLE always true on MS Access databases

### ISSUE THREAD

**Issue by LemarinelNet** [mkleehammer/pyodbc#726]
Hi,
I'm pulling my hair with reading MDB tables on python.
Everytime I try to get the NULLABLE property of a field, I get "YES" or "1" depending of where I get the information.
To confirm my problem, I've made a simple Access DB file, with just one table. Setting first field to Not Null and second field to "Null allowed".

Here is the code I run : 

`import pyodbc
from pprint import pprint

conn_str = (
    r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};'
    r'DBQ=C:\MDB\db1.accdb;'
    )
cnxn = pyodbc.connect(conn_str)
crsr = cnxn.cursor().execute("SELECT * FROM Table1")

for i in crsr.description :
    pprint(i)

for field in cnxn.cursor().columns(table = "Table1"):
    pprint(field)
`

I've tried with both .mdb format and .accdb format, both leads to the same problem.

Can someone confirm the problem ?
I'd like to test an older MS Access driver, but could'nt find something older than 14.

### Environment

- Python 3.7.3 x64
- pyodbc (4.0.30) installed via pip install pyodbc
- OS: Windows 10 x64
- DB: MS Access (both .mdb and .accdb tried)
- driver: Both MS Access 14 and 16 drivers tried

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by gordthompson** [comment]
> Can someone confirm the problem ?

Yes. It appears to be a deficiency in the Access ODBC driver. I found it while implementing the [sqlalchemy-access](https://github.com/sqlalchemy/sqlalchemy-access) dialect.

**Comment by LemarinelNet** [comment]
Do you know if an older version of the driver would handle it correctly ?
if yes, do you have any clue to download (and use !) an older version of the driver ?

**Comment by gordthompson** [comment]
You could use an .mdb file to test the 32-bit "Jet" driver that ships with Windows

```
DRIVER={Microsoft Access Driver (*.mdb)}
```

It's very old, but it's the last of that family (Access < 2007).

My strong suspicion is that the driver has always behaved like that and has never been fixed.

**Comment by LemarinelNet** [comment]
I can't manage to use this driver, it doesn't seems to be installed on my W10 machine.
I still have access to an "old" Windows Server 2008 that ships with an old Access driver, I could give it a try.

How did you solved the issue with sqlachemy ?

**Comment by gordthompson** [comment]
The old Jet driver still ships with Windows 10. It should appear on the Drivers tab of "ODBC Data Source Administrator (32-bit)".

Because the underlying driver does not support retrieving the nullable status of a column, the sqlalchemy-access dialect does not support it, either.

**Comment by LemarinelNet** [comment]
I can't manage to connect with the old driver, even if it appears on the ODBCAD32.exe tab...
When I list the drivers installed with `for x in pyodbc.drivers()`, it doesn't show up, only the newest one !?
Do I have to use a 32 bit python to do so?

**Comment by gordthompson** [comment]
Yes, you'd need to be running 32-bit Python in order to use a 32-bit driver.

**Comment by LemarinelNet** [comment]
I've tried on my W10 system, with python32, and the installed 32 bits ODBC driver (version 10.00.18362.01 , date 19/03/2019).
Still the same problem.
I'll give a try on a WS2008 server, which has a slighly older driver.
I keep you in touch !

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
