### ISSUE TITLE
intermittent issues with fetchmany

### ISSUE THREAD

**Issue by StudentForever** [mkleehammer/pyodbc#727]
### Environment

- Python: 3.6.5
- pyodbc:  4.0.30
- OS: linux (RHEL 6)
- DB: Azure Managed Instance
- driver: ODBC Driver 11 for SQL Server

### Issue

While using fetchmany, running into this error intermittently:

pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 11 for SQL Server]SSL Provider: [error:80001044:lib(128):func(1):internal error:unexpected error] (-1) (SQLGetData)')

Please let me know if I can provide any more information.

thanks

**Comment by v-makouz** [comment]
Sounds like incompatible version of OpenSSL, Driver 11 is quite old, I would recommend using the latest ODBC Driver 17 for SQL Server, especially since it has a more robust handling of OpenSSL (both 1.0 and 1.1, older drivers could only work with 1.0)

**Comment by StudentForever** [comment]
thanks a lot. I am not sure if I will be able to upgrade to ODBC driver 17 due to other interdependencies and the hosts where the code runs. But thanks a lot for the inputs.

Will explore the options and post the trace if relevant,

**Comment by v-makouz** [comment]
Driver 17 installs side by side with older drivers (package is named msodbcsql17) so you could have both on them on a system if that makes things easier

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
