### ISSUE TITLE
Close the pyodbc Google Group?

### ISSUE THREAD

**Issue by keitherskine** [mkleehammer/pyodbc#730]
Just FYI, the pyodbc Google Group is still up-and-running:
https://groups.google.com/forum/#!forum/pyodbc

Perhaps it's time to retire it?  It's rarely used these days and I'm thinking it would better if people raised issues here on Github.  I don't know who the administrator for it is though.

**Comment by mkleehammer** [comment]
Good idea.  I've posted a message pointing people here.  I could not find a way to archive it, so I simply set it so only owners can post.  Thanks.
