### ISSUE TITLE
conn string works in windows ODBC Administrator; doesn't work in pyodbc

### ISSUE THREAD

**Issue by Slowly** [mkleehammer/pyodbc#731]
windows 10 64 bit, python 3.6 64 bit. 
observed  behavior:
![ODBCadminConnectsSuccessfully](https://user-images.githubusercontent.com/119132/77810432-9dc7cb80-7051-11ea-879e-26ff82f7a232.png)
![pyodbcNotConnectSuccessfully](https://user-images.githubusercontent.com/119132/77810484-e5e6ee00-7051-11ea-9b28-a9af8a4aa732.png)

**Comment by gordthompson** [comment]
Two things you could try:

1. Remove the spaces after each semicolon separator in `strfileDSNAsAstring`.
2. Try calling `pyodbc.pooling = False` before calling `.connect`.

**Comment by Slowly** [comment]
Both Gord's recommendations, plus uppercasing my kerberos realm, worked. Apparently kerberos is case sensitive. Thanx Gord!

import pyodbc

strFileDSNAsAstring = "DRIVER=Cloudera ODBC Driver for Apache Hive;USEUNICODESQLCHARACTERTYPES=1; \
SSL=0;SERVICEPRINCIPALCANONICALIZATION=0;SERVICEDISCOVERYMODE=0;SCHEMA=database;PORT=port; \
KRBSERVICENAME=hive;KRBREALM=uppercaserealm;KRBHOSTFQDN=hostfqdndomain;INVALIDSESSIONAUTORECOVER=1; \
HOST=host;HIVESERVERTYPE=2;GETTABLESWITHQUERY=0;ENABLETEMPTABLE=0;DESCRIPTION=Hive; \
DELEGATEKRBCREDS=0;AUTHMECH=1;ASYNCEXECPOLLINTERVAL=100;APPLYSSPWITHQUERIES=1;CAIssuedCertNamesMismatch=1;"

try:
  pyodbc.pooling = False
  conn = pyodbc.connect(strFileDSNAsAstring, autocommit=True)
except:
  print("failure.")
else:
  conn.close()
  print("success.")

**Comment by sebarti** [comment]
I think this issue can be closed, right?
