### ISSUE TITLE
Persistent connection time out

### ISSUE THREAD

**Issue by deejcunningham** [mkleehammer/pyodbc#733]
### Environment

- Python: 3.8.1
- pyodbc: 4.0.30
- unixodbc: 2.3.7
- OS: Arch Linux, kernel: 5.5.6-arch1-1
- DB: 14.0.3223.3 Express Edition (64-bit)
- driver: ODBC Driver 17 for SQL Server

### Issue
I am unable to connect to my database and the attempt times out after ~30 seconds.

Trying to connect with `conn = pyodbc.connect("DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost,1433;DATABASE=dbname;UID=username;PWD=password;")`

I receive this error: `OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')`

I am able to connect using azuredatastudio as well as with the SQL server VSCode extension, so I am pretty certain that my port is forwarded correctly and I know that the user/pass is correct.

`cat /etc/odbcinst.ini` gives me

> `[ODBC Driver 17 for SQL Server]`
> `Description=Microsoft ODBC Driver 17 for SQL Server`
> `Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-17.4.so.2.1`
> `UsageCount=1`

The [documentation for Linux](https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Linux) only covers connection using a DSN. Is that method required if connecting from Linux?

**Comment by v-chojas** [comment]
> DB: 14.0.3223.3 Express Edition (64-bit)

Is this SQL Server running on Linux or Windows? Your connection string suggests SQL Server is running on the same machine as the driver itself, which would mean it's Linux SQL Server?

Also, Arch Linux is not an officially supported by the ODBC Driver 17 for SQL Server, nor Linux SQL Server.

**Comment by deejcunningham** [comment]
The SQL Server is running on Windows Server 2016 Datacenter 10.0 in a kubernetes cluster and my localhost port 1433 is forwarded to point there.

When I log in via Azure Data Studio for instance, I use "localhost" as the server.

**Comment by deejcunningham** [comment]
Actually wow, I think this is solved - instead of "localhost" in the connection string I needed to use "127.0.0.1"
