### ISSUE TITLE
Unable to Install Pyodbc while creating AWS EMR Cluster Bootstrapping. 

### ISSUE THREAD

**Issue by SarathPuppala** [mkleehammer/pyodbc#735]
### Environment

Instance Hardware Details: **AWS|EMR|x86_64|Linux**
- Python: **3**
- pyodbc: **4.0.27**
- OS: **EC2 Instance (m4.large)**
- DB: **MSSQL**
- driver: **{SQL Server}**

### Issue

**_"observed behavior"_**

sudo: apt-get: command not found
sudo: apt-get: command not found
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
  Could not find a version that satisfies the requirement json (from versions: )
No matching distribution found for json
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
**Command "/bin/python3 -u -c "import setuptools, tokenize;__file__='/mnt/tmp/pip-build-9cp7ycb5/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6sa0p0ud-record/install-record.txt --single-version-externally-managed --compile" _failed with error code 1_ in /mnt/tmp/pip-build-9cp7ycb5/pyodbc/**

Following is the **Snapshot of my Bootstrap file**:

sudo apt-get install build-essential libssl-dev libffi-dev **python3-dev**
sudo apt-get install **unixodbc-dev**			
sudo python3 -m pip install **pandas**
sudo python3 -m pip install **json**
sudo python3 -m pip install **boto3**
sudo pip install **pyodbc==4.0.27**	

Also I tried with 

**sudo -H pip install pyodbc**
**sudo apt-get install python3-dev**
**sudo apt-get install unixodbc-dev**

I referred following issues to solve my problem, but I could find a solution.

https://github.com/mkleehammer/pyodbc/issues/275
https://github.com/mkleehammer/pyodbc/issues/276

@mkleehammer  Please assist me on this.

**Comment by v-chojas** [comment]
Your "OS" looks more like a VM size. That field is for specifying whether you're using Windows, Linux or Mac, and which specific version of the OS. Judging by the commands you are attempting as if it is a Ubuntu/Debian but the lack of apt-get suggests it is not. Figure out which OS you are using and the commands to install packages on it, and that may solve your problem.

**Comment by thekomx** [comment]
Try this:
```
sudo yum install gcc-c++
sudo yum install python3-devel
sudo yum install unixODBC-devel
sudo pip install pyodbc
```

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
