### ISSUE TITLE
Server Failed to resume transaction

### ISSUE THREAD

**Issue by narenvema** [mkleehammer/pyodbc#736]
**Environment**
To diagnose, we usually need to know the following, including version numbers. On Windows, be
sure to specify 32-bit Python or 64-bit:

Python: 3.5.2
pyodbc: 4.0.28
OS: Ubuntu 18.04
DB: Microsoft SQL Server
driver: ODBC Driver 17 for SQL Server

**Issue**
Hitting error SQL Server Failed to resume transaction, for Flask web app, production server. 

**Description**
I'm working on a Python Flask web application which runs on Ubuntu and MS SQL Server, for which i'm using pyodbc and SQLAlchemy for database connection and request handling. The code has 
a lot of database transaction, mostly SELECT, UPDATE, INSERT. The app seems to run fine when i run it on local server without any issues. But, when i run on a production's uwsgi web server, I've been constantly hitting the error, 

**(pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server Failed to resume transaction.]** 

![Capture](https://user-images.githubusercontent.com/38214589/78816656-aaec9f00-79ef-11ea-85c6-4d6bfeca7654.PNG)

I've changed my code several times, used sessions in SQLAlchemy, changed nginx config, but no matter what i do, nothing seems to work and I'm back at this error. I couldn't understand if this an issue with my code or a bug in pyodbc. Few snippets of code below,

**Database config:**
```
# Database Configurations #
engine = create_engine("mssql+pyodbc://sa:********@0.0.0.0/WDM?driver=ODBC+Driver+17+for+SQL+Server",
                       echo=False, isolation_level="SERIALIZABLE", strategy='threadlocal')
Base = declarative_base(bind=engine)
Session = sessionmaker(bind=engine, autocommit=True, expire_on_commit=True, autoflush=True)
sc_ss = scoped_session(Session)
db_session = Session()
connection = db_session.bind
```
**Get data:**
```
with db_session.bind as c9:
    states = pd.read_sql("select distinct a.StateID, a.statename from DeskStateMaster a, DeskUnitRegistration b "
                         "where a.StateID = b.StateID", c9)
    states = states.to_dict('records')
```

**Flask route sample:**
```
# Set Master Values #
@app.route('/set_master_data', methods=["GET","POST"])
def set_master_data():
    logged_user = str(session["username"]).capitalize()
    with db_session.bind as c9:
        master_data = pd.read_sql("select ID,ParameterName,ParameterLowValue,ParameterHighValue from DeskMasterData", c9)

    if request.method == "POST":
        # master_data = pd.read_sql("select ID,ParameterName,ParameterLowValue,ParameterHighValue from TestMasterData", engine)

        updates = []
        for key,value in master_data["ParameterName"].iteritems():
            updates.append({
                "ParameterName": value,
                "ParameterLowValue": request.form.get(str(value + " " + "Low")),
                "ParameterHighValue": request.form.get(str(value + " " + "High")) })

        df = pd.DataFrame(updates)
        for i in range(0, df.__len__()):
            with db_session.bind as c9:
                c9.execute("update DeskMasterData set ParameterLowValue={low}, ParameterHighValue={high} "
                           "where ParameterName = '{parameter}' ".format(
                parameter=df.iloc[i].ParameterName,
                low=float(df.iloc[i].ParameterLowValue),
                high=float(df.iloc[i].ParameterHighValue) ))
        if updates:
            message = "Master Values Updated"
        else:
            message = ""
        master_data = pd.DataFrame()
        return render_template('set_master_data.html', masterValues = master_data, message=message,
                               logged_user=logged_user)

    return render_template('set_master_data.html', masterValues = master_data, message="", logged_user=logged_user)
```
Please let me know if any more details are required, any help would be appreciated. 

Thank you.

**Comment by v-chojas** [comment]
Could you post an ODBC trace?

**Comment by narenvema** [comment]
> Could you post an ODBC trace?

I've followed the steps in this link _https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log_ and tried to generate trace, but isn't working. Any suggestions?

**Comment by v-chojas** [comment]
What version of unixODBC do you have? Run `odbcinst -j` to find out.

**Comment by narenvema** [comment]
> What version of unixODBC do you have? Run `odbcinst -j` to find out.

unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/rootadmin/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

**Comment by v-chojas** [comment]
Make sure the location of the tracefile is writable by the process.

**Comment by narenvema** [comment]
> Make sure the location of the tracefile is writable by the process.

This is the edit i made on odbcinst.ini

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1
Trace=yes
TraceFile=/tmp/odbctrace.txt

The trace file is writable by any.

**Comment by v-chojas** [comment]
You need to put it in the `ODBC` section, not the driver's section of the file.

**Comment by narenvema** [comment]
> You need to put it in the `ODBC` section, not the driver's section of the file.

I've tried everything, but the trace is not generated in the file mentioned.

**Changed odbcinst.ini:**

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1

[ODBC]
Trace=yes
TraceFile=/home/rootadmin/odbctrace.txt
ForceTrace=yes

What could be the problem??

**Comment by v-makouz** [comment]
Try ` sstrace python test.py 2>&1 | grep odbctrace.txt` and see what's the output

**Comment by narenvema** [comment]
> Try ` strace python test.py 2>&1 | grep odbctrace.txt` and see what's the output

[odbctrace.txt](https://github.com/mkleehammer/pyodbc/files/4458014/odbctrace.txt)

Thanks for your suggestion. 
Here's the output.

**Comment by v-makouz** [comment]
It doesn't seem like this trace even mentions the driver, is it executed on a different thread? If so, can you try `strace -f python test.py 2>&1 | grep odbctrace.txt` ?

**Comment by narenvema** [comment]
> It doesn't seem like this trace even mentions the driver, is it executed on a different thread? If so, can you try `strace -f python test.py 2>&1 | grep odbctrace.txt` ?

I've tried with your command but got the same kinda output. 

[-fodbc.txt](https://github.com/mkleehammer/pyodbc/files/4458310/-fodbc.txt)

I've tried yet again to change the odbcinst.ini file to trace, changes are,

[ODBC]
IANAAppCodePage=4
InstallDir=/opt/microsoft/msodbcsql17
Trace=yes
TraceFile=/opt/microsoft/msodbcsql17/etc/odbctrace.out
TraceDll=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1

This didn't work too. How could i know if my Flask application is using this driver? Please suggest.

**Comment by v-chojas** [comment]
It is only necessary to use Trace and TraceFile in the ODBC section, please remove everything else in that section as it will only confuse.

Try renaming the odbcinst.ini and see if you can still connect; if so, you are editing the wrong one.

(FYI - it is not necessary to quote every single post in your replies.)

**Comment by v-makouz** [comment]
This one does show the driver loading, as expected, but it doesn't even seem to try to write a trace file. It looks like it's using `/etc/odbcinst.ini`

If nothing else works, I'm afraid the only sure way investigating would be to compile unixODBC from source and step through with the debugger, to see what's going on with the traces (although I suspect if you did that the trace might just start working).

**Comment by narenvema** [comment]
Hello,

I've changed the ODBC section which didn't work. As suggested, I've renamed the odbcinst.ini and to my surprise I'm still able to connect to the database and run queries. I'm confused and have no clue of what went wrong. Is there any other way to find the root cause?

**Comment by narenvema** [comment]
I'm attaching the uwsgi log, if it can be of some help. 

[uwsgi.log](https://github.com/mkleehammer/pyodbc/files/4462705/uwsgi.log)

**Comment by v-chojas** [comment]
If you are still able to connect, it means the DM is using an odbcinst.ini somewhere else. If you use strace you should be able to see where it is, and also where the DM is (look for libodbc.so) --- I suspect you may have another DM installed somewhere else, and that is causing all the confusion.

**Comment by zzzeek** [comment]
we have another user experiencing this problem at https://github.com/sqlalchemy/sqlalchemy/issues/6073 .

**Comment by bilalahmadj110** [comment]
- [ ] jhj
- [ ] jkh

**Comment by adenbley** [comment]
I am having this issue.

I build up the sqla query, then execute it once with `.count()` and a second time with `.limit(nn).offset(nn).all()` (for pagination).

This fails often, but works often as well.

This is a flask, flask-sqlalchemy app. I have tried close() and rollback() in a loop with try/except to retry, and it simply errors on those commands as well. Any suggestions are most welcome.

unixODBC 2.3.11
SQLAlchemy==1.4.22
pyodbc==4.0.31

[odbctrace.log](https://github.com/mkleehammer/pyodbc/files/11969725/odbctrace.log)

**Comment by v-chojas** [comment]
> The transaction active in this session has been committed or aborted by another session.

This is the actual reason for the error. You will need to look carefully at the rest of the trace to see the other operations on the transaction.
