### ISSUE TITLE
Source for SQL Data Type integer codes?

### ISSUE THREAD

**Issue by MikeB2019x** [mkleehammer/pyodbc#737]
In your excellent documentation [here](https://github.com/mkleehammer/pyodbc/wiki/Using-an-Output-Converter-function) you make reference to an integer code for SQL 'datetimeoffset' (ie. -155).  I have looked and not found a single reference that can give me that or any of the other codes.  Could you provide a reference?

Thanks for that documentation btw.  Saved me a lot of time!

**Comment by v-chojas** [comment]
https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-date-time/data-type-support-for-odbc-date-and-time-improvements
