### ISSUE TITLE
pyodbc ignores exception after first result is sent

### ISSUE THREAD

**Issue by ffoersterchen** [mkleehammer/pyodbc#739]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.0, x64 (Anaconda 4.3.0) 
- pyodbc: 4.0.30
- OS: Windows 10 
- DB: SQL Server 2016
- driver: ODBC Driver 17 for SQL Server

### Issue

_Step 1_
Created a SQL Stored Procedure on SQL Server:
`CREATE PROC toFail 
AS BEGIN
SELECT 'abc' AS Col1;
THROW 50000, 'This is an error to be caught', 1;
END
`
_Step 2_
created python connection and cursor and executed the stored proc
`
import pyodbc
conn = pyodbc.connect('DRIVER={ODBC Driver 17 For SQL Server};SERVER=XXXX;DATABASE=YYYY;')
crsr = conn.cursor()
crsr.execute('EXEC toFail;')
`

Expected Behavior: pyodbc should raise an exception (ProgrammingError)
Observed Behavior: no exception, cursor has one row with a tuple of ('abc', )

Note: when commenting out the select, pyodbc raises an exception 
Note: when changing the SELECT to a PRINT pyodbc fails to raise an exception
Note: when executing another procedure in lieu of the SELECT or PRINT which will generate a resultset, pyodbc also fails to raise an appropriate exception.

please fix.

**Comment by v-chojas** [comment]
This is not a bug. The stored procedure returns two resultsets, the THROW is only in the second one. If you call cursor.nextset() you will see the error.

**Comment by ffoersterchen** [comment]
good to know. thanks.
