### ISSUE TITLE
Missing the output value from a SQL Server stored procedure performing a DB BACKUP

### ISSUE THREAD

**Issue by grap3-fru1t** [mkleehammer/pyodbc#740]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.0, 64 bit
- pyodbc: 4.0.30
- OS: Windows Server 2012
- DB: SQL Server 2012
- driver: ODBC Driver 17 for SQL Server

### Issue

I need to call a stored procedure from python. The stored procedure is performing a database backup; an output value is to be returned to python.

### SP:
```SET ANSI_NULLS ON 
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [util].[backup_db_] (
	 @pDB_name NVARCHAR(MAX)
	, @pBackup_name NVARCHAR(MAX)
	, @pBackup_path NVARCHAR(MAX)
	, @pErrorStatus NVARCHAR(MAX) OUTPUT	
)
AS
BEGIN
SET NOCOUNT ON
DECLARE @vDynamic_SQL_command NVARCHAR(MAX);	
SET @pErrorStatus = '0'		

	SET @vdynamic_SQL_command = '
		BACKUP DATABASE '+@pdb_name+'
		TO DISK = '''+@pbackup_path+@pbackup_name+'.Bak''';

EXEC(@vdynamic_SQL_command);
SET @pErrorStatus = '1'		

END
```

### Python:
```
conn = pyodbc.connect(self.master_conn_string, autocommit=True)
sql = """
SET NOCOUNT ON;
DECLARE @pErrorStatus nvarchar(max)
EXEC [util].[backup_db_] 
       @pDB_name = ?
	 , @pBackup_name = ?
	 , @pBackup_path = ?
        , @pErrorStatus = @pErrorStatus OUTPUT;
        SELECT @pErrorStatus;
        """
cursor = conn.cursor()
        
parameters = (self.ProjectID, "\\"+self.ProjectID + datetime.now().strftime('%Y_%m_%d_%H_%M_%S'), self.serverPathArchive)

cursor.execute(sql, parameters)
cursor.commit()
while (cursor.nextset()):
    pass
error = list(cursor.fetchall()[0])
conn.close()
```

I can see that the stored procedure is recognized correctly by pyodbc and the backup of the database is performed. It just has a problem with returning the output parameter.

### Traceback:
```
  File "Project.py", line 187, in backup_function
    error = list(cursor.fetchall()[0])
pyodbc.ProgrammingError: No results.  Previous SQL was not a query.
```

ODBC Trace:
[SQL_backup.LOG](https://github.com/mkleehammer/pyodbc/files/4476221/SQL_backup.LOG)

**Comment by v-chojas** [comment]
You have already reached the end of the resultsets with the `while(cursor.nextset())` loop, so fetchall() won't return anything. You need to read the value as it comes. Also, you should not commit() before reading the results, because you may get the result of the commit() instead of the original query.

**Comment by ArtiomZ** [comment]
Thanks for the answer. I only added the while loop after browsing the forums. Unfortunately the loop with cursor.nextset() makes no difference. It also doesn't seem to make a difference if I use the explicit commit() or not (probably since I am using autocommit=True anyway?).

I need to mention, that the same Stored Procedure works fine if it is called in SQL (the output variable is being displayed correctly). It was also working fine and I was receiving the output variable when calling the same SP with cursor.callproc() method from the pymssql package.

**Comment by v-chojas** [comment]
Could you post an ODBC trace of the execution?

**Comment by ArtiomZ** [comment]
I uploaded the ODBC trace at the end of the initial post.

**Comment by v-chojas** [comment]
Looking at the trace, the server returned 3 resultsets, and the last one does contain the single column select result that you want.

```
python AS01_Pro 2dec-4120	ENTER SQLNumResultCols 
		HSTMT               0x00000071B3F36830
		SWORD *             0x00000071B01ADC80

python AS01_Pro 2dec-4120	EXIT  SQLNumResultCols  with return code 0 (SQL_SUCCESS)
		HSTMT               0x00000071B3F36830
		SWORD *             0x00000071B01ADC80 (1) <--- 1 column

python AS01_Pro 2dec-4120	ENTER SQLFreeStmt 
		HSTMT               0x00000071B3F36830
		UWORD                        2 <SQL_UNBIND>

python AS01_Pro 2dec-4120	EXIT  SQLFreeStmt  with return code 0 (SQL_SUCCESS)
		HSTMT               0x00000071B3F36830
		UWORD                        2 <SQL_UNBIND>

python AS01_Pro 2dec-4120	ENTER SQLFreeStmt 
		HSTMT               0x00000071B3F36830
		UWORD                        3 <SQL_RESET_PARAMS>

python AS01_Pro 2dec-4120	EXIT  SQLFreeStmt  with return code 0 (SQL_SUCCESS)
		HSTMT               0x00000071B3F36830
		UWORD                        3 <SQL_RESET_PARAMS>

python AS01_Pro 2dec-4120	ENTER SQLDescribeCol 
		HSTMT               0x00000071B3F36830
		UWORD                        1 
		UCHAR *             0x00000071B01ADB30 
		SWORD                      200 
		SWORD *             0x00000071B01ADB1C
		SWORD *             0x00000071B01ADB10
		SQLULEN *           0x00000071B01ADB20
		SWORD *             0x00000071B01ADB18
		SWORD *             0x00000071B01ADB14

python AS01_Pro 2dec-4120	EXIT  SQLDescribeCol  with return code 0 (SQL_SUCCESS)
		HSTMT               0x00000071B3F36830
		UWORD                        1 
		UCHAR *             0x00000071B01ADB30 <zero length>
		SWORD                      200 
		SWORD *             0x00000071B01ADB1C (0)
		SWORD *             0x00000071B01ADB10 (-9) <-- NVARCHAR
		SQLULEN *           0x00000071B01ADB20 (0) <-- (MAX)
		SWORD *             0x00000071B01ADB18 (0)
		SWORD *             0x00000071B01ADB14 (1)
```
The number of previous resultsets depends on the number of messages about the backup the server sends before it is finished, but you could try retrieving the output after calling nextset() a varying number of times.

**Comment by ArtiomZ** [comment]
Thank you very much. The output variables are retrieved correctly in the 3rd resultset.

Do you know of an elegant way to achieve this not knowing the exact number of resultsets needed? I am currently using this:

```
while True:
    set_nr += 1
    try:
        errorstatus = list(cursor.fetchone())
        break
    # when resultset is empty, programming error occurs
    except pyodbc.ProgrammingError:
        print("ProgrammingError encountered on set {}".format(set_nr))
        if cursor.nextset():
            continue
    except Exception as exception:
        print("Another Exception encountered:{}".format(exception))
        break
```

**Comment by v-chojas** [comment]
As mentioned, the number of resultsets sent by the server will vary, since they're progress messages of the backup. Looping through is the only way to find out when you're at the last one that contains the result you want.

**Comment by grap3-fru1t** [comment]
Thanks, I think we can close this one.
