### ISSUE TITLE
Ticket Expired Error when connecting to SQL Server from Red Hat 8 using Active DIrectory Authentication

### ISSUE THREAD

**Issue by jrisi256** [mkleehammer/pyodbc#744]
### Environment

* Python: 3.7.6
* pyodbc: 4.0.30
* OS: Red Hat 8
* DB: SQL Server (and SQL Server Express)
* driver: ODBC Driver for 17 for SQL Server

### Issue

Hello! Thanks for making such a great package, and I hope you're staying safe and healthy during these difficult times.

Below is a screenshot detailing the error message I receive upon trying to connect to a particular server at my company using pyodbc.

![image](https://user-images.githubusercontent.com/9837612/79501013-5e125500-7ffb-11ea-9f04-2415c7af0958.png)

I don't believe there is an issue with the odbc.ini entry or the server itself because I'm able to connect to the server (from the machine in question) using the R programming language so I believe it has something to do with pyodbc.

Below is the relevant entry in the odbc.ini file (with sensitive information excluded).

```
[Projects]
Driver = ODBC Driver 17 for SQL Server
Description = Microsoft ODBC Driver 17 for SQL Server
Server = /* sensitive */
ServerSPN = /* sensitive */
Trusted_Connection = yes
```

I suspect the issue has something to do with the fact we authenticate users using our Active Directory system, and pyodbc has its "prompt" turned off by default. As a result, users aren't able to enter in their credentials. This is just a hunch though, and I figured I would submit this as an issue to see if you had any further insight into what may be causing the issue.

**Comment by v-chojas** [comment]
`Trusted_Connection=yes` will use Kerberos for authentication, and the message indicates the Kerberos ticket has expired. Check that the clock is correct and use the `kinit` command to request a new one.

See this document for more information: https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication

**Comment by jrisi256** [comment]
Thanks this solved it!
