### ISSUE TITLE
accessToken Issue.

### ISSUE THREAD

**Issue by Rakesh30** [mkleehammer/pyodbc#745]
Hi,
I am getting the below error. Does anyone have any idea?

here is the code I am using
context = adal.AuthenticationContext(authority_url, api_version=None)
token = context.acquire_token_with_client_credentials(
"https://database.windows.net/",
'xxxxxxxxxxxxxxxxxxx',
'xxxxxxxxxxxxxxxxxxx')
SQL_COPT_SS_ACCESS_TOKEN = 1256
connString = "Driver={ODBC Driver 17 for SQL Server};SERVER={xxxxxxxxx};DATABASE={xxxxxxx}"
#get bytes from token obtained
tokenb = bytes(token["accessToken"], "UTF-8")
exptoken = b'';
for i in tokenb:
exptoken += bytes({i});
exptoken += bytes(1);
tokenstruct = struct.pack("=i", len(exptoken)) + exptoken;

conn = pyodbc.connect(connString, attrs_before = { SQL_COPT_SS_ACCESS_TOKEN:tokenstruct});

"
TypeError Traceback (most recent call last)
in
18 tokenstruct = struct.pack("=i", len(exptoken)) + exptoken;
19
---> 20 conn = pyodbc.connect(connString, attrs_before = { SQL_COPT_SS_ACCESS_TOKEN:tokenstruct});

TypeError: connection string too long
"

**Comment by v-makouz** [comment]
The connection string length limit was removed a while ago, can you try using newer pyODBC?

see also: https://github.com/mkleehammer/pyodbc/issues/228#issuecomment-615942329

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
