### ISSUE TITLE
Issue Encoding DB Microsoft SQL 2008

### ISSUE THREAD

**Issue by lschneidpro** [mkleehammer/pyodbc#750]
### Environment
- Python: 3.6.1 64bits
- pyodbc: 4.0.30
- OS: win10
- DB: Microsoft SQL 2008
- driver: ODBC Driver 17 for SQL Server

### Issue
 Hi there,

I'm retrieving data from a Microsft SQL 2008 (enconding is 'cp1252') as shown up below. All is good except, I end up sometimes with `\xa0` within strings. I have been playing around with parameters:

```
pyodbc.SQL_CHAR
pyodbc.SQL_WCHAR
pyodbc.SQL_WMETADATA
```
But nothing seems to fix this.
What could i try with pyodbc before assessing there is issues with the DB.
Thanks a lot for your help

```
import pandas as pd
import pyodbc

con = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=' + server + ';PORT=' + port+";Trusted_Connection=yes;")
df = pd.read_sql(query, con)
con.close()
```

**Comment by v-chojas** [comment]
Could you explain more about what you mean by "I end up sometimes with `\xa0` within strings"? In 1252 that is a "nonbreaking space" character so if that was stored in the database, then that is what you will get.

**Comment by lschneidpro** [comment]
> Could you explain more about what you mean by "I end up sometimes with `\xa0` within strings"? In 1252 that is a "nonbreaking space" character so if that was stored in the database, then that is what you will get.

Most strings (Unicode?) returned look fine except some space of some strings are displayed as`\xa0` sometimes. How can I ensure to not have these`\xa0` and have spaces instead? I could clean the strings but I believe some connection parameters could be set.

**Comment by v-chojas** [comment]
This has nothing to do with pyODBC nor the driver: it is returning the data you have in the database exactly as it is.
If you want to change the data you can do that in Python.

**Comment by lschneidpro** [comment]
Isn't there an encoding issue from 1252 to utf8 to end up with such characters? I also noticed some '\u00a', '\u2019', '\u2013', '\u201c... As said I retrieve 99.9% characters correctly.

Thanks

**Comment by v-chojas** [comment]
That would be a newline, a "right single quote", "en dash", and "left double quote". All perfectly valid characters, and they are what you have stored in the database, so you should not be surprised that you see them being returned. In 1252 those are the bytes 0A, 92, 96, and 93 respectively. Once again, there is no issue here.

**Comment by lschneidpro** [comment]
ok I understood now. These are actually converted utf-8 displayed as such by terminal. So How can I adress this in python? I mean at a following step, I convert dictionnaries into json for http responses and theses unicode are still there.

**Comment by v-chojas** [comment]
In Python 3, strings are Unicode. I am still not sure what you are trying to accomplish, nor what the issue is.

**Comment by lschneidpro** [comment]
I'm working on ML project with an API deployment
the issues are:
1. These mentioned part of strings are still displayed as unicode (eg. "the\xa0dog") on my terminal.
2. When ouputing a JSON (API part), I have the same issue in the JSON (eg. "the\xa0dog")

2. I'm also wondering if it is not creating issues for my tokenizer to tokenize properly (ML part)

**Comment by lschneidpro** [comment]
I found the solution:
`new_str = unicodedata.normalize("NFKD", str)`

Please close the thread

**Comment by v-chojas** [comment]
As the opener of the issue, you can close it.

**Comment by keitherskine** [comment]
It sounds like you have non-ASCII characters in your source data (in your database).  If you want to replace those non-ASCII characters with ASCII characters (e.g. replace a non-breaking space with an ordinary space) then you're going to have to clean your data.  That can be done directly in the database if you wish, but if you want to cleanse the data in Python, you may want to consider using the [Unidecode](https://pypi.org/project/Unidecode/) module.  It is very handy for converting unicode text into ASCII text.  (You'll have to "pip install" it first, of course.)  Once the text is cleaned, you can then output it to JSON:
```
(py36) C:\Users\keith\Downloads\pyvenvs\py36\Scripts>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from unidecode import unidecode
>>> t = '\u00a0\u2019\u2013\u201c'
>>> t
'\xa0’–“'
>>> unidecode(t)
' \'-"'
>>>
```

**Comment by lschneidpro** [comment]
> It sounds like you have non-ASCII characters in your source data (in your database). If you want to replace those non-ASCII characters with ASCII characters (e.g. replace a non-breaking space with an ordinary space) then you're going to have to clean your data. That can be done directly in the database if you wish, but if you want to cleanse the data in Python, you may want to consider using the [Unidecode](https://pypi.org/project/Unidecode/) module. It is very handy for converting unicode text into ASCII text. (You'll have to "pip install" it first, of course.) Once the text is cleaned, you can then output it to JSON:
> 
> ```
> (py36) C:\Users\keith\Downloads\pyvenvs\py36\Scripts>python
> Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from unidecode import unidecode
> >>> t = '\u00a0\u2019\u2013\u201c'
> >>> t
> '\xa0’–“'
> >>> unidecode(t)
> ' \'-"'
> >>>
> ```

worked like a charm.

many thanks
