### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2: invalid start byte

### ISSUE THREAD

**Issue by paulsuk1982** [mkleehammer/pyodbc#755]
we are getting same error when connecting to IBM DB2 database, and tried the mentioned solution does not work in our env, while creating connection object getting this issue.

Traceback (most recent call last):
  File "test_as400.py", line 10, in <module>
    cnxn=pyodbc.connect(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2: invalid start byte

Python: 3.6 64 bit
pyodbc: 4.0.27
OS: "RHEL 7.7/Linux"
DB: as400 i series DB2 database
driver: db2 for i Access Client Solutions

Could you please have a look into the issue for DB2 connection and update your findings would be really appreciated.

**Comment by v-chojas** [comment]
What is the locale/character encoding of the connection string?

**Comment by paulsuk1982** [comment]
character encoding of connection string is utf-8 

and server locale setting is en_US.UTF-8

**Comment by v-chojas** [comment]
Could you post an ODBC trace? That will help determine where exactly that 0xa0 byte is coming from.

**Comment by paulsuk1982** [comment]
Hi All,

we replicated the issue in a new server environment where
installed pyodbc in python3.6 using pip install and everything works file,  different database API AS400, Teradata works fine.
After that uninstalled pyodbc using pip

and manually installed pyodbc using 
setup.py build 
setup.py install 

and system broke, pyodbc throwing illegal encoding error, and sometime throws error in unrecognizable characters,

and, after that
1. Uninstalled manual built pyodbc using python setup.py install --record files.txt and xargs rm -rf < files.txt, 
2. Installed using pip nothing works.

Is there any library binding with linux kernel when running install build, not sure, as pyodbc breaks after manual install.
Os version : RHEL 7
Hypervisor VM

pyodbc version 4.0.30
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 208-209: illegal encoding

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
SystemError: <class 'pyodbc.Error'> returned a result with an error set

Traceback (most recent call last):

    cnxn=pyodbc.connect(n)
pyodbc.InterfaceError: ('IM002', '[IM002] 䑛瑡䑡物捥嵴佛䉄⁃楬嵢䐠楲敶\u2072慍慮敧\u2072敍獳条\u2065楦敬渠瑯映畯摮\u202e汐慥敳挠敨正映牯琠敨瘠污敵漠\u2066湉瑳污䑬物椠\u206e潹牵漠扤\u2e63湩\u2e69툀\uea9b(SQLDriverConnect)')

**Comment by v-chojas** [comment]
Could you post an ODBC trace? That will help determine where exactly that 0xa0 byte is coming from.

**Comment by paulsuk1982** [comment]
Code is not generating any odbc trace, we tried to generate that,
I think it not invoking the odbc call, before even odbc driver manager call it’s complaining.

**Comment by v-chojas** [comment]
You can `strace` the Python to see if it is getting to the DM - if it is, you should see it open the `odbcinst.ini` and/or `odbc.ini` files.

Does the connection string contain non-ASCII characters?

**Comment by paulsuk1982** [comment]
Thanks for the suggestion, we traced out the strace file and identified the issue with the odbc config where the driver file name needs to be mentioned exclusively and now driver is called.

character encoding='latin-1' is working with numeric data, 

however string data is still coming with different encoding 
like below when writing column header descriptions using writer method.

"塆佐⍌ 

could you please suggest which encoding should work universally with numeric and strings data type connecting with as400 database ?

**Comment by v-chojas** [comment]
Asian characters where you don't expect them are usually a sign of data in a narrow encoding like UTF-8, CP1252, etc. being interpreted as UTF-16.

**Comment by paulsuk1982** [comment]
Could you please explain this a little bit more elaborated ? so are you saying that string data stored in as400 tables can't expressed in UTF-8 encoding ? we haven't seen this kind of behavior in python3.4 with pyodbc 3.0.4.

**Comment by paulsuk1982** [comment]
@v-chojas 
could you please further update on this ?
I am stuck here.

actually pyodbc is not parsing the sql text being passed to the driver program and in python 3.6 layer could see implicitly modulename: utf_16_le decode method is being called which is not the case in another server where pyodbc functions properly with various db drivers.


test_as400_36.py(30): print(cnxn)
<pyodbc.Connection object at 0x7f8668593618>
test_as400_36.py(32): curr=cnxn.cursor()
test_as400_36.py(36): '''
test_as400_36.py(37): params=("FXLCCN")
test_as400_36.py(40): curr.execute(sql)
 --- modulename: utf_16_le, funcname: decode
utf_16_le.py(16):     return codecs.utf_16_le_decode(input, errors, True)
 --- modulename: trace, funcname: _unsettrace

**Comment by paulsuk1982** [comment]
@v-chojas 

if you need I can provide you the entire mtrace log to take a look.

Thanks and Regards,
Sukanta

**Comment by gordthompson** [comment]
@paulsuk1982 - Can you do a simple `SELECT 1 AS FXLCCN`? (I don't know if DB2 supports SELECT without FROM.) 

Perhaps @kadler might have some insights on this.

**Comment by kadler** [comment]
> @paulsuk1982 - Can you do a simple `SELECT 1 AS FXLCCN`? (I don't know if DB2 supports SELECT without FROM.)

Db2 does not allow this - you would have to use the dummy table eg. `SELECT 1 AS FXLCCN FROM SYSIBM.SYSDUMMY1` or  use values `VALUES(1)`.

@paulsuk1982 You say you're using the IBM i Access driver, but the message is coming from DataDirect and there's some disconnect that it doesn't speak UTF-16:

```
echo '䑛瑡䑡物捥嵴佛䉄⁃楬嵢䐠楲敶慍慮敧敍獳条楦敬渠瑯映畯摮汐慥敳 挠敨正映牯琠敨瘠污敵漠湉瑳污䑬物椠潹牵漠扤'  | iconv -f UTF-8 -t UTF-16 | hexdump -C
00000000  ff fe 5b 44 61 74 61 44  69 72 65 63 74 5d 5b 4f  |..[DataDirect][O|
00000010  44 42 43 20 6c 69 62 5d  20 44 72 69 76 65 4d 61  |DBC lib] DriveMa|
00000020  6e 61 67 65 4d 65 73 73  61 67 66 69 6c 65 20 6e  |nageMessagfile n|
00000030  6f 74 20 66 6f 75 6e 64  50 6c 65 61 73 65 20 63  |ot foundPlease c|
00000040  68 65 63 6b 20 66 6f 72  20 74 68 65 20 76 61 6c  |heck for the val|
00000050  75 65 20 6f 49 6e 73 74  61 6c 6c 44 69 72 20 69  |ue oInstallDir i|
00000060  79 6f 75 72 20 6f 64 62  0a 00                    |your odb..|
```

I'm pretty sure you have something messed up in your setup. I'd make sure that pyodbc is linked to unixODBC and nothing else is injecting DataDirect in there via LD_PRELOAD or something.

**Comment by paulsuk1982** [comment]
@kadler 

Thanks for the update, it’s suspected that characterset conversion is having issue through driver manger,

Appreciate your help in converting the characters into UTF-16 using iconv utility which I was not aware.

Actually we installed teradata driver before in this system, so might be that is causing issue still libraries are linked,
Will look into further and will update.

But this is great help.

**Comment by gordthompson** [comment]
Related: #847

**Comment by paulsuk1982** [comment]
@gordthompson 
thanks for sharing the link of another similar issue that has been resolved #847 

we are hitting the same issue. Nice catch.
below the ldd output on the pyodbc so file.

`
ldd /home/pyadmin/.local/lib/python3.6/site-packages/pyodbc.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffe2d7ed000)
        libodbc.so => /lib64/libodbc.so (0x00007f6112a16000)
        libpython3.6m.so.rh-python36-1.0 => /opt/rh/rh-python36/root/usr/lib64/libpython3.6m.so.rh-python36-1.0 (0x00007f61124ef000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f61121e8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f6111ee6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6111cd0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6111ab4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f61116e6000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f61114de000)
        libodbcinst.so => /lib64/libodbcinst.so (0x00007f61112af000)
        libddicu27.so => /lib64/libddicu27.so (0x00007f61103b8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f61101b4000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f610ffb1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6112ee5000)

lrwxrwxrwx. 1 root root 47 Dec 24  2018 /lib64/libodbcinst.so -> /opt/teradata/client/15.10/lib64/libodbcinst.so
lrwxrwxrwx. 1 root root 43 Dec 24  2018 /lib64/libodbc.so -> /opt/teradata/client/15.10/lib64/libodbc.so
lrwxrwxrwx. 1 root root 46 Dec 24  2018 /lib64/libddicu27.so -> /opt/teradata/client/15.10/lib64/libddicu27.so

`
in my case its symlink which is pointing to the teradata so files.
if I rename /lib64/libodbcinst.so, /lib64/libodbc.so and /lib64/libddicu27.so code breaks

`

 python3.6
Python 3.6.9 (default, Sep 11 2019, 16:40:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libodbc.so: cannot open shared object file: No such file or directory


`
Even uninstall/reinstall pyodbc does not help, do we need to uninstall teradata packages those are installed ? 
or how to approach ?

**Comment by paulsuk1982** [comment]
thanks for all your help,
issue is resolved after rebuilding pyodbc with correct unixODBC libodbc.so file, so thanks for all your help, we can close this issue.

thanks @gordthompson for relating this issue to Related: #847, which helped in identifying the issue.

**Comment by paulsuk1982** [comment]
Good to close this issue.

**Comment by paulsuk1982** [comment]
Good to close this issue.

**Comment by Brinkss** [comment]
Hi, am installing klipper on a Gen L boad and come up with this error:- Decode Error:
'utf-8' codec can't decode byte 0xa0 in position 72: invalid start byte. Please convert your config files to utf-8!
Have been searching the net for answers, the story above is about the closest, so i checked my config files for cockroaches, or anything else that might have jumped in uninvited, to no avail.
Don't really understand the jargon above, so if someone could help that would be great.

**Comment by v-chojas** [comment]
What ODBC driver are you using? It doesn't sound like your question is related to pyODBC?

**Comment by Brinkss** [comment]
started writing to "printer.cfg" line by line
1 # See the example.cfg file for a description of available parameters.  :- This line worked file
2 #      :- this line pulled the error

File contence

# See the example.cfg file for a description of available parameters.
# 
[stepper_x]
step_pin: ar54
dir_pin: !ar55
enable_pin: !ar38
microsteps: 16
rotation_distance: 40
#step_distance: .0125
endstop_pin: ^ar3
position_endstop: 0
position_max: 235
homing_speed: 50
homing_retract_dist: 0
# 
[tmc2130 stepper_x]
uart_pin: ar40
microsteps: 16
rotation_distance: 40
interpolate: True
run_current: 0.760
sense_resistor: 0.110
stealthchop_threshold: 100
#
[stepper_y]
step_pin: ar60
dir_pin: !ar61
enable_pin: !ar56
microsteps: 16
rotation_distance: 40
#step_distance: .0125
endstop_pin: ^ar14
position_endstop: 0
position_max: 235
homing_speed: 50
homing_retract_dist: 0
# 
[tmc2130 stepper_y]
uart_pin: ar59
microsteps: 16
rotation_distance: 40
interpolate: True
run_current: 0.760
sense_resistor: 0.110
stealthchop_threshold: 100
#
[stepper_z]
step_pin: ar46
dir_pin: ar48
enable_pin: !ar62
microsteps: 16
rotation_distance: 40
#step_distance: .0025
endstop_pin:probe:z_virtual_endstop
position_max: 250
position_min: -1
#
[tmc2130 stepper_z]
uart_pin: ar44
microsteps: 16
rotation_distance: 40
interpolate: True
run_current: 0.760
sense_resistor: 0.110
stealthchop_threshold: 5
# 
[extruder]
max_extrude_only_distance: 100.0
step_pin: ar26
dir_pin: !ar28
enable_pin: !ar24
microsteps: 16
rotation_distance: 40
#step_distance: 0.010526
nozzle_diameter: 0.400
filament_diameter: 1.750
pressure_advance: 0.060
pressure_advance_lookahead_time: 0.010
heater_pin: ar10
sensor_type: EPCOS 100K B57560G104F
sensor_pin: analog13
#  Pin for filiment runout
#control: pid
# tuned for stock hardware with 200 degree Celsius target
#pid_Kp: 21.527
#pid_Ki: 1.063
#pid_Kd: 108.982
min_temp: 0
max_temp: 250
#
[heater_fan my_nozzle_fan]
pin: ar7
heater: extruder
heater_temp: 50.0
#
[tmc2130 stepper_extruder]
uart_pin: ar44
microsteps: 16
rotation_distance: 40
interpolate: True
run_current: 0.900
sense_resistor: 0.110
stealthchop_threshold: 0
#
[heater_bed]
heater_pin: ar8
sensor_type: EPCOS 100K B57560G104F
sensor_pin: analog14
control: pid
# tuned for stock hardware with 50 degree Celsius target
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 130
# 
[fan]
pin: ar9
#       /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
[mcu]
serial: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
pin_map: arduino
# 
[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100
# 
[display]
lcd_type: st7920
cs_pin: ar27
sclk_pin: ar25
sid_pin: ar29
encoder_pins: ^ar23, ^ar17
click_pin: ^!ar35
# 
[board_pins]
aliases:
    # Common EXP1 header found on many "all-in-one" ramps clones
    EXP1_1=ar37, EXP1_3=ar17, EXP1_5=ar23, EXP1_7=ar27, EXP1_9=<GND>,
    EXP1_2=ar35, EXP1_4=ar16, EXP1_6=ar25, EXP1_8=ar29, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=ar50, EXP2_3=ar31, EXP2_5=ar33, EXP2_7=ar49, EXP2_9=<GND>,
    EXP2_2=ar52, EXP2_4=ar53, EXP2_6=ar51, EXP2_8=ar41, EXP2_10=<RST>
    # Pins EXP2_1, EXP2_6, EXP2_2 are also MISO, MOSI, SCK of bus "spi"
    # Note, some boards wire: EXP2_8=<RST>, EXP2_10=ar41
# 
[bltouch]
sensor_pin: ^ar18
control_pin: ar11
x_offset: -45
y_offset: -10
z_offset: 1.6
pin_move_time: 0.4
# 
[bed_mesh]
speed: 80
horizontal_move_z: 5
min_point: 90, 20
max_point: 235, 235
probe_count: 3,3
fade_start: 1.0
mesh_pps: 2,2
# 
[gcode_macro G29]
gcode:
    BED_MESH_CALIBRATE
#
[safe_z_home]
home_xy_position: 155,120
speed: 80.0
z_hop: 10.0
z_hop_speed: 10.0
# 
#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [extruder]
#*# control = pid
#*# pid_kp = 30.662
#*# pid_ki = 2.350
#*# pid_kd = 100.035

seems to be a syntax problem?

**Comment by v-chojas** [comment]
That clearly has absolutely nothing to do with pyODBC nor even ODBC, so this is the wrong place to ask.

**Comment by Brinkss** [comment]
where do  go for help with this

**Comment by Brinkss** [comment]
thanks heaps for your help

**Comment by rockyrockstars** [comment]
> thanks for all your help, issue is resolved after rebuilding pyodbc with correct unixODBC libodbc.so file, so thanks for all your help, we can close this issue.
> 
> thanks @gordthompson for relating this issue to Related: #847, which helped in identifying the issue.

Can you tell what is the resolution?
