### ISSUE TITLE
Invalid parameter type

### ISSUE THREAD

**Issue by DCyph** [mkleehammer/pyodbc#756]
### Environment

- Python:  3.8 32-bit
- pyodbc: 4.0.30
- OS: Windows 10
- DB: SQL Server 18
- driver: SQL Server

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

Returning the following error when attempting to insert data into a table - 

**pyodbc.ProgrammingError: ('Invalid parameter type.  param-index=0 param-type=set', 'HY105')**

I presume the error is referring to the first parameter (_the query uses 24 parameters_), and is used to populate a column with an INT datatype.

**Comment by keitherskine** [comment]
The error message you are getting would suggest you are trying to write a Python [set](https://docs.python.org/3.8/library/stdtypes.html#set-types-set-frozenset) object to the database.  Assuming your Python code is something like as described in the [wiki](https://github.com/mkleehammer/pyodbc/wiki/Cursor#executesql-parameters), check your code to make sure the first parameter value in your parameter list is definitely an integer.

**Comment by DCyph** [comment]
Thanks for the response.. Its most definitley an integer. It's making me lose my mind lol

` cursor.execute("INSERT INTO <table> (<columns>)"
               
                       "VALUES( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?, ? )",
                       {self.id},
			.....
                       )


c = Class(
    10000,
    ....
	)

c.function()`

**Comment by keitherskine** [comment]
The use of curly brackets around `self.id` turns it into a Python set:
```
>>> type(1)
<class 'int'>
>>> type({1})
<class 'set'>
```
Try removing the curly brackets and using just `self.id`.

**Comment by DCyph** [comment]
Thank you so much.... I'm such a rookie lol
