### ISSUE TITLE
ius or epel for pyodbc??Python.h no such file or directory , python36u-3.6.8-1.el7.ius.x86_64 conflicts with file from package python36-3.6.6-1.el7.x86_64

### ISSUE THREAD

**Issue by divyalakshmi24** [mkleehammer/pyodbc#758]
I am using
- Python: Python 3.6.6
- OS: "CentOS Linux 7 (Core)"

following steps in https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-RHEL-6-or-Centos-7

 got results till  the step
# check the DSN installation with:
odbcinst -j

unixODBC 2.3.1
DRIVERS............: /usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources
USER DATA SOURCES..: /usr/local/etc/odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

cat /etc/odbc.ini
 returned header

pip install pyodbc
Requirement already satisfied: pyodbc in /usr/lib64/python2.7/site-packages (4.0.30)
Could not build wheels for pyodbc, since package 'wheel' is not installed.

But i want to execute  the code using python3.6 
     ModuleNotFoundError: No module named 'pyodbc'

So tried 
python3.6 pip install pyodbc 
 #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

then tried
yum install python36u-devel
file /usr/bin/python3.6m from install of python36u-3.6.8-1.el7.ius.x86_64 conflicts with file from package python36-3.6.6-1.el7.x86_64

Kindly help.
should i need ius repo ,is epel not supported

**Comment by gordthompson** [comment]
Try installing pyodbc as documented here:

https://github.com/mkleehammer/pyodbc/wiki/Install#centos-7

**Comment by v-chojas** [comment]
Also note that unixODBC 2.3.1 is a very old version and quite buggy - the latest is 2.3.7.

**Comment by divyalakshmi24** [comment]
1. sudo yum install python-pip gcc-c++ python-devel unixODBC-devel

Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repo.ialab.dsu.edu
 * epel: mirror.vcu.edu
 * extras: reflector.westga.edu
 * ius: mirror.ehv.weppel.nl
 * updates: repo.ialab.dsu.edu
Package python2-pip-8.1.2-12.el7.noarch already installed and latest version
Package gcc-c++-4.8.5-39.el7.x86_64 already installed and latest version
Package python-devel-2.7.5-88.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package unixODBC-devel.x86_64 0:2.3.7-1.rh will be installed
--> Processing Dependency: unixODBC = 2.3.7 for package: unixODBC-devel-2.3.7-1.rh.x86_64
--> Running transaction check
---> Package unixODBC.x86_64 0:2.3.7-1.rh will be installed
--> Finished Dependency Resolution

2. NOW python --version
python 2.7.5

3. running my python script
 python example.py
('01000', u"[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")

checked symbolic link

 sudo ln -s /usr/local/etc/odbcinst.ini /etc/odbcinst.ini
ln: failed to create symbolic link ‘/etc/odbcinst.ini’: File exists
 sudo ln -s /usr/local/etc/odbc.ini /etc/odbc.ini
ln: failed to create symbolic link ‘/etc/odbc.ini’: File exists


4. but when i run as 
pthon3.6 example.py

ModuleNotFoundError: No module named 'pyodbc'


Odbc inst is  2.3.7 
on execution with python 2.7.5 , " Can't open lib 'ODBC Driver 13 for SQL Server" error occurs
on execution with python3.6 "No module named 'pyodbc'"

Kindly help me on this issue.

**Comment by v-chojas** [comment]
You need to install an ODBC driver, and if you want to use pyODBC with Python 3, then you need to also install the pyODBC for that Python.
Please read the documentation.

**Comment by divyalakshmi24** [comment]
yes odbc driver 2.3.7 is installed.
then sudo yum install python36u-devel gives 

"from file /usr/lib/python3.6/site-packages/pip/vcs/__pycache__/subversion.cpython-36.pyc from install of python3-pip-9.0.3-7.el7_7.noarch conflicts with file from package python36u-pip-9.0.1-1.ius.centos7.noarch"

**Comment by v-chojas** [comment]
That's not an ODBC driver version, that's just the driver manager.
You still need to install an ODBC driver too.
It looks like you already have pip installed from one package, so don't try to install it again from another.

Please, read the documentation carefully.

**Comment by divyalakshmi24** [comment]
Thanks alot!! code works fine with python2.7.5( which python --version is pointing) but unable to run with python3.6 ( any suggestions please)

**Comment by divyalakshmi24** [comment]
got it resolved using the following link, 

"https://community.centminmod.com/threads/python-conflict-on-update.17144/ " .

 which says "For CentOS 7, don't use IUS Community YUM Repo's python34u and python36u packages installed from addons/python34_install.sh and addons/python36_install.sh but instead use CentOS 7's EPEL yum repo versions of python34 and python36."

**Comment by divyalakshmi24** [comment]
it worked after removing ius repo and going with epel for centos 7
"https://community.centminmod.com/threads/python-conflict-on-update.17144/ " .
