### ISSUE TITLE
Stored Procedure parameters with TABLE Types

### ISSUE THREAD

**Issue by sjhughes77** [mkleehammer/pyodbc#759]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8
- pyodbc: 4.0.30
- OS: Windows 10 x64
- DB: SQL Server 2019
- driver: 17

### Issue

I created a TABLE Type and am trying to pass it into a stored procedure with other parameters, e.g. a VARCHAR(45) field.  If I call the stored procedure with just the Type as a parameter. it works OK.  If I add any other parameters, the result is  **Invalid string or buffer length (0) (SQLBindParameter)**.
It  would appear that pyodbc can only call a stored procedure with a table type OR other parameters but not both. 
 I modified the test script from GitHub as follows:
CREATE PROCEDURE [SelectTVP] @name VARCHAR(45), @TVP TestTVP READONLY,  @description VARCHAR(45) AS SELECT * FROM @TVP;

result_array = self.cursor.execute("exec SelectTVP ?, ?, ?",['XXXX', [param_array], 'DDDD']

Result text: Exception: [Error] ('HY090', '[HY090] [Microsoft][ODBC Driver Manager] Invalid string or buffer length (0) (SQLBindParameter)')

**Comment by gordthompson** [comment]
Have you seen [this post](https://github.com/mkleehammer/pyodbc/issues/732#issuecomment-605996193)? It provides a (working) [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by sjhughes77** [comment]
That link  states "when the Type table is not in the dbo schema"; I am using a TABLE Type.
When I couldn't get my application to work, I added two parameters to the unittest example 
https://github.com/mkleehammer/pyodbc/blob/969ea2c42712036d473fab5d4db715452580c6d3/tests3/sqlservertests.py#L1647

as shown above and the result.

**Comment by sjhughes77** [comment]
OK, managed to get it to work with the following changes.

I'd initially used this line to call the procedure:
cursor.execute('{CALL RegisterScript(?, ?, ?, ?)}', [environment, package_name, script_name, [actions]])

Using the example from #732, I changed it to:
    actions = []
    actions.append(['Coverage' , 'generate', 'Generation'])
    actions.append(['Coverage' , 'report', 'Report'])

    params = (environment, package_name, script_name, actions)
    sqlCmd = "execute [tafpy].[RegisterScript] ?, ?, ?, ?"
    cursor.execute(sqlCmd, params)

Interesting that instead of params being an array, it is just bracketed and instead of CALL,I used EXECUTE.

**Comment by sjhughes77** [comment]
Thanks to @gordthompson for giving me the helpful link.
