### ISSUE TITLE
"SHOW GRANTS" returns right number of results, but results are blank.

### ISSUE THREAD

**Issue by logan-jones** [mkleehammer/pyodbc#76]
Python 3.4.3, MariaDB 10.0.21, MariaDB ODBC Connector 1.0.0, pyodbc 3.0.10, all 64-bit on 64-bit Windows 7 SP1. Works perfectly in perl using DBI. Script is as follows:

	db = pyodbc.connect(driver = "{MariaDB ODBC 1.0 Driver}",
					server = "localhost", uid = "test",
					pwd = "test", autocommit = True)

	cursor = db.cursor()

	cursor.execute("SHOW GRANTS;")
	rows = cursor.fetchall()
	for row in rows:
		print(row)

	db.close()

Should return two grants for user "test" as it does in perl. Instead, returns the following:

    ('', )
    ('', )

**Comment by mkleehammer** [comment]
Hmmm..

I'm getting this:

    ("GRANT USAGE ON *.* TO ''@'localhost'", )

I'm using Python 3.5 with libmyodbc5w 05.03.0004

I think this, like a few other issues, is related to Unicode.  I've been trying to get time to add two new settings to control the encoding.  In the meantime, is your database using utf-8?

**Comment by mkleehammer** [comment]
I am pretty sure this is a Unicode issue.  I'm going to close this to replace with #112 so all discussions can be gathered in one place.  Please subscribe to that one for updates.
