### ISSUE TITLE
pyodbc.ProgrammingError: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Sintaxis incorrecta cerca de 'Gaitón'. (102) (SQLExecDirectW)")

### ISSUE THREAD

**Issue by manel00** [mkleehammer/pyodbc#760]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7
- pyodbc: 4.0.30
- OS: Windows 10
- DB: SQL Server
- driver: -
- IDE: PyCharm

### Issue

Error in the title, i'm trying to add an insert with accents and these spanish things but it pisses me off because don't know how to deal it on python, can you help me with this please? thank you so much

UPDATE:

Close the issue, i already realized what happened, by error PyCharm was taking me the Python 2.7 instead of 3.8, and was giving me strange errors, im sorry, now it works

**Comment by keitherskine** [comment]
The error message states there is a syntax error in your SQL.  Are you able to run your SQL statement separately, e.g. in SQL Server Management Studio?  I would start there.

If you can run your SQL statement on its own, it would help considerably to see the Python code you are trying to run.

**Comment by v-chojas** [comment]
_On Windows, be sure to specify 32-bit Python or 64-bit_

You also need to provide details on which driver you are using. It could be a character encoding issue, or actual incorrect SQL syntax. We don't know if you don't give us more information.

**Comment by keitherskine** [comment]
If you've managed to solve your problem, @manel00 , do please close this issue.  Many thanks!
