### ISSUE TITLE
inst -j

### ISSUE THREAD

**Issue by karlmoad** [mkleehammer/pyodbc#761]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 
- pyodbc: 
- OS: 
- DB:
- driver:

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by v-chojas** [comment]
@karlmoad did you accidentally submit this issue when you were intending to type `odbcinst -j` in another window...?

**Comment by karlmoad** [comment]
yes my apologies

**Comment by keitherskine** [comment]
No worries, @karlmoad , these things happen.  But in that case, could you close this issue.  Many thanks!

**Comment by karlmoad** [comment]
Issue opened in error.
