### ISSUE TITLE
pyodbc Cursor execute method doesn't wait for Stored procedure to finish

### ISSUE THREAD

**Issue by Verbato** [mkleehammer/pyodbc#762]
I am working on the project where I have a lot of stored procedures and I need execute method wait for the Stored Procedure to finish.

Solution like this https://github.com/mkleehammer/pyodbc/wiki/Calling-Stored-Procedures doesn't work for me since SPs don't return results.

**Comment by gordthompson** [comment]
I am unable to reproduce your issue:

```python
import time

import pyodbc

""" test environment:
CREATE TABLE [dbo].[pyodbc_762](
    [id] [int] NOT NULL,
    [n] [int] NULL,
PRIMARY KEY CLUSTERED 
(
    [id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE PROCEDURE mysp_pyodbc_762 
AS
BEGIN
    SET NOCOUNT ON;
    WAITFOR DELAY '00:00:20';
    UPDATE pyodbc_762 SET n = n + 1;
END
GO
"""
cnxn = pyodbc.connect("DSN=mssqlLocal", autocommit=True)
crsr = cnxn.cursor()
t0 = time.time()
crsr.execute("{CALL mysp_pyodbc_762}")
print(f"elapsed time {(time.time() - t0):0.1f} seconds")
# elapsed time 20.0 seconds
```

**Comment by Verbato** [comment]
Try with BACKUP DATABASE SQL command inside the Store procedure:

```
CREATE PROCEDURE mysp_pyodbc_762 
AS
BEGIN
    SET NOCOUNT ON;
    BACKUP DATABASE master TO DISK = 'C:\backup\master.bak' WITH NOFORMAT, INIT, SKIP, NOREWIND, NOUNLOAD,  STATS = 10
END
GO
```
Backup of my master database is about 5GB and pyodbc exit before it finished

**Comment by gordthompson** [comment]
Does it make any difference if you add a simple statement like `SELECT 1 AS foo` after the `BACKUP` statement?

**Comment by Verbato** [comment]
If I add `SELECT 1 AS foo` after backup it will result in error when execute method 'fetchone' . Second option is to iterate in infinite loop according to [solution](https://github.com/mkleehammer/pyodbc/wiki/Calling-Stored-Procedures) but some stored procedures make take an hour or more and that is not good for CPU load. 

I put `time.sleep()` inside loop and `fetchval()` didn't get `SELECT..` output for every time.sleep() argument..
I read somewhere that pyodbc recognize output from `PRINT `function as the result of Stored Procedure, is that true and can we get away from that since we don't have control over `BACKUP ` SQL command?

**Comment by gordthompson** [comment]
Related: #471

**Comment by v-chojas** [comment]
Note that in your initial post you should specify more details about your environment --- it really helps us provide more assistance that way.

This is yet another manifestation of the common "failure to consume resultsets" issue. You need to continue consuming resultsets as the server returns them, otherwise the server will fill up its output buffer and be blocked waiting for you to read them.

Also related: https://github.com/microsoft/msphpsql/issues/932

**Comment by keitherskine** [comment]
I dare say this has probably been discussed before, but it does seem there's a decent case for having some sort of "fetchmsgs()" function for cursor objects. The purpose of this function would be to retrieve all non-data messages returned by the database, e.g. warnings, errors, PRINT() statements, etc.  It would call SQLGetDiagRec and return whatever diagnostic messages were available at the time, in a Python list.  (Error handling would continue to call SQLGetDiagRec as before to get the error messages).

I realize this functionality is beyond PEP-249, but this does seem quite a glaring omission from that spec.

**Comment by gordthompson** [comment]
@keitherskine - #495

**Comment by keitherskine** [comment]
Thank you, @gordthompson !  I had a suspicion this had been discussed before.  And what's more, PEP-249 had considered this idea too.  Thank you for the correction on both counts.

**Comment by Verbato** [comment]
> Note that in your initial post you should specify more details about your environment --- it really helps us provide more assistance that way.
> 
> This is yet another manifestation of the common "failure to consume resultsets" issue. You need to continue consuming resultsets as the server returns them, otherwise the server will fill up its output buffer and be blocked waiting for you to read them.
> 
> Also related: [microsoft/msphpsql#932](https://github.com/microsoft/msphpsql/issues/932)

Sorry, this is my first posting issue please don't blame for the lack of the info in the initial comment. Thank you for this link.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
