### ISSUE TITLE
Different encoding for metadata (e.g., column names) and error messages - Impala

### ISSUE THREAD

**Issue by 1ira** [mkleehammer/pyodbc#764]
### Environment

- Python: 3.7
- pyodbc: 4.0.30
- OS: Ubuntu 18.04
- DB: Impala
- driver: Cloudera impala ODBC driver 2.06.05

### Issue

When fetching data from impala connection, i have issue when incorrect column names are returned, such as:
after running curor.describe, i see one of my column names as: `a\x00r\x00e\x00n\x00a\x00_\x00m\x00e`.

The problem is, that there are 1) obscure numbers and slashes, 2) part of the names is missing.
I can solve the column names by changing the decoding like:
`conn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-32')`

And then i get correct column names, however if i run an invalid query, i get a `System Error` instead of appropriate impala error, because the error message is encoded with `utf-16` instead of `utf-32`.

This behavior makes is very difficult to debug sql queries, i believe it would be very helpful to have ability to set decoding for column names and error messages separately.

If you know any other solution, please let me know, i would gladly fix it on my side, i just have no idea how.

**Comment by 1ira** [comment]
In the meantime, if there is anyone else with a similar issue i found a rather stupid workaround, i wrote a wrapper which can first run "explain [query]" with decoding set to utf-16 and if it doesn't throw an error it submits the query with decoding set to utf-32. Thus, if the result of my query is an impala error, i am getting the appropriate error message from impala, whereas otherwise i get the non-truncated column names.

I'd still like to see a better solution, which i think would come via ability to set the 2 decoding options separately.

**Comment by keitherskine** [comment]
Not a stupid workaround at all, @1ira , indeed it's very creative.

I agree, there is something of a case for having two decoding options, one for the database metadata (i.e. for column descriptions and other database calls like `primaryKeys()`), and one for error messages and other warnings generated by the database (i.e. the Diagnostic Records).

**Comment by 1ira** [comment]
@keitherskine and do you please know if there is some chance to have it implemented any time soon? :)

**Comment by keitherskine** [comment]
Unfortunately, @1ira , I doubt this will be implemented anytime soon.  If I were you, I would stick with your workaround for now.  Using EXPLAIN is actually a rather neat solution (but I agree it would be nice if you didn't have to do it all).  You could also raise this issue with Cloudera if you like. 
 After all, it's their driver that has this somewhat inconsistent behavior.

**Comment by 1ira** [comment]
I agree it's more of a Cloudera issue than pyodbc, however even if i convince Cloudera to fix it, i would then probably need to convince the dwh guys in our company to update impala. I think persuading both of these entities that i need these updates is an uphill battle.

**Comment by quinnj** [comment]
Forgive the drop in, but while debugging [my own issue](https://github.com/JuliaDatabases/ODBC.jl/issues/291), I came across this issue and thought I'd post the solution in case it's helpful.

In the impala ODBC docs, I came across discussion of the `DriverManagerEncoding` setting that is shipped with the driver.
<img width="701" alt="Screen Shot 2020-06-05 at 12 18 22 PM" src="https://user-images.githubusercontent.com/2896623/83910200-5cc1f680-a727-11ea-95b3-f741cfcae9e9.png">
It turns out that it sets the default to `UTF-32` by default, even for unixODBC (which is usually _not_ compiled for UTF32 support). By editing that file (`/opt/cloudera/impalaodbc/lib/64/cloudera.impalaodbc.ini`), and changing to `DriverManagerEncoding-UTF-16`, now all the column names/error messages/etc are coming back as expected.

**Comment by keitherskine** [comment]
This is hugely useful, @quinnj , many thanks indeed!

For reference, the document @quinnj cites is a pdf that can be found here:
https://www.simba.com/wp-content/uploads/2014/01/Simba-ODBC-Driver-for-Cloudera-Impala-Install-Guide1.pdf
(page 11)

**Comment by keitherskine** [comment]
@1ira , did you have a chance to try the idea described by @quinnj above?  That is, adding `DriverManagerEncoding=UTF-16` to your cloudera.impalaodbc.ini file?  If so, did it fix your issue with mismatching encodings in the column names and error messages?
