### ISSUE TITLE
Connection to sql server working from container but not from aws lambda

### ISSUE THREAD

**Issue by nrjchnd2** [mkleehammer/pyodbc#769]
Hi All,

I am trying to establish a connection with sql server from aws lambda function. Was following this blog [https://medium.com/faun/aws-lambda-microsoft-sql-server-how-to-66c5f9d275ed](url). The only difference is that I am using python 3.8 image for lambda CI as well as my aws lambda function is also using python 3.8 runtime.  The connection works just fine from inside of a container but fails when I zip the code to aws lambda. 

I have looked everywhere but didn't find any solution.  Below is the error which I get on aws lamda.

```
START RequestId: 6f3ec44e-aac0-4cc3-b5ed-f8935c4dff4d Version: $LATEST
[ERROR] Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/var/task/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2' : file not found (0) (SQLDriverConnect)")
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/test.py", line 9, in <module>
    conn=pyodbc.connect("DRIVER={ODBC Driver 13 for SQL Server};SERVER=***;PORT=1433;DATABASE=***;UID=***;PWD=***")END RequestId: 6f3ec44e-aac0-4cc3-b5ed-f8935c4dff4d
REPORT RequestId: 6f3ec44e-aac0-4cc3-b5ed-f8935c4dff4d  Duration: 1583.04 ms    Billed Duration: 1600 ms    Memory Size: 128 MB Max Memory Used: 15 MB  
Unknown application error occurred
```
When I put below code in python file, I can see that the file is indeed present there.
```
arr = os.listdir('/var/task/msodbcsql/lib64')
print(arr)
```
output - libmsodbcsql-13.1.so.9.2

More details : [https://stackoverflow.com/questions/62001501/sql-server-connection-works-fine-from-lambda-container-but-fails-after-uploading?noredirect=1#comment109660362_62001501](url)

**Comment by v-chojas** [comment]
The "file not found" message will still occur if the library is present but one of its dependencies (recursively) couldn't be found. You can try to `strace` it to see what else it can't find.

**Comment by nrjchnd2** [comment]
I was able to resolve this issue by using python 3.7 instead of 3.8 . Along with it, used msodbcsql17 instead of msodbc. It resolved the issue for me and now I am able to connect to sql server from aws lambda. Please refer to the SO post given above for more details.
