### ISSUE TITLE
__enter__ attribute error while using context managers in pyodbc connection

### ISSUE THREAD

**Issue by InsaneDhina** [mkleehammer/pyodbc#770]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.7.2
- pyodbc: 4.0.30
- OS: Windows 10 64 bit
- DB: MSSQL Local DB
- driver: SQL Server Native Client 11.0

### Issue
 I am trying to extract a table using pyodbc package from Python with context managers.

it is a pretty simplecode, but eventhough I have coded the__enter__ method I am receiving __enter__ Attribute error. does pyodbc support python context Managers?

Code:
```

import pyodbc

posts = {}


class DataBaseConnection:
    def __init__(self):
        self.connection = None

    def __enter__(self):
        self.connection = pyodbc.connect("""Driver={SQL Server Native Client 11.0};"
                      "Server=(LocalDB)\LocalDBDemo;"
                      "Database=pythondev;"
                      "Trusted_Connection=yes;""")
        return self.connection

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type or exc_tb or exc_tb:
            self.connection.close()
        self.connection.commit()
        self.connection.close()


with DataBaseConnection as connection:
    cursor = connection.cursor
    cursor.execute('SELECT * FROM tblpost')
    for row in cursor.fetchall():
        dtlist = list(row)
        posts[dtlist[0].strip()] = {'id': dtlist[0].strip(), 'title': dtlist[1], 'content': dtlist[2]}

print(posts)
```

```
C:\Users\Lenovo\PycharmProjects\import_project\venv\Scripts\python.exe C:/Users/Lenovo/PycharmProjects/dbcheck/app.py
Traceback (most recent call last):
  File "C:/Users/Lenovo/PycharmProjects/dbcheck/app.py", line 24, in <module>
    with DataBaseConnection as connection:
AttributeError: __enter__
Process finished with exit code 1
```

 
Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by keitherskine** [comment]
Hi @InsaneDhina , try: `with DataBaseConnection() as connection:` rather than `with DataBaseConnection as connection:`.

`DataBaseConnection` is the class itself, `DataBaseConnection()` is an instance of the class.

**Comment by keitherskine** [comment]
If this issue has been resolved, @InsaneDhina , do please help us out by closing it.  Many thanks!

**Comment by InsaneDhina** [comment]
Thankyou @keitherskine It has been resolved
