### ISSUE TITLE
Question: ODBC API

### ISSUE THREAD

**Issue by odinuv** [mkleehammer/pyodbc#771]
Hi,
while checking behavior ODBC drivers with respect to preparing statements, I came across this comment https://github.com/mkleehammer/pyodbc/blob/b4ea03220dd8243e452c91689bef34823b2f7d8f/src/cursor.cpp#L608 It suggests that the current behavior (not always preparing a query) is not truly intentional.
In comparison with ODBC drivers in other languages, this is a bit strange, because they strongly differentiate between preparing and executing a query. This is part of the [ODBC standard](http://www.simba.com/wp-content/uploads/2016/03/ODBC_specification.pdf) (pages 80-82 are relevant).

The [pypi](https://pypi.org/project/pyodbc/) page clearly states that pyodbc implements the [PEP-249 standard](https://www.python.org/dev/peps/pep-0249) so there is no issue here. But that is what makes it difficult, because PEP-249 doesn't have the concept of prepare and execute of statements and is somewhat contradictory to the ODBC standard. However the current behavior of pyodbc seems to reasonably match the ODBC behavior. So my question is - what is your stance towards this? 

I understand that this is possibly a very open ended question. My background is that I use different programming languages and the python ODBC API is a bit surprising - because it's not ODBCish, but Pythonish.

**Comment by gordthompson** [comment]
Related: #527

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with new information if necessary.
