### ISSUE TITLE
Migrate Travis CI from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by keitherskine** [mkleehammer/pyodbc#778]
It appears GitHub pyodbc is still using travis-ci.org.  The following link works:
https://travis-ci.org/github/mkleehammer/pyodbc
but this link does not:
https://travis-ci.com/github/mkleehammer/pyodbc

Travis has been [migrating](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps) open-source projects from travis-ci.org to travis-ci.com for some time now.  One consequence of still being on travis-ci.org is that travis-ci.org doesn't detect commits and pull requests so well, so you don't see the results of the Travis CI jobs for each commit.

@mkleehammer , when you get a chance, please could you migrate pyodbc to travis-ci.com.  Instructions are here:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository
Many thanks!

**Comment by keitherskine** [comment]
Just a gentle reminder to @mkleehammer that the ".org" version of Travis shut down at the end of last year (or at least went into read-only mode):
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions

To use Travis from now on, pyodbc must be migrated to travis-ci.com.  Instructions are here:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository

**Comment by mkleehammer** [comment]
Thanks so much for that.  I need to study up on Travis CI and see what all is available.  I've migrated the repo and triggered a new build.  Let me know if I missed anything important.

**Comment by keitherskine** [comment]
Many thanks, @mkleehammer !  Looks good.
