### ISSUE TITLE
Issue with connecting to paradox 

### ISSUE THREAD

**Issue by pilotkid** [mkleehammer/pyodbc#78]
I am attempting to use `pyobdc` to read data from a paradox database. But I keep getting the following error when attempting to connect to the database.

**Error:**

```
pyodbc.Error: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
```

I have tried to create new DNS links for the database but it has not helped what so ever.

**My system links looks like this:**![This is what the system DNS looks like](http://i.stack.imgur.com/KZ3cD.png)

**My code is:**

```
import os
import sys
import time
import pyodbc

LOCATION = "c:\Users\Marcello\Desktop\DATA\ScorMonitor.db"

cnxn = pyodbc.connect(r"Driver={{Microsoft Paradox Driver (*.db )}};Fil=Paradox 5.X;DefaultDir={0};Dbq={0}; CollatingSequence=ASCII;")
cursor = cnxn.cursor()
cursor.execute("select last, first from test")
row = cursor.fetchone()
print row
```

Any help is greatly appreciated!

You can find this post on stackoverflow.com at http://stackoverflow.com/questions/32662123/pyodbc-error-data-source-name-not-found-and-no-default-driver-specified-paradox

**Comment by woodlandhunter** [comment]
A couple problems

1) I believe LOCATION should be a folder that contains the .db files, not a DB file itself.
2) You're not calling format() on your format string.

Example (tested as working using this db http://www.thedbcommunity.com/dload/geog.zip):

```
LOCATION = r'c:\test\pdb'
cnxn = pyodbc.connect(r"Driver={{Microsoft Paradox Driver (*.db )\}};DriverID=538;Fil=Paradox 5.X;DefaultDir={0};Dbq={0};CollatingSequence=ASCII;".format(LOCATION), autocommit=True)
```


You also may need to pass autocommit=True (like in the example) as without you may get:

```
Error: ('HYC00', '[HYC00] [Microsoft][ODBC Paradox Driver]Optional feature not implemented  (106) (SQLSetConnnectAttr(SQL_ATTR_AUTOCOMMIT))'
```
