### ISSUE TITLE
fetch() breaks on Db2 timestamps when timestamp contains hh:mm:ss of 24:00:00 

### ISSUE THREAD

**Issue by soundstripe** [mkleehammer/pyodbc#782]
### Environment
- Python: 3.8
- pyodbc: 4.0.30
- OS: Windows
- DB: Db2 for i 7.4
- driver: iAccess Client Solutions

### Issue
Db2 supports times of 24:00:00 in timestamp fields representing "end-of-day." There is no way for python to represent `datetime` values with hour=24, but pyodbc's current behavior is to throw an exception when it tries to create the datetime. (`ValueError: hour must be in 0..23`)

I'd like to see pyodbc automatically coerce the value to an equivalent `datetime` with hour=0. It is already impossible to store those values into the database without representing them as strings, so this should not result in a loss of functionality.

I've got a pull request ready which I'll attach for discussion.

**Comment by soundstripe** [comment]
https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/db2/rbafztsstrings.htm

Documentation on the "hour can be 24" bit for db2. It explicitly states that the hour, minute, and second, and fractional part must all be zero, so maybe that code could be simplified.

**Comment by keitherskine** [comment]
Fixed by #783.

**Comment by dkornacki-cutco** [comment]
This only fixes datetime/timestamp fields. A similar fix is needed for TIME fields -- before line 637: return PyTime_FromTime(...).
