### ISSUE TITLE
row.fieldname to retrieve recordset data, but fieldname is case censitive. inconsistent with MS SQL

### ISSUE THREAD

**Issue by hotmzc1977** [mkleehammer/pyodbc#784]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8
- pyodbc: 32
- OS: win10
- DB:MSSQL
- driver:SQL Server Native Client 11.0

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by keitherskine** [comment]
Just FYI, @hotmzc1977 , there is an option to return column names in lowercase:
https://github.com/mkleehammer/pyodbc/wiki/The-pyodbc-Module#lowercase
That may help here.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
