### ISSUE TITLE
Using fast_executemany causes insertion of Decimal into float column fail

### ISSUE THREAD

**Issue by naveen-ram** [mkleehammer/pyodbc#786]
### Environment
- Python: 3.7.5
- pyodbc: 4.0.27
- OS: Windows 10
- DB: Db2 for IBM i
- driver: IBM i Access ODBC Driver
### Issue
@kadler and I were testing the fast_executemany functionality with Db2 for i by running the sqlalchemy test suite with pyodbc and fast_executemany as `True`.
#### Expected result
|                 x                  |
| ------------------------ |
| 1.100000023841858   |
| 1.2000000476837158 |
| 1.100000023841858   |
| 1.2000000476837158 |
#### Observed result
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('Converting decimal loses precision', 'HY000')
```
These tests passed when fast_executemany was False, so the expected behavior was for the tests to pass when set to True. We were able to reproduce the error with the following code:
```python
import pyodbc
import decimal
cnxn = pyodbc.connect("DRIVER=IBM i Access ODBC Driver;UID=uname;PWD=pass;System=ibmisys")
cur = cnxn.cursor()
cur.execute("CREATE TABLE TEST(X FLOAT(8))")
# Following inserts correctly
cur.executemany("INSERT INTO TEST(X) VALUES (?)", [(1.1,),(decimal.Decimal("1.2"),)])
cur.fast_executemany = True
# Following insert fails
cur.executemany("INSERT INTO TEST(X) VALUES (?)", [(1.1,),(decimal.Decimal("1.2"),)])
```
Also tested on MS SQL Server, same result.

**Comment by v-chojas** [comment]
fast_executemany gets its speed from doing a very minimal amount of conversion. This means that you will necessarily see behaviour differences when there is conversion required, and in fact your test case of mixing types in the same column is not ideal from the performance perspective either: fast_executemany will not make things faster in that case. Python Decimals are exact types whereas floating-point values are not. If you cast the Decimal to a float (thus explicitly acknowledging the loss of precision), then not only will you avoid the error, but also allow fast_executemany to perform at its best.

Also note that it was specifically developed for the ODBC Driver for SQL Server, and behaviour with other drivers depends on whether they support parameter arrays correctly. If your driver emulates parameter arrays with repeated execution, you are unlikely to see a performance benefit either.

**Comment by kadler** [comment]
Our driver supports both parameter arrays and column arrays for block insert and block fetch, which is why we were looking at enabling fast_executemany for our SQLAlchemy adapter based on PyODBC. This test case comes straight from the SQLAlchemy suite, so it seems that this behavior of fast_executemany is incompatible. I suppose we could add it as an option that users could turn on, with the caveat that it may not work in cases such as this, but I was hoping to avoid that.

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
