### ISSUE TITLE
Django Failed to connect SQL Server 2019

### ISSUE THREAD

**Issue by SeekerDexter** [mkleehammer/pyodbc#791]
### Environment

- Python:  3.7 64-bit
- pyodbc:  4.0.30
- OS:  Windows10 professional 1803 17134.1130
- DB:  SQL Server 2019 15.0.4033.1
- driver: {ODBC Driver 17 for SQL Server}

### Issue

I used sql server 2012 as database for my django peoject (via django-pyodbc-azure=2.1.0.0), it worked well. But after the DBA update sql server to version 2019, the code dose not work, it raise error : 

> `django.db.utils.NotSupportedError: SQL Server v15 is not supported.`

according to trackback, I found the reason is "15" id not a key in dict `DatabaseWrapper._sql_server_versions` ([PyEnvs]\Lib\site-packages\sql_server\pyodbc\base.py).

**Comment by gordthompson** [comment]
This is not a pyodbc issue:

``` python
sql = r"SELECT @@VERSION AS v"
crsr.execute(sql)
print(crsr.fetchval())
"""console output:
Microsoft SQL Server 2019 (RTM-CU3) (KB4538853) - 15.0.4023.6 (X64) 
	Mar  4 2020 00:59:26 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.4 LTS) <X64>
"""
```

It is a Django (or related) issue.

**Comment by keitherskine** [comment]
Further to @gordthompson 's point, a fork of `django-pyodbc-azure` has been built specifically to address this issue: [django-pyodbc-azure-2019](https://pypi.org/project/django-pyodbc-azure-2019/) .

@SeekerDexter , if this discussion gives you the answers you need, do please close this issue.

**Comment by SeekerDexter** [comment]
@gordthompson @keitherskine Thank u very much.
I temporarily bypassed this error by adding key-value pairs yesterday, but obviously your way is more elegant.
