### ISSUE TITLE
Pip install pyodbc

### ISSUE THREAD

**Issue by louisdupreve** [mkleehammer/pyodbc#793]
Hi guys,

I hope you're well, 

Here is the result after I've tried to install in the pip:

compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/dulo0814/virtualenv/monProjetWagtail/3.7/bin/python3.7_bin -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qv6or0la/pyodbc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-milmcrb1-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dulo0814/virtualenv/monProjetWagtail/3.7/include/site/python3.7/pyodbc" failed with error code 1 in /tmp/pip-build-qv6or0la/pyodbc/

**Comment by keitherskine** [comment]
It's difficult to provide assistance with so little information, @louisdupreve .  Perhaps the wiki page https://github.com/mkleehammer/pyodbc/wiki/Install might help.  If you find your solution there, please don't forget to close this issue.

**Comment by v-chojas** [comment]
I suspect you have not installed unixODBC, but if the error message is the same, see https://github.com/mkleehammer/pyodbc/issues/441

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
