### ISSUE TITLE
Pyodbc - if one connection to mssql get hung its blocking other connection to mssql server in multithreaded program

### ISSUE THREAD

**Issue by vptayde** [mkleehammer/pyodbc#794]
I am connecting to multiple mssql server in parallel Using below code using multithreaded python program.
If one connection get hung then all remaining connection getting hung.
If I remove that problematic host details (for which connection getting hung) from list then program works fine and connect to other mssql servers. 
I am unabale to understand how could other connection getting hung because of one connection.
I tried adding timeout but no luck.
I am using Active Directiory authentication for login to mssql server by using FreeTDS.
Could you please help me.

Below is code getting called for multi threaded program each thread is creating mssql connection for multiple host:

for obj in objList:
    host = obj.get('hostname')
    port = obj.get('port')
    dbname = obj.get('dbname')
    username = 'testusr'
    password  = 'testpass'
    conn = pyodbc.connect('DRIVER={FreeTDS};SERVER=' + host + ';PORT=' + port + ';UID=' + username + ';PWD=' + password 
                + ';DATABASE=' + dbname + ';timeout=10')

 
Version Used:   
OS : Linux
Python version : 3.6
Pyodbc Version = 4.0.30
FreeTDS vesrion = 1.1
DB : MSSQL

**Comment by gordthompson** [comment]
When you say that one connection "get[s] hung" do you mean that the connection attempt itself hangs, or is it that some operation hangs after the connection is successfully established?

**Comment by v-chojas** [comment]
If you can, please try the [Microsoft ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/)

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
