### ISSUE TITLE
Problems with restoration of a DB in SQL Server

### ISSUE THREAD

**Issue by grap3-fru1t** [mkleehammer/pyodbc#795]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8
- pyodbc: 4.0.30
- OS: Windows
- DB: SQL Server
- driver: SQL Server

### Issue
Successfull restoration of a db is not being awaited by python. Usage of a pyodbc connection as a context manager fails.

My code that works:
```
self.conn = pyodbc.connect(connection_string, autocommit=True)
cursor = self.conn.cursor()
#Restore command
restore_command = """
RESTORE DATABASE [{database}]
FROM DISK = N'{shared_folder}\\{database}.bak'
WITH FILE = 1, NOUNLOAD, REPLACE, STATS = 5, RECOVERY, 
MOVE N'{database}' TO N'{shared_folder}\\{database}.mdf',
MOVE N'{database}_log' TO N'{shared_folder}\\{database}_log.ldf'
""".format(database=database, shared_folder=shared_folder, sqldata_path=sqldata_path, sqllog_path=sqllog_path);
cursor.execute(restore_command)

time.sleep(120);
self.conn.close()
```
Note that I have to build in the extra time.sleep() command before closing the db for the program to await that the restoration finishes.

Code that doesn't work:
```
class SQLConnection:
    """ Joint functionality to connect to the SQL Server

    """
    conn = None
    def __init__(self, connection_string, autocommit=True):

        # define the string to connect to sql
        self.connection_string = connection_string
        self.autocommit = autocommit

    def __enter__(self):
        """ Entering the connection """
        self.conn = pyodbc.connect(self.connection_string, autocommit=self.autocommit)
        return self

    def __exit__(self, type, value, traceback):
        """ Closing the connection """
        self.conn.close()

    def sql_query_without_results(self, query):
        """ Simple select query to the SQL database """
        cursor = self.conn.cursor()
        cursor.execute(query)


with SQLConnection(connection_string) as conn:

    restore_command = """
    RESTORE DATABASE [{database}]
    FROM DISK = N'{shared_folder}\\{database}.bak'
    WITH FILE = 1, NOUNLOAD, REPLACE, STATS = 5, RECOVERY, 
    MOVE N'{database}' TO N'{shared_folder}\\{database}.mdf',
    MOVE N'{database}_log' TO N'{shared_folder}\\{database}_log.ldf'
    """.format(database=database, shared_folder=shared_folder, sqldata_path=sqldata_path, sqllog_path=sqllog_path);

    conn.sql_query_without_results(restore_command)

    time.sleep(120);
```

Issues:

- The second code seems to run through but the database will not be restored. The database still shows 
![image](https://user-images.githubusercontent.com/52132296/86921678-ccaf0c80-c12b-11ea-939e-dec868f464d9.png)
in SSMS. I am also not able to connect to that database after this restoration. I don't understand why the second code doesn't work where it should be doing the same thing as the first one.

- Is there a way for the program to automatically await the finish of the restore command before proceeding?

ODBC Trace from the second code execution:
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/4890761/SQL.LOG)

**Comment by v-chojas** [comment]
Same issue of not consuming all the resultsets...

https://github.com/mkleehammer/pyodbc/issues/471
https://github.com/mkleehammer/pyodbc/issues/740
https://github.com/mkleehammer/pyodbc/issues/762
https://github.com/microsoft/msphpsql/issues/932
https://support.microsoft.com/en-us/help/827575

**Comment by grap3-fru1t** [comment]
Thanks, that helps with the second issue.
However, I find it very unnatural that I need to loop over all result sets for a query where I do not need any results or return values at all. Is this behaviour intended by the odbc driver?

That still doesn't explain why the two code snippets posted above behave differently. Do you have any ideas?

**Comment by v-chojas** [comment]
From the Microsoft link above: "This behavior is by design." BACKUP and RESTORE both emit progress messages which appear to the driver like resultsets.

Waiting an arbitrary amount of time is fragile and subject to timing variances, which may be why you see subtly different results with subtly different code.
