### ISSUE TITLE
observed alert while trying to test the python i just installed

### ISSUE THREAD

**Issue by Rahman719** [mkleehammer/pyodbc#796]
PS C:\Users\Thermocool2> python
python : Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:30:28) [MSC v.1926 32 bit (Intel)] on win32
At line:1 char:1
+ python
+ ~~~~~~
    + CategoryInfo          : NotSpecified: (Python 3.8.4 (t...ntel)] on win32:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by gordthompson** [comment]
What leads you to conclude that the error has anything to do with pyodbc?

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
