### ISSUE TITLE
Complex Encoding Interaction

### ISSUE THREAD

**Issue by rlichtenwalter** [mkleehammer/pyodbc#798]
### Environment

- Python: 3.7.6
- pyodbc: 4.0.30
- OS: GNU/Linux (kernel Linux 4.4.0-1073-aws)
- DB: Cloudera Hadoop/Impala *and* Cloudera Hadoop/Hive
- Impala Driver: Cloudera Impala ODBC Driver 64-bit version 2.6.10
https://downloads.cloudera.com/connectors/ClouderaImpala_ODBC_2.6.10.1010/Debian/clouderaimpalaodbc_2.6.10.1010-2_amd64.deb
- Hive Driver: https://downloads.cloudera.com/connectors/ClouderaHive_ODBC_2.6.4.1004/Debian/clouderahiveodbc_2.6.4.1004-2_amd64.deb

versus (see long explanation below)

- OS: MacOS (kernel xnu 6153.141.1)
- Impala Driver: https://downloads.cloudera.com/connectors/ClouderaImpala_ODBC_2.6.10.1010/macOS/ClouderaImpalaODBC.dmg
- Hive Driver: https://downloads.cloudera.com/connectors/hive_odbc_2.6.1.1001/OSX/ClouderaHiveODBC.dmg

### Issue
Please hang in with me here...

#### Background
We have a Hadoop cluster that exposes data through both Impala and Hive with which we interact through pyodbc using the Cloudera Impala and Cloudera Hive drivers (see above for versions).

On Linux, when we use pyodbc to query Hadoop via either Hive or Impala, we can only see full and correct column names if we use
cn.setdecoding(pyodbc.SQL_WMETADATA, encoding="utf-32le")
No other encodings work. However, when we do use this encoding, queries that generate errors cause a UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)

On the other hand, if we use:
cn.setdecoding(pyodbc.SQL_WMETADATA, encoding="utf-16")
then we get proper SQL error messages without the exception, but column names that come back are mangled.

Which means there is no single encoding that we can set that permits both error messages to work and column names to show correctly.

Again, this is the case with *both* Impala and Hive drivers *on Linux*. You might suspect that it's a driver issue, so we tried using R and the 'odbc' library. There, we query the same databases on the same system with the same drivers, and everything works correctly with UTF-8 and does *not* work with *either* UTF-16 or UTF-32LE.

So then you might suspect that it's a pyodbc issue. So then we tried the same thing locally on our Macs. We're using the same version of pyodbc and the Mac version of the Cloudera Impala and Hive drivers (same version for the Mac platform as for Linux), and pyodbc works for both query errors and column names with UTF-8 and does *not* work with *either* UTF-16 or UTF-32LE.

We're at a loss where to go from here, but Cloudera support is vehemently insisting that the issue is with pyodbc and not on their side. The R odbc versus pyodbc test on Linux seems to support that. But then the Linux versus Mac ODBC test seems to contradict it.

**Comment by keitherskine** [comment]
Just to check, are you setting `DriverManagerEncoding` in your odbcinst.ini file?  If you are using unixODBC, you may need to set it to "UTF-16".  If you are using iODBC, you may need to set it to "UTF-32".  See the following for reference:
https://github.com/mkleehammer/pyodbc/issues/764#issuecomment-639688949
https://github.com/mkleehammer/pyodbc/wiki/Drivers-and-Driver-Managers#unixodbc

**Comment by rlichtenwalter** [comment]
I tried setting `DriverManagerEncoding=UTF-16` on the GNU/Linux side to no avail. It seems like if this were an issue, it would affect R's odbc library too. Furthermore, we're using unixODBC on both GNU/Linux and Mac, but we were not setting that on either before.

**Comment by keitherskine** [comment]
If it's OK with you, it would be handy to see the contents of your odbc.ini, odbcinst.ini, and cloudera.impalaodbc.ini files (with credentials redacted of course).

**Comment by rlichtenwalter** [comment]
Looking at cloudera.impalaodbc.ini, which we hadn't examined before, it seems like there could be clues there. I still don't understand why R odbc works differently from pyodbc if it's a driver-related issue. I can try playing with this and see if that gets me anywhere.

/etc/odbc.ini: EMPTY


cloudera.impalaodbc.ini:
[Driver]

## - Note that this default DriverManagerEncoding of UTF-32 is for iODBC.
## - unixODBC uses UTF-16 by default.
## - If unixODBC was compiled with -DSQL_WCHART_CONVERT, then UTF-32 is the correct value.
##   Execute 'odbc_config --cflags' to determine if you need UTF-32 or UTF-16 on unixODBC
## - SimbaDM can be used with UTF-8 or UTF-16.
##   The DriverUnicodeEncoding setting will cause SimbaDM to run in UTF-8 when set to 2 or UTF-16 when set to 1.

DriverManagerEncoding=UTF-32
ErrorMessagesPath=/opt/cloudera/impalaodbc/ErrorMessages/
LogLevel=0
LogPath=
SwapFilePath=/tmp


## - Uncomment the ODBCInstLib corresponding to the Driver Manager being used.
## - Note that the path to your ODBC Driver Manager must be specified in LD_LIBRARY_PATH (LIBPATH for AIX).
## - Note that AIX has a different format for specifying its shared libraries.

# Generic ODBCInstLib
#   iODBC
ODBCInstLib=libiodbcinst.so

#   SimbaDM / unixODBC
#ODBCInstLib=libodbcinst.so

# AIX specific ODBCInstLib
#   iODBC
#ODBCInstLib=libiodbcinst.a(libiodbcinst.so.2)

#   SimbaDM
#ODBCInstLib=libodbcinst.a(odbcinst.so)

#   unixODBC
#ODBCInstLib=libodbcinst.a(libodbcinst.so.1)


/etc/obdcinst.ini:
[ODBC Drivers]
ODBC Driver 11 for SQL Server=Installed
Cloudera ODBC Driver for Impala 64-bit=Installed
Cloudera ODBC Driver for Hive 64-bit=Installed
Amazon Redshift (x64)=Installed
[ODBC Driver 11 for SQL Server]
Description=Microsoft ODBC Driver 11 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.4.so.2.1
Threading=1
UsageCount=2
[Cloudera Impala ODBC Driver 64-bit]
Description=Cloudera ODBC Driver for Impala (64-bit)
Driver=/opt/cloudera/impalaodbc/lib/64/libclouderaimpalaodbc64.so
[Cloudera Hive ODBC Driver 64-bit]
Description=Cloudera ODBC Driver for Hive (64-bit)
Driver=/opt/cloudera/hiveodbc/lib/64/libclouderahiveodbc64.so
[Amazon Redshift (x64)]
Description=Amazon Redshift ODBC Driver (64-bit)
Driver=/opt/amazon/redshiftodbc/lib/64/libamazonredshiftodbc64.so
[PostgreSQL ANSI]
Description=PostgreSQL ODBC driver (ANSI version)
Driver=/usr/lib/x86_64-linux-gnu/odbc/psqlodbca.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1
[PostgreSQL Unicode]
Description=PostgreSQL ODBC driver (Unicode version)
Driver=/usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libodbcpsqlS.so
Debug=0
CommLog=1
UsageCount=1

**Comment by keitherskine** [comment]
You should be able to show verbatim text by adding three backticks before and after the text, even if that text contains markdown formatting, see [here](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) for an example.

Also, it's a bit strange the odbc.ini file is empty.  Could you run `odbcinst -j` and post the output?  That should show which odbc.ini and odbcinst.ini files are being used by unixODBC.

**Comment by rlichtenwalter** [comment]
We manage our DSNs elsewhere at the moment for portability reasons.

odbcinst -j returns:
```
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/ubuntu/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

**Comment by keitherskine** [comment]
Thank you @rlichtenwalter , that makes sense.

I don't know whether you're using the Simba driver manager or the unixODBC driver manager, but I'm pretty sure you're not using the iODBC driver manager.  So, in cloudera.impalaodbc.ini, I suspect the "Generic ODBCInstLib" entry should be commented out, and the "SimbaDM / unixODBC" entry should be commented in:
```
# Generic ODBCInstLib
#   iODBC
#ODBCInstLib=libiodbcinst.so

#   SimbaDM / unixODBC
ODBCInstLib=libodbcinst.so
```
Also, in the same file, I suspect the `DriverManagerEncoding` value should be set to UTF-16 rather than UTF-32:
```
DriverManagerEncoding=UTF-16
```
You might still need to fiddle around with pyodbc.SQL_WMETADATA but I'd start with utf-16:
```
cn.setdecoding(pyodbc.SQL_WMETADATA, encoding="utf-16")
```

**Comment by rlichtenwalter** [comment]
All right. Setting DriverManagerEncoding=UTF-16 causes the mismatch between column names and errors to go away; both work with pyodbc set to UTF-16 at that point. Presumably the cloudera.impalaodbc.ini config was overriding the change that you sagely asked me to make before in odbcinst.ini

If you have answers to the following questions, I would be really curious to understand better:
- Why, or maybe better, how, does R odbc get around this issue without changes to any configuration files, using UTF-8.
- Is there any way for me to use UTF-8 for the SQL_WMETADATA decoding. As it is now, our libraries making use of pyodbc have to take different values depending on the platform, which is undesirable.

**Comment by rlichtenwalter** [comment]
We crossed paths here. If you have any thoughts to share about the questions I posed, I'd appreciate it. I'm going to communicate the post-install configuration issue back to Cloudera so that they can hopefully improve their post-installation configuration, too.

**Comment by keitherskine** [comment]
Text encoding in ODBC is a bit of a hodge-podge.  Microsoft wrote the ODBC standard so, officially, only two encodings are supported - single byte ASCII (for non-unicode text) and UCS-2 (for unicode text, UCS-2 is very similar to UTF-16 but not exactly the same).  Many RDBMS's do not want to use UCS-2 for unicode text, they would prefer to use UTF-8.  Hence, they essentially go against the standard and write their drivers to transport UTF-8 encoded text instead.  Things are further complicated because there are different categories of unicode text passed between database and client.  There is the usual table data returned from SELECT queries, there is the metadata for those SELECT queries (i.e. the names of the returned columns), there is other metadata provided by the database (e.g. names of database tables), and finally there is the SQL statement itself (which of course is unicode text just like any other).  It's kinda surprising but RDBMS's often encode those four categories of text with different encodings, hence the various pyodbc `setdecoding()` options.  Frankly, ODBC text encoding is a bit of a mess, so I'm afraid it's difficult to answer your first question.  The R language probably has internal settings that makes sure everything lines up with UTF-8 from end to end.

The `setdecoding(pyodbc.SQL_WMETADATA, ...)` command tells pyodbc how to decode the metadata from the database, but it doesn't tell the database how to encode the metadata, so I'm afraid I can't think of an easy way to enforce UTF-8 metadata all the time on all platforms.

**Comment by rlichtenwalter** [comment]
@keitherskine **Thank you** for taking the time to write this very complete answer. I did not grasp all of this complexity well. Now that I do, I'm in a better position to handle such issues in the future. I also understand much better the concrete situation I'm in at the moment. Clearly the issue does not lie with pyodbc, so I'm closing. Take care!

**Comment by keitherskine** [comment]
Happy to help, @rlichtenwalter .  Glad it all works now.
