### ISSUE TITLE
[08001][unixODBC][Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:subject name does not match host name]

### ISSUE THREAD

**Issue by enod** [mkleehammer/pyodbc#799]
### Environment

Hi, I am running the following --

Python: 3.6 (64 bit)
pyodbc: 4.0.27
OS: Linux (Redhat 7.6)
driver: ODBC Driver 17 for SQL Server
and am trying to access a SQL SERVER (version 13) hosted on a linux machine.

### Issue
When I run following command: 
`isql -v -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=SERVER_ADDRESS,1433;UID= USERID;Authentication=ActiveDirectoryInteractive;"`

I'm receiving following error:
```
[08001][unixODBC][Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:subject name does not match host name]
[08001][unixODBC][Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection
[ISQL]ERROR: Could not SQLDriverConnect
```

I am able to connect to SQL server on my local machine using Jetbrains Datagrip which uses JDBC connector and driver that automatically downloaded for me. 

#610 Looks similar, however, error message is different. 

I've also tried running isql command with Encrypt=no. But still getting the same error. Python pyodbc code also gives the exact same error as shown above. 

Is there anything else I could do? Or is it just some sort of a bug?

Thanks in advance for you help.

**Comment by v-chojas** [comment]
The server is configured to use encryption - if either side requests encryption then connection will be encrypted.
Check that the SERVER_ADDRESS you specify in the connection string matches the name configured in the server's certificate. If you have no control over it, you can add `TrustServerCertificate=Yes` to not check the certificate.

Are you really trying to use AAD _Interactive_ authentication on _Linux_ ? That is currently not supported... so even if you get past the initial connection to the server you would not be able to login. Login with AAD credentials is also only for Azure SQL/DW/MI - if this is an instance of SQL that you installed, even if it is running in a VM in Azure, it will only support regular username/password and Windows Integrated (Kerberos) authentication methods.

**Comment by enod** [comment]
@v-chojas thanks for the guidance. Didn't notice Interactive authentication mode is not supported on linux.
I've tried
`isql -v -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=SERVER_ADDRESS,1433;UID= USERID;PWD=PASSWORD;Authentication=SqlPassword;TrustServerCertificate=Yes"`
but still giving the same error. When you say server's certificate, is it the certificate on server's side or CA cert on client side?

**Comment by v-chojas** [comment]
Try to not specify `Authentication` as that's the default you get with UID/PWD  (and this must be a SQL Server login - not an AAD credential).

To be clear, is this server Azure SQL, or just an instance of SQL Server installed somewhere (even if it's an Azure VM)?

**Comment by enod** [comment]
Tried without `Authentication`
`[28000][unixODBC][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'USERID'.`

Problem is I don't have control over MSSQL server. But it is a MSSQL server that is installed on linux machine not on Azure SQL nor Azure VM.

**Comment by v-chojas** [comment]
That's better, that error just means your credentials are incorrect. It should work once you have the user and pass correct.

**Comment by enod** [comment]
Ended up using SQL authentication instead of Windows.

**Comment by raminsamadian** [comment]
for fix that problem you can do this : 
1 - edit moodle path   like  :  public_html/lib/dml/sqlsrv_native_moodle_database.php
2 find dboption block and append : 
'Encrypt' => true, // Enable SSL encryption
'TrustServerCertificate' => true, // Trust the server certificate without validating it
========
 $options = [
            'UID' => $this->dbuser,
            'PWD' => $this->dbpass,
            'Database' => $this->dbname,
            'CharacterSet' => 'UTF-8',
            'MultipleActiveResultSets' => true,
            'ConnectionPooling' => !empty($this->dboptions['dbpersist']),
            'ReturnDatesAsStrings' => true,
            'Encrypt' => true, // Enable SSL encryption
            'TrustServerCertificate' => true, // Trust the server certificate without validating it
];


done .

**Comment by v-chojas** [comment]
In case you didn't notice, this project has nothing to do with PHP.
