### ISSUE TITLE
Login failed for user '<token-identified principal>'

### ISSUE THREAD

**Issue by stevenhurwitt** [mkleehammer/pyodbc#800]
### Environment

- Python: 64-bit
- pyodbc: 4.0.30
- OS: Windows
- DB: SQL Server
- driver: ODBC Driver 17 for SQL Server

#### Expected behavior
Establish a connection to SQL Server database.

#### Observed behavior
Getting an error that I don't have permission, when I can connect and run basic queries in MSSMS. Only thing I can think of is that there needs to be some sort of permissions thing done on the backend, but it doesn't make sense that it worked through SQL Server but not pyodbc.

Authentication:
![image](https://user-images.githubusercontent.com/7502272/88206218-8a99c680-cc13-11ea-8b85-e487e035b7b1.png)

Basic Query:
![image](https://user-images.githubusercontent.com/7502272/88206390-c92f8100-cc13-11ea-8e5e-ade5ab9f339f.png)

### Code
```python
import pyodbc

server = 'my_server.database.windows.net' 
database = 'my_db' 
username = '{me@gmail.com}'

cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username + '; AUTHENTICATION=ActiveDirectoryInteractive')
```
### Error
```python
InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '<token-identified principal>'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '<token-identified principal>'. (18456)")
```

**Comment by v-chojas** [comment]
Could you try to run `odbcad32.exe`, create a new DSN using the driver and test that? That will use the ODBC driver directly and help determine if it is something specific to pyODBC.

(SSMS uses .NET SqlClient, not ODBC.)

**Comment by stevenhurwitt** [comment]
Set up a system DSN and it configured successfully.

![image](https://user-images.githubusercontent.com/7502272/88208299-a18de800-cc16-11ea-995c-71f473250376.png)

Restarted my jupyter notebook server and tried again but the error persists. Is there a separate Python package I should use instead of pyodbc?

**Comment by v-chojas** [comment]
Could you post an ODBC trace of attempting to connect via pyODBC?

**Comment by stevenhurwitt** [comment]
This is the full error, it successfully brings up a Microsoft login info, but throws this when I authenticate through that:
```python
---------------------------------------------------------------------------
InterfaceError                            Traceback (most recent call last)
<ipython-input-2-862c32247593> in <module>
      6 username = '{stevenhurwitt@gmail.com}'
      7 
----> 8 cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username + '; AUTHENTICATION=ActiveDirectoryInteractive')
      9 #cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';TRUSTED_CONNECTION=yes')
     10 

InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '<token-identified principal>'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user '<token-identified principal>'. (18456)")
```

**Comment by v-chojas** [comment]
Yes, that's the same error you showed before. See [ODBC tracing instructions](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log).

**Comment by stevenhurwitt** [comment]
lol whoops, sorry about that. here is the log file: 
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/4963321/SQL.LOG)

**Comment by v-chojas** [comment]
Just to be sure, you are using the same credentials when you run the Python as you did in the successful DSN test above?

The way the AzureAD authentication to SQL works is that it authenticates to AAD first to get an access token, and then submits that token to SQL during login. What your symptoms show is that in both cases the authentication is successful, but in one case the server rejects the access token.

You could also try to remove the `Database` from the connection string in Python, and let Azure connect you to th

**Comment by v-chojas** [comment]
Just to be sure, you are using the same credentials when you run the Python as you did in the successful DSN test above?

The way the AzureAD authentication to SQL works is that it authenticates to AAD first to get an access token, and then submits that token to SQL during login. What your symptoms show is that in both cases the authentication is successful, but in one case the server rejects the access token.

You could also try to remove the `Database` from the connection string in Python, and let Azure connect you to th

**Comment by v-chojas** [comment]
e default database of your user.

**Comment by stevenhurwitt** [comment]
Thanks so much, that did it! Closing issue now.
