### ISSUE TITLE
fast_executemany = True, not working.

### ISSUE THREAD

**Issue by Sushmita-24** [mkleehammer/pyodbc#801]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki 
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7 64-bit
- pyodbc: 4.0.30
- OS: Windows 10
- DB: Ibm_db
- driver: NetezzaSQL

### Issue
tuple_of_tuples = tuple([tuple(x) for x in df.values])
cur1.fast_executemany = True
cur1.executemany('INSERT INTO TABLENAME VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', tuple_of_tuples)

With fast_executemany = True, data is not inserted in table(no error is thrown) and 
when fast_executemany= False, data is getting inserted in table but its very very slow.

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by v-chojas** [comment]
Please provide an ODBC trace. Note that this feature was developed with the Microsoft ODBC Driver for SQL Server in mind, and requires that the driver supports parameter arrays correctly --- not all drivers will.

**Comment by gordthompson** [comment]
https://github.com/mkleehammer/pyodbc/wiki/Driver-support-for-fast_executemany

**Comment by Sushmita-24** [comment]
@v-chojas and @gordthompson the same lines of code for the same coonection was working fine before I update pycharm, I degraded it again but same issue. And it gives on error the script just finishes with exit code.

Process finished with exit code -1073741819 (0xC0000005)

**Comment by gordthompson** [comment]
@Sushmita-24 - A non-zero exit code suggests that the Python interpreter has crashed. On Windows, 0xC0000005 is an "Access Violation" error. That is fairly common when trying to use fast_executemany with drivers that do not (properly) support it.

**Comment by Sushmita-24** [comment]
@gordthompson Thanks for this clarification.

Is there any alternative which I can use, and one more thing this was working perfectly fine in the same environment.

**Comment by v-makouz** [comment]
Is it possible to trace which line produces the "Access Violation Error"?

**Comment by gordthompson** [comment]
Closed due to inactivity. Feel free to re-open with additional information if necessary.
