### ISSUE TITLE
Best practice to keep connection open

### ISSUE THREAD

**Issue by tahv0** [mkleehammer/pyodbc#803]
### Environment
- Python: 3.8
- pyodbc: 4.0.30
- OS: Ubuntu
- DB: Oracle
- driver: ODBC

### Issue
I'm using Oracle DB through ODBC driver.

Should I keep connection open or close it as soon as query is executed? Making a new connection is quite slow, so I would like to keep connection open. Is there any flag to tell pyodbc to retry connection if connection is lost?

Any examples how to do this? Or should I try to get new cursor and manually reconnect if it fails? Thanks.

**Comment by gordthompson** [comment]
Fairly recent versions of unixODBC support [connection pooling](http://www.unixodbc.org/doc/conn_pool.html); you may want to investigate that.

**Comment by tahv0** [comment]
@gordthompson ok, thanks. I'll need to investigate that.

Currently I get
```pyodbc.OperationalError: ('08S01', '[08S01] [NetSuite][ODBC 64 bit driver][64 bit Client]Connection closed due to session kill (2251) (SQLPrepare)')```

**Comment by v-chojas** [comment]
Keeping the connection object in scope will keep the connection open, but that error you're getting suggests the server is closing the connection, in which case you will need to reopen it anyway..

**Comment by tahv0** [comment]
@v-chojas thanks. It seems to be so. So I just have to deal with slower connection...

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open if necessary.
