### ISSUE TITLE
Autocommit turning on when passing context to another function

### ISSUE THREAD

**Issue by stevesmit** [mkleehammer/pyodbc#806]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.9 64bit
- pyodbc: 4.0.30
- OS: Windows 10
- DB: Azure SQL Database
- driver: SQL Server

### Issue

I would like to be able to pass the connection variable that was opened with a context manager to another function, then it does it's processing with the cursor, and then the logic in the original context block continues. If an error occurs, I would like it to rollback the transaction. 

What I am instead seeing is that when I pass the context manager to another function and an exception is raised, the transaction is automatically committed. Here is some sample code:

```
    
    data = ["test 1"]

    SQL = '''
    
    INSERT INTO tester2(text) 
    OUTPUT INSERTED.id
    VALUES(?);

    '''
    with pyodbc.connect(cs, autocommit=False) as conn:
        with conn.cursor() as cursor:
            r = cursor.execute(SQL, data)
            print(r.fetchall())
            a = 1/0
```
In this code, the statement isn't committed to the database, as hoped. However in the code below, the statement is committed to the database, despite there being an exception before the context block closes. 

```
def function_to_execute(sql, data, conn):
    with conn.cursor() as cursor:
        r = cursor.execute(SQL, data)
        return r.fetchall()

if __name__ == "__main__":
    cs = "connection string"
    data = ["test 1", "test 2"]

    SQL = '''
    
    INSERT INTO tester2(text) 
    OUTPUT INSERTED.id
    VALUES(?);

    '''

    with pyodbc.connect(cs, autocommit=False) as conn:
        print(function_to_execute(SQL, data[0:1], conn))
        a = 1/0
```

Even wrapping the contents of the connection context block in a try/except block with a rollback doesn't work:

```
def function_to_execute(sql, data, conn):
    with conn.cursor() as cursor:
        r = cursor.execute(SQL, data)
        return r.fetchall()

if __name__ == "__main__":
    cs = "connection string"
    data = ["test 1", "test 2"]

    SQL = '''
    
    INSERT INTO tester2(text) 
    OUTPUT INSERTED.id
    VALUES(?);

    '''

    with pyodbc.connect(cs, autocommit=False) as conn:
        try:
            print(function_to_execute(SQL, data[0:1], conn)) 
            a = 1/0
        except Exception as e:
            conn.rollback()
            raise e
```
Any thoughts on this? Is this a driver issue, am I not using these context manager properly?

**Comment by keitherskine** [comment]
Just FYI, the context managers in pyodbc automatically commit for both connections and cursors:
https://github.com/mkleehammer/pyodbc/wiki/Connection#context-manager
https://github.com/mkleehammer/pyodbc/wiki/Cursor#context-manager

Fortunately, it's pretty easy to write your own context managers to do whatever you want them to do.  That's what I do.

**Comment by stevesmit** [comment]
> Just FYI, the context managers in pyodbc automatically commit for both connections and cursors:
> https://github.com/mkleehammer/pyodbc/wiki/Connection#context-manager
> https://github.com/mkleehammer/pyodbc/wiki/Cursor#context-manager
> 
> Fortunately, it's pretty easy to write your own context managers to do whatever you want them to do. That's what I do.

Thanks for that...I had read that about the connection context manager, but didn't realise that the cursor had the same behaviour (regarding executing `cnxn.commit()`! That was where the issue lay, because the cursor context had already closed and so had committed the transaction, before the exception was raised. 

As you noted, it is quite simple to create your own context manager, so this is what I used:

```
class CustomCursor():
    def __init__(self, conn):
        self.conn = conn
    def __enter__(self):
        self.cursor = self.conn.cursor()
        return self.cursor
    def __exit__(self, *exc):
        self.cursor.close()
```

This gives desired behaviour at the cursor level. 

Forgive me for being ignorant, but why is it that the autocommit flag is effectively pointless? Surely if autocommit is set to `False`, an error or exception should not commit the transaction.

**Comment by keitherskine** [comment]
As far as I know, the autocommit flag is overridden only in this one scenario, i.e. when using the built-in pyodbc context managers.  This context manager behaviour seems to have been around in other python odbc packages before it was implemented in pyodbc, see [here](https://github.com/mkleehammer/pyodbc/issues/43#issue-72173132) for examples.  I would agree though that it is less than intuitive.

To your second question, commits (and rollbacks) are always applied at the connection level, not the cursor level.  It's a common misconception that database transactions are handled at the cursor level.  See [here](https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management) for a longer explanation.

**Comment by stevesmit** [comment]
> As far as I know, the autocommit flag is overridden only in this one scenario, i.e. when using the built-in pyodbc context managers. This context manager behaviour seems to have been around in other python odbc packages before it was implemented in pyodbc, see [here](https://github.com/mkleehammer/pyodbc/issues/43#issue-72173132) for examples. I would agree though that it is less than intuitive.
> 
> To your second question, commits (and rollbacks) are always applied at the connection level, not the cursor level. It's a common misconception that database transactions are handled at the cursor level. See [here](https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management) for a longer explanation.

I agree that the commits and rollbacks are done at the connection level, but what I am saying is that the default behaviour of the cursor's context manager appears to be to commit the transaction of the **connection**, which I find confusing as a choice. Per the docs:

> Cursor objects do support the Python context manager syntax (the with statement), but it's important to understand the "context" in this scenario. The following code:

> ```with cnxn.cursor() as crsr:
>     do_stuff
> ```
> is essentially equivalent to:
> 
> ```crsr = cnxn.cursor()
> do_stuff
> if not cnxn.autocommit:
>     cnxn.commit()
> ``` 
> As you can see, commit() is called on the cursor's connection even if autocommit is False.

**Comment by keitherskine** [comment]
I agree that the built-in context managers are somewhat confusing, which is why I personally don't use them.  They appear to follow a trend in other python odbc managers whereby the "context" is effectively a database transaction, not a connection or cursor, and hence override the autocommit flag.  I argued against this behaviour five years ago, but it is what it is.  I think you're right to write your own context managers.
