### ISSUE TITLE
cursor.execute() with params returns TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by HKLansDev** [mkleehammer/pyodbc#808]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.7
- pyodbc: 4.0.30
- OS: Debian 9 Linux (container through win64) (python:3.7-slim-stretch)
- DB: SQL Server 2016
- driver: ODBC Driver 17 for SQL Server 

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

Execute without parameters seems to work fine, issue comes when parameters are added in the manner specified in the documentation. e.g.:
crsr.execute("{CALL usp_UpdateFirstName (?,?)}", params)

Tried with a single and multiple parameters with params as a list, tuple (as suggested from docs), raw strings.
Also tried with the query inside curly braces and without - same issue.

The line at which this fails implies that the format_sql() method is expecting an sql string with '%s' placeholders rather than '?' however I have also tried using %s placeholders which has resulted in a different error:

('The SQL contains 0 parameter markers, but 1 parameters were supplied', 'HY000')

Even though I am aware of the fact that the docs & function specifies that '?' is to be used.

Original error:
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
backend_dev_vet |     response = get_response(request)
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
backend_dev_vet |     response = self.process_exception_by_middleware(e, request)
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
backend_dev_vet |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_dev_vet |   File "/opt/project/backend/iservices/views.py", line 38, in testprocview
backend_dev_vet |     }""", [f_id])
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
backend_dev_vet |     return super().execute(sql, params)
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
backend_dev_vet |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
backend_dev_vet |     return executor(sql, params, many, context)
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_dev_vet |     return self.cursor.execute(sql, params)
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/sql_server/pyodbc/base.py", line 549, in execute
backend_dev_vet |     sql = self.format_sql(sql, params)
backend_dev_vet |   File "/usr/local/lib/python3.7/site-packages/sql_server/pyodbc/base.py", line 517, in format_sql
backend_dev_vet |     sql = sql % tuple('?' * len(params))

**Comment by v-makouz** [comment]
Can you provide a sample repro script? I have trouble reproducing this specific error

**Comment by HKLansDev** [comment]
Seems to be for any query so:

with connection['db'] as cursor:
    sql = "select * from table where field1 = ?"
    params = (1,)
    cursor.execute(sql,params)

**Comment by gordthompson** [comment]
This looks like a Django issue. The path ...

/usr/local/lib/python3.7/site-packages/sql_server/pyodbc/base.py

... shows that there is something called "sql_server" that is mucking with the query before passing it off to pyodbc itself.

**Comment by v-makouz** [comment]
This works fine in plain pyODBC, so yeah the problem is likely in Django

**Comment by absci** [comment]
I think the question mark placeholder doesn't work with Django. I got the same error if I'm using
```
sql = "select * from table where id = ?"
cursor.execute(sql, (1,))

  File "C:\Users\user\.virtualenvs\djangodev\lib\site-packages\sql_server\pyodbc\base.py", line 517, in format_sql
    sql = sql % tuple('?' * len(params))
TypeError: not all arguments converted during string formatting
```
if I change it to `sql = "select * from table where id = %s"` then it's good. Maybe you can try execute a raw query without parameters to see if that works.

**Comment by HKLansDev** [comment]
Thanks for the input on this guys. Apologies it's not a bug in pyodbc itself. A raw query works perfectly fine, it just needs to be parameterised with SQL injection prevention. I'll figure something out.
