### ISSUE TITLE
fast_executemany fails at conversion empty string to zero - Invalid character value for cast specification (0) (SQLParamData)')

### ISSUE THREAD

**Issue by Andrej730** [mkleehammer/pyodbc#809]
### Environment

- Python: 3.7
- pyodbc: 4.0.30
- OS: Windows 10 64 bit
- DB: SQL Server 2019
- driver: ODBC Driver 17 for SQL Server

### Issue

I have a table `sales` with 2 fields: date (date type) and Value (real type). If I set `fast_executemany = True` and try to insert the row `['2020-01-01', '']` using query `INSERT INTO sales (Date, Value) VALUES (?,?)` it results in error:

```
pyodbc.DataError: ('22018', '[22018] [Microsoft][ODBC Driver 17 for SQL Server]Invalid character value for cast specification (0) (SQLExecute)')
```

I've investigated and figured it fails to convert `''` to 0. So, the solution is to replace `''` with `0` before trying to insert values into table.
If i disable `fast_executemany` it works fine without converting empty string to zeroes.

Not sure if this issue is actually important to solve but I want to put it out there to help if someone will have the same problem.

**Comment by eddyizm** [comment]
I can't believe turning that option to `False` is does this trick. Tracking down the error is wildling challenging when there is actually nothing wrong with the sql statement. Thanks a bunch!

**Comment by v-chojas** [comment]
In order to achieve the extra speed, fast_executemany also restricts the type of conversions that it will perform. The performance doesn't come for free. That's why it's off by default.
