### ISSUE TITLE
Add a clearer error message for when ODBC header files are missing (Install unixodbc)

### ISSUE THREAD

**Issue by leej11** [mkleehammer/pyodbc#813]
### Issue
I recently encountered what seems to be a common error for users, whereby if one `pip install pyodbc` without having the "ODBC header files" (i.e. one hasn't installed unixodbc), then you get something that looks like the following:

```
In file included from src/buffer.cpp:12:0:
    src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
     #include <sql.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

Googling around and looking at previous GH issues here, I can eventually determine that if one installs `conda install unixodbc` or something like `unixodbc-dev`, then this problem is remediated.

**However, I'm wondering if a change could be put in the neatly handle this error, perhaps printing to the user**

`"Installation failed. Please install unixodbc and retry"`

This seems to be a common and recurring problem, I've found 3 historical issues about the same thing, so this change would definitely add value to the UX of pyodbc users!

#276 
#793 
#441

**Comment by v-makouz** [comment]
This error is from the gcc compiler, not sure pyODBC installer can do much about it. Also the exact package where the headers are can have different names on different OSs, updating the installation guide (if it doesn't include some scenarios) might be the best bet

**Comment by v-chojas** [comment]
For reference: installation guide is here https://github.com/mkleehammer/pyodbc/wiki/Install#installing-on-linux

**Comment by mkleehammer** [comment]
You are right that it would be a great idea, but I really don't see how to do so in a way that won't cause other problems.  It might be possible to capture the compiler output and scan it for hints that it might be the problem.  I'm going to close this for now as I don't think I can do much right now, but I will keep it in mind.  Maybe a build problems FAQ would help
