### ISSUE TITLE
Client unable to establish connection on Ubuntu but working MacOS

### ISSUE THREAD

**Issue by stefanknegt** [mkleehammer/pyodbc#817]
### Environment

- Python: 3.7.4
- pyodbc: 4.0.30
- OS: Ubuntu 16.04 
- DB: Azure SQL database
- driver: ODBC Driver 17 for SQL Server

### Issue

I have a script based on the instructions [here](https://docs.microsoft.com/en-us/azure/azure-sql/database/connect-query-python?tabs=macos) and it works perfectly fine on MacOS. After installing pyodbc via pip, unixodbc-dev via apt-get, and Microsoft ODBC driver using[ these instructions](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15) on my Ubuntu machine (same IP) I tried to run the script but I get the following error: 
```
with pyodbc.connect('DRIVER='+driver+';SERVER='+server+';PORT=1433;DATABASE='+database+';UID='+username+';PWD='+ password) as conn:
pyodbc.OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection (0) (SQLDriverConnect)')
```

I have no clue what I am doing wrong, so I hope someone can point me to some helpful instructions. Thanks a lot!

**Comment by v-makouz** [comment]
First thing to check is if connections string itself is good by using 
`isql -v -k "<CONNECTION STRING>"`

If `isql` works and connection string is not the issue, can you provide ODBC trace? (https://www.simba.com/blog/odbc-troubleshooting-tracing/)

Also "PORT" is not a proper connection string keyword for ODBC driver

**Comment by stefanknegt** [comment]
Isql does not work, I get t he following error: 
```
[01000][unixODBC][Driver Manager]Can't open lib 'ODBC' : file not found
[ISQL]ERROR: Could not SQLDriverConnect
-bash: UID: readonly variable
```

**Comment by stefanknegt** [comment]
After following the trouble shooting link for ODBC, I found the following in the log file:
```

[ODBC][18857][1599738944.961444][SQLDriverConnectW.c][290]
		Entry:
			Connection = 0x5626786d60e0
			Window Hdl = (nil)
			Str In = [DRIVER={ODBC Driver 17 for SQL Server};SERVER=X;DATABASE=X;UID=X;PWD=X][length = 125 (SQL_NTS)]
			Str Out = (nil)
			Str Out Max = 0
			Str Out Ptr = (nil)
			Completion = 0
		UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UTF-16LE'

[ODBC][18857][1599738945.054227][__handles.c][460]
		Exit:[SQL_SUCCESS]
			Environment = 0x562678b39a50
[ODBC][18857][1599738945.054274][SQLGetEnvAttr.c][157]
		Entry:
			Environment = 0x562678b39a50
			Attribute = 65002
			Value = 0x7ffcec48ab70
			Buffer Len = 128
			StrLen = 0x7ffcec48ab0c
[ODBC][18857][1599738945.054292][SQLGetEnvAttr.c][273]
		Exit:[SQL_SUCCESS]
[ODBC][18857][1599738945.054311][SQLFreeHandle.c][220]
		Entry:
			Handle Type = 1
			Input Handle = 0x562678b39a50
[ODBC][18857][1599738945.054388][SQLDriverConnectW.c][701]
		Exit:[SQL_ERROR]
[ODBC][18857][1599738945.054420][SQLDriverConnect.c][748]
		Entry:
			Connection = 0x5626786d60e0
			Window Hdl = (nil)
			Str In = [DRIVER={ODBC Driver 17 for SQL Server};SERVER=X;DATABASE=X;UID=X;PWD=******************][length = 125 (SQL_NTS)]
			Str Out = 0x7ffcec489310
			Str Out Max = 2048
			Str Out Ptr = (nil)
			Completion = 0
		DIAG [08001] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection
```

**Comment by gordthompson** [comment]
> Isql does not work, I get the following error:

You neglected to enclose the connection string in double-quotes. 

This will throw the error you describe:

``` text
isql -v -k DRIVER=ODBC Driver 17 for SQL Server;SERVER=192.168.0.179,49242;UID=sa;PWD=_whatever_
```

You need to use this:

``` text
isql -v -k "DRIVER=ODBC Driver 17 for SQL Server;SERVER=192.168.0.179,49242;UID=sa;PWD=_whatever_"
```

**Comment by stefanknegt** [comment]
Ok that was really stupid, sorry! Then it works indeed. The entire OBCD trace:

`[ODBC][19013][1599748235.498682][__handles.c][460]
		Exit:[SQL_SUCCESS]
			Environment = 0x5578d279bae0
[ODBC][19013][1599748235.498704][SQLSetEnvAttr.c][189]
		Entry:
			Environment = 0x5578d279bae0
			Attribute = SQL_ATTR_ODBC_VERSION
			Value = 0x3
			StrLen = 4
[ODBC][19013][1599748235.498710][SQLSetEnvAttr.c][381]
		Exit:[SQL_SUCCESS]
[ODBC][19013][1599748235.498716][SQLAllocHandle.c][377]
		Entry:
			Handle Type = 2
			Input Handle = 0x5578d279bae0
[ODBC][19013][1599748235.498722][SQLAllocHandle.c][493]
		Exit:[SQL_SUCCESS]
			Output Handle = 0x5578d279c0e0
[ODBC][19013][1599748235.498939][SQLDriverConnectW.c][290]
		Entry:
			Connection = 0x5578d279c0e0
			Window Hdl = (nil)
			Str In = [DRIVER={ODBC Driver 17 for SQL Server};SERVER=X;DATABASE=X;UID=X;PWD=X][length = 125 (SQL_NTS)]
			Str Out = (nil)
			Str Out Max = 0
			Str Out Ptr = (nil)
			Completion = 0
		UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UTF-16LE'

[ODBC][19013][1599748235.603457][__handles.c][460]
		Exit:[SQL_SUCCESS]
			Environment = 0x5578d2bffa50
[ODBC][19013][1599748235.603495][SQLGetEnvAttr.c][157]
		Entry:
			Environment = 0x5578d2bffa50
			Attribute = 65002
			Value = 0x7ffea329a170
			Buffer Len = 128
			StrLen = 0x7ffea329a10c
[ODBC][19013][1599748235.603513][SQLGetEnvAttr.c][273]
		Exit:[SQL_SUCCESS]
[ODBC][19013][1599748235.603531][SQLFreeHandle.c][220]
		Entry:
			Handle Type = 1
			Input Handle = 0x5578d2bffa50
[ODBC][19013][1599748235.603607][SQLDriverConnectW.c][701]
		Exit:[SQL_ERROR]
[ODBC][19013][1599748235.603639][SQLDriverConnect.c][748]
		Entry:
			Connection = 0x5578d279c0e0
			Window Hdl = (nil)
			Str In = [DRIVER={ODBC Driver 17 for SQL Server};SERVER=X;DATABASE=X;UID=X;PWD=******************][length = 125 (SQL_NTS)]
			Str Out = 0x7ffea3298910
			Str Out Max = 2048
			Str Out Ptr = (nil)
			Completion = 0
		DIAG [08001] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection

[ODBC][19013][1599748235.663926][SQLDriverConnect.c][1639]
		Exit:[SQL_ERROR]
[ODBC][19013][1599748235.663955][SQLGetDiagRecW.c][535]
		Entry:
			Connection = 0x5578d279c0e0
			Rec Number = 1
			SQLState = 0x7ffea329c900
			Native = 0x7ffea329c8fc
			Message Text = 0x7ffea329c910
			Buffer Length = 1023
			Text Len Ptr = 0x7ffea329c8fa
[ODBC][19013][1599748235.663987][SQLGetDiagRecW.c][596]
		Exit:[SQL_SUCCESS]
			SQLState = [08001]
			Native = 0x7ffea329c8fc -> 0
			Message Text = [[Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection]
[ODBC][19013][1599748235.664035][SQLFreeHandle.c][290]
		Entry:
			Handle Type = 2
			Input Handle = 0x5578d279c0e0
[ODBC][19013][1599748235.664057][SQLFreeHandle.c][339]
		Exit:[SQL_SUCCESS]`

**Comment by gordthompson** [comment]
Please run `odbcinst -j` to check the version of [unixODBC](http://www.unixodbc.org/) that you are using. If it is less than version 2.3.5 consider upgrading the the latest version.

**Comment by stefanknegt** [comment]
I have version 2.3.7 so that probably isn't the problem.

```
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/stefan/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

**Comment by v-makouz** [comment]
"Client unable to establish connection" is not an error I've seen myself, but looking around the it appears to be be usually caused by server configuration, but it works from the Mac using the same server. 

Can you create another Ubuntu VM and put a server on it (https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15) and see if you can connect to that? If it connects to a regular SQL Server then there might be some Azure settings that cause that, but if it can't then the problem is on the Ubuntu VM or some network issue.

**Comment by stefanknegt** [comment]
Solved by running `source ~/.bashrc`

**Comment by erfannariman** [comment]
I am having the same issue after upgrading ssl. When I run:

```
isql -v -k <connection string>
```

I get:
```
[08001][Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [OpenSSL library could not be loaded, make sure OpenSSL 1.0 or 1.1 is installed]
[08001][Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection
[ISQL]ERROR: Could not SQLDriverConnect
```

openssl is installed using brew. So when I check my folder  `/usr/local/etc/` I see that openssl@1.1 is there.
![image](https://user-images.githubusercontent.com/34067903/136184022-2f0d434f-01ba-4579-9072-0620e25742d9.png)

What could be the solution here? ODBC needs to find the 1.1 version of openssl.

**Comment by v-chojas** [comment]
The OP mentions it works on Mac but not Ubuntu, but you mention brew, so you are in a different situation and this is not the right issue to post on.
