### ISSUE TITLE
Unpredictable HY000 generic ODBC errors when processing large number of records and using parameter binding

### ISSUE THREAD

**Issue by mboeringa** [mkleehammer/pyodbc#822]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.10, 64 bit Python
- OS: Windows 10 as host, Ubuntu 20.04 as guest. Oracle Virtualbox 6.1.14
- DB: PostgreSQL 12.4 / PostGIS 3.0.2 (Ubuntu 12.4-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit. NOTE: I just upgraded to PostgreSQL 13, but haven't been able to test the issue there yet, but personally think it is unrelated to the PostgreSQL version.
- driver: Latest official PostgreSQL Windows ODBC driver (psqlODBC) from: https://www.postgresql.org/ftp/odbc/versions/
- pyodbc: 4.0.30
- cnxn.maxwrite = 1024 * 1024 * 1024 as per pyodbc documentation

### Issue

I have a two machine test setup with both machines running Windows 10. One machine acts as database server, and runs a Oracle Virtualbox 6.1 virtual machine, with Ubuntu 20.04 as guest OS running the actual database server. It has 2x 1.4 TB SSD storage available (Samsung EVO drives), used to host an PostgreSQL/PostGIS instance containing an OpenStreetMap Europe extract loaded with osm2pgsql. I connect to the database from a second Windows 10 machine using ODBC.

I developed a custom Python application that INSERTs and UPDATEs records in tables using pyodbc and Python multi-threading. Inserts and updates are record-by-record operations, committed in chunks of 40k records, and I have successfully performed them against tables of dozens of millions of records, where each and every record of those tables is being updated.

However, even with smaller tables, I was occasionally getting generic HY000 failures. The process would fail somewhere half way. With larger tables, this issue seemed to compound itself, where attempting to insert >135M records consistently failed somewhere along the way, and it was essentially impossible to process this amount of records without failure.

Combined with these failures, I noticed my "bridged" network adapter of the Ubuntu Virtual box instance, was down. While I could still access the internet from within the Ubuntu virtual machine via a second "NAT" type network adapter in Virtualbox, pinging the Ubuntu instance from my network failed. Accessing pgAdmin4 from within the virtual machine, showed the database to be up & running and in healthy state. I could open the partially finished table, showing the already inserted records before the failure happened. Data looked OK and was properly viewable, even the geometries (polygons) being inserted.

I initially blamed the issues on intermittent networking issues or other hardware malfunctioning. As this is a test setup, not running on enterprise grade hardware, this seemed the most likely cause. However, I then began to realize that it was primarily the INSERTs failing, not UPDATEs. Reviewing the code, I realized the INSERTs were using parameter binding and a data tuple, and the UPDATEs were not, just sending a simple plain text SQL statement to execute.

I then decided to replace the code used for INSERTs with a simple full text based SQL statement. This required replacing the WKB geometries with WKT, and appending any attributes in a single long SQL statement for the INSERT. This allowed me to get rid of the parameter binding, and re-run a full scale test with the >135M record INSERT in an empty, truncated table.

Much to my surprise, but a confirmation of my suspicions, it finally finished and managed to get through all of the 135M records using 16 threads to insert records in parallel on the first try.

Actually, before I did this and realized the potential issue with parameter binding, I also ran into another, possibly related issue. In an attempt to solve the HY000 issue, and before the switch to a full text based insert and WKT, I followed the recommendations in the pyodbc documentation as stated on this page:

https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-PostgreSQL

I initially did not specify the encoding as per the above link. I then decided to add this, in an attempt to possibly overcome the issue, by setting the following code lines in my code:
`pyodbcConnection.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')`
`pyodbcConnection.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')`
`pyodbcConnection.setencoding(encoding='utf-8')`
My database is UTF-8 as well.

However, instead of this fixing anything, I suddenly got consistent errors with a much smaller dataset that I had successfully processed multiple times before. This dataset has only 500k records, and it started to fail after about 130k records.

Removing the encoding settings, the INSERTs of the 500k records again successfully finished.

I am at a total loss why the encoding settings would cause this, but the results were quite clear. Leaving pyodbc to use its own defaults allowed the processing to finish, setting encoding on the connection object instead caused failure.

Other things I checked:
- Disk space: as said, with 2x 1.4TB there is plenty of disk space, and I have never witnessed disk space coming even close to being used up with the OpenStreetMap Europe extract, even though I am creating extra custom tables next to the ones created by osm2pgsql.
- Verified I ran all the latest application versions for the relevant software, including the PostgreSQL ODBC driver.

I realize this issue may not be a pyodbc one, but may be an issue/bug in the PostgreSQL ODBC driver, or something possibly to do with Virtualbox. However, before I needlessly start cross posting this issue elsewhere, and also taking into account the observed issue regarding encoding that is part of the pyodbc documenation and recommendations, I would sincerely appreciate some guidance about the different options, and the likelihood of where this issue is residing, pyodbc, PostgreSQL ODBC driver, or Virtualbox?

**Comment by mboeringa** [comment]
Hmmm... might this potential memory leak issue also mentioning parameter binding be related?:

https://github.com/mkleehammer/pyodbc/issues/378

**Comment by mboeringa** [comment]
@mkleehammer , @v-chojas , @gordthompson ,

Any comments regarding this issue, and especially the question whether it likely is a pyodbc, PostgreSQL ODBC driver, or Virtualbox issue?

I have now re-run the full scale >135M INSERT test a second time using WKT geometries, which again successfully finished (which is time-consuming). I was never able to do that using WKB geometries and parameter binding.

This is a clear indication to me there is a serious issue with parameter binding. Considering smaller datasets essentially always finish, but the bigger the dataset gets, the issues with failures start compounding up to the point of almost 100% failure when using parameter binding, the potential memory leak issue seems at least a plausible explanation, as I assume that may get worse the bigger the dataset being processed?

Any other ideas or remarks?

**Comment by gordthompson** [comment]
Have you seen #490 ? Does it give you any ideas that you may not have tried yet?

**Comment by gordthompson** [comment]
Possibly (tangentially) related: #490

**Comment by v-chojas** [comment]
I am not familiar with PostgreSQL but if you are suspecting it is a memory leak then watch the memory usage of the application and see if it is hitting a limit when it fails. You also have not mentioned the exact error message that occurs, which can hint at what happened to cause it.

**Comment by mboeringa** [comment]
> You also have not mentioned the exact error message that occurs, which can hint at what happened to cause it.

@v-chojas, I just get back the HY000 generic error, unfortunately without additional information, when my code catches the error, and I display it in my application. I guess setting an ODBC trace in the Windows ODBC connections settings is unwise, given the scale at which I am processing records... I don't know what exactly is being written to such a trace file, but with failure happening after dozens of millions of records being processed, that trace log might become problematic. Or am I wrong about this?

I am not sure if it is a memory leak issue, just saying the issue seems to be worse the bigger the dataset gets, up to a point of almost certain failure, while the WKT option without using parameter binding, happily churns through to the same datasets.

Also, I would appreciate if anyone of you could comment on the observation of the problem with setting the encoding as written in my original post, that seemed to exacerbate the issue. Why would the encoding make a difference?

**Comment by gordthompson** [comment]
ODBC traces really slow things down and the log files get large rather quickly so if you potentially need to process thousands of rows before an error occurs then the trace may not be all that helpful.

When trying to use WKB with parameters what type of values are you passing? Something like `byte`, `int`, `float`, `float`? Have you tried using [setinputsizes](https://github.com/mkleehammer/pyodbc/wiki/Cursor#setinputsizeslist_of_value_tuples) to explicitly specify the SQL types of the parameters?

**Comment by v-chojas** [comment]
When error occurs you should see more than just the 5-char error code, the error message should be provided by the driver and visible from pyODBC too as fields of the Error object. See this nearby issue for an example of that: https://github.com/mkleehammer/pyodbc/issues/830 Do you see any message in there when it happens, or is it blank? Because it comes from the driver, if it is blank then something very wrong may have happened, and you should request assistance from the driver authors (which is where I suspect the origin of this issue.)

As you have observed, ODBC trace would not be recommended due to the volume of data it creates.

**Comment by mboeringa** [comment]
> When trying to use WKB with parameters what type of values are you passing? Something like `byte`, `int`, `float`, `float`? Have you tried using [setinputsizes](https://github.com/mkleehammer/pyodbc/wiki/Cursor#setinputsizeslist_of_value_tuples) to explicitly specify the SQL types of the parameters?

@gordthompson  and @v-chojas , thanks for the responses so far, I really appreciate it!

@gordthompson , no, I haven't yet tried the **setinputsizes** yet. The documentation for that seems scarce, there is just one example, and I am not sure what exactly I am supposed to set if I know the types in PostgreSQL. Is there any solid information on that, that could help to guide me how to set it? Or more extensive examples you could point out?

@v-chojas , OK, thanks for the info about ODBC trace, this unfortunately doesn't seem an option than. As you said, and I also suspected, it may also be a driver issue, and yes, clearly something bad happens considering it also seems to take down my connection. Alternatively, but I am not sure how, it would be related to the Ubuntu UFW firewall, which is active, but I have set these ports and traffic to "allow", and of course, it the WKT option does work.\

I may attempt to remove the try/catch code, and just led it error out completely to see if the stack trace displays some more information, but I am not sure it will. It will surely take some time though before I can report the results of that though considering the processing time.

**Comment by gordthompson** [comment]
You could also try a test using [psycopg2](https://pypi.org/project/psycopg2/) to see if that works any better. psycopg2 is used extensively with SQLAlchemy in some pretty heavy-duty applications, so it has definitely been "field tested".

**Comment by mboeringa** [comment]
> You could also try a test using [psycopg2](https://pypi.org/project/psycopg2/) to see if that works any better. psycopg2 is used extensively with SQLAlchemy in some pretty heavy-duty applications, so it has definitely been "field tested".

@gordthompson , thanks. I may try to use psycopg2, but it will take some time to figure out how to use it, although at first glance, and probably thanks to the Python DB API, it seems pretty similar to pyodbc in its usage.

I initially came to use pyodbc, as it appeared to provide the most basic implementation (which was good enough for me), and thus allowed me to quickly familiarize myself with its usage and get up&running quickly, which is good thing about pyodbc. But I must admit I also overlooked psycopg2. And e.g. SQLAlchemy just seemed way to complex for my particular use case. I much prefer pulling in libraries with just a modest set of functionality that does the job, rather than being overwhelmed by a huge library with endless capabilities.

**Comment by mboeringa** [comment]
And yes, I realize I am definitely "field testing" ;-) pyodbc by putting it through its paces with a Geofabrik OpenStreetMap "Europe" sized extract!

**Comment by mboeringa** [comment]
@gordthompson: 

One question about psycopg2: 
It appears psycopg2 does not support creating a connection object using a predefined Windows ODBC data source / DSN? This is a nice feature of pyodbc, where I simply enter the DSN, and no longer need to supply database, host, port etc.

By the way, I recently upgraded to PostgreSQL 13, and restarted a full data load using **pyodbc** and the WKT geometries and _**no** parameter binding_.

This has now been running un-interrupted for 7 consecutive days on my poor 4 core test server, processing large amounts of records with the biggest dataset > 174M records. I have never been able to keep it up that long before without either the dreaded HY000 or an 08S01 error.

I am _**really, really**_ _cautious_ about this and certainly not making hard conclusions yet, but it might be that PostgreSQL 13 fixed something along the way that caused some of the issues I have been experiencing using pyodbc.

Before I come to definitive conclusions though, I first need to see this import & processing session finish, and also do a second import session using WKB geometries **and** parameter binding. Only then can I draw more solid conclusions about whether the upgrade to PostgreSQL 13 fixed some of my issues.

@mkleehammer:  would still highly appreciate your vision on some of the issues raised here, both regarding the HY000 error, and the observation regarding the encoding settings as described in my first post here.

If and when an updated version of pyodbc is released that has changes to the parameter binding, I am certainly willing to put it to test with some of my monster data loads and processing steps.

**Comment by gordthompson** [comment]
> It appears psycopg2 does not support creating a connection object using a predefined Windows ODBC data source / DSN? This is a nice feature of pyodbc, where I simply enter the DSN, and no longer need to supply database, host, port etc.

While psycopg2 may not understand ODBC DSNs directly, a DSN is really just a bunch of key/value pairs. When running Python on Windows you could write a little function that uses [dump_dsn](https://github.com/gordthompson/dump_dsn) to retrieve the key/value pairs as a `dict` and then pass the relevant ones to the `psycopg2.connect` method.

**Comment by gordthompson** [comment]
@mboeringa - Another reason why you might be better off using psycopg2:

> This has now been running un-interrupted for 7 consecutive days on my poor 4 core test server, processing large amounts of records with the biggest dataset > 174M records.

It sounds like you are performing individual (row-by-row) inserts and updates. With very large data sets that becomes impractical. An alternative is to bulk upload the new/updated rows and perform an "upsert". One example is described [here](https://stackoverflow.com/a/62379384/2144390). (I'm not suggesting that you necessarily use pandas; it's just an example.)

Unfortunately the PostgreSQL ODBC driver does not support pyodbc's `fast_executemany = True` feature (ref: [here](https://github.com/mkleehammer/pyodbc/wiki/Driver-support-for-fast_executemany)), so your bulk upload would be about the same as any other database with `fast_executemany = False`. However, psycopg2 offers a [copy_from](https://www.psycopg.org/docs/cursor.html#cursor.copy_from) method that can also speed up bulk uploads.

Simple test - Uploading 5000 rows to a remote (LAN) database:

| platform | method | approx. time (seconds) |
| -------- | ------ | ----------------------
| mssql+pyodbc | fast_executemany = False | 30
| mssql+pyodbc | fast_executemany = True | 1.5
| postgresql | pyodbc executemany | 30
| postgresql | psycopg2 executemany | 30
| postgresql | psycopg2 copy_from | 0.8

(YMMV)

**Comment by mboeringa** [comment]
> It sounds like you are performing individual (row-by-row) inserts and updates. With very large data sets that becomes impractical. An alternative is to bulk upload the new/updated rows and perform an "upsert". One example is described [here](https://stackoverflow.com/a/62379384/2144390). (I'm not suggesting that you necessarily use pandas; it's just an example.)

@gordthompson , it is not as bad as it sounds, in fact, _I am quite pleased with the performance I am getting out of **pyodbc**_! ;-)

The process I am talking about and taking 7 days is **_not_** a single data load of a single 174M record dataset to one table. In reality it is a highly complex multi-stage dataset load and update process that creates and updates _a few dozen tables_, that goes through many different steps involving generalization as well, so things like ST_SimplifyVW, ST_MakeValid, ST_Subdivide etc.

In reality, by now, it must have done **billions** of operations to the database!

You are right that these are individual INSERTS and UPDATES, but they are run using Python multi-threading and pyodbc (using a custom implementation of **concurrent.futures.ThreadPoolExecutor** that I wrote myself), where the client machine sends the INSERT and UPDATE requests in parallel on multiple threads.

Some stages of the processing are still single-thread (but depending on exact step may use PostgreSQL parallel execution), others are multi-threaded. 

For the multi-threaded stages, and depending on the complexity of the SQL command, I am getting between **1k to 7-8k records/s** INSERTs or UPDATEs for a 4 core multi-threaded processor (with only **6** allowed workers set in PostgreSQL), which I think is not bad given the processes run and the older hardware. Based on recent CPU benchmarks I have seen, I am pretty sure I could get double that from a modern server, so probably up to 15k records/s for 6 PostgreSQL workers, and probably a lot more with some of the current monster multi-core CPUs with up to and over 64 cores/CPU.

Also, I recently adjusted the code for the WKT full text INSERTs and UPDATEs, which now batches the INSERTs and UPDATEs in chunks of 50 records each by concatenating them into a long SQL statement and executing only a single 'cursor.execute' statement in the background for that chunked statement (transactions are committed every 40k records). I discovered this only improved the performance between some 7-12% max (I also tested larger chunks than 50 records, but performance did not really improve and at some stage dropped). I therefor have the strong feeling PostgreSQL already somehow "optimizes" such consecutive individual batch INSERTs and UPDATEs, maybe by caching the query plan? I don't have solid information for that though, and don't know if, when I am right, this is a recent addition to PostgreSQL in some of the latest versions.

**Comment by mboeringa** [comment]
@gordthompson , 

One nice thing about the individual INSERTs and UPDATEs is that I am capable to show real-time progress of the query execution using a thread safe global counter. With processes taking hours, that is really nice. I always hate it when heavy GIS type processes and operations don't show any form of progress, just leaving you guess whether it will take hours or days...

![afbeelding](https://user-images.githubusercontent.com/7635726/95673022-69f36400-0ba5-11eb-8ede-7cbb908b971e.png)

**Comment by mboeringa** [comment]
@gordthompson ,

I now actually managed to implement 'psycopg2' support into my application, took me the better part of yesterday and today to implement. I have not replaced 'pyodbc' though! This is now a dual capability in my application, where you can choose between using either pyodbc or psycopg2 as the bridge to PostgreSQL's ODBC driver.

I must say I now also appreciate some of pyodbc's convenience functions more ;-). 

psycopg2 is a more low-level API, missing handy things like a true row object, which meant using the 'psycopg2.extras' to pull in additional functionality, and requiring some thought and work to re-implement parts of the code for allowing psycopg2 to function properly.

This is now a really nice test-bed though, for comparing pyodbc to psycopg2... I intend to do some benchmarks in the near future, but for a fair comparison, I willl need to wait for my monster OpenStreetMap Europe data load to finish.

Here are some preliminary timing results of multi-threaded steps of the process flow, with psycopg2 as the interface. This is building data, so the complexity and size of the geometries involved is very limited. Note that these results were obtained with the Europe data load running against the same server in the background as well, so there is actually more heavy load on the server. 

I am quite pleased with these results considering the limited processing power of the 4-core server. I am also getting a bit more speed on the INSERTs than I expected, almost 10k records/s.

**### One of the heaviest steps involving generalization and checking & repairing geometry validity, just UPDATE: ###**

![afbeelding](https://user-images.githubusercontent.com/7635726/95679570-f6b51680-0bd3-11eb-9ccb-296e9019c572.png)


**### Using UPDATEs and ST_MakeValid to fix geometries: ###**

![afbeelding](https://user-images.githubusercontent.com/7635726/95679963-6e844080-0bd6-11eb-8bf2-bca436b187b1.png)


**### INSERT from my local client machine to database server via LAN: ###**

![afbeelding](https://user-images.githubusercontent.com/7635726/95679624-60352500-0bd4-11eb-9395-16f5ecde7ce6.png)

**Comment by mboeringa** [comment]
I now see the timing for the INSERTs is actually a bit over-optimistic. While the jobs finished in 10s, the start and end times registered represent a significantly longer timespan of 40s, probably due to the overhead in the multi-threaded processing. For a bigger dataset of almost 6M records, I see 3x bigger total time (5m jobs, 15m between start and end time), which in that case results in a realistic 6.4k records/s processed. It appears that with this implementation, the UPDATEs do not show this same issue. Start and end times seem to reasonably correspond with the job times.

**Comment by mboeringa** [comment]
@gordthompson 

I thought you might find these results interesting as well. I have now benchmarked 'pydodbc' against 'psycopg2'. From the results, I have the feeling psycopg2 is marginally faster, but pyodbc is holding up really well with the current custom multi-threaded implementation I developed. 

The differences are realistically certainly no bigger than 10%. Apart from syntax and a few minor programmatic differences due to the differences in the modules, there is one other thing to take into account here as well: the pyodbc implementation uses WKT, while the psycopg2 implementation uses WKB geometries to transfer data from client to server. This is due to an issue I encountered with 'pyodbc' with WKB where **cursor.executemany** does not seem to support WKB transfer, and results in a failure, whereas the equivalent 'psycopg2' **execute_batch** does accept WKB geometries as input.

The 'chunk size' is how many records / tuples I feed into one cursor.execute (pyodbc) or execute_batch (psycopg2) call. As you can see, the larger chunks size appears marginally faster in this case of landuse polygons, but with pyodbc, testing smaller building polygons, a chunk size of 500 was actually slower. So I think it depends on the actual record sizes in terms of geometries and number of fields being send as well.

**Results:**

psycopyg2: Landuse Netherlands: chunk size 50
46m22s

pyodbc: Landuse Netherlands: chunk size 50
53m21s

psycopyg2: Landuse Netherlands: chunk size 500
44m56s

pyodbc: Landuse Netherlands: chunk size 500
48m33s

**Comment by keitherskine** [comment]
Closed due to inactivity. Feel free to re-open with current information if necessary.
