### ISSUE TITLE
Where pyodbc looks for a certificate to use?

### ISSUE THREAD

**Issue by g0djan** [mkleehammer/pyodbc#825]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.9
- pyodbc: 4.0.30
- OS: Ubuntu 18.04.4 LTS
- DB: SQLServer 2016sp2
- driver: ODBC Driver 17 for SQL Server

### Issue
Hi, we are using certificates signed by our own certificate center. And we want to connect with `encrypt='yes', trust_server_certificate='no'`, but now I get 
OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]SSL Provider: [error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:unable to get local issuer certificate] (-1) (SQLDriverConnect)')

I added our certificate to trusted certificates and it helped for connection from Golang.
```
wget "https://path/to/certificate/CA.pem" -O /usr/local/share/ca-certificates/root.crt && \
update-ca-certificates
```
But pyodbc doesn't use it and I still got the error.
Where pyodbc looks for a certificate to use?
Is it possible to set a path to a certificate?

Connection string:
```
conn = pyodbc.connect( 
    driver='{ODBC Driver 17 for SQL Server}', 
    server='hostname,1433', 
    database='db1', 
    uid='user1', 
    pwd='<pass>', 
    encrypt='yes', 
    trust_server_certificate='no') 
```

**Comment by v-chojas** [comment]
This is not related to pyODBC, and the correct keyword for the ODBC Driver 17 for SQL Server is `TrustServerCertificate`. Please see the documentation for more information:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-ver15#using-tlsssl

https://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver15

**Comment by g0djan** [comment]
It's the same keyword. It works for azure. But the second link looks useful, there is a ClientCertificate option. I'll check it.

**Comment by v-chojas** [comment]
`TrustServerCertificate` is no by default, so you would not notice any difference anyway, and Azure SQL uses certificates that are already trusted by default. But it is definitely not `trust_server_certificate`.

**Comment by mkleehammer** [comment]
It looks like @v-chojas has taken care of this.  Thanks.  Closing.
