### ISSUE TITLE
Issue in Select binary large values 

### ISSUE THREAD

**Issue by vandanabhay** [mkleehammer/pyodbc#826]
I am using Pyodbc with unixodbc and while doing a select on binary data 

row = cursor.execute('select file from test where id = 1').fetchone()[0]

i get row with length 4096 . I am not able to use SQLGetData of ODBC from python to select large data and the same is not shown in wiki or any tests .

**Comment by v-chojas** [comment]
Please provide as much information about your environment as possible. There is considerable variation between DBMSs and ODBC drivers and it is not possible to answer your question without more information.

**Comment by vandanabhay** [comment]
I am using database as Apache Ignite , with unixodbc on Ubuntu 18.04 . I create a column with type binary and am able to work with c/odbc without any issue . But with pyodbc it is able to insert well but on select the value is truncated to 4096 .

**Comment by vandanabhay** [comment]
[odbctrace.txt](https://github.com/mkleehammer/pyodbc/files/5259568/odbctrace.txt)
Adding file odbctrace where i can see
[ODBC][722][1600757419.094829][SQLGetData.c][534]
                Exit:[SQL_SUCCESS]
                        Buffer = [BINARYDATA...]
                        Strlen Or Ind = 0x7fffda3c96c0 -> 4096

**Comment by vandanabhay** [comment]
while inserting , in the same column we can see 5289384 bytes were inserted .
[ODBC][722][1600757417.883492][SQLBindParameter.c][217]
                Entry:
                        Statement = 0x1bc9d90
                        Param Number = 1
                        Param Type = 1
                        C Type = -2 SQL_C_BINARY
                        SQL Type = -3 SQL_VARBINARY
                        Col Def = 5289384
                        Scale = 0
                        Rgb Value = 0x7f8f9b5d0010
                        Value Max = 5289384
                        StrLen Or Ind = 0x1bca968

**Comment by vandanabhay** [comment]
[odbctrace_c.txt](https://github.com/mkleehammer/pyodbc/files/5259614/odbctrace_c.txt)
This is trace with same select query in C , where SQLGetData.c is called multiple times till it has value .

**Comment by gordthompson** [comment]
Please check the version of unixODBC that you are using (run `odbcimst -j` in a terminal window) and consider upgrading to the latest version of your current version is rather old.

**Comment by vandanabhay** [comment]
sudo odbcinst -j
unixODBC 2.3.9
DRIVERS............: /usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources
USER DATA SOURCES..: /root/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

**Comment by vandanabhay** [comment]
The issue that i see is that SQLGetData returns SQL_SUCCESS_WITH_INFO for varchar and SQL_SUCCESS for binary . Moreover cbData ie StrLen_or_IndPtr returns actual length in case of varchar and 4096 in case of binary . So if i modify the function for read continuously for both SQL_SUCCESS and SQL_SUCCESS_WITH_INFO  and also realloc with 4096 byte each again once it is full . Then it works well .

**Comment by gordthompson** [comment]
This appears to be a driver issue. When I do the same thing with "ODBC Driver 17 for SQL Server" to retrieve a 11_936-byte JPEG file I see

``` text
[ODBC][2254][1600867369.318414][SQLGetData.c][237]
        Entry:
            Statement = 0x1a771d0
            Column Number = 1
            Target Type = -2 SQL_C_BINARY
            Buffer Length = 4096
            Target Value = 0x1a90d00
            StrLen Or Ind = 0x7fff0908ece0
[ODBC][2254][1600867369.318866][SQLGetData.c][545]
        Exit:[SQL_SUCCESS_WITH_INFO]                
            Buffer = [BINARYDATA...]                
            Strlen Or Ind = 0x7fff0908ece0 -> 11936
[ODBC][2254][1600867369.319026][SQLGetData.c][237]
        Entry:
            Statement = 0x1a771d0
            Column Number = 1
            Target Type = -2 SQL_C_BINARY
            Buffer Length = 7840
            Target Value = 0x1a93d20
            StrLen Or Ind = 0x7fff0908ece0
[ODBC][2254][1600867369.320028][SQLGetData.c][545]
        Exit:[SQL_SUCCESS]                
            Buffer = [BINARYDATA...]                
            Strlen Or Ind = 0x7fff0908ece0 -> 7840
```

so the SQL Server driver is returning the first 4096 bytes along with SQL_SUCCESS_WITH_INFO to provide the total length, and then we call SQLGetData again to retrieve the remaining 7840 bytes.

**Comment by v-chojas** [comment]
https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function?redirectedfrom=MSDN&view=sql-server-ver15#retrieving-variable-length-data-in-parts

"If there is more data to return or not enough buffer was allocated for the terminating character, SQLGetData returns SQL_SUCCESS_WITH_INFO and SQLSTATE 01004 (Data truncated). When it returns the last part of the data, SQLGetData returns SQL_SUCCESS."

If the driver is not returning success with info to indicate there is more data, how would the application know there is more? Definitely a bug in the driver.

**Comment by vandanabhay** [comment]
OK i will get it modified in Apache Ignite driver and take it with their team . Thanks for your help and explanation
