### ISSUE TITLE
Is there an exposed method for parameter binding outside of execute?

### ISSUE THREAD

**Issue by invokermain** [mkleehammer/pyodbc#828]
I want to switch from pymssql to pyodbc but I cannot find an analogous method for `pymssql._mssql.substitute_params()` which returns the string with parameters bound.

This function is really useful for building complicated SQL queries piece-by-piece whilst preventing SQL injectional (as parameter count can vary).

EDIT: Browsing a bit more I can see that this is handled by the ODBC API itself. And therefore I am guessing difficult/impossible to expose.

Is building SQL statements piece-by-piece in Python an anti-pattern? Also, how would one log the exact function run against the SQL server?

Here is an example of the pattern I'm talking about (pseudocode), I find myself using this quite often. Without the ability to bind parameters I imagine you would have to have two create one of two possible parameter tuples and query strings. Which doesn't lend to readability.
```
def query_database(min_date: date = None):
    if date:
        date_filter = bind_parameters("AND CreatedDate >= ?", min_date)
    else:
        date_filter = ""

    return cursor.execute(
        """
             SELECT * FROM my_table
             WHERE 1=1
         """
         + date_filter
    )
```

**Comment by gordthompson** [comment]
> I can see that this is handled by the ODBC API itself. And therefore I am guessing difficult/impossible to expose.

That is correct. pymssql did the parameter binding itself, but pyodbc (and ODBC in general) does not.

> Without the ability to bind parameters I imagine you would have to have two create one of two possible parameter tuples and query strings. Which doesn't lend to readability.

I dunno, this doesn't look so bad:

``` python
def query_database(min_date: date = None):
    params = []
    if date:
        date_filter = " AND CreatedDate >= ?"
        params.append(min_date)
    else:
        date_filter = ""

    return cursor.execute(
        """
             SELECT * FROM my_table
             WHERE 1=1
         """
         + date_filter,
        params
    )
```

**Comment by invokermain** [comment]
👍 Thanks for the quick reply, I was secretly hoping to avoid rewriting 50 usages of `substitute_params` when switching across.
