### ISSUE TITLE
Pyodbc update statement return 0 rows on MSSQL even though row was updated

### ISSUE THREAD

**Issue by yechiel-optimalq** [mkleehammer/pyodbc#829]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.30
- OS: Windows
- DB: SQL Server 12
- driver: ODBC Driver 17 for SQL Server

### Issue

All of a sudden pyodbc started returning rowcount==0 on update statements for specific database

Observed behavior:
example code test
import pyodbc

conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=SrVNAME,1111;DATABASE=DB_NAME;Trusted_Connection=yes;')
crsr=conn.cursor()
rslt=crsr.execute("update DBNAME.dbo.TABLE_DB set TIME='00000003' where ID=4653")
conn.commit()
print (rslt)
print(rslt.rowcount)

The rslt.rowcount ==0, even though i see the row updated in DB.

And when testing on another database, i get correct rowcount. 

Expected behavior:
Rowcount == 1.

**Comment by keitherskine** [comment]
If you include "print(crsr.rowcount)" at the end of the script, what does that print out?

**Comment by yechiel-optimalq** [comment]
0.

After running more tests i found out there is a trigger on the table "AFTER UPDATE" which is the reason for the issue.
Any idea on how i can get the ROWCOUNT without the trigger impacting? Some places recommending SCOPE_IDENTITY and other... donnow

**Comment by v-chojas** [comment]
Since you say "all of a sudden", and that it works on "another database" (server?), find out what changed on the server. 

In particular, check if someone turned on the NOCOUNT option for your database user:
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-user-options-server-configuration-option?view=sql-server-ver15

**Comment by yechiel-optimalq** [comment]
Yes, what changed was the trigger that i just found was added.

**Comment by yechiel-optimalq** [comment]
Any idea on how i can get the ROWCOUNT without the trigger impacting?

**Comment by v-chojas** [comment]
The trigger runs after your query, so you are seeing its results too; you can't get around that without disabling the trigger.

**Comment by gordthompson** [comment]
@v-chojas - Would `SET NOCOUNT ON;` in the trigger help prevent the issue? (Sorry, I can't test myself atm.)

**Comment by gordthompson** [comment]
> 
> 
> Would `SET NOCOUNT ON;` in the trigger help prevent the issue?

I just did a quick test and adding `SET NOCOUNT ON;` to my trigger did seem to work around the issue.

**Comment by mkleehammer** [comment]
Closing since this is a DB specific issue.  Please reopen if I misunderstood.

**Comment by s-maibuecher** [comment]
> > Would `SET NOCOUNT ON;` in the trigger help prevent the issue?
> 
> I just did a quick test and adding `SET NOCOUNT ON;` to my trigger did seem to work around the issue.

For future readers: This helped.
