### ISSUE TITLE
Windows wheels for Python 3.9

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#833]
Until such time as there is another release of pyodbc, Windows wheels for Python 3.9 are available at

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc

**Comment by mkleehammer** [comment]
Thanks Gord.   We should talk about adding you as a member...

I've now uploaded 64-bit wheels for macOS and Windows.

I just changed jobs, so I will be able to focus a bit more on getting this to the next level.

**Comment by adg-mh** [comment]
@mkleehammer Will 32-bit wheels no longer be supplied?

**Comment by zinkj** [comment]
@mkleehammer Were 32-bit wheels dropped or was this overlooked?
