### ISSUE TITLE
Successive escape sequences discarded

### ISSUE THREAD

**Issue by unresto** [mkleehammer/pyodbc#838]
### Environment

- Python: 3.8.5 32-bit
- pyodbc: 4.0.30
- OS: Windows 10 Enterprise
- DB: Window SQL Server 15 (2019)
- driver: SQL Server

### Issue

Expected behavior: Strings inserted or updated into a column are returned unchanged.

Observed behavior: Successive escape sequences are discarded from strings.  

(NOTE: This editor also seems to be having trouble with the triple slash - this is \\\\ followed by \n )
Insert: "tables\\\\\n(ii)Invoke"
Returns: "tables(ii)Invoke"

Putting a space or other printable character between the escape sequences causes them to not be discarded.

Insert: "tables\\\\ \n(ii)Invoke"
Returns: "tables\\\\ \n(ii)Invoke"

Here's the code, just basic insert or update:

> id = 'ID-1'
> value = 'tables\\\\\n(ii)Invoke'
> 
> cursor.execute('CREATE TABLE IF NOT EXISTS mytable (pk NVARCHAR(50) PRIMARY KEY, title NTEXT NOT NULL);')
> cursor.execute('INSERT INTO mytable (pk, title) VALUES(?, ?);', (id, value))
> cursor.execute('UPDATE mytable SET title = ? WHERE pk = ?;', (id, value))

**Comment by v-makouz** [comment]
Can you provide the code you are using to insert these values?

**Comment by unresto** [comment]
Edits: I noticed that the editor here messes up the multiple slashes too, so when I typed \\\\ followed by \n it removed one of the slashes.  Corrected the text, and added a simple code example too.

**Comment by gordthompson** [comment]
@unresto - I am unable to reproduce your issue:

```
>>> import pyodbc
>>> cnxn = pyodbc.connect("DSN=mssqlLocal")
>>> crsr = cnxn.cursor()
>>> result = crsr.execute("SELECT ? AS foo", "tables\\\n(ii)Invoke").fetchval()
>>> print(repr(result))
'tables\\\n(ii)Invoke'
```

**Comment by unresto** [comment]
Thank you, I will go back and see what's going on.

**Comment by mkleehammer** [comment]
I'm going to close this as stale for now.  Thanks @gordthompson
