### ISSUE TITLE
Cursor.procedures() returns adulterated procedure names with msodbcsql17

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#840]
`Cursor.procedures()` returns procedure names with `;n` appended to the end. For example `'sp_droprole;1'` is returned when the actual procedure name is `'sp_droprole'`.

[procedures.LOG](https://github.com/mkleehammer/pyodbc/files/5505262/procedures.LOG)

``` python
from pprint import pprint

import pyodbc

cnxn = pyodbc.connect(
    """\
    DRIVER=ODBC Driver 17 for SQL Server;
    SERVER=(local)\\SQLEXPRESS;
    DATABASE=master;
    Trusted_Connection=yes;
    """
)

print(
    f"driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)}, version: {cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}"
)
# driver: msodbcsql17.dll, version: 17.06.0001

crsr = cnxn.cursor()
pprint(crsr.procedures(procedure="sp_droprole%").fetchall())
"""console output:
[('master', 'sys', 'sp_droprole;1', -1, -1, -1, None, 2),
 ('master', 'sys', 'sp_droprolemember;1', -1, -1, -1, None, 2)]
"""
```

**Comment by v-chojas** [comment]
cursor.procedures() -> SQLProcedures -> sp_stored_procedures

https://stackoverflow.com/questions/1174579
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-procedure-transact-sql

This behaviour is by design.

**Comment by gordthompson** [comment]
Okay, thanks.
