### ISSUE TITLE
pyodbc/fasttosql table issue

### ISSUE THREAD

**Issue by erenhan1** [mkleehammer/pyodbc#842]
Hi,
I'm quite new in python and I'm trying to create a small ETL process, so in order to do that Im trying to upload df to sql server, my code was working very fine in local laptop until we move to company's server instance and I started to having error, basically my code was like that and it was working.
Working code:
```
import pandas as pd
import pyodbc
from fast_to_sql import fast_to_sql as fts
df=pd.read_excel(r'C:\Users\han.37\Desktop\Contact Pattern\Archive\Skill List.xlsx')
sql_conn = (
r'DRIVER={SQL Server Native Client 11.0};'
r'SERVER=GRATHLT37320;'
r'DATABASE=Performance;'
r'Trusted_Connection=yes;'

)
conn_db = pyodbc.connect(sql_conn)
create_statement = fts.fast_to_sql(df, 'cpattern' , conn_db, if_exists='replace', temp=False)

conn_db.commit()
conn_db.close()
```

Error Code:

```
import pandas as pd
import pyodbc
from fast_to_sql import fast_to_sql as fts
df=pd.read_excel(r'C:\Users\han.37\Desktop\Contact Pattern\Archive\Skill List.xlsx')
sql_conn = (
r'DRIVER={SQL Server Native Client 11.0};'
r'SERVER=GRATHDB03\REPLICA;'
r'DATABASE=Performance;'
r'Trusted_Connection=yes;'

)
conn_db = pyodbc.connect(sql_conn)
create_statement = fts.fast_to_sql(df, 'cpattern' , conn_db, if_exists='replace', temp=False)

conn_db.commit()
conn_db.close()
```

And the error is;
ProgrammingError: ('42000', '[42000] [Microsoft][SQL Server Native Client 11.0][SQL Server]The specified schema name "None" either does not exist or you do not have permission to use it. (2760) (SQLExecDirectW)')

But the issue is there is no permission, I have all the permissions by our IT team.

**Comment by v-chojas** [comment]
'None' is an odd name for a schema, but if `select * from sys.schemas where name = 'None'` returns no rows, then the error message is true - you need to find which query is emitting that error and modify it appropriately.

Also note there is a newer ODBC driver available, [ODBC Driver 17 for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc).

In any case, this does not appear to be an issue in pyODBC.

**Comment by gordthompson** [comment]
If you are using

https://pypi.org/project/fast-to-sql/

then you should probably be asking your question here:

https://github.com/jdglaser/fast-to-sql/issues

**Comment by erenhan1** [comment]
Wrong categor and issue resolved with sqlalcehmey+pyodbc
