### ISSUE TITLE
Make this library async supportive

### ISSUE THREAD

**Issue by ShadowFox88** [mkleehammer/pyodbc#844]
I'm using this library for my discord bot, and it is very slow because this library runs everything in sync, moving it to async would be good.

**Comment by v-chojas** [comment]
Points to consider:

- Not all ODBC drivers support async mode
- Even if they do, your bottleneck is likely to be the database
- Async ODBC adds a lot of additional complexity

**Comment by ShadowFox88** [comment]
I recommend aioODBC for async support
