### ISSUE TITLE
trouble getting a connection to azure synapse

### ISSUE THREAD

**Issue by mihaipopa** [mkleehammer/pyodbc#847]
I am using pyodbc to connect to an azure synapse db from a centos box.

I get
``` 
"Unable to set SQL_ATTR_CONNECTION_POOLING attribute"
```
right from the pyodbc.connect() method.
I did try to set pyodbc.pooling = False, before trying to get the connection, but then I get
```
"'utf-8' codec can't decode byte 0xf5 in position 2: invalid start byte"
```
which is weird since I am not executing any query, just pyodbc.connect(...)

I also tried to set odbc trace but I get nothing in the log...

Here's my env:
```
OS: CentOS Linux release 7.5.1804 (Core) 
Python: Python 3.7.4
Pyodbc: Version: 4.0.30
ODBC: unixODBC 2.3.7

odbcinst.ini:
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.6.so.1.1
UsageCount=1
```

By the way, I get the same message if I use the wrong driver name, or any of the other connection params.
I do have it working on my local box which is a mac, but I need to fix the centOS which is our jenkins box...

thank you in advance

**Comment by v-chojas** [comment]
Those symptoms suggest pyodbc is using a different driver manager than expected; try to connect from command line with `isql -v -k '<your connection string here>'`, and if that works, `strace` it and see where it is loading the `libodbc` library from. Then try the same from within Python.

**Comment by mihaipopa** [comment]
Thank you,

I've done that already, it worked.
Don't have root on that box, I will have to wait for someone to install strace for me:(

**Comment by v-chojas** [comment]
You can also try to find if more than one DM is installed by
`find / -name libodbc.so.2`
if you see multiple instances of that file it is likely to be causing this problem.

**Comment by mihaipopa** [comment]
sorry for the delay, there is only one libodbc:

[jenkins@np-lnx77-01 ~]$ sudo find / -name libodbc.so.2
/usr/lib64/libodbc.so.2

tried to run:
```isql -v -k '<your connection string here>'``` 
that does not work, but  
```isql -v '<your connection string here>' <myuser> <mypass>```

does work, and it loads the libodbc from /usr/lib64

**Comment by v-chojas** [comment]
Open a Python, `import pyodbc` and then `pyodbc.__file__` to see where the library for pyodbc is. Run `ldd` on that file and post the results.

**Comment by mihaipopa** [comment]
[jenkins@np-lnx77-01 ~]$ python3
Python 3.7.4 (default, Mar  3 2020, 09:14:27) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc     
>>> pyodbc.__file__
'/usr/local/lib/python3.7/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so'

please let me know if u need anything else

**Comment by v-chojas** [comment]
`ldd /usr/local/lib/python3.7/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so`

**Comment by mihaipopa** [comment]
[jenkins@np-lnx77-01 ~]$ ldd /usr/local/lib/python3.7/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007fffbd5f9000)
	libodbc.so => /opt/teradata/client/17.00/lib64/libodbc.so (0x00007fcb90ff4000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fcb90ced000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fcb909eb000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fcb907d5000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fcb905b9000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fcb901eb000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fcb8ffe3000)
	libodbcinst.so => /opt/teradata/client/17.00/lib64/libodbcinst.so (0x00007fcb8fd64000)
	libddicu28.so => /opt/teradata/client/17.00/lib64/libddicu28.so (0x00007fcb8ee6d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fcb8ec69000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcb91535000)

**Comment by mihaipopa** [comment]
Thank you very much V,

it now works (while terdata does not:), but at least we know what needs to be done)
