### ISSUE TITLE
pyodbc access issue to SQL server from AIX7.2

### ISSUE THREAD

**Issue by bergen288** [mkleehammer/pyodbc#850]
### Environment

- Python: 3.7.6
- pyodbc: 4.0.30
- OS: AIX7.2 (64bit)
- DB: Microsoft SQL Server 2012 (SP4-GDR)
- driver: SAS Institute, Inc 7.1 SQL Server Wire Protocol

### Issue
unixODBC is installed in ```/usr/local/unixODBC```.  ``` odbcinst -j``` has the following output:
```
unixODBC 2.3.5
DRIVERS............: /opt/freeware/etc/odbcinst.ini
SYSTEM DATA SOURCES: /opt/freeware/etc/odbc.ini
FILE DATA SOURCES..: /opt/freeware/etc/ODBCDataSources
USER DATA SOURCES..: /home/sas/.odbc.ini
SQLULEN Size.......: 4
SQLLEN Size........: 4
SQLSETPOSIROW Size.: 2
```
SQL ODBC is part of SAS9.4M6 installation in ```/software/sas94m6/home/AccessClients/9.4/SQLServer```.  Its title is ```SAS Institute, Inc 7.1 SQL Server Wire Protocol```.  ```print(pyodbc.drivers())``` has the following output:
```
['ODBC Drivers', 'ODBC Translators', 'Administrator', 'SAS Institute, Inc 7.1 SQL Server Legacy Wire Protocol', 'SAS Institute, Inc 7.1 SQL Server Wire Protocol', 'NetezzaSQL', 'DB2']
```
Below is my pyodbc connection string:
```
conn = pyodbc.connect(
                    "Driver={SAS Institute, Inc 7.1 SQL Server Wire Protocol};"
                    "Server=JWPKSQLEP01.corp.checkfree.com;"
                    "Port=1490;"
                    "Database=KUB;"
                    "username=checkfree\\xzhang;"
                    "password=xxxxxxxx;"
                    )
cursor = conn.cursor()
cursor.execute("SELECT @@version;")
for row in cursor.fetchall():
    print(row)
conn.commit()
cursor.close()
conn.close()
```
Below is the error:
```
Traceback (most recent call last):
  File "pyodbc_sql.py", line 45, in <module>
    "Driver={SAS Institute, Inc 7.1 SQL Server Wire Protocol};"
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/software/sas94m6/home/AccessClients/9.4/SQLServer/lib/S0sqls27.so' : file not found (0) (SQLDriverConnect)")
```
Somehow, unixODBC can't find ```/software/sas94m6/home/AccessClients/9.4/SQLServer/lib/S0sqls27.so```.  But I am sure it is there as shown below.  What's wrong with it?
```
Login=xzhang: Line=23 > ls -l /software/sas94m6/home/AccessClients/9.4/SQLServer/lib/S0sqls27.so
-r-xr-xr-x-    1 sas      sas         5487829 Nov 21 2018  /software/sas94m6/home/AccessClients/9.4/SQLServer/lib/S0sqls27.so
```

Thanks in advance.

**Comment by v-chojas** [comment]
"File not found" can also refer to the dependencies of the driver. Check that it can find and load its dependency libraries too.

**Comment by bergen288** [comment]
My ```SAS acces to SQL``` uses the same SQL ODBC driver without any issue.  do you have any clue what to check?

Thanks.

**Comment by v-chojas** [comment]
I am not familiar with AIX, but if you have a similar tool to `strace` on Linux you can see what files it tries to load, and which one fails.

**Comment by bergen288** [comment]
My SQL/Netezza ODBC data set names are defined in /software/sas94m6/home/AccessClients/9.4/SQLServer/odbc.ini on AIX.  odbcinst.ini is defined in the same location.  How may I take advantage of them?

**Comment by v-chojas** [comment]
You can try to have pyODBC link against a custom unixODBC or other DM, but may encounter issues if they are not completely compatible.

**Comment by bergen288** [comment]
I have trouble to get ```strace``` working.  But ```ldd``` gives me the following output.  Not sure what is ```libS0icu27.a(S0icu27.so)```.  Any clue?
```
Login=xzhang: Line=33 > ldd /software/sas94m6/home/AccessClients/9.4/SQLServer/lib/S0sqls27.so
/software/sas94m6/home/AccessClients/9.4/SQLServer/lib/S0sqls27.so needs:
         /usr/lib/libc_r.a(shr_64.o)
         /usr/lib/libC.a(ansi_64.o)
Cannot find libS0icu27.a(S0icu27.so)
         /usr/lib/libC.a(shr_64.o)
         /usr/lib/libpthreads.a(shr_xpg5_64.o)
         /unix
         /usr/lib/libcrypt.a(shr_64.o)
         /usr/lib/libC.a(shrcore_64.o)
         /usr/lib/libC.a(ansicore_64.o)
         /usr/lib/libc.a(shr_64.o)
```

**Comment by v-chojas** [comment]
You can try to ruun `find / -name libS0icu27.a` to find where that file is.

**Comment by bergen288** [comment]
```find``` gives me ```/software/sas94m6/home/AccessClients/9.4/SQLServer/lib/libS0icu27.a```.  The ```lib``` directory has the following files/modules.  As I mentioned,  ```/software/sas94m6/home/AccessClients/9.4/SQLServer/``` is the location of installed SAS SQL ODBC driver.

```
-rw-r--r--    1 sas      sas            2500 Oct 18 2018  DDS0.LIC
-r-xr-xr-x    1 sas      sas          744296 Oct 18 2018  S0msss27.so
-r-xr-xr-x    1 sas      sas           19511 Oct 18 2018  S0msssdlg27.so
-r-xr-xr-x    1 sas      sas         5487829 Nov 21 2018  S0sqls27.so
-r-xr-xr-x    1 sas      sas         2177336 Oct 18 2018  S0trc27.so
-rw-r--r--    1 sas      sas         2355110 Oct 18 2018  libS0curl27.a
-rw-r--r--    1 sas      sas        15024082 Oct 18 2018  libS0icu27.a
-rw-r--r--    1 sas      sas         3273716 Oct 18 2018  libS0mback.a
-rw-r--r--    1 sas      sas         4395194 Oct 18 2018  libS0mbackw.a
-rw-r--r--    1 sas      sas         2348738 Oct 18 2018  libodbc.a
-rw-r--r--    1 sas      sas         1960870 Oct 18 2018  libodbcinst.a
-r-xr-xr-x    1 sas      sas         2348319 Oct 18 2018  odbc.so
-r-xr-xr-x    1 sas      sas         2167261 Oct 18 2018  odbccurs.so
-r-xr-xr-x    1 sas      sas         1960448 Oct 18 2018  odbcinst.so
-r-xr-xr-x    1 sas      sas           67068 Oct 18 2018  vscnctdlg.so
```

**Comment by bergen288** [comment]
Both ```/software/sas94m6/home/AccessClients/9.4/SQLServer/lib```  and ```/software/sas94m6/home/SASFoundation/9.4/sasexe``` have to be exported to LIBPATH to resolve the issue.   Now I have the successful connection from Python to SQL server via ```pyodbc``` on AIX.  Thanks.

There is a new problem with Netezza access.  Below is my python script:
```
#!/bin/python
import pyodbc
conn = pyodbc.connect(
                      Driver='{NetezzaSQL}',
                      Server='10.30.4.76',
                      Port='5480',
                      Database='EPY_PROD_DWS',
                      UID='xzhang',
                      PWD='xxxxxxxx'
                      )
cursor = conn.cursor()

_sql = """
        select *
        from information_schema.columns
        limit 10
        ;
    """

cursor.execute(_sql)
for row in cursor.fetchall():
    print(row)
conn.commit()
cursor.close()
conn.close()
```
It works fine for connection from my Windows 10 workstation, but it has the following error on AIX:
```
Login=xzhang: Line=15 > pyodbc_neteza.py
Traceback (most recent call last):
  File "pyodbc_neteza.py", line 42, in <module>
    for row in cursor.fetchall():
pyodbc.ProgrammingError: No results.  Previous SQL was not a query.
```
I did google and saw lots of same error with connection to SQL, but none for connection to Netezza.  Do you know what's wrong with it?  Thanks.

**Comment by bergen288** [comment]
Never mind.  "nzpy" has no such problem.  I will use "pyodbc" for SQL and "nzpy" for Netezza.
Thanks.

**Comment by bergen288** [comment]
@v-chojas 

After a few days warning period, SAS SQL ODBC driver won't allow my python script to access it anymore.  Do you know any SQL ODBC driver that I may install on AIX?  Microsoft doesn't have one on AIX.

Thanks.
