### ISSUE TITLE
Unexpected Data Type Returned w/ Legacy Drivers

### ISSUE THREAD

**Issue by the-wondersmith** [mkleehammer/pyodbc#852]
### Environment

- Python: 32-bit
- pyodbc: 4.0.30
- OS: Windows 10
- DB: Borland Paradox
- driver: Intersolv DataDirect Connect ODBC v3.11

#### Expected Behavior

- When queried, data stored in a column with an internal type of `SQL_TINYINT`, `SQL_SMALLINT`, `SQL_INTEGER`, or `SQL_BIGINT` will be returned by pyodbc as a Python `int`.

#### Observed Behavior

- When queried, data stored in a column with an internal type of `SQL_INTEGER` is returned by pyodbc as a Python `float`

### Notes

- The Intersolv DataDirect Connect driver is (to put it mildly) *old*, but still nonetheless  functional. As best I can tell it was most recently updated in 1998, which means it supports the full specification for the SQL92 standard. I have experimentally verified this.
- Internally, the driver supports `SQL_INTEGER`, `SQL_DECIMAL`, `SQL_DOUBLE`, and `SQL_SMALLINT`. The columns in question that are returned as Python `floats` use `SQL_INTEGER`.
- The `float`-returning behavior seems to be pyodbc specific, as querying the same table / data by other means (i.e. [ODBC Query Tool](https://sourceforge.net/projects/odbcquerytool/files/odbcquerytool/)) yields the expected `int`-type value

What else can I do to help diagnose the issue?

**Comment by gordthompson** [comment]
You could do an [ODBC trace](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) to see what the driver is returning as the data type of the column in response to `SQLDescribeCol[W]`. For example, if I do a trace on

``` python
result = crsr.execute("SELECT CAST(1 AS float) as my_int_column").fetchval()
```

the trace contains

```
main            1bb0-1884	EXIT  SQLDescribeColW  with return code 0 (SQL_SUCCESS)
        HSTMT               0x03FC0368
        UWORD                        1 
        WCHAR *             0x009CF2DC [      13] "my_int_column"
        SWORD                      300 
        SWORD *             0x009CF2A0 (13)
        SWORD *             0x009CF294 (6)
        SQLULEN *           0x009CF298 (53)
        SWORD *             0x009CF2A8 (0)
        SWORD *             0x009CF2A4 (1)
```

The value `6` shows that the driver is reporting that column as `SQL_FLOAT`. Possible related values (from [here](https://github.com/microsoft/ODBC-Specification/blob/master/Windows/inc/sql.h)) would be

```
#define SQL_UNKNOWN_TYPE    0
#define SQL_CHAR            1
#define SQL_NUMERIC         2
#define SQL_DECIMAL         3
#define SQL_INTEGER         4
#define SQL_SMALLINT        5
#define SQL_FLOAT           6
#define SQL_REAL            7
#define SQL_DOUBLE          8
```

**Comment by the-wondersmith** [comment]
@gordthompson  Gord! I can't tell if we have to *stop* meeting like this, or if we need to catch up more often. 😁 Either way, thank you for once again coming to my rescue.

If it's not obvious, I'm revisiting the SQLAlchemy dialect I wrote for the Microsoft Paradox ODBC driver. I managed to get my hands on a copy of the Intersolv version that was shipped with Paradox when Corel was still publishing "developer" versions of Paradox. It doesn't have some of the fancier stuff that the Microsoft version does, but it also doesn't have any of the limitations either. Just to jog your memory, you helped me [figure a workaround](https://gist.github.com/the-wondersmith/92be7ff0b5954d612da35ead30768c47) for one of the more irritating bugs in the Microsoft driver.

For context on this particular bug, I'm working my way through the SQLAlchemy dialect test suite and kept getting failures in `OrderByLabelTest::test_composed_int_desc`. Looking at the emitted error in the pytest logs, the test was failing because `[(7.0,), (5.0,), (3.0,)] != [(7,), (5,), (3,)]` which I thought was odd.

The table creation and population statements issued by the dialect for this specific test are:

```sql
CREATE TABLE `some_table` (`id` Long Integer NOT NULL, `x` Long Integer, `y` Long Integer, `q` Alpha(50), `p` Alpha(50));
CREATE UNIQUE INDEX PRIMARY ON `some_table` (`id`);

INSERT INTO `some_table` (`id`, `x`, `y`, `q`, `p`) VALUES (1, 1, 2, 'q1', 'p3');
INSERT INTO `some_table` (`id`, `x`, `y`, `q`, `p`) VALUES (2, 2, 3, 'q2', 'p2');
INSERT INTO `some_table` (`id`, `x`, `y`, `q`, `p`) VALUES (3, 3, 4, 'q3', 'p1');

SELECT `some_table`.`x` + `some_table`.`y` AS `lx`  FROM `some_table` ORDER BY `some_table`.`x` + `some_table`.`y` DESC;
```

I did as you suggested and ran a trace. I put the full trace log [in a gist](https://gist.github.com/the-wondersmith/21662017a969455561110a151ca132d9#file-trace_log-txt-L723) in case there's anything more helpful in it that you can see. I also uploaded the reference documentation for the driver [here](https://gofile.io/d/epK0eV) if anyone finds it helpful. The relevant parts of the trace log are here:

First, the column definition for the table's `id` column. It's apparently being defined internally as `SQL_DOUBLE` even though it's specified as having the same type as the `x` and `y` columns.

```text
DatabaseBrowser 6394-5d7c	EXIT  SQLDescribeColW  with return code 0 (SQL_SUCCESS)
		HSTMT               0x064D7D40
		UWORD                        1 
		WCHAR *             0x00000000 <null pointer>
		SWORD                        0 
		SWORD *             0x00000000
		SWORD *             0x0019EBC8 (8)
		SQLULEN *           0x0019EBC0 (15)
		SWORD *             0x0019EBC4 (0)
		SWORD *             0x0019EBA0 (2)
```

Next, the definition for one of the text columns (`q`). Everything appears as expected:

```text
DatabaseBrowser 6394-5d7c	EXIT  SQLDescribeColW  with return code 0 (SQL_SUCCESS)
		HSTMT               0x064DA8A0
		UWORD                        4 
		WCHAR *             0x00000000 <null pointer>
		SWORD                        0 
		SWORD *             0x00000000
		SWORD *             0x0019E9F4 (1)
		SQLULEN *           0x0019E9EC (50)
		SWORD *             0x0019E9F0 (0)
		SWORD *             0x0019E9CC (1)
```

Last, the definition for one of the integer columns, which *also* appears as expected:

```text
DatabaseBrowser 6394-5d7c	EXIT  SQLDescribeColW  with return code 0 (SQL_SUCCESS)
		HSTMT               0x064DA8A0
		UWORD                        1 
		WCHAR *             0x00000000 <null pointer>
		SWORD                        0 
		SWORD *             0x00000000
		SWORD *             0x0019E9F4 (4)
		SQLULEN *           0x0019E9EC (10)
		SWORD *             0x0019E9F0 (0)
		SWORD *             0x0019E9CC (0)
```

I have no idea why the `id` column isn't using the same data type as the `x` and `y` columns, and I'll investigate that shortly. That shouldn't matter though since the `id` column isn't part of the query, right? Or am I completely bonkers?

**Comment by the-wondersmith** [comment]
Also, just to be *completely* ridiculous I tried this:

```python
import pyodbc

conn = pyodbc.connect("DSN=paradox_testing", autocommit=True)
cursor = conn.cursor()

result = cursor.execute(
    "SELECT INT(ROUND(INT(INT(`some_table`.`x`) + INT(`some_table`.`y`)), 0)) AS `lx`  FROM `some_table`"
).fetchall()

```

The result is *somehow* still `[(3.0, ), (5.0, ), (7.0, )]`  🤬

**Comment by gordthompson** [comment]
Hey, nice to see you again. Happy New Year!

If you want to further investigate "The float-returning behavior seems to be pyodbc specific" you could run the following VBScript and see what it reports:

``` vbscript
conn.Open "DSN=paradox_testing"
Set rst = CreateObject("ADODB.Recordset")
rst.Open "SELECT id FROM some_table", conn
vt = VarType(rst(0).Value)
Select Case vt
    Case 2
        vtName = "vbInteger"
    Case 4
        vtName = "vbSingle"
    Case 5
        vtName = "vbDouble"
    Case 8
        vtName = "vbString"
    Case Else
        vtName = "(other: " & vt & ")"
End Select
WScript.Echo vtName
```

**Comment by gordthompson** [comment]
@the-wondersmith - Any news?

**Comment by gordthompson** [comment]
Closing for now. Feel free to reopen if additional information becomes available.
