### ISSUE TITLE
pip 21.0 drops support for Python 2.7 and 3.5 - NOT an issue

### ISSUE THREAD

**Issue by keitherskine** [mkleehammer/pyodbc#857]
Just in case anyone was concerned that pyodbc's CI jobs will fail now that pip version 21 [has dropped support](https://pip.pypa.io/en/stable/news/#) for Python 2.7 and Python 3.5, this does not appear to be the case.  Both the AppVeyor and Travis jobs still appear to work successfully,  Actually the Travis jobs are not impacted by this at all, only the AppVeyor jobs attempt to upgrade pip to the very latest version.  When "python -m pip install --upgrade pip" is called in AppVeyor, the Python 2.7 and 3.5 jobs automagically upgrade pip to just 20.3.4 and the Python 3.6+ jobs upgrade pip to 21.0.  So, all good, no code changes on our part are necessary.

**Comment by mkleehammer** [comment]
Great to know.  I didn't even realize pip was dropping that.

I was hoping to drop 2.7 support myself, but the download stats show that way over half of the downloads are still on Python 2.  I don't mind dropping 3.5 though.

**Comment by keitherskine** [comment]
2.7 is still popular it would seem.  Anyway, I'm going to close this issue to keep things tidy.
