### ISSUE TITLE
SQL SELECT float rounding error

### ISSUE THREAD

**Issue by pinguin999** [mkleehammer/pyodbc#86]
Hi 

If I do a SQL SELECT to my DB to get a float value of 1.61 pyodbc retruns 1.609999...

I connect from Windows x64 with Python 2.7.9 and pyodbc 3.0.10 to MSSQL 2008 R2 Server.
I'm using 'Driver={SQL Server};'

I think it's a simple rounding error. 
Any help?

**Comment by mkleehammer** [comment]
This is actually not an error - floating point values often can't store a value that terminates in base 10 that don't terminate in base 2.  The most famous example is probably 0.1, which is actually not possible to store in a floating point number exactly - it repeats in base 2.  Therefore many exact values in base 10, apparently 1.61 is an example, must be approximated in a float.

The difference you are seeing is simply rounding for display.  Both systems are retrieving 1.6099999 but the DB is displaying it using something like `print('%0.2f', val)` which rounds to 2 digits after the decimal.

I'm not sure what database you are using, but it might have some decent documentation in its floating point data types section.  If you need exact values, such as when dealing with money, consider using the "numeric" or "decimal" data type in your database and the Python Decimal class.
