### ISSUE TITLE
Getting error - TypeError: fetchmany() takes no keyword arguments

### ISSUE THREAD

**Issue by sidnaik03** [mkleehammer/pyodbc#860]
Hi,
As per your documentation, [fetchmany(size=cursor.arraysize)
](https://github.com/mkleehammer/pyodbc/wiki/Cursor#fetchmanysizecursorarraysize) passing size parameter to the fetchmany() function, but its throwing an exception as fetchmany() takes no keyword arguments

- Python: 3.5.2
- pyodbc: 4.0.28
- OS: Windows 10 64 bit
- DB: SQL Server 2017
- driver: ODBC Driver 17 for SQL Server

My code snippet is
`
    try:
        cnxn = pyodbc.connect(
        'DRIVER={SQL Server};SERVER=devServ;DATABASE=TESTDB;UID=user;PWD=pwd11234')
        cursor = cnxn.cursor()
        results_one = cursor.fetchmany(size=10)
        results_two = cursor.fetchmany(size=10)
        cursor.close()
    except Exception as ex:
        print(ex.__str__())
    finally:
        connection.close()
`
What I am doing wrong? Please help.

**Comment by sidnaik03** [comment]
Got the work around. If you want fetch 10 rows then you need to specify cursor.arraysize = 10, and then you need to call cursor.fetchmany().

I guess this has to specify in the documentation.

**Comment by gordthompson** [comment]
@sidnaik03 - Thanks for reporting this. The wiki entry has been updated. Please feel free to close this now.

**Comment by sidnaik03** [comment]
Thanks @gordthompson.
