### ISSUE TITLE
Unable to install using pip 21 and python 3.8

### ISSUE THREAD

**Issue by vdantuluri-takeda** [mkleehammer/pyodbc#861]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8
- pyodbc: 4.0.36
- OS: Linux
- DB:
- driver: MSSQL

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

 In file included from src/buffer.cpp:12:0:
    src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
     #include <sql.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /var/lang/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zsh4k12i/pyodbc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zsh4k12i/pyodbc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qdjl8945/install-record.txt --single-version-externally-managed --home /tmp/pip-target-u5d_bajo --compile --install-headers /tmp/pip-target-u5d_bajo/include/python/pyodbc Check the logs for full command output.
make: *** [build-DependencyLayer] Error 1
Error: Process completed with exit code 1.

**Comment by v-makouz** [comment]
This error usually means that unixODBC or unixODBC-dev is not installed. 
Which OS is this?

**Comment by vdantuluri-takeda** [comment]
it is a Linux machine, and using wheel installation.

**Comment by gordthompson** [comment]
@vdantuluri-takeda - Have you seen this?

https://github.com/mkleehammer/pyodbc/wiki/Install#installing-on-linux

**Comment by vdantuluri-takeda** [comment]
Yes, i tried that, let me try using from a clean state. if the issue persists i will re-open.
