### ISSUE TITLE
Encoding problem with error messages

### ISSUE THREAD

**Issue by jcasale** [mkleehammer/pyodbc#863]
### Environment
- Python: 3.7.9 x64
- pyodbc: 4.0.30
- OS: Windows Server 2012 R2
- DB: Oracle 12.2.0.1.0
- driver: Oracle ODBC driver from client v12.01.00.02

### Issue
I am having difficulties determining the correct value for encoding such that error messages are converted correctly.

My connection configuration is as follows:
```py
    connection.setdecoding(pyodbc.SQL_CHAR, encoding='iso-8859-15')
    connection.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-16le')
    connection.setdecoding(pyodbc.SQL_WMETADATA, encoding='iso-8859-15')
```

If I use `utf-16le` for `SQL_WMETADATA`, I get surrogate errors decoding it. The iso codec is clearly wrong, errors returned appear as follows:

```
pyodbc.Error: ('HY000', '[HY000] [\x00O\x00r\x00a\x00c\x00l\x00e\x00]\x00... (918) (SQLExecDirectW)')
```

I captured a trace and the area around the error indicates an obvious problem which I most certainly would not expect to see in the trace as it has nothing to do with Python. Could this indicate a problem with the instant client installation?

```
		DIAG [HY000] [Oracle][ODBC][Ora]ORA-00918: column ambiguously defined
 (918) 

test            1cac-1fa0	ENTER SQLGetDiagRecW 
		SQLSMALLINT                  3 <SQL_HANDLE_STMT>
		SQLHANDLE           0x000000F450B63FB0
		SQLSMALLINT                  1 
		SQLWCHAR *          0x000000F44D7FE500
		SQLINTEGER *        0x000000F44D7FE4B4
		SQLWCHAR *          0x000000F44D7FE510 
		SQLSMALLINT               1023 
		SQLSMALLINT *       0x000000F44D7FE4B0

test            1cac-1fa0	EXIT  SQLGetDiagRecW  with return code 0 (SQL_SUCCESS)
		SQLSMALLINT                  3 <SQL_HANDLE_STMT>
		SQLHANDLE           0x000000F450B63FB0
		SQLSMALLINT                  1 
		SQLWCHAR *          0x000000F44D7FE500 [       5] "HY000"
		SQLINTEGER *        0x000000F44D7FE4B4 (918)
		SQLWCHAR *          0x000000F44D7FE510 [     114] "[Oracle][ODBC][Ora]ORA-00918: column ambiguously defined\ a\ 0????????????????????????????????????????????????????????"
		SQLSMALLINT               1023 
		SQLSMALLINT *       0x000000F44D7FE4B0 (114)
```

The only feedback on encoding I received from the dba's managing this instance appears below, and I am not clear whether I am misinterpreting that info or missing additional info to describe the necessary configuration.

PARAMETER | VALUE
--------- | -----
NLS_RDBMS_VERSION | 12.2.0.1.0
NLS_NCHAR_CONV_EXCP | FALSE
NLS_LENGTH_SEMANTICS | BYTE
NLS_COMP | BINARY
NLS_DUAL_CURRENCY | $
NLS_TIMESTAMP_TZ_FORMAT | DD-MON-RR HH.MI.SSXFF AM TZR
NLS_TIME_TZ_FORMAT | HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_FORMAT | DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_FORMAT | HH.MI.SSXFF AM
NLS_SORT | BINARY
NLS_DATE_LANGUAGE | AMERICAN
NLS_DATE_FORMAT | DD-MON-RR
NLS_CALENDAR | GREGORIAN
NLS_NUMERIC_CHARACTERS | .,
NLS_NCHAR_CHARACTERSET | AL16UTF16
NLS_CHARACTERSET | WE8ISO8859P15
NLS_ISO_CURRENCY | AMERICA
NLS_CURRENCY | $
NLS_TERRITORY | AMERICA
NLS_LANGUAGE | AMERICAN

**Comment by v-chojas** [comment]
try utf-16be

**Comment by jcasale** [comment]
That produced a similar result with a mix of Chinese characters instead of just escape characters.

**Comment by v-chojas** [comment]
in that case it might be utf-32be

**Comment by jcasale** [comment]
Still no luck:)

```
Traceback (most recent call last):
  File "D:\Python37\lib\encodings\utf_32_be.py", line 11, in decode
    return codecs.utf_32_be_decode(input, errors, True)
UnicodeDecodeError: 'utf-32-be' codec can't decode bytes in position 0-3: code point not in range(0x110000)
```

**Comment by keitherskine** [comment]
@jcasale You might want to try utf-32le just for good measure.  From the error message in your initial comment, I suspect utf-32le might be worth a go.

Also, there was one rather creative workaround I saw using "EXPLAIN \<query\>" that might help here: https://github.com/mkleehammer/pyodbc/issues/764#issuecomment-633525835

**Comment by mkleehammer** [comment]
The text *between* the square brackets is definitely utf16-be or UCS2BE.  It's the letters "Oracle" each as a big-endian two-byte character, so each starts with a 0x00 byte.  What does the rest of the error message look like.  UCS2 and UTF-16 are compatible for all characters defined for UCS2, so "utf16-be" really should be the right answer.

Do some of the fields, such as the SQLSTATE decode properly?

**Comment by jcasale** [comment]
Hi,
I wrote a simple select with a syntax error and I get the following:
```
pyodbc.Error: ('HY000', '[HY000] [Oracle][ODBC][Ora]ORA-00923: FROM keyword not found where expected\n\x00\x00\x00\x00\x00\x00\x00\x00\x13\x00\x00\x00壈솴ʐ\x00...
```
It appears the text message comes through with utf-16le, but when I switch to big-endian, even the message is decoded incorrectly and the entire string appears as Asian characters.

**Comment by v-chojas** [comment]
Everything after the run of \x00 looks like something left over from whatever was sitting in the buffer before.
I suspect the driver is returning an incorrect character length (double what it should be?)
