### ISSUE TITLE
pyodbc cursor.description is empty and query results fail to be returned

### ISSUE THREAD

**Issue by abekfenn** [mkleehammer/pyodbc#865]
### Environment:

- Python: 3.7
- pyodbc: 4.0.30
- OS: Linux Debian
- DB: MySql 5.6.23
- driver: MySQL ODBC 5.3 Unicode Driver
Note: I was able to produce this issue both on debian and red hat and MySql 5.6 and 8.0

### Issue
Stack trace:
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 383, in read_sql_query
    chunksize=chunksize,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 1744, in read_query
    columns = [col_desc[0] for col_desc in cursor.description]
TypeError: 'NoneType' object is not iterable

Note this appears to be related to two previously closed issues:
1. https://github.com/mkleehammer/pyodbc/issues/506
2. https://github.com/mkleehammer/pyodbc/issues/501
It seems this issue stems from a pyodbc bug in the 4.0.25 version.

### Expected behavior:
read_query should return always the query results for a given query, or the true issue underlying errors with the cursor is properly logged and raised to the user.

### Observed behaviour:
The iterator, cursor.description, is sometimes empty (i.e. no data for query columns is available) and the query will fail with the aforementioned error. Moreover, this seems to happen at random. 90% of the time, the query will execute successfully and a dataframe is returned, then 10% of the time cursor.description is empty.

### Additional details:
The queries being run all have column names for each column selected and should not return an empty dataset. 
The server is a client server and therefore I am unable to upgrade MySql version, however the issue occurs both on MySql 8 and MySql 5.6.

ODBC Trace Logs:
[ODBCTrace.txt](https://github.com/mkleehammer/pyodbc/files/5937881/ODBCTrace.txt)

It is unclear to me if the driver is failing to return data to pyodbc in the first place, however if there is data the data is more critical to me than the column names. 
sql.read_query calls frame.from_records to convert the returned data into a dataframe. 
frame.from_records accepts columns as None, definition below:
columns : sequence, default None
            Column names to use. If the passed data do not have names
            associated with them, this argument provides names for the
            columns. Otherwise this argument indicates the order of the columns
            in the result (any names not found in the data will become all-NA
            columns).
_I will be testing changes to sql.read_query to confirm that frame.from_records will return the resulting dataframe when columns is None_

Therefore, I would think the below outcomes are acceptable, in order of preference.
1. Issue underlying empty cursor.description is resolved.
2. The dataframe is returned without column names
3. The true error underlying the empty cursor.description is raised to the user.

Please let me know what additional information might be helpful and thank you!

**Comment by keitherskine** [comment]
Thank you for the trace file @abekfennessy , that is always appreciated, but are you sure that is the entire trace?  The trace ends just as the SQL query is executed (the SQL that starts with "WITH NewEncounters AS").  If you have a chance, could you check there isn't any more trace output that can be retrieved?  Many thanks.

**Comment by abekfennessy** [comment]
I'm fairly certain that that trace file should cover the issue. I believe the error related to the bug above is somewhere in the middle of the trace file. Nevertheless, I will attempt to recreate the issue with trace logs and send another trace file. Thank you @keitherskine

**Comment by abekfennessy** [comment]
Hi @keitherskine I was finally able to reproduce the issue.
I've attached the odbc trace below.
I noticed this diagnosis error: "MySQL server has gone away" however it seems this follows the error from pyodbc.
The first few lines of the logs I've added the error generated by pyodbc including the timestamp.
FWIW, I also added option=4 to my connection string.

The code that I am executing is as follows:
`
import pyodbc

connect_string = f"DRIVER={{{self.driver}}};SERVER={self.server};PORT={self.port}; " \
                         f"DATABASE={self.database};UID={self.username};PWD={self.password};" \
                         f"Trusted_Connection=no"
sql_connection = pyodbc.connect(connect_string)
chunk_size=200000
pd.read_sql_query(sql_query, sql_connection, chunksize=int(chunk_size))`
The query is a relatively simple one. Five columns selected from a table with one inner join to another table. The query only produces ~500,000 records.
/home/afennessy/Documents/ODBCTrace.txt

**Comment by keitherskine** [comment]
Looking at the following exert from the ODBC trace file:
```
[ODBC][2306][1613107504.765341][SQLExecDirectW.c][177]
		Entry:
			Statement = 0x5650e55f10c0
			SQL = [/*WITH NewEncounters AS (
		SELECT en.EncounterId FROM encounterlog lg 
        INNER JOIN enc en 
            ON en.encounterI...][length = 3222]
[ODBC][2306][1613107702.996659][SQLExecDirectW.c][456]
		Exit:[SQL_SUCCESS]
[ODBC][2306][1613107702.996702][SQLRowCount.c][173]
		Entry:
			Statement = 0x5650e55f10c0
			Row Count = 0x7ffca1e35c80
[ODBC][2306][1613107702.996716][SQLRowCount.c][247]
		Exit:[SQL_SUCCESS]
			Row Count = 0x7ffca1e35c80 -> -1
[ODBC][2306][1613107702.996727][SQLNumResultCols.c][156]
		Entry:
			Statement = 0x5650e55f10c0
			Column Count = 0x7ffca1e35c78
[ODBC][2306][1613107702.996738][SQLNumResultCols.c][251]
		Exit:[SQL_SUCCESS]
			Count = 0x7ffca1e35c78 -> 0
```
You can see the "Column Count" from the query is 0 (see SQLNumResultCols).  That seems odd.  In the scenario you described, I would normally expect a column count of 5.  Zero output columns would explain the empty query description you got.

Perhaps you could try re-running the code without the chunk size (instead use LIMIT to bring back just a few rows), or you could try taking pandas and/or SQLAlchemy out of the picture and call pyodbc directly.  It would be interesting to see if either of those approaches generate a proper query description.

**Comment by abekfennessy** [comment]
I'll give both these a shot, thank you. It may be difficult to try this given the inconsistent nature of the bug though. Will let you know what if any difference this makes

**Comment by abekfennessy** [comment]
I noticed row count was "-1" as well. This is also seen in the logs you mentioned and in the error I'm getting now. 

In testing I got this error with another query where I was not specifying a chunk size so I don't think that should be related.

Out of curiosity I updated read_query with the below logic:
`if cursor.description is None:
            columns = None
            print("Columns are none!!!!!!!".center(100, '-'))
        else:
            columns = [col_desc[0] for col_desc in cursor.description]`

Which resulted in the following error:

  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 383, in read_sql_query
    chunksize=chunksize,
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 1766, in read_query
    data = self._fetchall_as_list(cursor)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/sql.py", line 1779, in _fetchall_as_list
    result = cur.fetchall()
pyodbc.ProgrammingError: No results.  Previous SQL was not a query.

I can confirm that the query being executed is in fact a sql query and as part of my debugging I am printing out the query being passed to pyodbc and can confirm the same query passed compiles successfully when executed manually. 

Could you clarify what you mean by "calling pyodbc directly"? Perhaps something like the below?
`connection = pyodbc.connect(connect_string)
cursor = connection.cursor()
cursor.execute(sql_query)
result = cursor.fetchall()
print(result)
cursor.close()`

**Comment by abekfennessy** [comment]
Apologies, the formatting seems to have gotten lost..

**Comment by abekfennessy** [comment]
Accidentally closed ^

**Comment by keitherskine** [comment]
Yes, that's the idea, although you'll probably want to get the number of records and the description from the cursor rather than the rows themselves (which I'm guessing will be rather a lot):
```python
connection = pyodbc.connect(connect_string, autocommit=True)
cursor = connection.cursor()
cursor.execute(sql_query)
rows = cursor.fetchall()
print(cursor.rowcount)
print(cursor.description)
print(len(rows))
cursor.close()
connection.close()
```

**Comment by abekfennessy** [comment]
Ran using the following code, same error as above. Specfically..
line 132, in query_sql
    rows = cursor.fetchall()
pyodbc.ProgrammingError: No results.  Previous SQL was not a query.

        connect_string = ExportDetails.get_connection_str(self)
        logging.info(f"Attempting to connect to {self.server}")
        connection = pyodbc.connect(connect_string)
        logging.info(f"Connection initiated to {self.server}")
        cursor = connection.cursor()  # Initiate sql cursor
        logging.info(f"Cursor initiated..")
        cursor.fast_executemany = False
        cursor.execute(self.sql_query)
        logging.info(f"Query executed..")
        rows = cursor.fetchall()  # The process fails here
        logging.info(f"Rows fetched..")
        print(cursor.rowcount)
        print(cursor.description)
        print(len(rows))

Logs:
2021-02-13 04:55:27,546 - INFO - Attempting to connect to 192.168.20.117
2021-02-13 04:55:27,916 - INFO - Connection initiated to 192.168.20.117
2021-02-13 04:55:27,916 - INFO - Cursor initiated..
2021-02-13 04:59:00,557 - INFO - Query executed..

ODBCTrace:
[odbcTrace.txt](https://github.com/mkleehammer/pyodbc/files/5975203/odbcTrace.txt)

**Comment by keitherskine** [comment]
If the error returned is still "No results. Previous SQL was not a query." then it looks like the SQL statement itself is the issue here.  You mentioned earlier that the SQL is just a SELECT that returns 5 columns.  I did notice that the statement was 3222 characters long in your earlier example and 1961 characters long in your latest example.  Those are fairly substantial SQL statements.  Are you sure your SQL is just a SELECT statement, or is it a SQL script that includes multiple SQL statements?

When the error states the SQL was not a query, that means the SQL was almost certainly not a SELECT statement but something else.  For example, an UPDATE statement, or a statement that is not a data query (e.g. DROP INDEX ...), or even a call to a stored procedure perhaps.  If you're OK posting the SQL, please do, otherwise please check it to make sure it is a single SELECT statement (however complex it might be).

**Comment by abekfennessy** [comment]
I’m not sure that I can share the query here but I can assure you the query
is a valid SQL Query. I’ve been working with SQL for a few years now. The
second query that I posted about is technically a few different selects
that are unioned together using UNION ALL, hence being so many characters.
The first query has the majority of those unions commented out for
debugging purposes.
The reason for the two different query character lengths is because they
are two different queries and the process fails at random. My script at
large is iterating through several different extraction processes. These
same queries execute fine using my script more than half the time and can
also execute successfully when using DBeaver.

If necessary I could post redacted versions of these queries with column
and table names replaced. Importantly, I’ve modified pyodbc.base.sql to
print the same SQL scripts and can confirm that at final stage prior to
execution the scripts are unadulterated and copied into DBeaver, also
execute fine.

It seems the issue is somehow related to a timeout or something similar in
nature. Is it possible to get more verbose logs out of the driver? Please
let me know what if anything else might be helpful in troubleshooting this.

**Comment by keitherskine** [comment]
In that case, I'm afraid I'm a bit stumped.  I can only suggest you start from the most basic SQL query and work up from there.  Try a simple SELECT query like "SELECT col1 FROM table1 LIMIT 1" using just pyodbc and see if that works.  Assuming that does work, build up from there.  These are unlikely to be the cause of your issues, but be on the lookout for a couple of things - column names that are somewhat "exotic" (e.g. contain special characters / emojis) and the use of more unusual data types, perhaps specific to MySQL.  Lastly, there's always the remote possibility your query is bringing back multiple result sets, so you may need to call [nextset()](https://github.com/mkleehammer/pyodbc/wiki/Cursor#nextset) to get the result set (and description) you're looking for.  Good luck.

**Comment by abekfennessy** [comment]
Yeah I’ve thought about trying the same.. I’ll give it a shot, thanks!

**Comment by mkleehammer** [comment]
I'm going to close this due to inactivity, but we are all interested in the results.  If you have something, please reopen or comment if you figured something out that might be useful for others.

**Comment by abekfennessy** [comment]
Thank you @mkleehammer. Unfortunately, I do not have much of an update. The issue has not appeared again since.. I am still on pyodbc 4.0.30, my query has not changed, and my MySql version has not changed. I am also stumped. The issue must have been rooted in an inappropriate network configuration perhaps? But that is complete conjecture.

**Comment by abekfenn** [comment]
Thought I would update that this issue has randomly reappeared for me now, don't have any background just yet.

**Comment by upenn-hughmac** [comment]
In case it's useful for future searchers: for us this mystery was caused by a tiny subset queries hitting our `wait_timeout` setting.
