### ISSUE TITLE
Image not found error during import

### ISSUE THREAD

**Issue by Dawny33** [mkleehammer/pyodbc#87]
The following error pops up when trying to import the library

```
>>> import pyodbc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Python/2.7/site-packages/pyodbc.so, 2): Library not loaded: /usr/local/lib/libodbc.2.dylib
  Referenced from: /Library/Python/2.7/site-packages/pyodbc.so
  Reason: image not found
```

**Comment by Yanchek99** [comment]
I am also running into this when trying to use with a MySQL odbc driver.

**Comment by SamLiu79** [comment]
you should install unixodbc on your system.
```
#brew install unixodbc                                                                                                
==> Downloading https://homebrew.bintray.com/bottles/unixodbc-2.3.2_1.el_capitan.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring unixodbc-2.3.2_1.el_capitan.bottle.1.tar.gz
🍺  /usr/local/Cellar/unixodbc/2.3.2_1: 31 files, 1020K

#ipython                                                                                                                
Python 2.7.11 (default, Dec  5 2015, 14:44:53)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pyodbc
```

**Comment by mkleehammer** [comment]
Thanks @SamLiu79

**Comment by TimothyBramlett** [comment]
@SamLiu79 From a high-level, what is unixodbc and why do we need it?  Just for my own knowledge.  :)

**Comment by v-chojas** [comment]
unixODBC is an ODBC driver manager. See http://www.unixodbc.org/ for more information.

**Comment by NavjotMannan** [comment]
Thanks. Fixed the problem.

**Comment by nate-benton90** [comment]
Thanks @SamLiu79 - worked for me with `pipenv` on `macOS Catalina v.10.15.6` - note also my Python version was `3.7.7`

**Comment by TheCaffinatedDeveloper** [comment]
Great, maybe add this as a dependency or point to it in the installation docs 👍

**Comment by v-chojas** [comment]
It has been there on the installation page for over 2 years. https://github.com/mkleehammer/pyodbc/wiki/Install

**Comment by TheCaffinatedDeveloper** [comment]
> It has been there on the installation page for over 2 years. https://github.com/mkleehammer/pyodbc/wiki/Install

It points to it only for Linux installation right? I followed the OS X installation.

**Comment by TheCaffinatedDeveloper** [comment]
> It has been there on the installation page for over 2 years. https://github.com/mkleehammer/pyodbc/wiki/Install

Ah, I didn’t realize it was on a different installation page.

https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Mac-OSX

**Comment by Ritish-Madan** [comment]
I did install the unixODBC using Homebrew. And I have the Python installed using the Graphic Installer, instead of Homebrew installation of Python. 

I don't know if it is creating the problem, but installing the unixodbc is still throwing the same error after importing pyodbc

**Comment by RefriautoLeadDeveloper** [comment]
> I did install the unixODBC using Homebrew. And I have the Python installed using the Graphic Installer, instead of Homebrew installation of Python.
> 
> I don't know if it is creating the problem, but installing the unixodbc is still throwing the same error after importing pyodbc
> 
> I did also tried using brew install python3, but Homebrew version of python do not install the other libraries like Pandas, Numpy, Pyodbc too. So I installed the Python3 graphically and got all the other libraries installed.
> 
> I have MacBook Air M1

do you still have the problem? @Ritish-Madan ? Im having the same issue
