### ISSUE TITLE
Performance Related Issues

### ISSUE THREAD

**Issue by frankkloster** [mkleehammer/pyodbc#871]
### Environment

- Python: 3.8
- pyodbc: 4.0.30 and 4.0.31b51
- OS: Ubuntu 20.04
- DB: Cloudera Impala
- driver: clouderaimpalaodbc_2.6.10.1010-2_amd64

### Issue

When querying from very large Impala databases, seems to have significantly slower performance and memory usage than what would be expected.

Using

```
db = pyodbc.connect(server)
df = pd.read_sql(query, db)
```

vs.

```
pipe = subprocess.Popen([
        "sshpass",
        "ssh",
        f"{server}",
        f"'{query}'"],
        stdout=subprocess.PIPE
    )
    
df = pd.read_csv(pipe.stdout)
```

I benchmarked the time, as well as peak memory usage for a query of 1, 2, 5, and 10 million queries. The results should be attached. In particular, pyodbc seems to have a significant level of overhead compared to just using ssh that I can't seem to figure out. Using a `fetchall()` command with an appropriate cursor still doesn't fix the issue, suggesting it isn't pandas specific.

Looking for feedback as to what may be causing the issue. Thank you in advance!

![Screen Shot 2021-02-09 at 10 18 03 AM](https://user-images.githubusercontent.com/19669330/107708910-869dc680-6c81-11eb-9362-0acca12cd0ce.png)

**Comment by v-chojas** [comment]
This is not surprising, since pyODBC needs to create a Python object for each cell retrieved, whereas a native process doesn't. The memory usage is still linear, but results in a higher constant factor.

**Comment by rlichtenwalter** [comment]
What about the contents as they exist in the data frame? Either way, at the end, it seems like the same data is ultimately being represented in Python. Is that not also one Python object per cell, or is there some guaranteed optimization in the storage based on using `np.ndarray`s or the like so that the data streams across and then does *not* occupy space as a Python object?

**Comment by rlichtenwalter** [comment]
Also gives more background; not sure if it's relevant.

https://towardsdatascience.com/optimizing-pandas-read-sql-for-postgres-f31cd7f707ab

**Comment by mkleehammer** [comment]
I've considered adding some backends to read directly into data frames, but I have to get a new clean release out until I consider that.
