### ISSUE TITLE
django 连接sqlserver 15.0.4073.23

### ISSUE THREAD

**Issue by BeLinKang** [mkleehammer/pyodbc#875]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6 64
- pyodbc: 4.0.30
- OS: win
- DB:sqlserver 15.0.4073.23
- driver: SQL Server Native Client 10.0

### Issue
django.db.utils.NotSupportedError: SQL Server v15 is not supported.
_sql_server_versions no 15 conf
Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by gordthompson** [comment]
"SQL Server Native Client 10.0" is very old. Consider upgrading to "ODBC Driver 17 for SQL Server".

**Comment by absci** [comment]
Which Django database backend are you using?

**Comment by BeLinKang** [comment]
> “ SQL Server本机客户端10.0”非常老。考虑升级到“ SQL Server ODBC驱动程序17”。

Django 2.x connection sqlServer driver change to what you said?The new Django model driver, right? Thanks

**Comment by BeLinKang** [comment]
> Which Django database backend are you using?
> I think Native Client 10.0 only support SQL Server up to 2012.
> Some older Django backend don't support SQL Server 2019, so try a different backend like [`django-mssql-backend`](https://github.com/ESSolutions/django-mssql-backend)

Thank you very much,What do you need to pay attention to with this driver?When I used it, I thought it said there was no such driver

**Comment by absci** [comment]
> > Which Django database backend are you using?
> > I think Native Client 10.0 only support SQL Server up to 2012.
> > Some older Django backend don't support SQL Server 2019, so try a different backend like [`django-mssql-backend`](https://github.com/ESSolutions/django-mssql-backend)
> 
> Thank you very much,What do you need to pay attention to with this driver?When I used it, I thought it said there was no such driver

If you want to keep using the current driver, Try install an older version of SQL Server, like 2017.
