### ISSUE TITLE
pythonsql

### ISSUE THREAD

**Issue by piyushdeshkar** [mkleehammer/pyodbc#877]
pyodbc.ProgrammingError: ('Invalid parameter type. param-index=0 param-type=builtin_function_or_method', 'HY105')

Code:-->
print("Enter a Unique Id")
Id=int(input())
print("Enter Name")
Name=str(input())
print("Enter Age")
Age=int(input())
print("Enter Address")
Address=str(input())
cursor = conn.cursor()
SQLCommand = ("INSERT INTO Students(id,Name, Age, Address) VALUES (?,?,?,?)")
Values = [id,Name, Age, Address]
#Processing Query
cursor.execute(SQLCommand,Values)
#Commiting any pending transaction to the database.
cursor.executemany(SQLCommand, Values[:5])
conn.commit()
#closing connection
print("Data Successfully Inserted")
conn.close()

**Comment by gordthompson** [comment]
You create a variable named `Id`

```
Id=int(input())
```

but then later you try and use a variable named `id`

```
Values = [id,Name, Age, Address]
```

but `Id` does not override `id` (because identifiers are case-sensitive) to you get a reference to the built-in function `id`

```
>>> type(id)
<class 'builtin_function_or_method'>
```

**Comment by v-chojas** [comment]
Gord has found the problem already, but next time please provide more details about your environment -- the issue template exists for a reason.
