### ISSUE TITLE
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver for 17 SQL Server' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by bharatvr** [mkleehammer/pyodbc#878]
I am getting this error "Can't open lib 'ODBC Driver for 17 SQL Server" in python  on Debian GNU/Linux 10 (buster.
I have installed driver as per debian 10 instruction : 

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17

Below are the step install in my docker image :

# Required for pyodbc
# >>>>>>>>>>>>>>>>>>>>>>>>>For debian 10<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

RUN apt-get update \
 && apt-get install gnupg2 -y \
 && apt-get install --reinstall build-essential -y

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update \
    && ACCEPT_EULA=Y apt-get install msodbcsql17 -y

RUN apt-get update \
    && apt-get install g++ -y \
    && apt-get install unixodbc -y \
    && apt-get install unixodbc-dev -y \
    && apt-get install --reinstall build-essential -y

COPY requirements.txt /usr/local/bin/requirements.txt 
RUN pip3 install -r /usr/local/bin/requirements.txt
RUN pip3 install pyodbc==4.0.30

**### Next** : I start docker image and verify install driver. Can someone please let me know what wrong with all steps ?

bharatsi@BHARATSI-M-JK8Y ~ % 
bharatsi@BHARATSI-M-JK8Y ~ % docker container ls                        
CONTAINER ID   IMAGE                              COMMAND                  CREATED             STATUS          PORTS                                                      NAMES
d404d2826948   buff_buff-custom-actions-service   "sh /usr/local/bin/e…"   18 minutes ago      Up 18 minutes   0.0.0.0:4000->4000/tcp, 0.0.0.0:5000->5000/tcp, 7010/tcp   buff_buff-custom-actions-service_1
e9b43c233e36   redis                              "docker-entrypoint.s…"   About an hour ago   Up 18 minutes   0.0.0.0:6379->6379/tcp                                     buff_redis_1
bharatsi@BHARATSI-M-JK8Y ~ % docker container exec -it d404d2826948 bash
uwsgi@d404d2826948:~$  odbcinst -j
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/uwsgi/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
uwsgi@d404d2826948:~$ cat /etc/odbcinst.ini
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.1.1
UsageCount=1

uwsgi@d404d2826948:~$ cat /etc/odbc.ini
uwsgi@d404d2826948:~$ cd /opt/microsoft/msodbcsql17/lib64
uwsgi@d404d2826948:/opt/microsoft/msodbcsql17/lib64$ ls'
> ^C
uwsgi@d404d2826948:/opt/microsoft/msodbcsql17/lib64$ ls
libmsodbcsql-17.7.so.1.1
uwsgi@d404d2826948:/opt/microsoft/msodbcsql17/lib64$ python3
Python 3.7.9 (default, Sep 10 2020, 17:21:15) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> import pyodbc as pyodbc
>>> 
>>> print("Hello")
Hello
>>> cnxn = pyodbc.connect('DRIVER={ODBC Driver for 17 SQL Server};SERVER=SQL-RTP-056-S,6056;DATABASE=CXRPA_GSLODB;UID=userid;PWD=password')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver for 17 SQL Server' : file not found (0) (SQLDriverConnect)")
>>> cursor = cnxn.cursor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cnxn' is not defined
>>> exit()
uwsgi@d404d2826948:/opt/microsoft/msodbcsql17/lib64$

![Screen Shot 2021-03-03 at 7 28 24 PM](https://user-images.githubusercontent.com/2372774/109891250-ba538700-7c56-11eb-922e-19727295efc2.png)

**Comment by v-chojas** [comment]
Try using `isql -v -k '<your connection string here>'` to see if that connects, which will isolate the problem to pyODBC or the driver in general.

**Comment by gordthompson** [comment]
> cnxn = pyodbc.connect('DRIVER={ODBC Driver for 17 SQL Server}

The name of the driver is

```
ODBC Driver 17 for SQL Server
```

not

```
ODBC Driver for 17 SQL Server
```

**Comment by bharatvr** [comment]
> > cnxn = pyodbc.connect('DRIVER={ODBC Driver for 17 SQL Server}
> 
> The name of the driver is
> 
> ```
> ODBC Driver 17 for SQL Server
> ```
> 
> not
> 
> ```
> ODBC Driver for 17 SQL Server
> ```

**Comment by bharatvr** [comment]
> > cnxn = pyodbc.connect('DRIVER={ODBC Driver for 17 SQL Server}
> 
> The name of the driver is
> 
> ```
> ODBC Driver 17 for SQL Server
> ```
> 
> not
> 
> ```
> ODBC Driver for 17 SQL Server
> ```

Thanks for your quick response. I tried this way but still same issue.

**Comment by bharatvr** [comment]
I am able to find the solution after add driver path in connection string as below.

cnxn = pyodbc.connect('DRIVER={/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.1.1}; SERVER=server;DATABASE=database;UID=test;PWD=password')

**Comment by v-chojas** [comment]
Note that if you do that, and change version of driver, you will need to change it in the connection string too.
Your odbcinst.ini should contain the correct entry for the driver.

**Comment by Exlsunshine** [comment]
Still meeting the same error, should someone take a look?

**Comment by Exlsunshine** [comment]
> Try using `isql -v -k '<your connection string here>'` to see if that connects, which will isolate the problem to pyODBC or the driver in general.

```
(ipt_daemon) ➜  test isql -v -k 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=xxx-xxx.database.windows.net,1433;DATABASE=xxx;UID=xxx;PWD=xxx'
[01000][unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found
[ISQL]ERROR: Could not SQLDriverConnect
```
