### ISSUE TITLE
Difference between 2.19 and 3.0.10

### ISSUE THREAD

**Issue by rudyvogt** [mkleehammer/pyodbc#88]
Hi,

I've notice that the latest version is 2.19, but there is also a 3.10.10 version.

Rudy

**Comment by keitherskine** [comment]
I don't know why, but https://pypi.python.org/pypi/pyodbc/ goes to version 2.1.9 of pyodbc, but you're right, the latest version is 3.10 available at https://pypi.python.org/pypi/pyodbc/3.0.10

**Comment by mkleehammer** [comment]
I'm not seeing an issue here, so I'm going to close this.  Please re-open if I missed something.

**Comment by keitherskine** [comment]
It's somewhat cosmetic, but if you navigate to https://pypi.python.org/pypi/pyodbc/3.0.10, near the top of the webpage it says "Latest Version: 2.1.9", which is presumably not correct.  Not sure how to fix that though.

**Comment by mkleehammer** [comment]
Thanks - something is very wrong at pypi -- all of the releases except 2.1.9 were marked as hidden.  Fixed.
