### ISSUE TITLE
Invalid parameter type  param-index=18 param-type=method

### ISSUE THREAD

**Issue by dielleluis** [mkleehammer/pyodbc#888]
### Environment

- Python: 3.9.2
- pyodbc: 4.0.30
- OS: Windows 10 20H2 
- DB: SQL Server 2019
- driver: ODBC Driver 17 for SQL Server

### Create Table

```
CREATE TABLE covid_sp(
	nome_munic VARCHAR(100),
	cod_ibge VARCHAR(20),
	dia VARCHAR(2),
	mes VARCHAR(2),
	datahora VARCHAR(10),
	casos VARCHAR(10),
	casos_novos VARCHAR(10),
	casos_pc VARCHAR(15),
	casos_mm7d	VARCHAR(15),
	obitos VARCHAR(10),
	obitos_novos VARCHAR(10),
	obitos_pc VARCHAR(15),
	obitos_mm7d VARCHAR(15),
	letalidade VARCHAR(20),
	nome_ra VARCHAR(50),
	cod_ra VARCHAR(3),
	nome_drs VARCHAR(100),
	cod_drs VARCHAR(100),
	pop VARCHAR(10),
	pop_60 VARCHAR(10),
	area VARCHAR(10),
	map_leg VARCHAR(8),
	map_leg_s VARCHAR(5),
	latitude VARCHAR(10),
	longitude VARCHAR(10),
	semana_epidem VARCHAR(5)

)
```
I'm creating all fields as VARCHAR just for test purposes.

I run the Python script below and I get the following error:

> Invalid parameter type.  param-index=18 param-type=method, HY105

This error is returned after this script:

```
import pandas as pd
import pyodbc

data = pd.read_csv (r'C:\Users\Pichau\minorityreport\Data\dados_covid_sp.csv', sep = ',') 

cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE=minority_report;UID='+username+';PWD='+ password)
cursor = cnxn.cursor()



for index, row in df.iterrows():
    cursor.execute("INSERT INTO dbo.covid_sp (nome_munic, cod_ibge, dia, mes, datahora, casos, casos_novos, casos_pc, casos_mm7d, obitos, obitos_novos, obitos_pc, obitos_mm7d, letalidade, nome_ra, cod_ra, nome_drs, cod_drs, pop, pop_60, area, map_leg, map_leg_s, latitude, longitude, semana_epidem) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", row.nome_munic, row.cod_ibge, row.dia, row.mes, row.datahora, row.casos, row.casos_novos, row.casos_pc, row.casos_mm7d, row.obitos, row.obitos_novos, row.obitos_pc, row.obitos_mm7d, row.letalidade, row.nome_ra, row.cod_ra, row.nome_drs, row.cod_drs, row.pop, row.pop_60, row.area, row.map_leg, row.map_leg_s, row.latitude, row.longitude, row.semana_epidem)
cnxn.commit()
cursor.close()
```

I expected the script to insert all data into the table but I got this error.

**Comment by v-chojas** [comment]
Please provide an ODBC trace...

**Comment by v-chojas** [comment]
...and check the type of parameter 18, are you really giving pyODBC a method instead of a data value?

**Comment by dielleluis** [comment]
![image](https://user-images.githubusercontent.com/60760696/112394487-8dd1de80-8cdb-11eb-9611-c21448267fb6.png)

Here is the type of all data types on my csv file.

**Comment by dielleluis** [comment]
> ...and check the type of parameter 18, are you really giving pyODBC a method instead of a data value?

![image](https://user-images.githubusercontent.com/60760696/112394573-bce85000-8cdb-11eb-9ceb-f93af79d159d.png)

Here is all data types on my csv file.

**Comment by dielleluis** [comment]
I found out what was happening. 

One of the columns from my df was named `pop` and on the INSERT statement when i used `row.pop` the notebook intepreted as a pop() function.

Thanks for help @v-chojas
