### ISSUE TITLE
OS X iODBC  queries raise syntax error in python 3.5.0

### ISSUE THREAD

**Issue by johnchristopherjones** [mkleehammer/pyodbc#89]
This might be related to #57 and #73.

When using python 3.5.0, `execute()` always raises a pyodbc error complaining about a syntax error.  With the FileMaker driver, this is `pyodbc.ProgrammingError`, but with the SQLite driver this is `pyodbc.Error`.  I first encountered this problem with the FileMaker iODBC driver.  To make sure it wasn't (just) the driver, I've also tested against "Actual Open Source Databases" iODBC drivers for SQLite.  I encounter a similar syntax error problem in both cases.

I'm using pyodbc 3.0.10.  I have virtual environments set up for python 2.7.5 (stock OS X 10.9) and python 3.5.0 (homebrew).  I only encounter this problem with python 3.5.0.

I believe `pyodbc` is built against iODBC 3.52.10 in both cases, but I'm not sure how to verify that.  I created a homebrew receipt to install iodbc.

:+1: Python 2.7.5, "FileMaker" driver:

``` python
>>> import pydobc
>>> cnxn = pyodbc.connect('DSN=MyDatabase;UID=username;PWD=password;")
>>> cnxn.cursor().execute('select * from FileMaker_Tables').fetchone()
('TableOccurence', 1065210.0, 'BaseTable', 'MyDatabase', 12.0)
```

:-1: Python 3.5.0, "FileMaker" driver:

``` python
>>> import pyodbc
>>> cnxn = pyodbc.connect("DSN=MyDatabase;UID=username;PWD=password;")
>>> The following statement always works in FileMaker, regardless of schema.
... cnxn.cursor().execute('''select * from FileMaker_Tables''')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42000', '[42000] [FileMaker][FileMaker] FQL0001/(1:1): There is an error in the syntax of the query. (8310) (SQLExecDirectW)')

>>> # A more typical query
>>> cnxn.cursor().execute('''select "id" from "test_table" ''')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42000', '[42000] [FileMaker][FileMaker] FQL0001/(1:1): There is an error in the syntax of the query. (8310) (SQLExecDirectW)')
```

:+1: Python 2.7.5, "Actual Open Source Databases" driver:

```
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> cnxn = pyodbc.connect('DSN=MyDatabase;UID=username;PWD=password')
>>> cnxn.cursor().execute('select * from action').fetchone()
(1, 71427167, '66486446233213756711660861965240535626013997849', datetime.date(2014, 1, 10), 1)
```

:-1: Python 3.5.0, "Actual Open Source Databases" driver:

```
Python 3.5.0 (default, Sep 23 2015, 04:41:33) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> cnxn = pyodbc.connect('DSN=MyDatabase;UID=username;pwd=password')
>>> cnxn.cursor().execute('select * from action').fetchone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY000', '[HY000] [Actual][SQLite] near "s": syntax error (0) (SQLExecDirectW)')
```

My guess is that this is an encoding problem, that the iODBC driver manager is expecting some 8-bit encoding and it's receiving something like UTF-16.

My goal here is to access FileMaker, which is why I'm using the iODBC driver manager.  My understanding is that I cannot use the FileMaker driver with unixODBC, so I'm stuck with iODBC.

**Comment by johnchristopherjones** [comment]
By using `pypyodbc`, I was able to observe that something in the ODBC API is returning 4n+2 bytes at times when 4-byte character strings are expected. (In `pypyodbc` this causes a utf-32-le decode exception to be raised.)  The additional two bytes appear at the end of the string and were `\x00\x00` in the cases I observed.  I'm not familiar with the ODBC C-API, but the specific examples appeared to be part of the return statement; some sort of error code: `HY000`.

**Comment by mkleehammer** [comment]
I'm pretty sure this an iODBC / unixODBC difference.

Since Apple backed out of shipping and supporting iODBC for OS X, pyodbc for OS X switched to unixODBC as of 3.0.8 (aa178bf).  This is the most likely problem.

You *can* recompile pyodbc for iODBC.  In generally I really recommend against it because it's nice to have a single standard, but in your case you might want to try it.  You can see from the commit above that it is as simple as changing "odbc" in the setup.py file to "iodbc".

I'm certain it isn't a generic 3.5 issue since I'm using it on OS X with PostgreSQL.  I am setting up some Windows tests and will make changes if I see problems.

I'm going to update the title to include iODBC for those browsing the list.  Let me know if you think it is more than this.

**Comment by johnchristopherjones** [comment]
What setup have you used to configure unixODBC with PostgreSQL on OS X?  I'd like to try to reproduce a working setup.

**Comment by mkleehammer** [comment]
Closing due to lack of response.  Please reopen if you still have an issue.

**Comment by raphaelvannson** [comment]
Same issue attempting to connect to an Aster database from Mac OS X on python3.4.

Any help is appreciated! :)

## Environment

```
$ uname -a
Darwin MUSRV186016-382 14.5.0 Darwin Kernel Version 14.5.0: Tue Apr 11 16:12:42 PDT 2017; root:xnu-2782.50.9.2.3~1/RELEASE_X86_64 x86_64

$ isql --version
unixODBC 2.3.4

$ python3 --version
Python 3.4.4
```

## Symptoms

```python
import os
import pyodbc

conn = pyodbc.connect('dsn=mydb')
cursor = conn.cursor()

# This should list all the tables in the database
cursor.execute('select tablename, schemaname from NC_SYSTEM.nc_all_tables t, NC_SYSTEM.nc_all_schemas s where t.schemaid=s.schemaid')

---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
<ipython-input-20-59d076043433> in <module>()
----> 1 cursor.execute('select tablename, schemaname from NC_SYSTEM.nc_all_tables t, NC_SYSTEM.nc_all_schemas s where t.schemaid=s.schemaid')

ProgrammingError: ('42000', '[42000] [AsterData][nCluster] (34) ERROR: syntax error at or near "���������������������������������������������������������d".  (34) (SQLExecDirectW)')
```

**Comment by melMass** [comment]
Thanks @raphaelvannson

**Comment by macfreek** [comment]
Thanks @raphaelvannson, I had the same issue on macOS with unixODBC and Python 3.6.

@mkleehammer Is there a way to set these encodings by default? It seems that the problem is slightly more widespread, and will affect new users.

**Comment by brudolf** [comment]
Had the same issue. Thanks @raphaelvannson

**Comment by slokhorst** [comment]
I'm having the same problem, but the fix from https://github.com/mkleehammer/pyodbc/issues/89#issuecomment-314216039 causes python to crash. The connection works fine with isql.

Without fix:
```
conn = pyodbc.connect('DSN=test')
conn.cursor().execute('SELECT * FROM Orders')

pyodbc.ProgrammingError: ('42000', '[42000] [FileMaker][FileMaker] FQL0001/(1:1): There is an error in the syntax of the query. (8310) (SQLExecDirectW)')
```

With fix:
```
conn = pyodbc.connect('DSN=test')
conn.setdecoding(pyodbc.SQL_CHAR, encoding='utf-8')
conn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-8')
conn.setdecoding(pyodbc.SQL_WMETADATA, encoding='utf-32le')
conn.setencoding(encoding='utf-8')
conn.cursor().execute('SELECT * FROM Orders')

zsh: abort      python3
```

Also see the [crash log](https://github.com/mkleehammer/pyodbc/files/6938979/crash.txt). Any ideas?

**Comment by melMass** [comment]
This issue is 3years old. You should open a new one

**Comment by v-chojas** [comment]
I recommend using the unixODBC version of pyODBC.
