### ISSUE TITLE
Python 3 Runbook, Token Authentication, SQL Server

### ISSUE THREAD

**Issue by l3d2sawzf** [mkleehammer/pyodbc#890]
Hi,

I am trying to use a Python 3 Runbook in a Azure Automation Account to connect to a Azure SQL Server using Token authentication. Just to be clear, I can connect fine using SQL Authentication, and I can connect fine using Token Authentication from my laptop, but not from within the Python Runbook.

I first came across the problem "Data source name not found and no default driver specified", but this was fixed by changing {ODBC Driver 17 for SQL Server} to {SQL Server}. Then I was faced with "Windows logins are not supported in this version of SQL Server". I've added "Integrated Security=False" into the connection string to fix this. However not I'm faced with "Invalid connection string attribute.

Any idea why it's going wrong?

My code...

     #!/usr/bin/env python3
        
     import adal
     from msrestazure.azure_active_directory import AADTokenCredentials
     import pyodbc
     import struct
        
     resource = "x"
     tenant = "x"
     authorityHostUrl = "https://login.microsoftonline.com"
     clientId = "x"
     clientSecret = "x"
     authority_uri = authorityHostUrl + '/' + tenant
     resource_uri = 'https://database.windows.net/'
        
     context = adal.AuthenticationContext(authority_uri, api_version=None)
     mgmt_token = context.acquire_token_with_client_credentials(resource_uri, clientId, clientSecret)
     token = mgmt_token["accessToken"]
        
     SQL_COPT_SS_ACCESS_TOKEN = 1256 
     driver = "{ODBC Driver 17 for SQL Server}"
     server = "x.database.windows.net"
     database = "x"
     connString = "DRIVER=" + driver + ";SERVER=" + server + ";DATABASE=" + database +";Trusted_Connection=False;Encrypt=True;Integrated Security=False;"
        
     tokenb = bytes(token, "UTF-8")
     exptoken = b''
     for i in tokenb:
         exptoken += bytes({i})
         exptoken += bytes(1)
     tokenstruct = struct.pack("=i", len(exptoken)) + exptoken
        
     conn = pyodbc.connect(connString, attrs_before = {SQL_COPT_SS_ACCESS_TOKEN:tokenstruct})
        
     cursor = conn.cursor()
     cursor.execute("SELECT TOP (5) * FROM Reference")
     row = cursor.fetchone()
        
     for i in row:
         print(i)

**Comment by v-chojas** [comment]
> I first came across the problem "Data source name not found and no default driver specified", but this was fixed by changing {ODBC Driver 17 for SQL Server} to {SQL Server}.

SQL Server is the old driver, that definitely does not support token auth. The error is because you don't have ODBC Driver 17 for SQL Server installed.

**Comment by l3d2sawzf** [comment]
Is there a workaround for this?

Maybe there is a way to install ODBC Driver 17 on the Azure Machine via the Runbook?

**Comment by v-chojas** [comment]
I'm not sure what you mean by "via the Runbook" but the solution is to install the driver. You can download it from here:

https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server

**Comment by mkleehammer** [comment]
I'm closing this since the answer is to update the ODBC driver.  It's been 21 days so I assume you worked it out.  Thanks v-chojas!
