### ISSUE TITLE
pyodbc cant install by pip

### ISSUE THREAD

**Issue by kdyhkdy** [mkleehammer/pyodbc#891]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7
- pyodbc: 4.0.30
- OS: ubuntu 16.04.7 lts
- DB: tibero6
- driver:

### Issue
I get that error

/home/qara/.local/lib/python3.7/site-packages/setuptools/dist.py:644
I got rid of the error by manipulating it directly in the above path.
Can I delete the error by manipulating it like this?

And I don't know what to do with the second error.
 src/pyodbc.h:151:21: error: ‘BYTE’ was not declared in this scope
     bool pyodbc_realloc(BYTE** pp, size_t newlen);
I don't know how to fix this error.

If you know how to fix it, be sure to! Give me an answer.

I am in an emergency.

Ubuntu is connected with Python 3.5.
I am trying to install pyodbc on 3.7 by installing python 3.7.

Is there a way to install it directly using the pyodbc source file instead of pip?
I have to install pyodbc somehow. Please help.

**Error message is here.**
Collecting pyodbc
  Downloading pyodbc-4.0.30.tar.gz (266 kB)
     |████████████████████████████████| 266 kB 1.7 MB/s
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-rseogbtr
       cwd: /tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/
  Complete output (24 lines):
  /home/qara/.local/lib/python3.7/site-packages/setuptools/dist.py:644: UserWarning: Usage of dash-separated 'library-dirs' will not be supported in future versions. Please use the underscore name 'library_dirs' instead
    % (opt, underscore_opt))
  running bdist_wheel
  running build
  running build_ext
  building 'pyodbc' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYODBC_VERSION=4.0.30 -I/usr/include/python3.7m -c src/buffer.cpp -o build/temp.linux-x86_64-3.7/src/buffer.o -Wno-write-strings
  In file included from src/buffer.cpp:12:0:
  src/pyodbc.h:151:21: error: ‘BYTE’ was not declared in this scope
   bool pyodbc_realloc(BYTE** pp, size_t newlen);
                       ^
  src/pyodbc.h:151:28: error: ‘pp’ was not declared in this scope
   bool pyodbc_realloc(BYTE** pp, size_t newlen);
                              ^
  src/pyodbc.h:151:39: error: expected primary-expression before ‘newlen’
   bool pyodbc_realloc(BYTE** pp, size_t newlen);
                                         ^
  src/pyodbc.h:151:45: error: expression list treated as compound expression in initializer [-fpermissive]
   bool pyodbc_realloc(BYTE** pp, size_t newlen);
                                               ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc
    Running setup.py install for pyodbc ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ktx019f4/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/pyodbc
         cwd: /tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/
    Complete output (24 lines):
    /home/qara/.local/lib/python3.7/site-packages/setuptools/dist.py:644: UserWarning: Usage of dash-separated 'library-dirs' will not be supported in future versions. Please use the underscore name 'library_dirs' instead
      % (opt, underscore_opt))
    running install
    running build
    running build_ext
    building 'pyodbc' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYODBC_VERSION=4.0.30 -I/usr/include/python3.7m -c src/buffer.cpp -o build/temp.linux-x86_64-3.7/src/buffer.o -Wno-write-strings
    In file included from src/buffer.cpp:12:0:
    src/pyodbc.h:151:21: error: ‘BYTE’ was not declared in this scope
     bool pyodbc_realloc(BYTE** pp, size_t newlen);
                         ^
    src/pyodbc.h:151:28: error: ‘pp’ was not declared in this scope
     bool pyodbc_realloc(BYTE** pp, size_t newlen);
                                ^
    src/pyodbc.h:151:39: error: expected primary-expression before ‘newlen’
     bool pyodbc_realloc(BYTE** pp, size_t newlen);
                                           ^
    src/pyodbc.h:151:45: error: expression list treated as compound expression in initializer [-fpermissive]
     bool pyodbc_realloc(BYTE** pp, size_t newlen);
                                                 ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eib3zui3/pyodbc_c942e95e4e6e4a95879297f3ce5628f3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ktx019f4/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/pyodbc Check the logs for full command output.

**Comment by v-chojas** [comment]
What version of unixODBC did you install? Did you install unixODBC at all? It looks like you may be trying to use iODBC, which currently doesn't work with pyODBC:

https://github.com/mkleehammer/pyodbc/issues/880

**Comment by gordthompson** [comment]
@v-chojas - The documentation for [tibero ODBC](https://technet.tmaxsoft.com/upload/download/online/tibero/pver-20150504-000002/tibero_cli/ch05.html) mentions both unixODBC and iODBC but only gives instructions for using the driver with iODBC on Linux.

**Comment by kdyhkdy** [comment]
> What version of unixODBC did you install? Did you install unixODBC at all? It looks like you may be trying to use iODBC, which currently doesn't work with pyODBC:
> 
> #880

My unixodbc version is 2.3.1-4.1.
Should I install pyodbc using iodbc?

**Comment by gordthompson** [comment]
> Should I install pyodbc using iodbc?

Certainly from the pyodbc side it would be easier to work with unixODBC on Linux (since that has been by far the most common usage case), but the aforementioned tibero ODBC documentation strikes me as rather cryptic. It mentions unixODBC as an option but then talks exclusively about iODBC. 

It's not at all clear to me how the driver is distributed. If they offer binary distributions like .deb or .rpm that are linked to a particular DM (unixODBC or iODBC) and you can get a unixODBC build then that would probably be the path of least resistance. However, we can't really help you with that; it's something you'll need to discuss with tibero tech support.

**Comment by kdyhkdy** [comment]
> > Should I install pyodbc using iodbc?
> 
> Certainly from the pyodbc side it would be easier to work with unixODBC on Linux (since that has been by far the most common usage case), but the aforementioned tibero ODBC documentation strikes me as rather cryptic. It mentions unixODBC as an option but then talks exclusively about iODBC.
> 
> It's not at all clear to me how the driver is distributed. If they offer binary distributions like .deb or .rpm that are linked to a particular DM (unixODBC or iODBC) and you can get a unixODBC build then that would probably be the path of least resistance. However, we can't really help you with that; it's something you'll need to discuss with tibero tech support.

Your answer was helpful. I knew a long time ago that the tibero documentation also mentioned iODBC. But I forgot.
Thanks, I can finally run the web server.
