### ISSUE TITLE
Is PyODBC accessing Azure SQL Server securely?

### ISSUE THREAD

**Issue by stevesmit** [mkleehammer/pyodbc#893]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.5
- pyodbc: 4.0.30
- OS: Windows or Linux
- DB: Azure SQL Server
- driver: ODBC?

### Issue

Really more of a question - I am connecting to an Azure SQL Server using SQLAlchemy's `create_engine` function. 

```
import sqlalchemy as sa

params = <the parameters to connect to the DB such as the server and password, as a string>
engine = sa.create_engine("mssql+pyodbc:///?odbc_connect={}".format(params))
```

The questions are 
- whether PyODBC, which is being used to make this connection, is accessing the database securely by default
- whether the connection details (like user, password) are being passed in plaintext (or are they encrypted) and finally,
- what protocol is being used for this connection

The SQLAlchemy side have pointed me in your direction as they simply pass the connection details through to PyODBC.

**Comment by v-chojas** [comment]
Azure SQL has connection encryption on by default, and uses TLS.

**Comment by stevesmit** [comment]
@v-chojas thanks! And perhaps this is a silly question, but does that necessarily mean that whatever _connects_ to it is doing so securely? Are you saying it forces any connection to be secure?

**Comment by v-chojas** [comment]
Encryption is required to connect to Azure SQL.
See here for more information: https://docs.microsoft.com/en-us/azure/azure-sql/database/connect-query-content-reference-guide#tls-considerations-for-database-connectivity
