### ISSUE TITLE
pyodbc.connect() super slow on one VM

### ISSUE THREAD

**Issue by vabene1111** [mkleehammer/pyodbc#894]
### Environment
- Python: `3.8.5`
- pyodbc: `4.0.30`
- OS: `ubuntu 20.04.02` with 
- DB: SQL Anywhere 12
- driver: [SQL Anywhere 12 Linux driver](https://wiki.scn.sap.com/wiki/display/SQLANY/SAP+SQL+Anywhere+Database+Client+Download)

The driver was installed using the setup for the sqlanywhere driver and is located in the `/etc/odbcinst.ini`
```
[SQL Anywhere 12]
Description=SQL Anywhere ODBC Driver v 12
Driver=/opt/sqlanywhere12/lib64/libdbodbc12_r.so
Setup=/opt/sqlanywhere12/lib64/libdbodbc16_r.so
```

### Issue

I have a database running on a windows VM on a server that is located on a Hypervisor.

Then i have a linux VM (with the environment described above).
When making a connection with `pyodbc.connect('driver=SQL Anywhere 12;UID=USER;PWD=PASSWORD;Host=HOST:PORT;DatabaseName=DB_NAME;ServerName=DB_SERVER_NAME;')` it takes about 12 seconds. 

**The interesting thing is:**
I have installed the driver on an arch linux laptop connected via wifi, on my windows desktop and on two additional VMs (one running on the hypervisor the database is on and one running on another hypervisor (where the slow VM is on)).

All of those connections only take a few milliseconds, even over wifi. 

I suspect that this issue is not related to pyodbc but odbc in general but i have no idea on where else to get help on this. 
I have already tried
- re-installing the driver
- updating the VM
- verified that Tracing is disabled (i could not find it enabled in any config and also tested disabling it by adding Trace=no) but nothing changed
- restarted the server

Feel free to close if you dont have any ideas and dont want this here, if not thanks for the help. Also thanks for making pyodbc in the first place, its awesome.

**Comment by v-chojas** [comment]
I do not think pyODBC is causing this either, but could you try using isql from the Linux machine to connect?
`isql -v -k <your connection string here>`
If that is not slow then it could be pyODBC related, but if it is also slow, then It is not.

I suggest to do some packet tracing, compare the fast and slow case. It could be something like DNS lookup timing out.

**Comment by vabene1111** [comment]
I have tested using isql with an identical connection string and it is slow as well.
There is no DNS lookup required as i enter the IP addresses directly.

I would love to do some further tracing but i have no idea on how to do this ? I tried using -v for isql to get more verbose output but it did not show anything. pinging and tracrouting the DB server yields perfectly fine results from all test instances so its not a general connection issue.

Do you know of or could point me to any solution that would allow me to further debug the odbc connection ?

Thank you very much in advance, i am now pretty sure that this is your issue so please dont feel obligated to help.

**Comment by gordthompson** [comment]
Like @v-chojas suggests, you could try using a tool like Wireshark to see if the low-level communication between the client and server are significantly different in the slow vs. fast cases.

**Comment by vabene1111** [comment]
thank you, i will try that out tomorrow

**Comment by vabene1111** [comment]
Ok so i have run wireshark on both VMs. Interestingly all packages sent during connection establish are almost identical in timing. 
Both send 18 packages before the connection is established but on one VM the command simply hangs for about 10 seconds before actually showing the connection. 

I guess this means it is not a networking issue but some kind of driver issue. The slow VM was installed about a year ago so i dont really know if i did anything differently during installation but i reinstalled the drivers yesterday with the exact same settings and it did not change anything. 

So i guess this is definitely not a pyodbc issue. If you have any ideas on what could cause this any help would be appreciated but if you have no idea feel free to just close this issue.

**Comment by vabene1111** [comment]
Ok so just as an update if anyone stumbles across this in the future. Running `strace` on the isql command revealed that isql apparently tries trough all network adapters. 

This is super slow on one VM because it hosts quite a few docker containers which all have network adapters. I am currently trying to find out if i can specify the adapter used by isql and if this is really the issue.

**Comment by v-chojas** [comment]
Good to hear that the cause has been determined. Choosing which interface to use is usually the job of the OS TCP/IP stack, not the application. If you would like to research that more, the search keywords to use are "multihomed host".
