### ISSUE TITLE
Login failed due to client TLS version being less than minimal TLS version allowed by the server. 

### ISSUE THREAD

**Issue by iambernics** [mkleehammer/pyodbc#895]
Dear Community,

Pyodbc connection with "SQL Server" driver is failing due to the TLS version mismatch. 
TLS 1.2 or higher is only available on the target Azure SQL Server.

How can we enforce the proper TLS version on the client side?

Regards,
Gabor

`2021-04-21T13:47:22.9033854Z pyodbc.Error: ('HY000', '[HY000] [Microsoft][ODBC SQL Server Driver][SQL Server]Reason: Login failed due to client TLS version being less than minimal TLS version allowed by the server. (47072) (SQLDriverConnect); [HY000] [Microsoft][ODBC SQL Server Driver]Invalid connection string attribute (0); [HY000] [Microsoft][ODBC SQL Server Driver][SQL Server]Reason: Login failed due to client TLS version being less than minimal TLS version allowed by the server. (47072); [HY000] [Microsoft][ODBC SQL Server Driver]Invalid connection string attribute (0)')`

**Comment by v-chojas** [comment]
This has nothing to do with pyODBC.
"SQL Server" driver is very old and does not support TLS 1.2.
Use Microsoft "ODBC Driver for SQL Server" instead: https://docs.microsoft.com/en-us/sql/connect/odbc/microsoft-odbc-driver-for-sql-server
