### ISSUE TITLE
Python memory allocator called without holding the GIL

### ISSUE THREAD

**Issue by biomerge** [mkleehammer/pyodbc#898]
### Environment

- Python: CPython 3.8.5 (embedded)
- pyodbc: 4.0.30
- OS: Windows 10 (64-bit python)
- DB: NA
- driver: NA

### Issue

Error in debug mode when importing the pyodbc module:
Fatal Python error: Python memory allocator called without holding the GIL

textenc.c has a static variable which calls a Python/C API function that requires the GIL:

static PyObject* nulls = PyBytes_FromStringAndSize("\0\0\0\0", 4);

However the module is loaded from a block of code that first releases the GIL (dynload_win.c):

        Py_BEGIN_ALLOW_THREADS
        hDLL = LoadLibraryExW(wpathname, NULL,
                              LOAD_LIBRARY_SEARCH_DEFAULT_DIRS |
                              LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR);
        Py_END_ALLOW_THREADS

**Comment by v-chojas** [comment]
Calling Python APIs from what is effectively the DllMain doesn't seem like a good idea in general... moving the static into the function and initialising it on first use can avoid this.

**Comment by v-makouz** [comment]
Moved the static variable into the function from the global scope:
https://github.com/mkleehammer/pyodbc/pull/899

**Comment by mkleehammer** [comment]
v-makouz has a fix in progress, but it needs rebasing.  Thanks @v-makouz

**Comment by v-makouz** [comment]
PR https://github.com/mkleehammer/pyodbc/pull/903 should be the clean one, shows no conflicts and only the relevant changes.
