### ISSUE TITLE
Error Database does not exist.

### ISSUE THREAD

**Issue by Diyago** [mkleehammer/pyodbc#90]
I'm using `pyodbc` library from [here][1] and I'm connecting this way:

    conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};Server=(localdb)\MSSQLLocalDB;Integrated Security=true; database = online_banking; autocommit = True')

I use `MSSQLLocalDB`because it's the default instance name for SQL Server 2014. And this last version of Python 2.7.

However I cant run any simple query, every if them raise the error, saying that there is no such object or in that particular case database:

    cursor.execute('use online_banking;')

The full error:

    pyodbc.Error: ('08004', "[08004] [Microsoft][SQL Server Native Client 11.0][SQL Server]Database 'online_banking' does not exist. Make sure that the name is entered correctly. (911) (SQLExecDirectW)")

So what is wrong here?

**upd1** Database've been created this way:

    CREATE DATABASE [online_banking]
     ON  PRIMARY 
    ( NAME = N'online_banking', FILENAME = N'C:\...\online_banking.mdf' , 
      SIZE = 512000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30%)
     LOG ON 
    ( NAME = N'online_banking_log', FILENAME = N'C:\...\online_banking_log.ldf' , 
      SIZE = 1024KB , MAXSIZE = 20GB , FILEGROWTH = 10%)
    GO
**upd2** I've used built-in tool `sqlcmd`. 
So this `sqlcmd  -S (LocalDB)\MSSQLLocalDB -i C:\Users\1.sql -E` have shown, that 
`MSSQLLocalDB` doesn't have my database.

However `sqlcmd  -S localhost -i C:\Users\1.sql -E` performed successfully.
I'm totally confused, I' ve installed only one server, moreover SQL Management studio sees only one local server with my `online_banking` DB. This is look really weird to me.

Trying to use this connection string in Python 

    conn = pyodbc.connect(r'DRIVER={SQL Server Native Client 11.0};Server=localhost;Integrated Security=true; database = online_banking; autocommit = True')

causes the error below:

 

    pyodbc.Error: ('28000', '[28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]\xce\xf8\xe8\xe1\xea\xe0 \xe2\xf5\xee\xe4\xe0 \xef\xee\xeb\xfc\xe7\xee\xe2\xe0\xf2\xe5\xeb\xff "". (18456) (SQLDriverConnect); [01S00] [Microsoft][SQL Server Native Client 11.0]\xcd\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xfb\xe9 \xe0\xf2\xf0\xe8\xe1\xf3\xf2 \xf1\xf2\xf0\xee\xea\xe8 \xef\xee\xe4\xea\xeb\xfe\xf7\xe5\xed\xe8\xff (0); [28000] [Microsoft][SQL Server Native Client 11.0][SQL Server]\xce\xf8\xe8\xe1\xea\xe0 \xe2\xf5\xee\xe4\xe0 \xef\xee\xeb\xfc\xe7\xee\xe2\xe0\xf2\xe5\xeb\xff "". (18456); [01S00] [Microsoft][SQL Server Native Client 11.0]\xcd\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xfb\xe9 \xe0\xf2\xf0\xe8\xe1\xf3\xf2 \xf1\xf2\xf0\xee\xea\xe8 \xef\xee\xe4\xea\xeb\xfe\xf7\xe5\xed\xe8\xff (0)'

 

  [1]: https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Windows

**Comment by mkleehammer** [comment]
There are a lot of confusing things in this report, so we'll have to look at them separately.

The first, however, is that you don't need the "use" command.  You put the database into your connecting string, so you are already connected to that database.

Add a table to the database using SQL MS:
```sql
create table test1(a int, b varchar(20))
insert into test1 values (1, 'one'), (2, 'two');
select * from test1
```

Now, using the original connection string which seemed to connect successfully, try:
```python
cnxn = pyodbc.connect(...)
cursor = cnxn.cursor()
cursor.execute("select * from test1")
rows = cursor.fetchall()
print(rows)
```

How far do we get?

**Comment by Diyago** [comment]
I successfully created test1 table. Using my connection string returned such error:

```python 
pyodbc.ProgrammingError: ('42S02', "[42S02] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid object name 'test1'. (208) (SQLExecDirectW)")


Which leads to conclusion, that I have connection to smth different.

**Comment by Diyago** [comment]
This is how can be connected

``` python
import pyodbc
instance_name = r"(local)"
db_name = "online_banking"
conn_str = (
    "Driver={SQL Server Native Client 11.0};" +
    "Server={0};".format(instance_name) +
    "Database={0};".format(db_name) +
    "Trusted_Connection=yes;"
    )
conn = pyodbc.connect(conn_str)
print("Connected to {0} database on {1}.".format(db_name, instance_name))
conn.close()
import pyodbc
instance_name = r"(local)"
db_name = "online_banking"
conn_str = (
    "Driver={SQL Server Native Client 11.0};" +
    "Server={0};".format(instance_name) +
    "Database={0};".format(db_name) +
    "Trusted_Connection=yes;"
    )
conn = pyodbc.connect(conn_str)
print("Connected to {0} database on {1}.".format(db_name, instance_name))
conn.close()
```
