### ISSUE TITLE
Was not possible to execute an SQL statement without starting a transaction

### ISSUE THREAD

**Issue by VolodymyrGavrysh** [mkleehammer/pyodbc#900]
### Environment
- Python: 3.7 
-  databricks 7.6 (includes Apache Spark 3.0.1, Scala 2.12)
- pyodbc ->> databricks/python/lib/python3.7/site-packages/pyodbc.cpython-37m-x86_64-linux-gnu.so (packedge) 

### Issue

not possible to execute an sql statement without starting a transaction.
![Screenshot from 2021-05-20 16-10-04](https://user-images.githubusercontent.com/41486637/118984300-08d70e80-b986-11eb-9df5-94fa275fc9e7.png)

**Comment by v-chojas** [comment]
Then don't start one: Turn on autocommit (it defaults off in connection string.)

**Comment by VolodymyrGavrysh** [comment]
Thank you! Yes, I did it.
With and without doesn't work.(

**Comment by v-makouz** [comment]
@VolodymyrGavrysh So does it work OK now, with auto-commit on?

**Comment by VolodymyrGavrysh** [comment]
Unfortunately no, that is why I am writing here )

**Comment by VolodymyrGavrysh** [comment]
How can get it out in data bricks environment?

**Comment by VolodymyrGavrysh** [comment]
Actually tried to set it True in the beginning of query, and working!
Thank you for help! @v-chojas !
