### ISSUE TITLE
IBM i - Installing pyodbc fails with error library libstdc++ not found

### ISSUE THREAD

**Issue by brittomoses** [mkleehammer/pyodbc#902]
/QOpenSys/pkgs/lib/python3.6/config-3.6m/ld_so_aix g++ -pthread -pthread -bI:/QOpenSys/pkgs/lib/python3.6/config-3.6m/python.
exp -Wl,-blibpath:/QOpenSys/pkgs/lib:/QOpenSys/usr/lib build/temp.os400-powerpc64-3.6/src/buffer.o build/temp.os400-powerpc64-3.6
/src/cnxninfo.o build/temp.os400-powerpc64-3.6/src/connection.o build/temp.os400-powerpc64-3.6/src/cursor.o build/temp.os400-powe
rpc64-3.6/src/errors.o build/temp.os400-powerpc64-3.6/src/getdata.o build/temp.os400-powerpc64-3.6/src/params.o build/temp.os400-
powerpc64-3.6/src/pyodbccompat.o build/temp.os400-powerpc64-3.6/src/pyodbcdbg.o build/temp.os400-powerpc64-3.6/src/pyodbcmodule.o
 build/temp.os400-powerpc64-3.6/src/row.o build/temp.os400-powerpc64-3.6/src/textenc.o -L/usr/lib -L/usr/local/lib -L/QOpenSys/pk
gs/lib -lodbc -o build/lib.os400-powerpc64-3.6/pyodbc.so -L/QOpenSys/pkgs/lib -lodbc                                             
    collect2: fatal error: library libstdc++ not found                                                                           
    compilation terminated.                                                                                                      
    error: command '/QOpenSys/pkgs/lib/python3.6/config-3.6m/ld_so_aix' failed with exit status 1                                
                                                                                                                                 
    ----------------------------------------                                                                                     
 [31mCommand "/QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5n9safa2/pyodbc/setup.py';f=
getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" in
stall --record /tmp/pip-daaeyrgf-record/install-record.txt --single-version-externally-managed --compile" failed with error code 
1 in /tmp/pip-build-5n9safa2/pyodbc/ [0m                                                                                         
 [?25h$

**Comment by gordthompson** [comment]
On my Ubuntu Linux box "libstdc++" is installed as part of the GNU C++ compiler (`apt install g++`). Have you installed the GNU C++ compiler on your machine?

**Comment by brittomoses** [comment]
I'm running on IBM i and I have GCC installed, also I do see the libstdc++.so.6 in /qopensys/pkgs/lib. Previously I had the pyodbc installed and when I uninstall and re-install it, getting this error

**Comment by v-chojas** [comment]
Is the compiler looking for the library in the right place?

**Comment by brittomoses** [comment]
Got it resolved, Installing libstdcplusplus-devel.ppc64 fixed this
