### ISSUE TITLE
"String data, right truncation" error with cursor.excutemany()

### ISSUE THREAD

**Issue by ChenHuang1998** [mkleehammer/pyodbc#905]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: Python3.8
- pyodbc: 4.0.30
- OS: mac os
- DB: 
- driver:ODBC Driver 17 for SQL Server

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

('22001', '[22001] [Microsoft][ODBC Driver 17 for SQL Server]String data, right truncation (0) (SQLParamData)')

**Comment by ChenHuang1998** [comment]
No error will be reported when using cursor. execute

**Comment by gordthompson** [comment]
That error message can have several causes. Please post a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to illustrate your particular usage case.

**Comment by ChenHuang1998** [comment]
> 


The problem has been resolved because of the wrong field type
