### ISSUE TITLE
Connection fails for passwords greater than 30 characters with MS SSQL Server 2008 R2

### ISSUE THREAD

**Issue by Thesp1** [mkleehammer/pyodbc#91]
I don't know if this is the same on other versions of SQL Server, but I have experienced this issue on pyodbc 3.0.7 and 3.0.10. When logging into MS SQL Server 2008 R2, if the password length is greater than exactly 30 characters, the login automatically fails. For example:
`cur = pyodbc.connect('Driver=FreeTDS;Server=servername;Database=mydb;UID=user_name;PWD=123456789012345678901234567890;Port=1433').cursor()`
...yields a valid connection and cursor when the password matches. However, if the user's password is a single character longer...
`cur = pyodbc.connect('Driver=FreeTDS;Server=servername;Database=mydb;UID=user_name;PWD=1234567890123456789012345678901;Port=1433').cursor()`
...yields...
`    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    pyodbc.ProgrammingError: ('42000', "[42000] [unixODBC][FreeTDS][SQL Server]Login failed for user 'user_name'. (18456) (SQLDriverConnect)")`
This has been replicated with several passwords, and any valid passwords over 30 characters always fail.

**Comment by Thesp1** [comment]
Scratch this - it's a FreeTDS issue - early versions of FreeTDS cause problems, and this is fixed by specifying a later FreeTDS version. Sorry about that.

**Comment by FlipperPA** [comment]
Yep, I believe this was FreeTDS v. 0.82 and earlier. It took me a while to figure it out when it hit me a few years back - ugh!
