### ISSUE TITLE
pyodbc.ProgrammingError: ('42000', '[42000] [FreeTDS][SQL Server]ALTER DATABASE ---(226) (SQLExecDirectW)')**

### ISSUE THREAD

**Issue by kocharR** [mkleehammer/pyodbc#910]
Hi All,
I get below error while executing some alter database script in python. same scripts run fine in sq server.
 
**pyodbc.ProgrammingError: ('42000', '[42000] [FreeTDS][SQL Server]ALTER DATABASE statement not allowed within multi-statement transaction. (226) (SQLExecDirectW)')**

   ```
 sql1 = 'SET IMPLICIT_TRANSACTIONS OFF'
    sql1 = sql1 + '\nAlter Database [AAF_TEST] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    
    conn = pyodbc.connect('DRIVER={FreeTDS};DSN=test; db_name=DBA;UID=test;PWD=test123;autocommit=True')

obj = conn.execute(sql1)
```
Any idea about how to fix this issue?

Thanks.

**Comment by gordthompson** [comment]
the `autocommit` argument is separate from the connection string. Try

```python
conn = pyodbc.connect('DRIVER={FreeTDS}; … PWD=test123;', autocommit=True)
```

**Comment by kocharR** [comment]
Thank you! That worked like a charm.
