### ISSUE TITLE
pyodbc.Error: ('HY000', '[HY000] [GBasedbt][GBasedbt ODBC Driver][GBasedbt]无 RESOURCE 权限。\x00\x00\x00\x00\x00\x00\x00\x00 (-388) (SQLExecDirectW)')

### ISSUE THREAD

**Issue by knight-ni** [mkleehammer/pyodbc#911]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  python3.9.5
- pyodbc:  4.0.30
- OS:         centos 7.8
- DB:         informix
- driver:    odbc from CSDK

### Issue

i got error message as followed, part of this decoding to chinese utf8 as expected,but other parts are not,any one could help me to fix this?

![image](https://user-images.githubusercontent.com/43974877/121144724-d7f54580-c870-11eb-9c45-8f6d1f85c19d.png)

**Comment by v-chojas** [comment]
Multiple null bytes suggest that's the end of the error message and there are some extra bytes that are being taken because the driver might be returning an incorrect length. Need to see ODBC trace to be sure.

**Comment by gordthompson** [comment]
[Troubleshooting – Generating an ODBC trace log](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log)

**Comment by knight-ni** [comment]
this is my odbc trace file
[odbctrace.zip](https://github.com/mkleehammer/pyodbc/files/6620386/odbctrace.zip)

**Comment by knight-ni** [comment]
> ### Environment
> To diagnose, we usually need to know the following, including version numbers. On Windows, be
> sure to specify 32-bit Python or 64-bit:
> 
> * Python:  python3.9.5
> * pyodbc:  4.0.30
> * OS:         centos 7.8
> * DB:         informix
> * driver:    odbc from CSDK
> 
> ### Issue
> i got error message as followed, part of this decoding to chinese utf8 as expected,but other parts are not,any one could help me to fix this?
> 
> ![image](https://user-images.githubusercontent.com/43974877/121144724-d7f54580-c870-11eb-9c45-8f6d1f85c19d.png)

my odbc trace file:
[odbctrace.zip](https://github.com/mkleehammer/pyodbc/files/6620388/odbctrace.zip)

**Comment by gordthompson** [comment]
Google Translate tells me that

![error](https://user-images.githubusercontent.com/15894006/121355981-ab334380-c8ed-11eb-8ddd-47ed9302529a.png)

means either "No RESOURCE permission." or "No RESOURCE authority." If

```
ppid=0000420f,pid=7fdf76b87740	   ENTER SQLGetDiagRecW
	,SQLSMALLINT     3
	SQLHANDLE       0x02224810
	SQLSMALLINT     1
	SQLWCHAR *       
	SQLINTEGER *    0x7FFFEB8A7268
	SQLWCHAR *       
	SQLSMALLINT     512
	SQLSMALLINT *   0x7FFFEB8A726C
```

is saying that the length of the text it is returning is 512 bytes then that would explain the extra garbage characters at the end.

**Comment by knight-ni** [comment]
Thanks All

I tried modifying errors.cpp to handle the error message in bytes by using (SQLCHAR*) rather than (SQLWCHAR*) and make PyUnicode_Decode length just cchMsg from SQLGetDiagRec, it seems work for now.

![image](https://user-images.githubusercontent.com/43974877/121459807-7eab2480-c9de-11eb-9f70-56623fb92a2c.png)
