### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#912]
It has been well over a year since 4.0.30 was released (2020-02-08) and there have been 52 PRs merged since then.

Can we please take care of a few more high-value open PRs – specifically #703, #856, #903, and #904 – and create a new release?

**Comment by mkleehammer** [comment]
I think you are correct.  Let's add any issues we want closed to the milestone I just created and attached to this issue and make a release.

**Comment by gordthompson** [comment]
Great. Curious, though: why .37 and not .31 @mkleehammer ?

**Comment by mkleehammer** [comment]
Oops.  Probably as you expected - it was a typo.  Corrected.

BTW, I was hoping to make a release with anything that causes a crash or memory corruption to eliminate security issues.  If you see anything, add those also.  I have found a crash I need to reproduce and open an issue for.

**Comment by gordthompson** [comment]
https://pypi.org/project/pyodbc/4.0.31/
