### ISSUE TITLE
Can't open lib '...' : file not found (0) (SQLDriverConnect), but file is definitely there

### ISSUE THREAD

**Issue by mobusdorphin** [mkleehammer/pyodbc#913]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: Python 3.7.4
- pyodbc: 4.0.22-1+b1
- OS: Debian Buster
- DB: Oracle 21 (though issue is DB agnostic, have also tried with a mariadb connector)
- driver: libsqora.so.21.1

### Issue
Trying to import odbc and at least test the connection, but the driver manager can't find the file, both when I use a relative path to the default odbc dir, or an absolute path.  I have confirmed the file is world readable, and the file exists.  I have tried symlinking to a file that ends in .so and with the original file that ends in .21.1. Pyodbc correctly reads the path from odbc.ini but for some reason still can't find it.  The weird thing is, I did this on a nearly-identical Debian 10 box and didn't have the issue at all, the only difference is the one that didn't work had Google Cloud Platform Dataproc running on it, but I don't see how an application can mess with something like this at the OS layer.  If you're not aware of anything that could prevent ODBC or pyodbc from being able to find that file when it clearly exists, I can hunt down with Google who is the host of the particular VM, but I wanted to try to check here first.

output dumps:
```
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyodbc
>>> conn = pyodbc.connect("DSN=OracleODBC-21;")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/usr/lib/x86_64-linux-gnu/odbc/libsqora.so' : file not found (0) (SQLDriverConnect)")
>>>
```
```
root@localhost:~# cat /etc/odbcinst.ini
[Oracle 21 ODBC driver]
Description=Oracle ODBC driver for Oracle 21
Driver=/usr/lib/x86_64-linux-gnu/odbc/libsqora.so
Setup=/usr/lib/x86_64-linux-gnu/odbc/libsqora.so
FileUsage=
CPTimeout=
CPReuse=
UsageCount=1
```

```
root@localhost:~# cat /etc/odbc.ini
[OracleODBC-21]
AggregateSQLType = FLOAT
Application Attributes = T
Attributes = W
BatchAutocommitMode = IfAllSuccessful
BindAsFLOAT = F
CacheBufferSize = 20
CloseCursor = F
DisableDPM = F
DisableMTS = T
DisableRULEHint = T
Driver = Oracle 21 ODBC driver
DSN = OracleODBC-21
EXECSchemaOpt =
EXECSyntax = T
Failover = T
FailoverDelay = 10
FailoverRetryCount = 10
FetchBufferSize = 64000
ForceWCHAR = F
LobPrefetchSize = 8192
Lobs = T
Longs = T
MaxLargeData = 0
MaxTokenSize = 8192
MetadataIdDefault = F
QueryTimeout = T
ResultSets = T
ServerName =
SQLGetData extensions = F
SQLTranslateErrors = F
StatementCache = F
Translation DLL =
Translation Option = 0
UseOCIDescribeAny = F
UserID =
```

```
root@localhost:~# ls -l /usr/lib/x86_64-linux-gnu/odbc/
total 1268
-rw-r--r-- 1 root root   10208 May  9  2018 libesoobS.so
-rw-r--r-- 1 root root    6072 May  9  2018 libmimerS.so
-rw-r--r-- 1 root root   88992 May  9  2018 libnn.so
-rw-r--r-- 1 root root    6008 May  9  2018 libodbcdrvcfg1S.so
-rw-r--r-- 1 root root    5984 May  9  2018 libodbcdrvcfg2S.so
-rw-r--r-- 1 root root    6008 May  9  2018 libodbcminiS.so
-rw-r--r-- 1 root root   10136 May  9  2018 libodbcmyS.so
-rw-r--r-- 1 root root    6008 May  9  2018 libodbcnnS.so
-rw-r--r-- 1 root root   10200 May  9  2018 libodbcpsqlS.so
-rw-r--r-- 1 root root    6048 May  9  2018 libodbctxtS.so
-rw-r--r-- 1 root root   10504 May  9  2018 liboplodbcS.so
-rw-r--r-- 1 root root    5984 May  9  2018 liboraodbcS.so
-rw-r--r-- 1 root root    6112 May  9  2018 libsapdbS.so
lrwxrwxrwx 1 root root      47 Jun 14 21:35 libsqora.so -> /usr/lib/x86_64-linux-gnu/odbc/libsqora.so.21.1
-rwxr-xr-x 1 root root 1082576 Jun 14 21:21 libsqora.so.21.1
-rw-r--r-- 1 root root    5984 May  9  2018 libtdsS.so
```

**Comment by mobusdorphin** [comment]
Ran with isql, getting same error, looks like this is an issue with odbc, not pyodbc, thank you!

**Comment by v-chojas** [comment]
"file not found" doesn't apply only to the driver lib, but its dependencies too. Use strace to see what it's not finding.
