### ISSUE TITLE
('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)") #717

### ISSUE THREAD

**Issue by svatos-jirka** [mkleehammer/pyodbc#914]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.6.3
- pyodbc: 4.0.30
- OS: Debian Buster 10.2 (docker image FROM Debian:10.2)
- DB:
- driver:

### Issue
Unnable to connect (unable to open lib ODBC driver 17 for SQL Server"

please help.

**Comment by v-chojas** [comment]
Please check:
https://github.com/mkleehammer/pyodbc/issues/878
https://github.com/mkleehammer/pyodbc/issues/775
https://github.com/mkleehammer/pyodbc/issues/717

**Comment by svatos-jirka** [comment]
HI,

it looks like issue on MS side
https://github.com/MicrosoftDocs/sql-docs/issues/6494, most probably you
can close the ticket

st 16. 6. 2021 v 22:58 odesílatel v-chojas ***@***.***>
napsal:
