### ISSUE TITLE
can i off info log when pyodbc.connect?

### ISSUE THREAD

**Issue by shinel94** [mkleehammer/pyodbc#916]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.10
- pyodbc: 4.0.30
- OS: windows 10 
- DB: Machbase
- driver: Machbase ODBC

### Issue

how to off [INFO] Unused connection info (DRIVER) log.
i want not print this INFO log when connect

**Comment by v-chojas** [comment]
That sounds like something the driver does, in which case you'll have to ask the driver vendor about it.
