### ISSUE TITLE
pyodbc.Error: ('37000', '[37000] [OpenLink][Virtuoso ODBC Driver][Virtuoso Server]SQ074: Line 1:  (-1) (SQLExecDirectW)')

### ISSUE THREAD

**Issue by xqx1568** [mkleehammer/pyodbc#918]
Sorry to bother you, but could you give me some help?
My code as bellow:

    cn = pyodbc.connect("DSN=Freebase2;UID=dba;PWD=dba;")

    x =cn.execute(r"PREFIX res: <http://dbpedia.org/resource/> PREFIX dbp: <http://dbpedia.org/property/> select ?uri WHERE { res:Salt_Lake_City <http://dbpedia.org/ontology/timeZone> ?uri }")

    x.commit()

    x.close()

When I test first time it can run successfully, but now it raise an error:
![image](https://user-images.githubusercontent.com/43669838/122700784-84c2c000-d27e-11eb-9a18-37313a77deea.png)
I don not what happen.

**Comment by v-chojas** [comment]
Error is coming from the driver - doesn't look like a pyODBC-related issue.
