### ISSUE TITLE
Connection failure keeps occurring when connected to client/front end application

### ISSUE THREAD

**Issue by stepdata21** [mkleehammer/pyodbc#919]
Hi guys thank you for this awesome library it works perfectly but i've been having an odd issue.

I used pyodbc as my DB connection to build a flask api using flask_restful. I successfully deployed the app and even tested various endpoints on Postman and the API works perfectly.

The API is to serve an Angular dashboard at the front end however whenever the dashboard attempts to fetch data from the API, it returns an error 500 and then I can no longer connect to the API on  Postman unless I restart the API service. 

On inspecting the api service after retrying the API endpoints, these are the errors that come out:

('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (0) (SQLExecDirectW)')
('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: Error code 0x20 (32) (SQLExecDirectW)')

- Python: 3.8
- pyodbc: 4.0.3
- OS: Ubuntu 20.04.2
- DB: MSSQL Server 2019
- driver: ODBC driver 17 for sql server

### Connection details(masked):
server = '1**.***.***.***'
database = 'middleware_db'
username = 'SA'
password = '*********'
driver= '{ODBC Driver 17 for SQL Server}'
connection_string = 'DRIVER={driver};PORT=1433;SERVER={server};DATABASE={database};UID={username};PWD={password}'.format(
    driver=driver, server=server, database=database, username=username, password=password)
cn = pyodbc.connect(connection_string)
cursor = cn.cursor()

Below is a sample code from one of the endpoints (API was built using Flask_restful)
def get(self):
        LF = pd.read_sql_query('''SELECT  COUNT(Id) AS "Tickets Sold",  
                                  COUNT(DISTINCT CustomerId) AS "Customers",
                                  SUM(SellingPrice) AS "Revenue",
                                  SUM(CASE WHEN (Used) = 'True' THEN 1 ELSE 0 END)  AS "Tickets Used"
                        FROM Tickets
                        WHERE DateTimeSold > (SELECT MAX(CAST(DateTimeSold AS DATE)) FROM Tickets)''', cn).to_dict('record')[0]
        return LF
Again I'd like to state that the requests were working until the Angular dashboard tried to pull data from the endpoint.

Thank you in advance for any help.

**Comment by v-chojas** [comment]
Which exact driver version are you using?

**Comment by stepdata21** [comment]
Hi,

ODBC driver version 17 for sql server

**Comment by v-chojas** [comment]
Which exact version of ODBC 17?

**Comment by stepdata21** [comment]
The one for Ubuntu, my bad sorry I didn't understand that earlier

**Comment by v-chojas** [comment]
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/release-notes-odbc-sql-server-linux-mac
Which version?

**Comment by stepdata21** [comment]
Version 17.72

**Comment by v-chojas** [comment]
Could you post an ODBC trace?

**Comment by stepdata21** [comment]
Hi @v-chojas thanks so much for the questions and the time. I just figured out the problem and it wasn't completely related to PyODBC.  The problem was that all my endpoints were sharing one connection, so I decided to use a connection per endpoint triggered. 

Thank you
