### ISSUE TITLE
Issues connecting to SQL server via pyodbc

### ISSUE THREAD

**Issue by kuiperstj** [mkleehammer/pyodbc#921]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.9.5 (UCS4)
- pyodbc: 4.0.30
- OS: Red Hat Enterprise Linux Server release 7.9
- DB: Microsoft SQL Server 2016
- driver: ODBC Driver 17 for SQL Server
- unixODBC:  2.3.7

[odbctrace_isql.log](https://github.com/mkleehammer/pyodbc/files/6711319/odbctrace_isql.log)
[odbctrace_pyodbc.log](https://github.com/mkleehammer/pyodbc/files/6711321/odbctrace_pyodbc.log)

### Issue

I'm having issues connecting to our SQL server via pyodbc.  I am able to connect fine using isql.  I'm using a DSN named TRACY that I had configured in the .ini file.  When I try to connect thru pyodbc I get the response "Memory Fault" and then the process dies.

I uploaded my trace logs for you to view.  I've done a lot of reading on the Unicode articles and anything I can find to read from my various google searches, and I think the issue resides with the UCS4 install I have of Python.  This cannot be changed/reinstalled to be UCS2 and I just can't figure out how to work around this issue.  Any advice you have would be greatly appreciated.

Thank you kindly!

**Comment by v-chojas** [comment]
How are you installing pyODBC? If you have a slightly different Python the prebuilt binaries may not work correctly.

**Comment by kuiperstj** [comment]
All of the software was installed by another group, so I don't know any specifics about how it was installed or why they did things the way they did.  Unfortunately, I don't have any control over that.  I do know that the pyodbc was installed when the latest version of Python (3.9.5) was installed.

**Comment by v-chojas** [comment]
You will need to get that information for further assistance.

**Comment by gordthompson** [comment]
@v-chojas - I wasn't aware that there were pre-built binaries for Linux. https://pypi.org/project/pyodbc/#files certainly doesn't list any.

@kuiperstj - AFAIK, the UCS4/UCS2 thing was only an issue for Python_2 and early versions of Python_3 (< 3.3), so it is not relevant to Python 3.9 *per se*. Does `sys.getdefaultencoding()` return something other than `'utf-8'`?

**Comment by kuiperstj** [comment]
@gordthompson - when I check sys.getdefaultencoding() I get utf-8.

@v-chojas - Is there any way I can check after the install for the information you are looking for?

**Comment by gordthompson** [comment]
@kuiperstj - Output from `sudo dnf info msodbcsql17` would at least give us *something* to work with.

**Comment by kuiperstj** [comment]
@gordthompson - I have extremely limited permissions to do a lot of things on this server with software.  Separation of duties makes my life very hard, even on our development server.  I really appreciate all your help.

I couldn't run the command you provided but I was able to get this information from yum.
msodbcsql17.x86_64                 17.2.0.1-1           @/msodbcsql17-17.2.0.1-1.x86_64

And then I ran rpm -qR command and obtained this data:
$ rpm -qR msodbcsql17-17.2.0.1-1.x86_64
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/bin/sh
e2fsprogs
glibc
krb5-libs
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libcrypto.so.10()(64bit)
libcrypto.so.10(OPENSSL_1.0.1)(64bit)
libcrypto.so.10(libcrypto.so.10)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgssapi_krb5.so.2()(64bit)
libgssapi_krb5.so.2(gssapi_krb5_2_MIT)(64bit)
libkrb5.so.3()(64bit)
libkrb5.so.3(krb5_3_MIT)(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libodbcinst.so.2()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
librt.so.1()(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)
libssl.so.10()(64bit)
libssl.so.10(libssl.so.10)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(CXXABI_1.3.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.19)(64bit)
libuuid.so.1()(64bit)
libuuid.so.1(UUID_1.0)(64bit)
openssl
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)
unixODBC >= 2.3.1
rpmlib(PayloadIsXz) <= 5.2-1

One thing I'm noticing is that this command is saying unixODBC is 2.3.1, but the odbcinst -j command is showing 2.3.7.  
$ odbcinst -j
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /abc/def/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

**Comment by v-chojas** [comment]
The driver requires a _minimum_ of unixODBC 2.3.1. Hence 2.3.7 is acceptable (and better, since it has bugs fixed).

If you can reproduce this issue in your own environment, it will be much easier to investigate. If you can't, and everything works normally, then you can provide this evidence to show how to set up the environment correctly, so they can fix it.

**Comment by kuiperstj** [comment]
@v-chojas - I was just wondering if the driver showing version 2.3.1 and the odbcinst showing 2.3.7 could possible produce some issues.

Also this issue is happening in my main development environment.  We don't have it working on any of our servers.  We're migrating from perl to python, which is why we are now starting to use the pyodbc module.  So all the logs and information I grab is on the environment that I can obtain the most data from, but I'm still limited by not have su access and cannot change/add/remove server software.

When trying to connect to the database using pyodbc, I can't even get to to a login failure.  The script displays a "memory fault" and then just dies.  So even in the trace logs I provided.... they just stop providing data.

**Comment by v-chojas** [comment]
No, that wouldn't be a problem at all. Lots of others use msodbcsql17 with unixODBC 2.3.7.

What I mean is to set up an environment yourself (e.g. in a VM) and try to reproduce it that way.

**Comment by gordthompson** [comment]
@kuiperstj - Further to comment from @v-chojas : FWIW, it looks like you can download a copy of RHEL 7.9 from here

https://developers.redhat.com/products/rhel/download

(under the "View Older Downloads" link).

That, and an install of Oracle VirtualBox (free) means that you could set up a virtual machine for testing on your own workstation.
