### ISSUE TITLE
Cannot read from MS Access 64-bit - "Not a valid file name."

### ISSUE THREAD

**Issue by weeds-pests** [mkleehammer/pyodbc#922]
Using the code from the documentation as a template, I entered:
```
import pyodbc

conn_str = (
    r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};'
    r'DBQ="D:\\Test\\APNI.accdb";'
    )
print(conn_str)
cnxn = pyodbc.connect(conn_str)
crsr = cnxn.cursor()
for table_info in crsr.tables(tableType='TABLE'):
    print(table_info.table_name)
```
The response is:
```
 cnxn = pyodbc.connect(conn_str)
pyodbc.Error: ('HY000', '[HY000] [Microsoft][ODBC Microsoft Access Driver] Not a valid file name. (-1044) (SQLDriverConnect); [HY000] [Microsoft][ODBC Microsoft Access Driver] Not a valid file name. (-1044)')
```
I am running Win 10 64 bit ()
Python 64 bit (3.8.10)
and ms-access 64 bit

Note the code to see if I have 32 bit or 64 bit ms-access drivers also does not work as advertised.

I used the following code to list the drivers:

```
import pyodbc
for x in pyodbc.drivers():
    if x.startswith('Microsoft Access Driver'):
        print(x)
    else:
        print("-" + x)
```

The results were:

```
-SQL Server
-PostgreSQL ANSI(x64)
-PostgreSQL Unicode(x64)
-PostgreSQL ANSI
-PostgreSQL Unicode
Microsoft Access Driver (*.mdb, *.accdb)
-Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)
-Microsoft Access Text Driver (*.txt, *.csv)
```

At a guess, I would say the asterixis in the driver name might be causing the issue?

**Comment by gordthompson** [comment]
Access ODBC is not complaining about the driver name. It's the `DBQ=` file name that's wrong. It shouldn't be enclosed in double-quotes.

Also, while not necessarily incorrect: If you are using a raw string (`r'…'`) then you don't need to double-up the backslashes:

```py
    r'DBQ=D:\Test\APNI.accdb;'
```

**Comment by weeds-pests** [comment]
Removing the escapes for the special characters and changing the quotes for the raw strings worked.  Thank you.
