### ISSUE TITLE
Value returned from query padded with ASCII NULs

### ISSUE THREAD

**Issue by qed-** [mkleehammer/pyodbc#926]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.8
- pyodbc: 4.0.30           
- OS:  rhel 8.4
- DB:  Microsoft SQL Server 2019 
- driver:  unixODBC 2.3.9

### Issue

Table A and table B both have varchar(50) column containing same value 12 character value.
Reading from table A reads the string correctly.
Reading from table B reads the string padded with NUL (ASCII 0) characters.

e.g. 'XXXXXXXXXXXX'
vs 
'XXXXXXXXXXXX\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

Comparing an ODBC trace the only difference I can see is:

Working case:

```
[ODBC][542306][1625761692.470848][SQLGetData.c][545]
		Exit:[SQL_SUCCESS]                
			Buffer = [XXXXXXXXXXXX](unicode)                
			Strlen Or Ind = 0x7ffdca9887d0 -> 24 (64 bits)
```

Not working case:

```
[ODBC][542929][1625762484.688874][SQLGetData.c][545]
		Exit:[SQL_SUCCESS]
			Buffer = [XXXXXXXXXXXX](unicode)
			Strlen Or Ind = 0x7ffd690d0510 -> 100 (64 bits)
```

Running the same query in sql server management studio shows the string corectly, without padding.

**Comment by v-chojas** [comment]
I am over 99% certain the cell actually contains the extra null bytes, from whatever last inserted into it. Select the column casted as varbinary(max) to see that the data is actually in the table. 

> Running the same query in sql server management studio shows the string corectly, without padding

That's because it doesn't show nulls. Try running `select replicate(char(0), 1000)`, or even more enlighteningly, compare `select 'foo'` and `select concat('foo', replicate(char(0), 10)` to convince yourself of this.

**Comment by qed-** [comment]
@v-chojas Thanks for your quick response. You are correct, the field does in fact contain null bytes being hidden from SSMS. The intriguing thing is that these are ignored when joining to the column but are returned from queries. 
Clearly not a problem with pyodbc.
