### ISSUE TITLE
Can't insert datetime to DATE column using fast_executemany=True

### ISSUE THREAD

**Issue by Ptitlaby** [mkleehammer/pyodbc#928]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.30
- OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)
- DB: AWS Redshift (PostgreSQL)
- driver: AWS Redshift

### Issue

Using the code below in python, I am getting the following error when inserting data to a date column in AWS Redshift using pyodbc PostGreSQL driver with the parameter fast_executemany set to true :

[Amazon][Support] (40520) Datetime field overflow resulting from invalid datetime. (40520)

This error is not happening when using the same parameter set to false.

I created two trace, one with the parameter at false, and one with the parameter at true (failing) 
[odbctrace_false.log](https://github.com/mkleehammer/pyodbc/files/6806554/odbctrace_false.log)
[odbctrace_true.log](https://github.com/mkleehammer/pyodbc/files/6806555/odbctrace_true.log)

<details>
<summary>Python code used</summary>
<p>

```python
    import pyodbc
    odbc_string = "DSN=Amazon Redshift DSN 64"
    con = pyodbc.connect(odbc_string)

    from datetime import datetime
    data_true = [(f"fast_executemany {i} = True", datetime.now()) for i in range(1, 3)]

    with con.cursor() as cur:
        sql = "CREATE TABLE IF NOT EXISTS test_datetime ( test VARCHAR, my_date DATE )"
        cur.execute(sql)

        sql_insert = "INSERT INTO test_datetime (test, my_date) VALUES (?, ?)"

        cur.fast_executemany = False
        cur.executemany(sql_insert, data_true)

    con.commit()
```

</p>
</details>

**Comment by v-chojas** [comment]
`datetime.now()` contains both a time and date but you are inserting into a column that only holds a date.

Also, note that not all drivers support fast_executemany.

**Comment by gordthompson** [comment]
I am unable to reproduce your issue with PostgreSQL's own ODBC driver so this must have something to do with Redshift's driver.

**Comment by Ptitlaby** [comment]
Thanks for the feedback.

- Indeed DATE and TIMESTAMP are different datatype on redshift, and while the pyodbc driver is working when putting a datetime python value to a date column, I could understand why it's not working in fastexecute_many mode. I'll give it a try.

- Otherwise, I'll check with Amazon about Redshift's driver. I suppose you used the exact same code @gordthompson ?

Thanks
