### ISSUE TITLE
got error after compiled my python script with pyinstaller

### ISSUE THREAD

**Issue by themeswordpress** [mkleehammer/pyodbc#929]
I got the following error after compiled my python script using pyinstaller

pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.6.so.1.1' : file not found (0) (SQLDriverConnect)")

please keep in your mind that the python script it works without complied it

**Comment by v-chojas** [comment]
That error suggests either the driver or its dependencies are not found.

And Python is an interpreted language, it doesn't need compilation?

**Comment by gordthompson** [comment]
When testing the executable produced by pyinstaller are you testing on the same machine or a different one? If it's a different one does it have msodbcsql installed on it?

**Comment by Solar-Matrix-Core** [comment]
> When testing the executable produced by pyinstaller are you testing on the same machine or a different one? If it's a different one does it have msodbcsql installed on it?

I got a simillar issue, except that the error I got is "Can't open lib 'ODBC Driver 17 for SQL Server': file not found". Both the producing machine and the testing machine have all correctly installed msodbcsql. The testing machine can even normally run the original python script written on producing machine, but cannot run the executable file generated from the producing machine and got error as above.

For some reasons, I need to compile my python script to EXE file for others to use. Is there any case that I need to declare something like PATH on pyodbc or pyinstaller?

**Comment by v-chojas** [comment]
The OP is on Linux but you mention "EXE file" which is Windows so it's not clear what platform you're on.
If you are using Linux then strace can show you which file it is not finding; if you're using Windows, Process Monitor has the same functionality.

**Comment by Solar-Matrix-Core** [comment]
> 

EXE is just an acronym for executable.... platform for both machines are all **linux** (**On Windows I did not get error like this**, the program is functioning normally).

How do I use strace to locate the missing file? I tried `strace -e trace=stat` and I just got a huge log telling me lots of files are missing...

**Comment by gordthompson** [comment]
> EXE is just an acronym for executable

No, `.EXE` is a platform-specific file extension.

> platform for both machines are all **linux**

That is useful information. Please remember to include such details in the future.

**Comment by v-chojas** [comment]
A lot of the files will be searched for in multiple directories, so you should see multiple "file not found" followed by a successful open. Since this error is referring to the driver or one of its dependencies, start looking below the point where libmsodbcsql-17.x.so.y.z is being loaded (exact name depends on driver version).

**Comment by Solar-Matrix-Core** [comment]
> A lot of the files will be searched for in multiple directories, so you should see multiple "file not found" followed by a successful open. Since this error is referring to the driver or one of its dependencies, start looking below the point where libmsodbcsql-17.x.so.y.z is being loaded (exact name depends on driver version).

I still can't make sure what file is missing. I tried use -D option when compiling with pyinstaller, and **I can see libmsodbcsql in the dir where the program is compiled, but the error still exists as above.**

The scripts connecting server are quite simple:

`import pyodbc`
`conn = pyodbc.connect('''DRIVER = {ODBC Driver 17 for SQL Server}; SERVER = xxxxxx; DATABASE = xxxxxx; UID = xxx; PWD = xxx)`
`cursor = conn.cursor()`
`# other scripts`

And there's something I forgot to tell. **When I finished compiling on the producing machine (let's call it machine A), the program can function normally on machine A, but can't run on the testing machine (let's call it machine B)**.  Similarly, the program compiled on machine B can run on machine B, but can't run on machine A.

Do I need to add some addtional configuations or options when I run pyinstaller, or add something in the script?

**Comment by v-chojas** [comment]
I already said above, how you should look for the file that is missing in strace.
And being in the program directory is not the correct place; it depends on where the driver location is specified in odbcinst.ini. Normally that would be in /opt/microsoft/msodbcsql17/lib64/ .

**Comment by Solar-Matrix-Core** [comment]
> I got the following error after compiled my python script using pyinstaller
> 
> pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.6.so.1.1' : file not found (0) (SQLDriverConnect)")
> 
> please keep in your mind that the python script it works without complied it

I solved this out, after countless tries.

While compiling the script with pyinstaller, use `--add-binary` option and add libmsodbcsql-17.x.so.y.z. For example:
`pyinstaller -F main.py --add-binary /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1:.`

And this worked out perfectly for me.

**Comment by gordthompson** [comment]
Thanks for taking the time to come back and post an update, @Solar-Matrix-Core !
