### ISSUE TITLE
Pyodbc package no longer in Pypi 

### ISSUE THREAD

**Issue by btreecat** [mkleehammer/pyodbc#93]
https://pypi.python.org/pypi?%3Aaction=search&term=pyodbc&submit=search

This means that the official way to install Pyodbc (pip install pyodbc) does not currently work. 

One solution would be to just update the documentation. 

Another solution would be to get the package relisted in Pypi. 

Thank you.

**Comment by keitherskine** [comment]
This might very well be related to issue #88.

**Comment by btreecat** [comment]
So it seems the package is in Pypi, but neither their web search nor pip can find it.

**Comment by FlipperPA** [comment]
I got flurry of pyodbc updates recent from Mike K, I wonder if something went awry during that period of activity. I did an install about three hours ago and it happened...

**Comment by mkleehammer** [comment]
Thanks - something is very wrong at pypi -- all of the releases except 2.1.9 were marked as hidden.  Fixed.

**Comment by keitherskine** [comment]
Hi Mike, I think the original issue described by btreecat is still an issue.  If you go to https://pypi.python.org/pypi and search for "pyodbc" in the search box, lots of packages are returned, but not pyodbc.

**Comment by mkleehammer** [comment]
Thanks - I thought that fixed it but apparently not.  This could be a pypi issue:

https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when

I'll keep looking into it.

**Comment by mkleehammer** [comment]
This seems to be fixed now?
