### ISSUE TITLE
Issue connecting to MS SQL Data Warehouse

### ISSUE THREAD

**Issue by GavinReynolds** [mkleehammer/pyodbc#930]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.9
- pyodbc: 4.0.31
- OS: Win Server 2012
- DB: MS Data Warehouse - Analytics Platform Service (APS)
- driver: ODBC Driver 13 for SQL Server

### Issue

Hi, I'm trying to connect to our data warehouse but I am receiving the following error: 

django.db.utils.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Setting DateFormat to ymd is not supported. (104409) (SQLExecDirectW)')

I have come across the following post from someone who was trying to connect to Azure Data Warehouse and it explains DateFormat in SQL Data Warehouse cannot be overridden. 

https://github.com/michiya/django-pyodbc-azure/issues/77

The post was from 2016 where and I have installed the latest version on pyodbc (July 2021). 

Could support for MS APS and also Synapse be included in a future release of pyodbc?

Is there a work around for the time being?

Many thanks.

**Comment by v-chojas** [comment]
This does not appear to be a pyODBC issue, but a Django one.

**Comment by absci** [comment]
I think Azure Data Warehouse might not support `SET DATEFORMAT ymd`.

Comment this line out and install from the source, see if that works for you. 
https://github.com/michiya/django-pyodbc-azure/blob/a902a956e2a492ec349d4637a618183c14216ec7/sql_server/pyodbc/base.py#L352

**Comment by GavinReynolds** [comment]
Hi absci, 
This has worked. Thanks for your help!
