### ISSUE TITLE
Directly assigning keyword argument connstring generates error on pyodbc.connect()

### ISSUE THREAD

**Issue by jmferreirab** [mkleehammer/pyodbc#936]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.2
- pyodbc: 4.0.31
- OS: Windows 10 Version 21H1 (OS Build 19043.1110) 64-bit
- DB: Microsoft SQL Server (localhost)
- driver: {SQL Server} and {ODBC Driver 17 for SQL Server}
- IDE: VS Code with ms-python.python v2021.7.1060902895

### Issue

Unexpected error when calling pyodbc.connect(connstring=my_conn_string) with valid connection string in localhost.

#### Expected behaviour:
- Calling pyodbc.connect(connstring=my_conn_string) generates an usable connection if the connection string is valid.
- Statements pyodbc.connect(connstring=my_conn_string) and pyodbc.connect(my_conn_string) are equivalent.

#### Actual behaviour:
- Statements pyodbc.connect(connstring=my_conn_string) and pyodbc.connect(my_conn_string) are NOT equivalent.
- Calling pyodbc.connect(connstring=my_conn_string) generates an error with a valid connection string.

#####

 ```python
import pyodbc
driver = r'{ODBC Driver 17 for SQL Server}'   #same behaviour with: r'{SQL Server}
server = r'localhost'
database = r'LocalDB' 
username = r'admin' 
password = r'admin' 
conn_string = (f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password};')
conn = pyodbc.connect(connstring=conn_string)    #FAILS TO CONNECT
conn = pyodbc.connect(conn_string)               #CONNECTS SUCCESSFULLY
```

### User workaround:

```Do not specify positional argument 'connstring' when calling pyodbc.connect.```

-----------------------

#### ODBC Drivers

![image](https://user-images.githubusercontent.com/29668777/126908214-f703995d-763c-4077-b153-0c49837723e5.png)

**Comment by jmferreirab** [comment]
It seems this may be by design given the definition of connect method in [https://github.com/mkleehammer/pyodbc/blob/master/src/pyodbc.pyi](url)

Relevant reading on the parameter_list_no_posonly and parameter_list_starargs object which enforce certain arguments to not be passed as keyword arguments or to be passed as such.

https://www.python.org/dev/peps/pep-0457/
https://docs.python.org/3/reference/compound_stmts.html#function-definitions


The error message, however, seems rather misleading. If this is by design, would it be possible to have a more relevant error?

**Comment by keitherskine** [comment]
I take your point, @jmferreirab , but hopefully the new pyodbc.pyi file will provide the necessary guidance on how to call the `connect()` function.

**Comment by mkleehammer** [comment]
To be clear, there is no *keyword* named `connstring`.  The first parameter is named that (at least in the pyi file), but it must be passed without a keyword.  The keywords are in addition to the required connection string.

The C code could be updated to allow a name for the first parameter, but I'm going to pass on that for now.  I will keep it in mind for v5, however.  Thanks.
