### ISSUE TITLE
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by jigisha9** [mkleehammer/pyodbc#938]
I am getting same error
`pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'SQL Server' : file not found (0) (SQLDriverConnect)")
`

VM: Ubuntu latest: 20
python: unixodbc, pyodbc installed

**command**: odbcinst -j
**Result**:
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/vsts/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

**command**: cat /etc/odbcinst.ini
**Result**:
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1

I am able to execute it locally no issues. Its only when i use Azure pipeline using Ubuntu latest VM unable to connect sql server with above error.

**I have tried** with 
ip and host both. 
also, tried with Driver: SQL Server and {ODBC Driver 17 for SQL Server}

  conn = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};'
                                'Server=ip/host;'
                                'Database=xxx;'
                              'Trusted_Connection=yes;'
                              'UID=xxx;'
                              'PWD=xxx')

Then I have also run below commans:
sudo apt-get update
sudo apt-get install -y unixodbc-dev

Now i am seeing below error: 
`pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')`

  - No luck.

**Comment by v-makouz** [comment]
"Login timeout expired" means the server is not accessible for some reason. Can you ping it from that machine? Can you connect to it by other means (such as SSMS)? 

This error can be caused by many things, such as server service not running, firewalls etc.

**Comment by ucop-ocio** [comment]
I am having the same exact issue - our production environment was fine until last Friday. Receiving the same error "pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')". 

Can connect locally, but not on our AWS EC2 instance. We are running an older version of Ubuntu 18.04.5.  Can connect via SSMS. Interested in hearing recommendations for troubleshooting.

**Comment by v-chojas** [comment]
Figure out what changed to cause it. This error is usually related to networking.

**Comment by jigisha9** [comment]
@ucop-ocio 

I had same issue earlier on AWS EC2 VM, Its resolved with below in Python:
```

conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                              'SERVER=' + server + ';'
                              'DATABASE=' + db + ';'
                              'UID=' + user + ';'
                              'PWD=' + pwd)
```


Take out 'Trusted_Connection=yes;' in connection. You don't need on external system.
