### ISSUE TITLE
On Oracle 11g database: Insert on more than one column fails with HY000 error

### ISSUE THREAD

**Issue by ryogesh** [mkleehammer/pyodbc#94]
OS version: CentOS Linux release 7.2.1511 (Core)
Python version: 2.7.5
Pyodbc version : '3.0.10'
Oracle database version: 11.2.0.2.0

Database table definition:
Create table t1 (id1 int, id2 int);

Python script:
cnxn = pyodbc.connect("DRIVER={Oracle};DBQ=host:port/instance;UID=myuser;PWD=mypwd")
crsr = cnxn.cursor()
id1 = 1
id2 = 2
crsr.execute("insert into t1(id1, id2) values(?, ?)", (id1, id2));

fails with
pyodbc.Error: ('HY000', 'The driver did not supply an error!')

However the below statements works:
crsr.execute("insert into t1(id1) values(?)", (id1)); 
crsr.execute("insert into t1(id1, id2) values(1, 2);"); 

Table column type doesn't matter, e.g. the table could have been
Create table t1 (id1 int, txt1 varchar2(10), id2 int);

and the below statement fails, with the same HY000 error
crsr.execute("insert into t1(id, txt1) values(?, ?);" ,(1, 'sample2'))

but this works
crsr.execute("insert into t1(id1, txt1) values(1, 'sample');");

**Comment by mkleehammer** [comment]
Are any of the columns type NUMBER(xxx)?

**Comment by ryogesh** [comment]
There are no number(xxx) columns, all the columns are either integer or varchar2.

**Comment by ryogesh** [comment]
I noticed that on the database when i do a describe, i see the definition of the columns as Number(38).

e.g.
SQL> create table t3(id integer);

Table created.

SQL> desc t3
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ID                                                 NUMBER(38)

**Comment by hindmanj** [comment]
I can confirm this issue.

Environment:
Linux CentOS 7.2.1511
Python 3.5
pyodbc 3.0.10
UnixODBC 2.3.4
Oracle 12.1 Instant Client & ODBC
Oracle 11.2.0.4 DB

Per Oracle, this is likely a limitation in their ODBC driver:
http://docs.oracle.com/cd/E11882_01/server.112/e10839/app_odbc.htm#UNXAR346

Oracle's ODBC driver doesn't support SQL_C_SBIGINT or SQL_C_UBIGINT

Issue exists in their latest ODBC driver as well:
http://docs.oracle.com/database/121/UNXAR/app_odbc.htm#UNXAR352

The workaround is likely to force it to a Decimal or a Float before we pass it to pyodbc, but that is an ugly hack. Not sure there is a better one without sniffing Oracle's ODBC driver somehow.

**Comment by ryogesh** [comment]
Curious, Why does the insert work on 1 column only
i.e. Assuming a table t1 (id1 int, id2 int, id3)

Below works:
cnxn = pyodbc.connect("DRIVER={Oracle};DBQ=host:port/instance;UID=myuser;PWD=mypwd")
crsr = cnxn.cursor()
id1 = 1
id2 = 2
crsr.execute("insert into t1(id1) values(?)", (id1));
 
But more than 1 column insert fails 
crsr.execute("insert into t1(id1, id2) values(?, ?)", (id1, id2));

**Comment by mkleehammer** [comment]
I believe this is fixed by 4.0.8. Good luck.  Please reopen if that is not true.
