### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by shadowmimosa** [mkleehammer/pyodbc#942]
- Python: Python 3.9.6 64-bit
- pyodbc: pyodbc-4.0.31
- OS: Win10

Got error:
  > DLL load failed while importing pyodbc: %1 不是有效的 Win32 应用程序。

Other versions were tried later
- Python: Python 3.8.0 32-bit
- pyodbc: pyodbc-4.0.31
- OS: Win10

Got error:
  > DLL load failed while importing pyodbc: 找不到指定的模块。

**Comment by gordthompson** [comment]
Try downloading the appropriate wheel file from here

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc

and install it with pip, for example

```
pip install pyodbc‑4.0.31‑cp39‑cp39‑win_amd64.whl
```

**Comment by shadowmimosa** [comment]
> Try downloading the appropriate wheel file from here
> 
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc
> 
> and install it with pip, for example
> 
> ```
> pip install pyodbc‑4.0.31‑cp39‑cp39‑win_amd64.whl
> ```

It's strange. I tried this method yesterday, but it didn't work. But now it's OK. thx
