### ISSUE TITLE
ERROR:  No results.  Previous SQL was not a query.

### ISSUE THREAD

**Issue by ShreeshaAck** [mkleehammer/pyodbc#946]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.9
- pyodbc: 4.0.26
- OS: <**AWS Lambda environment**>
- DB: SQL Server
- driver: ODBC Driver 17 for SQL Server

### Issue
We have multiple users in the SQL database and we want to reset the password for some users by using master user login, but when we try to reset the password using the lambda function, it is showing the error as "**ERROR:  No results.  The previous SQL was not a query.**" but other SQL statements(**Select or Insert**) are working as expected rather "**ALTER**"

Here is a code sample:

```
import json
import pyodbc

def lambda_handler(event, context):
    try:
        pyodbc.pooling = False
        conn = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};Server=amazon-rd-endpoint,1433;Database=database_name;Uid=supper_user;Pwd=password;CENSORED;Trusted_Connection=yes;',autocommit=True)
        cursor = conn.cursor()
        
        cursor.execute("ALTER LOGIN second_user WITH PASSWORD = 'newPassword'")
        conn.commit()

        return {
            'statusCode': 200,
        }
    except Exception as e:
        print('ERROR: ', e)
```

**Comment by ShreeshaAck** [comment]
@gordthompson I am trying to make DDL command via pyodbc, hope `.fetchone(), .fetchall()` will work proper with DML command

anyhow I tried `cursor.fetchall()` or `cursor.fetchone()` after the `cursor.execute()` but getting same error **"No results.  Previous SQL was not a query."**

**Comment by v-chojas** [comment]
I am not sure what you are trying to say. In any case, neither me nor Gord are able to reproduce your issue.
What did you expect? The previous SQL was indeed not a query.

**Comment by ShreeshaAck** [comment]
Whenever I perform ALTER queries by using `pyodbc ` I am getting the error "No results. Previous SQL was not a query." so I tried with a different Python module `pymssql`, I don't think so pyodbc will work with Lambda env, so I continue using `pymssql` instead `pyodbc`

I am very sad that you are not able to reproduce your issue. here is the screen-shot which I am getting the error in Lambda: https://picd.in/rJGM6jSw

Also, you can see the status of the lambda function and error message which pyodbc is returning in `try-catch` block

**Comment by v4ld3rr4m4** [comment]
I get this error using the DML comand delete and trying some as mention @ShreeshaAck  fetching the result  . Look my **wrong** code:
`for msg in cursor.execute("DELETE FROM MYTABLE...  "):**
         # using msg here
` 
I found that in core inside execute method  exist  this block:

`	    if (ret == SQL_NO_DATA)
	    {
		// Example: A delete statement that did not delete anything.
		cur->rowcount = 0;
		Py_INCREF(cur);
		return (PyObject*)cur;
	    }`
and when you try to use it thinkind DATA EXIST then fire this another code in Cursor_validate method
`    if (IsSet(flags, CURSOR_REQUIRE_RESULTS) && cursor->colinfos == 0)
    {
        if (flags & CURSOR_RAISE_ERROR)
            PyErr_SetString(ProgrammingError, "No results.  Previous SQL was not a query.");
        return 0;
    }`

So later understand this I just make execute and work with rowcount var of Class Cursor  :+1: 
`cursor.execute("DELETE FROM MYTABLE...  "):**
  # using cursor.rowcount  that could be 0 or more
`

**Comment by ShreeshaAck** [comment]
@v4ld3rr4m4 How this will help me to rectify the error? my problem statement I different, and the thing is if I try to make an `ALTER` statement, pyodbc is throwing the error, unfortunately, the database level query is working but pyodbc is showing an error as "No results. Previous SQL was not a query." also you can refer screenshot which is attached in the previous reply.

**Comment by v-chojas** [comment]
The error comes from line 100 here:

https://github.com/mkleehammer/pyodbc/blob/24e0ccadaec091ce6b1b81e3197a345b895773fc/src/cursor.cpp

...so Cursor_Validate needs to be called with at least CURSOR_REQUIRE_RESULTS and CURSOR_RAISE_ERROR for that to occur. Where does that happen?

- Cursor_iternext
- Cursor_fetchval
- Cursor_fetchone
- Cursor_fetchall
- Cursor_fetchmany
- Cursor_skip

...none of which are called from Cursor_execute, so the error you are getting in this issue is practically _impossible_ given the code you claim to be executing.
