### ISSUE TITLE
Current procedure(s) for connecting to Azure SQL

### ISSUE THREAD

**Issue by gordthompson** [mkleehammer/pyodbc#949]
A PR was recently submitted to SQLAlchemy …

https://github.com/sqlalchemy/sqlalchemy/pull/6968

… proposing an update to the documentation on how to connect to Azure SQL via `mssql+pyodbc://` by using MSAL. However, the documentation it is amending was submitted less than a year ago and there is some confusion as to what the current procedure should be.

The pyodbc wiki already has a description titled "Authenticate using an Access Token from Azure Active Directory"

https://github.com/mkleehammer/pyodbc/wiki/Tips-and-Tricks-by-Database-Platform#authenticate-using-an-access-token-from-azure-active-directory

and I'm wondering if it may need to be expanded (and possibly promoted to be its own article under "Connecting to databases") to clarify the relationship(s) between [azure](https://pypi.org/project/azure/), [azure-identity](https://pypi.org/project/azure-identity/), and [MSAL](https://pypi.org/project/msal/).

**Comment by v-chojas** [comment]
Azure SQL has not changed - you can still authenticate using regular SQL Server auth or any valid AAD access token.
