### ISSUE TITLE
Segmentation fault with ODBC Driver 13 from Microsoft

### ISSUE THREAD

**Issue by DeusSanctum** [mkleehammer/pyodbc#95]
Hello,

I have a trouble connecting to a SQL Server database from Python 3.4 in Linux.

I just do something like that : import pyodbc as odbc

sql_server = odbc.connect("Driver={ODBC Driver 13 for SQL Server};Server=XXX;Database=YYY;Trusted_Connection=Yes") 

An then Ipython crashes, same for standard python.

It is strange because everything is fine in Windows.

Any clue ?
Thanks

**Comment by burnsba** [comment]
Check `ldd` for the installed microsoft library:  

    $ ldd /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0  


If it prepends the output with `version not found` but goes on to find the required libraries, I think that means something internal has changed in version 13 so that it can't link correctly. I couldn't find a solution for this, I downgraded to version 11.  

Output when I run `ldd`:  

    $ ldd /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0
    /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0: /usr/lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found (required by /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0)
    /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0: /usr/lib/x86_64-linux-gnu/libcrypto.so.10: version `libcrypto.so.10' not found (required by /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.0.so.0.0)
            linux-vdso.so.1 (0x00007fff5e7fe000)
            libcrypto.so.10 => /usr/lib/x86_64-linux-gnu/libcrypto.so.10 (0x00007f4ad0d59000)
            libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4ad0b55000)
            librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4ad094c000)
            libssl.so.10 => /usr/lib/x86_64-linux-gnu/libssl.so.10 (0x00007f4ad06e2000)
            libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f4ad04dd000)
            libodbcinst.so.2 => /usr/lib/x86_64-linux-gnu/libodbcinst.so.2 (0x00007f4ad02cb000)

**Comment by meet-bhagdev** [comment]
Hello @burnsba @DeusSanctum Do you still have this issue?

**Comment by mkleehammer** [comment]
Closing due to lack of response.  Please reopen if you have more.
