### ISSUE TITLE
Connection pooling and ANSI

### ISSUE THREAD

**Issue by oalfred** [mkleehammer/pyodbc#950]
Hi

I have a question regarding connection pooling, which I can only get to work if I connect like so `pyodbc.connect(connection_str, ansi=True)`. Now, I have read this issue from September 2018 https://github.com/mkleehammer/pyodbc/issues/283 and I wanted to ask if it is still the case that the workaround with `ansi=True` is necessary in pyodbc due to a bug or missing support in unixODBC. If so, could we get an issue opened on https://github.com/lurcher/unixODBC (if that is the correct place)? I can of course do it myself but I wanted to raise my issue here first since I really don't know much about database drivers and I'm not sure where the problem may lie.

If I may, I would also like to ask if there are any potential risks with using `ansi=True`. With my limited understanding of databases I have not managed to figure out whether it could affect the data that is returned by the database to my python program or if it only affects something more low level that I don't actually need to care about.

For what it's worth, here is some info about my environment and my test code.

python 3.9.6
pyodbc 4.0.32
unixODBC 2.3.9
macOS 11.4

odbcinst.ini:
```
[ODBC]
Pooling=Yes

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/usr/local/lib/libmsodbcsql.17.dylib
UsageCount=9
CPTimeout=30
```

Test code:
```python
import pyodbc

connection_str = '...'

for i in range(0, 10):
    connection = pyodbc.connect(connection_str, ansi=True)
    cursor = connection.cursor()
    cursor.execute('SELECT * FROM sys.dm_exec_sessions')
    row = cursor.fetchone()
    print(row.login_time)
    connection.close()
```

Using `ansi=True` I get the same timestamp in every iteration of the loop, otherwise the timestamp is different each time.

**Comment by v-makouz** [comment]
Basically unixODBC doesn't support connection pooling for wide API (SQLDriverConnectW). By default pyODBC uses the wide version because that allows for Unicode support, setting `ansi=True` forces it to use narrow SQLDriverConnect and so pooling works.

If you don't use Unicode or wide characters `ansi=True` shouldn't be a problem.

**Comment by oalfred** [comment]
Thank you for your reply. I would like to ask for clarification on whether the `ansi` parameter affects how data in the database is read, or if it only affects how the connection string from my python code is interpreted. I don't think there is a problem either way but I want to further my understanding of this topic.

**Comment by v-chojas** [comment]
The ansi parameter to connect() only affects which API pyODBC calls to establish a connection.
Note that the driver is made aware of this (via the SQL_ATTR_ANSI_APP connection attribute) but it's up to the driver to decide whether it wants to change its behaviour based on that.

**Comment by oalfred** [comment]
Thank you for explaining. I have opened an issue on unixODBC so we will see where this goes. I'm closing this here issue since I don't believe there is anything else to do in pyodbc.

**Comment by greatvovan** [comment]
@oalfred I see _"Add connection pooling via wide connection functions"_ was mentioned in 2.3.11 release notes. Thank you for raising the issue with unixODBC.
