### ISSUE TITLE
Drop official support for Python 3.5

### ISSUE THREAD

**Issue by keitherskine** [mkleehammer/pyodbc#954]
It seems about time to drop official support for Python 3.5, which is now quite old.  Besides, the build tests for Python 3.5 have started failing recently, probably in part because pip dropped support for Python 3.5 back in January.  Rather than jerry-rig the unit tests to get them working with 3.5, it seems easiest to just move on.

Related: #857 (note Kleehammer's [comment](https://github.com/mkleehammer/pyodbc/issues/857#issuecomment-766485011))

**Comment by abitrolly** [comment]
Yep, @appveyor upgraded `pip` https://www.appveyor.com/docs/windows-images-software/#visual-studio-2019 to Python 3.5 incompatible version (while still shipping Python 3.5), and now Python 3.5 Windows builds are failing https://ci.appveyor.com/project/mkleehammer/pyodbc/builds/41154018/job/vqfa6d6ednmy8std
