### ISSUE TITLE
Segfault or abort with core dump on TVP passed to SQL Server Stored Procedure containing NULLs

### ISSUE THREAD

**Issue by jrsmiley** [mkleehammer/pyodbc#955]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7.6
- pyodbc: 4.0.32
- OS: Linux
- DB: SQL Sever 2019
- driver: ODBC Driver 17 for SQL Server

### Issue

Expected Behavior
Passing NULL values in a TVP to a stored procedure returns normally when the target table type allows NULLs for the column value.

Observed Behavior
segfault or abort with coredump when passing NULL values for NULLable columns in a TVP to a stored procedure for some, but not all column types.  Specifically, segfault occurs when passing NULL to varbinary(MAX) column and abort with coredump occurs when passing NULL in a float or tinyint column.

**Comment by v-makouz** [comment]
Do you have a repro app (and SQL queries to setup the stored procedure and the like)? I want to try it out and see what's happening.

**Comment by jrsmiley** [comment]
Python app: 

import pyodbc

conn=pyodbc.connect('DSN=MSSQLServerDatabase;UID=JavaUser;PWD=Redacted;DATABASE=JS')
cursor=conn.cursor()
cursor.execute("{CALL JavaTest.HardLoad()}")
rows=cursor.fetchall()
tvp_payload = [["HardTableType", "JavaTest", ] + rows]
cursor.execute("{CALL JavaTest.HardStore(?)}", tvp_payload)
cursor.commit()

**Comment by jrsmiley** [comment]
The app simply calls JavaTest.HardLoad to load a resultset into a TVP and then passes that to JavaTest.HardStore, which will insert any rows that it does not already have.

HardSourceTable
USE [JS]
GO

/****** Object:  Table [JavaTest].[HardSourceTable]    Script Date: 9/14/2021 3:30:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [JavaTest].[HardSourceTable](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SomeText] [sysname] NULL,
	[SomeTiny] [tinyint] NULL,
	[SomeBig] [bigint] NULL,
	[SomeSmall] [smallint] NULL,
	[SomeDate] [date] NULL,
	[SomeTime] [time](7) NULL,
	[SomeDateTime] [datetime] NULL,
	[SomeDateTime2] [datetime2](0) NULL,
	[SomeDateTime3] [datetime2](7) NULL,
	[SomeUnique] [uniqueidentifier] NULL,
	[SomeBinary] [varbinary](200) NULL,
	[SomeBigText] [nvarchar](max) NULL,
	[SomeBigBinary] [varbinary](max) NULL,
	[SomeFloat] [float] NULL,
	[SomeSmallNum] [numeric](8, 2) NULL,
	[SomeNum] [numeric](38, 6) NULL,
	[SomeBit] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

**Comment by jrsmiley** [comment]
USE [JS]
GO
/****** Object:  StoredProcedure [JavaTest].[HardLoad]    Script Date: 9/14/2021 3:33:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   Proc [JavaTest].[HardLoad]
AS
SELECT * FROM JavaTest.HardSourceTable
RETURN 0

**Comment by jrsmiley** [comment]
USE [JS]
GO
/****** Object:  StoredProcedure [JavaTest].[HardStore]    Script Date: 9/14/2021 3:33:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   Proc [JavaTest].[HardStore]
  @ResultSetToStore  JavaTest.HardTableType READONLY
AS
INSERT INTO JavaTest.HardTargetTable
  SELECT * FROM @ResultSetToStore
    WHERE ID not in (select ID from JavaTest.HardTargetTable)
RETURN 0


--*/

exec JavaTest.NewData

DECLARE @TempEasy AS JavaTest.EasyTableType;

DECLARE @RC AS int

INSERT INTO @TempEasy
  EXEC @RC = JavaTest.EasyLoad
  IF (@RC <> 0) PRINT 'ERROR'

EXEC @RC = JavaTest.EasyStore @TempEasy
  IF (@RC <> 0) PRINT 'ERROR'

**Comment by jrsmiley** [comment]
USE [JS]
GO

/****** Object:  Table [JavaTest].[HardTargetTable]    Script Date: 9/14/2021 3:35:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [JavaTest].[HardTargetTable](
	[ID] [int] NOT NULL,
	[SomeText] [sysname] NULL,
	[SomeTiny] [tinyint] NULL,
	[SomeBig] [bigint] NULL,
	[SomeSmall] [smallint] NULL,
	[SomeDate] [date] NULL,
	[SomeTime] [time](7) NULL,
	[SomeDateTime] [datetime] NULL,
	[SomeDateTime2] [datetime2](0) NULL,
	[SomeDateTime3] [datetime2](7) NULL,
	[SomeUnique] [uniqueidentifier] NULL,
	[SomeBinary] [varbinary](200) NULL,
	[SomeBigText] [nvarchar](max) NULL,
	[SomeBigBinary] [varbinary](max) NULL,
	[SomeFloat] [float] NULL,
	[SomeSmallNum] [numeric](8, 2) NULL,
	[SomeNum] [numeric](38, 6) NULL,
	[SomeBit] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

**Comment by jrsmiley** [comment]
USE [JS]
GO

/****** Object:  UserDefinedTableType [JavaTest].[HardTableType]    Script Date: 9/14/2021 3:37:32 PM ******/
CREATE TYPE [JavaTest].[HardTableType] AS TABLE(
	[ID] [int] NOT NULL,
	[SomeText] [sysname] NULL,
	[SomeTiny] [tinyint] NULL,
	[SomeBig] [bigint] NULL,
	[SomeSmall] [smallint] NULL,
	[SomeDate] [date] NULL,
	[SomeTime] [time](7) NULL,
	[SomeDateTime] [datetime] NULL,
	[SomeDateTime2] [datetime2](0) NULL,
	[SomeDateTime3] [datetime2](7) NULL,
	[SomeUnique] [uniqueidentifier] NULL,
	[SomeBinary] [varbinary](200) NULL,
	[SomeBigText] [nvarchar](max) NULL,
	[SomeBigBinary] [varbinary](max) NULL,
	[SomeFloat] [float] NULL,
	[SomeSmallNum] [numeric](8, 2) NULL,
	[SomeNum] [numeric](38, 6) NULL,
	[SomeBit] [bit] NULL
)
GO

**Comment by v-makouz** [comment]
What's the schema for [JavaTest] ?

**Comment by jrsmiley** [comment]
JavaTest is the schema.

**Comment by v-makouz** [comment]
How do I create it?

**Comment by jrsmiley** [comment]
USE [JS]
GO

/****** Object:  Schema [JavaTest]    Script Date: 9/14/2021 4:30:57 PM ******/
CREATE SCHEMA [JavaTest]
GO

**Comment by v-makouz** [comment]
I can't seem to reproduce it, I instead get:
```
cursor.execute("{CALL JavaTest.HardStore(?)}", tvp_payload)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column, parameter, or variable #1: Cannot find data type HardTableType. (2715) (SQLParamData)')
```

If I don't use the schema the app executes without any errors...

**Comment by jrsmiley** [comment]
HardTableType should be in the JavaTest schema.  Is it?  What are you populating tvp_payload with?  The first two rows must point to the location of the data type.  In this case, ("HardTableType", "JavaTest").

What do you mean when you say, "If I don't use the schema.."?

**Comment by jrsmiley** [comment]
Also keep in mind that you need to have NULL values in HardSourceTable for SomeBigBinary, SomeFloat, or SomeTiny.

**Comment by jrsmiley** [comment]
When the SP executes successfully, both HardSourceTable and HardTargetTable will have the same contents.

**Comment by jrsmiley** [comment]
Any progress?

**Comment by v-makouz** [comment]
When I try to reproduce it, I get 
```
[HY004] [Microsoft][ODBC Driver 17 for SQL Server]Invalid SQL data type (0) (SQLBindParameter)
```

When trying to copy a table that has NULLs for SomeBigBinary, SomeFloat, and SomeTiny. That's if I don't use JavaTest schema, and create the tables and stored procedures in default dbo schema. Otherwise I get that "type not found" error, so I still can't seem to get the segfault.

**Comment by jrsmiley** [comment]
Please paste your Python code here.

**Comment by v-makouz** [comment]
My Python code:
```
import pyodbc

conn=pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER=***;UID=***;PWD=***;DATABASE=JS')
cursor=conn.cursor()
cursor.execute("{CALL JavaTest.HardLoad()}")
rows=cursor.fetchall()
tvp_payload = [["HardTableType", "JavaTest", ] + rows]
cursor.execute("{CALL JavaTest.HardStore(?)}", tvp_payload)
cursor.commit()
```

**Comment by jrsmiley** [comment]
This line tells pyodbc to look for the data table type named HardTabletype in JavaTest, so you must have it defined there and used by JavaTest.HardStore.

tvp_payload = [["HardTableType", "JavaTest", ] + rows]

**Comment by jrsmiley** [comment]
Also, which version of Python are you using?

**Comment by v-makouz** [comment]
I have JavaTest defined and and created HardTableType like so: `CREATE TABLE [JavaTest].[HardTableType] ....`

I tried with a few Python versions, but mostly Python 3.9.6

**Comment by gordthompson** [comment]
I am unable to recreate the test environment. After creating the tables, table type, and stored procedures, when I try the `INSERT INTO` in the previous post I get

> (0 rows affected)
> Msg 2628, Level 16, State 1, Line 3
> String or binary data would be truncated in table 'JS.JavaTest.HardSourceTable', column 'SomeBinary'. Truncated value: ''.
> The statement has been terminated.

That is because the `varbinary` and `nvarchar` columns do not specify a width, so it defaults to 1.

**Comment by gordthompson** [comment]
Even after fixing the DDL for the tables and table-type to use

```sql
	[SomeBinary] [varbinary](5) NULL,
	[SomeBigText] [nvarchar](max) NULL,
	[SomeBigBinary] [varbinary](max) NULL,
```

and successfully populating the [HardSourceTable] I just get

> [HY004] [Microsoft][ODBC Driver 17 for SQL Server]Invalid SQL data type (0) (SQLBindParameter)

as @v-makouz mentioned [above](https://github.com/mkleehammer/pyodbc/issues/955#issuecomment-925359704)
