### ISSUE TITLE
text truncated with Filemaker

### ISSUE THREAD

**Issue by sebastianelsner** [mkleehammer/pyodbc#956]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.9.6
- pyodbc: 4.0.32
- OS: Windows 10
- DB: Filemaker 12
- driver: Filemaker ODBC

### Issue

Hello!

I am connecting to a filemaker odbc data source like so:

```python
import pyodbc
connection = pyodbc.connect("DSN=cura;UID=admin;PWD=123)
cursor = connection.cursor()
for row in cursor.execute("SELECT id, textcol FROM table"):
    print(row)
```

It appears the textcol data is truncated to 2047 cutting text off mid-word.

I found this ticket https://github.com/mkleehammer/pyodbc/issues/835 which mentions the same "limit", but I cannot make much of it.

I have checked the driver's docs and settings, it has a toggle for "Describe text fields as long varchar". But it does not change behaviour. 

I tested with the pywin32 odbc module and it returns the correct text, so I assume this is an issue in pyodbc since pywin32.odbc works with the same data source.

Maybe you have a pointer what I could check to debug?

Thank you!

**Comment by gordthompson** [comment]
Please generate an [ODBC trace log](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) and upload it as an attachment to a comment.

**Comment by sebastianelsner** [comment]
Thanks! I have created one.

I guess the relevant part is:

```
flask           d40-310	EXIT  SQLGetData  with return code 1 (SQL_SUCCESS_WITH_INFO)
		HSTMT               0x00000272224CB3B0
		UWORD                        2 
		SWORD                       -8 <SQL_C_WCHAR>
		PTR                 0x0000027225C77CA0 [    4096] ""
		SQLLEN                  4096
		SQLLEN *            0x000000C6B03EB8D0 (4640)

		DIAG [01004] [FileMaker][FileMaker] String data, right-truncated (0) 
```

I have attached the full log of one query: [SQL.LOG](https://github.com/mkleehammer/pyodbc/files/7178739/SQL.LOG)

**Comment by v-chojas** [comment]
Driver bug. pyODBC sees the truncation and makes another call to SQLGetData to retrieve the next block of 4k, but the driver returns no more data.

https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function#retrieving-variable-length-data-in-parts

**Comment by sebastianelsner** [comment]
Hm, I now tested with a newer driver from a Filemaker version, which is not supposed to be compatible (thats why I did not test tat before).... Now I get the whole text. Seems to work! Thank you!
