### ISSUE TITLE
Missing cp39-win32.whl

### ISSUE THREAD

**Issue by imba-tjd** [mkleehammer/pyodbc#960]
See https://pypi.org/project/pyodbc/#files

There are `pyodbc-4.0.32-cp38-cp38-win32.whl` and `pyodbc-4.0.32-cp39-cp39-win_amd64.whl` but there isn't a `pyodbc-4.0.32-cp39-cp39-win32.whl`

Shall we add it? Or do you drop it on purpose?

Other people also mentioned in https://github.com/mkleehammer/pyodbc/issues/833

**Comment by keitherskine** [comment]
Yes it's true, that wheel is not on PyPi, but if it helps, there are unofficial 32-bit wheels here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc
