### ISSUE TITLE
Is the M1 version got released ?

### ISSUE THREAD

**Issue by sujiplr** [mkleehammer/pyodbc#963]
Is the M1 version got released ?

I'm getting below error on my M1 . 

  creating build/lib.macosx-10.9-universal2-3.9
  g++ -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g -L/opt/homebrew/opt/msodbcsql17@17.8.1.1/lib -I/opt/homebrew/opt/msodbcsql17@17.8.1.1/include build/temp.macosx-10.9-universal2-3.9/src/buffer.o build/temp.macosx-10.9-universal2-3.9/src/cnxninfo.o build/temp.macosx-10.9-universal2-3.9/src/connection.o build/temp.macosx-10.9-universal2-3.9/src/cursor.o build/temp.macosx-10.9-universal2-3.9/src/errors.o build/temp.macosx-10.9-universal2-3.9/src/getdata.o build/temp.macosx-10.9-universal2-3.9/src/params.o build/temp.macosx-10.9-universal2-3.9/src/pyodbccompat.o build/temp.macosx-10.9-universal2-3.9/src/pyodbcdbg.o build/temp.macosx-10.9-universal2-3.9/src/pyodbcmodule.o build/temp.macosx-10.9-universal2-3.9/src/row.o build/temp.macosx-10.9-universal2-3.9/src/textenc.o -L/usr/local/lib -lodbc -o build/lib.macosx-10.9-universal2-3.9/pyodbc.cpython-39-darwin.so
  ld: library not found for -lodbc
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/bin/g++' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyodbc

_Originally posted by @sujiplr in https://github.com/mkleehammer/pyodbc/issues/870#issuecomment-934438368_

**Comment by v-chojas** [comment]
Please ensure you have install the ARM version of unixODBC first.

**Comment by mkleehammer** [comment]
These are the macosx ARM wheels I believe.  Please reopen if that is not correct.
