### ISSUE TITLE
'08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection (0) (SQLDriverConnect)'

### ISSUE THREAD

**Issue by ciuliene** [mkleehammer/pyodbc#967]
### Environment

- Python: 3.9.7
- pyodbc: 4.0.30
- OS: macOS BigSur 11.6
- driver: ODBC Driver 17 for SQL Server

### Issue
My app worked until yesterday (14th October 2021)
After updating brew and packages, when I try to connect to SQL Server, this error is thrown:
'08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection (0) (SQLDriverConnect)'

### Expected behavior
Established connection

### Observed behavior
This statement throws the error: 
`pyodbc.connect(connection_settings) `

**Comment by FyZzyss** [comment]
I got ln: `/usr/local/opt/openssl: No such file or directory` and `which openssl` shows: `/usr/bin/openssl` Instead of `/usr/local/opt/openssl`. How to fix this?

**Comment by v-chojas** [comment]
ODBC Driver for SQL Server version 17.9 and later support OpenSSL 3.
