### ISSUE TITLE
InterfaceError [Microsoft] [ODBC Driver Manager] Data source name not found and no default driver specified

### ISSUE THREAD

**Issue by mookjais** [mkleehammer/pyodbc#971]
- Python: 3.9.7 (32-bit) 
- pyodbc: 4.0.28
- OS: Window 10 Enterprise 64-bit
- DB: MsAccess 365 16.0
- driver: Microsoft Access Driver (*.mdb, *.accdb)

**Observed behavior**: When I connect the database in VS Code, the connection is made & there are no errors, but when I compile the code into an .exe file w/ pyinstaller, I get the following error.

<class 'pyodbc.InterfaceError'> ('IM002', '[IM002] [Microsoft] [ODBC Driver Manager] Data source name not found and no default driver specified (0) (SqlDriverConnect)') 

Here is the connection string: 
`conn_str = (r"DRIVER=Microsoft Access Driver (*.mdb, *.accdb); DBQ="networkdrive\myDb.accdb;")
conn = pyodbc.connect(conn_str)
crsr = conn.cursor()
`

**Expected Behavior**: Connection to the database is made successfully

**Comment by mookjais** [comment]
I uninstalled Python & reinstalled & this fixed the issue

**Comment by MehmetUzel** [comment]
> Try creating an executable using the same procedure as your example above except that the python code to run is
> 
> ```python
> import pyodbc
> 
> print(pyodbc.drivers())
> ```

This saved my 4 days thank you very much
