### ISSUE TITLE
Cannot install on jupyter/scipy-notebook:python-3.9.7

### ISSUE THREAD

**Issue by paoloalba** [mkleehammer/pyodbc#975]
here in the following my docker file:

FROM jupyter/scipy-notebook:python-3.9.7

USER root

RUN apt-get update

RUN apt-get install curl -y
RUN apt-get install -y gnupg2

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN exit

RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17

RUN apt-get install -y --no-install-recommends \
    unixodbc-dev \
    unixodbc \
    libpq-dev

RUN pip install pyodbc

USER jovyan

RUN pip install nb_black
RUN pip install xmltodict
RUN pip install pyarrow

CMD ["jupyter", "lab", "--ip", "0.0.0.0"]

in the following the error at building time:

=> ERROR [11/14] RUN pip install pyodbc                                                                                                                                                                                                3.9s
------
 > [11/14] RUN pip install pyodbc:
#14 0.685 WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
#14 1.014 Collecting pyodbc
#14 1.234   Downloading pyodbc-4.0.32.tar.gz (280 kB)
#14 1.406   Preparing metadata (setup.py): started
#14 1.739   Preparing metadata (setup.py): finished with status 'done'
#14 1.742 Building wheels for collected packages: pyodbc
#14 1.743   Building wheel for pyodbc (setup.py): started
#14 2.062   Building wheel for pyodbc (setup.py): finished with status 'error'
#14 2.062   ERROR: Command errored out with exit status 1:
#14 2.062    command: /opt/conda/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mf85wgw8
#14 2.062        cwd: /tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/
#14 2.062   Complete output (9 lines):
#14 2.062   running bdist_wheel
#14 2.062   running build
#14 2.062   running build_ext
#14 2.062   building 'pyodbc' extension
#14 2.062   creating build
#14 2.062   creating build/temp.linux-x86_64-3.9
#14 2.062   creating build/temp.linux-x86_64-3.9/src
#14 2.062   gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -DPYODBC_VERSION=4.0.32 -I/opt/conda/include/python3.9 -c src/buffer.cpp -o build/temp.linux-x86_64-3.9/src/buffer.o -Wno-write-strings
#14 2.062   error: command 'gcc' failed: No such file or directory
#14 2.062   ----------------------------------------
#14 2.062   ERROR: Failed building wheel for pyodbc
#14 2.063   Running setup.py clean for pyodbc
#14 2.316 Failed to build pyodbc
#14 3.202 Installing collected packages: pyodbc
#14 3.204     Running setup.py install for pyodbc: started
#14 3.511     Running setup.py install for pyodbc: finished with status 'error'
#14 3.511     ERROR: Command errored out with exit status 1:
#14 3.511      command: /opt/conda/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ixlo6h8v/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.9/pyodbc
#14 3.511          cwd: /tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/
#14 3.511     Complete output (11 lines):
#14 3.511     running install
#14 3.511     /opt/conda/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
#14 3.511       warnings.warn(
#14 3.511     running build
#14 3.511     running build_ext
#14 3.511     building 'pyodbc' extension
#14 3.511     creating build
#14 3.511     creating build/temp.linux-x86_64-3.9
#14 3.511     creating build/temp.linux-x86_64-3.9/src
#14 3.511     gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC -DPYODBC_VERSION=4.0.32 -I/opt/conda/include/python3.9 -c src/buffer.cpp -o build/temp.linux-x86_64-3.9/src/buffer.o -Wno-write-strings
#14 3.511     error: command 'gcc' failed: No such file or directory
#14 3.511     ----------------------------------------
#14 3.512 ERROR: Command errored out with exit status 1: /opt/conda/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7ou4m3d0/pyodbc_f7360841345e48a999efd9c66e8ace43/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ixlo6h8v/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.9/pyodbc Check the logs for full command output.
------
executor failed running [/bin/bash -o pipefail -c pip install pyodbc]: exit code: 1

the installation of pyodbc worked using jupyter/scipy-notebook:python-3.9.4 instead. The installation seems to have stopped working as of jupyter/scipy-notebook:python-3.9.5. I tried having a look at the differences in the layers between the two images, and apart the conda version, they seem to be the same except for the declaration of ARG miniforge_installer=Mambaforge-4.10.1-4-Linux-x86_64.sh

**Comment by v-chojas** [comment]
> error: command 'gcc' failed: No such file or directory

Try installing gcc first...?

**Comment by paoloalba** [comment]
> > error: command 'gcc' failed: No such file or directory
> 
> Try installing gcc first...?

Already done and the error message stays the same...?

**Comment by v-chojas** [comment]
What do you get if you run gcc --version ?

**Comment by paoloalba** [comment]
I solved it updating the gcc library to 9.3.0, probably there was some corrupted dependency or similar
