### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [mkleehammer/pyodbc#977]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/pyodbc/lokal -name '*.py')
```

How do you think about to improve eight source code places? :thinking:

**Comment by v-chojas** [comment]
Feels like spam. pyODBC isn't even written in Python.

**Comment by elfring** [comment]
@v-chojas: How does your comment fit to the language statistic at the moment?
Python: 63.5%

**Comment by v-chojas** [comment]
Did you look at the source? Does this look like Python to you? https://github.com/mkleehammer/pyodbc/tree/master/src

**Comment by gordthompson** [comment]
@elfring - Thanks for your suggestion, but the Python parts of pyodbc are really just the tests. There is no need to do any fancy optimization of them as long as they properly test the C++ code in pyodbc itself.
