### ISSUE TITLE
Failed login issue with pyodbc connect

### ISSUE THREAD

**Issue by shaunster666** [mkleehammer/pyodbc#978]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6
- pyodbc: 4.0.32
- OS: Centos 7
- DB: MSSQL SE 14.00.3381.3.v1
- driver: Microsoft ODBC Driver 17 for SQL Server v17.7.2.1

### Issue

Correct connection string for use with Microsoft ODBC Driver 17 for SQL Server

I encounter this error: 

"Login failed for user 'administrator'. (18456) (SQLDriverConnect) when I use this connection string"

when I use this connection stanza:

    cnxn = pyodbc.connect(
      SERVER="myhost.eu-west-1.rds.amazonaws.com",
      DATABASE="DWH_DT_BI",
      UID="administrator",
      PWD='xxxxxx',
      DRIVER='{ODBC Driver 17 for SQL Server}',
      Trusted_Connection="no"
    )

I think there is something wrong with this stanza, please could you advise how to correct this?

If I use this sqlcmd the connection is established successfully with the same credentials

/opt/mssql-tools/bin/sqlcmd -S myhost.eu-west-1.rds.amazonaws.com -Uadministrator -Pxxxxxx

**Comment by keitherskine** [comment]
Hi, it would be great to see the whole error string, if you still have it.

Just a guess, but if you leave off the DATABASE parameter from the `connect()` call, does that work?

Also, does the AWS portal for RDS instances provide the ODBC connection string for each instance?  (Azure certainly does this.)  If so, you could try using that, i.e. `pyodc.connect('aws_rds_conn_string')`.

**Comment by shaunster666** [comment]
Hi Keith,

Thank you so much for such a prompt response, much appreciated

I removed the DATABASE parameter but still no joy:

pyodbc.InterfaceError: ('28000', "[28000] [unixODBC][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'administrator'. (18456) (SQLDriverConnect)")

I will contact AWS and ask if an ODBC connection string is available for this RDS instance

**Comment by keitherskine** [comment]
Good to know what the issue was, @shaunster666 .  Thanks for sharing.

**Comment by rpardee** [comment]
> > I've traced this problem to an errant meta char in the password which the driver cannot process, so please close.
> 
> @shaunster666 did you have a hash symbol (#) or single or doble qute character in the password? or other language symbol?

Is there somewhere a complete list of the chars that are no good in a password? I've seen references to curly braces & semicolons, but are there others?
