### ISSUE TITLE
Release python 3.10 win wheels for pyodbc

### ISSUE THREAD

**Issue by SimoneD89** [mkleehammer/pyodbc#981]
Is it possible to add python 3.10 win wheels for pyodbc 4.0.32?

I know that there are unofficial wheels as a workaround (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyodbc)

**Comment by bernd-wechner** [comment]
Thanks for the workaround.

**Comment by thaibee** [comment]
I found the solution! It's problem with Microsoft products.
Very easy to solve - and I think MS should add this info to all their products.
If you can't install these plugins as well,
need to download it from other repositories like this one:
https://www.lfd.uci.edu/~gohlke/pythonlibs/ depends on the version of python and the system. 
for example: for my windows 11(x64) and python 3.10 I took this file: pyodbc‑4.0.32‑cp310‑cp310‑win_amd64.whl
it's very easy to install: pip install pyodbc‑4.0.32‑cp310‑cp310‑win_amd64.whl
after it system works well and didn't ask you about VC.
This solution I found in problem with the MySql plugin for Django. I don't understand why - but they also use VC for the installation process. People also are in shock with the recommendation to install Studio with 16 GB with unusable information! 
Microsoft team!!! Please stop doing it!!! Why for all your product we should be finding a solution for installation? It's a quest?

**Comment by myamullaciencia** [comment]
if we downgrade python from 3.10 to 3.7 would pyodbc be installed successfully

**Comment by MajorWin** [comment]
+1

**Comment by eraliabd** [comment]
This error originates from a subprocess, and is likely not a problem with pip

**Comment by tf-nvoisin** [comment]
+1

**Comment by dileivas** [comment]
+1

**Comment by mkleehammer** [comment]
Uploaded.  It is now added to my Windows build laptop so it will be there from now on.

However, the next thing I'd like to do is make a stable ABI build so future versions simpy work.  (That doesn't mean I don't want to make new builds; I just want to move work to version 5 and have 4.x continue to work for people while 5 is being stabilized.)

**Comment by lineshopping** [comment]
This guy saved me https://whodeenie.medium.com/installing-pyodbc-and-unixodbc-for-apple-silicon-8e238ed7f216
