### ISSUE TITLE
Cannot change 'timeout' property of connection

### ISSUE THREAD

**Issue by ilookhandsometoday** [mkleehammer/pyodbc#984]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.10
- pyodbc: 4.0.32
- OS: Linux Mint 20.1 Ulyssa 
- DB: MS SQL Server (don't know the year)
- driver: ODBC Driver 17 for SQL Server

### Issue
import pyodbc
connection = pyodbc.connect('Driver={ODBC Driver 17 for SQL Server};Server=host;Database=db;Uid=user;Pwd=pwd')
connection.timeout = 0.5
print(connection.timeout)

expected behaviour - timeout property of connection changes
observed behaviour - timeout property does not change

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by v-chojas** [comment]
https://github.com/mkleehammer/pyodbc/blob/master/src/connection.cpp#L1071
Timeout is an integer.

**Comment by gordthompson** [comment]
Confirmed that this works correctly when timeout is specified as an integer value.

```
>>> import pyodbc
>>> connection = pyodbc.connect("DSN=mssqlLocal")
>>> connection.timeout
0
>>> connection.timeout = 1
>>> connection.timeout
1
```
