### ISSUE TITLE
can not insert None in DB

### ISSUE THREAD

**Issue by selfcs** [mkleehammer/pyodbc#986]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.7.5
- pyodbc:  4.0.0
- OS: Linux x86_64
- DB: inceptor (like Hive)
- driver:  odbc2.3.4

### Issue

I'm insert None what it's faild 

mycode:
```python
cursor.execute("INSERT INTO user_info(uid, name) VALUES (?,?)", (1, None))
```
the error is
```text
pyodbc.Error:('HY000','[HY000] record count less than QuestionMarkNum (517) (SQLEXecDirectW)')
```

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by v-chojas** [comment]
Please post an ODBC trace.

**Comment by selfcs** [comment]
`/tmp/odbc.log` is
```
ODBCStatement.cpp:1023 "0x55923806f2d8"
./../../ODBC4HiveServer2/include/ODBCObject.h:75  "record count less than QuestionMarkNum "
```

**Comment by v-chojas** [comment]
That doesn't help. We need the full trace to see why that's happening.
