### ISSUE TITLE
cannot use fast_executemany with Informix ODBC driver

### ISSUE THREAD

**Issue by knight-ni** [mkleehammer/pyodbc#989]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

- Python: 3.9
- pyodbc: 4.0.32
- OS: centos 7.8 (64-bit)
- DB: informix
- driver: odbc for informix  iclit09b.so

### Issue
when setting cursor.fast_execmany = True , will cause core dump or Memory Error 
is there any way to insert by bulk rather than row by row as without fast_execmany did

**Comment by v-chojas** [comment]
Not all ODBC drivers support the array binding (or even implement it correctly) required to use fast_executemany. You will need to ask your ODBC driver vendor for more information.

**Comment by gordthompson** [comment]
You might try [Turbodbc](https://turbodbc.readthedocs.io/en/latest/index.html).

**Comment by PyodbcUnix** [comment]
@knight-ni is it possible for you to connect to informix with pyodbc version bigger than 5.x.x and the unicode version SQLDriversConnectW() function?
