### ISSUE TITLE
 [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection (0) (SQLDriverConnect)'

### ISSUE THREAD

**Issue by altintashalitmert** [mkleehammer/pyodbc#994]
### Environment

- Python: 3.10.1
- pyodbc: 4.0.32
- OS: macOS Big Sur 11.6.1
- DB: SQL Server
- driver: ODBC Driver 17 for SQL Server

### Issue
Hi, when I try to connect to SQL Server, this error is thrown:
'08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection (0) (SQLDriverConnect)', i have readed this issue https://github.com/mkleehammer/pyodbc/issues/967 and move to openssl the location but still can't connect to server.

### ls -l /usr/local/opt/openssl/lib :
<img width="565" alt="resim" src="https://user-images.githubusercontent.com/88205389/147283349-6d953066-d781-49e1-bff1-f8f38abf4ecc.png">

### ls -l /usr/local/opt/openssl@1.1/lib :
<img width="652" alt="resim" src="https://user-images.githubusercontent.com/88205389/147283608-5f9928b0-ffd6-49c6-9417-dc161b95ef1f.png">

**Comment by gizmo93** [comment]
I had the same problem and nothing in https://github.com/mkleehammer/pyodbc/issues/967 worked.
I ended with setting this environment variable when launching my script:

DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1l_1/lib/: $DYLD_LIBRARY_PATH

and now it works.

**Comment by altintashalitmert** [comment]
> I had the same problem and nothing in #967 worked. I ended with setting this environment variable when launching my script:
> 
> DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1l_1/lib/: $DYLD_LIBRARY_PATH
> 
> and now it works.

how can i do it?

**Comment by gizmo93** [comment]
@altintashalitmert 
Either set it using os.environ inside Python before you import pyodbc or set it for example in your IDE before running your code. If you are using PyCharm: https://stackoverflow.com/questions/42708389/how-to-set-environment-variables-in-pycharm

**Comment by dragnblow** [comment]
@v-chojas and @david-engel

![image](https://user-images.githubusercontent.com/94332384/150604581-5ed98668-0703-4516-b128-56efbc4ca670.png)
via isql

which openssl
![image](https://user-images.githubusercontent.com/94332384/150604688-06ad1dc8-21b1-47dd-8ee6-ae0c779fc7de.png)

openssl version
![image](https://user-images.githubusercontent.com/94332384/150604744-08935105-680d-4147-ae2b-c2c5e618faea.png)

Error:
![image](https://user-images.githubusercontent.com/94332384/150604854-c5bf3f5d-ae02-44ba-b312-17c4b0af9a9c.png)

**Comment by v-chojas** [comment]
That one does not appear to be OpenSSL-related. Timeout error is usually because you are not connecting to the right server, or it's not listening, or a firewall is in the way. In any case, it is a networking issue.

**Comment by dragnblow** [comment]
@v-chojas this works with no errors on a windows machine :( 

same code, same service accts, same hostname and db

**Comment by v-chojas** [comment]
Are you able to at least ping the server from the machine you're getting the connection errors?
Does the server have a firewall that is not allowing the connection?

**Comment by dragnblow** [comment]
I can ping the server and get the following output:
![image](https://user-images.githubusercontent.com/94332384/150611337-4b55a514-447b-4531-871a-3d9871c56022.png)

**Comment by dragnblow** [comment]
@v-chojas and David-Engel

I get the correct error now (All I did is remove the '<>' from my connection string. 

![image](https://user-images.githubusercontent.com/94332384/150612200-17545706-b504-4467-8f46-58a8851c4183.png)

Thank you!

**Comment by v-chojas** [comment]
Now you can go to https://github.com/microsoft/homebrew-mssql-release/issues/59 to apply the workaround.

**Comment by dragnblow** [comment]
ln -s /usr/local/Cellar/openssl@1.1/1.1.1l /usr/local/opt/openssl 

@v-chojas this you mean? Sorry!

**Comment by dragnblow** [comment]
@v-chojas - I tried to do the above (running the 'ln -s /usr/local/Cellar/openssl@1.1/1.1.1l /usr/local/opt/openssl'

and did 'rm /usr/local/opt/openssl'
<img width="349" alt="(base) h54615@C02DG42MML85 ~  which openssl" src="https://user-images.githubusercontent.com/94332384/150812844-e40d2b00-aec9-4334-a417-b4e732335ecd.png">

I still get the same error:
![image](https://user-images.githubusercontent.com/94332384/150813022-57147fa9-fdbd-42f7-8b25-34ede53a649f.png)

**Comment by dragnblow** [comment]
Okay @v-chojas . sorry about the confusion, I still get the same library not loaded error :(

**Comment by dragnblow** [comment]
@v-chojas - Success (please find the screenshot below):
![image](https://user-images.githubusercontent.com/94332384/150817813-d345369c-4287-4811-98f6-985ede1865fb.png)

Solution for above: 
![image](https://user-images.githubusercontent.com/94332384/150818074-ad4c2e71-f744-4f83-a95a-570d2e3f3251.png)


but I get the same error using my python script:
![image](https://user-images.githubusercontent.com/94332384/150817985-24abedff-9e6f-4d98-99d3-0c6067aa1cdf.png)

**Comment by dragnblow** [comment]
this now!

![image](https://user-images.githubusercontent.com/94332384/150819808-a088eb5c-e8fd-4773-b35f-edcba7835edf.png)

**Comment by dragnblow** [comment]
@v-chojas - I am all set, just restarted my machine and i can connect now. 

Solution: ln -s /usr/local/Cellar/openssl@1.1/1.1.1l/m /usr/local/opt/openssl

**Comment by aravindk-ecs** [comment]
@dragnblow does this if you are on linux machine we have to confirm what SSL version it's using to connect to SQL 2019 server?
